# Scraper Tempat Makan & Wisata Viral di Indonesia (6 Bulan Terakhir)

Notebook ini melakukan scraping berita dari **Google News RSS** (bahasa Indonesia) untuk mencari artikel tentang tempat makan/wisata yang sedang viral dalam 6 bulan terakhir, lalu mengekstrak:

- Nama tempat
- Lokasi (kelurahan, kecamatan, kota/kabupaten, provinsi) + latitude/longitude (via geocoding OpenStreetMap Nominatim)
- Sejak kapan viral (perkiraan dari tanggal berita/isi artikel)
- Kenapa viral (kalimat yang mengandung alasan viral)
- Sumber berita (judul, link, tanggal publish)

## Catatan penting
- Ekstraksi nama tempat, lokasi, dan alasan viral memakai **heuristik berbasis regex**, bukan NLP/NER penuh, karena berita berbahasa Indonesia sangat bervariasi formatnya. Hasil disarankan **dicek/dibersihkan manual** sebelum dipakai untuk keperluan resmi.
- Geocoding memakai **Nominatim (OpenStreetMap)** yang gratis tapi ada batas 1 request/detik dan mewajibkan `user_agent` yang jelas. Untuk kebutuhan volume besar/produksi, pertimbangkan pakai Google Maps Geocoding API (berbayar) untuk akurasi lebih baik.
- Gunakan data ini untuk riset/analisis internal. Selalu cek Terms of Service situs sumber sebelum melakukan scraping berskala besar.

In [3]:
import json
import re
import time
import urllib.parse
from datetime import datetime, timedelta, timezone

import feedparser
import pandas as pd
import requests
from bs4 import BeautifulSoup
from dateutil import parser as dateparser
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
from googlenewsdecoder import gnewsdecoder
from tqdm.auto import tqdm
import os
import glob

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    )
}

c:\Users\PC NEVIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
# KEYWORDS = [
#     "tempat makan viral",
#     "kuliner viral",
#     "cafe viral",
#     "restoran viral",
#     "wisata viral",
#     "destinasi wisata viral",
#     "spot wisata viral",
#     "tempat wisata baru viral",
# ]

# MONTHS_BACK = 6           # rentang waktu maksimal (bulan)
# MAX_ITEMS_PER_KEYWORD = 25  # batas jumlah artikel per keyword dari RSS
# REQUEST_DELAY = 1.0        # jeda antar request (detik) - sopan ke server

# CUTOFF_DATE = datetime.now(timezone.utc) - timedelta(days=30 * MONTHS_BACK)
# print("Ambil artikel sejak:", CUTOFF_DATE.date())

In [5]:
BASE_KEYWORDS = [
    "tempat makan viral",
    "tempat makan enak",
    "kuliner viral",
    "kuliner enak",
    "cafe viral",
    "cafe enak",
    "restoran viral",
    "restoran enak",
    "wisata viral",
    "wisata baru"
]

PROVINCES = [
    "Aceh", "Sumatera Utara", "Sumatera Barat", "Riau", "Kepulauan Riau",
    "Jambi", "Sumatera Selatan", "Kepulauan Bangka Belitung", "Bengkulu", "Lampung",
    "DKI Jakarta", "Jawa Barat", "Banten", "Jawa Tengah", "DI Yogyakarta", "Jawa Timur",
    "Bali", "Nusa Tenggara Barat", "Nusa Tenggara Timur", "Kalimantan Barat",
    "Kalimantan Tengah", "Kalimantan Selatan", "Kalimantan Timur", "Kalimantan Utara",
    "Sulawesi Utara", "Gorontalo", "Sulawesi Tengah", "Sulawesi Barat", "Sulawesi Selatan",
    "Sulawesi Tenggara", "Maluku", "Maluku Utara", "Papua", "Papua Barat",
    "Papua Selatan", "Papua Tengah", "Papua Pegunungan", "Papua Barat Daya",
]

BIG_CITIES = [
    "Jakarta Selatan", "Jakarta Pusat", "Jakarta Barat", "Jakarta Timur", "Jakarta Utara",
    "Surabaya", "Bandung", "Medan", "Yogyakarta", "Sleman", "Semarang", "Makassar",
    "Palembang", "Depok", "Bekasi", "Tangerang", "Bogor", "Malang", "Denpasar",
    "Bandar Lampung", "Padang", "Pekanbaru", "Banjarmasin", "Balikpapan", "Samarinda",
    "Pontianak", "Manado", "Jayapura", "Solo", "Cirebon", "Tasikmalaya", "Batam",
]

REGIONAL_CATEGORIES = [
    "tempat makan viral",
    "tempat makan enak",
    "cafe viral",
    "cafe enak",
    "restoran viral",
    "restoran enak",
    "wisata viral",
    "wisata baru",
    # "tempat belanja viral"
]

LOCATION_KEYWORDS = [
    f"{category} {region}"
    for region in PROVINCES + BIG_CITIES
    for category in REGIONAL_CATEGORIES
]
KEYWORDS = list(dict.fromkeys(BASE_KEYWORDS + LOCATION_KEYWORDS))

MONTHS_BACK = 6
MAX_ITEMS_PER_KEYWORD = 100
REQUEST_DELAY = 1.0

CUTOFF_DATE = datetime.now(timezone.utc) - timedelta(days=30 * MONTHS_BACK)
print("Total keyword:", len(KEYWORDS))
print("Ambil artikel sejak:", CUTOFF_DATE.date())

Total keyword: 570
Ambil artikel sejak: 2026-04-05

In [19]:
EDITIONS = [
    ("id", "ID", "ID:id")
    # ("en-ID", "ID", "ID:en"),
]


def fetch_google_news(keyword: str, max_items: int = 25, hl: str = "id", gl: str = "ID", ceid: str = "ID:id"):
    """Ambil daftar berita dari Google News RSS untuk sebuah keyword & edisi bahasa/negara tertentu."""
    query = urllib.parse.quote(keyword)
    url = f"https://news.google.com/rss/search?q={query}&hl={hl}&gl={gl}&ceid={ceid}"
    feed = feedparser.parse(url)

    items = []
    for entry in feed.entries[:max_items]:
        try:
            pub_date = dateparser.parse(entry.published)
            if pub_date.tzinfo is None:
                pub_date = pub_date.replace(tzinfo=timezone.utc)
        except Exception:
            pub_date = None

        if pub_date is not None and pub_date < CUTOFF_DATE:
            continue  # lewati berita yang lebih lama dari batas waktu

        source = entry.get("source", {}).get("title") if hasattr(entry, "get") else None
        items.append(
            {
                "keyword": keyword,
                "title": entry.title,
                "link": entry.link,
                "published": pub_date,
                "source": source or getattr(getattr(entry, "source", None), "title", None),
            }
        )
    return items


all_news = []
os.makedirs("news", exist_ok=True)
for kw in tqdm(KEYWORDS, desc="Fetch RSS per keyword"):
    for hl, gl, ceid in EDITIONS:
        all_news.extend(fetch_google_news(kw, MAX_ITEMS_PER_KEYWORD, hl=hl, gl=gl, ceid=ceid))
        time.sleep(REQUEST_DELAY)

df_news = pd.DataFrame(all_news).drop_duplicates(subset="link").reset_index(drop=True)
# Simpan semua berita yang telah diambil ke dalam folder "news" tiap keyword
df_news.to_csv("news/all_news.csv", index=False)
for kw in KEYWORDS:
    df_news_kw = df_news[df_news["keyword"] == kw]
    df_news_kw.to_csv(f"news/news_{kw}.csv", index=False)
print(f"Total artikel ditemukan: {len(df_news)}")
df_news

Fetch RSS per keyword:   0%|          | 0/570 [00:00<?, ?it/s]

Fetch RSS per keyword: 100%|ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â | 570/570 [19:28<00:00,  2.05s/it]

Total artikel ditemukan: 5261

,keyword,title,link,published,source
0,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang J...,https://news.google.com/rss/articles/CBMitAFBV...,2026-10-01 05:00:00+00:00,food.detik.com
1,tempat makan viral,Media Sosial Mengubah Cara Kita Memilih Tempat...,https://news.google.com/rss/articles/CBMifkFVX...,2026-09-25 08:00:00+00:00,Jatimnet.com
2,tempat makan viral,"10 Rekomendasi Kuliner Malam Sidoarjo, Gak Tak...",https://news.google.com/rss/articles/CBMizwFBV...,2026-09-16 07:00:00+00:00,IDN Times Jatim
3,tempat makan viral,"TikTok Food Fest 2026 Hari Terakhir di GBK, Ad...",https://news.google.com/rss/articles/CBMidEFVX...,2026-09-27 10:22:00+00:00,Aktualita.co
4,tempat makan viral,10 Tempat Makan Viral di Bandung 2026 - nibble.id,https://news.google.com/rss/articles/CBMiaEFVX...,2026-06-09 07:00:00+00:00,nibble.id
...,...,...,...,...,...
5256,wisata baru Batam,HARRIS Barelang Batam Hadirkan Promo Liburan K...,https://news.google.com/rss/articles/CBMiigFBV...,2026-07-07 07:00:00+00:00,Liputan Bhagasasi
5257,wisata baru Batam,"Pemko Batam Bangun Taman Budaya Rp50 Miliar, T...",https://news.google.com/rss/articles/CBMiyAFBV...,2026-07-15 07:00:00+00:00,Jawa Pos
5258,wisata baru Batam,Disbudpar: 113.784 wisman kunjungi Batam pada ...,https://news.google.com/rss/articles/CBMingFBV...,2026-06-03 07:00:00+00:00,ANTARA News Kepri
5259,wisata baru Batam,"Ascott Resmikan Fox Hotel Nagoya Batam, Hotel ...",https://news.google.com/rss/articles/CBMioAFBV...,2026-05-20 07:00:00+00:00,Beritakota
5260,wisata baru Batam,Batam Tegaskan Aman dari Hantavirus Meski Keda...,https://news.google.com/rss/articles/CBMitAFBV...,2026-05-13 07:00:00+00:00,mediaindonesia.com

In [20]:
df_news.keyword.value_counts()

keyword
wisata baru                             99
kuliner viral                           94
wisata viral                            76
tempat makan viral                      73
wisata viral Bali                       68
                                        ..
restoran enak Kalimantan Utara           1
restoran viral Tasikmalaya               1
cafe viral Kepulauan Bangka Belitung     1
cafe enak Kepulauan Bangka Belitung      1
tempat makan viral Manado                1
Name: count, Length: 491, dtype: int64

In [6]:
df_news = pd.read_csv("news/all_news.csv")
df_news

,keyword,title,link,published,source
0,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang J...,https://news.google.com/rss/articles/CBMitAFBV...,2026-10-01 05:00:00+00:00,food.detik.com
1,tempat makan viral,Media Sosial Mengubah Cara Kita Memilih Tempat...,https://news.google.com/rss/articles/CBMifkFVX...,2026-09-25 08:00:00+00:00,Jatimnet.com
2,tempat makan viral,"10 Rekomendasi Kuliner Malam Sidoarjo, Gak Tak...",https://news.google.com/rss/articles/CBMizwFBV...,2026-09-16 07:00:00+00:00,IDN Times Jatim
3,tempat makan viral,"TikTok Food Fest 2026 Hari Terakhir di GBK, Ad...",https://news.google.com/rss/articles/CBMidEFVX...,2026-09-27 10:22:00+00:00,Aktualita.co
4,tempat makan viral,10 Tempat Makan Viral di Bandung 2026 - nibble.id,https://news.google.com/rss/articles/CBMiaEFVX...,2026-06-09 07:00:00+00:00,nibble.id
...,...,...,...,...,...
5256,wisata baru Batam,HARRIS Barelang Batam Hadirkan Promo Liburan K...,https://news.google.com/rss/articles/CBMiigFBV...,2026-07-07 07:00:00+00:00,Liputan Bhagasasi
5257,wisata baru Batam,"Pemko Batam Bangun Taman Budaya Rp50 Miliar, T...",https://news.google.com/rss/articles/CBMiyAFBV...,2026-07-15 07:00:00+00:00,Jawa Pos
5258,wisata baru Batam,Disbudpar: 113.784 wisman kunjungi Batam pada ...,https://news.google.com/rss/articles/CBMingFBV...,2026-06-03 07:00:00+00:00,ANTARA News Kepri
5259,wisata baru Batam,"Ascott Resmikan Fox Hotel Nagoya Batam, Hotel ...",https://news.google.com/rss/articles/CBMioAFBV...,2026-05-20 07:00:00+00:00,Beritakota
5260,wisata baru Batam,Batam Tegaskan Aman dari Hantavirus Meski Keda...,https://news.google.com/rss/articles/CBMitAFBV...,2026-05-13 07:00:00+00:00,mediaindonesia.com

In [7]:
def resolve_and_fetch(url: str, timeout: tuple[int, int] = (5, 15)):
    """Decode URL Google News lalu ambil HTML halaman artikel sumber."""
    source_url = url
    if "news.google.com" in url:
        try:
            decoded = gnewsdecoder(url, interval=1, timeout=10)
            if decoded.get("success") and decoded.get("decoded_url"):
                source_url = decoded["decoded_url"]
        except Exception:
            pass

    try:
        resp = requests.get(source_url, headers=HEADERS, timeout=timeout, allow_redirects=True)
        resp.raise_for_status()
        return resp.url, resp.text
    except requests.RequestException:
        return None, None


def extract_article_text(html: str) -> str:
    """Ambil isi artikel dari JSON-LD, meta description, paragraf, atau body HTML."""
    if not html:
        return ""
    soup = BeautifulSoup(html, "lxml")

    # Banyak situs berita menyimpan isi artikel di JSON-LD, bukan tag p.
    for script in soup.find_all("script", type="application/ld+json"):
        try:
            payload = json.loads(script.string or script.get_text())
        except (TypeError, json.JSONDecodeError):
            continue
        candidates = payload if isinstance(payload, list) else [payload]
        for item in candidates:
            if isinstance(item, dict) and isinstance(item.get("articleBody"), str):
                article_body = re.sub(r"\s+", " ", item["articleBody"]).strip()
                if len(article_body) >= 100:
                    return article_body

    meta = soup.find("meta", attrs={"name": "description"}) or soup.find(
        "meta", attrs={"property": "og:description"}
    )
    meta_text = meta.get("content", "").strip() if meta else ""

    for tag in soup(["script", "style", "nav", "footer", "header", "aside", "noscript"]):
        tag.decompose()
    paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]
    paragraphs = [p for p in paragraphs if len(p) >= 20]
    paragraph_text = " ".join(paragraphs)
    if len(paragraph_text) >= 100:
        return paragraph_text
    if len(meta_text) >= 40:
        return meta_text

    body_text = soup.get_text(" ", strip=True) if soup.body else ""
    return re.sub(r"\s+", " ", body_text).strip()


# def fetch_article_batch(
#     df_news: pd.DataFrame,
#     mulai: int = 0,
#     max_articles: int = 2410,
#     request_delay: float = REQUEST_DELAY,
# ) -> tuple[list[str | None], list[str]]:
#     """Fetch dan ekstrak isi artikel sebanyak maksimal `max_articles` baris."""
#     article_texts = []
#     final_urls = []

#     for article_number, link in enumerate(df_news["link"].head(max_articles), start=1):
#         if article_number < mulai: continue
#         print("Processing article number:", article_number)
#         print("Fetching link:", link)
#         final_url, html = resolve_and_fetch(link)
#         final_urls.append(final_url)
#         article_texts.append(extract_article_text(html))
#         print("panjang artikel:", len(article_texts[-1]))
#         time.sleep(request_delay)

#     return final_urls, article_texts


# final_urls, article_texts = fetch_article_batch(df_news, mulai=0, max_articles=2410)

In [8]:
import concurrent.futures

# Kenapa loop suka "diam" tanpa error: gnewsdecoder/requests kadang stall di level
# socket (koneksi macet, bukan timeout HTTP biasa) sehingga thread utama menggantung
# selamanya. fetch_article_safe menjalankan fetch di thread terpisah dan memaksa
# menyerah setelah HARD_TIMEOUT detik, supaya satu link bermasalah tidak mematikan
# seluruh loop.
HARD_TIMEOUT = 25.0
_fetch_executor = concurrent.futures.ThreadPoolExecutor(max_workers=4, thread_name_prefix="fetch")


def fetch_article_safe(link: str, hard_timeout: float = HARD_TIMEOUT):
    """resolve_and_fetch + extract_article_text dengan hard timeout & anti-exception."""
    future = _fetch_executor.submit(resolve_and_fetch, link)
    try:
        final_url, html = future.result(timeout=hard_timeout)
    except Exception:
        return None, ""
    try:
        return final_url, extract_article_text(html)
    except Exception:
        return final_url, ""

In [9]:
import json
import os
from pathlib import Path

# Checkpoint per-baris: setiap link yang selesai difetch langsung ditulis ke file
# ini (flush + fsync). Kalau kernel macet/di-restart, jalankan ulang cell ini ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â
# link yang sudah ada di checkpoint otomatis dilewati (resume), jadi progres tidak
# hilang lagi walau berhenti di tengah jalan.
CHECKPOINT_PATH = Path("fetch_checkpoint.jsonl")

START_FROM = 0
done = {}
if CHECKPOINT_PATH.exists():
    with CHECKPOINT_PATH.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
                done[rec["index"]] = rec
            except json.JSONDecodeError:
                continue
    print(f"Resume: {len(done)} link sudah pernah diproses, akan dilewati.")

with CHECKPOINT_PATH.open("a", encoding="utf-8") as ckpt_file:
    for idx, link in enumerate(tqdm(df_news[START_FROM:]["link"], desc="Fetch isi artikel")):
        if idx + START_FROM in done:
            continue
        try:
            final_url, text = fetch_article_safe(link)
        except Exception as e:
            print(f"Error tak terduga pada index {idx}: {e}")
            final_url, text = None, ""

        rec = {"index": idx + START_FROM, "link": link, "final_url": final_url, "article_text": text}
        ckpt_file.write(json.dumps(rec, ensure_ascii=False) + "\n")
        ckpt_file.flush()
        os.fsync(ckpt_file.fileno())
        done[idx] = rec
        time.sleep(REQUEST_DELAY)

print(f"Total link diproses (checkpoint): {len(done)} dari {len(df_news)}")

Resume: 5261 link sudah pernah diproses, akan dilewati.

Fetch isi artikel: 100%|ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â | 5261/5261 [00:00<00:00, 3391153.12it/s]

Total link diproses (checkpoint): 5261 dari 5261

In [10]:
# Gabungkan seluruh checkpoint (boleh dijalankan kapan saja, termasuk saat proses
# fetch di atas belum 100% selesai, untuk lihat progres sementara) jadi satu CSV.
indices = sorted(i for i in done if i < len(df_news))
df_result = df_news.iloc[indices].copy()
df_result["final_url"] = [done[i]["final_url"] for i in indices]
df_result["article_text"] = pd.Series(
    [done[i]["article_text"] for i in indices], index=df_result.index, dtype="string"
)
df_result["article_text_length"] = df_result["article_text"].str.len().fillna(0).astype(int)

print(f"Artikel dengan isi berhasil diambil: {(df_result['article_text_length'] >= 100).sum()} dari {len(df_result)}")
print(f"Fetch gagal/kosong: {df_result['article_text'].eq('').sum()}")

df_result_final = df_result[df_result["article_text_length"] >= 100].reset_index(drop=True)
df_result_final.to_csv("df_news_extended_full_coba.csv", index=False)
print("Saved df_news_extended_full_coba.csv")

Artikel dengan isi berhasil diambil: 5090 dari 5261
Fetch gagal/kosong: 97
Saved df_news_extended_full_coba.csv

In [11]:
import glob
import json
import os
import re
import time
from datetime import datetime, timedelta

import pandas as pd
from dateutil import parser as dateparser
from rapidfuzz import fuzz
from tqdm.auto import tqdm

pd.set_option("display.max_colwidth", 120)

In [5]:
NEWS_CSV_FILE = "df_news_extended_full_coba.csv"
MIN_ARTICLE_LEN = 150

df_news_all = pd.read_csv(NEWS_CSV_FILE)
print("File dipakai:", NEWS_CSV_FILE)

# beberapa batch mungkin punya nama kolom isi artikel yang sedikit berbeda; standardisasi
text_col_candidates = [c for c in ["article_text", "article_text_extended", "text"] if c in df_news_all.columns]
if "article_text" not in df_news_all.columns and text_col_candidates:
    df_news_all["article_text"] = df_news_all[text_col_candidates[0]]

dedup_key = "final_url" if "final_url" in df_news_all.columns else "link"
df_news_all = df_news_all.dropna(subset=[dedup_key])
df_news_all = df_news_all.drop_duplicates(subset=[dedup_key]).reset_index(drop=True)
df_news_all = df_news_all[df_news_all["article_text"].fillna("").str.len() >= MIN_ARTICLE_LEN].reset_index(drop=True)

print("Total artikel unik & layak diproses:", len(df_news_all))
df_news_all.head(3)

File dipakai: df_news_extended_full_coba.csv
Total artikel unik & layak diproses: 4834

,keyword,title,link,published,source,final_url,article_text,article_text_length
0,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang J...,https://news.google.com/rss/articles/CBMitAFBV...,2026-10-01 05:00:00+00:00,food.detik.com,https://food.detik.com/tempat-makan/d-8687381/...,Semangkuk ramen berkuah gurih hangat dengan an...,4249
1,tempat makan viral,Media Sosial Mengubah Cara Kita Memilih Tempat...,https://news.google.com/rss/articles/CBMifkFVX...,2026-09-25 08:00:00+00:00,Jatimnet.com,https://jatimnet.com/media-sosial-mengubah-car...,"Jumat, 25 September 2026 08:00 UTC Ilustrasi: ...",7110
2,tempat makan viral,"10 Rekomendasi Kuliner Malam Sidoarjo, Gak Tak...",https://news.google.com/rss/articles/CBMizwFBV...,2026-09-16 07:00:00+00:00,IDN Times Jatim,https://jatim.idntimes.com/food/dining-guide/1...,Kuliner malam di Sidoarjo menjadi daya tarik t...,7524

## 5. Buat Prompt Batch untuk Ekstraksi Manual via Chat Claude.ai

Sel di bawah membuat file prompt per-batch (`manual_llm_batches_coba/batch_XXX_prompt.txt`) yang bisa langsung ditempel ke chat Claude.ai untuk diekstrak jadi daftar tempat dengan skema kolom final:

`no, nama_tempat, kategori, jenis_tempat, lokasi, keterangan, status_viral, viral_sejak, dasar_viral, kelurahan_desa, kecamatan, kota_kabupaten, provinsi, negara, latitude, longitude, presisi_koordinat, catatan_lokasi, jumlah_artikel, keyword_pencarian, judul_artikel_sumber, link_sumber`

Langkahnya:
1. Jalankan sel "Generate Prompt Batch" ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ini membuat file `batch_001_prompt.txt`, `batch_002_prompt.txt`, dst di folder `manual_llm_batches_coba/`.
2. Buka chat baru di claude.ai, tempel **seluruh isi** satu file `batch_XXX_prompt.txt`, kirim.
3. Simpan balasan JSON Claude (hanya JSON, tanpa teks tambahan) sebagai `manual_llm_batches_coba/batch_XXX_response.json`.
4. Ulangi untuk semua batch, lalu jalankan sel "Gabungkan Hasil ke CSV Final" di bawah untuk membangun tabel final sesuai skema kolom di atas.

Kolom `no`, `jumlah_artikel`, `keyword_pencarian`, `judul_artikel_sumber`, `link_sumber` **tidak** diminta dari Claude ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â `jumlah_artikel` dihitung otomatis saat tempat yang sama disebut di beberapa artikel (fuzzy dedup berdasarkan nama), sisanya diisi dari metadata artikel saat hasil digabungkan.

In [13]:
MANUAL_BATCH_DIR = "manual_llm_batches_coba"
MANUAL_BATCH_SIZE = 8       # jumlah artikel per file prompt - kecilkan jika artikel panjang
MANUAL_MAX_CHARS = 3000     # potong isi artikel supaya prompt tidak terlalu panjang untuk chat

In [ ]:
os.makedirs(MANUAL_BATCH_DIR, exist_ok=True)

# simpan pemetaan article_id -> metadata artikel, dipakai lagi saat mengimpor hasil balasan
id_map = {}
for idx, row in df_news_all.iterrows():
    id_map[str(idx)] = {
        "final_url": row[dedup_key],
        "title": row.get("title", ""),
        "link": row.get("link", row[dedup_key]),
        "keyword": row.get("keyword", ""),
    }
with open(os.path.join(MANUAL_BATCH_DIR, "id_map.json"), "w", encoding="utf-8") as f:
    json.dump(id_map, f, ensure_ascii=False, indent=2)

PROMPT_HEADER = """Kamu akan menerima beberapa artikel berita. Untuk SETIAP artikel, ekstrak semua tempat makan/kafe/resto/wisata/museum/wahana/pameran yang disebutkan.

Balas HANYA dengan JSON valid (tanpa penjelasan, tanpa markdown code fence) dengan format:
{
  "results": [
    {
      "article_id": <id artikel, angka>,
      "places": [
        {
          "nama_tempat": "...",
          "kategori": "Kafe/Restoran/Wisata Alam/Museum/Wahana/Pameran/lainnya",
          "jenis_tempat": "subtipe lebih spesifik, mis. 'rooftop cafe', 'kuliner kaki lima', 'air terjun', 'taman hiburan', dst",
          "lokasi": "lokasi mentah apa adanya sesuai artikel (alamat/nama jalan/area jika disebut)",
          "keterangan": "ringkasan singkat ciri khas/daya tarik tempat ini (mis. menu andalan, konsep, fasilitas)",
          "status_viral": "Disebut viral" (artikel eksplisit menyebut tempat ini viral/ramai dibahas/jadi perbincangan warganet) atau "Rekomendasi" (tempat hanya direkomendasikan/masuk daftar, tanpa disebut eksplisit viral),
          "viral_sejak": "tanggal/bulan/periode eksplisit terkait mulai viral jika disebut, atau 'Tidak disebut' jika tidak ada",
          "dasar_viral": "kutipan/alasan singkat dari artikel yang menjadi dasar kenapa tempat ini dianggap viral/direkomendasikan, atau null jika tidak ada dasar eksplisit",
          "kelurahan_desa": "nama kelurahan/desa, atau null jika tidak diketahui",
          "kecamatan": "nama kecamatan, atau null jika tidak diketahui",
          "kota_kabupaten": "nama kota/kabupaten, atau null jika tidak diketahui",
          "provinsi": "nama provinsi, atau null jika tidak diketahui",
          "negara": "nama negara, default 'Indonesia' kecuali artikel jelas menyebut negara lain",
          "latitude": angka desimal lintang jika kamu bisa simpulkan/cari dari nama tempat & lokasi, atau null jika tidak yakin,
          "longitude": angka desimal bujur jika kamu bisa simpulkan/cari dari nama tempat & lokasi, atau null jika tidak yakin,
          "presisi_koordinat": "exact" (alamat persis diketahui), "approximate" (hanya area/kecamatan/kota), atau "unknown" (tidak ada dasar koordinat),
          "catatan_lokasi": "catatan tambahan soal lokasi, mis. ketidakpastian, patokan terdekat, atau null jika tidak ada"
        }
      ]
    }
  ]
}

Jika sebuah artikel tidak menyebut tempat spesifik, kembalikan places: [] untuk artikel itu. Sertakan SEMUA article_id yang diberikan di bawah, jangan ada yang terlewat.
"""

article_ids = list(df_news_all.index)
batches = [article_ids[i:i + MANUAL_BATCH_SIZE] for i in range(0, len(article_ids), MANUAL_BATCH_SIZE)]

for b_num, batch_ids in enumerate(batches, start=1):
    parts = [PROMPT_HEADER, "\nArtikel:\n"]
    for aid in batch_ids:
        row = df_news_all.loc[aid]
        text = str(row.get("article_text", ""))[:MANUAL_MAX_CHARS]
        parts.append(f"\n### Artikel {aid}\nJudul: {row.get('title', '')}\nIsi:\n{text}\n")
    prompt_text = "\n".join(parts)
    fname = os.path.join(MANUAL_BATCH_DIR, f"batch_{b_num:03d}_prompt.txt")
    with open(fname, "w", encoding="utf-8") as f:
        f.write(prompt_text)

print(f"Dibuat {len(batches)} file prompt di folder '{MANUAL_BATCH_DIR}/'")

Dibuat 605 file prompt di folder 'manual_llm_batches_coba/'

**Setelah semua file `batch_XXX_response.json` tersimpan** di folder `manual_llm_batches_coba/` (isi tiap file harus JSON valid sesuai format di atas), jalankan sel berikut untuk menggabungkan semuanya jadi tabel final dengan kolom sesuai skema yang diminta.

In [14]:
with open(os.path.join(MANUAL_BATCH_DIR, "id_map.json"), encoding="utf-8") as f:
    id_map = json.load(f)

RESPONSE_BATCH_DIR = "responses_json_coba"
response_files = sorted(glob.glob(os.path.join(RESPONSE_BATCH_DIR, "batch_*_response.json")))
print("File respons ditemukan:", len(response_files))

rows = []
for rf in response_files:
    with open(rf, encoding="utf-8") as f:
        try:
            data = json.load(f)
        except json.JSONDecodeError as e:
            print("Gagal parse", rf, "-> pastikan isinya JSON valid tanpa teks tambahan:", e)
            continue
    for result in data.get("results", []):
        aid = str(result.get("article_id"))
        meta = id_map.get(aid)
        if not meta:
            print("article_id tidak dikenal:", aid, "di", rf)
            continue
        for p in result.get("places", []):
            rows.append({
                "nama_tempat": p.get("nama_tempat"),
                "kategori": p.get("kategori"),
                "jenis_tempat": p.get("jenis_tempat"),
                "lokasi": p.get("lokasi"),
                "keterangan": p.get("keterangan"),
                "status_viral": p.get("status_viral"),
                "viral_sejak": p.get("viral_sejak"),
                "dasar_viral": p.get("dasar_viral"),
                "kelurahan_desa": p.get("kelurahan_desa"),
                "kecamatan": p.get("kecamatan"),
                "kota_kabupaten": p.get("kota_kabupaten"),
                "provinsi": p.get("provinsi"),
                "negara": p.get("negara"),
                "latitude": p.get("latitude"),
                "longitude": p.get("longitude"),
                "presisi_koordinat": p.get("presisi_koordinat"),
                "catatan_lokasi": p.get("catatan_lokasi"),
                "_article_key": aid,
                "keyword_pencarian": meta.get("keyword"),
                "judul_artikel_sumber": meta.get("title"),
                "link_sumber": meta.get("link") or meta.get("final_url"),
            })

df_places_raw = pd.DataFrame(rows).dropna(subset=["nama_tempat"]).reset_index(drop=True)
print("Total baris tempat mentah (sebelum dedup antar-artikel):", len(df_places_raw))
df_places_raw.head(5)

File respons ditemukan: 170
Total baris tempat mentah (sebelum dedup antar-artikel): 2467

,nama_tempat,kategori,jenis_tempat,lokasi,keterangan,status_viral,viral_sejak,dasar_viral,kelurahan_desa,kecamatan,...,provinsi,negara,latitude,longitude,presisi_koordinat,catatan_lokasi,_article_key,keyword_pencarian,judul_artikel_sumber,link_sumber
0,Sai Ramen,Restoran,restoran ramen Jepang halal,"Sampoerna Strategic Building, gedung Synergy, Living World Kota Wisata","Ramen halal harga bersahabat Rp50-75 ribu; Black Garlic Ramen, Akakara Spicy Ramen, kaldu ayam pekat",Rekomendasi,Tidak disebut,Ramen bersertifikat halal dengan harga bersahabat,None,Setiabudi,...,DKI Jakarta,Indonesia,-6.2196,106.8186,approximate,Punya beberapa cabang; koordinat mengacu ke cabang Sampoerna Strategic Square,0,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
1,Menya Beast,Restoran,restoran ramen Jepang,"Lantai Dasar Trinity Tower, Setiabudi, Kuningan","Resep chef Jepang, kaldu dimasak 12 jam; Jun Tonkotsu Mayu Ramen, Taiwan Tantan Abura Soba; Rp100-130 ribu",Rekomendasi,Tidak disebut,"Ramen dengan resep chef asal Jepang, kaldu dimasak 12 jam",Karet Kuningan,Setiabudi,...,DKI Jakarta,Indonesia,-6.2187,106.8303,approximate,"Di dalam gedung Trinity Tower, Kuningan",0,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
2,Raku Ramen,Restoran,kedai ramen Jepang (basement),"Fairground SCBD, Senayan, Kebayoran Baru, Jakarta Selatan","Gerai 'nyempil' di bawah tanah, kuah shoyu/shio/paitan, mulai Rp50 ribuan",Rekomendasi,Tidak disebut,Lokasi nyempil di bawah tanah tetapi tidak pernah sepi pengunjung,Senayan,Kebayoran Baru,...,DKI Jakarta,Indonesia,-6.2257,106.8089,approximate,Area Fairground SCBD,0,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
3,Echigoya,Restoran,restoran ramen Jepang autentik,None,"Ramen autentik langganan warga Jepang, kuah kental milky, topping ayam atau babi",Rekomendasi,Tidak disebut,Sering menjadi tujuan banyak warga lokal Jepang,None,None,...,DKI Jakarta,Indonesia,NaN,NaN,unknown,Lokasi terpotong di artikel; hanya disebut di Jakarta,0,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
4,Warung Amanda,Restoran,warung makan (sego sambel lento),"Jl. Raya Taman Pinang Indah No.6, Banjarbendo, Kec. Sidoarjo","Sego sambel lento khas Sidoarjo, buka 24 jam, mulai Rp11 ribu, hanya tunai",Rekomendasi,Tidak disebut,"Menjual sego sambel lento, menu khas Sidoarjo",Banjarbendo,Sidoarjo,...,Jawa Timur,Indonesia,-7.4560,112.7010,approximate,Kawasan Taman Pinang Indah,2,tempat makan viral,"10 Rekomendasi Kuliner Malam Sidoarjo, Gak Takut Lapar Saat Begadang - IDN Times Jatim",https://news.google.com/rss/articles/CBMizwFBVV95cUxQbG9QZ2VwZ3NYR3lVb1N2Z25GTkkxWU93Tko3SGtkakhXN2JVVmFhXzRJc1NsSWp...

Tempat yang sama bisa disebut di beberapa artikel berbeda (dengan penulisan nama sedikit berbeda). Sel berikut melakukan **fuzzy dedup** nama tempat (`rapidfuzz.fuzz.token_sort_ratio`) supaya tiap tempat jadi satu baris, lalu menghitung `jumlah_artikel` dan menyimpan ke CSV final dengan urutan kolom sesuai skema.

In [15]:
FUZZY_THRESHOLD = 88  # 0-100, makin tinggi makin ketat kemiripan nama

FINAL_COLUMNS = [
    "no", "nama_tempat", "kategori", "jenis_tempat", "lokasi", "keterangan",
    "status_viral", "viral_sejak", "dasar_viral", "kelurahan_desa", "kecamatan",
    "kota_kabupaten", "provinsi", "negara", "latitude", "longitude",
    "presisi_koordinat", "catatan_lokasi", "jumlah_artikel",
    "keyword_pencarian", "judul_artikel_sumber", "link_sumber",
]


def normalize_place_name(name: str) -> str:
    name = str(name).lower().strip()
    name = re.sub(r"[^\w\s]", " ", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name


def first_non_null(series: pd.Series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) else None


df_places_raw["_nama_norm"] = df_places_raw["nama_tempat"].map(normalize_place_name)

# cluster nama unik yang mirip (greedy): tiap nama unik dibandingkan ke representative cluster yang sudah ada
unique_names = df_places_raw["_nama_norm"].unique().tolist()
name_to_group = {}
cluster_reps = []  # representative nama tiap cluster, indexnya = id cluster

for name in unique_names:
    if not name:
        continue
    best_idx, best_score = None, 0
    for idx, rep in enumerate(cluster_reps):
        score = fuzz.token_sort_ratio(name, rep)
        if score > best_score:
            best_idx, best_score = idx, score
    if best_score >= FUZZY_THRESHOLD:
        name_to_group[name] = best_idx
    else:
        cluster_reps.append(name)
        name_to_group[name] = len(cluster_reps) - 1

df_places_raw["canonical_group"] = df_places_raw["_nama_norm"].map(name_to_group)
print("Total nama mentah unik:", len(unique_names))
print("Total tempat unik setelah fuzzy dedup:", df_places_raw["canonical_group"].nunique())

agg_cols = [c for c in FINAL_COLUMNS if c not in ("no", "jumlah_artikel")]
grouped_rows = []
for _, g in df_places_raw.groupby("canonical_group", sort=False):
    row = {col: first_non_null(g[col]) for col in agg_cols if col in g.columns}
    row["jumlah_artikel"] = g["_article_key"].nunique()
    grouped_rows.append(row)

df_places_final = pd.DataFrame(grouped_rows, columns=[c for c in FINAL_COLUMNS if c != "no"])
df_places_final.insert(0, "no", range(1, len(df_places_final) + 1))

# OUTPUT_CSV = "hasil_ekstraksi_tempat_viral.csv"
# df_places_final.to_csv(OUTPUT_CSV, index=False)
print(f"Total baris tempat (setelah dedup): {len(df_places_final)}")
# print(f"Total baris tempat (setelah dedup): {len(df_places_final)}. Disimpan ke {OUTPUT_CSV}")
df_places_final.head(5)

Total nama mentah unik: 2082
Total tempat unik setelah fuzzy dedup: 2051
Total baris tempat (setelah dedup): 2051

,no,nama_tempat,kategori,jenis_tempat,lokasi,keterangan,status_viral,viral_sejak,dasar_viral,kelurahan_desa,...,provinsi,negara,latitude,longitude,presisi_koordinat,catatan_lokasi,jumlah_artikel,keyword_pencarian,judul_artikel_sumber,link_sumber
0,1,Sai Ramen,Restoran,restoran ramen Jepang halal,"Sampoerna Strategic Building, gedung Synergy, Living World Kota Wisata","Ramen halal harga bersahabat Rp50-75 ribu; Black Garlic Ramen, Akakara Spicy Ramen, kaldu ayam pekat",Rekomendasi,Tidak disebut,Ramen bersertifikat halal dengan harga bersahabat,Karet Semanggi,...,DKI Jakarta,Indonesia,-6.2196,106.8186,approximate,Punya beberapa cabang; koordinat mengacu ke cabang Sampoerna Strategic Square,2,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
1,2,Menya Beast,Restoran,restoran ramen Jepang,"Lantai Dasar Trinity Tower, Setiabudi, Kuningan","Resep chef Jepang, kaldu dimasak 12 jam; Jun Tonkotsu Mayu Ramen, Taiwan Tantan Abura Soba; Rp100-130 ribu",Rekomendasi,Tidak disebut,"Ramen dengan resep chef asal Jepang, kaldu dimasak 12 jam",Karet Kuningan,...,DKI Jakarta,Indonesia,-6.2187,106.8303,approximate,"Di dalam gedung Trinity Tower, Kuningan",1,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
2,3,Raku Ramen,Restoran,kedai ramen Jepang (basement),"Fairground SCBD, Senayan, Kebayoran Baru, Jakarta Selatan","Gerai 'nyempil' di bawah tanah, kuah shoyu/shio/paitan, mulai Rp50 ribuan",Rekomendasi,Tidak disebut,Lokasi nyempil di bawah tanah tetapi tidak pernah sepi pengunjung,Senayan,...,DKI Jakarta,Indonesia,-6.2257,106.8089,approximate,Area Fairground SCBD,2,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
3,4,Echigoya,Restoran,restoran ramen Jepang autentik,None,"Ramen autentik langganan warga Jepang, kuah kental milky, topping ayam atau babi",Rekomendasi,Tidak disebut,Sering menjadi tujuan banyak warga lokal Jepang,None,...,DKI Jakarta,Indonesia,NaN,NaN,unknown,Lokasi terpotong di artikel; hanya disebut di Jakarta,1,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
4,5,Warung Amanda,Restoran,warung makan (sego sambel lento),"Jl. Raya Taman Pinang Indah No.6, Banjarbendo, Kec. Sidoarjo","Sego sambel lento khas Sidoarjo, buka 24 jam, mulai Rp11 ribu, hanya tunai",Rekomendasi,Tidak disebut,"Menjual sego sambel lento, menu khas Sidoarjo",Banjarbendo,...,Jawa Timur,Indonesia,-7.4560,112.7010,approximate,Kawasan Taman Pinang Indah,1,tempat makan viral,"10 Rekomendasi Kuliner Malam Sidoarjo, Gak Takut Lapar Saat Begadang - IDN Times Jatim",https://news.google.com/rss/articles/CBMizwFBVV95cUxQbG9QZ2VwZ3NYR3lVb1N2Z25GTkkxWU93Tko3SGtkakhXN2JVVmFhXzRJc1NsSWp...

In [16]:
df_places_final

,no,nama_tempat,kategori,jenis_tempat,lokasi,keterangan,status_viral,viral_sejak,dasar_viral,kelurahan_desa,...,provinsi,negara,latitude,longitude,presisi_koordinat,catatan_lokasi,jumlah_artikel,keyword_pencarian,judul_artikel_sumber,link_sumber
0,1,Sai Ramen,Restoran,restoran ramen Jepang halal,"Sampoerna Strategic Building, gedung Synergy, Living World Kota Wisata","Ramen halal harga bersahabat Rp50-75 ribu; Black Garlic Ramen, Akakara Spicy Ramen, kaldu ayam pekat",Rekomendasi,Tidak disebut,Ramen bersertifikat halal dengan harga bersahabat,Karet Semanggi,...,DKI Jakarta,Indonesia,-6.2196,106.8186,approximate,Punya beberapa cabang; koordinat mengacu ke cabang Sampoerna Strategic Square,2,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
1,2,Menya Beast,Restoran,restoran ramen Jepang,"Lantai Dasar Trinity Tower, Setiabudi, Kuningan","Resep chef Jepang, kaldu dimasak 12 jam; Jun Tonkotsu Mayu Ramen, Taiwan Tantan Abura Soba; Rp100-130 ribu",Rekomendasi,Tidak disebut,"Ramen dengan resep chef asal Jepang, kaldu dimasak 12 jam",Karet Kuningan,...,DKI Jakarta,Indonesia,-6.2187,106.8303,approximate,"Di dalam gedung Trinity Tower, Kuningan",1,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
2,3,Raku Ramen,Restoran,kedai ramen Jepang (basement),"Fairground SCBD, Senayan, Kebayoran Baru, Jakarta Selatan","Gerai 'nyempil' di bawah tanah, kuah shoyu/shio/paitan, mulai Rp50 ribuan",Rekomendasi,Tidak disebut,Lokasi nyempil di bawah tanah tetapi tidak pernah sepi pengunjung,Senayan,...,DKI Jakarta,Indonesia,-6.2257,106.8089,approximate,Area Fairground SCBD,2,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
3,4,Echigoya,Restoran,restoran ramen Jepang autentik,None,"Ramen autentik langganan warga Jepang, kuah kental milky, topping ayam atau babi",Rekomendasi,Tidak disebut,Sering menjadi tujuan banyak warga lokal Jepang,None,...,DKI Jakarta,Indonesia,NaN,NaN,unknown,Lokasi terpotong di artikel; hanya disebut di Jakarta,1,tempat makan viral,5 Ramen Lezat di Jakarta Ini Langganan Orang Jepang hingga Selebgram - food.detik.com,https://news.google.com/rss/articles/CBMitAFBVV95cUxPQUJIYUdRRG8xWkJUdXhNT2o0SnlTVHQ2TXNfdlBodFFmNk5IT0haOEo1SGNLYUZ...
4,5,Warung Amanda,Restoran,warung makan (sego sambel lento),"Jl. Raya Taman Pinang Indah No.6, Banjarbendo, Kec. Sidoarjo","Sego sambel lento khas Sidoarjo, buka 24 jam, mulai Rp11 ribu, hanya tunai",Rekomendasi,Tidak disebut,"Menjual sego sambel lento, menu khas Sidoarjo",Banjarbendo,...,Jawa Timur,Indonesia,-7.4560,112.7010,approximate,Kawasan Taman Pinang Indah,1,tempat makan viral,"10 Rekomendasi Kuliner Malam Sidoarjo, Gak Takut Lapar Saat Begadang - IDN Times Jatim",https://news.google.com/rss/articles/CBMizwFBVV95cUxQbG9QZ2VwZ3NYR3lVb1N2Z25GTkkxWU93Tko3SGtkakhXN2JVVmFhXzRJc1NsSWp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2046,2047,Klyf Club,Kafe,beach club kolam infinity,"Blue Lagoon Avia Villas, Nusa Ceningan, Klungkung","Di Blue Lagoon Avia Villas, kolam infinity menghadap Blue Lagoon",Rekomendasi,Tidak disebut,Direkomendasikan di panduan wisata Nusa Ceningan,None,...,Bali,Indonesia,-8.6950,115.4560,approximate,Titik di pulau kecil Nusa Ceningan; koordinat perkiraan,1,wisata viral Bali,"Panduan Wisata ke Nusa Ceningan, Hidden Gem Bali! ÃƒÆ’Ã‚Â°Ãƒâ€¦Ã‚Â¸ÃƒÂ¢Ã¢â€šÂ¬Ã‚ÂºÃƒâ€šÃ‚Âµ - TripZilla Indonesia",https://news.google.com/rss/articles/CBMiekFVX3lxTE9zNWlwNjF2enI3UXVaSzIxbVdaSnZ5NXhNcjctZHJZM2RKUmRLOE01ajlreHpER3J...
2047,2048,The Dungki Bendega Resto,Restoran,restoran,"Nusa Ceningan, Nusa Penida, Klungkung",Terkenal dengan burger ayam dan rendang sapi,Rekomendasi,Tidak disebut,Direkomendasikan di panduan wisata Nusa Ceningan,None,...,Bali,Indonesia,-8.7065,115.4500,approximate,Titik di pulau kecil Nusa Ceningan; koordinat perkiraan,1,wisata viral Bali,"Panduan Wisata ke Nusa Ceningan, Hidden Gem Bali! ÃƒÆ’Ã‚Â°Ãƒâ€¦Ã‚Â¸ÃƒÂ¢Ã¢â€šÂ¬Ã‚ÂºÃƒâ€šÃ‚Âµ - TripZilla Indonesia",https://news.google.com/rss/articles/CBMiekFVX3lxTE9zNWlwNjF2enI3UXVaSzIxbVdaSnZ5NXhNcjctZHJZM2RKUmRLOE01ajlreHpER3J...
2048,2049,Yellow Bridge (Jembatan Kuning),lainnya,jembatan ikonik,Antara Nusa Lembongan dan Nusa Ceningan,"Jembatan penghubung Nusa Lembongan-Ceningan, hanya untuk pejalan kaki dan motor",Rekomendasi,Tidak disebut,Direkomendasikan di panduan wisata Nusa Ceningan,None,...,Bali,Indonesia,-8.6840,115.4490,approximate,Titik di pulau kecil Nusa Ceningan; koordinat perkiraan,1,wisata viral Bali,"Panduan Wisata ke Nusa Ceningan, Hidden Gem Bali! ÃƒÆ’Ã‚Â°Ãƒâ€¦Ã‚Â¸ÃƒÂ¢Ã¢â€šÂ¬Ã‚ÂºÃƒâ€šÃ‚Âµ - TripZilla Indonesia",https://news.google.com/rss/articles/CBMiekFVX3lxTE9zNWlwNjF2enI3UXVaSzIxbVdaSnZ5NXhNcjctZHJZM2RKUmRLOE01ajlreHpER3J...
2049,2050,Bali Maritime Tourism Hub,lainnya,hub wisata maritim/pelabuhan,"Pelabuhan Benoa, Bali",Proyek Pelindo/PT LEGI untuk melayani kapal pesiar dan yacht; listrik dipasok PLN,Rekomendasi,Tidak disebut,Transformasi Pelabuhan Benoa jadi destinasi wisata maritim kelas dunia,Benoa,...,Bali,Indonesia,-8.7440,115.2120,approximate,Koordinat perkiraan Pelabuhan Benoa,1,wisata viral Bali,"PLN Hadirkan Kelistrikan Andal untuk Bali Maritime Tourism Hub, Perkuat Pariwisata dan Ekonomi Bali - Bali Viral News",https://news.google.com/rss/articles/CBMiyAFBVV95cUxPRW1qU1N4RVlBaDBkbjRGYzZkamdvOTctdzN0Y3NHcW1QT0p5WldJODkxQzdQUHB...
2050,2051,Agrowisata Salak Sibetan,Wisata Alam,agrowisata kebun salak,"Sibetan, Karangasem, Bali","Petik salak gula pasir langsung dari pohon, wine salak",Rekomendasi,Tidak disebut,Destinasi wisata hijau eksotis di Karangasem,Sibetan,...,Bali,Indonesia,-8.4650,115.5350,approximate,Koordinat perkiraan desa Sibetan,1,wisata viral Bali,"Menjelajahi Agrowisata Salak Sibetan: Destinasi Wisata Hijau Nan Eksotis di Jantung Karangasem, Bali - Radar Bali",https://news.google.com/rss/articles/CBMi5AFBVV95cUxObzlVVUNBbExkMi04bGtfdHhpakVhelRxY3Z2SWQ1Rk5VdDRlLVRXZkwwWjJMeWx...

In [17]:
# # Hitung jumlah berita 6 bulan terakhir per nama_tempat (Google News RSS), plus
# # tanggal berita pertama, terakhir, dan selisih harinya. Hasil ditambah ke df_places_final.
# # Keyword = "nama_tempat" + kota_kabupaten (kalau ada) supaya nama umum tidak tercampur tempat lain.
# # Checkpoint per tempat ke JSONL -> aman di-resume kalau kernel berhenti.
# import concurrent.futures
# import threading
# from pathlib import Path

# PLACE_CKPT = Path("place_news_stats_checkpoint.jsonl")
# PLACE_DELAY = 1.0          # jeda per request (detik), per worker
# PLACE_WORKERS = 3          # jangan terlalu besar supaya tidak kena rate limit Google
# PLACE_MAX_ITEMS = 100      # RSS Google News maksimal ~100 item per query
# PLACE_DAYS_BACK = 180      # ~6 bulan
# USE_CITY_IN_QUERY = True   # False = cari hanya berdasarkan nama_tempat

# place_cutoff = datetime.now(timezone.utc) - timedelta(days=PLACE_DAYS_BACK)


# def fetch_place_news_stats(place: str, city: str | None = None, retries: int = 3) -> dict:
#     """Cari berita dengan keyword "nama_tempat" [kota] dalam 6 bulan terakhir."""
#     q = f'"{place}"'
#     if USE_CITY_IN_QUERY and city:
#         q += f' "{city}"'
#     query = urllib.parse.quote(f"{q} when:{PLACE_DAYS_BACK}d")
#     url = f"https://news.google.com/rss/search?q={query}&hl=id&gl=ID&ceid=ID:id"

#     entries = None
#     for attempt in range(retries):
#         try:
#             resp = requests.get(url, headers=HEADERS, timeout=20)
#             if resp.status_code == 200:
#                 entries = feedparser.parse(resp.content).entries
#                 break
#         except requests.RequestException:
#             pass
#         time.sleep(3 * (attempt + 1))
#     if entries is None:
#         return {"nama_tempat": place, "error": True}

#     dates, seen = [], set()
#     for e in entries[:PLACE_MAX_ITEMS]:
#         key = e.get("link") or e.get("title")
#         if key in seen:
#             continue
#         seen.add(key)
#         try:
#             d = dateparser.parse(e.published)
#             if d.tzinfo is None:
#                 d = d.replace(tzinfo=timezone.utc)
#         except Exception:
#             continue
#         if d >= place_cutoff:
#             dates.append(d)

#     return {
#         "nama_tempat": place,
#         "error": False,
#         "keyword_berita": q,
#         "jumlah_berita_6bln": len(dates),
#         "tanggal_berita_pertama": min(dates).date().isoformat() if dates else None,
#         "tanggal_berita_terakhir": max(dates).date().isoformat() if dates else None,
#     }


# # --- resume dari checkpoint (baris error akan dicoba ulang) ---
# place_done = {}
# if PLACE_CKPT.exists():
#     with PLACE_CKPT.open(encoding="utf-8") as f:
#         for line in f:
#             try:
#                 rec = json.loads(line)
#             except json.JSONDecodeError:
#                 continue
#             if not rec.get("error"):
#                 place_done[rec["nama_tempat"]] = rec

# # satu pasangan (nama_tempat, kota) per nama unik
# df_todo = (
#     df_places_final.dropna(subset=["nama_tempat"])
#     .drop_duplicates(subset="nama_tempat")[["nama_tempat", "kota_kabupaten"]]
# )
# todo = [
#     (p, c if isinstance(c, str) and c.strip() else None)
#     for p, c in df_todo.itertuples(index=False)
#     if p not in place_done
# ]
# print(f"Sudah ada: {len(place_done)} | Perlu diproses: {len(todo)}")

# _lock = threading.Lock()


# def _worker(args):
#     place, city = args
#     rec = fetch_place_news_stats(place, city)
#     time.sleep(PLACE_DELAY)
#     return rec


# with PLACE_CKPT.open("a", encoding="utf-8") as ckpt, \
#         concurrent.futures.ThreadPoolExecutor(max_workers=PLACE_WORKERS) as ex:
#     futures = [ex.submit(_worker, t) for t in todo]
#     for fut in tqdm(concurrent.futures.as_completed(futures), total=len(futures), desc="Berita per tempat"):
#         rec = fut.result()
#         with _lock:
#             ckpt.write(json.dumps(rec, ensure_ascii=False) + "\n")
#             ckpt.flush()
#         if not rec.get("error"):
#             place_done[rec["nama_tempat"]] = rec

# # --- gabungkan ke df_places_final ---
# stat_cols = ["jumlah_berita_6bln", "tanggal_berita_pertama", "tanggal_berita_terakhir"]
# df_stats = pd.DataFrame(place_done.values())[["nama_tempat", "keyword_berita"] + stat_cols]
# df_places_final = df_places_final.drop(
#     columns=[c for c in df_stats.columns if c != "nama_tempat"], errors="ignore"
# ).merge(df_stats, on="nama_tempat", how="left")

# tgl_pertama = pd.to_datetime(df_places_final["tanggal_berita_pertama"])
# tgl_terakhir = pd.to_datetime(df_places_final["tanggal_berita_terakhir"])
# df_places_final["selisih_hari"] = (tgl_terakhir - tgl_pertama).dt.days

# gagal = df_places_final["jumlah_berita_6bln"].isna().sum()
# print(f"Tempat tanpa data (gagal fetch, jalankan ulang cell ini): {gagal}")
# df_places_final[["nama_tempat", "keyword_berita"] + stat_cols + ["selisih_hari"]].head(10)

In [19]:
# Versi Google Search (tab Berita): https://www.google.com/search?q={query}&tbm=nws&hl=id&gl=ID
# Hitung jumlah berita 6 bulan terakhir per nama_tempat + tanggal pertama, terakhir, selisih hari
# -> menimpa kolom hasil dari versi RSS di df_places_final.
#
# Butuh:  pip install selenium   (+ Google Chrome; driver diunduh otomatis oleh Selenium Manager)
# Google minta JavaScript, jadi pakai browser asli (jendela Chrome terbuka, jangan ditutup).
# Kalau muncul CAPTCHA: selesaikan manual di jendela Chrome, script lanjut otomatis.
# Checkpoint per tempat ke JSONL -> aman di-resume kalau berhenti.
import random
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

PLACE_CKPT = Path("place_news_stats_google_checkpoint.jsonl")
PLACE_DAYS_BACK = 180          # ~6 bulan
MAX_PAGES = 3                  # halaman hasil per tempat (~10 berita/halaman) -> jumlah maksimal ~30
DELAY_RANGE = (3.0, 6.0)       # jeda acak antar request (detik) supaya tidak kena blokir
USE_CITY_IN_QUERY = True       # False = cari hanya berdasarkan nama_tempat
CAPTCHA_WAIT_SECONDS = 600     # batas waktu menunggu CAPTCHA diselesaikan manual
LIMIT = 100                      # tes dulu 5 tempat, cek hasil, lalu ubah ke None untuk semua

today = datetime.now()
range_start = today - timedelta(days=PLACE_DAYS_BACK)

MONTHS_ID = {"jan": 1, "feb": 2, "mar": 3, "apr": 4, "mei": 5, "jun": 6, "jul": 7,
             "agu": 8, "agt": 8, "sep": 9, "okt": 10, "nov": 11, "des": 12}
UNIT_DAYS = {"menit": 0, "jam": 0, "hari": 1, "minggu": 7, "bulan": 30, "tahun": 365}
REL_RE = re.compile(r"^(\d+)\s+(menit|jam|hari|minggu|bulan|tahun)\s+(?:yang\s+)?lalu$", re.I)
ABS_RE = re.compile(
    r"^(\d{1,2})\s+(jan|feb|mar|apr|mei|jun|jul|agu|agt|sep|okt|nov|des)[a-z]*\.?(?:\s+(\d{4}))?$", re.I
)


def parse_news_date(text: str):
    """Parse teks tanggal Google ('3 hari yang lalu', '5 Mei 2026', 'Kemarin') -> datetime, atau None."""
    t = text.strip()
    if t.lower() == "kemarin":
        return today - timedelta(days=1)
    m = REL_RE.match(t)
    if m:
        return today - timedelta(days=int(m.group(1)) * UNIT_DAYS[m.group(2).lower()])
    m = ABS_RE.match(t)
    if m:
        year = int(m.group(3)) if m.group(3) else today.year
        try:
            d = datetime(year, MONTHS_ID[m.group(2).lower()[:3]], int(m.group(1)))
        except ValueError:
            return None
        if not m.group(3) and d > today:
            d = d.replace(year=d.year - 1)
        return d
    return None


def build_google_news_url(query: str, start: int = 0) -> str:
    cd_min = f"{range_start.month}/{range_start.day}/{range_start.year}"
    cd_max = f"{today.month}/{today.day}/{today.year}"
    url = (
        f"https://www.google.com/search?q={urllib.parse.quote(query)}&tbm=nws&hl=id&gl=ID"
        f"&tbs=cdr:1,cd_min:{cd_min},cd_max:{cd_max}"
    )
    return url + (f"&start={start}" if start else "")


def parse_results(html: str) -> dict:
    """Ambil {link: tanggal} tiap kartu berita. Link hasil di Google berbentuk '/goto?url=...'
    (atau http langsung); teks tanggal ('22 Apr 2026', '43 menit yang lalu') ada di dalam <a> yang sama.
    Tidak bergantung pada nama class CSS Google."""
    soup = BeautifulSoup(html, "lxml")
    found = {}
    for a in soup.find_all("a", href=True):
        href = a["href"]
        is_result = href.startswith("/goto?url=") or (href.startswith("http") and "google." not in href)
        if not is_result:
            continue
        for el in a.find_all(["span", "div"]):
            txt = el.get_text(" ", strip=True)
            if len(txt) <= 25:
                date = parse_news_date(txt)
                if date:
                    found.setdefault(href, date)
                    break
    return found


def make_driver():
    opts = Options()
    opts.add_argument("--lang=id-ID")
    opts.add_argument("--disable-blink-features=AutomationControlled")
    opts.add_argument(f"--user-data-dir={Path('chrome_profile_news').resolve()}")  # simpan cookie antar sesi
    # chromedriver lama di PATH (mis. C:\\Selenium, v112) bikin SessionNotCreatedException;
    # buang dari PATH supaya Selenium Manager mengunduh driver yang cocok dengan versi Chrome.
    os.environ["PATH"] = os.pathsep.join(
        p for p in os.environ.get("PATH", "").split(os.pathsep)
        if not os.path.exists(os.path.join(p, "chromedriver.exe"))
    )
    return webdriver.Chrome(options=opts)


def wait_if_blocked(driver):
    """Kalau Google menampilkan CAPTCHA/'unusual traffic', tunggu sampai diselesaikan manual."""
    waited = 0
    while "/sorry/" in driver.current_url or "unusual traffic" in driver.page_source.lower():
        if waited == 0:
            print("CAPTCHA terdeteksi -> selesaikan manual di jendela Chrome...")
        if waited >= CAPTCHA_WAIT_SECONDS:
            raise RuntimeError("CAPTCHA tidak diselesaikan; jalankan ulang cell ini nanti (progres tersimpan).")
        time.sleep(5)
        waited += 5


def clean_city(city: str | None) -> str | None:
    if not isinstance(city, str) or not city.strip():
        return None
    return re.sub(r"^(kota|kabupaten|kab\.)\s+", "", city.strip(), flags=re.I)


def fetch_place_news_stats(driver, place: str, city: str | None = None) -> dict:
    q = f'{place}'
    if USE_CITY_IN_QUERY and city:
        q += f' {city}'

    all_found = {}
    for page in range(MAX_PAGES):
        driver.get(build_google_news_url(q, start=page * 10))
        time.sleep(1.5)
        wait_if_blocked(driver)
        found = parse_results(driver.page_source)
        new = {k: v for k, v in found.items() if k not in all_found}
        all_found.update(new)
        if not new or len(found) < 10:  # halaman terakhir
            break
        time.sleep(random.uniform(*DELAY_RANGE))

    dates = [d for d in all_found.values() if d >= range_start]
    return {
        "nama_tempat": place,
        "error": False,
        "keyword_berita": q,
        "jumlah_berita_6bln": len(dates),
        "tanggal_berita_pertama": min(dates).date().isoformat() if dates else None,
        "tanggal_berita_terakhir": max(dates).date().isoformat() if dates else None,
    }


# --- resume dari checkpoint ---
place_done = {}
if PLACE_CKPT.exists():
    with PLACE_CKPT.open(encoding="utf-8") as f:
        for line in f:
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            if not rec.get("error"):
                place_done[rec["nama_tempat"]] = rec

df_todo = (
    df_places_final.dropna(subset=["nama_tempat"])
    .drop_duplicates(subset="nama_tempat")[["nama_tempat", "kota_kabupaten"]]
)
todo = [(p, clean_city(c)) for p, c in df_todo.itertuples(index=False) if p not in place_done]
print(f"Sudah ada: {len(place_done)} | Perlu diproses: {len(todo)}")
if LIMIT:
    todo = todo[:LIMIT]

if todo:
    driver = make_driver()
    try:
        with PLACE_CKPT.open("a", encoding="utf-8") as ckpt:
            for place, city in tqdm(todo, desc="Berita per tempat (Google)"):
                try:
                    rec = fetch_place_news_stats(driver, place, city)
                except RuntimeError:
                    raise
                except Exception as e:
                    print(f"Gagal '{place}': {e}")
                    rec = {"nama_tempat": place, "error": True}
                ckpt.write(json.dumps(rec, ensure_ascii=False) + "\n")
                ckpt.flush()
                if not rec.get("error"):
                    place_done[place] = rec
                time.sleep(random.uniform(*DELAY_RANGE))
    finally:
        driver.quit()

# --- gabungkan ke df_places_final (menimpa hasil RSS) ---
stat_cols = ["jumlah_berita_6bln", "tanggal_berita_pertama", "tanggal_berita_terakhir"]
df_stats = pd.DataFrame(place_done.values())[["nama_tempat", "keyword_berita"] + stat_cols]
df_places_final = df_places_final.drop(
    columns=[c for c in df_stats.columns if c != "nama_tempat"] + ["selisih_hari"], errors="ignore"
).merge(df_stats, on="nama_tempat", how="left")

tgl_pertama = pd.to_datetime(df_places_final["tanggal_berita_pertama"])
tgl_terakhir = pd.to_datetime(df_places_final["tanggal_berita_terakhir"])
df_places_final["selisih_hari"] = (tgl_terakhir - tgl_pertama).dt.days

print(f"Tempat belum punya data: {df_places_final['jumlah_berita_6bln'].isna().sum()}")
# save csv
# df_places_final.to_csv("df_places_final_with_news_stats.csv", index=False)
df_places_final[["nama_tempat", "keyword_berita"] + stat_cols + ["selisih_hari"]].dropna(
    subset=["jumlah_berita_6bln"]
)

Sudah ada: 39 | Perlu diproses: 2012

Berita per tempat (Google):   0%|          | 0/100 [00:00<?, ?it/s]

CAPTCHA terdeteksi -> selesaikan manual di jendela Chrome...

Berita per tempat (Google):  29%|ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â°       | 29/100 [03:17<07:10,  6.06s/it]

CAPTCHA terdeteksi -> selesaikan manual di jendela Chrome...

Berita per tempat (Google):  40%|ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â       | 40/100 [07:00<09:31,  9.53s/it]

CAPTCHA terdeteksi -> selesaikan manual di jendela Chrome...

Berita per tempat (Google):  52%|ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€šÃ‚Â    | 52/100 [09:26<05:43,  7.17s/it]

CAPTCHA terdeteksi -> selesaikan manual di jendela Chrome...

Berita per tempat (Google):  65%|ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¦Ã¢â‚¬â„¢   | 65/100 [11:11<04:05,  7.02s/it]

CAPTCHA terdeteksi -> selesaikan manual di jendela Chrome...

Berita per tempat (Google):  79%|ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â°  | 79/100 [13:01<02:17,  6.56s/it]

CAPTCHA terdeteksi -> selesaikan manual di jendela Chrome...

Berita per tempat (Google):  92%|ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€šÃ‚Â| 92/100 [14:48<00:56,  7.04s/it]

CAPTCHA terdeteksi -> selesaikan manual di jendela Chrome...

Berita per tempat (Google): 100%|ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“Ãƒâ€¹Ã¢â‚¬Â | 100/100 [16:42<00:00, 10.02s/it]

Tempat belum punya data: 1912

,nama_tempat,keyword_berita,jumlah_berita_6bln,tanggal_berita_pertama,tanggal_berita_terakhir,selisih_hari
0,Sai Ramen,Sai Ramen Jakarta Selatan,5.0,2026-06-28,2026-10-02,96.0
1,Menya Beast,Menya Beast Jakarta Selatan,4.0,2026-09-11,2026-10-02,21.0
2,Raku Ramen,Raku Ramen Jakarta Selatan,3.0,2026-10-01,2026-10-02,1.0
3,Echigoya,Echigoya Jakarta,3.0,2026-04-22,2026-10-02,163.0
4,Warung Amanda,Warung Amanda Sidoarjo,3.0,2026-05-11,2026-09-25,137.0
...,...,...,...,...,...,...
134,Roti Bakar Eddy,Roti Bakar Eddy Jakarta Selatan,10.0,2026-04-10,2026-09-29,172.0
135,Mie Kangkung Kite,Mie Kangkung Kite Jakarta Selatan,2.0,2026-05-30,2026-09-02,95.0
136,Ayam Bakar Ganthari,Ayam Bakar Ganthari Jakarta Selatan,2.0,2026-05-14,2026-05-30,16.0
137,Ayam Bulungan,Ayam Bulungan Jakarta Selatan,19.0,2026-05-03,2026-09-25,145.0
138,Nasi Uduk Cipete,Nasi Uduk Cipete Jakarta Selatan,10.0,2026-05-22,2026-08-03,73.0

In [27]:
import os, getpass

In [28]:
# Input API key langsung di notebook (hindari masalah env var PowerShell yang suka kemasukan
# whitespace/newline tak sengaja). Key tidak ditampilkan & tidak tersimpan ke file notebook.
import getpass

_key = getpass.getpass("Masukkan Serper API key (dari https://serper.dev/api-key): ").strip()
if _key:
    os.environ["SERPER_API_KEY"] = _key
del _key

In [37]:
# Versi Serper.dev (https://serper.dev/) -- menggantikan Selenium supaya tidak kena CAPTCHA.
# Serper adalah proxy resmi ke Google Search/News; permintaan dikirim via REST API mereka,
# jadi tidak ada browser yang perlu dibuka dan tidak ada CAPTCHA yang perlu diselesaikan manual.
#
# Setup:
#   1. Daftar gratis di https://serper.dev/ (dapat 2.500 query gratis, tanpa kartu kredit).
#   2. Set API key sebagai environment variable SERPER_API_KEY (jangan hardcode di notebook).
#      PowerShell: $env:SERPER_API_KEY = "xxxxx"
#   3. pip install requests (sudah ada di cell import di atas)
#
# Checkpoint terpisah dari versi Selenium supaya tidak tercampur / bisa dibandingkan.

SERPER_API_KEY = os.environ.get("SERPER_API_KEY", "").strip()
if not SERPER_API_KEY:
    raise RuntimeError(
        "SERPER_API_KEY belum di-set. Set environment variable SERPER_API_KEY lalu restart kernel."
    )
if len(SERPER_API_KEY) > 64 or any(ch.isspace() for ch in SERPER_API_KEY):
    raise RuntimeError(
        f"SERPER_API_KEY terlihat tidak valid (panjang={len(SERPER_API_KEY)}, ada whitespace="
        f"{any(ch.isspace() for ch in SERPER_API_KEY)}). Key asli dari dashboard serper.dev "
        "biasanya ~40 karakter hex tanpa spasi/baris baru. Cek ulang cara kamu set env var-nya "
        "(mis. jangan pakai Get-Content tanpa -Raw, jangan ada kutip/newline ikut ter-copy)."
    )
print(f"SERPER_API_KEY terbaca, panjang: {len(SERPER_API_KEY)}")

SERPER_NEWS_URL = "https://google.serper.dev/news"
PLACE_CKPT_SERPER = Path("place_news_stats_google_checkpoint.jsonl")
SERPER_PAGES = 3          # halaman hasil per tempat; berhenti lebih awal kalau sudah mentok (lihat fetch_place_news_stats_serper)
SERPER_NUM = 30           # jumlah hasil yang diminta ke Serper (endpoint /news tampaknya selalu balas ~10/halaman apa pun nilainya)
SERPER_DELAY = (0.2, 0.6)  # jeda acak antar request (detik); API-nya sendiri sudah tahan rate tinggi
SERPER_MAX_RETRIES = 3
LIMIT = 3000

_serper_session = requests.Session()
_serper_session.headers.update({
    "X-API-KEY": SERPER_API_KEY,
    "Content-Type": "application/json",
})


def build_serper_payload(query: str, page: int = 1) -> dict:
    cd_min = f"{range_start.month}/{range_start.day}/{range_start.year}"
    cd_max = f"{today.month}/{today.day}/{today.year}"
    return {
        "q": query,
        "gl": "id",
        "hl": "id",
        "tbs": f"cdr:1,cd_min:{cd_min},cd_max:{cd_max}",
        "num": SERPER_NUM,
        "page": page,
    }


def parse_serper_date(item: dict):
    """Serper mengembalikan teks tanggal yang sama seperti tampilan Google ('3 hari yang lalu',
    '5 Mei 2026', dst), jadi dipakai ulang parser yang sama. Fallback ke dateutil kalau gagal."""
    text = item.get("date", "")
    if not text:
        return None
    d = parse_news_date(text)
    if d:
        return d
    try:
        d = dateparser.parse(text, default=today)
        if d and d <= today:
            return d
    except (ValueError, OverflowError):
        pass
    return None


def fetch_place_news_stats_serper(place: str, city: str | None = None) -> dict:
    q = f'{place}'
    if USE_CITY_IN_QUERY and city:
        q += f' {city}'

    all_found = {}
    for page in range(1, SERPER_PAGES + 1):
        payload = build_serper_payload(q, page=page)
        resp = None
        last_err = None
        for attempt in range(SERPER_MAX_RETRIES):
            try:
                resp = _serper_session.post(SERPER_NEWS_URL, json=payload, timeout=20)
                if resp.status_code == 200:
                    break
                if resp.status_code == 429:
                    time.sleep(5 * (attempt + 1))
                    continue
                resp.raise_for_status()
            except requests.RequestException as e:
                last_err = e
                resp = None
                time.sleep(2 * (attempt + 1))
        if resp is None or resp.status_code != 200:
            status = resp.status_code if resp else None
            raise RuntimeError(f"Serper gagal (status={status}): {last_err}")

        items = resp.json().get("news", [])
        if not items:  # halaman kosong -> sudah mentok
            break
        new = {}
        for item in items:
            link = item.get("link")
            if not link or link in all_found:
                continue
            d = parse_serper_date(item)
            if d:
                new[link] = d
        all_found.update(new)
        if not new:  # halaman berikutnya cuma mengulang hasil yang sama -> sudah mentok
            break
        time.sleep(random.uniform(*SERPER_DELAY))

    dates = [d for d in all_found.values() if d >= range_start]
    return {
        "nama_tempat": place,
        "error": False,
        "keyword_berita": q,
        "jumlah_berita_6bln": len(dates),
        "tanggal_berita_pertama": min(dates).date().isoformat() if dates else None,
        "tanggal_berita_terakhir": max(dates).date().isoformat() if dates else None,
    }


# --- resume dari checkpoint ---
place_done_serper = {}
if PLACE_CKPT_SERPER.exists():
    with PLACE_CKPT_SERPER.open(encoding="utf-8") as f:
        for line in f:
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            if not rec.get("error"):
                place_done_serper[rec["nama_tempat"]] = rec

df_todo_serper = (
    df_places_final.dropna(subset=["nama_tempat"])
    .drop_duplicates(subset="nama_tempat")[["nama_tempat", "kota_kabupaten"]]
)
todo_serper = [
    (p, clean_city(c)) for p, c in df_todo_serper.itertuples(index=False) if p not in place_done_serper
]
print(f"Sudah ada: {len(place_done_serper)} | Perlu diproses: {len(todo_serper)}")
if LIMIT:
    todo_serper = todo_serper[:LIMIT]

if todo_serper:
    with PLACE_CKPT_SERPER.open("a", encoding="utf-8") as ckpt:
        for place, city in tqdm(todo_serper, desc="Berita per tempat (Serper)"):
            try:
                rec = fetch_place_news_stats_serper(place, city)
            except Exception as e:
                print(f"Gagal '{place}': {e}")
                rec = {"nama_tempat": place, "error": True}
            ckpt.write(json.dumps(rec, ensure_ascii=False) + "\n")
            ckpt.flush()
            if not rec.get("error"):
                place_done_serper[place] = rec
            time.sleep(random.uniform(*SERPER_DELAY))

# --- gabungkan ke df_places_final (menimpa hasil versi Selenium/RSS) ---
stat_cols = ["jumlah_berita_6bln", "tanggal_berita_pertama", "tanggal_berita_terakhir"]
df_stats_serper = pd.DataFrame(place_done_serper.values())[["nama_tempat", "keyword_berita"] + stat_cols]
df_places_final = df_places_final.drop(
    columns=[c for c in df_stats_serper.columns if c != "nama_tempat"] + ["selisih_hari"], errors="ignore"
).merge(df_stats_serper, on="nama_tempat", how="left")

tgl_pertama = pd.to_datetime(df_places_final["tanggal_berita_pertama"])
tgl_terakhir = pd.to_datetime(df_places_final["tanggal_berita_terakhir"])
df_places_final["selisih_hari"] = (tgl_terakhir - tgl_pertama).dt.days

print(f"Tempat belum punya data: {df_places_final['jumlah_berita_6bln'].isna().sum()}")
df_places_final[["nama_tempat", "keyword_berita"] + stat_cols + ["selisih_hari"]].dropna(
    subset=["jumlah_berita_6bln"]
)

SERPER_API_KEY terbaca, panjang: 40
Sudah ada: 316 | Perlu diproses: 1735

Berita per tempat (Serper):   0%|          | 0/1735 [00:00<?, ?it/s]

Berita per tempat (Serper):  15%|█▍        | 260/1735 [13:18<1:16:08,  3.10s/it]

Gagal 'Pecel "Senggol" Beringharjo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  63%|██████▎   | 1098/1735 [59:30<42:36,  4.01s/it]

Gagal 'Singapore Oceanarium': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  63%|██████▎   | 1099/1735 [59:44<1:13:58,  6.98s/it]

Gagal 'Mandai Wildlife Reserve': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  63%|██████▎   | 1100/1735 [59:56<1:31:25,  8.64s/it]

Gagal 'Floral Fantasy Gardens by the Bay': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  63%|██████▎   | 1101/1735 [1:00:09<1:43:11,  9.77s/it]

Gagal 'Children's Museum Singapore': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▎   | 1102/1735 [1:00:24<2:01:46, 11.54s/it]

Gagal 'Museum of Ice Cream': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▎   | 1103/1735 [1:00:37<2:04:04, 11.78s/it]

Gagal 'ArtScience Museum': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▎   | 1104/1735 [1:00:49<2:06:01, 11.98s/it]

Gagal 'Wisata Sungai Misland': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▎   | 1105/1735 [1:01:02<2:07:16, 12.12s/it]

Gagal 'Wisata Batu Belah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▎   | 1106/1735 [1:01:14<2:07:42, 12.18s/it]

Gagal 'Tourism Seminar Destination 3S Malaysia': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1107/1735 [1:01:26<2:08:07, 12.24s/it]

Gagal 'Roti Prata Pujasera Tiban Centre': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1108/1735 [1:01:39<2:08:02, 12.25s/it]

Gagal 'Mie Tarempa Tiban Center': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1109/1735 [1:01:51<2:08:23, 12.31s/it]

Gagal 'Morning Bakery Tiban': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1110/1735 [1:02:03<2:08:18, 12.32s/it]

Gagal 'Sarapan Pagi Bu Sri': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1111/1735 [1:02:16<2:08:35, 12.37s/it]

Gagal 'Morning Bakery': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1112/1735 [1:02:28<2:08:52, 12.41s/it]

Gagal 'Tempat Makan Kopitiam': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1113/1735 [1:02:41<2:09:21, 12.48s/it]

Gagal 'Kez's Bakery & Restaurant': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1114/1735 [1:02:54<2:09:32, 12.52s/it]

Gagal 'La Kopi Cafe & Resto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1115/1735 [1:03:06<2:09:08, 12.50s/it]

Gagal 'Lontong Sayur Jalan Bengkong Baru': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1116/1735 [1:03:19<2:09:02, 12.51s/it]

Gagal 'Mentari Kopitiam Pasir Putih': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1117/1735 [1:03:31<2:08:25, 12.47s/it]

Gagal 'Mie Tarempa Bengkong': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1118/1735 [1:03:44<2:08:42, 12.52s/it]

Gagal 'Rumah Makan Bawean': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  64%|██████▍   | 1119/1735 [1:03:56<2:08:29, 12.51s/it]

Gagal 'Mie Tarempa Sungai Panas': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▍   | 1120/1735 [1:04:09<2:07:37, 12.45s/it]

Gagal 'Rumah Makan Pagi Sore Batam': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▍   | 1121/1735 [1:04:21<2:07:43, 12.48s/it]

Gagal 'Warung Antique': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▍   | 1122/1735 [1:04:34<2:08:06, 12.54s/it]

Gagal 'Sop Tulang Sapi Nunung': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▍   | 1123/1735 [1:04:46<2:07:37, 12.51s/it]

Gagal 'Baa Baa Kambing': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▍   | 1124/1735 [1:04:59<2:06:53, 12.46s/it]

Gagal 'Brother Seafood NFC': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▍   | 1125/1735 [1:05:11<2:06:10, 12.41s/it]

Gagal 'Pecal Sabar Menanti': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▍   | 1126/1735 [1:05:23<2:05:45, 12.39s/it]

Gagal 'Kenangan Coffee Hub Gading Serpong': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▍   | 1127/1735 [1:05:36<2:05:31, 12.39s/it]

Gagal 'Golden Prawn': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▌   | 1128/1735 [1:05:48<2:05:21, 12.39s/it]

Gagal 'Festival Kompang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▌   | 1129/1735 [1:06:01<2:05:45, 12.45s/it]

Gagal 'Gelar Budaya Pulau Penyengat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▌   | 1130/1735 [1:06:13<2:05:29, 12.44s/it]

Gagal 'Bintan Resort Night Parade': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▌   | 1131/1735 [1:06:25<2:04:52, 12.41s/it]

Gagal 'Dekranasda Tanjungpinang Fun and Run 5K & 10K': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▌   | 1132/1735 [1:06:38<2:04:50, 12.42s/it]

Gagal 'Festival Kopi Merdeka': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▌   | 1133/1735 [1:06:50<2:05:01, 12.46s/it]

Gagal 'Tour de Bintan 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▌   | 1134/1735 [1:07:03<2:05:04, 12.49s/it]

Gagal 'Indonesia Tourism & Trade Investment Expo (ITTIE) 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▌   | 1135/1735 [1:07:15<2:04:33, 12.46s/it]

Gagal 'Kemilau Nusantara Kepri 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  65%|██████▌   | 1136/1735 [1:07:28<2:04:26, 12.47s/it]

Gagal 'Penyengat Heritage 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1137/1735 [1:07:40<2:04:34, 12.50s/it]

Gagal 'Taman Budaya Nyat Kadir': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1138/1735 [1:07:53<2:04:43, 12.54s/it]

Gagal 'Pulau Katang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1139/1735 [1:08:05<2:04:36, 12.55s/it]

Gagal 'Pulau Benan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1140/1735 [1:08:18<2:03:41, 12.47s/it]

Gagal 'Dragon Boat Race 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1141/1735 [1:08:30<2:03:16, 12.45s/it]

Gagal 'Bintan E-Sport Championship 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1143/1735 [1:08:55<2:02:16, 12.39s/it]

Gagal 'Semarak Anambas 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news
Gagal 'Jembatan Barelang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1144/1735 [1:09:07<2:02:12, 12.41s/it]

Gagal 'Landmark Welcome to Batam Bukit Clara': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1145/1735 [1:09:20<2:01:52, 12.39s/it]

Gagal 'Dataran Engku Putri': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1146/1735 [1:09:32<2:02:18, 12.46s/it]

Gagal 'Museum Raja Ali Haji Batam': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1147/1735 [1:09:45<2:02:41, 12.52s/it]

Gagal 'Masjid Sultan Mahmud Riayat Syah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1148/1735 [1:09:57<2:02:01, 12.47s/it]

Gagal 'Pollux Meisterstadt Habibie': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▌   | 1149/1735 [1:10:10<2:02:13, 12.51s/it]

Gagal 'Treasure Bay Bintan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▋   | 1150/1735 [1:10:22<2:01:34, 12.47s/it]

Gagal 'Kawasan Tepi Laut Tanjungpinang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▋   | 1151/1735 [1:10:35<2:01:20, 12.47s/it]

Gagal 'Laman Boenda': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▋   | 1152/1735 [1:10:47<2:01:34, 12.51s/it]

Gagal 'Gedung Gonggong': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  66%|██████▋   | 1153/1735 [1:11:00<2:01:00, 12.48s/it]

Gagal 'Pulau Penyengat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1154/1735 [1:11:12<2:00:34, 12.45s/it]

Gagal 'Masjid Raya Sultan Riau': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1155/1735 [1:11:25<2:00:59, 12.52s/it]

Gagal 'Taman Gurindam 12': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1156/1735 [1:11:37<2:00:42, 12.51s/it]

Gagal 'Monumen Tugu Bahasa Nasional': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1157/1735 [1:11:50<2:00:54, 12.55s/it]

Gagal 'Museum Bahasa Pulau Penyengat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1158/1735 [1:12:03<2:00:52, 12.57s/it]

Gagal 'ASITA Kepri Travel Mart 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1159/1735 [1:12:15<2:00:06, 12.51s/it]

Gagal 'Kenduri Seni Melayu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1160/1735 [1:12:27<1:59:37, 12.48s/it]

Gagal 'Nirwana Garden Bintan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1161/1735 [1:12:40<1:59:05, 12.45s/it]

Gagal 'Festival Mandi Safar': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1162/1735 [1:12:52<1:58:54, 12.45s/it]

Gagal 'Kenduri dan Festival Durian Bentan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1163/1735 [1:13:05<1:59:02, 12.49s/it]

Gagal 'Masjid Raya Sultan Riau Penyengat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1164/1735 [1:13:17<1:58:45, 12.48s/it]

Gagal 'Balai Adat Pulau Penyengat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1165/1735 [1:13:30<1:58:57, 12.52s/it]

Gagal 'Gunung Bromo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1166/1735 [1:13:42<1:58:56, 12.54s/it]

Gagal 'First Hotel & KTV': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1167/1735 [1:13:55<1:58:47, 12.55s/it]

Gagal 'Kawasan Lagoi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1168/1735 [1:14:08<1:58:44, 12.57s/it]

Gagal 'Wisata Religi Yayasan Duta Dharma Agung': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1169/1735 [1:14:20<1:58:51, 12.60s/it]

Gagal 'Pulau Berhala': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1170/1735 [1:14:33<1:57:54, 12.52s/it]

Gagal 'Kali Cokel': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  67%|██████▋   | 1171/1735 [1:14:45<1:57:06, 12.46s/it]

Gagal 'Dapur Allung': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1172/1735 [1:14:57<1:57:03, 12.47s/it]

Gagal 'Pondok Pindang Sarinande': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1173/1735 [1:15:10<1:56:24, 12.43s/it]

Gagal 'Warung Pindang Bi Cik': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1174/1735 [1:15:22<1:56:13, 12.43s/it]

Gagal 'Pempek Selamat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1175/1735 [1:15:35<1:55:59, 12.43s/it]

Gagal 'Pempek Asiong': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1176/1735 [1:15:47<1:56:09, 12.47s/it]

Gagal 'Saoenk Kito': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1177/1735 [1:16:00<1:55:44, 12.45s/it]

Gagal 'Saung Purnama': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1178/1735 [1:16:12<1:55:11, 12.41s/it]

Gagal 'Rumah Makan Bikcik Way': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1179/1735 [1:16:24<1:55:14, 12.44s/it]

Gagal 'BeanStar Coffee': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1180/1735 [1:16:37<1:55:21, 12.47s/it]

Gagal 'Festival Pesta Rakyat Petani Kopi Kerinci 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1181/1735 [1:16:49<1:55:13, 12.48s/it]

Gagal 'Cafe Gudhas': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1182/1735 [1:17:02<1:55:26, 12.52s/it]

Gagal 'Danau Letang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1183/1735 [1:17:14<1:54:53, 12.49s/it]

Gagal 'Danau Sigombak': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1184/1735 [1:17:27<1:54:42, 12.49s/it]

Gagal 'Danau Kerinci': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1185/1735 [1:17:39<1:54:10, 12.46s/it]

Gagal 'Danau Kaco': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1186/1735 [1:17:52<1:53:43, 12.43s/it]

Gagal 'Danau Sipin': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1187/1735 [1:18:04<1:54:01, 12.48s/it]

Gagal 'Genzhi Cafe and Resto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  68%|██████▊   | 1188/1735 [1:18:17<1:53:46, 12.48s/it]

Gagal 'Cloud Nine Coffee & Eatery': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▊   | 1189/1735 [1:18:29<1:53:08, 12.43s/it]

Gagal 'Rumah Makan Padang Pagi Sore (cabang PIK)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▊   | 1190/1735 [1:18:42<1:52:53, 12.43s/it]

Gagal 'Babylon Garden Affair': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▊   | 1191/1735 [1:18:54<1:53:11, 12.48s/it]

Gagal 'Rumah Makan Cempaka Sari': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▊   | 1192/1735 [1:19:07<1:53:02, 12.49s/it]

Gagal 'Bakso Malang Cak Wawan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1193/1735 [1:19:19<1:52:54, 12.50s/it]

Gagal 'Yoshinoya': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1194/1735 [1:19:32<1:52:43, 12.50s/it]

Gagal 'Dapur Solo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1195/1735 [1:19:44<1:52:28, 12.50s/it]

Gagal 'Ramen1': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1196/1735 [1:19:57<1:52:16, 12.50s/it]

Gagal 'Masjid Agung Al-Falah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1197/1735 [1:20:09<1:51:50, 12.47s/it]

Gagal 'Candi Muaro Jambi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1198/1735 [1:20:22<1:51:38, 12.47s/it]

Gagal 'Makam Sultan Thaha Syaifuddin': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1199/1735 [1:20:34<1:51:38, 12.50s/it]

Gagal 'Menara Gentala Arasy': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1200/1735 [1:20:47<1:51:25, 12.50s/it]

Gagal 'Pura Giri Indra Loka': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1201/1735 [1:20:59<1:51:11, 12.49s/it]

Gagal 'Vihara Sakyakirti': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1202/1735 [1:21:11<1:50:35, 12.45s/it]

Gagal 'Makam Raja-Raja Jambi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1203/1735 [1:21:24<1:50:48, 12.50s/it]

Gagal 'Danau Gunung Tujuh': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1204/1735 [1:21:37<1:50:43, 12.51s/it]

Gagal 'Geopark Merangin': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  69%|██████▉   | 1205/1735 [1:21:49<1:50:04, 12.46s/it]

Gagal 'Perkebunan Teh Kayu Aro': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|██████▉   | 1206/1735 [1:22:01<1:49:46, 12.45s/it]

Gagal 'Jambi Paradise': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|██████▉   | 1207/1735 [1:22:14<1:49:29, 12.44s/it]

Gagal 'Kampung Batik Ulu Gedong': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|██████▉   | 1208/1735 [1:22:26<1:48:57, 12.41s/it]

Gagal 'Gunung Kerinci': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|██████▉   | 1209/1735 [1:22:39<1:48:44, 12.40s/it]

Gagal 'Bukit Khayangan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|██████▉   | 1210/1735 [1:22:51<1:48:54, 12.45s/it]

Gagal 'Air Terjun Telun Berasap': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|██████▉   | 1211/1735 [1:23:03<1:48:16, 12.40s/it]

Gagal 'Taman Nasional Kerinci Seblat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|██████▉   | 1212/1735 [1:23:16<1:48:32, 12.45s/it]

Gagal 'Jembatan Gentala Arasy': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|██████▉   | 1213/1735 [1:23:28<1:48:23, 12.46s/it]

Gagal 'Air Terjun Sungai Manau': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|██████▉   | 1214/1735 [1:23:41<1:47:54, 12.43s/it]

Gagal 'Kawasan Wisata Kuliner Kota Tua Pasar Jambi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|███████   | 1215/1735 [1:23:53<1:48:20, 12.50s/it]

Gagal 'Jambi Park': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|███████   | 1216/1735 [1:24:06<1:47:44, 12.45s/it]

Gagal 'Pasar Budaya Lopak Sepang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|███████   | 1217/1735 [1:24:18<1:47:22, 12.44s/it]

Gagal 'Festival Batanghari': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|███████   | 1218/1735 [1:24:31<1:47:29, 12.48s/it]

Gagal 'World of Water': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|███████   | 1219/1735 [1:24:43<1:47:10, 12.46s/it]

Gagal 'Danau Retensi Telago Kajang Lako': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|███████   | 1220/1735 [1:24:56<1:47:24, 12.51s/it]

Gagal 'Danau Pauh': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|███████   | 1221/1735 [1:25:08<1:47:29, 12.55s/it]

Gagal 'Danau Tangkas': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|███████   | 1222/1735 [1:25:21<1:47:05, 12.53s/it]

Gagal 'Minang Festival Jambi 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  70%|███████   | 1223/1735 [1:25:33<1:47:01, 12.54s/it]

Gagal 'Taman Banjuran Budayo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1224/1735 [1:25:46<1:46:44, 12.53s/it]

Gagal 'Museum Sriwijaya Dharmakirti': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1225/1735 [1:25:59<1:46:49, 12.57s/it]

Gagal 'Taman Wisata Jambi Paradise': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1226/1735 [1:26:11<1:46:00, 12.50s/it]

Gagal 'Aek Tumpah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1227/1735 [1:26:23<1:45:49, 12.50s/it]

Gagal 'Wonderlab': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1228/1735 [1:26:36<1:45:51, 12.53s/it]

Gagal 'Telaga Biru Jangkat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1229/1735 [1:26:49<1:45:48, 12.55s/it]

Gagal 'Kebun Teh Kayu Aro': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1230/1735 [1:27:01<1:45:13, 12.50s/it]

Gagal 'Kebun Kelengkeng Nur Usman': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1231/1735 [1:27:14<1:44:59, 12.50s/it]

Gagal 'Pekan Budaya Pariwisata Jambi Elok Nian 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1232/1735 [1:27:26<1:44:18, 12.44s/it]

Gagal 'Kawasan Kota Tua Pasar Jambi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1233/1735 [1:27:38<1:44:21, 12.47s/it]

Gagal 'Mie Celor 26 Ilir H. M. Syafei Z.': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1234/1735 [1:27:51<1:44:37, 12.53s/it]

Gagal 'Martabak HAR Simpang Sekip': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1235/1735 [1:28:03<1:44:04, 12.49s/it]

Gagal 'Rumah Makan Pindang Musi Rawas': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████   | 1236/1735 [1:28:16<1:43:49, 12.48s/it]

Gagal 'Nasi Cia': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████▏  | 1237/1735 [1:28:28<1:43:12, 12.43s/it]

Gagal 'Pempek & Es Kacang Vico': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████▏  | 1238/1735 [1:28:41<1:43:32, 12.50s/it]

Gagal 'Pempek Kiki': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████▏  | 1239/1735 [1:28:54<1:43:42, 12.55s/it]

Gagal 'Pempek Cik Puan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  71%|███████▏  | 1240/1735 [1:29:06<1:43:06, 12.50s/it]

Gagal 'Belido House': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1241/1735 [1:29:18<1:42:42, 12.47s/it]

Gagal 'Kampoeng Palembang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1242/1735 [1:29:31<1:42:53, 12.52s/it]

Gagal 'Asuk Koboy': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1243/1735 [1:29:43<1:42:08, 12.46s/it]

Gagal 'RM Sri Melayu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1244/1735 [1:29:56<1:42:19, 12.50s/it]

Gagal 'Kopitiam Palembang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1245/1735 [1:30:09<1:42:28, 12.55s/it]

Gagal 'Bebek Carok': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1246/1735 [1:30:21<1:41:55, 12.51s/it]

Gagal 'Baropi Grill': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1247/1735 [1:30:34<1:42:02, 12.55s/it]

Gagal 'Madam Lee Korean BBQ': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1248/1735 [1:30:46<1:42:01, 12.57s/it]

Gagal 'GRISE (Grill, Suki, Coffee & Eatery)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1249/1735 [1:30:59<1:41:11, 12.49s/it]

Gagal 'HungryPedia Lahat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1250/1735 [1:31:11<1:41:04, 12.50s/it]

Gagal 'Ayam Goreng Cibiuk': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1251/1735 [1:31:24<1:41:11, 12.54s/it]

Gagal 'Ayam Goreng Nelongso': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1252/1735 [1:31:36<1:40:52, 12.53s/it]

Gagal 'Ayam Goreng SPG (Sambal Pedas Gurih)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1253/1735 [1:31:49<1:40:26, 12.50s/it]

Gagal 'Ayam Goreng Suniaratu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1254/1735 [1:32:01<1:40:04, 12.48s/it]

Gagal 'Ayam Goreng Si Bungsu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1255/1735 [1:32:13<1:39:37, 12.45s/it]

Gagal 'Ayam Penyet Bu Erte': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1256/1735 [1:32:26<1:39:37, 12.48s/it]

Gagal 'Jembatan Kewek': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  72%|███████▏  | 1257/1735 [1:32:38<1:39:26, 12.48s/it]

Gagal 'Kafe Panhead': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1258/1735 [1:32:51<1:39:04, 12.46s/it]

Gagal 'Jacobson Van Den Berg & Co': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1259/1735 [1:33:03<1:39:04, 12.49s/it]

Gagal 'Lestari Resto Cafe & Karaoke': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1260/1735 [1:33:16<1:39:16, 12.54s/it]

Gagal 'Cafe MNC': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1261/1735 [1:33:29<1:38:46, 12.50s/it]

Gagal 'Cafe de'Clan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1262/1735 [1:33:41<1:38:51, 12.54s/it]

Gagal 'Creative Hub TVRI Sumatera Selatan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1263/1735 [1:33:54<1:38:19, 12.50s/it]

Gagal 'LINE BOX': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1264/1735 [1:34:06<1:38:00, 12.48s/it]

Gagal 'Stadion Bumi Sriwijaya': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1265/1735 [1:34:19<1:37:55, 12.50s/it]

Gagal 'RJ's Bar Aryaduta Palembang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1266/1735 [1:34:31<1:38:02, 12.54s/it]

Gagal 'Novotel Palembang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1267/1735 [1:34:44<1:37:23, 12.49s/it]

Gagal 'Tomoro Coffee Lemabang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1268/1735 [1:34:56<1:37:11, 12.49s/it]

Gagal 'Fadhil Bar Bar': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1269/1735 [1:35:08<1:36:45, 12.46s/it]

Gagal 'Plaza Benteng Kuto Besak (BKB)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1270/1735 [1:35:21<1:36:44, 12.48s/it]

Gagal 'Kopi Ali Sudirman': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1271/1735 [1:35:33<1:36:22, 12.46s/it]

Gagal 'McDonald's R. Sukamto Palembang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1272/1735 [1:35:46<1:35:49, 12.42s/it]

Gagal 'Infinity Pool Salatin Hotel Palembang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1273/1735 [1:35:58<1:35:23, 12.39s/it]

Gagal 'Kedai Kiry': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1274/1735 [1:36:11<1:35:50, 12.47s/it]

Gagal 'Pojok Tembesu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  73%|███████▎  | 1275/1735 [1:36:23<1:35:52, 12.50s/it]

Gagal 'Palembang Indah Mall (PIM)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▎  | 1276/1735 [1:36:36<1:36:03, 12.56s/it]

Gagal 'Gyukaku': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▎  | 1277/1735 [1:36:49<1:35:57, 12.57s/it]

Gagal 'Bingxue Sukabangun': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▎  | 1278/1735 [1:37:01<1:35:57, 12.60s/it]

Gagal 'Desa Wisata Gunung Dempo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▎  | 1279/1735 [1:37:14<1:35:44, 12.60s/it]

Gagal 'Sawah Namang Pelangi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1280/1735 [1:37:26<1:35:28, 12.59s/it]

Gagal 'Tan Kopi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1281/1735 [1:37:39<1:35:15, 12.59s/it]

Gagal 'Zyla Coffee': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1282/1735 [1:37:51<1:34:52, 12.57s/it]

Gagal 'Air Lintang Indah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1283/1735 [1:38:04<1:34:36, 12.56s/it]

Gagal 'Pantai Mutun': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1284/1735 [1:38:16<1:34:05, 12.52s/it]

Gagal 'Danau Ranau': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1285/1735 [1:38:29<1:33:28, 12.46s/it]

Gagal 'Air Terjun Putri Malu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1286/1735 [1:38:41<1:33:19, 12.47s/it]

Gagal 'Bukit Sakura': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1287/1735 [1:38:54<1:32:52, 12.44s/it]

Gagal 'Pulau Kelagian': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1288/1735 [1:39:06<1:32:27, 12.41s/it]

Gagal 'Taman Nasional Way Kambas': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1289/1735 [1:39:18<1:32:18, 12.42s/it]

Gagal 'Air Terjun Cuhup Pendahatan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1290/1735 [1:39:31<1:32:38, 12.49s/it]

Gagal 'Bukit Tungguan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1291/1735 [1:39:44<1:32:34, 12.51s/it]

Gagal 'Persawahan Kertapati (Lorong Abu Yasin)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  74%|███████▍  | 1292/1735 [1:39:56<1:31:54, 12.45s/it]

Gagal 'Bukit Sulap': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▍  | 1293/1735 [1:40:08<1:31:24, 12.41s/it]

Gagal 'Air Terjun Temam': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▍  | 1294/1735 [1:40:21<1:31:33, 12.46s/it]

Gagal 'Kampung Kapitan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▍  | 1295/1735 [1:40:33<1:31:32, 12.48s/it]

Gagal 'Kampung Al Munawar': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▍  | 1296/1735 [1:40:46<1:31:20, 12.48s/it]

Gagal 'Wisata Danau Biru Ogan Ilir': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▍  | 1297/1735 [1:40:58<1:31:14, 12.50s/it]

Gagal 'CFD Palembang (Bundaran Air Mancur - Jembatan Ampera)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▍  | 1298/1735 [1:41:11<1:30:52, 12.48s/it]

Gagal 'CFD Ampera': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▍  | 1299/1735 [1:41:23<1:31:04, 12.53s/it]

Gagal 'Kebun Raya Dempo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▍  | 1300/1735 [1:41:36<1:30:19, 12.46s/it]

Gagal 'Dusun Camp Riverside Glamping': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▍  | 1301/1735 [1:41:48<1:30:22, 12.49s/it]

Gagal 'Tugu Rimau': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▌  | 1302/1735 [1:42:01<1:29:53, 12.46s/it]

Gagal 'Oziel Amazing Garden': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▌  | 1303/1735 [1:42:13<1:29:29, 12.43s/it]

Gagal 'Green Paradise': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▌  | 1304/1735 [1:42:26<1:29:33, 12.47s/it]

Gagal 'Objek Wisata Cemerlang Asri': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▌  | 1305/1735 [1:42:38<1:29:27, 12.48s/it]

Gagal 'Pantai Tanjung Tinggi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▌  | 1306/1735 [1:42:51<1:28:59, 12.45s/it]

Gagal 'Lempah Kuning Muara': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▌  | 1307/1735 [1:43:03<1:29:02, 12.48s/it]

Gagal 'Warung Lempah Kuning Bang Agoes': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▌  | 1308/1735 [1:43:16<1:29:11, 12.53s/it]

Gagal 'Lempah Kuning Muket': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  75%|███████▌  | 1309/1735 [1:43:28<1:29:10, 12.56s/it]

Gagal 'Lempah Kuning PC46': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1310/1735 [1:43:41<1:29:09, 12.59s/it]

Gagal 'Mie Ayam Bangka Fina': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1311/1735 [1:43:53<1:28:17, 12.50s/it]

Gagal 'Coffee Shop Antara': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1312/1735 [1:44:06<1:28:21, 12.53s/it]

Gagal 'Bebek Stania': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1313/1735 [1:44:18<1:27:56, 12.50s/it]

Gagal 'Restoran Gale-Gale': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1314/1735 [1:44:31<1:27:43, 12.50s/it]

Gagal 'Destar Point': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1315/1735 [1:44:43<1:27:26, 12.49s/it]

Gagal 'Alun-Alun Taman Merdeka': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1316/1735 [1:44:56<1:27:11, 12.49s/it]

Gagal 'Bukit Dealova': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1317/1735 [1:45:08<1:27:03, 12.50s/it]

Gagal 'Wihelmina Park': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1318/1735 [1:45:21<1:27:00, 12.52s/it]

Gagal 'Pantai Tanjung Kelayang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1319/1735 [1:45:33<1:26:38, 12.50s/it]

Gagal 'Pulau Lengkuas': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1320/1735 [1:45:46<1:26:21, 12.49s/it]

Gagal 'Pulau Kepayang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▌  | 1322/1735 [1:46:11<1:25:34, 12.43s/it]

Gagal 'Pantai Tuing Indah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news
Gagal 'Belitung UNESCO Global Geopark': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▋  | 1323/1735 [1:46:23<1:25:45, 12.49s/it]

Gagal 'BN Zoo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▋  | 1324/1735 [1:46:36<1:25:44, 12.52s/it]

Gagal 'Air Panas Nyelanding': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▋  | 1325/1735 [1:46:48<1:25:38, 12.53s/it]

Gagal 'Air Panas Permis': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▋  | 1326/1735 [1:47:01<1:25:43, 12.57s/it]

Gagal 'Bubble Waterboom': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  76%|███████▋  | 1327/1735 [1:47:13<1:25:05, 12.51s/it]

Gagal 'Benteng Toboali': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1328/1735 [1:47:26<1:25:09, 12.55s/it]

Gagal 'Bukit Kejora': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1329/1735 [1:47:38<1:24:37, 12.51s/it]

Gagal 'Pantai Batu Beriga': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1330/1735 [1:47:51<1:24:17, 12.49s/it]

Gagal 'Bukit Berungkai': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1331/1735 [1:48:03<1:23:46, 12.44s/it]

Gagal 'Cemara Beach Resort': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1332/1735 [1:48:16<1:23:30, 12.43s/it]

Gagal 'Museum Kata Andrea Hirata': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1333/1735 [1:48:28<1:23:17, 12.43s/it]

Gagal 'Replika SD Laskar Pelangi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1334/1735 [1:48:40<1:23:04, 12.43s/it]

Gagal 'Leebong Island Resort': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1335/1735 [1:48:53<1:22:50, 12.43s/it]

Gagal 'Danau Kaolin (Kulong Biru)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1336/1735 [1:49:06<1:23:05, 12.50s/it]

Gagal 'Pantai Parai Tenggiri': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1337/1735 [1:49:18<1:23:12, 12.54s/it]

Gagal 'Bangka Botanical Garden (BBG)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1338/1735 [1:49:31<1:22:50, 12.52s/it]

Gagal 'Museum Timah Indonesia': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1339/1735 [1:49:43<1:22:12, 12.46s/it]

Gagal 'Agrowisata Kelekak Durian': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1340/1735 [1:49:55<1:21:47, 12.42s/it]

Gagal 'Goa Batu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1341/1735 [1:50:08<1:21:40, 12.44s/it]

Gagal 'Batu Kelambu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1342/1735 [1:50:20<1:21:52, 12.50s/it]

Gagal 'Pantai Baru Tanjung Kalian': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1343/1735 [1:50:33<1:22:01, 12.55s/it]

Gagal 'Taman Bintang Samudra': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  77%|███████▋  | 1344/1735 [1:50:46<1:21:49, 12.56s/it]

Gagal 'Aik Biru Bukit Senja': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1345/1735 [1:50:58<1:21:18, 12.51s/it]

Gagal 'Pantai Tanjung Pesona': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1346/1735 [1:51:11<1:20:58, 12.49s/it]

Gagal 'Sungailiat Triathlon 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1347/1735 [1:51:23<1:20:45, 12.49s/it]

Gagal 'Alun-alun Simpang Lima Toboali': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1348/1735 [1:51:36<1:20:49, 12.53s/it]

Gagal 'Desa Wisata Kolong Cepakek': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1349/1735 [1:51:48<1:20:22, 12.49s/it]

Gagal 'Festival Namul Hasil Bumi Jering': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1350/1735 [1:52:01<1:20:24, 12.53s/it]

Gagal 'Pantai Wisata Tanjung Pendam': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1351/1735 [1:52:13<1:19:49, 12.47s/it]

Gagal 'Grand Final Bujang Dayang Belitung 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1352/1735 [1:52:26<1:19:38, 12.48s/it]

Gagal 'Ketoprak Lapangan Golf': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1353/1735 [1:52:38<1:19:08, 12.43s/it]

Gagal 'Ketoprak Pos': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1354/1735 [1:52:50<1:18:47, 12.41s/it]

Gagal 'Dangau Datuk': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1355/1735 [1:53:03<1:18:36, 12.41s/it]

Gagal 'Kedai Pesonk': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1356/1735 [1:53:15<1:18:22, 12.41s/it]

Gagal 'Kampoeng Pesisir': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1357/1735 [1:53:27<1:18:03, 12.39s/it]

Gagal 'Rumah Makan Takana Juo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1358/1735 [1:53:40<1:18:22, 12.47s/it]

Gagal 'Restoran Pindang 77': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1359/1735 [1:53:52<1:18:05, 12.46s/it]

Gagal 'Restoran Sari Eco': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1360/1735 [1:54:05<1:18:04, 12.49s/it]

Gagal 'Raflesia Beach Resto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  78%|███████▊  | 1361/1735 [1:54:18<1:17:54, 12.50s/it]

Gagal 'Sultan Coffee Pantai Panjang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▊  | 1362/1735 [1:54:30<1:17:44, 12.50s/it]

Gagal 'Cafe Kana': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▊  | 1363/1735 [1:54:43<1:17:48, 12.55s/it]

Gagal 'Bar Black Rock': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▊  | 1364/1735 [1:54:55<1:17:47, 12.58s/it]

Gagal 'Bika Cafe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▊  | 1365/1735 [1:55:08<1:17:33, 12.58s/it]

Gagal 'Kraving Coffee Sukarami': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▊  | 1366/1735 [1:55:20<1:17:18, 12.57s/it]

Gagal 'Kampung Kecil Resto Bengkulu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1367/1735 [1:55:33<1:17:14, 12.59s/it]

Gagal 'Bulan Resto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1368/1735 [1:55:46<1:16:39, 12.53s/it]

Gagal 'Danau Hijau Kepahiang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1369/1735 [1:55:58<1:16:11, 12.49s/it]

Gagal 'Pantai Sungai Suci': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1370/1735 [1:56:10<1:15:40, 12.44s/it]

Gagal 'Bukit Kandis': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1371/1735 [1:56:23<1:15:30, 12.45s/it]

Gagal 'Benteng Marlborough': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1372/1735 [1:56:35<1:15:18, 12.45s/it]

Gagal 'Pulau Tikus': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1373/1735 [1:56:48<1:15:09, 12.46s/it]

Gagal 'Beta Agrowisata': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1374/1735 [1:57:00<1:15:10, 12.50s/it]

Gagal 'Danau Dendam Tak Sudah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1375/1735 [1:57:13<1:14:38, 12.44s/it]

Gagal 'Pantai Pasir Putih': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1376/1735 [1:57:25<1:14:11, 12.40s/it]

Gagal 'Festival Tabut 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1377/1735 [1:57:37<1:14:01, 12.41s/it]

Gagal 'Pasar Barukoto I (Bencoolen Heritage)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1378/1735 [1:57:50<1:13:37, 12.37s/it]

Gagal 'Desa Wisata Baru Manis': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  79%|███████▉  | 1379/1735 [1:58:02<1:13:22, 12.37s/it]

Gagal 'Wahana Surya': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|███████▉  | 1380/1735 [1:58:15<1:13:44, 12.46s/it]

Gagal 'Mangkurajo Hills (Bukit Mangkurajo)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|███████▉  | 1381/1735 [1:58:27<1:13:47, 12.51s/it]

Gagal 'Pantai Cemoro Sewu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|███████▉  | 1382/1735 [1:58:40<1:13:26, 12.48s/it]

Gagal 'Pantai Pasar Bawah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|███████▉  | 1383/1735 [1:58:52<1:13:18, 12.50s/it]

Gagal 'Pantai Bengkenang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|███████▉  | 1384/1735 [1:59:04<1:12:51, 12.45s/it]

Gagal 'Taman Tabot': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|███████▉  | 1385/1735 [1:59:17<1:12:33, 12.44s/it]

Gagal 'Belungguk Point': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|███████▉  | 1386/1735 [1:59:29<1:12:33, 12.47s/it]

Gagal 'Taman Remaja Kota Bengkulu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|███████▉  | 1387/1735 [1:59:42<1:12:40, 12.53s/it]

Gagal 'Pulau Pahawang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|████████  | 1388/1735 [1:59:54<1:12:05, 12.47s/it]

Gagal 'Pantai Kyokko': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|████████  | 1389/1735 [2:00:07<1:11:40, 12.43s/it]

Gagal 'Bukit Aslan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|████████  | 1390/1735 [2:00:19<1:11:28, 12.43s/it]

Gagal 'Teluk Kiluan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|████████  | 1391/1735 [2:00:32<1:11:46, 12.52s/it]

Gagal 'Ceker Kerang Pedas Nona': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|████████  | 1392/1735 [2:00:44<1:11:37, 12.53s/it]

Gagal 'Kampung Daun Culture Gallery & Cafe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|████████  | 1393/1735 [2:00:57<1:11:12, 12.49s/it]

Gagal 'Sapulidi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|████████  | 1394/1735 [2:01:09<1:11:00, 12.49s/it]

Gagal 'Imah Seniman': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|████████  | 1395/1735 [2:01:22<1:11:03, 12.54s/it]

Gagal 'Warung Nasi Omar': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  80%|████████  | 1396/1735 [2:01:35<1:11:00, 12.57s/it]

Gagal 'Sarapan 10 Ribu by Dapoer Radira': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1397/1735 [2:01:47<1:10:39, 12.54s/it]

Gagal 'Cerita Dadar': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1398/1735 [2:02:00<1:10:33, 12.56s/it]

Gagal 'Resto Lamban Sabah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1399/1735 [2:02:12<1:10:19, 12.56s/it]

Gagal 'Lembah Hijau Lampung': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1401/1735 [2:02:37<1:09:35, 12.50s/it]

Gagal 'Kampung Vietnam': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news
Gagal 'Farm Day Mountain Side': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1402/1735 [2:02:50<1:09:10, 12.46s/it]

Gagal 'Lengkung Langit': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1403/1735 [2:03:02<1:09:02, 12.48s/it]

Gagal 'Lembah Durian Farm Stable': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1404/1735 [2:03:15<1:08:51, 12.48s/it]

Gagal 'Kawasan Batu Putu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1405/1735 [2:03:27<1:08:32, 12.46s/it]

Gagal 'Kali Akar': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1406/1735 [2:03:40<1:08:35, 12.51s/it]

Gagal 'Pantai Gigi Hiu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1407/1735 [2:03:52<1:08:02, 12.45s/it]

Gagal 'Desa Wisata Budaya Telukbetung': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1408/1735 [2:04:05<1:07:59, 12.48s/it]

Gagal 'Desa Wisata Budaya Kedamaian': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████  | 1409/1735 [2:04:17<1:08:02, 12.52s/it]

Gagal 'Desa Wisata Budaya Mulang Maya': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████▏ | 1410/1735 [2:04:30<1:07:52, 12.53s/it]

Gagal 'Desa Wisata Budaya Way Rarem': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████▏ | 1411/1735 [2:04:42<1:07:16, 12.46s/it]

Gagal 'Desa Wisata Budaya Pekon Balak': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████▏ | 1412/1735 [2:04:54<1:06:55, 12.43s/it]

Gagal 'Desa Wisata Budaya Bumi Lebu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████▏ | 1413/1735 [2:05:07<1:06:33, 12.40s/it]

Gagal 'Desa Wisata Budaya Wana': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  81%|████████▏ | 1414/1735 [2:05:19<1:06:26, 12.42s/it]

Gagal 'Desa Wisata Budaya Pugung Raharjo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1415/1735 [2:05:32<1:06:33, 12.48s/it]

Gagal 'Desa Wisata Budaya Putih Doh': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1416/1735 [2:05:44<1:06:21, 12.48s/it]

Gagal 'Desa Wisata Budaya Gedung Batin': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1417/1735 [2:05:57<1:06:21, 12.52s/it]

Gagal 'Desa Wisata Budaya Terbanggi Besar': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1418/1735 [2:06:09<1:06:14, 12.54s/it]

Gagal 'Desa Wisata Budaya Taman Baru': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1419/1735 [2:06:22<1:05:49, 12.50s/it]

Gagal 'Desa Wisata Budaya Lingai, Kibang, Lebuh Dalem': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1420/1735 [2:06:34<1:05:41, 12.51s/it]

Gagal 'Desa Wisata Budaya Pagar Dewa': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1421/1735 [2:06:47<1:05:12, 12.46s/it]

Gagal 'Gunung Krakatau': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1422/1735 [2:06:59<1:04:47, 12.42s/it]

Gagal 'Pantai Tanjung Setia': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1423/1735 [2:07:12<1:04:50, 12.47s/it]

Gagal 'Krakatau Historical Corner': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1424/1735 [2:07:24<1:04:43, 12.49s/it]

Gagal 'Illumination of Jakarta: Glow of Peace': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1425/1735 [2:07:37<1:04:48, 12.54s/it]

Gagal 'Indonesia World Dance Festival (IWDF) 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1426/1735 [2:07:50<1:04:45, 12.57s/it]

Gagal 'Pasar Literasi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1427/1735 [2:08:02<1:04:37, 12.59s/it]

Gagal 'F4 Forever 1st World Tour': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1428/1735 [2:08:15<1:04:32, 12.61s/it]

Gagal 'Kalarasa Fest: Perayaan Patah Hati': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1429/1735 [2:08:27<1:04:08, 12.58s/it]

Gagal 'Ancol (Flying Board)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1430/1735 [2:08:40<1:03:38, 12.52s/it]

Gagal 'Ciliwung River Adventure': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  82%|████████▏ | 1431/1735 [2:08:52<1:03:26, 12.52s/it]

Gagal 'M Bloc Space': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1432/1735 [2:09:05<1:02:58, 12.47s/it]

Gagal 'Pos Bloc': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1433/1735 [2:09:17<1:02:44, 12.47s/it]

Gagal 'Taman Ismail Marzuki (TIM)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1434/1735 [2:09:30<1:02:37, 12.48s/it]

Gagal 'Kota Tua Jakarta (Taman Fatahillah)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1435/1735 [2:09:42<1:02:10, 12.43s/it]

Gagal 'Monumen Nasional (Monas)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1436/1735 [2:09:54<1:02:12, 12.48s/it]

Gagal 'Tebet Eco Park': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1437/1735 [2:10:07<1:02:05, 12.50s/it]

Gagal 'Masjid Cut Meutia': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1438/1735 [2:10:20<1:02:08, 12.55s/it]

Gagal 'Hotel Mercure Jakarta Sabang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1439/1735 [2:10:32<1:01:54, 12.55s/it]

Gagal 'Open Dining Jakarta': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1440/1735 [2:10:45<1:01:48, 12.57s/it]

Gagal 'BTN Jakarta International Marathon (JAKIM) 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1441/1735 [2:10:57<1:01:17, 12.51s/it]

Gagal 'Ancol': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1442/1735 [2:11:10<1:01:15, 12.54s/it]

Gagal 'Taman Margasatwa Ragunan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1443/1735 [2:11:22<1:00:43, 12.48s/it]

Gagal 'Remember Fest': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1444/1735 [2:11:35<1:00:45, 12.53s/it]

Gagal 'Bukit Strawberry Berbunga': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1445/1735 [2:11:47<1:00:19, 12.48s/it]

Gagal 'La Fresa Farm': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1446/1735 [2:12:00<59:59, 12.45s/it]

Gagal 'Ngukus Layung': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1447/1735 [2:12:12<1:00:03, 12.51s/it]

Gagal 'Rumah Makan Mina Family': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  83%|████████▎ | 1448/1735 [2:12:25<59:37, 12.47s/it]

Gagal 'Tiramisusu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▎ | 1449/1735 [2:12:37<59:14, 12.43s/it]

Gagal 'Accra Bakes': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▎ | 1450/1735 [2:12:49<59:08, 12.45s/it]

Gagal 'Warisan Kue': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▎ | 1451/1735 [2:13:02<58:52, 12.44s/it]

Gagal 'D.dough Doughnut & Cookies': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▎ | 1452/1735 [2:13:15<59:01, 12.51s/it]

Gagal 'Sudirman Street Bandung': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▎ | 1453/1735 [2:13:27<58:31, 12.45s/it]

Gagal 'Cibadak Night Culinary Festival': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1454/1735 [2:13:39<58:35, 12.51s/it]

Gagal 'Zona Merah (Zomer) Sukajadi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1455/1735 [2:13:52<58:32, 12.55s/it]

Gagal 'Darajat Pass': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1456/1735 [2:14:04<58:04, 12.49s/it]

Gagal 'Kampung Sumber Alam Garut': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1457/1735 [2:14:17<57:54, 12.50s/it]

Gagal 'Nagara Hot Spring Experience': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1458/1735 [2:14:29<57:25, 12.44s/it]

Gagal 'Talaga Bodas': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1459/1735 [2:14:42<57:04, 12.41s/it]

Gagal 'Nordic Land': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1460/1735 [2:14:54<56:50, 12.40s/it]

Gagal 'Situ Gunung': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1461/1735 [2:15:06<56:42, 12.42s/it]

Gagal 'Situ Patenggang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1462/1735 [2:15:19<56:32, 12.43s/it]

Gagal 'Situ Cileunca': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1463/1735 [2:15:31<56:14, 12.40s/it]

Gagal 'Desa Wisata Gegesik': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1464/1735 [2:15:44<56:14, 12.45s/it]

Gagal 'Cukul Pangalengan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1465/1735 [2:15:56<56:09, 12.48s/it]

Gagal 'Kampung Naga': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  84%|████████▍ | 1466/1735 [2:16:09<55:51, 12.46s/it]

Gagal 'Kasepuhan Ciptagelar': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▍ | 1467/1735 [2:16:21<55:47, 12.49s/it]

Gagal 'Panyaweuyan (Desa Cibeusi)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▍ | 1468/1735 [2:16:34<55:26, 12.46s/it]

Gagal 'Desa Wisata Alamendah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▍ | 1469/1735 [2:16:46<55:23, 12.49s/it]

Gagal 'Puncak Aher': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▍ | 1470/1735 [2:16:59<55:11, 12.50s/it]

Gagal 'Plaza Haji Al Qosbah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▍ | 1471/1735 [2:17:11<54:42, 12.43s/it]

Gagal 'Kawah Putih': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▍ | 1472/1735 [2:17:24<54:47, 12.50s/it]

Gagal 'Gunung Papandayan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▍ | 1473/1735 [2:17:36<54:36, 12.51s/it]

Gagal 'Green Canyon': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▍ | 1474/1735 [2:17:49<54:14, 12.47s/it]

Gagal 'Curug Cikaso': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▌ | 1475/1735 [2:18:01<53:57, 12.45s/it]

Gagal 'Taman Nasional Gunung Gede Pangrango': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▌ | 1476/1735 [2:18:13<53:37, 12.42s/it]

Gagal 'Telaga Remis': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▌ | 1477/1735 [2:18:26<53:25, 12.43s/it]

Gagal 'Curug Cimahi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▌ | 1478/1735 [2:18:38<53:13, 12.43s/it]

Gagal 'Hibisc Fantasy Puncak': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▌ | 1479/1735 [2:18:51<52:57, 12.41s/it]

Gagal 'Jembatan Jaya Perkasa (Sodongkopo)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▌ | 1480/1735 [2:19:03<52:45, 12.41s/it]

Gagal 'Desa Wisata Tikukur': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▌ | 1481/1735 [2:19:16<52:46, 12.47s/it]

Gagal 'Kampung Gajah Wonderland': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▌ | 1482/1735 [2:19:28<52:38, 12.48s/it]

Gagal 'Snowbay Water Park TMII': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  85%|████████▌ | 1483/1735 [2:19:41<52:17, 12.45s/it]

Gagal 'Situ Cikedal': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1484/1735 [2:19:53<52:02, 12.44s/it]

Gagal 'Pesantren Fest 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1485/1735 [2:20:05<51:43, 12.41s/it]

Gagal 'Kawasan Banten Lama': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1486/1735 [2:20:18<51:22, 12.38s/it]

Gagal 'Movenpick Resort Carita': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1487/1735 [2:20:30<51:08, 12.37s/it]

Gagal 'Bukit Waruwangi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1488/1735 [2:20:43<51:14, 12.45s/it]

Gagal 'Pantai Carita': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1489/1735 [2:20:55<51:13, 12.49s/it]

Gagal 'Pantai Anyer': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1490/1735 [2:21:08<50:54, 12.47s/it]

Gagal 'Ocean Park BSD City': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1491/1735 [2:21:20<50:45, 12.48s/it]

Gagal 'Masjid Agung Banten': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1492/1735 [2:21:32<50:25, 12.45s/it]

Gagal 'Pulau Peucang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1493/1735 [2:21:45<50:19, 12.48s/it]

Gagal 'The Nice Ocean View Anyer': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1494/1735 [2:21:58<50:08, 12.48s/it]

Gagal 'Royal Baroe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1495/1735 [2:22:10<49:43, 12.43s/it]

Gagal 'Pulau Lima': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▌ | 1496/1735 [2:22:22<49:34, 12.45s/it]

Gagal 'Ayam Goreng Kalibogor': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▋ | 1497/1735 [2:22:35<49:38, 12.52s/it]

Gagal 'Ayam Goreng Tantene': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▋ | 1498/1735 [2:22:48<49:28, 12.53s/it]

Gagal 'Ayam Goreng Kaliandra': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▋ | 1499/1735 [2:23:00<49:04, 12.48s/it]

Gagal 'Ayam Goreng Sae Niki': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  86%|████████▋ | 1500/1735 [2:23:12<48:51, 12.47s/it]

Gagal 'Djago Jowo Purwokerto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1501/1735 [2:23:25<48:39, 12.48s/it]

Gagal 'Stupa by Plataran': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1502/1735 [2:23:37<48:32, 12.50s/it]

Gagal 'Warung Bali Pak Gede': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1503/1735 [2:23:50<48:20, 12.50s/it]

Gagal 'Warung Mbah Jingkrak Setiabudi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1504/1735 [2:24:03<48:16, 12.54s/it]

Gagal 'Warung Mebo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1505/1735 [2:24:15<47:59, 12.52s/it]

Gagal 'Mie Ayam dan Bakso Worth It': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1506/1735 [2:24:28<47:52, 12.55s/it]

Gagal 'Mie Ayam Kita Solo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1507/1735 [2:24:40<47:48, 12.58s/it]

Gagal 'Mie Ayam Yumie': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1508/1735 [2:24:53<47:40, 12.60s/it]

Gagal 'EloProgo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1509/1735 [2:25:05<47:19, 12.57s/it]

Gagal 'Melek Huruf': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1510/1735 [2:25:18<46:52, 12.50s/it]

Gagal 'Cerita Kita Cafe and Eatery': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1511/1735 [2:25:30<46:40, 12.50s/it]

Gagal 'Warung Kondre': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1512/1735 [2:25:43<46:43, 12.57s/it]

Gagal 'Warung Tuman': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1513/1735 [2:25:55<46:24, 12.54s/it]

Gagal 'Warung Makan Gabus Mpok Kuni': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1514/1735 [2:26:08<46:01, 12.50s/it]

Gagal 'Warung Pecak Duren': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1515/1735 [2:26:20<45:45, 12.48s/it]

Gagal 'Babah Liem': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1516/1735 [2:26:33<45:20, 12.42s/it]

Gagal 'Mie dan Babi Tepi Sawah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1517/1735 [2:26:45<45:09, 12.43s/it]

Gagal 'RM Sendang Pengilon': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  87%|████████▋ | 1518/1735 [2:26:57<44:52, 12.41s/it]

Gagal 'Ayam Kampung Goreng Mbah Karto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1519/1735 [2:27:10<44:51, 12.46s/it]

Gagal 'Gubug Makan Apung Suramadu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1520/1735 [2:27:23<44:47, 12.50s/it]

Gagal 'Torrys Tea House': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1521/1735 [2:27:35<44:28, 12.47s/it]

Gagal 'Resto Joglo Mamapipih': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1522/1735 [2:27:47<44:07, 12.43s/it]

Gagal 'Soto Carikan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1523/1735 [2:28:00<44:06, 12.48s/it]

Gagal 'Omah Eyang Resto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1524/1735 [2:28:12<43:47, 12.45s/it]

Gagal 'Soto Segeer Mbok Giyem': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1525/1735 [2:28:25<43:33, 12.45s/it]

Gagal 'Djenak Dine N Chill': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1526/1735 [2:28:37<43:25, 12.47s/it]

Gagal 'Ayam Tim Goreng Bu Better': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1527/1735 [2:28:50<43:21, 12.51s/it]

Gagal 'Bakso Remaja Gading': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1528/1735 [2:29:02<43:09, 12.51s/it]

Gagal 'Kusuma Sari': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1529/1735 [2:29:15<43:06, 12.55s/it]

Gagal 'Soto Betawi Haji Mamat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1530/1735 [2:29:27<42:47, 12.52s/it]

Gagal 'Soto Kudus Kencana': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1531/1735 [2:29:40<42:36, 12.53s/it]

Gagal 'Bale Dahar': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1532/1735 [2:29:53<42:21, 12.52s/it]

Gagal 'Pak Manto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1533/1735 [2:30:05<42:07, 12.51s/it]

Gagal 'We Land Sunrise View': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1534/1735 [2:30:18<42:02, 12.55s/it]

Gagal 'Torys Grill': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  88%|████████▊ | 1535/1735 [2:30:30<41:41, 12.51s/it]

Gagal 'Emerald Resto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▊ | 1536/1735 [2:30:43<41:39, 12.56s/it]

Gagal 'KOITO BATUGA': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▊ | 1537/1735 [2:30:55<41:15, 12.50s/it]

Gagal 'Kiken Resto & Kopitiam': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▊ | 1538/1735 [2:31:08<41:05, 12.51s/it]

Gagal 'Resto Sawah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▊ | 1539/1735 [2:31:20<40:51, 12.51s/it]

Gagal 'Argoloro Kopi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1540/1735 [2:31:33<40:48, 12.56s/it]

Gagal 'Nuansa Bening Cafe and Venue': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1541/1735 [2:31:45<40:26, 12.51s/it]

Gagal 'De Selokaton': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1542/1735 [2:31:58<40:19, 12.54s/it]

Gagal 'Ayam Panggang Mbah Dinem': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1543/1735 [2:32:10<40:06, 12.53s/it]

Gagal 'Soto Seger Hj. Fatimah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1544/1735 [2:32:23<39:54, 12.54s/it]

Gagal 'Sego Wiwit Prambanan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1545/1735 [2:32:35<39:31, 12.48s/it]

Gagal 'Bebek Goreng Suwarni': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1546/1735 [2:32:48<39:13, 12.45s/it]

Gagal 'Ramayana Garden Resto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1547/1735 [2:33:00<39:08, 12.49s/it]

Gagal 'Pawon Mbah Noto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1548/1735 [2:33:13<38:44, 12.43s/it]

Gagal 'Nasi Tiwul Mbok Sembleng': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1549/1735 [2:33:25<38:37, 12.46s/it]

Gagal 'Mie Ayam Bu Yuni': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1550/1735 [2:33:38<38:28, 12.48s/it]

Gagal 'Mie Ayam & Bakso Idolaku Pak Tikno': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1551/1735 [2:33:50<38:12, 12.46s/it]

Gagal 'Soto Kwali Karunia': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  89%|████████▉ | 1552/1735 [2:34:02<37:51, 12.41s/it]

Gagal 'Gudeg Bu Cokro': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|████████▉ | 1553/1735 [2:34:15<37:36, 12.40s/it]

Gagal 'Djos Gandhos Steak & Resto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|████████▉ | 1554/1735 [2:34:27<37:19, 12.38s/it]

Gagal 'Dembakoe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|████████▉ | 1555/1735 [2:34:39<37:03, 12.35s/it]

Gagal 'Soto Kwali Bu Trini': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|████████▉ | 1556/1735 [2:34:52<36:58, 12.40s/it]

Gagal 'Warung Idjo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|████████▉ | 1557/1735 [2:35:04<36:43, 12.38s/it]

Gagal 'Es Pak San Gurih Gandem': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|████████▉ | 1558/1735 [2:35:17<36:47, 12.47s/it]

Gagal 'Sate Ayam Martawi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|████████▉ | 1559/1735 [2:35:29<36:33, 12.46s/it]

Gagal 'Lontong Opor Pak Mul': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|████████▉ | 1560/1735 [2:35:42<36:22, 12.47s/it]

Gagal 'Bakso Pak Joko': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|████████▉ | 1561/1735 [2:35:54<36:02, 12.43s/it]

Gagal 'Kupat Tahu Hj. Sapen': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|█████████ | 1562/1735 [2:36:06<35:51, 12.44s/it]

Gagal 'We Got Steak': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|█████████ | 1563/1735 [2:36:19<35:32, 12.40s/it]

Gagal 'Sido Londo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|█████████ | 1564/1735 [2:36:31<35:23, 12.42s/it]

Gagal 'Sis 20': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|█████████ | 1565/1735 [2:36:44<35:19, 12.47s/it]

Gagal 'RM Oh La Vita': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|█████████ | 1566/1735 [2:36:56<35:11, 12.49s/it]

Gagal 'Kopi Gedang Kepok': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|█████████ | 1567/1735 [2:37:09<35:03, 12.52s/it]

Gagal 'Embung Bumiayu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|█████████ | 1568/1735 [2:37:21<34:43, 12.48s/it]

Gagal 'Wisata Alam Posong': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|█████████ | 1569/1735 [2:37:34<34:28, 12.46s/it]

Gagal 'Lokawisata Baturraden': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  90%|█████████ | 1570/1735 [2:37:46<34:09, 12.42s/it]

Gagal 'Negeri Kahyangan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1571/1735 [2:37:58<33:53, 12.40s/it]

Gagal 'Solo Safari': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1572/1735 [2:38:11<33:43, 12.41s/it]

Gagal 'Gunung Merapi jalur pendakian Selo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1573/1735 [2:38:23<33:33, 12.43s/it]

Gagal 'Wadas Cinta Carik': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1574/1735 [2:38:36<33:17, 12.41s/it]

Gagal 'Pantai Sepanjang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1575/1735 [2:38:48<33:06, 12.42s/it]

Gagal 'Pantai Drini Park': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1576/1735 [2:39:01<32:57, 12.44s/it]

Gagal 'Jungwok': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1577/1735 [2:39:13<32:54, 12.50s/it]

Gagal 'On the Rock': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1578/1735 [2:39:26<32:34, 12.45s/it]

Gagal 'Jalan Malioboro': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1579/1735 [2:39:38<32:23, 12.46s/it]

Gagal 'Titik 0 Km Jogja': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1580/1735 [2:39:51<32:14, 12.48s/it]

Gagal 'Alun-Alun Kidul': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1581/1735 [2:40:03<32:03, 12.49s/it]

Gagal 'Kawasan Malioboro': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1582/1735 [2:40:16<31:55, 12.52s/it]

Gagal 'Alun-Alun Selatan (Alkid) Yogyakarta': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████ | 1583/1735 [2:40:28<31:44, 12.53s/it]

Gagal 'Kaliurang Park': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████▏| 1584/1735 [2:40:41<31:37, 12.57s/it]

Gagal 'The Lost World Castle': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████▏| 1585/1735 [2:40:53<31:16, 12.51s/it]

Gagal 'Rumah Domes Prambanan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████▏| 1586/1735 [2:41:06<30:54, 12.45s/it]

Gagal 'Monumen Jogja Kembali (Monjali)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  91%|█████████▏| 1587/1735 [2:41:18<30:46, 12.48s/it]

Gagal 'Teras Malioboro': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1588/1735 [2:41:31<30:35, 12.49s/it]

Gagal 'Pabrik Bakpia Pathok 25': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1589/1735 [2:41:43<30:16, 12.44s/it]

Gagal 'Gesing Wonderland': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1590/1735 [2:41:55<30:01, 12.42s/it]

Gagal 'On The Rock Drini': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1591/1735 [2:42:08<29:51, 12.44s/it]

Gagal 'On The Rock Cafe and Bar': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1592/1735 [2:42:20<29:39, 12.44s/it]

Gagal 'Soleil Bistro': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1593/1735 [2:42:33<29:25, 12.43s/it]

Gagal 'Sungai Code': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1594/1735 [2:42:45<29:11, 12.42s/it]

Gagal 'Sasjiwa Wellness Space': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1595/1735 [2:42:58<29:05, 12.47s/it]

Gagal 'Kelok 23 (JJLS Kretek-Girijati)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1596/1735 [2:43:10<28:47, 12.43s/it]

Gagal 'Sungai Gajah Wong': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1597/1735 [2:43:23<28:36, 12.44s/it]

Gagal 'Winongo Art Festival': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1598/1735 [2:43:35<28:28, 12.47s/it]

Gagal 'Mandala Krida Expo 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1599/1735 [2:43:48<28:14, 12.46s/it]

Gagal 'De Mangol': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1600/1735 [2:44:00<27:57, 12.43s/it]

Gagal 'Heha Sky View': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1601/1735 [2:44:12<27:49, 12.46s/it]

Gagal 'Puri Mataram': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1602/1735 [2:44:25<27:35, 12.45s/it]

Gagal 'Bukit Klangon': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1603/1735 [2:44:37<27:20, 12.43s/it]

Gagal 'On The Rock Jogja': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  92%|█████████▏| 1604/1735 [2:44:50<27:15, 12.48s/it]

Gagal 'Agreya Coffee & Resto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1605/1735 [2:45:02<26:56, 12.43s/it]

Gagal 'Kampung Warna-Warni Jodipan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1606/1735 [2:45:15<26:51, 12.49s/it]

Gagal 'Hawai Waterpark': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1607/1735 [2:45:27<26:36, 12.47s/it]

Gagal 'Pantai Pulau Merah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1608/1735 [2:45:40<26:23, 12.47s/it]

Gagal 'Taman Nasional Baluran': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1609/1735 [2:45:52<26:09, 12.46s/it]

Gagal 'Simpang Lima Gumul': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1610/1735 [2:46:05<25:59, 12.48s/it]

Gagal 'Gunung Kelud': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1611/1735 [2:46:17<25:51, 12.51s/it]

Gagal 'Makam Bung Karno': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1612/1735 [2:46:30<25:39, 12.52s/it]

Gagal 'Kampung Coklat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1613/1735 [2:46:42<25:19, 12.45s/it]

Gagal 'Istana Gebang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1614/1735 [2:46:54<25:02, 12.42s/it]

Gagal 'Batu Secret Zoo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1615/1735 [2:47:07<24:58, 12.49s/it]

Gagal 'Bukit Premium': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1616/1735 [2:47:20<24:46, 12.49s/it]

Gagal 'Pesarean Gunung Kawi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1617/1735 [2:47:32<24:35, 12.50s/it]

Gagal 'De Karanganjar Koffieplantage': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1618/1735 [2:47:44<24:18, 12.46s/it]

Gagal 'OG Cafe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1619/1735 [2:47:57<24:12, 12.52s/it]

Gagal 'Moesioem Noegroho': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1620/1735 [2:48:10<24:02, 12.55s/it]

Gagal 'Roemah Lodji': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1621/1735 [2:48:22<23:51, 12.56s/it]

Gagal 'Hutan De Djawatan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  93%|█████████▎| 1622/1735 [2:48:35<23:37, 12.54s/it]

Gagal 'Green Island': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▎| 1623/1735 [2:48:47<23:23, 12.53s/it]

Gagal 'Taman Nasional Alas Purwo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▎| 1624/1735 [2:49:00<23:03, 12.47s/it]

Gagal 'Pantai Plengkung (G-Land)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▎| 1625/1735 [2:49:12<22:54, 12.50s/it]

Gagal 'Pantai Kedung Tumpang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▎| 1626/1735 [2:49:25<22:38, 12.47s/it]

Gagal 'Wisata Bahari Lamongan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1627/1735 [2:49:37<22:27, 12.48s/it]

Gagal 'Cimory Dairyland Prigen': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1628/1735 [2:49:50<22:19, 12.52s/it]

Gagal 'Santera De Laponte': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1629/1735 [2:50:02<22:01, 12.46s/it]

Gagal 'Jatim Park': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1630/1735 [2:50:15<21:54, 12.52s/it]

Gagal 'De Djawatan Forest': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1631/1735 [2:50:27<21:38, 12.48s/it]

Gagal 'Taman Gandrung Terakota': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1632/1735 [2:50:39<21:23, 12.46s/it]

Gagal 'Jembatan Ngundang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1633/1735 [2:50:52<21:09, 12.45s/it]

Gagal 'Jembatan Tamping': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1634/1735 [2:51:05<21:03, 12.51s/it]

Gagal 'Wisata Kali Jompo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1635/1735 [2:51:17<20:49, 12.49s/it]

Gagal 'Air Terjun Coban Kepel': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1636/1735 [2:51:29<20:33, 12.46s/it]

Gagal 'Kali Pinusan Poncosumo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1637/1735 [2:51:42<20:19, 12.44s/it]

Gagal 'Kampung Jepang Surabaya': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1638/1735 [2:51:54<20:11, 12.49s/it]

Gagal 'Pantai Prigi': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  94%|█████████▍| 1639/1735 [2:52:07<20:00, 12.51s/it]

Gagal 'Pantai Pasir Putih Karanggongso': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▍| 1640/1735 [2:52:20<19:51, 12.54s/it]

Gagal 'Goa Lowo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▍| 1641/1735 [2:52:32<19:36, 12.52s/it]

Gagal 'Peternakan Berkah Wafa Farm (BWF)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▍| 1642/1735 [2:52:45<19:24, 12.53s/it]

Gagal 'Museum Angkut': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▍| 1643/1735 [2:52:57<19:12, 12.53s/it]

Gagal 'Goa Selo Pawon (Watu Dapur)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▍| 1644/1735 [2:53:10<19:02, 12.55s/it]

Gagal 'Pantai Sine': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▍| 1645/1735 [2:53:22<18:44, 12.50s/it]

Gagal 'Miniatur Ka'bah Madiun (Pahlawan Religi Center)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▍| 1646/1735 [2:53:35<18:35, 12.54s/it]

Gagal 'Mikutopia': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▍| 1647/1735 [2:53:47<18:17, 12.48s/it]

Gagal 'Lembah Dieng': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▍| 1648/1735 [2:54:00<18:10, 12.54s/it]

Gagal 'Museum Mega Science Center dan Budaya': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▌| 1649/1735 [2:54:12<18:01, 12.57s/it]

Gagal 'Museum Marsinah': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▌| 1650/1735 [2:54:25<17:51, 12.60s/it]

Gagal 'Kirana Garden Resto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▌| 1651/1735 [2:54:37<17:33, 12.54s/it]

Gagal 'Bambu Kuliner Bali (Bakul Bali)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▌| 1652/1735 [2:54:50<17:18, 12.51s/it]

Gagal 'Kaizen Renon': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▌| 1653/1735 [2:55:02<17:06, 12.51s/it]

Gagal 'Laloba Bali': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▌| 1654/1735 [2:55:15<16:50, 12.47s/it]

Gagal 'Donat Kentang Renon': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▌| 1655/1735 [2:55:27<16:39, 12.50s/it]

Gagal 'Warung Mesari Bali': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  95%|█████████▌| 1656/1735 [2:55:40<16:28, 12.51s/it]

Gagal 'Pasukan 36 Bali': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1657/1735 [2:55:52<16:12, 12.47s/it]

Gagal 'Bakmi Kien': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1658/1735 [2:56:05<16:00, 12.47s/it]

Gagal 'Ngehe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1659/1735 [2:56:17<15:43, 12.42s/it]

Gagal 'D'Pota Chiz Korean Bread': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1660/1735 [2:56:29<15:31, 12.42s/it]

Gagal 'KAJA by Numa': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1661/1735 [2:56:42<15:17, 12.39s/it]

Gagal 'Luca Bali': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1662/1735 [2:56:54<15:09, 12.45s/it]

Gagal 'Nichidao': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1663/1735 [2:57:07<14:57, 12.46s/it]

Gagal 'Tuniang Bali': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1664/1735 [2:57:19<14:42, 12.43s/it]

Gagal 'Restoran Dewata': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1665/1735 [2:57:32<14:32, 12.47s/it]

Gagal 'Bali dari Selatan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1666/1735 [2:57:44<14:19, 12.46s/it]

Gagal 'Uncle Pipin Chinese Food': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1667/1735 [2:57:57<14:08, 12.47s/it]

Gagal 'Majesty Burger': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1668/1735 [2:58:09<13:59, 12.53s/it]

Gagal 'Standar Lokal': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▌| 1669/1735 [2:58:22<13:44, 12.49s/it]

Gagal 'Souphoria': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▋| 1670/1735 [2:58:34<13:28, 12.44s/it]

Gagal 'Al Jazeerah Signature Bali': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▋| 1671/1735 [2:58:47<13:18, 12.47s/it]

Gagal 'Take Japanese Restaurant': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▋| 1672/1735 [2:58:59<13:03, 12.44s/it]

Gagal 'Dapur Ibuk Nyoman': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▋| 1673/1735 [2:59:12<12:54, 12.49s/it]

Gagal 'Duduk Makan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  96%|█████████▋| 1674/1735 [2:59:24<12:45, 12.54s/it]

Gagal 'L'Orizon': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1675/1735 [2:59:37<12:35, 12.58s/it]

Gagal 'Gusto Gelato & Caffe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1676/1735 [2:59:50<12:23, 12.60s/it]

Gagal 'Menega Cafe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1677/1735 [3:00:02<12:11, 12.62s/it]

Gagal 'Pony Fine Dining dan Nightlife': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1678/1735 [3:00:15<11:57, 12.58s/it]

Gagal 'Cavo': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1680/1735 [3:00:40<11:32, 12.58s/it]

Gagal 'Baker Butcher Barista': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news
Gagal 'Luca': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1681/1735 [3:00:53<11:20, 12.61s/it]

Gagal 'Warung Nasi Tempong Bu Indra': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1682/1735 [3:01:05<11:05, 12.56s/it]

Gagal 'Sama-Sama Yakiniku Restaurant': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1683/1735 [3:01:18<10:54, 12.58s/it]

Gagal 'Sababa': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1684/1735 [3:01:30<10:39, 12.55s/it]

Gagal 'We Love Falafel': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1685/1735 [3:01:43<10:25, 12.51s/it]

Gagal 'Paradisocafe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1686/1735 [3:01:55<10:12, 12.51s/it]

Gagal 'Ettore Gelato': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1687/1735 [3:02:08<10:02, 12.56s/it]

Gagal 'Sari Organik': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1688/1735 [3:02:20<09:52, 12.60s/it]

Gagal 'WYAH Art & Creative Space': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1689/1735 [3:02:33<09:37, 12.55s/it]

Gagal 'Teba Sari': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1690/1735 [3:02:45<09:24, 12.56s/it]

Gagal 'Cafe Lotus': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  97%|█████████▋| 1691/1735 [3:02:58<09:09, 12.49s/it]

Gagal 'Nook': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1692/1735 [3:03:10<08:56, 12.47s/it]

Gagal 'Milu by Nook': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1693/1735 [3:03:23<08:42, 12.45s/it]

Gagal 'Tsavo Lion Restaurant': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1694/1735 [3:03:35<08:29, 12.43s/it]

Gagal 'Warung Mogan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1695/1735 [3:03:48<08:20, 12.50s/it]

Gagal 'Bali Funtastic': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1696/1735 [3:04:00<08:08, 12.52s/it]

Gagal 'Gurita Playground & Board Game Cafe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1697/1735 [3:04:13<07:54, 12.48s/it]

Gagal 'Food, Hotel and Tourism Bali (FHTB) 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1698/1735 [3:04:25<07:39, 12.43s/it]

Gagal 'Panggung Budaya Praharsacitta': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1699/1735 [3:04:38<07:30, 12.51s/it]

Gagal 'Pantai Kelan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1700/1735 [3:04:50<07:19, 12.56s/it]

Gagal 'Pantai Mengiat': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1701/1735 [3:05:03<07:05, 12.52s/it]

Gagal 'Pantai Balangan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1702/1735 [3:05:15<06:51, 12.46s/it]

Gagal 'Marine Safari Bali': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1703/1735 [3:05:28<06:40, 12.50s/it]

Gagal 'De Cafa': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1704/1735 [3:05:40<06:28, 12.54s/it]

Gagal 'Taman Wisata Kertha Gosa': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1705/1735 [3:05:53<06:14, 12.49s/it]

Gagal 'Museum Semara Jaya': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1706/1735 [3:06:05<06:00, 12.44s/it]

Gagal 'Water Blow Nusa Dua': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1707/1735 [3:06:17<05:48, 12.43s/it]

Gagal 'Peninsula Island Nusa Dua': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  98%|█████████▊| 1708/1735 [3:06:30<05:37, 12.48s/it]

Gagal 'Pantai Lovina': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▊| 1709/1735 [3:06:42<05:24, 12.48s/it]

Gagal 'Air Terjun Sekumpul': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▊| 1710/1735 [3:06:55<05:11, 12.44s/it]

Gagal 'Danau Tamblingan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▊| 1711/1735 [3:07:07<04:59, 12.46s/it]

Gagal 'Air Terjun Gitgit': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▊| 1712/1735 [3:07:20<04:46, 12.44s/it]

Gagal 'Pura Meduwe Karang': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▊| 1713/1735 [3:07:32<04:32, 12.40s/it]

Gagal 'Lovina Festival 2026': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1714/1735 [3:07:44<04:20, 12.39s/it]

Gagal 'Jatiluwih': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1715/1735 [3:07:57<04:08, 12.43s/it]

Gagal 'Tanah Lot': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1716/1735 [3:08:10<03:57, 12.50s/it]

Gagal 'Yeh Gangga': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1717/1735 [3:08:22<03:45, 12.54s/it]

Gagal 'Soka': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1718/1735 [3:08:35<03:32, 12.49s/it]

Gagal 'Pura Ulun Danu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1719/1735 [3:08:47<03:20, 12.51s/it]

Gagal 'Satu Asa Coffee': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1720/1735 [3:09:00<03:08, 12.53s/it]

Gagal 'Turyapada Tower': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1721/1735 [3:09:12<02:55, 12.51s/it]

Gagal 'Museum Puri Lukisan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1722/1735 [3:09:25<02:42, 12.52s/it]

Gagal 'Pasar Seni Ubud': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1723/1735 [3:09:37<02:30, 12.51s/it]

Gagal 'Desa Petulu': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1724/1735 [3:09:50<02:17, 12.51s/it]

Gagal 'Danau Beratan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1725/1735 [3:10:02<02:04, 12.48s/it]

Gagal 'Telaga Waja': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper):  99%|█████████▉| 1726/1735 [3:10:15<01:52, 12.54s/it]

Gagal 'Bali Safari & Marine Park': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper): 100%|█████████▉| 1727/1735 [3:10:27<01:40, 12.55s/it]

Gagal 'Sea Breeze Cafe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper): 100%|█████████▉| 1728/1735 [3:10:40<01:28, 12.58s/it]

Gagal 'Mahana Point Restaurant': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper): 100%|█████████▉| 1729/1735 [3:10:52<01:15, 12.50s/it]

Gagal 'Next Level Cafe': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper): 100%|█████████▉| 1730/1735 [3:11:05<01:02, 12.52s/it]

Gagal 'Klyf Club': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper): 100%|█████████▉| 1731/1735 [3:11:18<00:50, 12.57s/it]

Gagal 'The Dungki Bendega Resto': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper): 100%|█████████▉| 1732/1735 [3:11:30<00:37, 12.51s/it]

Gagal 'Yellow Bridge (Jembatan Kuning)': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper): 100%|█████████▉| 1733/1735 [3:11:42<00:25, 12.51s/it]

Gagal 'Bali Maritime Tourism Hub': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper): 100%|█████████▉| 1734/1735 [3:11:55<00:12, 12.49s/it]

Gagal 'Agrowisata Salak Sibetan': Serper gagal (status=None): 400 Client Error: Bad Request for url: https://google.serper.dev/news

Berita per tempat (Serper): 100%|██████████| 1735/1735 [3:12:07<00:00,  6.64s/it]

Tempat belum punya data: 638

,nama_tempat,keyword_berita,jumlah_berita_6bln,tanggal_berita_pertama,tanggal_berita_terakhir,selisih_hari
0,Sai Ramen,Sai Ramen Jakarta Selatan,5.0,2026-06-28,2026-10-02,96.0
1,Menya Beast,Menya Beast Jakarta Selatan,4.0,2026-09-11,2026-10-02,21.0
2,Raku Ramen,Raku Ramen Jakarta Selatan,3.0,2026-10-01,2026-10-02,1.0
3,Echigoya,Echigoya Jakarta,3.0,2026-04-22,2026-10-02,163.0
4,Warung Amanda,Warung Amanda Sidoarjo,3.0,2026-05-11,2026-09-25,137.0
...,...,...,...,...,...,...
1409,Kopi Kimteng,Kopi Kimteng Pekanbaru,5.0,2026-05-08,2026-07-11,64.0
1410,Pusat Pelatihan Gajah,Pusat Pelatihan Gajah,30.0,2026-04-23,2026-10-02,162.0
1411,Camping Ground Pulau Tongah,Camping Ground Pulau Tongah Kampar,2.0,2026-05-23,2026-05-23,0.0
1412,Air Terjun Batu Dinding,Air Terjun Batu Dinding Kampar,11.0,2026-05-19,2026-09-02,106.0
1413,Jewel Changi Airport,Jewel Changi Airport Singapura,29.0,2026-04-15,2026-09-11,149.0

In [34]:
df_places_final[df_places_final["jumlah_berita_6bln"] > 10]

,no,nama_tempat,kategori,jenis_tempat,lokasi,keterangan,status_viral,viral_sejak,dasar_viral,kelurahan_desa,...,catatan_lokasi,jumlah_artikel,keyword_pencarian,judul_artikel_sumber,link_sumber,keyword_berita,jumlah_berita_6bln,tanggal_berita_pertama,tanggal_berita_terakhir,selisih_hari
7,8,TikTok Food Fest 2026,Pameran,festival kuliner,"Hutan Kota Gelora Bung Karno (GBK), Jakarta","Festival kuliner gratis 26-27 Sep 2026, 40+ tenant F&B, demo masak, musik; tema 'Every Ingredient Tells a Story'",Disebut viral,26-27 September 2026,Menghadirkan sejumlah kuliner yang populer/banyak diperbincangkan di TikTok,Gelora,...,Hutan Kota GBK,1,tempat makan viral,"TikTok Food Fest 2026 Hari Terakhir di GBK, Ada 40 Lebih Tenant hingga Kuliner Viral - Aktualita.co",https://news.google.com/rss/articles/CBMidEFVX3lxTE5xMXhUUkZOTGJJcWZ2VmgwdGgtcnJsZ3NnbklPWENaLWV0RTVpM2Njc25KNDhpOFZ...,TikTok Food Fest 2026 Jakarta Pusat,30.0,2026-04-16,2026-10-02,169.0
14,15,Aldi's Burger,Restoran,burger (tenant festival),"Tenant TikTok Food Fest, Hutan Kota GBK",Tenant festival (burger),Disebut viral,Tidak disebut,Tenant kuliner yang banyak diperbincangkan di TikTok,Gelora,...,"Lokasi tenant festival, bukan gerai tetap",2,tempat makan viral,"TikTok Food Fest 2026 Hari Terakhir di GBK, Ada 40 Lebih Tenant hingga Kuliner Viral - Aktualita.co",https://news.google.com/rss/articles/CBMidEFVX3lxTE5xMXhUUkZOTGJJcWZ2VmgwdGgtcnJsZ3NnbklPWENaLWV0RTVpM2Njc25KNDhpOFZ...,Aldi's Burger Jakarta Pusat,17.0,2026-04-06,2026-07-28,113.0
19,20,DaGo,Restoran,restoran ayam goreng Korea,"Panglima Polim, Jakarta Selatan","Ayam goreng Korea tradisional, yangnyeom, jjajangmyeon, tteokbokki; Rp89-159 ribu",Disebut viral,Tidak disebut,"""Restoran ini juga viral di media sosial lho!""",None,...,Area Jl. Panglima Polim,1,tempat makan viral,"Bukan Fried Chicken Biasa, Ini 5 Restoran Ayam Goreng Korea Enak di Jakarta - food.detik.com",https://news.google.com/rss/articles/CBMivwFBVV95cUxNWWlVUWNKY0FTdC1PTDNfLUdFV2xRVXNWc3dSZldmVnJ1QWl2VW53V3ZuTVFvYjd...,DaGo Jakarta Selatan,23.0,2026-04-10,2026-09-11,154.0
76,77,Cita Rasa Nusantara,Restoran,restoran Nusantara rumah Joglo,"Ampera Raya, Jakarta Selatan","Interior Joglo, suasana asri berumput; soto Betawi Rp79 ribu",Rekomendasi,Tidak disebut,Suasana asri dengan interior rumah Joglo,Cilandak Timur,...,Koordinat perkiraan area Ampera Raya,1,tempat makan viral,"5 Tempat Makan Enak di Ampera Raya Jaksel, Ada Nasi Bali hingga Live Seafood - food.detik.com",https://news.google.com/rss/articles/CBMiwAFBVV95cUxPLTVYWUJBdVc3a3Jjd0ZKbTFhSVJyTkJVX3B1OWtUMEtMWjRNNTJVejhUSFFkTEh...,Cita Rasa Nusantara Jakarta Selatan,30.0,2026-04-08,2026-10-01,176.0
79,80,Pasar Cihapit,lainnya,pasar tradisional kuliner,"Jl. Cihapit Jl. Sabang No.32, Cihapit, Kec. Bandung Wetan","Pasar tradisional hits dengan kedai Toko Bakmi Feng, Rama Ramen, Baso Gepeng 99",Disebut viral,Tidak disebut,"Pasar tradisional yang lagi hits, favorit wisatawan",Cihapit,...,None,1,tempat makan viral,13 Tempat Makan Hits dan Viral di Bandung Yang Wajib Kamu Kunjungi - TripZilla Indonesia,https://news.google.com/rss/articles/CBMiZ0FVX3lxTFBOYktCUGo5UEpQNWNnbkowTm0wUW1tOEU4YlBYU1gwdlRfUzBYQ0hBOTRHU19PZGJ...,Pasar Cihapit Bandung,30.0,2026-04-09,2026-09-25,169.0
81,82,Warung Nasi Ibu Imas,Restoran,warung nasi,Bandung,Buka pagi hingga tengah malam,Disebut viral,Tidak disebut,Masuk daftar tempat makan hits dan viral di Bandung,Balonggede,...,Alamat terpotong; koordinat pusat Kota Bandung,4,tempat makan viral,13 Tempat Makan Hits dan Viral di Bandung Yang Wajib Kamu Kunjungi - TripZilla Indonesia,https://news.google.com/rss/articles/CBMiZ0FVX3lxTFBOYktCUGo5UEpQNWNnbkowTm0wUW1tOEU4YlBYU1gwdlRfUzBYQ0hBOTRHU19PZGJ...,Warung Nasi Ibu Imas Bandung,21.0,2026-04-11,2026-09-26,168.0
104,105,Mie Ayam Bakso Yunus,Restoran,warung mi ayam bakso,"Tebet Barat, Jakarta Selatan","Sejak 1980-an; mie yamin, mie ayam, bakso urat besar; mulai Rp25.000",Disebut viral,Tidak disebut,Langganan artis seperti Yuni Shara dan Krisdayanti,Tebet Barat,...,None,2,tempat makan viral,Ini 5 Tempat Makan Favorit Hotman Paris hingga Nicholas Saputra di Jakarta - food.detik.com,https://news.google.com/rss/articles/CBMivAFBVV95cUxPekVkWno1b2ZRb3BHbF9SbUM3dEctamhTXzREdnNMN1I5aEV3NmJRVm5zVnRiblh...,Mie Ayam Bakso Yunus Jakarta Selatan,11.0,2026-04-29,2026-09-28,152.0
119,120,Kupat Tahu Gempol,Restoran,warung kupat tahu,"Jl. Gempol Kulon No.53, Citarum, Kec. Bandung Wetan",Kupat tahu bumbu kacang gurih manis; buka 06.00-12.00; 5-10 menit dari stasiun,Rekomendasi,Tidak disebut,Menu sarapan legendaris di Bandung,Citarum,...,None,1,tempat makan viral,"Murah Hingga Melegenda, Nih Spot Makan Favorit Dekat Stasiun Bandung! - TripZilla Indonesia",https://news.google.com/rss/articles/CBMic0FVX3lxTE0ydjdic2taZ05GalVxT3hLZ2FHaU52RVNiOFhoRDFjeFJzVExBMGIwNkEwT2pOOWJ...,Kupat Tahu Gempol Bandung,14.0,2026-04-30,2026-09-26,149.0
124,125,Teras Rumah Nenek,Kafe,kafe dan restoran outdoor,"Jl. Abdulrahman No.46, Cibubur, Ciracas","Area outdoor asri; bakmi, ayam, snack platter, kopi",Rekomendasi,Tidak disebut,Konsep unik dengan suasana asri dan banyak pepohonan,Cibubur,...,None,1,tempat makan viral,7 Rekomendasi Tempat Makan di Jakarta Timur yang Murah dan Enak - Rumah123,https://news.google.com/rss/articles/CBMipAFBVV95cUxNT2JOTmR1bzRaR04zcXphbk01M2xxNFZ0S3JGU3FRTW9JMXNHWkNPZi0yOFpkTzZ...,Teras Rumah Nenek Jakarta Timur,12.0,2026-04-15,2026-09-02,140.0
132,133,RM Sepakat,Restoran,restoran Padang legendaris,"Blok M, Jakarta Selatan",Sejak 1967; gulai gajebo cepat habis beberapa jam setelah buka,Rekomendasi,Tidak disebut,Restoran Padang legendaris yang masih bertahan sejak 1967,Melawai,...,Alamat jalan tidak disebut,1,tempat makan viral,"7 Rekomendasi Tempat Makan Legendaris di Blok M, Sudah Pernah Coba? - CNN Indonesia",https://news.google.com/rss/articles/CBMizAFBVV95cUxNMTRwajdIbkVxQnNVUWJnSGM1Uk5ER2lnX0JMUlFGMTh3VkVIMDg3MU5RMDNuZUd...,RM Sepakat Jakarta Selatan,24.0,2026-04-14,2026-10-01,170.0
137,138,Ayam Bulungan,Restoran,rumah makan ayam goreng,"Bulungan, dekat Blok M","Diklaim sejak 1973; ayam goreng khas, soto Kudus, gudeg",Rekomendasi,Tidak disebut,Kuliner legendaris di kawasan Blok M,Selong,...,None,1,tempat makan viral,"7 Rekomendasi Tempat Makan Legendaris di Blok M, Sudah Pernah Coba? - CNN Indonesia",https://news.google.com/rss/articles/CBMizAFBVV95cUxNMTRwajdIbkVxQnNVUWJnSGM1Uk5ER2lnX0JMUlFGMTh3VkVIMDg3MU5RMDNuZUd...,Ayam Bulungan Jakarta Selatan,19.0,2026-05-03,2026-09-25,145.0

In [35]:
# save file
df_places_final.to_csv("df_places_final_with_news_stats.csv", index=False)

In [1]:
print("a")

a