# Scraper Tempat Makan & Wisata Viral di Indonesia (6 Bulan Terakhir)

Notebook ini melakukan scraping berita dari **Google News RSS** (bahasa Indonesia) untuk mencari artikel tentang tempat makan/wisata yang sedang viral dalam 6 bulan terakhir, lalu mengekstrak:

- Nama tempat
- Lokasi (kelurahan, kecamatan, kota/kabupaten, provinsi) + latitude/longitude (via geocoding OpenStreetMap Nominatim)
- Sejak kapan viral (perkiraan dari tanggal berita/isi artikel)
- Kenapa viral (kalimat yang mengandung alasan viral)
- Sumber berita (judul, link, tanggal publish)

## Catatan penting
- Ekstraksi nama tempat, lokasi, dan alasan viral memakai **heuristik berbasis regex**, bukan NLP/NER penuh, karena berita berbahasa Indonesia sangat bervariasi formatnya. Hasil disarankan **dicek/dibersihkan manual** sebelum dipakai untuk keperluan resmi.
- Geocoding memakai **Nominatim (OpenStreetMap)** yang gratis tapi ada batas 1 request/detik dan mewajibkan `user_agent` yang jelas. Untuk kebutuhan volume besar/produksi, pertimbangkan pakai Google Maps Geocoding API (berbayar) untuk akurasi lebih baik.
- Gunakan data ini untuk riset/analisis internal. Selalu cek Terms of Service situs sumber sebelum melakukan scraping berskala besar.

## 1. Install & Import Library

In [ ]:
%pip install feedparser requests beautifulsoup4 lxml geopy pandas python-dateutil tqdm openpyxl pytrends googlenewsdecoder -q

In [1]:
import json
import re
import time
import urllib.parse
from datetime import datetime, timedelta, timezone

import feedparser
import pandas as pd
import requests
from bs4 import BeautifulSoup
from dateutil import parser as dateparser
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
from googlenewsdecoder import gnewsdecoder
from tqdm.auto import tqdm

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    )
}

c:\Users\Agus Zainal Arifin\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 2. Konfigurasi

Ubah `KEYWORDS` atau `MONTHS_BACK` sesuai kebutuhan.

In [2]:
BASE_KEYWORDS = [
    "tempat makan viral",
    "kuliner viral",
    "cafe viral",
    "restoran viral",
    "warung viral",
    "jajanan viral",
    "street food viral",
    "wisata viral",
    "destinasi wisata viral",
    "spot wisata viral",
    "tempat wisata baru viral",
    "museum viral",
    "galeri seni viral",
    "pameran viral",
    "event viral",
    "festival viral",
    "pasar viral",
    "pasar malam viral",
    "toko viral",
    "toko oleh-oleh viral",
    "toko barang unik viral",
    "thrift shop viral",
    "pasar loak viral",
    "pusat oleh-oleh viral",
    "tempat belanja viral",
    "hidden gem Indonesia",
    "tempat hits Indonesia",
]

PROVINCES = [
    "Aceh", "Sumatera Utara", "Sumatera Barat", "Riau", "Kepulauan Riau",
    "Jambi", "Sumatera Selatan", "Kepulauan Bangka Belitung", "Bengkulu", "Lampung",
    "DKI Jakarta", "Jawa Barat", "Banten", "Jawa Tengah", "DI Yogyakarta", "Jawa Timur",
    "Bali", "Nusa Tenggara Barat", "Nusa Tenggara Timur", "Kalimantan Barat",
    "Kalimantan Tengah", "Kalimantan Selatan", "Kalimantan Timur", "Kalimantan Utara",
    "Sulawesi Utara", "Gorontalo", "Sulawesi Tengah", "Sulawesi Barat", "Sulawesi Selatan",
    "Sulawesi Tenggara", "Maluku", "Maluku Utara", "Papua", "Papua Barat",
    "Papua Selatan", "Papua Tengah", "Papua Pegunungan", "Papua Barat Daya",
]

BIG_CITIES = [
    "Jakarta Selatan", "Jakarta Pusat", "Jakarta Barat", "Jakarta Timur", "Jakarta Utara",
    "Surabaya", "Bandung", "Medan", "Yogyakarta", "Sleman", "Semarang", "Makassar",
    "Palembang", "Depok", "Bekasi", "Tangerang", "Bogor", "Malang", "Denpasar",
    "Bandar Lampung", "Padang", "Pekanbaru", "Banjarmasin", "Balikpapan", "Samarinda",
    "Pontianak", "Manado", "Jayapura", "Solo", "Cirebon", "Tasikmalaya", "Batam",
]

REGIONAL_CATEGORIES = [
    "tempat makan viral",
    "wisata viral",
    "museum viral",
    "toko viral",
    "tempat belanja viral",
    "pasar viral",
    "event viral",
]

LOCATION_KEYWORDS = [
    f"{category} {region}"
    for region in PROVINCES + BIG_CITIES
    for category in REGIONAL_CATEGORIES
]
KEYWORDS = list(dict.fromkeys(BASE_KEYWORDS + LOCATION_KEYWORDS))

MONTHS_BACK = 6
MAX_ITEMS_PER_KEYWORD = 20
REQUEST_DELAY = 1.0

CUTOFF_DATE = datetime.now(timezone.utc) - timedelta(days=30 * MONTHS_BACK)
print("Total keyword:", len(KEYWORDS))
print("Ambil artikel sejak:", CUTOFF_DATE.date())

Total keyword: 517
Ambil artikel sejak: 2026-04-01

In [3]:
KEYWORDS

['tempat makan viral',
 'kuliner viral',
 'cafe viral',
 'restoran viral',
 'warung viral',
 'jajanan viral',
 'street food viral',
 'wisata viral',
 'destinasi wisata viral',
 'spot wisata viral',
 'tempat wisata baru viral',
 'museum viral',
 'galeri seni viral',
 'pameran viral',
 'event viral',
 'festival viral',
 'pasar viral',
 'pasar malam viral',
 'toko viral',
 'toko oleh-oleh viral',
 'toko barang unik viral',
 'thrift shop viral',
 'pasar loak viral',
 'pusat oleh-oleh viral',
 'tempat belanja viral',
 'hidden gem Indonesia',
 'tempat hits Indonesia',
 'tempat makan viral Aceh',
 'wisata viral Aceh',
 'museum viral Aceh',
 'toko viral Aceh',
 'tempat belanja viral Aceh',
 'pasar viral Aceh',
 'event viral Aceh',
 'tempat makan viral Sumatera Utara',
 'wisata viral Sumatera Utara',
 'museum viral Sumatera Utara',
 'toko viral Sumatera Utara',
 'tempat belanja viral Sumatera Utara',
 'pasar viral Sumatera Utara',
 'event viral Sumatera Utara',
 'tempat makan viral Sumatera Barat',
 'wisata viral Sumatera Barat',
 'museum viral Sumatera Barat',
 'toko viral Sumatera Barat',
 'tempat belanja viral Sumatera Barat',
 'pasar viral Sumatera Barat',
 'event viral Sumatera Barat',
 'tempat makan viral Riau',
 'wisata viral Riau',
 'museum viral Riau',
 'toko viral Riau',
 'tempat belanja viral Riau',
 'pasar viral Riau',
 'event viral Riau',
 'tempat makan viral Kepulauan Riau',
 'wisata viral Kepulauan Riau',
 'museum viral Kepulauan Riau',
 'toko viral Kepulauan Riau',
 'tempat belanja viral Kepulauan Riau',
 'pasar viral Kepulauan Riau',
 'event viral Kepulauan Riau',
 'tempat makan viral Jambi',
 'wisata viral Jambi',
 'museum viral Jambi',
 'toko viral Jambi',
 'tempat belanja viral Jambi',
 'pasar viral Jambi',
 'event viral Jambi',
 'tempat makan viral Sumatera Selatan',
 'wisata viral Sumatera Selatan',
 'museum viral Sumatera Selatan',
 'toko viral Sumatera Selatan',
 'tempat belanja viral Sumatera Selatan',
 'pasar viral Sumatera Selatan',
 'event viral Sumatera Selatan',
 'tempat makan viral Kepulauan Bangka Belitung',
 'wisata viral Kepulauan Bangka Belitung',
 'museum viral Kepulauan Bangka Belitung',
 'toko viral Kepulauan Bangka Belitung',
 'tempat belanja viral Kepulauan Bangka Belitung',
 'pasar viral Kepulauan Bangka Belitung',
 'event viral Kepulauan Bangka Belitung',
 'tempat makan viral Bengkulu',
 'wisata viral Bengkulu',
 'museum viral Bengkulu',
 'toko viral Bengkulu',
 'tempat belanja viral Bengkulu',
 'pasar viral Bengkulu',
 'event viral Bengkulu',
 'tempat makan viral Lampung',
 'wisata viral Lampung',
 'museum viral Lampung',
 'toko viral Lampung',
 'tempat belanja viral Lampung',
 'pasar viral Lampung',
 'event viral Lampung',
 'tempat makan viral DKI Jakarta',
 'wisata viral DKI Jakarta',
 'museum viral DKI Jakarta',
 'toko viral DKI Jakarta',
 'tempat belanja viral DKI Jakarta',
 'pasar viral DKI Jakarta',
 'event viral DKI Jakarta',
 'tempat makan viral Jawa Barat',
 'wisata viral Jawa Barat',
 'museum viral Jawa Barat',
 'toko viral Jawa Barat',
 'tempat belanja viral Jawa Barat',
 'pasar viral Jawa Barat',
 'event viral Jawa Barat',
 'tempat makan viral Banten',
 'wisata viral Banten',
 'museum viral Banten',
 'toko viral Banten',
 'tempat belanja viral Banten',
 'pasar viral Banten',
 'event viral Banten',
 'tempat makan viral Jawa Tengah',
 'wisata viral Jawa Tengah',
 'museum viral Jawa Tengah',
 'toko viral Jawa Tengah',
 'tempat belanja viral Jawa Tengah',
 'pasar viral Jawa Tengah',
 'event viral Jawa Tengah',
 'tempat makan viral DI Yogyakarta',
 'wisata viral DI Yogyakarta',
 'museum viral DI Yogyakarta',
 'toko viral DI Yogyakarta',
 'tempat belanja viral DI Yogyakarta',
 'pasar viral DI Yogyakarta',
 'event viral DI Yogyakarta',
 'tempat makan viral Jawa Timur',
 'wisata viral Jawa Timur',
 'museum viral Jawa Timur',
 'toko viral Jawa Timur',
 'tempat belanja viral Jawa Timur',
 'pasar viral Jawa Timur',
 'event viral Jawa Timur',
 'tempat makan viral Bali',
 'wisata viral Bali',
 'museum viral Bali',
 'toko viral Bali',
 'tempat belanja viral Bali',
 'pasar viral Bali',
 'event viral Bali',
 'tempat makan viral Nusa Tenggara Barat',
 'wisata viral Nusa Tenggara Barat',
 'museum viral Nusa Tenggara Barat',
 'toko viral Nusa Tenggara Barat',
 'tempat belanja viral Nusa Tenggara Barat',
 'pasar viral Nusa Tenggara Barat',
 'event viral Nusa Tenggara Barat',
 'tempat makan viral Nusa Tenggara Timur',
 'wisata viral Nusa Tenggara Timur',
 'museum viral Nusa Tenggara Timur',
 'toko viral Nusa Tenggara Timur',
 'tempat belanja viral Nusa Tenggara Timur',
 'pasar viral Nusa Tenggara Timur',
 'event viral Nusa Tenggara Timur',
 'tempat makan viral Kalimantan Barat',
 'wisata viral Kalimantan Barat',
 'museum viral Kalimantan Barat',
 'toko viral Kalimantan Barat',
 'tempat belanja viral Kalimantan Barat',
 'pasar viral Kalimantan Barat',
 'event viral Kalimantan Barat',
 'tempat makan viral Kalimantan Tengah',
 'wisata viral Kalimantan Tengah',
 'museum viral Kalimantan Tengah',
 'toko viral Kalimantan Tengah',
 'tempat belanja viral Kalimantan Tengah',
 'pasar viral Kalimantan Tengah',
 'event viral Kalimantan Tengah',
 'tempat makan viral Kalimantan Selatan',
 'wisata viral Kalimantan Selatan',
 'museum viral Kalimantan Selatan',
 'toko viral Kalimantan Selatan',
 'tempat belanja viral Kalimantan Selatan',
 'pasar viral Kalimantan Selatan',
 'event viral Kalimantan Selatan',
 'tempat makan viral Kalimantan Timur',
 'wisata viral Kalimantan Timur',
 'museum viral Kalimantan Timur',
 'toko viral Kalimantan Timur',
 'tempat belanja viral Kalimantan Timur',
 'pasar viral Kalimantan Timur',
 'event viral Kalimantan Timur',
 'tempat makan viral Kalimantan Utara',
 'wisata viral Kalimantan Utara',
 'museum viral Kalimantan Utara',
 'toko viral Kalimantan Utara',
 'tempat belanja viral Kalimantan Utara',
 'pasar viral Kalimantan Utara',
 'event viral Kalimantan Utara',
 'tempat makan viral Sulawesi Utara',
 'wisata viral Sulawesi Utara',
 'museum viral Sulawesi Utara',
 'toko viral Sulawesi Utara',
 'tempat belanja viral Sulawesi Utara',
 'pasar viral Sulawesi Utara',
 'event viral Sulawesi Utara',
 'tempat makan viral Gorontalo',
 'wisata viral Gorontalo',
 'museum viral Gorontalo',
 'toko viral Gorontalo',
 'tempat belanja viral Gorontalo',
 'pasar viral Gorontalo',
 'event viral Gorontalo',
 'tempat makan viral Sulawesi Tengah',
 'wisata viral Sulawesi Tengah',
 'museum viral Sulawesi Tengah',
 'toko viral Sulawesi Tengah',
 'tempat belanja viral Sulawesi Tengah',
 'pasar viral Sulawesi Tengah',
 'event viral Sulawesi Tengah',
 'tempat makan viral Sulawesi Barat',
 'wisata viral Sulawesi Barat',
 'museum viral Sulawesi Barat',
 'toko viral Sulawesi Barat',
 'tempat belanja viral Sulawesi Barat',
 'pasar viral Sulawesi Barat',
 'event viral Sulawesi Barat',
 'tempat makan viral Sulawesi Selatan',
 'wisata viral Sulawesi Selatan',
 'museum viral Sulawesi Selatan',
 'toko viral Sulawesi Selatan',
 'tempat belanja viral Sulawesi Selatan',
 'pasar viral Sulawesi Selatan',
 'event viral Sulawesi Selatan',
 'tempat makan viral Sulawesi Tenggara',
 'wisata viral Sulawesi Tenggara',
 'museum viral Sulawesi Tenggara',
 'toko viral Sulawesi Tenggara',
 'tempat belanja viral Sulawesi Tenggara',
 'pasar viral Sulawesi Tenggara',
 'event viral Sulawesi Tenggara',
 'tempat makan viral Maluku',
 'wisata viral Maluku',
 'museum viral Maluku',
 'toko viral Maluku',
 'tempat belanja viral Maluku',
 'pasar viral Maluku',
 'event viral Maluku',
 'tempat makan viral Maluku Utara',
 'wisata viral Maluku Utara',
 'museum viral Maluku Utara',
 'toko viral Maluku Utara',
 'tempat belanja viral Maluku Utara',
 'pasar viral Maluku Utara',
 'event viral Maluku Utara',
 'tempat makan viral Papua',
 'wisata viral Papua',
 'museum viral Papua',
 'toko viral Papua',
 'tempat belanja viral Papua',
 'pasar viral Papua',
 'event viral Papua',
 'tempat makan viral Papua Barat',
 'wisata viral Papua Barat',
 'museum viral Papua Barat',
 'toko viral Papua Barat',
 'tempat belanja viral Papua Barat',
 'pasar viral Papua Barat',
 'event viral Papua Barat',
 'tempat makan viral Papua Selatan',
 'wisata viral Papua Selatan',
 'museum viral Papua Selatan',
 'toko viral Papua Selatan',
 'tempat belanja viral Papua Selatan',
 'pasar viral Papua Selatan',
 'event viral Papua Selatan',
 'tempat makan viral Papua Tengah',
 'wisata viral Papua Tengah',
 'museum viral Papua Tengah',
 'toko viral Papua Tengah',
 'tempat belanja viral Papua Tengah',
 'pasar viral Papua Tengah',
 'event viral Papua Tengah',
 'tempat makan viral Papua Pegunungan',
 'wisata viral Papua Pegunungan',
 'museum viral Papua Pegunungan',
 'toko viral Papua Pegunungan',
 'tempat belanja viral Papua Pegunungan',
 'pasar viral Papua Pegunungan',
 'event viral Papua Pegunungan',
 'tempat makan viral Papua Barat Daya',
 'wisata viral Papua Barat Daya',
 'museum viral Papua Barat Daya',
 'toko viral Papua Barat Daya',
 'tempat belanja viral Papua Barat Daya',
 'pasar viral Papua Barat Daya',
 'event viral Papua Barat Daya',
 'tempat makan viral Jakarta Selatan',
 'wisata viral Jakarta Selatan',
 'museum viral Jakarta Selatan',
 'toko viral Jakarta Selatan',
 'tempat belanja viral Jakarta Selatan',
 'pasar viral Jakarta Selatan',
 'event viral Jakarta Selatan',
 'tempat makan viral Jakarta Pusat',
 'wisata viral Jakarta Pusat',
 'museum viral Jakarta Pusat',
 'toko viral Jakarta Pusat',
 'tempat belanja viral Jakarta Pusat',
 'pasar viral Jakarta Pusat',
 'event viral Jakarta Pusat',
 'tempat makan viral Jakarta Barat',
 'wisata viral Jakarta Barat',
 'museum viral Jakarta Barat',
 'toko viral Jakarta Barat',
 'tempat belanja viral Jakarta Barat',
 'pasar viral Jakarta Barat',
 'event viral Jakarta Barat',
 'tempat makan viral Jakarta Timur',
 'wisata viral Jakarta Timur',
 'museum viral Jakarta Timur',
 'toko viral Jakarta Timur',
 'tempat belanja viral Jakarta Timur',
 'pasar viral Jakarta Timur',
 'event viral Jakarta Timur',
 'tempat makan viral Jakarta Utara',
 'wisata viral Jakarta Utara',
 'museum viral Jakarta Utara',
 'toko viral Jakarta Utara',
 'tempat belanja viral Jakarta Utara',
 'pasar viral Jakarta Utara',
 'event viral Jakarta Utara',
 'tempat makan viral Surabaya',
 'wisata viral Surabaya',
 'museum viral Surabaya',
 'toko viral Surabaya',
 'tempat belanja viral Surabaya',
 'pasar viral Surabaya',
 'event viral Surabaya',
 'tempat makan viral Bandung',
 'wisata viral Bandung',
 'museum viral Bandung',
 'toko viral Bandung',
 'tempat belanja viral Bandung',
 'pasar viral Bandung',
 'event viral Bandung',
 'tempat makan viral Medan',
 'wisata viral Medan',
 'museum viral Medan',
 'toko viral Medan',
 'tempat belanja viral Medan',
 'pasar viral Medan',
 'event viral Medan',
 'tempat makan viral Yogyakarta',
 'wisata viral Yogyakarta',
 'museum viral Yogyakarta',
 'toko viral Yogyakarta',
 'tempat belanja viral Yogyakarta',
 'pasar viral Yogyakarta',
 'event viral Yogyakarta',
 'tempat makan viral Sleman',
 'wisata viral Sleman',
 'museum viral Sleman',
 'toko viral Sleman',
 'tempat belanja viral Sleman',
 'pasar viral Sleman',
 'event viral Sleman',
 'tempat makan viral Semarang',
 'wisata viral Semarang',
 'museum viral Semarang',
 'toko viral Semarang',
 'tempat belanja viral Semarang',
 'pasar viral Semarang',
 'event viral Semarang',
 'tempat makan viral Makassar',
 'wisata viral Makassar',
 'museum viral Makassar',
 'toko viral Makassar',
 'tempat belanja viral Makassar',
 'pasar viral Makassar',
 'event viral Makassar',
 'tempat makan viral Palembang',
 'wisata viral Palembang',
 'museum viral Palembang',
 'toko viral Palembang',
 'tempat belanja viral Palembang',
 'pasar viral Palembang',
 'event viral Palembang',
 'tempat makan viral Depok',
 'wisata viral Depok',
 'museum viral Depok',
 'toko viral Depok',
 'tempat belanja viral Depok',
 'pasar viral Depok',
 'event viral Depok',
 'tempat makan viral Bekasi',
 'wisata viral Bekasi',
 'museum viral Bekasi',
 'toko viral Bekasi',
 'tempat belanja viral Bekasi',
 'pasar viral Bekasi',
 'event viral Bekasi',
 'tempat makan viral Tangerang',
 'wisata viral Tangerang',
 'museum viral Tangerang',
 'toko viral Tangerang',
 'tempat belanja viral Tangerang',
 'pasar viral Tangerang',
 'event viral Tangerang',
 'tempat makan viral Bogor',
 'wisata viral Bogor',
 'museum viral Bogor',
 'toko viral Bogor',
 'tempat belanja viral Bogor',
 'pasar viral Bogor',
 'event viral Bogor',
 'tempat makan viral Malang',
 'wisata viral Malang',
 'museum viral Malang',
 'toko viral Malang',
 'tempat belanja viral Malang',
 'pasar viral Malang',
 'event viral Malang',
 'tempat makan viral Denpasar',
 'wisata viral Denpasar',
 'museum viral Denpasar',
 'toko viral Denpasar',
 'tempat belanja viral Denpasar',
 'pasar viral Denpasar',
 'event viral Denpasar',
 'tempat makan viral Bandar Lampung',
 'wisata viral Bandar Lampung',
 'museum viral Bandar Lampung',
 'toko viral Bandar Lampung',
 'tempat belanja viral Bandar Lampung',
 'pasar viral Bandar Lampung',
 'event viral Bandar Lampung',
 'tempat makan viral Padang',
 'wisata viral Padang',
 'museum viral Padang',
 'toko viral Padang',
 'tempat belanja viral Padang',
 'pasar viral Padang',
 'event viral Padang',
 'tempat makan viral Pekanbaru',
 'wisata viral Pekanbaru',
 'museum viral Pekanbaru',
 'toko viral Pekanbaru',
 'tempat belanja viral Pekanbaru',
 'pasar viral Pekanbaru',
 'event viral Pekanbaru',
 'tempat makan viral Banjarmasin',
 'wisata viral Banjarmasin',
 'museum viral Banjarmasin',
 'toko viral Banjarmasin',
 'tempat belanja viral Banjarmasin',
 'pasar viral Banjarmasin',
 'event viral Banjarmasin',
 'tempat makan viral Balikpapan',
 'wisata viral Balikpapan',
 'museum viral Balikpapan',
 'toko viral Balikpapan',
 'tempat belanja viral Balikpapan',
 'pasar viral Balikpapan',
 'event viral Balikpapan',
 'tempat makan viral Samarinda',
 'wisata viral Samarinda',
 'museum viral Samarinda',
 'toko viral Samarinda',
 'tempat belanja viral Samarinda',
 'pasar viral Samarinda',
 'event viral Samarinda',
 'tempat makan viral Pontianak',
 'wisata viral Pontianak',
 'museum viral Pontianak',
 'toko viral Pontianak',
 'tempat belanja viral Pontianak',
 'pasar viral Pontianak',
 'event viral Pontianak',
 'tempat makan viral Manado',
 'wisata viral Manado',
 'museum viral Manado',
 'toko viral Manado',
 'tempat belanja viral Manado',
 'pasar viral Manado',
 'event viral Manado',
 'tempat makan viral Jayapura',
 'wisata viral Jayapura',
 'museum viral Jayapura',
 'toko viral Jayapura',
 'tempat belanja viral Jayapura',
 'pasar viral Jayapura',
 'event viral Jayapura',
 'tempat makan viral Solo',
 'wisata viral Solo',
 'museum viral Solo',
 'toko viral Solo',
 'tempat belanja viral Solo',
 'pasar viral Solo',
 'event viral Solo',
 'tempat makan viral Cirebon',
 'wisata viral Cirebon',
 'museum viral Cirebon',
 'toko viral Cirebon',
 'tempat belanja viral Cirebon',
 'pasar viral Cirebon',
 'event viral Cirebon',
 'tempat makan viral Tasikmalaya',
 'wisata viral Tasikmalaya',
 'museum viral Tasikmalaya',
 'toko viral Tasikmalaya',
 'tempat belanja viral Tasikmalaya',
 'pasar viral Tasikmalaya',
 'event viral Tasikmalaya',
 'tempat makan viral Batam',
 'wisata viral Batam',
 'museum viral Batam',
 'toko viral Batam',
 'tempat belanja viral Batam',
 'pasar viral Batam',
 'event viral Batam']

## 3. Ambil Daftar Berita dari Google News RSS

In [5]:
def fetch_google_news(keyword: str, max_items: int = 25):
    """Ambil daftar berita dari Google News RSS untuk sebuah keyword (bahasa Indonesia)."""
    query = urllib.parse.quote(keyword)
    url = f"https://news.google.com/rss/search?q={query}&hl=id&gl=ID&ceid=ID:id"
    feed = feedparser.parse(url)

    items = []
    for entry in feed.entries[:max_items]:
        try:
            pub_date = dateparser.parse(entry.published)
            if pub_date.tzinfo is None:
                pub_date = pub_date.replace(tzinfo=timezone.utc)
        except Exception:
            pub_date = None

        if pub_date is not None and pub_date < CUTOFF_DATE:
            continue  # lewati berita yang lebih lama dari batas waktu

        source = entry.get("source", {}).get("title") if hasattr(entry, "get") else None
        items.append(
            {
                "keyword": keyword,
                "title": entry.title,
                "link": entry.link,
                "published": pub_date,
                "source": source or getattr(getattr(entry, "source", None), "title", None),
            }
        )
    return items


all_news = []
for kw in tqdm(KEYWORDS, desc="Fetch RSS per keyword"):
    all_news.extend(fetch_google_news(kw, MAX_ITEMS_PER_KEYWORD))
    time.sleep(REQUEST_DELAY)

df_news = pd.DataFrame(all_news).drop_duplicates(subset="link").reset_index(drop=True)
print(f"Total artikel ditemukan: {len(df_news)}")
df_news.head()

Fetch RSS per keyword: 100%|██████████| 517/517 [16:14<00:00,  1.88s/it]

Total artikel ditemukan: 2473

,keyword,title,link,published,source
0,tempat makan viral,Media Sosial Mengubah Cara Kita Memilih Tempat...,https://news.google.com/rss/articles/CBMifkFVX...,2026-09-25 08:00:00+00:00,Jatimnet.com
1,tempat makan viral,Awas Kalap! Ini 7 Tempat Makan Soto Mie Legend...,https://news.google.com/rss/articles/CBMitgFBV...,2026-09-26 08:00:30+00:00,detikFood
2,tempat makan viral,Rekomendasi 7 Tempat Makan Ramah Kantong di Jo...,https://news.google.com/rss/articles/CBMiwgFBV...,2026-09-23 06:38:00+00:00,RRI.co.id
3,tempat makan viral,10 Tempat Makan Viral di Bandung 2026 - nibble.id,https://news.google.com/rss/articles/CBMiaEFVX...,2026-06-09 07:00:00+00:00,nibble.id
4,tempat makan viral,"TikTok Food Fest 2026 Hari Terakhir di GBK, Ad...",https://news.google.com/rss/articles/CBMidEFVX...,2026-09-27 10:22:00+00:00,Aktualita.co

In [7]:
df_news = pd.read_csv("df_news_extended_1_249.csv")
# remove last 50 row 
df_news = df_news[:-50]
# df_news.keyword.value_counts()
df_news

,keyword,title,link,published,source
0,tempat makan viral,Media Sosial Mengubah Cara Kita Memilih Tempat...,https://news.google.com/rss/articles/CBMifkFVX...,2026-09-25 08:00:00+00:00,Jatimnet.com
1,tempat makan viral,Awas Kalap! Ini 7 Tempat Makan Soto Mie Legend...,https://news.google.com/rss/articles/CBMitgFBV...,2026-09-26 08:00:30+00:00,detikFood
2,tempat makan viral,Rekomendasi 7 Tempat Makan Ramah Kantong di Jo...,https://news.google.com/rss/articles/CBMiwgFBV...,2026-09-23 06:38:00+00:00,RRI.co.id
3,tempat makan viral,10 Tempat Makan Viral di Bandung 2026 - nibble.id,https://news.google.com/rss/articles/CBMiaEFVX...,2026-06-09 07:00:00+00:00,nibble.id
4,tempat makan viral,"TikTok Food Fest 2026 Hari Terakhir di GBK, Ad...",https://news.google.com/rss/articles/CBMidEFVX...,2026-09-27 10:22:00+00:00,Aktualita.co
...,...,...,...,...,...
2418,tempat makan viral Batam,5 Tempat Makan Siang Enak di Batam yang Cocok ...,https://news.google.com/rss/articles/CBMixwFBV...,2026-06-11 07:00:00+00:00,Jawa Pos
2419,tempat makan viral Batam,Jelajah Kuliner Batam: 5 Tempat Makan Baru den...,https://news.google.com/rss/articles/CBMisAFBV...,2026-07-06 07:00:00+00:00,Batam Pos
2420,tempat makan viral Batam,"Pilihan Tempat Makan Siang Hits di Batam, Saji...",https://news.google.com/rss/articles/CBMiswFBV...,2026-05-17 07:00:00+00:00,batam.inews.id
2421,tempat makan viral Batam,"Wisata Kuliner Batam Makin Ramai, 5 Tempat Kul...",https://news.google.com/rss/articles/CBMiygFBV...,2026-05-29 07:00:00+00:00,Jawa Pos
2422,tempat makan viral Batam,Berburu Dessert di Batam! 5 Cafe Estetik denga...,https://news.google.com/rss/articles/CBMixwFBV...,2026-06-10 07:00:00+00:00,Jawa Pos

## 4. Ambil Isi Artikel (Full Text)

Link dari Google News RSS adalah redirect, kita ikuti sampai ke halaman aslinya lalu ambil teks paragraf.

In [ ]:
def resolve_and_fetch(url: str, timeout: tuple[int, int] = (5, 15)):
    """Decode URL Google News lalu ambil HTML halaman artikel sumber."""
    source_url = url
    if "news.google.com" in url:
        try:
            decoded = gnewsdecoder(url, interval=1, timeout=10)
            if decoded.get("success") and decoded.get("decoded_url"):
                source_url = decoded["decoded_url"]
        except Exception:
            pass

    try:
        resp = requests.get(source_url, headers=HEADERS, timeout=timeout, allow_redirects=True)
        resp.raise_for_status()
        return resp.url, resp.text
    except requests.RequestException:
        return None, None


def extract_article_text(html: str) -> str:
    """Ambil isi artikel dari JSON-LD, meta description, paragraf, atau body HTML."""
    if not html:
        return ""
    soup = BeautifulSoup(html, "lxml")

    # Banyak situs berita menyimpan isi artikel di JSON-LD, bukan tag p.
    for script in soup.find_all("script", type="application/ld+json"):
        try:
            payload = json.loads(script.string or script.get_text())
        except (TypeError, json.JSONDecodeError):
            continue
        candidates = payload if isinstance(payload, list) else [payload]
        for item in candidates:
            if isinstance(item, dict) and isinstance(item.get("articleBody"), str):
                article_body = re.sub(r"\s+", " ", item["articleBody"]).strip()
                if len(article_body) >= 100:
                    return article_body

    meta = soup.find("meta", attrs={"name": "description"}) or soup.find(
        "meta", attrs={"property": "og:description"}
    )
    meta_text = meta.get("content", "").strip() if meta else ""

    for tag in soup(["script", "style", "nav", "footer", "header", "aside", "noscript"]):
        tag.decompose()
    paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]
    paragraphs = [p for p in paragraphs if len(p) >= 20]
    paragraph_text = " ".join(paragraphs)
    if len(paragraph_text) >= 100:
        return paragraph_text
    if len(meta_text) >= 40:
        return meta_text

    body_text = soup.get_text(" ", strip=True) if soup.body else ""
    return re.sub(r"\s+", " ", body_text).strip()


article_texts = []
final_urls = []
i = 1
for link in tqdm(df_news["link"], desc="Fetch isi artikel"):
    if i > 2410: break
    i += 1
    print("Processing article number:", i)
    print("Fetching link:", link)
    final_url, html = resolve_and_fetch(link)
    final_urls.append(final_url)
    article_texts.append(extract_article_text(html))
    print("panjang artikel:", len(article_texts[-1]))
    time.sleep(REQUEST_DELAY)

df_news["final_url"] = final_urls
df_news["article_text"] = pd.Series(article_texts, index=df_news.index, dtype="string")
df_news["article_text_length"] = df_news["article_text"].str.len().fillna(0).astype(int)
print(f"Artikel dengan isi berhasil diambil: {(df_news['article_text_length'] >= 100).sum()} dari {len(df_news)}")
print(f"Fetch gagal/kosong: {df_news['article_text'].eq('').sum()}")
df_news = df_news[df_news["article_text_length"] >= 100].reset_index(drop=True)
df_news.to_csv("df_news_extended.csv", index=False)

Fetch isi artikel:   0%|          | 0/2423 [00:00<?, ?it/s]

Fetching link: https://news.google.com/rss/articles/CBMifkFVX3lxTE9qZDRrbTc5elBjLU5ra0pZVnp1M21wMFRZd1NydUpGY2xlbm5vMktZZEJXNnhfcVZVWG1uRHJUSF9Dc0xydVdoLWItQ0RMMEd2dXQyMUNWeFB0QjNNZU02bmg2OTlOR0JtZVRBWW5pUWhUc0ZZcTdDbjZobmtNUQ?oc=5
panjang artikel: 7110

Fetch isi artikel:   0%|          | 1/2423 [00:04<3:09:17,  4.69s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxOYk92ckFweFFab1BZMHdPUTB2U2NXeE5vOVpHOUJfbXVqUm5YeHNHVjVUdUYxT2x2VVZtVnBHeEdTYmVBZXI3Y2xpWGRLMWcwMnJJNlduRUtqREJLbzhOQWpPMHhaRXc4cjBXRUwwbWZVUlViWFduN2plTU93UF9MVDRuRmZ0SW5rR2pYbmNUQjc1MG00bnJpSGtMN3ZIcVdhRTd1MXctcy1WOXhraWhiR2xfRVQ0Z9IBuwFBVV95cUxQQjFXOGp4UXEyUlp5aDl4dFFYN3VnQnBFN0E3akFRQ2ljdE1rcndCMkVldVhWcHFDekQwU3J2U0NNZzB1dGFGQWlxWGRWUXVPNU5OaUt0NmRIX3RaT1JjSFoxZU9RQXpXaTdYcXN4SEpZWTRSbnFUNHIxYk1ZUVM2SExaemdKNC1MX0tqemlKY1phWi1XajR2VVlMU0xtNGRJNzVRdG5VbUVWUjlqVktDNlYyd0p2eG1MZzFj?oc=5
panjang artikel: 2855

Fetch isi artikel:   0%|          | 2/2423 [00:09<3:11:15,  4.74s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxPQzJKTVJPcXJKa3ZnWnhCTXZUYVBySTd5d25iek4xRmdETXZXdWFicVJXdkl4ZGFObHJWbW4zT3JZbEQ1VzlvVFFCZ1dEZVktM2p3OVJNWlNoNXlwQUVHZ3FHOHFqaUhxaGw4b0dSRnJNOF9tX1JWaUsxdnQ1M0pPZUN4ZE9sY1g2bnBVTFZfQzVlVTVVQm5SQnhhbzNRRl8zcmxxR0hlTTFMRzVnc0JWOTJMU1laX1c1Yi1sQ3FURjNjQQ?oc=5
panjang artikel: 6348

Fetch isi artikel:   0%|          | 3/2423 [00:15<3:29:47,  5.20s/it]

Fetching link: https://news.google.com/rss/articles/CBMiaEFVX3lxTE9pZzU0UEt2M3VSYUxyTVBQdWtIMDEzaDhmRld1eWFGWk5ZaXc4Q0F0Q1FlQktpQW9fVGJBS2hFN0I0YWY1eUxJamkxUE9OVF9sWDFpbWtTVFFKRFNoaVJuUEFCeDBha0VE?oc=5
panjang artikel: 9858

Fetch isi artikel:   0%|          | 4/2423 [00:20<3:35:07,  5.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMidEFVX3lxTE5xMXhUUkZOTGJJcWZ2VmgwdGgtcnJsZ3NnbklPWENaLWV0RTVpM2Njc25KNDhpOFZZbGxmbmtzbWx5WUhEbjh1MWlUVTFVY3FrOVZ4cEV4VUpIeFZEREFkVDZIMWdTdXpCOWNqbTEtZ2FzdnJN?oc=5
panjang artikel: 6105

Fetch isi artikel:   0%|          | 5/2423 [00:25<3:26:04,  5.11s/it]

Fetching link: https://news.google.com/rss/articles/CBMikAFBVV95cUxObnhzRGlQbVdYSGxKT2luV0dxWFp2aGhnLU9zTGhSLVlieXl4aE9WSDVPOWVWdl91dHBrYWRaa2paUmZzVGR1QW90WGdvMVkzS3l1MG56aHdsejdUM25iYl9lN0NYWHFaLUVxTkMtRU5wb0FmWUhKVUtxclVfVGJGSVBiOHhldEVKWF9ETFQ0emo?oc=5
panjang artikel: 11596

Fetch isi artikel:   0%|          | 6/2423 [00:29<3:06:15,  4.62s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxOYy1wRXhmRUtDWkcxZU1NWUFWREdKV01kYXJqT29VQ21QNkhSRGprSzIySHp0LVI2VGUtenhCNEplTWtGY1A2T1RJaWcxVEVxbF9FbVV4Z3RWRHhhYzhUR1FrZVc5cjdDMDJQRWlubC1LTXY3dXI2Mk5zcGVDZmNLa0d4dGFaY2poQlc1Z3hkT3FrTERzRTZoWkJMbGxmU0o4SXlIa0xNbjdDcDl4ZXVUbXQyRFFRaWFGcU40Qzl6eEZQV3gzcXdIRFhLRGxSeHPSAb8BQVVfeXFMTWh2alpvNkhkMVdJVjRGUC16cWVBWURPVHVwSUIwdDYxd0Yxc09oM1pRYzdjWEJ5b0dRSEpzZHRJV1hTc1VJencxRTdZd1FPWmwtNkJZV2FjRUhDSEIxOUJJcl9DMEFlWGpTTUk1SkExVi1HWXVpSHAyZkI0OFM1ZDlMd01yYkNiSzVxb084cGlHbFI4UmZ2VmYzM2xPOWFSc3k1eEZOcF9EdW15T3BMX0lTdUxfSDgtNk5DbUtnY2c?oc=5
panjang artikel: 3416

Fetch isi artikel:   0%|          | 7/2423 [00:33<3:04:55,  4.59s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxQbG9QZ2VwZ3NYR3lVb1N2Z25GTkkxWU93Tko3SGtkakhXN2JVVmFhXzRJc1NsSWpHbEpEelJrZjRydDd1clVDVzVVbzdfQkM5SG96RlJhYjJzNUdSQ1I0ZTlGamFIOVdJQklQeVNYTGpkSnpfT21zekUxeTNsWHJmV09LaEtCRWVjVlBUSUdNRVBMWE5mQ3pxZllNTXhhX2NORzllNTFtOGY3N0lQaVI2b000aFotTF9MQTNpRXltYlhrdS1LWkVzUG41bVZkS2_SAdQBQVVfeXFMTlpxTkZVdG0tZWxNYm96bzZTdmpZVHItLURuQ3dCT1hsTVo5UUdJdHphclVRTjhucG5vby16VnZ6ci1JZXFDdE1weHZmcHJTNmlmblB4UU5YeXcybmFFRDAyQUhlbzF5aUVDb1NCbHFZU0hpa1NsMWRaMFdZZmtlMmRsYmlzSTZISHo0WlpJRWpad0gxeFlDbDhIbkxRXzA0ZmNfUUlzNjNXTlNsa0lwaWJxYkd2VFIyTWNFRWxHbV9YLWt6dm5JVnVWbTlEb0hQbk5DUUQ?oc=5
panjang artikel: 7524

Fetch isi artikel:   0%|          | 8/2423 [00:37<3:00:34,  4.49s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxNT2JOTmR1bzRaR04zcXphbk01M2xxNFZ0S3JGU3FRTW9JMXNHWkNPZi0yOFpkTzZiNDh0b3NLWVJiSFRsOVM3MVROVlVtcmNmZDFrNmxuWTVWMEY0cFFLVmctdHFYV2VJQnJ2TjNkMkV6WFNla3BaV1lBVl9ORmpja1ZieUp0S0hrWngwNENhd1htQU1TdWt2Znh3amJnRjdHVFptRA?oc=5
panjang artikel: 3877

Fetch isi artikel:   0%|          | 9/2423 [00:42<3:00:55,  4.50s/it]

Fetching link: https://news.google.com/rss/articles/CBMiaEFVX3lxTFBwb3pPOHhxQ0VuT2hCQlFfbk14WVg1S2sxTHVPcFh1Z2dZeVB5Y0hHSnM3bXh5MEdqRTkzOEwyTm9hUDZFR2psYlZLRTNKREVFYno2NV9XVThKUm1rN0NtYnVneEUyMlI2?oc=5
panjang artikel: 7534

Fetch isi artikel:   0%|          | 10/2423 [00:46<2:54:55,  4.35s/it]

Fetching link: https://news.google.com/rss/articles/CBMib0FVX3lxTE5wWUtsdUlMUTF1ci1Cc3VLUHd4RnIwb2drc3JCVjVBTzNqYUFfMmxJdGxPYlhINzIySlM5OHpPQzFzRHRRbDVmMXNfOERSYWIxY3FmeF9DM3FITnlENVM0b3RvWXJpR0FRajJoZ3g4Zw?oc=5
panjang artikel: 5967

Fetch isi artikel:   0%|          | 11/2423 [00:52<3:15:04,  4.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMiiwFBVV95cUxNZWRTUUZsRjMxU2dWTEN4WE5YZXZvNVJ4NmRqdGZhY3pLOUNlMUhpcXZOVVltYUppMmtDUlpxQU5hc0JYSVl5eTNLTEdpYmVOUkcydE9aNGdwSktFb1Z4WVRDTUFmUXA2M2FzRXVZSUV1STFiLVRkUklYc2hYZ0hRZFl1RUM4VXJ3b1hn?oc=5
panjang artikel: 2310

Fetch isi artikel:   0%|          | 12/2423 [00:58<3:26:55,  5.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxNN0pxVGFvRVNWWjhhdEpIR2VYTmFhUmpkZEpjZ1UyYml2V2JTYWFReWd1MDhVYzdEZ1B4VnJWZ25KeGk1OFFfMWU2bFhVTWl4QXJza0hUaDY0MGl6eHlZSHA2WkZOVWZjVnM2SUhxWFA3RjZmRWdWVUJDRENwYkhXSnBjYlZsTEIzdmx6UUVsRWVveWRicFFsRmo4dzJsNmRQcDU5LWVlRGIzS1BkSVHSAbMBQVVfeXFMTTBfM0RXZ2ZRUHJDMmFRQU5acm9PVDRzZGVkV2VDVmQtWkt3WjAzTXJnTFZjZF9nZnp2cnRkakM2eW5sZzc3MU5mSnlwcTVwRV9iUVhvYWhON3R2TC1GNWhYS2RiT0pkQW9xY0RSM05oQkpKbF9lZUFldFpSbDdyRTN4OXJPaVVtcnFUSXNSVDRTYkdzNERBYXBkTWFkRTFXQ1lGZDR3XzQyTC1ydGdnamNXUFE?oc=5
panjang artikel: 6351

Fetch isi artikel:   1%|          | 13/2423 [01:03<3:22:35,  5.04s/it]

Fetching link: https://news.google.com/rss/articles/CBMiYkFVX3lxTE1vVTJYVFBITm10T3lIQ05wcllWUEtpYnFmc3NVUU43NWJIQTNYV3NvQk9lMGtrLXh3RmtvSVJMMTItNnVtV1l2ZzRCRTFaUzNXdUMzb1R6eE9CY0ZKNElXMFdB?oc=5
panjang artikel: 21865

Fetch isi artikel:   1%|          | 14/2423 [01:08<3:28:51,  5.20s/it]

Fetching link: https://news.google.com/rss/articles/CBMiZkFVX3lxTFBzNzNTZlc5MXpMVGVkSzg3OHFPVlBRWGhUOVE1MnlKcVJrMGU0dk5EQkEtTG5JUXlKaER6RkxuTVg1LWxuY3RHUmdQSWgwLVY3SjRlRVpTNFNaeFhGb25iRzZFeVY4dw?oc=5
panjang artikel: 7510

Fetch isi artikel:   1%|          | 15/2423 [01:13<3:21:59,  5.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxPMHZQUG1YVUxUTHJEa1B1VG9QWi1ILWhTc0d0SEJnM1B5MDRKNk1MTmRNREZJQWFVVEtlVGlCVW81Z1RjWUxtUDU4TTFPVHZ6RUJFVFc2dlV2N0szUEcyZ2pzRWd6alpzU3dFdHd2WUoxWGFCRTBrLWYxRFhxM1E3QUQzNmpraFdnal9RRXFCUC1TcjRDYkFCUk9pYkhBQ2NwZzF6eUJFVmhZckJEMk1fUmVUa0E5MXBqajZYZ2NvRFVZOV9ReTVzM2pTWjVNc1JO0gHAAUFVX3lxTE5Sb2czQ2pjbjM2Q2xlMUxXclRmem1sbFBJd1dFVDR5Tlo5VURIX2l5T3JCWmdSMjdVMlZqdThOY2ZwelRCWUhjMmYyczJvcEJXYUQ2cUR3aW9ETHN3cnN3YjVnemQyUjhMUXoxY2FoYTZodU1BQXpuYnA0M25nTmYyVXZfVDEwOGszVm5ySUZiR05sRHFmVE4wem9Nc0pqVUF3bzZsby13cktreHVYZjBhNnhvOXphbWxFZ0ZJVlB0Vw?oc=5
panjang artikel: 3919

Fetch isi artikel:   1%|          | 16/2423 [01:18<3:22:25,  5.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMic0FVX3lxTE5sNTNaWWx3SzhEWUUyZ1ZRX0tNd0ZXSUtRM2l6elMzLTBpeXp2M3YxTF9TMnNHSEZmX251ZDItUmdoNEFQWmo4TW1Kc0JwcDhXRng1RTNqekJyUFdZRXNLZWV0OTdYbDVHWUFmQ2JhTjhtNzQ?oc=5
panjang artikel: 6666

Fetch isi artikel:   1%|          | 17/2423 [01:26<3:53:47,  5.83s/it]

Fetching link: https://news.google.com/rss/articles/CBMiZ0FVX3lxTFBOYktCUGo5UEpQNWNnbkowTm0wUW1tOEU4YlBYU1gwdlRfUzBYQ0hBOTRHU19PZGJlX1I5c3ZER2dOQ3lUQ0k4S0t6aWU0czJiblh2OFB0QTlnQUt1VlBGS0RhSmpUY3c?oc=5
panjang artikel: 9107

Fetch isi artikel:   1%|          | 18/2423 [01:32<4:04:06,  6.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMidEFVX3lxTE9maUNtQkhUSFRweDRnV3NaX1hVdG5NRXl3NTFySXR2VEdsVEtXZTN1ZWplNnBoOERrU2IzZVowMFlDVmdBalFkUkNpX1NpelJlT1ZsbW9NbnFVcXE3X3NYM2tmQ1FwQUVnNzFpNWVqWjVnb1po?oc=5
panjang artikel: 6813

Fetch isi artikel:   1%|          | 19/2423 [01:38<4:03:33,  6.08s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxPblBtVTZvS2VxX1dwNGJpVFh0ZDlvR0duZ0k3X19FZTFEMHZvN3hwcXVqWEZqd1g3RDZtRVJUdUZZMnpzUE05ODhIREZ0WURXbDNtMTdJWVA4Ym1KdDUyYU1kbXgyekJDQjRfQmFQdGd1dUNlellsTmR2QU1aLTVKdHE0MVo0aDhFaDBpVUhkam5fRlh0MW9xZG9JX245MW1ZZjBPUnloYXhsczAtWXREZjVfdmNzTHMxUmI00gHAAUFVX3lxTE5HUHlDRHR2TXFzQ3lxc3A5MXJaN2xQeXpPV2xzUDNBbG04a1RyVkpvTFExd1VYYjFZTmNpTXQ2bUExbEVmX0N5NTBCVnhoQnlsTW41WTM4X2tMeF8wT0RQLUc4Vnp4a3NZTVQwLXZjZ1YzQ0NORUtNeWU5LW52S2FQVlBFR1NiUEpXMDg5OTI4VGt2VFphQW56RjlMb3NzVDhZbVNKUXJfQ0xTNFVpcnVNbDZtczFqVXlKbHZ5NTBWSA?oc=5
panjang artikel: 3683

Fetch isi artikel:   1%|          | 20/2423 [01:45<4:12:52,  6.31s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxNMXNya3g1THViRHZYUjlqZmdEOE1uUTFMc3NCWmYtWkM3Zk5NbWZXbHA0R0VyY2hZMVdQRWIxWHliRzBQSUZTVXpKZkh0Z290MDByYXJUeXQtSHM2YXBtU3hhMWFXcnZ6QnJXZk4tUV9YbDNtT19VbXRSY2J4TElLOW9aS1hPYmtYUkpEZEFhQTZtQU1KdkZkVXU0QjNIM3A0RWxEenpkcWJZMkh6OHVTV3VZME9xVFB0OGlSLTVCOVlxZw?oc=5
panjang artikel: 2274

Fetch isi artikel:   1%|          | 21/2423 [01:50<4:00:44,  6.01s/it]

Fetching link: https://news.google.com/rss/articles/CBMilgFBVV95cUxPYmRfcXF2bTQ1Ukt6a0Yxb1dkTXp6SjdYYjh3bE9PUEQ4ZVBUU1pBOXBydndzdHIzU3BBTGVKanNPUDVKSVEtb3Jrano3aWd5eUctZEhfWFQ5blE3RU43V3U2a0JnSTZoN19vZTdGWmZ5a0ktYTJDMTF0UUp2RzVvZWo3Q3FXQWJqaEJOekpDaVNrREhOZlHSAZcBQVVfeXFMTWhlS1JHZ1E0YU5tS0VCZ1E1enlyNVdSRnVhdHpnZWtWbjNyN0cyWUJxM0lWNXZCMk5FT0FQanIzMC0zQUhLQTR2LTFBTmU5ZjN1cVlya215WHQ1Vktfc2Y4WlZTUlNuUTdhUDR6RTI2OGhoUEZhMllBbmFKbjhoS01DSGV6QTZ3dUlNSzFTTl9lQWhSTnFiSQ?oc=5
panjang artikel: 632

Fetch isi artikel:   1%|          | 22/2423 [01:59<4:36:30,  6.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxQcHJVWWF6SG1sSW01bncyaVlMb1pYV3FkZFdyOG95bFBMa3I0dnhmeEd4dW1jSFZwSjIwMHp3eHVTbVdtdjRMX2MzWHNmQjN6aVBpUnp5U18zSmtzNGVGVjNDRXhmNzFTb0wyM3V5ME50emNFRTRMc09rUlRtaVB1bTdrMDNoZ1FZMDV4amttVkFGRDZHZy1OdnViQW1ZdTBMUlNlbUdMRVNtUW1uMXBiZ1JlZXFhOFdNUTAxT01LbVNsbm1aQ1BxMU0yRDJTUQ?oc=5
panjang artikel: 3422

Fetch isi artikel:   1%|          | 23/2423 [02:07<4:43:26,  7.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxONm43VkVVYlExc2w0ZHRJckNqM0hSZnZGc01UMWRyOFU1OXFfb242WkFaSElTbHdwUzI3SFVybmd4dG5nVmRMc0JjVnY4bWZvOUR4MlFiWVU4a0dJOWNyN0tiT1NwZVZCcEQ4WFpMTWd2OVh6aWh6MjVmRU9nakpjankydEtsWkNXWXhfWkJueEJFU2plMUxRaGJUTml4cU1jdW4zUDJLQndyOUdXbkZYeEd4anFuWU5Zek9UOWRLWVJ0VGc?oc=5
panjang artikel: 6185

Fetch isi artikel:   1%|          | 24/2423 [02:18<5:25:39,  8.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMiaEFVX3lxTE1hMzNEQlAtQzVGN2tVbURBclltWU5Sczdac2xycDN1MHJmSDktdFFhMjExY0k4eEtTMU5WN0VhSURHWkZaOFRQNmZsb1ZLSE5zYVBRY2VsMnV2c3NCT0Z4MGpuVE80VVhY?oc=5
panjang artikel: 6448

Fetch isi artikel:   1%|          | 25/2423 [02:23<4:58:33,  7.47s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQX2RudkdjWWNkeDh3LUxfQjh2VmUxVHBTdGpOTXN6dHdVM0ZYNzRxeXQ1bkh6eW1zRjNkTGlvQi11MmtkOFNJdHJodTJTMWswbmpCd0YyUjFMZ2VnZ29pN3VSal9CYWhnbVhVWTdudXRtdjFFNkc0RGxpTmNaeDhpY0wtNTRMS0FNcW5YeExSb0pwSGs1eWFkYi0wcFRTQmJlQjg4NHpHeThVRmFVZ0lvZ2hpUWV6WDJQWHfSAb8BQVVfeXFMUGdmWWdiQmdkbGNRUkJmSk9qOG8yNzJkajZlc3dfMnV1QmdrTUt2cjkzdEZsd09rTjBSQ1hwSlNneFhvVVRjb2ZqdVIwVWZRYjFkb0EzV1F6ZU53WlBGbFFPUWM3NXlYZ08yRGtrbEZjVGhMUXdRa0NudUg1SWtjZFdFREwxX3E4UzlNd3F1a19kZXhmWTB2bF96T2QxNFdLRmp2QUxJNUhaUUc2d1pJeDllcDgxWi1CY0ZzTWtHU3c?oc=5
panjang artikel: 2998

Fetch isi artikel:   1%|          | 26/2423 [02:31<4:59:02,  7.49s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPRV94MWQ2eWQzQ001amJ1ak1yM3Q3V2tEeUxSOElwaHFTc1U3NmY1WWtHOVJtR2JxR2pSY0ZKOFNMY1lyM2pjSkdscW14TlFIUW43N2VDbjBWR3lENmhpeTdfMjdkWDBBZVlxTkdTaGVmeTdsV1oyQTVkUDNhSjI3eUtPY3hyVHIzemVHZk9tbFNkVUVwR3A3RWNReWxQUHIwOEtHN2VQV0ViSDBjeUY0ek5n0gG3AUFVX3lxTFA1YmxRUlJvQ0tZa1BvYlZDU18xTWZ2aG9pbW9PZndseW5fSXItSXMwam9mak1NSzhLVF9IQUQ3djBsLXFZSWsxdTNRTzBUdWU2WkFaS1lZR1p0Z1QxQnZPV0V5WS1FaUtObG9MMjF4Y0lEbWNPTVBITUxVc1JqU21CRTdkaFNMWnZ2aHp1Z1lLMmFBSEZTYWNXLUVnZ1VIQ3czMExCcUtTUEtTcEpKdnB4OF9EMi1Oaw?oc=5
panjang artikel: 2209

Fetch isi artikel:   1%|          | 27/2423 [02:38<4:57:12,  7.44s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1wFBVV95cUxOUkJlMWpoZVN6Y2FrR01PVzl6RUFSQ1Z2cmhmNXItVnNZbGNOc2NqZjBfRmgzbEhpMVB2YTJGQ0dvSTVKb3J2S0l0TXRuNkFLeWxhb2c4UU9jU3puZDJRUE1nWVlqaWNVb0dfWllKT2c4c3pxeE15MnNHQ2VQZlA3c0wxX3ZId2NzcXFwR3NtM0xfMEVEdFE1U2xTYWd3TDBzSmdPVC1KWGFQZ3hpNFVPcDZwZDRGTXJyeS1xLXFzY2FZY1RkOW9qN2RrZXFSdWlkTVAxOUpMYw?oc=5
panjang artikel: 3326

Fetch isi artikel:   1%|          | 28/2423 [02:44<4:35:46,  6.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxNenIwVFhuRWo4VjhfRXRQQW5HbFRXSjZKcUhaWTU0aE16Uno5YmUxUlJqQVNpaHdlRWs0aWpIN3NUTEJmYy03aVlRNzJ4cG9xU2RFQmkxYXZNX0dNYVpwX1FJazNUWjdHcWNRS3AxYWkxS1REQnkxNmxmZ2JxQVh2SlNhQl9FZm85RnVzQmItUjBNSWRxcloxR1R0WUJCUEs2OVE?oc=5
panjang artikel: 0

Fetch isi artikel:   1%|          | 29/2423 [02:51<4:33:28,  6.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQSjM1aWR6R3pwR1VKeTExQ3VxT3VOWmdiOG5VXzBfUjRtMkZ0cjhjLUdpUFM1NDFzMnZqNzc3ZVBVOVVCX3ZsUEEyeC1HRkx4VDNGLU01bkFiMDRldUJlZVRuMVdtbjRmYzJMVm5zYlFSdTZzVVRheXBlbE5tLTFNWGRaVm5aWHZPRC1VeVNfN1hLTGNzTEZ5VXlpUzNIQnNTeTZlRi0tRlp6eDV2bUdRaS1CWi1sUVJmcXc?oc=5
panjang artikel: 5708

Fetch isi artikel:   1%|          | 30/2423 [03:00<5:04:47,  7.64s/it]

Fetching link: https://news.google.com/rss/articles/CBMikAFBVV95cUxQWFZEQ0RjQ1RMRUdUbEI5Y0J0TzRwRnRJcjZCWU5kdnVLNVh6QzZmSXlWaTFYUk03YmNUREdUQjZ5bnhnY1U0S201cG9LaFRSQVVmdkVQaVRWWjZGc1hHY1ViYmpycmkxWHc2blVTNkJxclFHM2lIZ3R5Wm4xWDc5Z2dPR2hOYjBxajFKWWtDQjHSAZYBQVVfeXFMUEI3YkphSkppc3ZfWk9VeTFpOUlzQWJkWFNIbUYtUDgzUmVTeUtFU3J4blFaakFGTnRwVmNvU0pzVmpFMDhwOUVRb2ZQWldvTzdaUmJmY25DYzR4ZmZMd1ZxRURpeDBiRFNqV1BWV2h1VkY0WVBIaUlrZHh6QmVDb2Uya0pKMm5sV1NjMEhleURITHZSbWNB?oc=5
panjang artikel: 399

Fetch isi artikel:   1%|▏         | 31/2423 [03:07<4:48:44,  7.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxPWmZ6SExGYUF2S2JlQmdHOGxxdERGaTZfcGt6Sm1CLWxmdmtYX1hueUNXckNmN3hZY0VYM2pjMFZFWjNSYTRVT0NFczYxV0xKSWxqM21GZ0djbEE2SlRsYk5WRGljSUNQdkZPNGhBRDRIVDlMYktqMlUtc3VBRVdndlNqRWFkMGh1MnA1RXZJYUpmSzkwWHRXRDJCeFljN2VfTTNMUGtneS04RUJ6QjJv?oc=5
panjang artikel: 2599

Fetch isi artikel:   1%|▏         | 32/2423 [03:13<4:36:55,  6.95s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxQQXU4NXltUldYRTg4TTBmZFd0dU9ic1lyVW10ekZYMGczblJweGl3Y3NHa1o3eU9VWTFGVVNIOXplOHVsNjF3a2FSeGV0UGRVR3hSWVNNYUlrTllreXg2NDNaTjN2WmJTdzJvZHNxYzZoU1NvdUZ4R0FFdENySnRHeUQ0dHBNZEVqTWF2WFBJZUl4OVFXUFMtdkRUb1BKTzdSU0txSmNrS0I?oc=5
panjang artikel: 4432

Fetch isi artikel:   1%|▏         | 33/2423 [03:27<6:04:57,  9.16s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxNLTd0c2dqZ1VRYTlwRmRjUTVPT0wzc01xVFRTWVEyU3E0UVI3TnJXVTVIQWlFTkF6SXFlSm0yTXJROEtPNDNMSWRocmZxZ3JmR1JGWXRKV3lpVnFMcUtOSFQ2QzFrMmI3Sl96YXpiTE5ERlRBeGxvU2tSeWdzYUt6TnJNaDJYaVhFbHg2bnl6MS1OODYwN2JGbGNNOXJTNDlrbGltWkk4cEI0VWd6RkhtU1VMdEpseU1OcklFbnNVVdIBxAFBVV95cUxNTWw1cGZXek9PMmJiSHYxT0xvX2xrTmE3NGtSQWM1aDRsOHB1NXRXUk1zanhlakdVTVZZTTJLenZCSDI4R2J0TllrR2NfYWlyZy13c25hTzlGcVNQLWNpSGstZEg3d1FreEF0MFV0aGp4VWtERkVJZXZsSC1wV2pBaUZxQUt1aGlCVTFRYkpBMWx6TElhWFZIR3BjOGx5VlN6NVpoSGtybm4tcHNUc1FsVDJPX3YzZkx3N1A4Nmp3NmZ4N2Jf?oc=5
panjang artikel: 1036

Fetch isi artikel:   1%|▏         | 34/2423 [03:33<5:19:51,  8.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxPczVFYVg3NlJQTDRVa2dDZW16aFd4NERYUU1ibUFKZDB5YnZIMzhrYUNtMURLcnVoSkxpT1RpRS1mN2NYN0NQSXVGMkRHRWRqQ05mc3hlQzJtOEpJME9fbk5oRWxXcUJTUWJxWHBLVktIaVBDRHJ4eE5TYUEwSjVNOVNCbndpb3BwYmFaOHZEVnFvZXIyUlJsa0tiUDZSa2cwXzFWSEpkREgyNlIzQWxJY2w5YTRZazhnMVdGbzNWS0xVWXVkY09TcWFuczhnbkJRN2JHeHJiQTVTdjjSAeABQVVfeXFMT2Q0ckx4c0FCeVVqQ25HS0lQejR2aXdNR1ZMRHNQYlFkOXhxSXVKVHlxOFVDLUdxVXBwVFJNZE82eHRLY3lUWXlOOFBZR0p0NVhzQ2N3a2RMN3BuQmdoLWMzMExTQXNQMXp4eURrekJnLWQxaUg1Qi1uUDE0RzZDMFZWQ05UWGp2eGNnUTVYNkJsb29wNHdmSWpXZFBRSlFJcWpncG0tU2dWYzBHT1UxazFISVc0Qm9vYno5X0VFWlpDQzIwYldDcjZjYm1kaXVjaXBrNHQyWlRmUC1TNjhqY0s?oc=5
panjang artikel: 2799

Fetch isi artikel:   1%|▏         | 35/2423 [03:38<4:44:07,  7.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMif0FVX3lxTE1KVHNXYV9uMy1yaFczOFl3ZkxKdWtsVW4waVBSNm1xOTBEclRsU2tkU0tUQjlTNERlWUdTSE9vRXZkUWp2MUZEbHoySE5WNEFha3hQSno4Y0ZzUThnLVRUUTJkcDdNYWZCTzllZG1LNzVFUnp6M0VVOTkwQktDWHc?oc=5
panjang artikel: 13707

Fetch isi artikel:   1%|▏         | 36/2423 [03:47<5:07:18,  7.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxQbW9IR3F6U2lidlk0azF0aHJZZFRMQlNYNlZXdkZGNUtnS0dhT3JuTkE4cldzZTJScWhCNTdKdlVkWDVKRkh1NVNHeVZjcHFoMlk4LW15ZUY1VFh2bjd5NG5wTTMwTnd5UllFNjZ1US01NFFzLTBnM3J1THV6YTQ3YV9hUmdBTml4N1VNNkptYW9laGZwU000WWVDUGt6bWRSb3g0eTFDcmM3MHNsVWN5NlowQQ?oc=5
panjang artikel: 3037

Fetch isi artikel:   2%|▏         | 37/2423 [03:52<4:44:11,  7.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxPTm5kRGplYXRoZk5XNml6Z01MRVI1akZFSHdtWkZLNG1VSGpfcW5lam9ESEVneUVKZzN3Q3Rsa2t2cDAzRkN5UnU3MWpyT0Z5MUhkUWM2MlhGWE50alJZc00yQ0Q3NW0tR29xTnJQQnFwcDE2bl82Q000R3g4MVdObzk3S29wS3FfUm5GczVaMHFhUGJSZWlOQWc5R3VkcVYtOXc?oc=5
panjang artikel: 2025

Fetch isi artikel:   2%|▏         | 38/2423 [03:57<4:17:44,  6.48s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxQd0hfLVVLQnlCamlHdnRvVUVPV1pzcEVtWUVxUXJ2RWJGZFlHbzhIcVpkOGVac3hoNk9fR01BVkQxNWk5YmtuY3MwT0RZb01DelRTSTgxUUtyNVd6eXZxQkM2ZnZrOTlJdkRnOUpuczh3RU96dGtuVTZ3VDhzU2xzWUZCMW5Fb2xyYWdVUjZFZHJqdW1fbFlXMGNyTTdXdGl6MDZCUVgwbGZQS2NaXzM0Qg?oc=5
panjang artikel: 1749

Fetch isi artikel:   2%|▏         | 39/2423 [04:03<4:05:51,  6.19s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxNX2pfQ0VId2JlUVRjVGN4Smw3VERTdkZiNjNWajZfWXdzSmR6M1RGbHZINGRRZmg0MjUzNjBLZzRkbUhaUkhxX0puMVotYUpZLTdTMFJyVUoxTW82U1VIRHVuenJ4ejdRaWlaMFpfQkIwZTZUNGZ4bTF5cFRRYURiTlY0RmN6cTRjem0xbnlRZkhBT3lGNUZTOWdzcHpDS0NOWVMxd0w1RU9VYWN0MFV3eFM2UEdDVjdkcHBjbEQwR1lHQjh0REt4RGFR?oc=5
panjang artikel: 7414

Fetch isi artikel:   2%|▏         | 40/2423 [04:08<3:55:18,  5.92s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxNTnQ3S2VJQkhxbGhTNndVaTBXdHRBcDZTbkJya1lUY3lEd0xLN1VQbERSR0lyZ0JxQ09fRG9Pcm5PLTFYWUVTVENRdVFkV29KMGw1emU1X0tXWnRQTE15VU1NN25iTjhVSEVHQzFhTnF6QmZFRHJSOTRKSUswc29Fd1g4Y256cDRNd0FxdnZ3dU9Bd2NsZXdpY3ZiUmpKX3E5aFVickNBa2VBamhTWm0w?oc=5
panjang artikel: 190

Fetch isi artikel:   2%|▏         | 41/2423 [04:13<3:36:20,  5.45s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxQWDkzb21QcUJzNnFoMHlyM2JYY3p6dFpBTlNGcWtmQ0hrTG5QNVBTbVZSWE5HU2M0U3J2VnphUElXUTZkdlpPV3EzU1VtNkZ2ZGhJN1dzZHBnei12UkROaXNpcjZic0h1RnhRMS1Hbm9hLTJtemlyMEN5cHJ5X0tWWHRzZXAzaHd0ckNGTkhqcEtsS0NReldTMjMyenNhOUZDTzdiTlRLRXdaWEItN1RpaVpLdzE4c3hZLVdnejV1YTFDYkZ50gHKAUFVX3lxTE94LXhpYnhhckxkNmFBRnFkNkx5SXZxcUI4ZUtXOW14YnVTcHZ3cDZrS19xVUpabDFsOG5XRkVYZC04YUU2LVFNbnN0VHJuTjNOaU5CcU5KbFlNdGUxRWgyT2FEQzZ4R05wQnFSR3Jja2VrS3ZpTWs3bVJOSWdfVXloMV95YzVpYTRrSFZJemY3WW00MkZzZUp0X0ZVaXBIM0VBdUtVODN6dXF3bVUzLW93QXhWTV9uLXAtQ1pYYVdPaVdvU3JWUWg2c1E?oc=5
panjang artikel: 2299

Fetch isi artikel:   2%|▏         | 42/2423 [04:18<3:32:55,  5.37s/it]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxNVFgyRUdsSVlpSlIwUlJEVUwwcGhPa00zZXQ3R1gxaXVsVkw4OHQwOVByTjNGYjJjdUNWajZZTmZ2cUdRd1l5WHdtV295eGdyUDY0cmpiLVhrdjlZNWNRTFk4TWZaWUdaUGVOSl9NeUtqRUt2Zk9TeEFyQ0VKQkx6b3hMQzc5QnpCVjFleFgyMTZHam16aEIwNmFoNGM?oc=5
panjang artikel: 2912

Fetch isi artikel:   2%|▏         | 43/2423 [04:23<3:26:29,  5.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0gFBVV95cUxNeXFWYmpzZlR4YzFUQXF6SEc4OXBPM29Kdmt0RHNYWGlkQTJvR2YxTU5VN3dVZi1DMU1Ud2c0c1JEX1BIaUY5NVZubkhBVEFwU0VkRFA3d0FwRGxCYUFpX1dkSVczUkdOSUMxeGR5Z0xtQlhnNzVLeGhMMkR5UmdVdWN2eGNOcXBXczA2bGdhOTdoYmlpLVdnaTU0TzZoa3dEbFFmd3I3ZVhVT1M4aGRCMzZuT296R1ltcGxLMHRtZ0FQVzI3aWhZRUZTaXlyRlI1RWc?oc=5
panjang artikel: 0

Fetch isi artikel:   2%|▏         | 44/2423 [04:27<3:14:40,  4.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxQTThTenFzZHlDODdVX1d5NFhBRlFwNmVfT0xuSDZLUHdFblFiSmxwejU5THlFektJSkU1TV91SVZXQkNUNHFoV29BMEZiNHZ0dzhTU1F1QVZUaEtSem12czl3R1dEa2dKam91MmlldERLY0xYaW5Ea0ZWZFhUODcxX0VuZGZ0bDNKODdIRHNvVS1RT0cyZE0tNWtqUEMydUlHYWM3a0Z3RFhFSmtEWThuRjdTcjRrVWZ3TVo4M2ZYR0Vhak9YcHY40gHMAUFVX3lxTE5vZVpPRWlDd01RN0VpcEJFN282VFYtWndscnZWbzZpU1RIUlRaR1hxenlPM19hRW1kQmEwMW5CYmdidkR2TzNHMm81MFNmaUhfM2oxaDh4ZnVDbXNuVmdYeTQxQlhlb0ZiNjRZdWJaNnh4Y2hlU2NFVGNsZG5tdVk5eWlQZ0NnbGk5T2FwNVpJWk92X2xfUUYtQjFlT1ZKSVB1cFNKVzVNVHlVTWo5Q0RiQmhTaG5oeEZWSGJGMGh5Ul9GZGJycjR0V3NWag?oc=5
panjang artikel: 4945

Fetch isi artikel:   2%|▏         | 45/2423 [04:31<3:07:39,  4.73s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxPcXltY0FSaXNYcU9pcjRzb01ENGJ0N2pHRUtZVlJOdmF0ZDdxdUZMZzd1UFJwLU9FTkRheHVUNXNjeE5NX21uclprVDhwcFl6Vm01ZVlaN05HSGNXZm9ra1ZCT0NZb1kyTTN0YkJHN2tsRWxoMER6TktfdE5oYkJqUXpSdjY3YjVoUndIdU1CV2NDNUQ3YWZDSjZtM1luNmpjd0E?oc=5
panjang artikel: 2184

Fetch isi artikel:   2%|▏         | 46/2423 [04:35<3:03:26,  4.63s/it]

Fetching link: https://news.google.com/rss/articles/CBMiZkFVX3lxTE8tQkwxNG5QNnNiYUZOUEZRQkZIcVVwLUkwUjB0Tklac0wtRUNkTVlrS2g5TzFVc0E5bUxvemlENVBYdGkyZW9KU2V6VV9oR0thUlk5RHVEY0VSclVDM0Y0RDlXQWlSUQ?oc=5
panjang artikel: 5649

Fetch isi artikel:   2%|▏         | 47/2423 [04:40<3:00:33,  4.56s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxNZzRqZ1FZQnBvUTRRLUdnNVRVb3VDdVpzSTBXUGo1aTVPVVBjajZNVWQ4czEwQ3pnTGFReHF5MUNDNFo0cmtEaEZvV3RWT2RIU3RmNmhtRUxkT0lUcTJFWmZUWnhiTW1QNnB1Wjc4OFc3SkZpT2JPX19vT0c4SXpwUjNYbnB3a21CdV8tSHBSM3l6Qk1jbm1remthM1lFQm5vekFRag?oc=5
panjang artikel: 221

Fetch isi artikel:   2%|▏         | 48/2423 [04:44<3:01:00,  4.57s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxPZVBEOEltcWI4MHo2bzdfSkRCSUlqNFM2R1JaSzVTcmF5eWxDX3hZSFMzUkVpX2ZDS19nOExDRlpyU0licTdZaThpMklwVnBzb3dvNkR6dHQ4WmdjR2dXU19KSjk5OHNTTklhZHpxdWhuT1g3NF94VkZBbm50TnJ3NFR1eFJUYWJaVVlmQWMwTWxTejAyV0lSU3h3?oc=5
panjang artikel: 759

Fetch isi artikel:   2%|▏         | 49/2423 [04:50<3:15:10,  4.93s/it]

Fetching link: https://news.google.com/rss/articles/CBMipgFBVV95cUxNUFVBR2RnWUVmVFhjdWJqRERMRXNIc2VSS29TUXJzT205NFpraXlhUEo5VGlaczlmcWJmdDZkVmdEWmNFTzVwbmRRTTlKa1BKOWNVYklmS2pMS2dwZkxHT203czZGVDc3cmFyS1JqUkVRRVI3T092Zk5pcHZNeGFWLTdKa09FTEk3Y3RRdEZSeXpSVVJpSkw0R1RRTXlveVhBU3VqQWhB?oc=5
panjang artikel: 2405

Fetch isi artikel:   2%|▏         | 50/2423 [04:57<3:36:21,  5.47s/it]

Fetching link: https://news.google.com/rss/articles/CBMingFBVV95cUxQMVVxdU9zOWRFMTR2MWMzNHNrX2FhTUhURzBEc3BlTG9NVVp5V1RTdmw0TEwxeTVJU1ZqRnhQdms3RzU3WHlNczFIa1ZnNEhEMjhjdDJzTzgtcHhDQnhIbEdBX2FtTEpkandBTUx4M1hzS0piR0NQQ3dpU1d1dzM4MktzOVpDdzdBc2JkUENLLUMzM3ZhajZLVWhoUjNDQQ?oc=5
panjang artikel: 279

Fetch isi artikel:   2%|▏         | 51/2423 [05:01<3:19:41,  5.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMiowFBVV95cUxNWlpIa2l1VV9WU25ubkRHM0phc1U3X3hZQ3NzeFo3dFNLRU1BV084QzFLN0Exb2w5cFUtb1dPV0I1VTZ1d3JYb1RReEg5cWVIcEJuNTdkR3c3WTlrd0x1OHlkZENkdDNVTkV0eDZkVmFTMi1IOW54Q21mckdTMEZKSmNZbHpoTnhGeGh1RVg4LVMxYzVhNDBKS3pBbHZRTDRwSHlF?oc=5
panjang artikel: 275

Fetch isi artikel:   2%|▏         | 52/2423 [05:06<3:18:00,  5.01s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxPd0R6cURLSVBiVTh2cVg2cFFkSTNhaFJXUDEtYU5lT2tJUE9jMVV5RzBxODFUOUVVNlhOQ19hSHBpWDZVaWdxVmpSMk16NURhRkt2YmdWNFF6d3pFc1RWbHJoZDRSQVc5bDZaNEZfMXcyb1VjUjBudmZKRmgtRE5QV1pZbjU4MW1RQlN3R3R5Y3BXMzdNVV9UYUxMOXFEd3FycU8yMm1ZZFRPcGs?oc=5
panjang artikel: 188

Fetch isi artikel:   2%|▏         | 53/2423 [05:11<3:16:46,  4.98s/it]

Fetching link: https://news.google.com/rss/articles/CBMingFBVV95cUxPci1tTk5IaERxNnpHV0xFblpqYS0weG1wTUZfQkFMMmhFcTJYVGdjd0dYbFhvOXhScURuSzY3QzRBZlhQMTNWckNOTFdLdDEwenFDbm1uM3IzUko3QWdCenF5WWhRVFlUV2s5SHNwQlpiSERMYnFDNU1uakJleTZzNTQyUXJLTzE5TDgwVWF0RjM4el84eTdWMWREaUtMUQ?oc=5
panjang artikel: 192

Fetch isi artikel:   2%|▏         | 54/2423 [05:15<3:12:01,  4.86s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxQbXFCUnVHTW5RcDVUZVExZ2VQVGdkX2NmaDRRNkpBS1ZNbXdaaTJramY0OGJ1SFFPX2NZcC00ZXJwOW95NWtIOWZZcUpkM3dWYWh6b2dGUHVIbUg5Y25xNXVUcGJ2d3JJSWk2bGdzMEFILVdYdWJURDdjUGlfRHZYUlBUY2ZzQTVZVWdSZVpRVzZGbmdBX2pBbGlwaV8xdmZfQmdhbkpHSTJ4eWIzMm9HbnpR0gG3AUFVX3lxTFBXdWUyRGtPb1RKUGhqTmdqeXI3dm9FcUhQc1lXOVJJbXd3QkpPeU9wY25QRjhmQjJJSHdHOFR1SVlzcnY1TmVBZHdjcWtyWWliX2ppSEh3LUdOcFVUaUhZQTlWemV4b09ibk1WRTVRcnE1dUhPVzJZWVdobUF0QnhtZEFxcHFONjVrYW43Nk1YUFBjTzE3Ql95V1dUbEp6TE5mLWNtNVVlMkFtSG9aenltS2x1b1RlZw?oc=5
panjang artikel: 2318

Fetch isi artikel:   2%|▏         | 55/2423 [05:20<3:07:18,  4.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMiowFBVV95cUxOazVzdWVQZ2hERFF0MFZDdFBLMmpNTEE1Y2NPbEtIUjZGb0otSVV6ajdyYTA4RHZsdFdqV05sYkFRVE94WXRkR0x0R1R4UjhwT1pfNEU4eTYtV2RXem90LV9ESmtSQVp5bjdZdzZOWGxHbE1zNGpuYllTcVJRSFViejRvWnN3eXBUX2gzUkFSczQ4NnJpSmFGWmN4V2hodDJ2cFR30gGoAUFVX3lxTFB0eEpaTXdIVE5qTzlUSWM1eS1xT3FoNWtzT21mOU1yendvQ2IzWjg5U0xDR2RlRnVfTHhBaXhYRkprUldJNG00eE9ocnNfOW1OaXhNQVA3VHhvaHlQaTZBRDVtNmZNZXp2MDNXMGRoN0FIWjRPcWNUQnpQTjlSQlliQklWVkpMODZCblh4VlhxVW1zZmZYQTBoTnhGbzc1YzlEMGFZRERMcg?oc=5
panjang artikel: 994

Fetch isi artikel:   2%|▏         | 56/2423 [05:24<3:01:29,  4.60s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxPaGt2ZzhrR1NYOVZoUE1nLTZBbks4dVJTV2dFOVhFRE5fVUtSdXU5R2dJeUpjNGdEaDhQS3E0NkZvdjRtd3VFU0dfRld5eFhjaDRfSVBKMDVneDZ6X3FSTmVDdjg4bzE3bkh3YThMTVVKRHhlbEZLWFFSUEowVDN3YzJrQjJNcFNpQUdfWG1LR3p2VmRUOTBQN3lJUFJ0NTllbGtjNmNXeG05MG5J0gGyAUFVX3lxTE1HZE9uNnhwSWk4RjNXSnpoYTFXMFlvUWNPZFdTSW5XR0o2OVhWbHhJeXBuV2JVVkFra0M5UTdsWnhDSVNTMHV2R2VwVVBJYTF1UFpqREExQ01veklnVzNmYzdRcHp3UDNLbnVSQ2QyRFFNc1NOVzNiUTJlMDNDeUllcWxXd01Rb0psWEp4a24tTDdkbDMtTDNZbDFLbE0zeXpxeExwd2dINExSaDc4R240U2c?oc=5
panjang artikel: 2889

Fetch isi artikel:   2%|▏         | 57/2423 [05:29<3:00:37,  4.58s/it]

Fetching link: https://news.google.com/rss/articles/CBMingFBVV95cUxPdFBwemd3UHdNeWFiZ1ZiNXpCT2xxYkptWVdqMGkxaFpxNzJGUm9nZlRoZVVuQ2dkQWZmWUNocUQteW9ndDJyb0JHQ1VLVVdtQ2Q3cHJWNlZoUWROTTNvd25fUmJ6cGFPTnl4aWp6cU5FM3RqRmFFZHE0czhlZjR2RDV1QTFiNHM0UkFZbGZqVzlmbVcxaEVCX2lmSnZadw?oc=5
panjang artikel: 3557

Fetch isi artikel:   2%|▏         | 58/2423 [05:34<3:07:24,  4.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxOSUs0Uy0yYVpENTNpekNaMG12TTNxR216ZVFCN2lFb3Bza2dJamV2dzhGbjk5bmxjbE5qdWdkN3I4cUxVbXB0d2UxZmJUQmNvYUhNb20tMGcwRmhIZGN2R3lXMFBNYU9hRF9CcWVaMmZOQTRna0QtVW80aWFveVhGeVRWRTY3SC1nUmM2MkxheGJFb21DeWk2LXFOa3JWcEhMZzZ2UUJ2SzRIWlMtbUs1cVVkQ0R0LUY5WjZsQVhSNDlKdw?oc=5
panjang artikel: 1232

Fetch isi artikel:   2%|▏         | 59/2423 [05:39<3:08:35,  4.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0gFBVV95cUxPT2dseWE4cXZrdGZTY3pMZjU4SFJoZXBMMC05VzRYUGZpd0lRTUhEOGJVa1VHZU4tQnRiOXdQaVh4TDRRVVFrVHV0Y0tyTk5KdVdpOXFMSUpwNWxMQ2NnS2R6Q2pkU1NkVE5GZEVUVHZ4c012MDJSdzlRNzZ6RC1TQ0RBRFRGdXE4Z01oYVk4M3V5aXBybFBRQXoxR1k0OGlPcUZzd2VZUGVBNUNfbWwwWHRRVXpwRllDeFZURXlnZG5YMXdvWnYxLWFwaEhrcFg5TXfSAcIBQVVfeXFMT0ZTVTZ0amgwRVdPSWxDX19ORElrdGxVTjZ1ZWNDcWdZLXR2NzlFQXVzc2FQWUFaZlpILTN5bGtvYjJKeTJHWDFSUVRLM3ZMRE53Rjh3WW5FTDd2bVFZeW5kUm5hU2dqeGhRMS14VzVxX2VPTEZtS3FtVUt3V1RPOU9BcTRRZUdGcFlWemdqanE4c0xSaTVJazQ1WVlyMWtCQ2FLYk9TNERhblhCOElwNjR1b2NqN0d4OGVGVnJZdFdwVlE?oc=5
panjang artikel: 4661

Fetch isi artikel:   2%|▏         | 60/2423 [05:47<3:52:45,  5.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxOS3E1cWVianUwU1UxZndzc3lBSVhpSG02V0VmREtLNzdCclJ5XzRpSmhqNUNmNmoycTRFdE1mX05HbFQ0VWtoVW1CcmZVRzRZajFXWjd1a2swcU5kYUxuLWpTUURqQkx3V3dGS2huUVA5Unk4NHBCV0ZqcDdJb2pLS3d1OUVfZDRpTjJvcTRHZ090eF9rd2tiazZBd0IwN2V1WkFOQTFXbHZyUERQVXN0WTlnekszUQ?oc=5
panjang artikel: 3753

Fetch isi artikel:   3%|▎         | 61/2423 [05:52<3:33:34,  5.43s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxQR2lOVjI0TlN5OUtKVzg0MkdFUkIwVjN1MTBBdEF4YTBGcXdoRHhqUXlVazhGbExXRHRSQkVTOGYtSGl3eHU5ZURtUlZoV3RrNVBjaUdCdWdxZTZqUElRU1MzNmFvYWhtQncycnpaeGlYNHRaS0RXSGpUSHdzRklrQzRHT2paczNsRTFVMTMzbm1pNjBBNE1LaUhlQVJlckNDUGtLVFJDLW9FU3RxcUpKcWRxN1E5LXY30gG-AUFVX3lxTFBZU29sVFNkSTFwSUh6NW9kZkdFZjlUT3VfanhpeDk0TVprRy1uNEExd3plVUFIeVo1N1RuS1hzLUFmMDFWT28xUHpGMTZLazl1MzhXX2w0dTU0OUZ4Mlh4anYzdEpyVVI1dTUxOV9uX2I1N3pHSWpOQUpqTElfS21pYlc0Q0VteU42ckZ6bV9WRktMbHAtRlFtSmR2b3BtSGExNmtza292OWZwTVNZQnk3bC10a096Vkp5eWQxTEE?oc=5
panjang artikel: 2684

Fetch isi artikel:   3%|▎         | 62/2423 [05:57<3:27:54,  5.28s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxQTTdfalBUaG9MTDByaFRUM1MxekFTZ3hSbzJ2TGM4SFVLaWVlb2sySjR6c1JPeXJONDczM1NSMXVZeXpBajkzTHlFMFU3S2lIQ1pGRnoxanFmNXczX0M4OUhqZDVBS0JvU2V1TzFiajJZZmRrTDZ6WS1mRGpOcXRGc0hVVEt6Z1Jna1B0TUZnUmRYZ19qWlpJNlBLZHFYaTNyRmppRnQ4VXh4eEJTQ19lZ1J30gG3AUFVX3lxTE1KUlhxZ0ZQaGVZXzVmNEhRRTJ2YTZ1WTM5SGdKUzhkZ0lsT2xkNnJJV0RRYlFaX1Vrc2MxMDhtU21xSEtoTWppbDNsTE5YQ28zMlY4MHV0VTg4QlcyN0NqVUtidnE2dXRPb3huMVBnTG9PbkU0Z1FVSnVUR09ZWXI4TW1feGFZUThlZ1o3WWgtYWNOOXBvRm5xekJXb0FucGg0RTJJSWxDUWJWZ2FOY1ZMazducnJHdw?oc=5
panjang artikel: 2512

Fetch isi artikel:   3%|▎         | 63/2423 [06:02<3:24:28,  5.20s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxOMzZSUGRYR3B4RUVxZFVBX1RBV0ZjUGpBX3Y5TGgweml0UnI4V19JcDZVRm1pN2dRcTF0NnFzZXlUYlAzcVhUeGpzY0RYMGdaTElfZ3kwQmNfYW1YWWtJRklHa2JieEFxem9XQUdFYXRwOWk1Z2R6UjRqVHhKblM0bFd2T0paZGRCam1CSEFVeWYzMV9yRlFDZkpfM1lkY2ZEQ0RXTWNrQVVVY3QwcF92SExQb1lHNjg1SV9uVkY5VmhKelpFSVhlQk1LbmVldmkt?oc=5
panjang artikel: 5324

Fetch isi artikel:   3%|▎         | 64/2423 [06:07<3:26:33,  5.25s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxQVU5wTUZIcDgxMG5IVkx5VVhUSTFUSkwyNkdWZkdOeTM0TlAzb0JzNmZsamtkcWNzbG13TGY0aVhYazhtbXNXSDRPUFNGYlNsejE1VUlnMWp3YTNxU1QxS3EweXdEU1RjZXotN2N5LVRMUEltYURzX3ZnTTZmZmxsSDVhQy1ZVTVLeWZNWFQ4bmk0RmRwMUdwcGQ4d3c4TUNvQXF5SFVTdlgwaUlFZWVN0gG0AUFVX3lxTE1MVE1NamlVQ1U1Tkg0S2hrT09lZEotSEJWUG5zY3VKSExUMjBfdDlkMmNMQ1NrM20xeUstYXM0SkxKdF81XzgyOEsxZ0xxLWhtb0JNeGZVdnp0Z2I1WmwzQzVJSW00Y2R6YXJPNHB1VWhBcEJYdnVzRkpEY1VvS2xkUF83RktyRHdDT0lhVW1ZdTJBS2kwSE9EZzY3QVpXREpqNGFwRU9VVGlzNmtFUENDOVBwNw?oc=5
panjang artikel: 6592

Fetch isi artikel:   3%|▎         | 65/2423 [06:11<3:17:32,  5.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxPeTFrT0d4N1JrX2lsbmlWaHRlV1BueTJOSk03WFVZZVljQl93SDRZUER2aHUtcC1iTlJsMmp4dnNwMFE5T01kWm0zU3JNMllKUkR1RFlRWmFGaU1tRzFHSUxtVDhHc3p0NUJOdGYxblR4OWtRbFJLVkpKVnFqbDRiX2VEOEU2ZnZqXzZBV3g4V2NFSjViaUxnVmpEZkFxMUpDNWNPUjliVHRXRmY2MjZDUWlSZzZkN3lkbkxKTNIBwgFBVV95cUxOd2xNcENweV9wdDQ4bG1XcHdvQnJSbWRNN3dJM3QwSnQtbHd5MFZfQ2s5QmZ5Tk5naUk2Q3lIMUE2SFd5X2VpYW5lbzZTRHQtd3VHdU96bnE0RHgxamRqcWllamUyWDZYWXdVUGJRQ0N0NDVWWjFYSFl4UU9LRG80OTdUaUwwV1VWYTVGRDBYOGZPSXhJMmNDM29mRzluUkV6UFNCN1R1NFRuaU5XTG1JeGtwMTBycjBUTU9OTmZGS0duUQ?oc=5
panjang artikel: 8472

Fetch isi artikel:   3%|▎         | 66/2423 [06:17<3:22:19,  5.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMiowFBVV95cUxQT1ZodmRXbzk1LUtoS0hBV0d1NXgxT3E4bTl5Z0FwaEdEQzI1SWZaTDlOZk1xaWMwX3h2VWRzcF9xcFJ6NnVvMmZrNGhFazA5TVJCaWRiTEJkRkRfUzdZaVgyWUR1THY1YU1lOXljb3ZEd01DS0tmUFNKN19ScENmWGZQZE4wUnJyNkY2SXJ0empjaVZCdV9pNC03ZzgtNU0xcUR30gGoAUFVX3lxTE12LTVrVnJhQWNCckpYZkVCNFNCQmNtcFI3ODh4TmRwYk1DVWY3SDBtb3pibXBrNVBNeTNBNXlLcGFiU0RjNGNXcWIyLTRqdXZWZDhtLU45NFF2Y1BmbVBKeHhLSmIzZ2xrSVAyMUZpNC1tN2FBU19VeVRINEk2SWxUU0s4eEM0VWhDV1A3dUh2T0J0RHBsTW1oX2hXbWJxQVlDOElzam5wTQ?oc=5
panjang artikel: 4763

Fetch isi artikel:   3%|▎         | 67/2423 [06:22<3:23:34,  5.18s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxOLVBQVnhKeE84ZkJnSmxudGUwVk1xMDZkTEV2OGE1a0l5WW1Gd2JoRVZmLVZ4Z01HdWV1akVGTUxjdXlfUUpscWFITHU1UWwzODVXTWdVM1UwQzJ2T0FURGlvcUdKd1BMMTMxcFVrcUQ3cGZkaGt2YTgxYUw4a3c0N0pTTG51eTBseFJhbDhoWEZzUjktWHNEaU5tRUlSbE9WeWE0ZUV1Ql9La3dHNzlzVDNrMkhxb2vSAbwBQVVfeXFMTlJXUGNwLTgwbEJ5aVBxZVVJNFBpTGpucVJFWlpJaVJUbHUxSk1za2FiOG1jcnhrckJpaXB4QWw3Xy1peW5MWmcwMWI5N3F3OTRhaW8wQVNRbWZvdmIxQnAySFNaWnFlaWRBNjVxM2IzT1BoY08xTUxEN29udFlsZFktZDdhREd0RmtLTDJYS0NUdVpsbVZZQ21GemkwcjBVOGx0MVU3UDNCQmNMdzZKRFJablRPZ3QtR0k2bVg?oc=5
panjang artikel: 6347

Fetch isi artikel:   3%|▎         | 68/2423 [06:26<3:08:30,  4.80s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxOLTN1a3dwbjVYb1g1M0VfWTVKSWF3aXF1YmpFcElDSm10Q0Q3RUlSbVVLd1Axd3ZDeGRobzE0bmZ6WXExbGlTSV9tQVFOYzhJQ3loX081Y1NPb3E3VjRDTEtsRXc2blM5dzBCWWNLcm9TRzNfa1RhMXZNVmp3dnRadVhjdVhhY0tRcGZ5NFYzMzB2cDVIa2hLaE5YR0FlemlLbGJhMTdRaXR5SG9INlp2N9IBtgFBVV95cUxNN3Mtamd4d2tnWVJKbHJ4VVhuOGlWaWpTWUxKb0JsUDlrNjJYUnBoVXpfeHRhRWtyMVhDTnMxY3hlSzZHSG92MF9YSXJZMnZzZjlDZmxLQTZ4bjlZZnY5cUxPLTRzWjRDTHBxVUpEWEp0dGIwbTNUQnFvMF9TQkQtQ2hPMFpIUG1GSmFIQU5oamdSQThsVDFnbkx3amQ3VG52WVd0N01rQWJGYUg0S05KT29FUEp3Zw?oc=5
panjang artikel: 2941

Fetch isi artikel:   3%|▎         | 69/2423 [06:30<3:01:06,  4.62s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1AFBVV95cUxOTERjem1XOHFjNk9QQmZzd2kxSzNXTlBpbmV0SzBLblhBUTdacVp1WWpzdlM4Z0dtRTBtaHFyazFsaUxFOGtGZ3VPZ1dqTEdCYl9lRWs5Z0d0RlFPdVJfaS1Db1ZtNEE0NllpLVRyV0FTX3ZFY2pHdTJCV2lZWXlYbkZsNWw5ckNhV3FaMlFxVEZDaHV2Wm1OMkpJVGZidVNqcVE3WGVLTEQ3T3J6aHBoNzJYNVlxSHlNdmpJOTR1aFI2Tll0NW8tbUlzbjRTc04xQ2h4Mw?oc=5
panjang artikel: 176

Fetch isi artikel:   3%|▎         | 70/2423 [06:35<3:03:26,  4.68s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxNejRoNDBHUXluSFY3VHlYTXpKQ2Q4U3VKbkRTUVUyQ2E0UERiRDhRVXlOdC1jMk5FUU1TV2hybGNFa2FMd0h0aVZRNTJXTVk2NEtxOW9tRkNsQy04VVF5SlhSeUtRVmlhYVBLeU1ab3A5eGc4WGx0SVNGdmlGVjc3S19Dd1Z0cDdhSmNPZVNZdTJDLVlVUkE2X0Y3cEVrSmpCVWZBYzB2NU9NT25jVG0tME50ZWXSAboBQVVfeXFMTmFIRkV5V0VNLXJWUzB6R1J4Q2RNaVdrazIxWktuaHBKM0JvUV8yNXdXS3c0Skp4dktfMnRiM0pfUWdmVFdPMFNFMF9hZ2oxeVFfSHRqQ0hKZklhSURBeG14NXloMUhTTWxYTmtnR0poV0Q2OVN1UWV0aFVYWDVtNGRxT3lNTkNKWWFjRmxCaE81bDR2bF9CTjJ3WFN1cEhSWkhnWTdHWW41ZHJtRmV6dzdmbjVJSlNjNXZR?oc=5
panjang artikel: 2611

Fetch isi artikel:   3%|▎         | 71/2423 [06:40<3:02:48,  4.66s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxPZjcyTlNtQXJjS1lFTGRPRi14c0VpSjFKRWYzR3FEYXlVaDdodk1FeUFXTnB2czFyUFhqSUQxSkozTEdKUkZzMmxoVVdGb2J1bmFFSnU1NE9RbjFKbWhmNTBtMWk4VV94VzZjdHY1QUhVczRqUDZqNWFnRWJFOW9tcVU4bHVleGlrYlVzU0pWRWlyVC1pYkM0cXVpenpUYkhVbW12MVB5MHRLNS1oclA3bFBRY19ib2dr0gG-AUFVX3lxTE05U1J3VVlzVGRIY2FQS2VxRnpPTUxQbFkxNEpVZGFqdTZ6eFlJclVOVVVTZHJ2VVZROVhRelZzS0IwaFZ4TGYtd0dDLTVsLXhERHhpMTlwVktsckxwdWFHZG9YdEZySmZ4YjQyUEJSQWRZYjFnZkpaX2pHZFRQdGQ5U1NDWmRlT0VyekEtOEEwaGRlNmc0U1E1bmlFeXF6djJuNW9kWWVCWnNjN1pXUjRhXzVxbk5YOWhlY3AxeGc?oc=5
panjang artikel: 2500

Fetch isi artikel:   3%|▎         | 72/2423 [06:44<3:00:15,  4.60s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxOQ3lVa2VkUE15Y2twOWVxZGZFZnFISF90Y2Q2d19sNUxPU1Ytek1qOWNaNGNYRy1WVlVYVmRhbWxadmNoVHBBeUlJZlNiNjUzT0hJWHNvSHFUeEtBUjViVjE4TlVhWnptamI0eWw4czdjWV9hME14S0cwREdTNXNYeW8wMk1sZTlxS2ctVE4yY2xORmlieDNZRkNUMWNGbjJzaWl4eVJPSzNYT3RVcm8wYUhQUDZ5M0HSAbwBQVVfeXFMTUlVVlExRDRyMWJsTTJ5SGxORlpVUGZEQ1lCZ2h1NEg4bmtNWFRLbEJqV2wwZEFfT0dSa1p3TjRCYVZZUjFJYTRuMHRMcERqLVQxbV9YOENOUXV4WnJHa1g2OG1SdFNDVHVheEtKMlFwYVJVeUY0NDduY2Nnb01KNy1NVXY4NnZpNTNKMC1Pc3lYVnNGOEZZTmRTOHFXNE1kVmFQWV9Zdk43ZUExeHc3LUNsb1pZcEFCM2c0UEo?oc=5
panjang artikel: 2724

Fetch isi artikel:   3%|▎         | 73/2423 [06:49<3:07:21,  4.78s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxOdmZXc0xjenhCUTZ5dTV0ekJBTGU1YUhzb0IwSW5PeU9ENlVIT19sZXBkUURKSjE3bW52TnAyYmJBSEd4VmFWOG90NDJscV9Jbm1yOEpva1NiRTI0dm4zZTFnaFgyYW9YZGk4dHpYMGtXdHBqWm83cGRNay1vSGw1ZUpvcHdDYjQ1bG5LaHhNWXRCUU9iSlZIWW9Rel8wSkJfZC1fQVlkLXU0RDN6QjdDXzAzeUtBZ9IBuwFBVV95cUxPRVZxZFVuUWlTRktPX3JweGd2WkVHcUZGRC0zWXRlbWtXS0tlVjFETS1uR0s5cDNZQm9xUHNDc3ozS1VTQzVGckpQMXN4NmRHSTlkRW4zclN3cktUeHRLMTRJcmZraUNEd292ODJ1LTdLZm5WdTIyUV9ab1VBQTI3SUpxbnp4bmJKbUZWejJKazdiUkg0MGRDRGRZVzhzSWFWa1pfbDg5d2R2NHcyY2s2X1ZHMFAteU1ZeDRF?oc=5
panjang artikel: 164

Fetch isi artikel:   3%|▎         | 74/2423 [06:54<3:11:10,  4.88s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxOdV8ycG1sbDh3alJhUzZUUkFJLXpTWE82YnIzc1M0dXY5ajlvOHRRV2VLazVkUXFXV1cySVBrX0hodHRWZlNXaDRibGZzangyS21VVEhHU0ZWMHdWN0dWM0lrNGEtSWdvOUxuSGFWY0dMYVF5VnVydFBKY18zZ0hDYWI5ZDlMeWt0VmF0ZThrMlE4QXBGclFucUs0cTljR3BDa3BIanY1NTRCR2PSAbABQVVfeXFMTzl0VUtJZnFtSTRYdW8wbWllOEJzMFhDbHJCU2J6NldQa2dqSHNZTUpwSmdtWkIzQl9hT0FLbFMyMWN1bGxzWWJyUkszT0dPNWlSbHdCSERZNTVvUWk4eHNfYlRRYjNtM1E5bjYzOWNTMzl1N0R0NjJfZlNVSWhtOFBkaW83U3dzS0RmT2dxOHJwZm5VOXM1aWFUYVd2QV9HVXRQSnBlY0dlbnVUbmhtMHc?oc=5
panjang artikel: 2528

Fetch isi artikel:   3%|▎         | 75/2423 [06:59<3:09:31,  4.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxOVHg2dEpJZllUQmtIQmduUnZjam5UNmpYYndjSGZnbDZ2ZGgzckJybzgzemlnNWROeXV5MmQ5RGx1aXh1ampuQmVrWUdrTV9NWTdBU0dJXzFiSzRmT0dnT0NtWHZJSzBMekZqZ2xXNkxVaVRZclF0Zkp5ZXZCNzRILWJsdXF6TGRKT2QxdDZ1WlpCTThjSjlWaS1LSUtzMklqWC1uS2dGS1JZUQ?oc=5
panjang artikel: 1249

Fetch isi artikel:   3%|▎         | 76/2423 [07:04<3:05:10,  4.73s/it]

Fetching link: https://news.google.com/rss/articles/CBMikwFBVV95cUxNeHJsa0xwQ1I4ZVUxeE9SdFNLSzFPajVRYmlFQW1RQWc5NXotZlNrU29BR2ZuT19uc0k3M3pRam9YbFp3dm9DaURWN0ZPV0hfc0ROdkxSX3lWc3Z4U1cybDlTdjY2cXd4ZUFCVVJCTkp5ejNiR3Uyb2tiWk1sWGhwUEdYY093NDJzdVc3V0V6SGRVM28?oc=5
panjang artikel: 653

Fetch isi artikel:   3%|▎         | 77/2423 [07:09<3:17:22,  5.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxQOUpGTDBkV21uYmhRNVo2V21nOG9SZjQ3OTJSNUc2UlE5UmRleXFsZlYyc1BqYVg1N1ZDRGc1XzRXS3NSN1RlVmNEYlJUOTQ4RUhPNmJQdjlnRmRDSV83NXREZHFWYWdmeVI1T3NfdHJnZEMzZEEwNDQyYW5HVDdZTEJodDBWb09fVHRxOUhWZE02RktjRENJZkNyNkwwcUdlSC0zMmF5MVkxaEFCTzBYTEtPMFlIT2lVZmdXVtIBwgFBVV95cUxNb0R1SXE4Vi04dnhLanBEWGotWkd2OGFHWUgwbGdlSUZKZ0JQWEl6N0RNZUpsbUpzVnJtdGtLSVRLdlYxTzYxeENBLWJEZFlWM1h1bEhpbVUweXFnQkduOVVjMUh2a2h6MDZpbTB0LU1odU9RZTFjYlNBMlpZcl9oZkZsWTNsY0ZZT0NKX3FMdHpPQW5ZNlZ6MVBoSHNZWEhBbldITHoyTG9POUJ2SHlVUlBlRnFBUWtqWFhMc3Y5amZ3Zw?oc=5
panjang artikel: 167

Fetch isi artikel:   3%|▎         | 78/2423 [07:14<3:10:47,  4.88s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxPZ0ZBeUdWa0N2bkNSLTlkLWc4b2s5em1PRUhyakowZ0RhMlM0VEZQZW1QQXhQRHQ1ZEVCNkxOSUtKNzdvSV9CQkx3enhmVUlpSVRwUTZVV244cTloR3hvbG5mVUwxUm9xMTU5c2E2dE5leGp2Z3pNWU5sRWJlVFRkVUpKV3NqRmdQOTgyUmI5MFdrRTRHdFRtTlNzZGtsU0daZTB1M2ZjVGkwSHFwejluTWhQY9IBuAFBVV95cUxPWTJzU0JwZVZ4RFdMRDNJb3NoamZUU1RfdXVpVTJTcUtxLXZWUXIyZEQ4S0wwRnZPSWcyMVl3NTJvaHBlVjN0dWpkUWhUOXNjM3pzaW5sanU1Y2F1dXZodnVxUGxSMDd3c3hOMEpoUVk4NEtmOTdxMWxOUERCaTA1bGFQMWNpV1RaQkNrZDVjX0VYRUZTYVpLWk9aQ2wyOFItZkZScG9ra3VBWlJCTFBETTJhU2FEdUJT?oc=5
panjang artikel: 1408

Fetch isi artikel:   3%|▎         | 79/2423 [07:18<3:01:43,  4.65s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxOUWYzRkVjSlVURzg1MzdOVVc1aWV0WkFRWjNJRFNvLXNzLWFSUm1EZWVfMHUzQWx5Q09jVWZqMkJxbVR2QjE2V2s3aHQ3OWZxT01DSlhLanJTWS0xa1NEUEVtOHNxSjdmUmdTNWptaTg3R2FJcHlTcTREWkZhRzdhYnFWVWhlZzBlVHl1Wl9SSUtJZC1hblU0UUZHWjVKM043RVRwOEM3ckVYVTJOcUx6NHNGQk1BS1h4dTdiRE9iV2haeGVmTzhsbWZOb3hBQQ?oc=5
panjang artikel: 2258

Fetch isi artikel:   3%|▎         | 80/2423 [07:22<2:54:48,  4.48s/it]

Fetching link: https://news.google.com/rss/articles/CBMihgJBVV95cUxOY01NYmxGdUxnTUpOcmcwM2NHLTRQRXh6aFFQcXk4dExrbzBobmZfVndMRnh2a28tckVyck5iY1VVd09IZ1htTTJoWXpXak5aUnhvS3RHOUQ0Q0l2ZmhIakFtYzdMOEZNZXdzelJsb1VIbGRtdG53TlpHV3dyWHRaYnltQXYxem9YeXhYcEtvcnlOX0xoVlVFWWFFZGFydHBPQmZmSFRIbkJ3bWRvSTdYUTRRaU5uNzRZeVJ2b2tmSWdRVlgwc2I4MjNtbW5ISzZPZzZzTTdKNTdQc3JvSUlBT0ZtRWJUY21RSzcxUm5uSVM4Szh1SDg0aUxINFdlQjlsOXJMWkln?oc=5
panjang artikel: 2850

Fetch isi artikel:   3%|▎         | 81/2423 [07:27<2:54:19,  4.47s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxPLXNLVXEyVHFyWDRsNEhfWmZUTExKWDlCb1Flc2tjbDRzallxaUxnSUFhUkNmM1B4MHRkX0ZlSUxsOUVXMUhGenp1WVgyR0M1Y1R0RGVIME9QcncxekZhT284ZllzMEF1R0xWREIyUjk1X3BoRTZwcHAxRnpVVHpFRXJIR0Z6NV9IaHczUUN5ak4yNTN3WkdlV0UySzIzQVJ2ZVNNYm9hSGp4UkVOYzlUSExmWVpnYzVCQlRSbFpn?oc=5
panjang artikel: 1735

Fetch isi artikel:   3%|▎         | 82/2423 [07:33<3:20:15,  5.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0wFBVV95cUxQUkVsU3FFZ3NHV1RNaU1vMXRRMGNTc1laVUducEkzei1LbmZPbG9OTnJiQllSb2ZvUjMyaktMMV9tQkFvQmlSeUowRnpxWkNvb0xnQ3F0SDlOT2tuaUppb05ZSkh1a21faXlENXRqU0ctUExOLVY3dUdvcGxTQk9ScElvOE80ako4bXJTZ1g1TEZHeVo1Ums2eGcwVDNRRkZGN1QyZW9aUDJtRXF4Mk9fRjZKVUlJMnhMZEV2ZXZCMEVsUzhCaTlqeC1pSWphbGlrUTlR?oc=5
panjang artikel: 5770

Fetch isi artikel:   3%|▎         | 83/2423 [07:38<3:20:22,  5.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxOZWNFUFNfRHJrOVZ3SnBlY3ZCLUhmdHp0Qm42WFFka1lPWGRhV0E1UENqOFZyVDhIU25kTTlXNWE4UU9xb3RXNXBDR1JfYXljeEpOZDRGdzBrcFBzQUI4aG5yY0FNMHRDU1VwdTRIb2FsT0NETENzT1RsalRXR1BxS1R1ZW9Nd0p6dFZpYnJoUGxERUVqV1VXNWhacmx0V1g1QlB2S2JDUHBTQXZaYXVvTHVUcjg5elhsdTlJSzFkSjAyMGJYSFE?oc=5
panjang artikel: 2477

Fetch isi artikel:   3%|▎         | 84/2423 [07:43<3:09:23,  4.86s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQSzEyWWpQVGxISXRsdUluUEYtUlp1V0dsMDIySmFQSXl0aVp3M1pKLWxqZ0E0NFNMd2c0S3pLWkZyMWtIa3RJd1Y4TVJCRlFRZUhsZF9rTUlQTW9xWmo1NFVfZjV6NzQ5b0ZHbkFxWHowYXQ5THRvS1hUMnUwSWhhNllRYS1KQ3BzaXF0TW9GU2NsYWp3V056djlSOHh1MEFlaFEwVW4wZGQ5azZLWXp0Q2ZBUGRhbGNOWWc?oc=5
panjang artikel: 1146

Fetch isi artikel:   4%|▎         | 85/2423 [07:47<3:07:03,  4.80s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPbjdkRzNiYWpRMmRIelFfMmdNT2dJUnl0WXBZajY0bHVuQmdSNTFiT3hfN0sxSVBlemVON0NfdGV1MmU4cVBKVmh2TUs2R2FxbTFuVHNxdF9xVGdFVnY0WHhOa1ZRNS1mT09paXNTWndRUDBtcXJ2dThoMGFqa0JtVUVMV3JjNkZqVVhrY2RVUEFESERhYW84amVlNms2YTNVLS1xR1VBWUxDbDJEMUxldzZB0gG3AUFVX3lxTE1XTkd6dGI4TGY2cEt6enphdEF6REpHVW93WWVFR1d3VGFkbVpGMVJ5bUQxX1ZlZGsyRnMwa3ZVdkNrbC0zXzlCTFdNNjVVbzBmaGg2b0tGYWhtUFFWdmZRU01YRmhuTEdpaHdDNFBKb3A5VFhGOHpkVVJBc0RJNkh0OWNuakQyb0xVY2RzSVo1MFA5SVRNb2ZwWGVHM21JQk9vdkFBS21wS1QyMUtZOTdBZnlReTdxaw?oc=5
panjang artikel: 2895

Fetch isi artikel:   4%|▎         | 86/2423 [07:53<3:14:06,  4.98s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0gFBVV95cUxObmR5RlhEcEVqUWg4aE5MaDVSVFVHV2lhUjdzR0VzS1h6UFowVC1BM0RSeDlhWGp5N2ZleXJPeFpUSjM2VkhtZm1McEhZZDZTc1hXeDRrTHJ0UHAtd0FnYWVuS3dROUtMMVJ5Ml9rNHJ0SVdZM2NEZUNrV1g5Ym1GMVRrckZhUFAxSDRodW5OTjgza1JYR1hBaXVVdjU1c2xKSHZVMnFLeDljaE9wNENBTXplQllIZkNRV1lBcU4tYWs4eGtHX0pLaENQVGI4eE5QdWfSAdcBQVVfeXFMTWxQUU9jT0FEbDFITlFrTUluWjZJRVRYUTFZaVpDQzd4dDdnVnNNTERQNTVPMVhNMUFfUWVTaGVHTXpsc19JSExxUEZIc0k4bG9aV1lWSW9jNi04dTl4dS1YZy1YOFVKazIzNEszTktMYWNoNEllZ3NkLXIxUEI5Ujh5X1htTDJuLUNpYkt6LUxkN1dZdkdCUXA4SHJEQ1hJa1Jod19Cem0yeTVKODBvRlhzM2ZrUmNHZS1RNmllMmZnYkdhU2ZxOGh4a0lWVkN5TlhZajZvVWM?oc=5
panjang artikel: 134

Fetch isi artikel:   4%|▎         | 87/2423 [07:57<3:11:30,  4.92s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxQcTVpaHZ2YVdlaWVZREVhSjU1clJaby00R2FFSS10YWdaR2hWMUVFSEh5Y19ubUhRdmpnc21PWUV0aERLTEtEWXZFZktPSFBLMUNiV3JLcUxvZmlhMElBdXhhUGFsaS1DSzcwdlBHWVFaMmV5UktYZUNRQjljZkhFYW1kVUZpZG1fTmQyM1dyWkd6Z3FZcUdUWEFNWlhKSk1nanNDNHZvZUl4UdIBrwFBVV95cUxNTlY5RkFvdWRaMW5lRWZiVG5iSzd2TWl6MkJWV1R0aHhlalNFU3dsNm42cWRuSU1Rc2VBWHVDQVJONlhER25FU05PMHVtQVc2eTd1MWo4TzU5SEY1THQxZXVUX0ZTeTBYekJzbWNmYS1RdTJNOFM2aGh3aV9YLUtFMHRzMVRQOVU2a2pwSGhPUjJXMVpzWU9GS1RBVkNYN1JsNTh3ekJHRmZDQklWY0Nj?oc=5
panjang artikel: 1528

Fetch isi artikel:   4%|▎         | 88/2423 [08:02<3:04:47,  4.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxNVFZCQ21VSmJjQzl2ZzktS3ZtV3pNMXVVVEVXVzN1TEo0bGJab2pJWDJobV8tQTZUSDlLdU15N2ZPYzZwVURPeWlQbHlRRnVnVm0tZTRPX0kwQWdyY3RHS3RkQVdqUWNOY3NRRWZWcVpVNW9qVHhMUjM3d1FEdDRJcXJJM1M3RS02NUlYQUkwdzBMX045azdqRHlwZHMzMTgyMUJncDdvSkk3SnZnQmZhaHNaeG1iRzdKa1hiS1A1d2R6LTBq?oc=5
panjang artikel: 465

Fetch isi artikel:   4%|▎         | 89/2423 [08:07<3:07:11,  4.81s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxNV2dtcVY0b0o0eU5aLUg4OHRtWnU5MjdBUzVlVDkwY2h3M2dJakR5UVA5MDU2djRBRlcwMWdXVV9wYTlJVjJBRU1DX205ZUh4OWxNSmYwRkwxd2NNMEVkNzlCWHBDeV9wOFJwd3N3UDhvYXRHbnFkZ0lCQy1XeVRzUkdlU2RSRktjeVpEbGhkUFBLajEyNkJqRnBpcVh0UTA0XzloNjFoYmY4OFcyTXJkVkZR0gG3AUFVX3lxTE5yMFktaFZGVm1BbUlsZ3BELWh0b2lRM19ORlFadEFVY3EybU9IMlB3YmpnZ25nYlhuOXV1VmhiZWdOSUwtUHBUMUxpWjA4R3Y0ekJyQUFicG1vRnM1UmhBNnRwU21YM3NaUGJjdWZ3U2NZSlNvaFBTbGdma1dsVnBpaHJ1eEJheWdoZjJLc1VOMHhCR2xJYlRtblkwQ2laZklUbkZ4SW5YZG5GOWV3NW1GNWMtbExXcw?oc=5
panjang artikel: 1407

Fetch isi artikel:   4%|▎         | 90/2423 [08:12<3:08:46,  4.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxNMHpYSDBTQ1VpOGs2dXFPUlZjUkFaY2pRQmw0ZXo3RGJmcHg5MmkzOEhOaF9UMmpSVk1YSFEwM3NXdkNlT0ltczh0MGdZR3lyemZITzhJV3VMMXVXRVFoSlZ6bExXMTJ1UUtCQkZoSmhnQTljU0lxWlpfWGFFNHdlVGRGUmtwZ1BvOEp1TmJ1b3dtVnNoc3lmd0RiYkhIZmFGeGRGSUxNbllWVmthRzFQakVWN2fSAboBQVVfeXFMUFZ0TFVmY2V1cng0LVZOUVdrMjh3UTNoUWFlSkx1d2J5TXVxTXpncVgyNFN1Y0I3cTIzXzNWalN6TldqcHVud3ZLU1lEaldUY3NuX19JTmwwMlNHRGJiVUtMNnBwNWlGdW5LV2dxazFtWkdtMEc1RjNYblJ6QXh4czVZRUUxbnNra3BCZHBvdHZGLWJ2Y2l3bG44QkpXaVd6NmFmLTk0R2o5UVllLXA1YXlVZXFhak5tNmd3?oc=5
panjang artikel: 3035

Fetch isi artikel:   4%|▍         | 91/2423 [08:17<3:15:07,  5.02s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxNZGM2VnUzbkVncTlHYU1iYS1uZzF3VWFSZ3BXdEpQSV83S051aFZ6UEU2XzB0UGlpYS1WZWtGU2JXNlBUMi1tUUltTFVXV2VlTW5fc0NFdmY3TjNUNHh6cTJjNGlwanlBOEl6akl6NEJ2X3BtWDdxVnNfSm44UEpDckdkZm41SzVHdkRGUTZaNHEzRzh0SDk2Nm5Nc1ZxLUNKcG9jcEpQcG5xSG_SAbABQVVfeXFMTkdvTE83VWJGOEwwZWxqSGJTYWRYUkg0S2FkREx5WUNvLUl0cDFUdGVZNVQzX1hiaS10OFVmanpRVEVoeXJqUHItRGhVcThGbVQyTElwY1U1emI4VGw1c0Q5ODJiMm5zVEw1T0FBLUowX3dqa3ZWZzNidHBqdlNSQVhSc21rWjNuS1lGYzZPWkF6T3pZQzNSTXRDQk9wTEs3Mm1BSkxtcFNucDNZYllQa2s?oc=5
panjang artikel: 2845

Fetch isi artikel:   4%|▍         | 92/2423 [08:22<3:08:16,  4.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxNM2g5enpURC1BLWFkaFl0aWZnVWtYbWN2QkxrdzF5RXlxYUJYQkMwckZCcDBrbEdwN3lIMXNsM0s4cGMyTFY2VG1TSFdtcnpSc2RDWjBhUG1rTjFnU3gzSkllMEphSUxadmFkc3J0TE9rc3ZLekprUVdpWmtEcjNHbGdDcGEwLWNpTjZsVFlYSkxrNG9fdWtvVEo4WnB4d01Na1htdW43X1hMVERmY1Mw?oc=5
panjang artikel: 446

Fetch isi artikel:   4%|▍         | 93/2423 [08:26<3:01:47,  4.68s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxQV0pGLUNNT29WVFZmaFNTXzdyYkNWWUpqNDlNZDhUelJxV3hxd2tUc0ZGd2l6RW5QM0hZU0xDbjdLZ3g4YXlmdTRGaHZicVNQRTJxRHQ2VXU1dGJ4ZHRiOTJlUkMyYmM1NVV6LW10eVFsX0p3QVRUX2hpQWJCRnBocXlDSGN3eTlPODgzbXJSQ290SVo5WDNSWGJKVmVab1J1STlsUVVGemF0UDjSAbABQVVfeXFMUGJ0am1lVUc0VlQ1QlpJdHoxYllIbTZONjhiaTRxY3k0bXdQQWlBdU90bDhTdHZvWFZWVjR6T3Y1Tk45azVubWswV0h5Q2VQLTRCMGNuTG5GazM5ek1NYzJpZWpwc1lNbFRRWWxQalVUM1A2c3VXZThQTER6aTlVWjdrNG9NVnBCd1ZNV2FUS3JQV3JLZjNLTUpNTG9TMWJCUUhHeGRCcGZBYkpkWW9UbE4?oc=5
panjang artikel: 2022

Fetch isi artikel:   4%|▍         | 94/2423 [08:31<3:01:56,  4.69s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxPaC1tR3JJWFlZNTVaT1N6VlhLUlFSMmtCY19tU0poY1NiVEdvdTdSZGdBYXc4ZjRmYXdVQ0J2TDhSQVI1QkRhb0VQdTI2QnVPdnAwQS1WXzdzUHNYVDQ0TlNSZVJCUFdTQlBGY0RoYnRfaEJHTV9rb0ZMTU5sWVgxTFF2UU1udjJGQlNaOGJ5M2dHNk1fOVpOUU1WMThwbnZYVU1ReHdUYWpscW1OZ0hqeG5ETGZYQ0VqYTNF0gHAAUFVX3lxTE5LdmFwVzhDeGZRa2JkR2pMT1pweU1tVVhwTF94NzVmbVpyU2VHUFUzWXR3dy1IVUprcVRGdTRMMFhpUnF2YS1EeEcwY004UGpNRXVwbEt3RjA1R1hkUFZSV3lDZjlxU0pRNEpZSTl3Vi1Ocy1FY05PRGhvTjBPR19jeFJvREllVW5pQWx6Unhtd01Fb3BLYXVsWWg2bzhLTFZiYTBiR21xTUJJR2ZTQjdSVjVwTUhaVHpWbWNvY0xXdQ?oc=5
panjang artikel: 563

Fetch isi artikel:   4%|▍         | 95/2423 [08:35<2:58:06,  4.59s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2AFBVV95cUxNRWs2YzhKUklWc0J4OC1rTnBJQ2hsY2dUalUzNGJCaG9SMUNyTk9JN3FUTU5GdHRTbncta3ZDa0ctSGRWWjZHUnVza09JeC1PLVZRZ3NnYmhPT1M4R2E2NjFham1jaThyV0NZaFZEY2FZQUVJLUdsT3ByRnFhM0wtNDFKZU9vWV8zc2lybmYyODlJVlhYalc3VzlQZ00zNndmTTRlLXJWcVBqSUIxX3ZYM2tnSHIySE12WXFXREVDNnpBd2N3TVJERmRBZG1DQnd4a1hVMzhTUVbSAdgBQVVfeXFMTUVrNmM4SlJJVnNCeDgta05wSUNobGNnVGpVMzRiQmhvUjFDck5PSTdxVE1ORnR0U253LWt2Q2tHLUhkVlo2R1J1c2tPSXgtTy1WUWdzZ2JoT09TOEdhNjYxYWptY2k4cldDWWhWRGNhWUFFSS1HbE9wckZxYTNMLTQxSmVPb1lfM3Npcm5mMjg5SVZYWGpXN1c5UGdNMzZ3Zk00ZS1yVnFQaklCMV92WDNrZ0hyMkhNdllxV0RFQzZ6QXdjd01SREZkQWRtQ0J3eGtYVTM4U1FW?oc=5
panjang artikel: 2587

Fetch isi artikel:   4%|▍         | 96/2423 [08:40<3:06:05,  4.80s/it]

Fetching link: https://news.google.com/rss/articles/CBMikwFBVV95cUxNeGJqR29NWjdoaGI2cm1ScFFmak1ycDd3VnkwSG1rVzVza1BWZ2loQ2NPcFNhd3JORGUtYUpuLTJNOTBlR0hEV0k0MC1tbW51OUJoeXlhY3dNeUxCaVFfRmIybExoemhPSXNkWWU1WjRNOVI0N3ctQ0ZQekpGUTE2cVNLS2hOQks0SjNEZnRmcEdnLUE?oc=5
panjang artikel: 2573

Fetch isi artikel:   4%|▍         | 97/2423 [08:48<3:37:01,  5.60s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxPTE1KeUltZUNKdTN1VVkzb0s1YVVDX2NFdUFaWXhQWlhrM2NZeHJvQmQwRktNRmRSNkgzWEdGS1NpQXYwZl9pYzN6cmdmR0R0eEVYaFBSeHhVZ01mMkt0cVJtNVFORURJemk5YjNtWmh0RzRSLVFaT25RY284cW5xZ3VINHdIUXBzSXQ5X0Ftc2FPekFnNF9oX0VSTXU1S25KTnkwbjI4MUtkZkRSYXh5UXhvRGt5NTNsSWoxMXN4VldRMGJKRTJVQzFrRmw0dw?oc=5
panjang artikel: 2715

Fetch isi artikel:   4%|▍         | 98/2423 [08:54<3:49:10,  5.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2AFBVV95cUxQeTlhOG5pYXNUc1JFRm1lWWpQT21yZVlGOUNQTmlzWUxZS3l6UENiVndqN2U5dW9LQW9za3pCcGZpVmMycENaODdXazFBTmhxTnQySFJPNWlwbUl1ejRkSjFIMmxIZ0FZRzdNZlE1aTdXVWtyV2ZqR09FMF9XTmxOcnktRWlVVkJVX1lEMDVEbEQyVFR2T1lkVjBseHVkODZoNnpXczRNU0RfX1ZscWdWNU16cHdCT1Z0SlZwYkNEZnFQTUdXRFhXTnc5TWpiSXRwTnIyVEwzSXU?oc=5
panjang artikel: 1960

Fetch isi artikel:   4%|▍         | 99/2423 [08:58<3:22:54,  5.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxQZHJjdnFsNkhHS3JLOW1JY2piT1FPQVVKUVhNYk5iTUI5NzR3VmxITFRuZ1U5YVp4U2twQnpHcDd4M3NyMUQ0X0preEZVWWNrT0Y2NDN1cXdUVndtQWRxNEtzUzBpSjd1RlRIbTVZbElRM1lmdGVOb2Zrem9RVHRWMXJjLXBnNDl3SW92Z1JmWnFVNk44eFNid29CN3JlZ2NhbnA3ajZoUTI4RlRhYVo4RzBzNjlqcWc?oc=5
panjang artikel: 2736

Fetch isi artikel:   4%|▍         | 100/2423 [09:05<3:44:24,  5.80s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxOdFdVMkJjek83RFpiNHZ0RXdYZFMza1FNeFZfaG5OSnNORlZzcktTZ2c4LWt5ZWMxenhFdnBSdkpMWXd0WEw2R0w2QWZPSXRfbno3ZTlCeEJCdjBrN1dlSHVFNkhrTTBNTGRpRWNMVVNsbG0xSE5uWGFmVFpuQmw5NjBDdUNVeXY2NVFYMXNOSUw1NHlzUk4zU0dKRk52N3NKWUhia1pDLU8wbk1iR1ZxNFZ3?oc=5
panjang artikel: 1390

Fetch isi artikel:   4%|▍         | 101/2423 [09:09<3:24:32,  5.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxQLXVjWTRMOGsxMFVTM3R2a0dxa0xHdlJmaGItTjdzQ1NaWnJJd2NQZ0k4NlhkdDJGMnRRWmdlSHJuTk1wbWNmeVR0Vjk0VFNjNl9EUkhiQ3NMS3A2dFdublVwU0g5OEs2NDdScDJTLThMTUhBRnJpX1hybUtCN1piTmNaTTRaLXFJVTNldGprTjkwdmZZeUhDVzdnRmk1ZkdhaE5jcm9HX2ZNdFZTZ1VaYnFydWI3cWNTOGExdVg2WHlOZXdJVnc?oc=5
panjang artikel: 3119

Fetch isi artikel:   4%|▍         | 102/2423 [09:15<3:26:28,  5.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMioAFBVV95cUxQRDlkMDQtRTBubXpIcElHNWRkaUpmMXViRTZ0Ry1xOW05ZTVuTWNuWWpReG5yblNySXE1LTljNDFsSkVReHM5VU83LURfOEd3YnQ3UUljT3hUOE5COFBHeHkxbmJtTVpOa3U2X09kN1pXcXR0YjROTHpkRmFPa25GRjBGekRNUS1aR1FqR0xLV0JRQ2sxWFFDY3JpQlpjOF8y?oc=5
panjang artikel: 7922

Fetch isi artikel:   4%|▍         | 103/2423 [09:18<3:08:34,  4.88s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxOd1dJUjZVZ3UtQjNnQ1R3bFpfWmRDbWZ0MlcyUFBiUURweTFxUTVCaDRCV3FsWWRDN0hlN1ptNlBJcFQxMEVwOWEzVDhfQ0h6QXBaTXdWMUhIZDZPWkIwemRzcGNPUG9Ia3BONl9yc1BoMUIxaUNoN0hqSnhTZFMwd0h2VUUtdlhrUDg4bVVhVkcyLUo4ZnhVMnoweUpXMXUxOVkxMjByTWFDNndqeUtZ?oc=5
panjang artikel: 2025

Fetch isi artikel:   4%|▍         | 104/2423 [09:23<3:06:07,  4.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxNcGhkLVREXzk0V3N5d2daT2R4em1RZGc2eWFaMk5aTTBoS2hPOHlmRnZpZldpRGxOTHo0WVNUZ1l3UVZPRHZOai1SSGczVG9MZFd4SXRkblk0ZzRVdmhXWWJMcmNwWllsN3lHaC1rby1xOWNQVHFvVFBzbkFIZHFwRG5xV2RqYjhaQk1sc254QWV2YUxFNTB6MW53?oc=5
panjang artikel: 1947

Fetch isi artikel:   4%|▍         | 105/2423 [09:28<3:05:51,  4.81s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxNa2JVakNkM3JKclp6RHVLS2VudDhMRHdydEdlUjBEY09GTlMtakZzWTJneXNldklKb0F5cHMtZFk5Y2JnZFRHVVU0UHcxanoxMmREVGViTy11TmJOSzZHMC1YTXVvSUR3dG9iOEZYX3NKZDRLNjlCOWttVDNsSURpRnhmZFdZNGV6OW5YRGdJcFAyT3VnTnVaTDk0R0RkeVlKeFpIYldVTdIBrAFBVV95cUxPaDd5VGRuYVVPOXFTbFQ2Vlk3VWM4TVBUZENSVTBuM25xelJEcGh1OXVrWVpNa0FnRUhRN0tOMkVOZHFWbkQtVlB1V0NhLWs2SHBRWnFidU1KeS1saXVUY0QyQUVIRHNVdzhFOFd3VlhwRXFQNWtFT0U4cEFMM0RINWhvbFZ2M3VuSk5BQ1kxam1XREVqUzdXMUt3dXF0SnU4ajNEUXlaeGJ3TTZN?oc=5
panjang artikel: 3468

Fetch isi artikel:   4%|▍         | 106/2423 [09:33<3:04:02,  4.77s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxObzk3MnR0OFhOQXZfYnd0WlZVZURlMzI0cWZKN3Bnc0RyZ3d1MXpXU0VHZTgyR3JGcFdRMTVzSWo3ZGd6M3MtdEZCODN0STRhZHRubTJxZzJubkRSOVN0elQ3Q0ZvZkdTNHB0YXZUbEswdkZFMjNmQzlWbkZHcnNHczB4X213aENOUUdfWmRXT1IxSFJqSWVRYm9hZEZmMUItb2V1RzgyTGpxVUM5NkJYM1l2MGJkVUZxemZDbEszZEzSAcYBQVVfeXFMTVNoRnF5bGhhRHk1TmtzUzBUQTQydkZFVGZ0UTBQcVB3SUlvVXRzZE5KWTZvQS1wRlhNTUhILURkQXJiTGJGQTBramtoelVDckhaQU1FUWNrMGN1RlhEam03YWEwT2pvQXJ2anVEbllvQ0J2QVpjT3NobENvek02R05nNS0ycmphM0xtSE1EMGstR3MxNGgxdXNiY1ZVQnI5V2V0WGJ4Uk9vSUJHNFNXMjRpLVFHX255ZGRYX2x0d09pWGx6RmR3?oc=5
panjang artikel: 3811

Fetch isi artikel:   4%|▍         | 107/2423 [09:37<3:03:44,  4.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMingFBVV95cUxOUGFUSW8zb3dJcHhtSDBWVHBsV1NqMHFIVGQ3c04yYm9PSE5ad1pacXFWT3hnbWFWb3VlZFVESThGV3puRGpJb3YyWG1TTGJ0dXVGSEpwTVZpNVZEeTg5UFpDZldLNTVOLVpLSlkzX2hQd0JSRHE2VGtrVEpmQjJiRmktLUNnd0Z2V2ZsdzRkOTV6ZjhwWFBCOGtESzM4Z9IBowFBVV95cUxOZ1UzYnBwVDJIR1Fkc19McUhIeEpwQ2tuOXE3bE12c3diV1BXOXY4blg5MnRTamxuY1BDdk1JYWtMVFgzZjJzY3JRLU5jOW1ldGh3TzJyWWlOTFlOVUdMR3oyVjlsdVk1bW1zSUEtVTA4Z2N6emNFRXVOYThueDVVY0xwMXlCbkNOWlFiMkdLR1dobkduUUQwYVVCNkc5X0U3dWVR?oc=5
panjang artikel: 145

Fetch isi artikel:   4%|▍         | 108/2423 [09:42<2:59:48,  4.66s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxOYThSMlRxQ0R4TnVQZVBJTWJCUDZFbF9hWXRyTnFET0RrT1QzRFlqV3RoVE8ybVRKaUF0LVgzVy03X2lnUnJjSUlpOVlNT2R3Y0ZhQXFLT014bWY4NmhRT3BVX0RLdHlVVnV2MTZTWF9MZ2NkeWVGanktbGh4NUdPTXNieVNQdmgyVllNMHNRMm56aDZnLWh4ek5TNHNxanlIM2tyc3Q0SmVPT0U?oc=5
panjang artikel: 725

Fetch isi artikel:   4%|▍         | 109/2423 [09:46<2:49:42,  4.40s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxPVjJDMG4teXdhZU1iRy1HVHpiM0VpVldEV3JCakg1YzZ3SDI3WVFLWnhEclFwV19adENBUVh2SnkxaGNCVXdCekkzQXdYWWZLeFpoTjRXc2pDWnBVYV9mRjhGbWRWeHRfSVoydHdQNDFsckF2c3BiM1ZOdUxjUUMtMV9LN3BXUk1LOEFnc1NXcTgzRVpxMG0xck1xeDYtY0o0YkVXaml6Nmp0RXM4SXM1OXRGLW56QdIBuwFBVV95cUxNUjBVTlVSaC11cWM0MDdLZkhaRDJYM2lrb0JTMXYyTVM1NzNDZWlZRnJLNkhCUDJhWlhOYi01VVhPZzU0WFZDejBZMDVOSUowZk54N29tOG54MUpxTXRZRjEzNjYxVjdpMzRFVkhwYXRaQjJJWFZtVTVOZEExZ0wxOUV3ME9UZXUxM0NWUTNpUkJyb3gyVFc1aHlBd0stSTlxYWJsLUM4bkFzZzNiYXlEc3A5ajJXOW4xdzFF?oc=5
panjang artikel: 4126

Fetch isi artikel:   5%|▍         | 110/2423 [09:50<2:54:53,  4.54s/it]

Fetching link: https://news.google.com/rss/articles/CBMipgFBVV95cUxNd0lyaWdyRnJFVFNqYWNYd1ppbldxdTBmR244TmFTU2JvNldmdFdFV1N5Vzc4c3FGTm1jQkFSc1ZHdHgxS0xoa0IyazN1MHNsMWVLY1N3eVI3ZXdSbEhZRVFZOWJvQzRvT3dWVUZ5NDRWZk1MTWJyQ1pPMExyWTJ4bXJzUTZ4RTIwNFJLZHZYYWtLMzJjU0Z6TE0zWm1fRXhpVVNmX3NB?oc=5
panjang artikel: 2237

Fetch isi artikel:   5%|▍         | 111/2423 [09:55<2:56:20,  4.58s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3AFBVV95cUxNLTRIXzZTeUhPNGNPVkpvX2FoRVJtQ0hZR1VDd0RSQ3RVamc4aWhQc0FnNTdsV0wwM0I5UG5BMFFJbWU2TmFIdEpTdE5wVUdMRHdVS2c4OUd4aTdkaEJEWS1SdkxkS19feUstWkIzMWlhWVdOYWptWHRQV2RNUGxSVXJFNEpaMEw1Vkx0a1ZGS1lfUzdvTkhtbW1FRWRjSlJDdFdGRFEzWW9LaHFLdWpaLXQzb3EteXJfdXI5U0NRdjRFOWlJU3Q0NGFEYVljcDJiSFhKakhfZ055Tk5l0gHMAUFVX3lxTE9oU1QzR08xMkU4N1cxOGpDQndLR0Yxc1JYNjgwbkVVYU13a2t2SFU5dTdncERvdUk5eXk3OTVFWFQyeEMzWnV4dlFpX1UyUHpEZFJWWXlYR0h2UUVCcGlKYzNHX2RQNW1TVC1RZUFOWktkZjVaMnNmYk1oN0ZKR3VrdjIzZUdyOUVtVEYxYjFuT0IwTVUtN3JUUVY3dGZTQ2RpZklkcXQ2Q3kxNE9sMEhYTnJQVFJCenZ3dU9MQmgtdnpKMzZWZEJESUdtVg?oc=5
panjang artikel: 4072

Fetch isi artikel:   5%|▍         | 112/2423 [09:59<2:46:35,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxQNjF5bUVSZ1pJdlBDUlpzZ2p3UTl3YlFsZ09VSDhxTlhsdVFkT2RBOUZCTWdjS2RlT0pFRS1fcHhQOVBPRm1GcWFnLXB4LWNCeU50NkhxVFNEaWl0Y0xGZFA1QnRVYmk4dFZhaF91Nk9JY2phd1ZTdDItMXhsYUphUFhGa3FEWHVldDFENlE4c3JJTTlVbjRWQUcxbGhHUndGS0xRU0VKTXdmYU9ITndLWFNIVTI4RjM4X182TWgtc01tNk0?oc=5
panjang artikel: 4003

Fetch isi artikel:   5%|▍         | 113/2423 [10:02<2:36:52,  4.07s/it]

Fetching link: https://news.google.com/rss/articles/CBMiyAFBVV95cUxQX1VMUEh5cHJaMFVNSjZHRmZvRVpfYXB2QlRHdDdrVkM1b01GRk15RW9vM0ItblJ4M2JLUXJ0QkpNTXR2OXprZ2NHdmRfNXFGTnk2SlRhaU1yTmo0OFRGODBObW9jU2pjeTBUYzZMOEFDaGV5TDYtWWExWkJyQ2hUc3lJQ3N4MWRvZFdBLTg3UGREdlpSaW9oNjV3LVg0OF9keFhESnJBOWxudENybzFmQlVpNUdQdFQzeWxpRndmSVpNSmJ3N1NCadIBzgFBVV95cUxNSVFtOHVtSERja3BmS2xnOFpGY3JMTmVuVDZhZUIzb0dCRzhVNlFfVWF4OEtxbGhqdUtGNy1KQ1d4blhEMFY3ZVh2UGRoMlAyNjluazJOYW83VDlYT21ZX0p4LVc2aG9QODVzS2I1MnF1aWhZa2NBQVloWnFkUmtIcU45QWhQME1fZXJfOHRVNy0wVFJ6bVluZ3Fwb0NEY3FmdlBuSmdpcGVFMUE4amZNSjN0T0drQ2EwZy1WU0RTVTNlQVI0NV84aW5QaTZqQQ?oc=5
panjang artikel: 2141

Fetch isi artikel:   5%|▍         | 114/2423 [10:06<2:38:05,  4.11s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxQSHRGb25ra05abGF4b1NBU1E5MzB6TmI5dDJ5YVhBdjBBN25wUzFNZXJrODNBaVQ0R0Z6V0JuSlVMcW50M1lCMWRXU01BNlNRSU1fdHVlX2lyLVg1ZTJnY3htUmJFd0lvWi1Lb2pfZGQ1djVqRkZwOUtZTEIwaWFuaFk4aXFrQTNDT04zLUYxRWM1X3gySTJoNW82NzFJZlNtcHRwMkFKSGJCY3pL0gGyAUFVX3lxTFBQTm1jRnBranl5Y3F1VkxSaWctcUwyZklGNm1SYXpGRG9rekI1QkFBNzBzT2I1b3Z6WURqN0ljZVgyQVBOVk5xcm9nLUZZLS1CUTNXTXRaZEhWZmRFbmtxYUhsWFp3TFBReWR0bkZVb0FURXc0T01JZkxPckJCX0pfUzBnVUNGWlRObWxINzdEZnh3ZE5veGZES1N5STFkMDRvQmdiaDVpTTJyWUhzN1hKTEE?oc=5
panjang artikel: 4160

Fetch isi artikel:   5%|▍         | 115/2423 [10:11<2:47:06,  4.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1wFBVV95cUxPdGgwdHdOTDlFQlNTQ1NGN0xRWXJxM0lxSDhRUlRKRmRza1Q2ci1aWDZjNUdaclJQLW9CTy0wcG54aEd3MzN0eWctdzJmMDZxOXFLaExHNUI3S0lNNm1jVWxVQ2FpckNmRHhZejd6LWlOSnJtX2JINGh6Q2NndmdVSXlRX01jTnAtUWpHWThuajB2dHdaT183RG84NEp6V0dNOEFYQ0w1YmctV1NwOXByR1dBUzE5YUxfVTlLWF9sVTBROWZJVFFJYjRtTGRlVkpqRTdBMmZ4a9IB1wFBVV95cUxOcU1POUlFV1A3MG16NFVTa3BSTmR5enBTZWJOZ1RnaWlmQ2dDbmdWVlZpOHpYLVBMQ0lTckx5NDd4blpaNm1XZmpjSExjOGcwZUp5dW8xaldFRWNQMHc2bG91dUcxbFpKdEJ2dTJkSVhxb1RwXzdUX2VtT0RPUGlieElxYU9LS2VoaVhwTXNVcFgtNlJXYXdldnUwcElmMUd0M2dXeVpjUHNPQmVDaDJ5Yl9WNTJxelJ6RGthOFVobG9vR1JEWmJxTGpIck5UdzM1Nll2NGVDQQ?oc=5
panjang artikel: 134

Fetch isi artikel:   5%|▍         | 116/2423 [10:15<2:42:05,  4.22s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxOVy1xSWZRTmVPeExRVTFsRGlicU5MZnhtMTBqWmY1R1JET25fUGJ0RWtWNGlrNnc2ckEzOWhlTURrbDJKWkVUeU1hYkRDOG9GWk1LazY1UFB5SnNrdzI4VThtZUZaem9wWlRQS1psR2VfM1g1bUtneXBNd0N5UV9aQVIycm05cGFTcDM2VDd3UVhnRTZEenRxeGRfYjREOXVDa00tWGFqN19rUEN6OHRjTEI5QXFFaVFVLXYyS2JCT2ZuanlvdnIw0gG3AUFVX3lxTE5SajRGSXJGTFNhbFB1Wi0tTTI5cnBzNkxMeUFUaUJBbG55UlZOTnBBWVhWeVNTb2t0Z3pJNTVMOGJuMDlCM3hab3JwMWRrd0RnMEVZSmFZZjU2Rmp1cXJndzBhMWpXbzhwTEZMdlg5bnJSMDJXU3JJUDdkN296aTN5SlJFV2JCT0l1bjZ0eG1WQUFfTkx3T25CdmJVc0RTb3kyX0tpTkZ5UjVKa2RMaG5JTWJUTk1hUQ?oc=5
panjang artikel: 4465

Fetch isi artikel:   5%|▍         | 117/2423 [10:19<2:41:43,  4.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxPdzVTRXRpUGV4Ry1jdGdsUTVVRWFmRUxURjVmWlE3cVlaUF9mNXlPY0d4V1FvcE5OTFoyLVJFSTlPQ0wxZDU4YnFwZ1BxYXBGWnAzNzl2Z0ZUcG5hWWQxY2xFMkFBS1BtQlVuSFVCTnprZjI4UEF4cG9BSzdwNHVhV3NOMXlMR1dEaThjMHRvd2luZGhFc1VXeENQUWNhQlMxM0Q0Yld6ZnRxb184Smdfa1pBTW1fTW1IYS1R0gGrAUFVX3lxTE1lcmstV2hoZlJtU1QwMlcwendUQTI2VTRvejh6dGZ3XzNyX29RVFotWUVkOEVrWHF1QUxPUktJWFRYX2dscGlMeEdIN3RkcXo2RENzdDdFWkV6RlQ0YncyakNTU0NaRVh1dXBLUTFBTU44cHRqUkhHX2wwZ2QyT2JvTkQ2VEduUE9KQ2dyNy03WWwtbXV4VWNXT3BlMmZ4TEx1X2g4Y1U3TlJOTQ?oc=5
panjang artikel: 4620

Fetch isi artikel:   5%|▍         | 118/2423 [10:23<2:38:35,  4.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxNT21JUnkxb1F6TmVRVGF0d0I4X08xcnFaQjk3aFFDRDhDWG5ubnVTNmI0alg3OUozSF9aQUhLYmFUYzItd0xid0JaZGVLMFpUazh3ekNPY1U4YnNJa05XLTc4VndWSnpIaDRBaUt0elNTQ3dQeHZLR0dKQzc3emYxRjRmbVpZMVF1SXA3WHBMc040YmZNaGhwcWZzQ3p4V3FaclhGRkNmZzVKclN3bi1WcFh3RWtpSDFJVHhFeFgtSnA?oc=5
panjang artikel: 5314

Fetch isi artikel:   5%|▍         | 119/2423 [10:27<2:33:56,  4.01s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxNbnh0eGhQNHAzdVVrenZTVElnUkdEV1pDT0Z0MXl2dTdEdXJUc1JSNUdNQmE3V1RvXzF3TnpZay1TbnhZdWYyNFBDOWh4MGNjLWlDa252bkJSRi1qUm9xbkoyYVFkY3JQM1phVzRnaklyVVlrNmpUUU9VTktMYnJibUhtRXFmZjB1enRWN1ZwdUIyUmY3R1RpSlNSdVllSEs1WHM3RDZDWHhjOTBHWURPRmx2OFhpX0p0?oc=5
panjang artikel: 1480

Fetch isi artikel:   5%|▍         | 120/2423 [10:31<2:33:03,  3.99s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxOc3pTVzRBR0c5WV9wZUNGUExMSmxlNzV0Tm5lVXBlSUJJZnZvTXhhOW5lUDBubTdUczl0a1ROdzhuTW1EY0RvNjJVR1g5cmFpV3BsQXlqVnhnQlBMcXd5a0M1YVVpRWt2WE9kb3UzcWZfbU9qQ0ltN3hhemUzYWtMNmo3SXBpRFNxOWJlTGRJRGNaazNGeTBLajZodl9qNXJ3bE5LbXd6SU1RNWZMZWc?oc=5
panjang artikel: 6770

Fetch isi artikel:   5%|▍         | 121/2423 [10:35<2:29:29,  3.90s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxOY0JwejhlUEVMbUcxWE4wb21uMkc0VmRwbFJYZHl3WE9ObF9lUC1hSkxMWHhYMjZBQjR1cTFmdXdUclZKcjBOWS1GdmVLOS1OOHBwN1JDbHhYcklRMnRXWGZjNGpOcDBMRkFwaGdHZ0MtWG9aUHl0TjhEcTRfb0JseG1pS1ZPaEExSml1cHdQcGRkNnhiY0pER1NDcTRZelU3NEtyRlZ6T29ZODFUQjZmSGdpS0MzbWt1MU14UDN6WQ?oc=5
panjang artikel: 1864

Fetch isi artikel:   5%|▌         | 122/2423 [10:42<3:07:39,  4.89s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxPSVA1ZVVPNHE4bWEwSFNfMDExeUFrLWtQdHRRT2lnRHZJTU5Idm9sWDE5OENUSG9GUXktbEZ5cUU4eDFCbG9DRW5jTGRKNnB6VG11a203LVVUNjVKMWluWGVXa1NMTS1IMXRtdzNTNU9qLWhiNlZLM0NOaE5iRjlQZGZ6LVRKckZBNHdFcFRMQ1BockZQcFF3UUJodUMxWk9xYmZYMlZvZ0VTSmgyZkF4dEpqdWs5R3RCVTVLbGxVUDZXY1V4ZlJUTEVvQUd1eXFN?oc=5
panjang artikel: 4400

Fetch isi artikel:   5%|▌         | 123/2423 [10:45<2:49:49,  4.43s/it]

Fetching link: https://news.google.com/rss/articles/CBMikwFBVV95cUxNRXo2Q1pjbXlkXzVYUlEzemgwSkZEZmZUSENrYnZKSm1hdXVfMmhuUDdJQjBKS0pyQWpsVlJScGNjSTVMcEpQckkxSDdiYjlrXzlERUZrM3NPUzhoMEk0OWxkMlJ6VlBmYW01dlFLcVZMVi10NUN5Ulk1RlppQzI2NXNhTDhfVHVUdFRwSGViblUxcVk?oc=5
panjang artikel: 3509

Fetch isi artikel:   5%|▌         | 124/2423 [11:00<4:43:25,  7.40s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxObGxSSTJZWDU1LVpGT2RMdnpWaG5nVkNqRFBQZ2EzcDQtLUlnTlEzYmtQQnEzQTZHSC1ZcWVvRmI4bUJLRDEtWDhPTGFubThtT01UcWxpSXphclRnTXNIQjJLc0NtdXNFTjJmOXpkNVQtaEVRTnZPdHdwRzRBTm1VNERuSnR2ZXVSQTJfOV9HVHdTZFZVTVA1STRwVVNINUZZR1NINFp1WUlXUktpeElV0gG0AUFVX3lxTE44UjhuUk9ZemI1LVpud1B4cE1VcEtld0YwYVl6MUNVQnpKOVRGdkVzSGY2cGV3MklSUEk3THNCR2VRRzdzSE5xTFFCY0VBOVIyMUNWYWNYNFgxOGRURUFST3ZHSTdjTlBFbTQtRVhGLUszcklzQ0paXzdjQVVGRGg5QjZMWDMyUXJTOTZIWGhmWllQWmI3OGJqNEF6WVN1eDFScjVIQ3ZES1NDalo2RGFadEZLTA?oc=5
panjang artikel: 3372

Fetch isi artikel:   5%|▌         | 125/2423 [11:04<4:08:22,  6.48s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxOMklTRHZOVHBCMWVxaGQ4ajJ0MmxOc01jNTlVNV9Icm8tb19lVVVVY0dXME5BZ0Q1Mkg5alp5NnRxYUJ3R0JuMDNQaWt2RWJZOERvdGFPOHMtbUs4bjBOTXl0SjhTRlNIaDJ3VV80SFBtT2VyTU1YeWxEbThYZ0JZY2p1WTlPWXc1TTYzVkwyNTBiN1J4cGZ6VUZfeXhxa1ZQNmRSdXdaS3ZUMERWZk5RajNzY9IBuAFBVV95cUxQbGtYMUFZSE9seXV1OUxmdFFBaDFGQk02TTlnQWxxbzlDWnREak44V19qWHYxNG1yeWxIa2RBNHF6QlpWakpHZ2ZOQkkzbUdOM1VTSGwzX3NCNDIyNjJvdFFOZi11UGQyQjNCX3M3ekxKVEQxVWk1NWF5SThpbHpMSzRKX2UxUzc1T3BTZGJ6UkRzRVUzODZNXzBhWE5XOW9qTndUdmZzSmJCS1NJMUJocEIwWnhrRnlQ?oc=5
panjang artikel: 5967

Fetch isi artikel:   5%|▌         | 126/2423 [11:09<3:51:29,  6.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxPb292RmVJaVVET3dqLUNZV1Y0YWFsbEY5RVlFYjktbmV3Z1hyR09kQUMzM1hTV0F6cHU3dVhJb1hNSFZTVnJmZXVadzJnajZlb1JZUXBQa0Q1QVFDMldMMkFfX1NMaGt3X1dMcjlnZE5DMzlVWC1Rb2VxaU1wS0VrWmdjZUh5c1R6M1ZVdWxlWFFkd1FmNTVoZmNlTGJrc19GTUpzalJEZGtGeGU1bUE?oc=5
panjang artikel: 1234

Fetch isi artikel:   5%|▌         | 127/2423 [11:14<3:41:37,  5.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMiiwFBVV95cUxQYVZUeWN1MmNCanNiWENWXzBacXZ3VHhxTDVzX09PSUZBdk1CbXdvTXdyZkNfbXJoT0YxUE1aZXJFcGh5eVlyTkl5SjRIM09wMjZRZ3lsNndFanItMGdpbjNiM0ZtenhmNm5HdHIyaGVXTmc4RVBwR1lfaUdpZFFLNTNsZkFkZlpoTlRF?oc=5
panjang artikel: 2745

Fetch isi artikel:   5%|▌         | 128/2423 [11:28<5:16:02,  8.26s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3gFBVV95cUxOZ2ZyZWhBMkpOakg2V251UzRCMWZrZHp2X3Bva3hqS191ZzUzdENHSFZKeW1LRE9pSXlsTzBlQUxkOU5GMjFHOFIyYWFxOGRZUG05MzFuN0pIX3lBVjVlek4zczFlQVFFdnQtM3ozXzAtOE05anNCN250M1NSRWFPRTB6UG92TmxkVmRLYnppRDRtYmVoTWtKUWlQU0lmVDNyTnM5aGdCRmhyRXNMNFFmUjJLVUtmcXRLUVViMHJJM24yVW9EYnQ2S0xYUEVyc2tnSkE4OEJocGU2dm9kcUE?oc=5
panjang artikel: 155

Fetch isi artikel:   5%|▌         | 129/2423 [11:32<4:28:07,  7.01s/it]

Fetching link: https://news.google.com/rss/articles/CBMilwFBVV95cUxNSmRQbVQ0ZFZGelhLWDYxQkUtS3UydVdkZXdEVUpZVnI2Qk9CMGhuQ003Z1FOX0Q3amFIMFJaUkNXc1dJanRsREUtUlFkUmVPcEtMS2p1YWlpRC0xZWhRRXFpQmhxTGJxamdkR05iRUhkc2dZdXFiQW5Qb0U4NWhxZDNpMXdsUVphc2FFQm12NFI4RHBxRi1R?oc=5
panjang artikel: 1993

Fetch isi artikel:   5%|▌         | 130/2423 [11:38<4:16:19,  6.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxNMTZEc0tpa25uY1dxdjFWUnpsMVE4OFNSY256UW1Hbmx2djBlSWVNdHBvQW9NTVVCeW4zcm54ek8wZHNHZVpWUVJVMmlyTWRCYjgxc1BWamdHMk0zdjBxS25GRU5QWW5uekYzY2dlMlJ4WVBBQmJ3TWg4VnVzdmF5YXlLSjhycnpJaU4za216MVE4ekphbkd5TlEtdG1BQXhmMHFyVjl0LUpuU2tjdm1sdC1xNGlxUjJwam94U0NB0gHDAUFVX3lxTE9ab190YWFETFg0VUFmWVVjbmlkMmF1YXd3VHI5Qzc5eEQ4VFB4RTh2OGtMYk9FWTFrOGY0WkpxV0xqeDh4c3BRVEhLMWF6RkpEYmo0bkJBSVlWcEFmUlUwdWM1c3VGVG05MUsweDlqcXIxcXFkeFk2THhqQzFRYXR2NDhHUWVMMDFHa05CalRwaHhkNF9KMG4ta1dNcUdrLWFzclRaM3dfYXRIMmZ5NjFtS1FKdkZVbUQ3Vmt4ejFDdDlybw?oc=5
panjang artikel: 2799

Fetch isi artikel:   5%|▌         | 131/2423 [11:42<3:42:29,  5.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMikwFBVV95cUxQSENNUlNMNlZMUTFpUk1PaThZNVBSZWpnd2c2b2NwMWZlOGt1ZXNod0ROY0kwN0l5MjUyamlTRjQyTTZDemlyLUp6enNXRVBSZm5YOWNfUDJGa001ZWFGWGUwWXI3RUVyejBkdEZiek5TWmVSczcxWFg0TFlXSHdjWEdPT3dYQTY0clZIWnV4S0ltaVE?oc=5
panjang artikel: 1654

Fetch isi artikel:   5%|▌         | 132/2423 [11:48<3:45:35,  5.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMi7AFBVV95cUxNcEwzRThna0xoUXNjWE0xQThSQWsxUlJ0M0UtYjZwWE9EQzlhN3dvcnNfYU1mWmJtVTgzNEZBN1k5V3Q1eC1zaEJ5UkV4cmRSc0VOdEk4UnVhenhBOEE5YmpaLTVCMjNEQ21JZDR1QmRIQmdpOE1NOE1uVTQxZFFHbEM0Q2dzZThhQ3ozeWRQTXMyRnk4X0RzLXUtWWd1b09KakQ0ZFV3Y1gxMzBGTVMtZ3pkVHZ1TF9lZ2FBWEl3bUR0ejBhdXhZRVBOSjhQak5yYTFwUFZJVmZsNXltNktGWGNpOTVjTGs1R2FTNtIB8gFBVV95cUxQNkxVZUdORTNJWnVhOXJxbE94SS00QXdJcWo2emZzNjdtbFZyUDFQSWZlOHczcUszNlNNWVZmbVlyb1IyTGRQTlhDM2djYkZIdTMxZXNvUnJycnkxS0RDc1dXRS1Kb2w5eklTYU5yYkJmWU52MzEwQjhoQ0V4VjBfREh5bTQwZUtCMWgxak50Zkk1MjFMVWxUNVBlVEtlMjZLb2xXbFVrWmhiZTQwRUxpaFBfQUhIRlB5R21tcHZoYUIxT0NoUTRFU3FpRjB0NnczRlV6dVhMb0ItazFnUFVlOWNxSnNNb1Q0dEZCVkJic29SZw?oc=5
panjang artikel: 3222

Fetch isi artikel:   5%|▌         | 133/2423 [11:52<3:23:53,  5.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQejRHa1pFak5aZndGMzhELWhlMXFwcVROYURpOG1hdXR4dWxhdVNMRjRjNVR0U1BHNW52WnNsVWNrZS1EUlh3OFBtdzAzSkdUS2MxclBfczZ1V09XcXN1S3B0M2NKN1c1MFVKM1h0M1I4S29oOFpoekNiSDVJRExJM0I4dnk2ZEFseU83Ui1OTXU1dTB6TFc3QVM5a3NTU0VHYXBSUTFtNzZnSVFUMEtsbkRxV1F3NTFqM1HSAb8BQVVfeXFMT0MwLWIxMDY5eUdHNTEzRUhteDBHaFVtVUE1TGlEeTFQZV9iRUtUNXFnRWV6MzdDU1JVR3daSU10S3NWVW9SUE1tcmlIWGFTN1FPU0UyTlZIN1h2anJwOTAxaURTd3NaSkF5OWRIbDRDS1RRVjh1QndSNHhocDFQMy1nTzlIc09XenZDSUNpdWdaSklacmt6X1VlaVltSEc1Q3N1UVRmM3RhS2x4RmFvcElEcVRjQlpJbGtVZEp5cEE?oc=5
panjang artikel: 1972

Fetch isi artikel:   6%|▌         | 134/2423 [11:56<3:01:11,  4.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxNYU8wV0x6OUtIS2FVUjJhOE9pYzh2Rm1SWVQxTm1MS2QzTDJkeXg4bi1uVGNzM2NfTm1rV3VnbTV3TmtFLW15alMwY09jTEhpbnZTZl9KOVc4SDZYOG4xNWpPMktyLUx4V0NDenVsYkxkNnk3cW1BZkN3NTRjVlVWU0pMdUZRZk1SWXpwUnpLd1oxMmRIUS1vWjZJUnBiWDJOV1JEZnoxQdIBrAFBVV95cUxOWXdWbkJHTUlfNm1tWFpTMHQtTlp2NTljQWJxYTZxNkR2S3MtRWtNeExrazFveG9LYkExRm1NOWR4MWR6Ynp4QXJTOU1faGl1RWVoaG9hNVQxVFlsaTJvVFNnMDF6QXlPR0RUZU1RektuTUNVa1loMU9QdlUzNDdnVDZBZXM3bU5Dek9GS05XQ2hFcENic1VrUkNwZEtzd0s5OFhiMXE5NVppOFFz?oc=5
panjang artikel: 137

Fetch isi artikel:   6%|▌         | 135/2423 [11:59<2:47:45,  4.40s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxObUN4TDB1OGNQOXVIN0tUYVdlZERRSklTb0JicW1HTzVmSVVaanExc0E4UFRoQzlPMENnZGRhNWJoVFhmUG5rT1BaVmp0NmJuYTQ1SnptTHdNTnMwLXFoOHZTbzdTekNNendkeEROVm9uQTlYR1MyYnllRDl2M0xzOUNNak5sd0JkelpVVjJ4bFk4MnRDTVQ5aGVFZ3RBb3FFbUVpYUtzRGR0NVd0dW1NdU96OUgwME5L?oc=5
panjang artikel: 2658

Fetch isi artikel:   6%|▌         | 136/2423 [12:03<2:46:21,  4.36s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxNTGJybV9FTi1GLUZ1dldBaTRNbklSMFlEYVFLYUFSUWpnOFNHekhVV3c3ZjBNeDNtN3JnWXNXYXc1WlBzVGVjUFpudVBXQzZpSnVzbzhVOEJEZnN1SHdvOUFoYm9KWlRDRFNyWlg4Z2lyemM2ckJMODNyVlU3WFZQX2NVRUNkYVNMb19EOHEtOHlqbmxUQ3VaQ1RXU2Z1RXU5bUxqRkgwOVptR3k2aHBzZVNQdW1iR2RaZlE?oc=5
panjang artikel: 4388

Fetch isi artikel:   6%|▌         | 137/2423 [12:07<2:37:17,  4.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxPVEowSHYtVmhnQmgtaEE5VmVoWXlZanItWXdudWd1Y05VZzdwMk5GYkRrbk1FNnRZQm0zRHQzcnlYOGRkR1RNazVJQmV4MGxETXhhYmR2dkhkVndIZWJLeFYwaTdDSUNuNmlQSGdpZmhmNlRIaC05VkhnRGV6ZjZ3emRvUkhObzR5Y3pNZVRTMVE3bXZtb24wUm5vSmtvbnplQm13Q2J5TWczMXdqY01KYk5ZYTRocEF1c0wyb2Y1QkE?oc=5
panjang artikel: 628

Fetch isi artikel:   6%|▌         | 138/2423 [12:10<2:27:22,  3.87s/it]

Fetching link: https://news.google.com/rss/articles/CBMi4AFBVV95cUxORDd4VlBKV3hkWUJycHFJRG9nanRwWVI0UDdGWi1CQUJtRjFZQzJXdENnTk95VXY5YzNPV2NoRHoyaTlyR0VmYndaUTZMbHE5VUU4RHJ5Z0Npa1hCc2FodTlPUzQ0ampZU2tTZVFoTm5UUkp3c2JCcGNxYzJHZlBMMFdDdTFqVlR0QWY3YkhCM1JQOXZoOFhTMHIycDNFX1pENWhKbmQ1UlQ4SndNRThLWVBQa08xWkVfZFhTSk5KUUotSXcxWEJSdXRQMEJDS3lNNDN1eDREbm5FMzdRejUweA?oc=5
panjang artikel: 1825

Fetch isi artikel:   6%|▌         | 139/2423 [12:14<2:23:48,  3.78s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxQal9IRnJjOHN4LXZCNmZMSDBGam9ja2NjLVgxY2F6R2Ezc3RTR0Nkcl9XanMwalBTUllUWE0zY1ZReWhlR3BDY1R0bVU3MEhzWHVjUHNIRDBSMldsVmJySUZlNVBia1g0Ry10ckJIcF83N0ttYy12RU1tOUZhVHJ4bkxBMEF0RU0yeWVmSTFNSWFzelotaTRzdkVUNmFQSkpWa3fSAacBQVVfeXFMTllZSHFacUZEcEdIc2ZjVFdIcGllNkNUc0ZEX3RCdVZ5OXNfRnhiMjFybmI5cm5PakRYa01sZkVSNE1tS2RUa3JCM3BrUXhVYndpcXRWZW5YQk1KMlc1V3h3Tl9lSUZlNVZXWDFidjRfMzA1YlRQNFdYV0pQWE1nRXAxbm94OUhwWEpSTHpKaHM0S1lESERIa2JzT0NwVWY2cllzMlBaSHc?oc=5
panjang artikel: 145

Fetch isi artikel:   6%|▌         | 140/2423 [12:18<2:32:00,  4.00s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPSDlpa2JTZl9YWExGMXh5dC03UnFVWU0wZ3BWUHNWZUhrQjVlcFNfazlpTzZDb0Q3dFdmSUR0SU04eFJNRjZBSDV4YTdIQTBRME05aDJmcHJhNEVhUzZ0S1lZSnRKMng1YU5vUHlKZndzOGVmZ3hSbmVEN2ZBdE5xWEhCcE90djFuak5kbHNPTDBfWDZ1WjRfUVhpVUJmU2t2X1Z6N0JIV0ZRUEZzeG5uaXBn?oc=5
panjang artikel: 2586

Fetch isi artikel:   6%|▌         | 141/2423 [12:23<2:33:34,  4.04s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3AFBVV95cUxPdDFkZV9QNWNlZDBWTHhjb2FTcVFrR2JoRkUydHZtdjR2amYxZ3lMdG9UV3F2ckFBb0ZKRThaQWZNdEdaYm5McXpPVS1keEhabUNIaGYwQWFlTjZpaTA4YzMwQzJZNVJhWnFOTmJmenBxUUR4VldncVl2U0wybFV4UHZqZC1oSVNOLTNpOFVCRk1GUm5ONkRocHRLbURZdFR3YXp3QXFVdTVSa2NaU0tVNDRDNWtoQnVyY0RpWE9JeHlPN2owRXYwZDhFdVQ0NTFMSWpIRkc1eERBWFlG?oc=5
panjang artikel: 0

Fetch isi artikel:   6%|▌         | 142/2423 [12:27<2:36:01,  4.10s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxPVk9vcDgySktxTFpibDh2Y3BzeWNjak5XeVJmdDFpQ2F4c3Z0UjRrMkZOSS13NGdyU3dBZHpRaWxZV29mR1pReVRTeXZiUUw5S0dDUkFvdC1yU0kyU3dGWmZNdDhzaUpNcjlXaWd0SDRPWkY0OHEyTTNNN1FCX1ZPUHNVQWdLQ2R0a3h2TVI0U0V4NC1xNFEzdjlNczBtRjdsQnhEUlJDNWYyUdIBrwFBVV95cUxPWmt4UUljZHVNRHhEX1FERWtJeUR2VzgyQ29LeUZqbEpiWlRrcTBjNFltcEQ3dFJRcG82cE1MYlVRUENsMThyRWwwdzF2bkNaTXdLMUJocFg0WUdGQ01GWHcxb2pteFFQRHdXUjRpRnpTRjJIaVlOLTQtTmNKOEt3WFJWdmlSeU9KOUhlcU5vekd5amFuanFGX3phbVA3LU05MEYzYmgxdzhLNTM0c21F?oc=5
panjang artikel: 6977

Fetch isi artikel:   6%|▌         | 143/2423 [12:31<2:37:22,  4.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMidEFVX3lxTE5ZUFZJS0VkbWV2anNTYWVUdl9sMThFaVROTHZyZ29rWWRvd3JsczlTZG1VUHVSZnFBOWQtdVBKbU5CYjBaN1ZTanUxVzFyd1pCQWRvb1Zxa2pVWVdxZlpWeGxnWEdWYUw4OVpwU3QtYks5YllE?oc=5
panjang artikel: 8716

Fetch isi artikel:   6%|▌         | 144/2423 [12:35<2:41:07,  4.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxNck5pczBaV3BQX2NENnZkN2RWMlNnSHg5LUJKa3ZZM2c2YVNkNGd3YmxteGE5QnBqRk9OcFh6ZXRvT0ZxZTBkakRYYUhDY1psQUh0RGpTSTIwYTU4b2NabzlpMEpQWVlzNXNYRWdlWWRhalcxVC1Kc1JNM2tGYXlzS2pla3BCX1lna001aXlSa1AyUF9ZckZhQ0xsRkxwYW9QbHM5MlEyZ2s4azJia1liYURISDdYbVRRZmsw0gHAAUFVX3lxTFBydHdxTzI3dnZVQXlqcDZsVjhjNXdTRTZacjllMDRGMUUzUTJZdENyczYwSkNWUlVDNnB0enlLM1htM3RmN0lmQXdnQlZSZFQxb092d0FtcXJvYU5wdXhjNllyRXpNLXZvQVVKdzRNYUZDR1FRU21hdExRZDVuTFB3MWtlYW5Xcml5VG9ldTZMNnk4cV9oTmtMcXh1N1J1M2lrUVJJQ2ppY2xYSWhxR1ZEM2pQTHVWaXpZbE5Db2VtOQ?oc=5
panjang artikel: 2919

Fetch isi artikel:   6%|▌         | 145/2423 [12:40<2:38:45,  4.18s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxNYU15dTIwVWFLVW5fR1o5a2dnc3hGblBEdlJfdkJuX0UtbXVpdG1ENGpPYmZSV0VQSDJJRmsxamtQUkZFZ0tuSlN4TVpIRl9VRkgwLTBsdkRHekkxRjVCWmNST2x2aVRLZ2tFVzBxaVc3NU8xVGN1MmJzU0gzeXc2YkFsYzBobnZpcWRwam5PWWRrZ1JqdnhJY2xqMjdrdnc1WFBqaUYyWEtWbk5rY0hMZWVtWVFlcHc2eEREMDlvdmpSYmdibGRIY09DUHlNQ1BnSWUtYXdGOTNEU2_SAcoBQVVfeXFMT1NLQWVPS25ZeVRKa21xTzFtZFk0YnUxd0tLc1lOUThxLTh1SmF6ZjlJY1BpbTJmYUZpdV84ajRGRGFVNFR6eWhZNXNyamlBVEtmbG1uRElOMXhBRFFmbnRwVHFXZTNHZ3FHSnVBVTNfeHpmVjg2Y0Jjd0VBWE1rMm5OekFIRk5oeFhpYkhwOWhLekw5cERJX2F2eGc1SlZSbndFYkM5dlZqcUdHNkVwSjVTNm91Tm9CYXhBYkNmQUNUYTRVeGhTdTV4Zw?oc=5
panjang artikel: 2648

Fetch isi artikel:   6%|▌         | 146/2423 [12:46<3:00:15,  4.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMiowFBVV95cUxNVGxiWFpVSzhNWllDOGRqVG1XWWg5SDJKN1VodU0wUzE0M0RMcnUxQmw5dmpzVzNXOW9tejB3REJCeEppUktKMzJMS2FRMF83Wjl2SXVmTjRDUE0yRm0tYnZRYUhrX3JPRDMxRnhtS1lNeTR3Mkt1Xzd0WDBSLXcxbUthR0p6UU1HNUJPSmR4UE1zWFFLbnVrR3pCak1EdVNMelQ0?oc=5
panjang artikel: 362

Fetch isi artikel:   6%|▌         | 147/2423 [12:51<3:04:34,  4.87s/it]

Fetching link: https://news.google.com/rss/articles/CBMiVkFVX3lxTE84ZnpWVEJHbjFla1FqNEV2STJ1YkpTclIzd3BLWnFZamUyRl95OHJEZGttTmZMZ0RTS3RiN0NYTTR3NGhkYVBaVU0wT1Q5NjAwb2pIREVR?oc=5
panjang artikel: 7051

Fetch isi artikel:   6%|▌         | 148/2423 [12:56<3:12:13,  5.07s/it]

Fetching link: https://news.google.com/rss/articles/CBMimwFBVV95cUxOaFJhQ2VHVElMV3pucTFvdlZJTU0xdWZ1dUxEcEcyN3NLMTUxcDZkMHhnbUd6NGY5R1NMaUNPdkZMVlJtZWJGSDlnNWNSWm9SY1RDZjQzdkUxRUM5WEpMQVJYaG9LRFZaTWtMVGRwTzQwVDlHLW4wdUswUTFZakgtY1lwMTZmellWOUZOaWM0eUFmYVI2cXNYM0dNOA?oc=5
panjang artikel: 95

Fetch isi artikel:   6%|▌         | 149/2423 [13:01<3:03:22,  4.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxOb01xLWZHc3NTXzVPSTM5SkRDSnp4VF9EMkpENlFaRXlhSjF3NGNNWllrVzVsQUNoR3dDelNfUU5LODljbzVtdEx3aU83eXZJckdmRmJ5YThrc2pfSjd6WVUxTjZaTDlDZEswcy1SS1VMMi1JcjRQSHlicERSQVFVWm12bWZEbFpwcU1leU8xSlFWT3ptcS1FYlJQU2RRYjZTMkNsZzZEdjNKbHVlc3RZ?oc=5
panjang artikel: 2922

Fetch isi artikel:   6%|▌         | 150/2423 [13:06<3:04:26,  4.87s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxQSk9ZajJRNFdtX0szU0FaLXJsMEYzVmp6V1B2d2JoV1JFcFhLeUUzUm94SGlyUlkzNlVMV2h3eWREYzd1bkptRzQ1R0ZnTnFJTjkyOGpNdkdVdXF1MFZLYl96Rkx3U245ME1RRUV1MWs2WUM3UnBkYzFBOW44R1BvQ1JLdkpDVUt4VExsS21jbGdDQ2Yxci1jX3lBVjNWX3AtYzBVdU90RXlPQQ?oc=5
panjang artikel: 3528

Fetch isi artikel:   6%|▌         | 151/2423 [13:12<3:22:18,  5.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxNTzFlNlF3Nkg4Yk9DdndobU1BQVFyR3Q5c3Y2QU42UmJZd3dJZndiT255ekF5UHhCYlJsSUVSNlEwNWFEeXdqOGpfUW96cTVheXBIQ0xXTExMU21oSWhhdE1hbDNCR2FzM2kwREdISjVGemdEVXQyV2Z0S1k0UXJNN3B4bHpyNS02ZFpxSUtmZHByVC1DbDFaOGNBMzJEWjROWFRNUU1OdW1QSHIwWldwRtIBtgFBVV95cUxQVDFSY1ZoQ0QyMldFMUQ3cTVwTGJxeGRvaFA3RG9nQl9aM20tV0xPVFV5aEg2dy1DT2VPcmJhRjViUlMtdUlhUFJONGJnUmItcmdDaEJRZ2piTDBUWTltLUdjaVBwNHN6S2dQdU1BcVd3Ri1WLUpLTWJGQl9XMlJ1S0tLWG1HYjctQ01HckhvTlhxdWtGWUtfTGFobTZQRkFSeEhKVTdwcGRpQ3lfcnpnQjZ5NWpwZw?oc=5
panjang artikel: 2756

Fetch isi artikel:   6%|▋         | 152/2423 [13:16<3:07:07,  4.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMia0FVX3lxTE1vRFpEeUtVMUdYWDBmellXNGtkUVhoZVE4aS00WWRYNDdnY0lCUzRpODNXVDBza0d1YmJFUXZ1SUQ0Wng2TllxVVhhOS1Zbjk4a3o5Qnl2RDJRaThrWTNIbTl1b2ktRlctMXJn?oc=5
panjang artikel: 364

Fetch isi artikel:   6%|▋         | 153/2423 [13:25<3:52:40,  6.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxPUTBuS1FGMUpEb0ZhSjFPZjBSZWZEc1RBSUYtNUdLcHE2aFpqYzdpTDcxcGRmUVN3RzVxTnhxNVp4ZjdXLXh0cUY0VTYxUXBNb0FMZHN1VF9mMktuLWwtX3JicjBXV0FSLXBZaFBYMEE0SjFxWjRsekNxemJKMkFUWG54bl9HSWxmNE40LTRkX2JublJzd05MM0dTZXN3TzFGM0tiNjFHSk1CSXZpc3ZJYmFzNDlsbVdaUlhCY1U2bw?oc=5
panjang artikel: 7131

Fetch isi artikel:   6%|▋         | 154/2423 [13:30<3:40:49,  5.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMiyAFBVV95cUxPd0dJN2o0LUlfMWpSdHBRWUdEV1M0d3N5UVlHdzM2UVF5T0psRUVucjc1amJpckpXQTdxY3dNZHJMYjRkcWE4YVQtODcwWkRMX1dxNktvdGMtNlR3TEhmcThIekJUUzFFWV9Ea1JLWkJFbTFwSUVGd0J5dDhYNlpud0Nkd1Y1NndUQU1BNnpSQ2lJNXZYNDZwTFAtNG9iV0M4eFdsQmVYN3AyRFFVRWViVlUyMzNraUdEc0tjYUhjOWN0RTFwc1o4Y9IBvgFBVV95cUxOeUNPLVZ4dU1FOUcyOTkxdkQ0YV9kSHJvVDBYSUFFbXhrRGM4ampGNzAxbDM0dmV5R3NZbHpnbzJ0S2J6Qjh0cm9VcXhyb1JRMlh4bjdMUDF1NzVEZXRlQVRwWUFCb2xQT0ZCaEljNnlfMzFHb05wQ2FIVHBScWFKeklPV3h5a3Nsc0pTY3p0R2k2aTVwdWk5aDhHaTg0V1RDRXVreDJXVzRQN1NCTm9kWUJtOU9uNGIxbkVxbkxR?oc=5
panjang artikel: 4695

Fetch isi artikel:   6%|▋         | 155/2423 [13:36<3:40:03,  5.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxNMmxPRlFGT09kQS1pSlVSRnpfQ1o2TUI1NGVwTWZ2VWRySWpqMGx2RXU4blYxaVpqbjdsT2dHVVducTd4ZVZfdEJ1TGhua0dMT0RKVmRGWW5JM3BpRjdTZk1VQmJPUW5BME1uNk5laHBrR2xxdGREOVkzSDh2RXhaWjV6cklLMjI2bWRpVmNxcnNuQ05LeDVaeTAzUGpiVm4ydEFad09hSm1yeUw0VmZQOS1oSm1iQ1VjMnc0YWhvSWg?oc=5
panjang artikel: 3489

Fetch isi artikel:   6%|▋         | 156/2423 [13:42<3:43:46,  5.92s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3gFBVV95cUxQandrXzFUTFA1OXRiSGVwNFBmM1ZrOTU3UG4zMDY5ODRDcXlmSHR3MkxubWtxLV92MDJmNndPNnMyMmhPdUM1ZDFmSmI3NkxDZGpCNTl3M1NfbzZzd0NHZjk5cTcwdnBHbVA4MFlmM0dmZFVUZDh2b1dtZzUxSU10SFE1ZlV4QUVTdy1NN05xYVFqRzRpMkNpSy1pQmtZaDBBRFRMd0QweFN3TVQ4OVlnU2VYUUN2d05odnI2R3llLWZGX2lQbHlNbG1CS2xmR0Q1VWphQXUxMEMzSWRta3fSAeMBQVVfeXFMTTRfdk9fYnlibHFWdGdVTDU5ZGI4QlVsdlN6X1daQ19HbTZqRnpkUVBxVXpKaG1ES0RhN0RsakxYS2hXTmRINFp2UGRXMHAwZWliTy0wd09hN0llZjQwUnJPTTlGTTRycDRYQWxKYnlZN05QVTY3Y2F6Z0pMTzBYaFcwWEVZTWdvb21kRUUwZVJxOUtrLWVGVEtpREtCaTJDdExEdlRheUIyRDlPV0F4Tm9XMHk4dkdGSHE5QXN4a2thazdtZlFXcDRJNXIzMGlEN0hZaE1PejV2WWt4eTJwODg2NUE?oc=5
panjang artikel: 206

Fetch isi artikel:   6%|▋         | 157/2423 [13:48<3:49:05,  6.07s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxPSmVYYVdfUVM1ZWR5MGJ1eGQwWWl5UVF6SmNKaks1dG0tVGJ4UXQ1R21Xa1lhNzU1LVVtbVBZVjlzdWJkRXl2UWJVTjNEVnZNcGdxUmp0aURtZEhoNHRxcDlpVmwwRGotY3YwN3ZDVkRubDlsYVNFNkVTWGpYaldsS2tka0JSMXlrVEFJMWphTjlnUnY3UXdVT2F5TWp5YlhMaTgwbUItM3A0QQ?oc=5
panjang artikel: 2902

Fetch isi artikel:   7%|▋         | 158/2423 [13:53<3:37:33,  5.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxOdVNSWHgwQXBLOGUzbUQxa2ZKdTFtVU1MNlo0VmFzajZpUGtZTHlYTnVBOXNiZlcxMGdyUEFLczN2d1c3R2hwVkIxd1JwZ24zYzE1Vk5mVS1kSEtDdUw4X3BvTm1seHNoYVRCcnJnMHg2ZnFHQXVCc1hjc1ZwY1JENlpuNU0wWEFBLVdCaTVlRWhBNHNaWnlhSlJJNHhGemppZkNNWjJST1lRSlV2VkVZ?oc=5
panjang artikel: 950

Fetch isi artikel:   7%|▋         | 159/2423 [13:58<3:19:05,  5.28s/it]

Fetching link: https://news.google.com/rss/articles/CBMiigFBVV95cUxNRlpqOUFWNDIwZG1lSE5nbENPc2tuX1pSNGFYLUFBS1k3OG03ZjZoY1VHcHZxQjRGa2lNd0lBN3QyWmJTXzRpeWZ1M0U2S3ZwSVEyM0ZZZGNnbmJLN3JzN1E4RC15UU9NeWVrQ196ekU2Y3ZjUzBjeHJDUGFsa0R3aFJ2bTBxUUxqVFHSAY8BQVVfeXFMUHRMd1Nwd3dDRUxtMnl2ZXBhMWdWNExDblB3MlptbWtLa0w2d0FLVnR6OW5haFI2TzdLZklkTFNSbjAwVUVCR1NCVU1rdGkzeHJvVlBtWlp1cEhFYTZoQU5FU2x0X3ZyUGJqRXJtamU5OUNOQmtYNDhncnlmU2syWFROYjlyemtmMXNUTW04VG8?oc=5
panjang artikel: 371

Fetch isi artikel:   7%|▋         | 160/2423 [14:02<3:06:16,  4.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxNcHhhZzNlbVlYSGowdXlabUdtYXpVYmtQNkpGaHpRRmpvMkRsdVV3Y2g4VmFMXzAxSFhRUmZLc0JUM0owMDlRR2FpUk93Y0MtcWtYSUN2MFhYdkpJVlpQRlRsNy1CUHQ0TVo5RlZzdExCQWRSMkJBNmM0NlJCeS1kMlhNMUZ2dnh1bzhyUldQcDZ1cVBKbkh5b0ZCTmhwMkZDeXpFNlBJaGJuOWNUaGUyTFlR?oc=5
panjang artikel: 2022

Fetch isi artikel:   7%|▋         | 161/2423 [14:06<2:59:35,  4.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1AFBVV95cUxNRHpzQ1M1SzBZdENuRkZhS2hWNUhtUmV0c2lUZEdoVDdvQjVNSGdFWVdaYVUxV3p6UjdzRVgwUEQ0OERDb3FfNmU0MXoyNnhrTFpIREo0WVRCMTlHcWg3cGo3WGZhRWdjblYxckpFc2ZNajc1M3NiRzgtV0JhUDUxbFZaOGotUlhkWF9OQzcxZk4xTzB1SjU4VDlSdHRWSFJPNFpWVC0wSjdzeWNvYnE2RHAyR2l1SkN6YXF6Mk9EY2syZ2ZZMzNISkR2ekU5UWhHNVpPSw?oc=5
panjang artikel: 1789

Fetch isi artikel:   7%|▋         | 162/2423 [14:11<2:57:57,  4.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMi4AFBVV95cUxNbUFPVXBTRkRkY0FKRmhLczRQZlZkUlp5TnNpWDhYa3lJYVNkVC16bDhuR0djV1ZqOGRNUnRyV2FqN1RLOUNIZHRIOW15QV9fb1ZpX2E0ZVhGNy1HTWNGaV9qSnExcFRITllwREgwRU40bjVMdDJjbDVjRzgzLUhOQ2tNeFZzNEVQMXo5YzVsbW5fcEhIUzRGc25zUWQwbkhMZVJ5aFJ3RFBjU0t3Smc2Q2F4M2YzVGZHM3JDaHo1YWdjUzdoUTZMTzgwRE9vNGZwbW16MGYzbjRYNHdyTjJfUNIB3wFBVV95cUxNMnozUl9MYVRQV0FLckFENzZUdkVnTEJtalRYRGNNamJfbG9OQURmWjJ3cVE1bnM4a1l6bThNRVo2WEI2Qkd6blR5Y1VTSG1DODRPV3BPdGFMMUVhM0ZRUm1HMVVFazRaR01vSFVwbUZlR3RvZC14QXNwUW5Od1MweWhSVUdzeG1vVUhzbTFZY0RTY293dDBfbW9GUDB0dm9keFFWQThSNFA0NDZQNWVZTUlXczh5T3ltYm8xV1FnR1A0ZDZmdHNBS3NGRUdGYTZBV1ZYSUgzbWcxVXgycXpZ?oc=5
panjang artikel: 3180

Fetch isi artikel:   7%|▋         | 163/2423 [14:16<3:02:57,  4.86s/it]

Fetching link: https://news.google.com/rss/articles/CBMihgFBVV95cUxOYkRFeHIwRHhKZXlzYjNOcEJIS0lRYW9EZVFydXJlNDl5SzRoZlM3Z3dSeFdYb0tEOTVOUWlxOE4wTWFXSFFYd3BKOXE2cHpSSnJVZW1xekpRaGFGUWRCZFRHWlRHazVJSDBUSFBxYXF4NndFQ3JETEJzYmxpRmVQb210aXQ0Zw?oc=5
panjang artikel: 4346

Fetch isi artikel:   7%|▋         | 164/2423 [14:21<3:00:21,  4.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxNaS1RVWEtOW90X19Xd1RVM3B5Wk51WE1NVXVPb3B1NXBDTERleWhWNHl0d01La1NYVWFsY0JULVlpYWE1Q0ZJSGlOLUJpRnlYNGU3Xy1xT2JiVDhhT3U5SF9QZzVWbDhuR2FWNDVrUllBX1BQcm80WkhOWm9rSE9TamQ5aVR5dXVsU0JSMzZHR3J5Y281TFZkVXlhOHgtM3VPbHJGbFA0ZHF5aml5dXBOYmpMeVhjUdIBuwFBVV95cUxQYWljd3locE0tZG1nOXZkRUZoT2QyQ19mUnpTUlVUR25MZXg0VExtWmZ5TEtXV21HRDJqdnE5U3ZtT2FtdTB0RVZ3TGhDZ3NOZXpEdnFsT0dxRmVHeFRQQUxmT0lIM3MtWi1nSDZ5QmwxVGF0bTVhZWc0Yi1hM2ZCZHhsQ3lSLU9VM0ZHTUN1T2g2emtBNzRGM0NiSDNTekx4TmRaU2UtZmxXc0xHYWNLbEtWNERVNWJQVDk4?oc=5
panjang artikel: 958

Fetch isi artikel:   7%|▋         | 165/2423 [14:26<3:07:03,  4.97s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxOdS0wTVlDczFtdzBDOHdiVHI2NlpabndNdVVZWDA3Sm44b2I1Z0NpTWc2anYyS1E4VjhjRjNteG9nMkQwbENHY0lodjJMeWRjaENnNjczaU9YbG4wQVdNOGhnY1B3RXIydFNuMXpfS3pOTDVuNEJDZUlabzBqNGM4czNpa1dyVHdnM3JEaGVTYldQT2hGLTZIWXNiVXZxU2hmRkNGamNmYVVMSjVNZWV1Q2RwWE1wS29pNkRWd3FlN1RGLUwxRTNJ?oc=5
panjang artikel: 5254

Fetch isi artikel:   7%|▋         | 166/2423 [14:31<3:03:59,  4.89s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxQa0hRWHFRd0J6VDhCenhXemhtSUJRQVdUaHMxYURwN0xTOEVKb0dOeXZMOUxmRU9sbnl5TzZhVTFOZlFUcGZ5M1BjbXUxM2FIYk9mVEowMWM5Vzd6MXByNE1weV8yT05XSDhLdHd0b002TExMSkM2M3l0YklnbVUxUkZCMVBydmNMdnJ0X2l3ZVE3ZFhVYUJMd2NkdFlBeDhFOVlIcnprc2tSb092SWNCMjN3eGMyM1HSAbwBQVVfeXFMTzNNbXpiUWo2N19xYjBQbkc1MzJGbzYwd25Pd1F5Sm5MUzBHcHh0Z0pFNWR6Y2FBMm9RSXdHR091VlJqdnJSZ0oxUlc1ekJ6XzN4U21EVTloU2VySmxpSl9qaDZRdVltNVQ0ZkhrU2kyQ21HZldJemJuS0FXOU8wZGEzbklQYnRMRnNKUkdMdk5ERkp2bGpaTVJNa2tJRjlSZzcyWXo1NTN5SmNfNURUUzZ1TnRlVDM3M2p3MXk?oc=5
panjang artikel: 2596

Fetch isi artikel:   7%|▋         | 167/2423 [14:36<3:11:17,  5.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQNmtkQXctMm44RlZvWm9mSkhrb2c5ZS1UMFA0ZWc5U3lua0VDQzJuUWhqM3M4eGNTblV0eVVzaHowendENjQyUVJZWFdfeUp0dkx5VHhTVkM1VWFDcGhPZEU4ZU5ZVW9mVjl5bWloenB4N1J6ODFrMDJkRmJvWE1tYnRIUFhDeG9iNW9kNmtoaTdISFdkZWRJcm53aktOTFZMYUFCOTh1TVpnbF9OZWh4bTJRek50TFVyR2c?oc=5
panjang artikel: 2245

Fetch isi artikel:   7%|▋         | 168/2423 [14:40<3:00:14,  4.80s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxOaGJkYXZVWGJvelR5ODNrbEVpb0czbm9rQ1BobHlKY2gwU2E4ZHhCOGNtemt4eWNDY2tkRkh5YmdmM0hIclBMUEhaUlRndHRtMk53R0hTNi1aUDNDZ0RySU56ZDRZWlF1M290S09hTFMzM3l2azkxWmkzb2R3ZlhJNUdjaUVaNk81OVNFY0thV0R6YzZqM3NELXR3MTNzSmZoSHZiNTFobW5obEFIM0pFN2FPMVduTG9weEZQa0NPR1lYOThJ?oc=5
panjang artikel: 2642

Fetch isi artikel:   7%|▋         | 169/2423 [14:45<3:03:48,  4.89s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxPSGRHTzZKekIyTF9DZEdkSXo4UUZfX19ZTEt1VHBEUnRyRWtaY0lrS0xJNFlTSmVMbHB3TUhaQ2VpdkFBb1dpcl9Ydm1pWTdKcWtaYUxfY2M4ZUp2NnZhRnRiZ1NRVWdTY1NTcUJrdVdUVk5zMGFlVDIxYVdwUWYxMW5PUExfQUdyMGgtd21nbzNiS0VVNGVZQjBrZlpwemN4MmNDNjJjZUZmbDFRVFRLdTh6dVJfNG_SAbwBQVVfeXFMUHZ6ZHAxN3JOdmR5bU1QQkZYV0p6bkF4M2FtNXQ3cFhsZFlIVVh1bGVfQlAxY2hNcEZGQlJBMi1nMG5lZ3pYcnI5ZDFFbzBnd0szNjdiZzdRTWhjTktYWjZpWVRndEhRbVRuSERqdm9abUM0WHM2ZXU3UGJfV1pfQnhsZ3prdU5TdXNQXzNuQTdTOExJVktTTERjX1h1M21nS01mLWxYMkhLdWVGRFZCaURpa05mUjAxLUV4bS0?oc=5
panjang artikel: 4947

Fetch isi artikel:   7%|▋         | 170/2423 [14:50<3:04:35,  4.92s/it]

Fetching link: https://news.google.com/rss/articles/CBMimwFBVV95cUxQLWc1UUYwVENBeTFha1pqQ2RhTW0yTFFienFGR0FaSGRKZEg3VDRqN3NCMVBfeXFOV1NhdHVSbGc3RFR3ODhmMDEyR0o3UkVoa2N5cW0yemhLQ2xpdEYxaDFRSnB4MTFCZG5QZFg0WjZsSDFITXVRRGJjMjBtQ2VaVXllVXdWOW5DRENoWFd2OFhrcmNjczlfaGN0b9IBoAFBVV95cUxOSk9xczRxcDg1MmxqSldWSmduRmUwem9wMHFSUXlvTXpBdERYOThHcGRUQ2doVk11dHBxVWpfYnZEUTdWREdtMXVnTGctTkZWcjc3RkxSeUdkc2dkLU50d3ZVQmMzZnR3V0xwanM1c1NQVHpSNllwdDc0NExMZ3Ezd1N4ZHg5c0RLVU9Vd2xueHBwc3dMVm94X3ZSMTM4V3NG?oc=5
panjang artikel: 2133

Fetch isi artikel:   7%|▋         | 171/2423 [14:55<3:01:14,  4.83s/it]

Fetching link: https://news.google.com/rss/articles/CBMi4gFBVV95cUxNU3M0OXlHZDJvZjlGd3o1Z2lCR1BJcWFhejlmUW80QWU2Y1VpNkI5VUhsc1A4cWVPaDlQWUtkaUFsMlVtWEpYTXc1VEtwZXZiS1I0TGpJVWZGNW45VUtKR0ZtQ2ZYbnZaMjBUZjA3Wk5TT1UweFF5R3F3dHVqc1c5SUdHZ3BfeGx1NkVvRE1TNGxleTVTZ0N5dXItTHJVX0ZNSzBLczRvbVZWcTdLOGExVlYwWEd4aUNHSXBkMVg2dEgyb2t5WXFQX0RwNjVfTmtGTjdSSVlpWEtNV2RWMmVoQjJB?oc=5
panjang artikel: 1945

Fetch isi artikel:   7%|▋         | 172/2423 [15:00<3:00:41,  4.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMiywFBVV95cUxNY09tR3gyaGJ6SDhDUktQaHhyMFVJUV9GRkhvNnpPdjBWSTFEVUw0bzlEWml3TkJfSTQ0b25GWEdocDZSZWlvQ1dYcEt5Q2tFUzU5SmYxcWEwODFJX2lRMkFDN0Q3dXc2SzA5eHVrbTB2bTlUck1SNmYxa05scDBLSWlSYjhTY0s4UEZUeFllbC15U3QwdUxqWHNvNE9HaGlzeXdPbnJIZE1WR3NOTXFkbmFBOHdjb0RCMFlrdTd1Vzluako0dTZpeUJPOA?oc=5
panjang artikel: 1999

Fetch isi artikel:   7%|▋         | 173/2423 [15:05<3:02:36,  4.87s/it]

Fetching link: https://news.google.com/rss/articles/CBMihgFBVV95cUxPX2VBZmdOcDFpRVFOWVVHYmV2WVZXWXhBcEpNb3dJbHF0cVBxRXItZW9BVm1lZkdXMS1fYkJhR0tiMGYwaXNMNzYwV2E0cEFVeXdRUjNyTGVoLUZTYXFYOUtfU29DcVpfTnVsQ3I0VXFjZFZBbHYzT2RlbHVvczVfOFdKUjJYZw?oc=5
panjang artikel: 155

Fetch isi artikel:   7%|▋         | 174/2423 [15:10<3:09:23,  5.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2AFBVV95cUxOdEdUeFdUc1o2R1VHNFNpTFRsdnVuSmRIcTZZMW8tVWIzRWNOQUlsQUJLY2hULXNTNmFOdklKeVBQbEFFdjVYNzBUUWp1RTdDTWZGOTZCS0twdmpPQ0FlSlRVNS1GeURqNUliWEpsaVlGV0ZmWDNWaUY0Q3dsT3dZN0V5ZUpnaHVyV1dabzFEOWlaY2dyb3lmenNCYlRCd1NQeTNxd2Z4LTZRQmVRSTNBdXdUYTIzSkhVQ2ZabHRhQW52Y000UV9hNFdnVndKS2pBMmxvOEJYcmXSAdcBQVVfeXFMUGZzQVFvVUFGRFNSMFhIOU12TElyb25kdUs5SVk1Y2lvMVlqRERpd3Q1d3lfVjJZYk1nbWV1bWczM1pqR2pnTVFPT3d5aTdKT2RnbkxUV1RBSmZFWU5TVTVqSFVMX1g3elVBMWFMTjZ2dk94MkdZdldpa01GaUkyUTBpNFotNC1JX1NibWdrVU83MUhScjNkM3ljSUxjZ3JIRGZkdkRVR2F5WlVna19CNFdyVGUxcmZGS2N3RThFeUJkc0locGo5eTFkSUQ3YkdobmdEdU5yTVU?oc=5
panjang artikel: 1527

Fetch isi artikel:   7%|▋         | 175/2423 [15:14<2:57:46,  4.74s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxQM3NnZ3JucGJjaWxLSnhqbEU5dDh5ekMyRFMyMThIN0lGWUJxcllSRzVaQUc0bHZOY1M4aEFpWFMwNkpqcFFrVURQRWphNTBDLWhaRnBabGJlMkVZNmZ3NkFqWGkwZEFqa1V6RjBoay1UWmFPaTJLUXdPbjZoWkRKYkVJWEhBV2VmQlBjc2xucXhZQWNpQ0pUVGVUTmtic194YVBmQmZMd25MbnRGWXRSQVdkSDhmeTg3cnlV?oc=5
panjang artikel: 2022

Fetch isi artikel:   7%|▋         | 176/2423 [15:19<3:01:22,  4.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxORnJMa3Z3eGpkYlN2Mk9JYXBLeHk4bXdmZTlBc1NBZE5pNE56Q0NqcG1HS0FIdmg2bGk0cWtuZi1PZ094LVUwQ1hTOWJNU2dxanhoNkh2MXZKd1JJa3BGVmRpWWZsSmE4SGFuZUVRbW1ZdDRzOVFIa3FkcHVNaUNGeXNBOTBoSTZ3by1lVnNhZGgwYUw0WVotbUhwV3AtcGhiNS1hUTY0Snh0aFJtNVlINUJuQ1BXMU4tLVVSMThEbThTSlhC0gHKAUFVX3lxTFBkZXdRUGk2Q2tYSGtZR2h3UWV5Uy1NelVDZkNWaEh4X2lOaTAydnpWTGV0VmtvX2RvS0daWHR3TlJ4RDNzcUp1d2dOZGdUekZvTWJMN01qOTlwaFMyLUJLamVxM2ZJSXRCNU1KMi14bElOXzJyVkI2VmJHdEg3U2czNEdHbXRJLWFZcmxVdkJPbDZrbDBacTV1NF96VV8wUUhCZFBNNzNXT09KR05vUVpYMXJXRFk5R3VRZFVxMDliSWNPTEJkVUwxb0E?oc=5
panjang artikel: 125

Fetch isi artikel:   7%|▋         | 177/2423 [15:24<2:55:18,  4.68s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxPX2V1b2RHM0tJZ2V1RDdJLUZjU2lWNEQzM2NxLVMzTTVTSUh6bVFKajVRUnNfM3lvZzJ6TTlRWU1teExfQzlmYm5faWpPeW1XQ0ttQXFwdVBFRXVmMHRSYXdkZjBvRzJZYS1jWnhjZ3NGak9CWjEwY2lZY2ZjWTh5ZTY1UjV5bm9xQnJwekhnVUtFcExRZU1wX1IwRkdTSUVhVndtUVl6RlRCd0pxWTlGNlJ2YW1oLWhsNmtKa3hwaTJxOTdwSVVN0gHMAUFVX3lxTE9BRUpEUzFUTE1qbjhGQi12NTJtUGo3dXZjVS1rQkh0ekdEclN6SzAtTXBUdE5vYWhtV3BxMFhiMUN1RFdEZzJJZ25OVlJsSkJOTUdxNDRKeUEtYk9rTVlhQXdoTzliR1RxLTFoekZZRnBNUE1MWm1HQnpENG9uQXBtODNrNkdUclhLdTYybEY5SkxWdExMRlNoOTVfZ21mdkZGYnNSSGRjcW9RYjZ0bE1hVjJLbGRyUnMwYlZDWDU0UG90ZmtGM2ZIZzFqRg?oc=5
panjang artikel: 973

Fetch isi artikel:   7%|▋         | 178/2423 [15:28<2:53:36,  4.64s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxQMVdGSWdnNnhWRkU1V2pYZWJBTmsxOUVnN0lFbU9tOWRTNkRIVVhQZjNSdXFXdnBYd0pidlcyQV9lMVhnaUk2cjJuM2o1Z2xSa2swbV82VGVIdjQwUUJkU25tV1F6d09iUm5IRHkxNFdVNmcyUlh5UzQ0M2thX1FZU3F4eUtpT0hvX2lMYVNsWnVyYm9YeWRaVE94TGdJRU1QRGx2ejlRbHDSAa4BQVVfeXFMT1lNUV9DSUJiMDcwMEpWQU1MVXNVbzA3UHRrTXVjMzkwZk9HWGloTEZqOHZ1SHVJV2NEamNYRkFmd0Q0dXNTY0NvWkpTTl9Td2hfVVNSbVJ3ZFVWR1Boc3pycmJhenZaaWVkdmJXallMT0lwT1NJVEhMbnlfUmNyS3hHVjQzTFZFWlJrODJ1LW9lRVBHbXZPbFpBR0dJWnlDZ3dhVFpYVkxuZ0Q5eXV3?oc=5
panjang artikel: 2510

Fetch isi artikel:   7%|▋         | 179/2423 [15:34<3:01:05,  4.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxNaXNrZ2FJMVZ1aFZ1RDE3dVYxVEdoSDZkQnhVekpiUUY2NGd0WGhIMHRWWmlhMGJDLUZXZHZNSzh6VXNqc2pYRWhacGJWWUhUV2FUaENpai1TcU04T0Vpd0ZyUDdxWE5BamV5ejZnRG5VZ2tPaG5XUGs4YTZSbm5wQzREMnF2V0NuX2lzOWcyUFZYTDNQMGlVMThiWm9RQWRCanR6MjNZNnYxWDFKYXllVDlqTHZmRFFvSC1kWWhIZWxhcFdwb1VrOGcxUWEyU1k?oc=5
panjang artikel: 160

Fetch isi artikel:   7%|▋         | 180/2423 [15:38<2:55:54,  4.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxNRS1WamRhVWZBX2NsaVZKQXdoVlRIaVhnTkpSTHhQQjdxNjEzZ1lsQWtQLXNucHlRbGZLUnVNdS10NXZTUHd1cWhZQVRpNW9FQWluSFlpeGdHN3I1Z3JUUVBJeFZ1bmdCdmdxcEgyNVZvOUEyU3d2ZzRRYjJNZ2ZwNUYwRFVDSUhLLWsxMUdxLWpWeG9uT2M1ajRiNE4xaTVKQWpRWlc1bXRlcTTSAaoBQVVfeXFMUFdQWUlGYXQxa3lhOFc3UWtta1hIMUtaVUpRNkdoVGduSmVkY0FUV0pIQW03dlhEdTZyR1BZSUNuZ2xqTVF4cVJBVzh0VTdXLVJNSU0tYmIzV05mcGlGdGstX2Q0ZUQwUlUwYXdteHYzaGtweHh3Uk1hcTJiOFgxRlpzSzk3a01FSDB0Q3RWRUpmWTJzQUtMWEp2T3Z5V0E5Q1pUTVhlUWxSQ1E?oc=5
panjang artikel: 1311

Fetch isi artikel:   7%|▋         | 181/2423 [15:42<2:49:04,  4.52s/it]

Fetching link: https://news.google.com/rss/articles/CBMi6gFBVV95cUxNM2Zua2g1dXdkR1ptak5tdDZ1LWRfb3lwU04ya1Q5VWM3eURlcUxsZVpxcUZGbVhkU09GUUZtVk5jUGxZMUVtb2NnTWxaZWJBMDM2WEVjMW9WY0NJNnpBUWkwS2VROGp6bE9HeFJ4TDh1Z0VxM2oxVHMwUjRFd3VkN09xUkVLWElmZmhyU1JhLVdVanpoSGVQMjEtclYxWmE0QzVob2ZSWktxNndMaVZnQmNpUDhFUVVnYVp2NFFsbUVHVFpUR2tIRGhoZjFwckY0eGVYVTNmaGJRSkd0WndycnhiZU5pdjVSNEHSAegBQVVfeXFMTkdBWlJjQ0NTb3JQWHVIZk5VOHNoS0txX2paeEI5Z0hHZEdGRl9uclpSaDBMTWJOSW5qczNoaDhlOG10elhlZWw0VjFWdWlxckdUblRaYmk5eGFRRlFzak5FNjFFdEYwQTJUaTVMNUNCR3hXUTE1YTMxdVZzRmtkWUNwTjh3cTBqSWxTTUhmbWlXY3pTYUhONEVnajBLR1VpblZFQlZTLWZ3eC1pVllQdXNJQ2ZWYzc5TjVpQUtMdTZCaFNSNjZSVGpEcmJTNkxBZlRRODRkR1ZfYUM0NUJUTzdST1RJSUh4Yg?oc=5
panjang artikel: 1046

Fetch isi artikel:   8%|▊         | 182/2423 [15:47<2:50:02,  4.55s/it]

Fetching link: https://news.google.com/rss/articles/CBMilgFBVV95cUxPc1VubmFBeVo0cWZYU0FTZVMxNHg5SXEtbFVqOV9ydU1Rd0locWw5TkZNQy1nSGxtQTVFZjhRSC1XSFo5QnAyei1NYW5Ha2pVTl9NUkJVZHczeGRHY3dUcEVmekZaV3NJajBmOXRIVzZncWdhSXJFdnBtamVKSlJRZTU0b25IdmF1YVNsM1h2dEcxbDNWT0E?oc=5
panjang artikel: 1732

Fetch isi artikel:   8%|▊         | 183/2423 [15:54<3:23:26,  5.45s/it]

Fetching link: https://news.google.com/rss/articles/CBMiyAFBVV95cUxNaXMwWFMwZFctMHJmR1d1RjVxZG9SaFo0VzJQRWVwTFdFX25BbU1tZmczVzFuTGlLTnB2VTFoQ0daYmVDSnMyQXY2SkNLM09KWURBeTJ0dWFRVDdnR3pwVnc1WTZQVlpPUjQ1c0RrV1IyV2RtMkRaZXZlRlBxRkFYRnFueTBILVZQU0YxeFZ1YlhReGQ5Q0YwWlpBZDY5dWFjdFdrM1dtTDUwZl84UFBRNWh4bndjRzFXM2ZKNDdOOGhrMWc1QWQxdNIBwgFBVV95cUxOWDNYbDZUUzFCVXd0MmRRYllxQlIwWkVQenhoUlBIMmRvY3l6NVVBNnRGNGJsdG5wN0EtMG5PYWxJRnZNWlYyUHYxQUhXQmV5WV9GcDFvRnpucFI5NlVZOTJOeER0NzNJcGs0LTY1ai0wSllhSWpNTnc1Z0YteFhCOWIxVjVsUGU0QTNuOVRxUmhuWmtrUEliZG1TVjQxeFFBb1F2SGhoRG5JQ2M3SThXNmJSaVlBWlVnVFVHREVaaXg3dw?oc=5
panjang artikel: 2647

Fetch isi artikel:   8%|▊         | 184/2423 [15:59<3:19:10,  5.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxOQnZJcWd1V2s5cUNXWVZ6MmVwREotMHliNS1mNng4czJsblh6WVI2R0VCWE9Vdkg3QnlRUUwzTThhNFhrYnB0NDNZNk9wblBlSDZfdHk2R1h1OWtqM2R3Wlh2dmNLdFU5Vi1ROGFobHlocF9SZkRGT2stR2drQ1BLcHVOMF9uZzZteFUxRHF6cTBFMFc4SklvbUczRks5cmlHTWt4bXFkc1pmRm9uT0UwWER3?oc=5
panjang artikel: 598

Fetch isi artikel:   8%|▊         | 185/2423 [16:05<3:21:05,  5.39s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxNa3REa216c0NpdzB2b3Jrckp5d0hMOVRqNXZTck45UTBpMGZpWnNabEJuSVFqcUEzbDdUcVpWSGp2dm1ibWdqTmZsRmFQTHBoTE11aGxnZmFiNjZfOGJnWmZCWmhJZ3BHMEFDUE5EY1BZZXBwcDNTMWlKZjd0QW1Hekt1Vm9FeVRNdEZoNThWWVJRMzNSalZqYmE2M1hndzdWLTV4UGpMUQ?oc=5
panjang artikel: 3307

Fetch isi artikel:   8%|▊         | 186/2423 [16:09<3:12:50,  5.17s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxPbndWRlVQSHZ1dExIbHlpTzhBcVJreE80NWZOamJEbVNNa00wamJON2ktOHpXbF9ZNlBERnQ4VWZMUHBIOFB5YTBWS3h2U2NYaVAxNnhwb1VodW8wc0ZDSGFDaExfM3RHMUlyd1ozN19zcmVJcVBib2xjSDRBVFJseUZVajI0UXltMjhaSHJUZm55dDNxQldSYXljNnZWSncyWVRfeWlXTVZEZzNOckE?oc=5
panjang artikel: 2006

Fetch isi artikel:   8%|▊         | 187/2423 [16:14<3:08:21,  5.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxNZEk0MWd4Y1ZmcC1naWNjV0VjN0JGSUxnV18zYVZ0TUpiX1N0WXRMdVdJamJ5RDNwek5QWWtTTmxDYmhwYlJ4VnJUTy1FdkFsZU03QXlONnMxSUlwdG11RVk0UFdkSl9Dc21ESVdYZGgzd1hqLWFZcUxab0FMeFRqRGlDbGprSTBIQ2poUGVjTUFCTTlfN1ZPYUlSRGZNNzNlX3E3ajF0OWk3TVprODE40gGyAUFVX3lxTE01SWZVSjJFdEtYeThZemNaWGlRU2JsNTBTSkpKOHNSYmhkZm9zTXZ1MWNVNVUydTBQdUNpM2MzcWNuZVJQYXpPMGtMSVdsUk81bk0yT2FQdTV4RnFudXBfX3lTc1lTVTBxTWVuUV9GaHdVaUdVaFFRbXplUGxsNEF5eVl4a1NxMl9kM2hYV3RhOGFidURzWHNDYndhdVRFYW1yQ1FzdDhoamlmb1Vqc0pWeXc?oc=5
panjang artikel: 2187

Fetch isi artikel:   8%|▊         | 188/2423 [16:19<3:10:16,  5.11s/it]

Fetching link: https://news.google.com/rss/articles/CBMilwFBVV95cUxOTGdUWEhNSEZYNE5xT1dPZ0I1aXo5MUxBZVQ5Z2h0MjRGWF9SZGFkVWhiel85TktpSEN2X3RaNEJSbUVaRW1xcEphZUw1NW43d1V4czBOM1RFMTRkQzNfVERWVm1KUHNCM0dXSFJ2Z3FyNFFRVmJjclhzNHRYZzV5cHhZNU51VnA4ZFdYcHNud3ptOEE1R3l30gGcAUFVX3lxTE5EeW9UMUZlXzdBVVNXMDk1cHBLNFBNbFJ6R213dW15ZUZnYi1ldFNUMElKSzlfV1lwSEtYS1dGVFpncVZsQm10QkxvcnVZcE10SGt1RkY3MzRaZFdVWjBNY0ZpUjNNd09VdzFuQXRCUGRmckh4cjdXVkE3Q0NYTGlLQkxITE1DS0RKSHFnSjRaTkVYMEVvYU8tQUZXdQ?oc=5
panjang artikel: 403

Fetch isi artikel:   8%|▊         | 189/2423 [16:24<3:05:44,  4.99s/it]

Fetching link: https://news.google.com/rss/articles/CBMi6wFBVV95cUxQd21ETlhETnFzSnltLWt1c2RWa0dfMW9qUXdSSVB5alprRXJJN2hNc0pFX3N4dGtjbVBlYlNQSWtmZDc1Tk9sX09IcWc3c2ZzUDVKa3V1Z3JobUI5MjUyMnZRMGlMOTA1WUhmbGs1UC1Vd0I0VFN6TUFlUG5aYmdzM3lZUGgweFdVbzdfQ285X05kODNEblFzbnFPVGcwUktnWWZyUGxMUXB3dW1qSXQxMFRfakZjeVRzNmZOdEo3N2x2ZGRRekNZN0Z2dmJBQjBwUW1SRHBxZzNWai1wTEdIZHJQczd5QnlzNWhN0gHwAUFVX3lxTE5mT3pjYU1lMkpIMG1LcGhvOGE5LTJfUFdFTDV4V2hjZDJEeW9FOXJxM1RZTXkxbHdBVUZGVk9kSEJ6czJkU2JPSDNvQVE3d0hGaGcxQm1pYmpiRDlIVG5xNlRvekhhNDkxLVNHTEwwOGNoX3lRRzRIMEttMVppSnk2SHRfMWRrVmUtTk1yZ0hfRUR1VU0tc3BCVHIyMEVXRDdzLV9PcG80V01RTHkwVjgwcW5TdmdtMFZrZ3E3S0RESUF3dENXV1lwYXRPVjlUMmstWUY0a0lsNGRuLU1kbm04dXF0VGs2OGR0TXAzRmZMNA?oc=5
panjang artikel: 117

Fetch isi artikel:   8%|▊         | 190/2423 [16:30<3:09:49,  5.10s/it]

Fetching link: https://news.google.com/rss/articles/CBMiiAFBVV95cUxQUEN1eFdNcW9mRm1kVnp4UGNiSEEzSlppUEZua0FRcmZ2bFZMM01tckpUTnpaUlN1QmhvQjhCSHIwYUNMNkxrOGJEeDNleDY0LW9xR3paQXd6R0E2ejBmY0FwLW5uSUZ1akJNZXgwUF9TTU1IY2lVU1p6YjBZZURZTk40cFdsT0ot?oc=5

In [ ]:
# df_news.to_csv("df_news_extended_1_249.csv", index=False)

In [9]:
def resolve_and_fetch(url: str, timeout: tuple[int, int] = (5, 15)):
    """Decode URL Google News lalu ambil HTML halaman artikel sumber."""
    source_url = url
    if "news.google.com" in url:
        try:
            decoded = gnewsdecoder(url, interval=1, timeout=10)
            if decoded.get("success") and decoded.get("decoded_url"):
                source_url = decoded["decoded_url"]
        except Exception:
            pass

    try:
        resp = requests.get(source_url, headers=HEADERS, timeout=timeout, allow_redirects=True)
        resp.raise_for_status()
        return resp.url, resp.text
    except requests.RequestException:
        return None, None


def extract_article_text(html: str) -> str:
    """Ambil isi artikel dari JSON-LD, meta description, paragraf, atau body HTML."""
    if not html:
        return ""
    soup = BeautifulSoup(html, "lxml")

    # Banyak situs berita menyimpan isi artikel di JSON-LD, bukan tag p.
    for script in soup.find_all("script", type="application/ld+json"):
        try:
            payload = json.loads(script.string or script.get_text())
        except (TypeError, json.JSONDecodeError):
            continue
        candidates = payload if isinstance(payload, list) else [payload]
        for item in candidates:
            if isinstance(item, dict) and isinstance(item.get("articleBody"), str):
                article_body = re.sub(r"\s+", " ", item["articleBody"]).strip()
                if len(article_body) >= 100:
                    return article_body

    meta = soup.find("meta", attrs={"name": "description"}) or soup.find(
        "meta", attrs={"property": "og:description"}
    )
    meta_text = meta.get("content", "").strip() if meta else ""

    for tag in soup(["script", "style", "nav", "footer", "header", "aside", "noscript"]):
        tag.decompose()
    paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]
    paragraphs = [p for p in paragraphs if len(p) >= 20]
    paragraph_text = " ".join(paragraphs)
    if len(paragraph_text) >= 100:
        return paragraph_text
    if len(meta_text) >= 40:
        return meta_text

    body_text = soup.get_text(" ", strip=True) if soup.body else ""
    return re.sub(r"\s+", " ", body_text).strip()


article_texts = []
final_urls = []
i = 1
for link in tqdm(df_news["link"], desc="Fetch isi artikel"):
    if i < 250:
        i += 1
        continue
    print("Fetching link:", link)
    final_url, html = resolve_and_fetch(link)
    final_urls.append(final_url)
    article_texts.append(extract_article_text(html))
    print("panjang artikel:", len(article_texts[-1]))
    time.sleep(REQUEST_DELAY)

df_news["final_url"] = final_urls
df_news["article_text"] = pd.Series(article_texts, index=df_news.index, dtype="string")
df_news["article_text_length"] = df_news["article_text"].str.len().fillna(0).astype(int)
print(f"Artikel dengan isi berhasil diambil: {(df_news['article_text_length'] >= 100).sum()} dari {len(df_news)}")
print(f"Fetch gagal/kosong: {df_news['article_text'].eq('').sum()}")
df_news = df_news[df_news["article_text_length"] >= 100].reset_index(drop=True)
df_news.to_csv("df_news_extended.csv", index=False)

Fetch isi artikel:   0%|          | 0/2473 [00:00<?, ?it/s]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxNSGFiVnlfaUZyU2ZzVFZvTkdRTURaNnNiSGxHS0JVUFJRYVFQNXVwVkJIU1NJS1lWNXRVNVJ0WTFVM0dnUXhEMDNHZXdCQ2FWeFItMzlWaDcwUDA3bHVDVlp0NGxPVDMxSTlvWW5RVWJZSWxmMGM5elpkSTBydFJ2NTYtcG9EV1JnZ08yamlDM3BzbE1GVTJIX042b0hVbV94TmhscXRybVNvVFhXai0tNVg2UXlqYWE2Z1hrVU5YSmd4bHJId0ZSc1hKZDY3MnPSAdQBQVVfeXFMTzltZ0l6QVpyeHJKNTQ1LU5EUzdMSWZLN0dacFRaT29ob0oySEdTRjVIR2RLV0ZHQWMwczZGVXNFOHRac2FmRWo5dUhsa3M5aTV5QUd4WkpDUFpEbXhxMEliZ0oyNi11UXdZemYzTUdOOTJiQ3dqaGlTb1hVRjNHX1UxSXhJeC1WRVJpRzBnNXR6VllkVkJRelZkT0pESEtiQVNjWlBsZGUyLVY1dU1INnhYd0hjYWhheFYwRU0zRERSaFBlbzFqb0pxZEJqejlpekh4eGQ?oc=5
panjang artikel: 4802

Fetch isi artikel:  10%|█         | 250/2473 [00:03<00:33, 65.98it/s]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxNWldUREVla1dsaVB4bnpkUWpRMHZXRG81REV5OHA4VjktbU5nVjFDYWY2WXdGWUZXRTRFanN6eUJtYWg2YVBiYXpFVUVMQVpxSnhkcDZ5cXdfRUM5R0NsdnRVTTBVSEFNd2hzNFcwTHoxb1E0S055X1EtR3JsTVh2elluTTlVbHFXRVNuSzU3SjljbGRYSm55NlFaN3gwaGs3TTczbTd1dGtnZ9IBqAFBVV95cUxNbXRNYy1IS1E4ejZIZ0RXZnhMM1JJdldIWjV1ei1PY0hfQUctUmZ2ejlkcXFiT1RRcFk4bUgtNDh2Nmo4V05HRHczV0Jwd3hUUVV0a1AtSkpObWNGM29HcDRmNTFxT2ZwNkgyOXpSNXVla1FHNjVjQmtBMlctRW5SaFBUdW9TSnBLXzhiTVZpdEh1X3I5ajNzaWkxaEpZdWVTb0otSElDbVg?oc=5
panjang artikel: 2775
Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQcWpQc3dabzZwUVVtMjhwX2FzeVJBeGJOd1NUQzNmXzlnZGozbTZieDl1VVFGUlAzdnJHUkNRaFE5MmRfc29hM3ZsSnBPQXZoSHFfeFVjTHVVdnRaWlBpeklOdDNpVFZla1hqUHctLXB1Ny11VWI2UjVvZDNsX1hvTDFBQ3k0Nk5EUGNqLVJVbDZEWXh6LW9JVmRpNUFZVElGdFZ5dElZUkE5SGwwS2kwc0kzQnZDMkZIMHfSAb8BQVVfeXFMT3loVmFjUTJ2a09wd2hEa3MteE5lOE5NSUlMYVp6WVE5bXVWbk1GYndHd0JQajZyQ3dFcExObUg3aXYyYjV1bzFfdFc5bTBNbHlqQ0RhOEJ5Mk5IZVFYdXJPd2FFYzIzMzlNNUFKckdjNGNuU1FzQWRGM19keEFKUXpfLUREZndRMFRsSHFuSlBtSU5TRktHSWRBVTUtOUVrQ2xiX3VMXy1fTUJmMUd3ZWtMQzd1NGxFTWV5MWpQQVE?oc=5
panjang artikel: 6554
Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxPRHhXVEJHYXlBMXZwYldwSFdRcW8xQzlyNmxyZXdSenZfdmtPcXFlX3lHS2pGWXZSVkRBZjBhTVY4a0R4OXl4Y19xS3Fad2Q4R3FueHZIVGQzRGNWSF93WklsZTZ0RlhuU3ZELVQyc3hTWFBhZEtzanFGZFNlWG5mM3dQeG1SM1J0STUyUE5jNXplMXpTYjczcmR2aHVRanVMc19SQjd1aGcwem8wcmVQeXc5X1B2TFU?oc=5
panjang artikel: 1125
Fetching link: https://news.google.com/rss/articles/CBMi6AFBVV95cUxQTTBvY19PS3FqRUlEMmkxMFhfc2wzWGphajgtUms2Mi01Q1dLOEg0a2NtbW0tNHV6QVl3eTF3dmNVLWcwVDVpRU5EVTZEZ1llM3ZHTVdNNzdtazduUkNmeVo0NzdadEs5NmlpeDBsemt4aVctQkx5UjBGX29mZ2NJZGxMZWZYRFRWd21tb2JCWUt2Rl9lSWpqMy1kLUhhUjdqT3llenJWX3lNZUd5TXZ2R19QMElZY2gxUEVUcmNadnhYYTZkN3VVYkt3Qm9HQWdIUk56VlJNcnZxaGs0WmdQMUZBcFExOUFS0gHPAUFVX3lxTE5qa0Q0UDA5UDJ6bVhHaFBhZUprQWItSWdVdnp1dldTLWRWeXZzVHI1dzVsZVI3SFg1eEYxbGlxUjdxclZYWGgxcUZpdlF3d2pYeXV0YnJWVFhDV3BiU2VQak5VS1BwZGNIOVZieFFOOGxJR2hTWGtLVjE5V0Q5aENOUDVELVg4OFBWT3Awa25mMFA1cTRIdWsxMm5rdEhoS2FJQTdFNldUc0hsZjc5NVBvYzJEZjBQTDZkeVBnelMxTy1ka3RjSlIzQklQbGMwTQ?oc=5

Fetch isi artikel:  10%|█         | 250/2473 [00:18<00:33, 65.98it/s]

panjang artikel: 1502

Fetch isi artikel:  10%|█         | 254/2473 [00:20<04:02,  9.16it/s]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxQSXgxeEd4VzRVbGtyVzlsUDkxZ3lZX3hGcWVFc3dGNXhxaFBVWGFrLU13ZUFjWkh2YVVUcDNia0IwMjNWaHFRU2VfN1NOemY2NDdHYzhZODVKTWJEVUtreGdidC1VQlM4MW1vcjJfQlR5R3g5dVMxOVdrSU16V0pkeUdQd0huYl8zcEhyVnhpTzBaWVBUeklxamlidzJZcF9pbVdtM0FoMWxKYkZiZTlfd3NTWUExX2J6cjR1c3JLRThfUQ?oc=5
panjang artikel: 3241

Fetch isi artikel:  10%|█         | 255/2473 [00:24<05:13,  7.08it/s]

Fetching link: https://news.google.com/rss/articles/CBMihAFBVV95cUxQdlVrbk5QalhOM1hjWEpqZmtFeWtxdUtqUFhkZTRIcTMybjNZSjZWWEM5MkZSdDJHeEFEUWVtb1l3N2p2Vmlia2owOTVIRjZnd0lUTF90T0dXajhUWjh4SWJfQWNBbW9UQmVXeVFzUUhSY0hLUksyZS1yNFhFYTFfVVlYeDY?oc=5
panjang artikel: 5154
Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPQWpSREk3UGp6dUduT20tVTNzaTJuRzVHMlUzWnQybVdMOGVWTGxNemkwXzdpRWQ1REFRZzFkdkNLZ1V1VWlVVmRjcmZUTVlBUmRfU09KOG9wSFZNaDduOHF0LVZiNGN6U05rNWllSzFYQTNmbl9RSWNzUU5aQWxSVEh2eFRJcWtJZlRaRFluZzQydHhlT3p6dG9IZFY5TlMtaGEtQUNTalNWZUFQcldsOVRR0gGqAUFVX3lxTE1pNEtoVFBITkhieGNxNUJ0V1RSUllfMXpqZWlPaEd1d3owZXdlaldNM05wd0FZVENlV0RfOXZjeE90bGVTdnd3U0N1czNHOGV0Ri0tRXBjUnMycFFTaWRMM05hWVJrYlJPT0RjMDhzZExRd0w5NHNweHJEb1VZOFRyc21ta0RsYjJxN0ptLWVtOWpkY2NOOXYwT214NFptZTd2SE1TTmNMUUNR?oc=5
panjang artikel: 2822
Fetching link: https://news.google.com/rss/articles/CBMi1wFBVV95cUxNa1Vrc0N2UENwcGFsY3IybDIxMDB2VFBzOWhGaWxQcHhKUjRULTRtTTMtdnZENW9fR19WZzd1S1paV19BWVRXZGdtbHNLUjRMbjdyZlA0c2RMVnVMbXhuR1JzTTYxTWFtZFhfT2VyYmxseVBrbmhBLTROSjAyMU1qQmJHRVF0aU1jQlFLV1IxSjBDVHBuT0NhMjRqOExKSkpnVmF1Q3lWMXdNeW41ZjdZLUI4YzJFempxa0UzNG9xZGQwY1lUNE9sNTdoWFVmV09oMUh2YjI5TQ?oc=5
panjang artikel: 2869

Fetch isi artikel:  10%|█         | 258/2473 [00:38<10:31,  3.51it/s]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxPRVVyeXRvT01iRHp0Z0pyOENwcG16eHJ2RjlGNUh4LTQ2cS1waDFUOURLb29uU1RJTEJBVFhXV0prYWdOUFZ6dXhYTXdPNXhfRTExaTREYWtGOHZfcml5YzJNUW40WnYyb2NnZ1VDQnViMUo4SzZtcEdFdHBGeGJCeFZIenhJdlhWTldJby1wYTFmSzNfYVN6dUdDalZfdjI0RmlWcXpaeDVUZG51a21hb2R2cWNFY3ZsTDVtblZB0gHDAUFVX3lxTE5wcTREMlBWRXZHWndHaFEzNktUZlg4S09mbGwxRzBlbjN6SFhvc0YxYzJONHMwQ1l1WVJraEpfU19scTlJZkd2ZGdHc295WDVmT2lfTFFsbzAyZFJUbWdNLTlkdUpGLU1ZeDM3aFZmZ0dTaDRTby1HVEl2TFpZUHM4b2Y2WklnNzlndXBmTXRaZldUaS1vdmxkY3B3ZnZtSFpMdkxhMkZlZ0lDenJGQ1NONkFXbU9nZ20xMmZNRWRRUTdCRQ?oc=5
panjang artikel: 28953

Fetch isi artikel:  10%|█         | 259/2473 [00:41<12:20,  2.99it/s]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxOaWg3eDAzTGZpV2tzNjctRUVZVjd1b3FhbkkxRXpESDVLVnVFZjIyaTR1SkprQTJoalUzSEMzeTRPVmk5ZEUzVEszeDNmdmc4LXY5OVl4NG8tWXNWTTVVSHBxTERGVThmejk3TFk5SFpCbUVweXpLblRjd2pra0dhTU94cUtVeEI5UmpobUxBRXZ1NkJPTGZQYkhhVzk?oc=5
panjang artikel: 1642
Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxObnEzTVpxREZnSjNXa1AyM0pzMWdRU2lnVDZTWVNyTndiMHRkNFY4MUxWWDRhVkFNSGlMSWtPWVo0VmFDeWMwdW1aWUx6ekpMakpCazBJWnN3bUZEQl9DMElEcjU2SUFmN2VoRlptWFJyM3E4bTZaU0FoNkNHeWNKT19uZ3N3eFJTOEtLSWJBeHJfVm1qNFpSemI2VHJfU1o4VEpBWWJqUWM?oc=5
panjang artikel: 2049

Fetch isi artikel:  11%|█         | 261/2473 [00:49<17:44,  2.08it/s]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxNN05Pd0dTN2dPVVR2ZHdvZTVIeTVWZWJVLWlFQXNfNmV6ZEk1MEc2YmtrWno2d3dqMnZ2YU15UDI4NnRDYTFnV01VSDB6ZXBaVGxQWFJvTWp0OGRYa0hRMHdiNkRJYkVndTN4S2RzdXltTkxjd252Y3pTa3p1ay1kT2tmTXowaE9Rb09lSWpENWEwRlJuMTFsVHU2MWd0NVlpTC1RdGRKMVlfUVNXRFdRU1BVbFplY0VyUTRrWlpvM3J2bXdXdUJv0gHMAUFVX3lxTE1oVVcxR3NiYnp5emstcDNVdkVsWkJNd1AzRGFpNHZLV3U4Z09hUWxaN0xvVjU3Y0YtQnpUS0ZUdXJISXpPY0p0SUt0VXRrSmViMTV2RDhsMi1yd2NrT3lqN1ZfNl82bUpFRzRMeUktNjJOeDMyVm1rS0tCTGk1Y0lDRTBDZHEwWXc3M2pRcXJLeFRKbzJRd19tanppS3Flc3RlaWtEekUtTkdmYmhaWWpMdVNDSVVMSFlQelBkQzZ4WXJ3SDlrX0JNYUZaZQ?oc=5
panjang artikel: 11031

Fetch isi artikel:  11%|█         | 262/2473 [00:53<21:15,  1.73it/s]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxPSjZLZzhwQTBET0tVY0gxUURDWGdsVXJvZjVRdlI3SWlRZFZTQTJNQmliMVdEdVJLTkZJV3ZXRktlcG5WdExuaHRJMmpVMkliU0hEUTNTTjZYWFdSSHNKRUNhN1Y2eDBxWE5Tak9YYlhDMTJRWWUyMW9sdG54UlBpSTR2R1ZjZnV6RG9Bb0I2eDdKODVhOUF0OTh2QjNKcThZUzVkRXc1SE9OR2VtMVViMldySkt5Z2IzSU1lc0U3NUQ?oc=5
panjang artikel: 0

Fetch isi artikel:  11%|█         | 263/2473 [00:59<29:51,  1.23it/s]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxQdFluRjZuTHo5NHc0cFJwamlRTXlQdVRpUUt4ZXd5RWFUNGN0eE0wcWRiT3hCaTJyLV84ejQwM1A4MFZQUjItNEFfck9mNGNNT09vN0hvSGZWbkt3TWRFV1FwUTFlTjFMSG9aYUFjQU5TVGFfc3ZWamw4ZmEzMWpLd0dVU1NFNXBtRXRzRXFYdklJQ3RpYVBHeDAzLWxnb09zTTNPaEJIY2o?oc=5
panjang artikel: 1441

Fetch isi artikel:  11%|█         | 264/2473 [01:04<36:56,  1.00s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxPbTFtUjZyQU1tTG15bUdKb1Z5aFBBaktqX3Y2Q0o4U1h2U2xGU1VYTVNfLWtDSS1BSHd0ZUVReGFheTNtZlJlTjg5TXM2UlBualF6cmFuOU9jampQQnJUbUV6LXg3V2k1NVVmMVFZak5JZnNMNlNacW1MTmd4VTdIbTItSkdGLXp4NGRpTzZ2Ry14VjdNU25qX3I1UE5WVnRWQzdyeWdzbkhDZi1PQnBoaG04YVpjOGZEN1Vr?oc=5
panjang artikel: 4521

Fetch isi artikel:  11%|█         | 265/2473 [01:08<46:39,  1.27s/it]

Fetching link: https://news.google.com/rss/articles/CBMiV0FVX3lxTE1kMFpteFFFbVNpdzBnd1B2YkdnTHpZM0dIR29CbEZVU0lKS3dVbms1VDV0V2J2NlNVd1BxS3JlR0Z0U3lXaGVtbDdTTEFOYjVjb0JoQ0FLcw?oc=5
panjang artikel: 8557

Fetch isi artikel:  11%|█         | 266/2473 [01:13<58:17,  1.58s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxQcmdpUlFsY1hDQ2VHRE8xejBNWnhHMUJaVDdhUEVZZ24yWm5HV3lRZUJoMWJJbFYxMm5ZUmJuU0ZuWUJyRkJpTWNrUG5fQjBIbmNUX3Q4LU5FX2ZrWW52eWd2a2V6NG0zaTFlZmVDcVZEMzVuN1c0b0V4bHl1R2lEVGhXeFczWFNrbHdJLTZieDl2UUZZVnBVUjFabGZLVUJ3QXc?oc=5
panjang artikel: 0

Fetch isi artikel:  11%|█         | 267/2473 [01:17<1:10:14,  1.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMingFBVV95cUxPZzhERXR3dDZQcXRuOE11aW1ydUlvLXF3ZkpGRnFQT2FMMEdmZk9jNHZhdE0wRk8tUG5iZGxlNHNrWmJjU2FnRlJVakJYbmlmenRlTVIxc0N0QjhHemIyVUJtS0J6d3hzZEFMMkhocThucnI0ZjZuTE95SzNHbjFfYWRqeHNkM1hLb1VZcDdWLVZ2TlpfWWdFMXdnSFhOZ9IBowFBVV95cUxQdEdfd2ZvZlJzNmI4THd5M25aVXIxTTlxR2dqbWJic2Job3J3dWtRUFhZRTlxWnlkRF9sRHJTT0R2cEROWU1Kd28takRaeHN3NGI5YVR4U3JXYnluTlEzZ1diYVVsaUttTkVVX0ZIWGZ1WF9zUG0ycTFGZ0FNcW5UUFROWHNKVURBUFBCVVhVMkV6UkN3ZHJ2M0ZiTDl6OWZmTU1V?oc=5
panjang artikel: 4994

Fetch isi artikel:  11%|█         | 268/2473 [01:23<1:27:29,  2.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMiaEFVX3lxTFB0LUFLcVpXVUFjYWRBc2R6VF9pVDA5bjg0anBHS3lCQi1SUkNMRHUtMDFELVNoeTNINGctNk51QlA2RXk4WUlfM0RPQW9Qc1J4emJRZThmLUd0UVI0ckU5emkxVnBIQUk1?oc=5
panjang artikel: 8537

Fetch isi artikel:  11%|█         | 269/2473 [01:27<1:41:05,  2.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxQN3pkNjd6UnlTRXhzdXhkMHlDdmh5SXIwREo2SEpZb3ZBMDlaR3NuUHR4UWpJTTVLSTVaVURnekYxYXJES1VpVVV1TmZPS1FMdkJmeXZ4QlZLSWpXX3Z4ZGlMa283MmtiaUFzVWJOMm9obENkTHlxRnBxNzZjZk1PaE82QmRwUEZJQjJYR2dXSTlVQmtuNlpfTnZtaVVVR1hyak9zbmM2b1NPU3kzeE5aQl9jQ3Z2NUk?oc=5
panjang artikel: 5119

Fetch isi artikel:  11%|█         | 270/2473 [01:31<1:47:29,  2.93s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxNbmRiTldYa256YzhkTHA2Ym1GN3kxWDJ6VDFVa3BIWGdwOGU2NEdZYXpvWGlnUmhLU3hnckV4MnFOYjZWdi1Yclg3Rl9TaWdZb01jWVBKY0k3WG9NYVdPV2NfNnNZZGd5OTh1Ym1YUUlNUS1IeTlsN3BfQWpEbWdqYlNad1h4TkpIdEdIdS1LLWZHZzlDbWt4SlhTb1VEamU3RHhXMVNRcGp0Nk4tbWY5SFFvOGVMbmREbjhSX2xta2ZBamNFTmJqRllPXzRDS2M?oc=5
panjang artikel: 4517

Fetch isi artikel:  11%|█         | 271/2473 [01:35<1:58:38,  3.23s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxOa0JmZkRlSXY1QVN2MjVCdXpZSnZTeFdVYW1JNmMtWFNqU0U3dVRwQ280ak1rdjl4SUZ1TWJFN2RwX1B6WTU0OEhiX2ZSTXJVNFNhWTBrajM4Tno1YW9LNER5SE1FU0NSN0lOQ0VTcmY5dS00bkpLXzlQUl83M0J1em5lREw0ZFZDbXJFbm83czBlRFA2el9KXy1IdVpNeFB1NEt1NUlMNS1Ga0FCOHpZYXNwRFJwZWZSdnI5ZzNKTER2UXZ5a3c?oc=5
panjang artikel: 2335

Fetch isi artikel:  11%|█         | 272/2473 [01:40<2:11:46,  3.59s/it]

Fetching link: https://news.google.com/rss/articles/CBMimwFBVV95cUxNR2Jta2FyZXQ3dTZtZFVTMjJIZktQbWNDajlETndycDhQckpqdlN6T001RHNHS1huNjFaTEVNWVhCSGtFVVFXaEZ2cEQ4bnhYSndZd1l6UUlMaTNtXzhZMVp0ODRrT29Nck8tSXNzNGxhWnZLSHJseTBNNzFvRGEtN01FbXZuYnl5UGpuT3F4a1lsNDFZOUkyUXJ5QQ?oc=5
panjang artikel: 2931

Fetch isi artikel:  11%|█         | 273/2473 [01:44<2:17:55,  3.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxPUm5DVGt6b0drQllLbTVTb2ZWQk1xRmJGTzg3b0N6ZDY4ZnVQWWpXRGZkWno5RWRFVnc3RmdjNE1HckNiZW94WEFhRm1Bbi12dWo0UDRnU2xnaFY2dEdDb0FrNndmN0dLNlhralJCRXhERHBhdDdCM3MxbVNBX09GazFKakc5YzZwM3pBVkN5UkM4ZEw1MUxRNWtFeVhBMVY2WWNEdW1jM3EtZFc4WGhncA?oc=5
panjang artikel: 7270

Fetch isi artikel:  11%|█         | 274/2473 [01:48<2:18:04,  3.77s/it]

Fetching link: https://news.google.com/rss/articles/CBMimwFBVV95cUxPaktWY2NPbng3eGRlcE5ZS2JhSUNQY2lic09Jd2hRbEtzaTdUSGhKWWtBQThuR04zS200ZnQtaUV0YS1XT0ppUThkWFY4WjBWRklXaGZCNGNLUGhwckRhOXJQRUJISkZLRXA2a1hNZlpQbVNPZ2F2R0FzUndQU2h3VVVXR3VUeTFpeUV3ZUZZMTlkZld5V1pXRTRkYw?oc=5
panjang artikel: 2366

Fetch isi artikel:  11%|█         | 275/2473 [01:51<2:12:48,  3.63s/it]

Fetching link: https://news.google.com/rss/articles/CBMijgFBVV95cUxOU1B4d0s4cjRqRDUtN2QtQ1ZGcXpsUncwVDZKdndlVFdhcmt3S25zbHRXMnRVenhPa01acVJSeHBVSlpGWk5fcGRYVy1uWFlIUG9xaXFRMjFWQ2R0UkpVYmV5U3JYYkVvMkFwblh5U0NtWk9OeHhUbFdERmlRaUdJWEpvR1YtQUZpTnZGSGd3?oc=5
panjang artikel: 1699

Fetch isi artikel:  11%|█         | 276/2473 [01:55<2:11:57,  3.60s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxPeXhyMXJWX282ZGtRQUJJZGdTUWRJRFl1ZEFaenRSMjFEd3NYRXVQSG9Ba3ZDck1McTFkbWR4RHJ6dlNOcTdxNVZOTGtPdnZVYjJfTDk5Y0JRRUNfeTZLUHgxR2JxTHFwdkpyeWE4aWhOZjNUWF9PQWxaUUY5YXo1OTVFZGpMbGRpTzQ0SURnYWhQTnJqM21TMlByeDJjbnJISUNsWHNKMDh0RURx0gGyAUFVX3lxTE1jVXNNY2JmWUpJQ0NlSWFmVXZfV0tOMDNnS0xLSkRWc05YbjlyVmpsdFVjMHpsSFIzV0libFpMdmplN3o5MFBoZ2kxTDRQY3gxTW1haGtpXzM0OGxWM3JiMEFOV2s3eVlmUEoxbnlBZ1F1N0J4WWNKTDlCbTlCRFphWk1UWFY1WVZ2eTJ1c05YOEw4LXBDd0ZHc1hVZjBhME9ZMy1vMGJuVDJMTlBCbkxUN2c?oc=5
panjang artikel: 2363

Fetch isi artikel:  11%|█         | 277/2473 [01:59<2:20:33,  3.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxNRkFFd0NMMnpyTThqeDFOM1hwdDJyZFc3aW84VXlVNVloaFd0dVd0ZlI1Z3Rfa3d4R0tHbVBIN3NUNmY5OUxmNmlsTWFSc0hLM1ZlYi1CYW9ISnFlUzdhQURYOGJpOVFIYmpqNlRXZjNmRTBteTBVb0dpX0c3a2NGcThhbTRhN0hKMlpweFNUdDVQc2JNeUthNERsN3JIQkRpblJHSFl2UVFpVnZMejE0SXV30gGvAUFVX3lxTE9tWmV6U200SE4yQkRoOXJKQlI0VEZwendpOFEyeV9oQjNYYUEtekpndnRLOFdxdDBPeUstQVNIU3hrYlYtOXc5VTVySEFNN0cxNWFLOUxWWEpwMVJDWlRDT21DYkpPQ25GczM1NjZzZmdJS3d5X3JXSFE5eVd2Rl9XYWtRN3FneTVVZHlscFRXaFp4c1dSLUhWRTNjYk82ZHM1QW10aGV3RGhWeHA2eXc?oc=5
panjang artikel: 2160

Fetch isi artikel:  11%|█         | 278/2473 [02:03<2:21:13,  3.86s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxPMzNRRVB5YkVMVmwybC1oSEdiQVlZb3hKel9PZ3pRU09DUTREVUVXYXpRZzhjOHpQeFItZjBPU3IxOVVPV1YyRTMwUXhjNmJ4dUJSM19BVzcyMWxuaXF2Mm1MUXZqTXFUMERLcGVSWDVIUEdRdEhJc05UREdxVUpDUzEzTG5ieTRhQUVHZmRkUnVxWmVJeDR5bFNiZUUycnhob3VzM1hlYnNPUQ?oc=5
panjang artikel: 2745

Fetch isi artikel:  11%|█▏        | 279/2473 [02:07<2:20:17,  3.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMiyAFBVV95cUxNNUV1YXFFaWFhdHh5WHhsckFOY0dOV2FRQm5zSElKeUh1ZmllSk11b1A0b3ZEM3pKWHMweG9aOHZ1M0w1bTJoWVE1elpxcjZINVdWUlc5SnJQdV81QUFLOGl0Y2NMeXcySlR0OUl6bXg2eTdLX1AzTFhDTklCUGd0ZmNoNDZJcUljYUdWRWpGLV9OenBDMUpFTHloWFFvXy1UVFJYX0hLVWEtVnRTTlhDVFl1ZGE3MTdTQUFGY1FiVzZWWTZLcHpmXw?oc=5
panjang artikel: 3763

Fetch isi artikel:  11%|█▏        | 280/2473 [02:10<2:17:09,  3.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxNYUk1RG9pUmxDX0tiMWRnel83bjZtNjd2elVYYmFSRFlDTkNGSlROd2Q3TER4d085Z0lQY0xYMmRNVTZEQ25FSGk4TXlfV3FBT0syUHBJM0NwSkVUc2hDTUFSVXc4SE01OWlVMVR3RjhyX3hIaG0yMVZYRWlnWnhvUVFoSkdyT1IxaFZqcFBiaXR6ZVpLZ1Rnd00zTHhtamFtR3R5aVdqcjU3LUlURmRqTDNibEo4SGZ5?oc=5
panjang artikel: 4320

Fetch isi artikel:  11%|█▏        | 281/2473 [02:14<2:19:35,  3.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxNQXpjc2xoUEVMUUlGNGFxbElIbERiNm5KUFc1NmlHMjRDdHJNaTNzdk93N2N6WE8xTHpQMnRhYlI5ZmtmOV96bm01eUVmenFVeWxpU3d5UTJpUzAza0cwdlJsNDNVMGp5aDc0MEFnNU02U1o5VmZYSG1wUnVGdXBvemV1ajBYSU5JUWZYTlNVTFJPOWU3SUt4NzdhNW00TUJLU1E?oc=5
panjang artikel: 1542

Fetch isi artikel:  11%|█▏        | 282/2473 [02:18<2:20:36,  3.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxNOEFmNmJEZkNzYlRlck5LWHJnU01kMjNpMVJsU0hWUkpWc0Q5Q05fb21vbjcyOW9vcERKcHV6enhweXBYbWQyNlpfc20xNWlVZTk5MEo4SGtLcnhjMTAxdEdRclRBRTFjZC1YTXYtdmtWaDV0MmNsMnhHYWdUOFEtRlNfODNSUEV3SFhWS3JoUml3MzQ3YnJQd1QxMllNdGxocTBtY0c1UzQ?oc=5
panjang artikel: 1471

Fetch isi artikel:  11%|█▏        | 283/2473 [02:22<2:21:39,  3.88s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxPUkZKWk1RSE9TVHpEYUN6bWtkaEtlNFFOT2RSZWdxS2ZGQVpoc1RYcmFCc3RzaFp2NWFSdkhBSWwyMGRuaXgxMHVxaEVCTmE5bHFHcndJR2dfUEcwVWpQNEN4aXZaRzZvdExRODhiTi1CRWctRlQ0RWViVG41dUx2eTZfOHNVNkpWVUYzVVRVRFQ1NF9TZmJfNzlVYWx5dTJhc1d6Vw?oc=5
panjang artikel: 2226

Fetch isi artikel:  11%|█▏        | 284/2473 [02:26<2:21:13,  3.87s/it]

Fetching link: https://news.google.com/rss/articles/CBMioAFBVV95cUxQT3laZmQyZEM1V2w0V0I5NW15WHBFcmJPdUNHd1p3SWg0MkpVZjNUS0dHUk9rMGRIOXJYVURNRTNYWnBmSXRUcl9WaGloalh2Ukd2dFF3bjdLRUNTVUVXU1JNTGN4NnMtUGY2b0NvV0ozZmFXZ2V1eTJRSUNNRGNIZjhrTjI2c1R1R2VocE9mRVVFdHZYdjdSQmNva1h5Q1RN?oc=5
panjang artikel: 3735

Fetch isi artikel:  12%|█▏        | 285/2473 [02:30<2:27:01,  4.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxQbzFlankzZEpkbnJhU1Bhb2NVVV9oMWljRG5fT1hpbVF3anVoQTZicTlLY2VOcU1sQ3hXdVRxYXl0ekRLX1RMUUFFaDh4Yk54QU1SZXZnNmRadFRPcTRIbHdTMkJjemtnb3gtNm9RdFU5c0JJQXRKalBvSm05eVFUWkFIUFZGMXJzNnlQYkNxUGV0YjMxZFpPUnRJNVNLRXpyZU9WREkzb0ljdE14MndLUjN5SQ?oc=5
panjang artikel: 1634

Fetch isi artikel:  12%|█▏        | 286/2473 [02:35<2:36:47,  4.30s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQa29SODZLNE1XTERXRFRMNS1LWTkyeDM2N215V2E2OFVFWHFMYzZmVzZ1VEFzVndlR2xRZnRBWlVJay0wX0JBNjVobE1COTVzT3lmZlJ3Y24tRzM1T0tnTDlzdmI4U191a0RpUm9GeU5vZV9fY05EYmxiWEZRQmRrZTQ0RTlVX1BiUFliRC14LVNxSzJNV0pJS3BwazVUNVQ5NkFpQlNPQTNiM1dFaG12elNud3c?oc=5
panjang artikel: 1867

Fetch isi artikel:  12%|█▏        | 287/2473 [02:39<2:34:14,  4.23s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxQd0FWTmVZT25kbUYxeG5zZ0k3NGVvS0g3R2dUU1A1SDhHb0pnVE1nQ1k1MHkxVnhaOUdtNnIwZ0VjRnRNMzhsOFg4ZkRNZVVsb25LRzgyRmdLUDQ4SDhOanJCZmtSdnZCYi14R1NEZmRZcDlza1ByTlFWdk9yR09tdVlRcDh5RDlkX0VUZnZNb25tNHFMTlZyQ013d3k4NWJqWVpaaUFvTm9hWDN1WHliSWprR2ZraHluenFiLdIBugFBVV95cUxNdkZpbWJ6ZzVXYnVSdWVHUzRPc0prWGhfV3ZWSUVudThMZFpPT3ZVV001VE93RFc5MlgxYXZZSFNwTEpha1NKLTl0ZWpScnZ4bUhmQzV2RHVFZlRMWVAtZ3VveGJ1RUUyaE5Sd1dxbEk4cnZXU3hGOGREaHN2VGJvUlRmaFhtQjNOLVRKS3NmY3ZWR215VXpPRDVQTFM4Sk02YUVPdHFTQ3VYaEFvWWlxbFBGdVI2cmZGOGc?oc=5
panjang artikel: 3888

Fetch isi artikel:  12%|█▏        | 288/2473 [02:46<2:57:44,  4.88s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxNazN5TzVaTGczLWNPRi03bVd5NmZqUXNVdGJjQjhLeWdEbm1ZZnhEWTZzZmFzSmt0S3o0ZXBONWxLQU9OYTVDYmxUV2VzbGNUWmVjWnhLRHBrUTdzSEZGWXJoeDJob0VqcGZDbkpSaG9neFh6Y0FIRUpIN1lHd2ZoRDBhZko3Rzh5ODBWaUt2T0p1cVBFUXB0TUFFQ3MyOTM1WFFmY0thZjlnR3dmZFYzLTJ0aXhJVFdfS1QyNEFJM1VkRUk?oc=5
panjang artikel: 3379

Fetch isi artikel:  12%|█▏        | 289/2473 [02:50<2:46:47,  4.58s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxQVk1sbHFUdUJnVWJCSEViOEktUmpHVDBMUU9MT2pGR0hxU3FhcmdCRE5uZ09RTi1MUFN2UUIyVENfM0RYTGNVblRlTkpsem92ejVmS1RnMzFXczd0dU1WZGdEUGYxWnFhZEgzM1d1M1B3dWRlbWl3c1k2QlZ2WS1BWG1XUjk3eFdFUm1FWkdkTXVvU1UtTk1pdVZrSXlKaEppc0lRMF9UOTdHcEV5TXFaSEhvcHFHY3ZBWnR0N1JVa0c?oc=5
panjang artikel: 3233

Fetch isi artikel:  12%|█▏        | 290/2473 [02:54<2:40:23,  4.41s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxOT25xZTVvQktZaGJ3dGpmczVFOVVnQ1I0MWVMSmJ3T0R1TnRRQVJBNGJ3Vk91UUdQcDFScjM1bU4zUElGUVAzUU13bENJeVFZQ0RNbVpVelJSRVhnWkRFaU5fb0Q3Z2x4UU52Q0o5Sy1TTmNOMFgzcmRTN2psR2FFTVRuZEJPUTlzLS1KYTNlY3FXQkhZeVJQTktvd2NBNklEV0NDdVhzQThqUWMzenAtRU9yc2dqU2NTaG9LbEFZWFRkWDAzZ3Jv0gHMAUFVX3lxTE9Yd1RkMjdLSEREVFVVQTFJcHhHWkdHRWV0ZlEtYno4ZnpCOENtanFmUHVnZ01BbFpVYWVubk5NcnprQWN3eXdsTFVyb05hdjQ1aDNBTGNET2NjWmRwV0RFampORmR6cHRTdTBKeUdPeGJsQmlncVF0aVpUb1d4MHJYdUUwUWxLNG9md2FxOVRBZWJsMERPYzFkMllSZURqRzVJWEZlWXQzYkZjVkNUVml0MXp6NlFwdkdoRFI1d3BKZ3JQRTZRNC1iWTA4VQ?oc=5
panjang artikel: 1009

Fetch isi artikel:  12%|█▏        | 291/2473 [02:58<2:34:40,  4.25s/it]

Fetching link: https://news.google.com/rss/articles/CBMiVEFVX3lxTE1KNVJqcHU0WTNpY0JNYUhHOXl4RzJobDcwRTNPenNaWkhZMGdKVzdISlg4VGJVOUZ4Mkg5b3c4c05iYUpuNkNyNnB6Sk01Vk0tS3U1Vg?oc=5
panjang artikel: 1935

Fetch isi artikel:  12%|█▏        | 292/2473 [03:02<2:38:39,  4.36s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3AFBVV95cUxPUEctX1ZOMmtuVmtieDRKcDlBTTduZ1l2T3M2VmpXeGFLN0ZwTjM5Ym4wZXBYRmdEdVhES1dINk82d2luM1lSSkxQOERMLThmZW1PMUNxQTVqWEhjZ1c2RFNJMzh6T2JTY1cwa1VJdnN4ekxNR0tIbzhMS3VPM3RhTDBULTZFTjZMcjFtVHdRdGdFa3BieWZUYzd3Q2FHVW5GUkdMTnhJNldRV0EwX3BlNDdUMWtBUzZwVlYtLXdhQWtwY216ZHFlVU5DNHF2aXVJUGpCZTJKUzhTYkkx?oc=5
panjang artikel: 0

Fetch isi artikel:  12%|█▏        | 293/2473 [03:06<2:35:49,  4.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxNTzVtcnFUUW1JMTVqQzE1S3RtQ2lDRDlOUXYyM1hfTmxGdk9Rb1EtZDBvd1dOR2haTXA3NjUxbjhZaXMtVV9ZWFJnbFdFQmRxbnUxejdSVXI5My1hb2NYNmthMVp1Zm1qeDZFendhLTlWWURKX2JtOC1QMjJobXpSY2VOLXBtdG85TmZUSjRYMVl0blh0RGRxRE9mcGhPakV1OVQtSUNHNHdZcTVOUFp5dGI4Xy1EaG5TdnVxaVNZLUtVcUIyVUHSAcsBQVVfeXFMTzRicS1obHlVUFhjVmlTZjVzYWpWTkw3UU5lcHB6ckNfY0IyZUQ1TmZ1TzFVblpCeHRUWkhJSEdLS1NaVDdlOXVpUDIxdEJ4dUNBZGNUdEZMNmxWTTJYTndvWGt3LWRuS01qVnhkYVR2TXR1aVptZFpVMXdNYzdpNklnV1VNZjEwMnN5WVY0X2dKZFkxbUhTVFdYa3BBN2RMRUgzSWh1T3hNaW1UcDFJWFdlMmhaS2JRZDZ4U1BjVjh2WE1lV1BmOFRDT2c?oc=5
panjang artikel: 2168

Fetch isi artikel:  12%|█▏        | 294/2473 [03:11<2:35:33,  4.28s/it]

Fetching link: https://news.google.com/rss/articles/CBMizAFBVV95cUxNYWl2NUZVdXBxb3hFcnE1OVFobEVBVFFVY19kbjhTMkFNNWVJV3ZFemVpZ2xINDRHOU9Ib0VUVlVFeXhNV0dYVnpWeVFpemVZVV9UYTNMc01fQ05HbVN5SG9TUjZSVE56eXplc2lpN2tJN3pnVVpfRzN4VHNEV2hSeG8yNGtZY0gyc2ZQa3ZTUXUwZmp4SG1kUDVQWEVlaXlEalA5aXk0Z0stTFFjbjBvbTl5ZnBKSTE2azZab1dvS0t0bzc5ckZRLTJnNUg?oc=5
panjang artikel: 3855

Fetch isi artikel:  12%|█▏        | 295/2473 [03:14<2:28:13,  4.08s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxOZUZ5cXBpQVNPVS12R3lzdldZWTc4WHpNaXdkeFdBN2RpMkdSR1l3M0dUazNDZEdhTUYxM3lVQ1lKUkFxcGhKVkV0OEJTSXpmdXY0WDJ5SU5ndncxcmhIdDNuQmk4cm95SkxjbEtnSHFPSENrdmlPZmkwNzM1YVB6SEhJWjJtcHJpV056eHAzZkJfeWNGQWxicFZWZE9mdmFFUk41cnh1Q0lvd0gtUFZOZU9PNGZYZw?oc=5
panjang artikel: 2312

Fetch isi artikel:  12%|█▏        | 296/2473 [03:18<2:23:02,  3.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxOOWZaWEYwQTBpbU9OV2R4RVRIVHlXRzZrdVQ3Z1o2TGVTWUpsX0QwMnRmWEoxMVBCS0c1MXk5T001ZkxQNWlUTFB1b3pGbG5vLU1xWE1MN1dLdTNGT29VSm0zZzNzeUdveXNuVWVwQ1dpQUstaVVoUUhxbkFIT1hEN2p0dlBxUjdVMHZMZnhKWFhySVhrZTVEWTBjckJVZ0J1aFlURU43M3ZwWF9KOWRpZWpBakZISHhXMVhpVmtMQXprclMtRWxnVERn0gHPAUFVX3lxTE81S1FzWkRUcUhQV3BVaUVXVTY0ajhaUUpFdGpUYWd1WDVLcU55d25mSmV4dWFjNGFLalJxWHJGWnZXa05mb2lySnBoQWs5X0NZWk94YmlabHI5NGl4TW1Fay1HN0pTd3lENUFZTGN2aDZJNVFGM1ducFZ5U3gtdDE1eUFiWXJIMTh6QndqZVluN1VkdWdfY2pqR2tlM19Ra3Z3YnU1VXpuNEIyckhLRkp2RWt3S2NPdmI0aFpJLWtPNWZMN0tYTDVSajNNQUh4bw?oc=5
panjang artikel: 1516

Fetch isi artikel:  12%|█▏        | 297/2473 [03:22<2:24:55,  4.00s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxNT25KOWhEUVNWUEJEalR6MER0RlVHbllTaDlOUklmcFQ3d3BxaFgyTDg2M0o0S2MtMVdDdGxRSUxDOTJpcko5amsxdEluTWhZVWdhcjd3RzlsdWVwNEJOakVlSVl6a1llQmt2OG96R2ZqSWQ0aHE2cl9aQXo2dFFBUzcwaENFZ1JWNzA1X0hSTWdEVFRpeUdUSmZTWUR6YjVNRTVSYnFDM1VIaFNNNW50U2RCMHpjQWfSAbwBQVVfeXFMTWF0SEdvRndEZVlsc3dzdlhRdzdHdXFmdmpwejR5cExRTWg3LU9VcGNfVHlIdG1BdS1UUU1HZFBScnJzaXdhdzBhaGJKQTBLaVVZUG50T1FMQk5QU25oeURZdTJZdE1IR2dYN3VKbFpHMmp0aVFLdTNvemxBMUFLOWhnY0VVbWN1ZnZVemp4X0V4NkFyZjBoT0hVTGY5V0o2M2R3UnpPVWdaaVVqbVRjRTlYMlU1Z0FTLWxzOVc?oc=5
panjang artikel: 1472

Fetch isi artikel:  12%|█▏        | 298/2473 [03:25<2:19:35,  3.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxOcnRHbmtKXzYyV21YeE9TMENsQmJkY1dJR2pBZmNmRWkteUFtVWREU1NWWlY1NkVXVTdTVlpQWGJENUotaEoteUxmT2RsZ2Y5WVZGRG9XNE9oa3RnTVNmcjVEVmFtYTVMT0hkS0xNMG5fdmhDZnFVUFVRekJXcVF5UHp4ejlsclV6Z0RPc0htakRkTzJwUlBHeThGTHREN0dmUXlaaDI1MGp3MXYxWjBYS0djdnpYMzNMUnhXVy1xRERRZw?oc=5
panjang artikel: 4077

Fetch isi artikel:  12%|█▏        | 299/2473 [03:31<2:35:50,  4.30s/it]

Fetching link: https://news.google.com/rss/articles/CBMihwFBVV95cUxOdDc1M2lfVGVmWmJSOEhOdm5vcjhydF80dkFyS0xGcVdLYUQyaEFtS0NIMHgtZmtrd2FNek1QeVNnZnNicmR4SzQyVGlGczh4dHF0RWcycDFycmNUbDJQUjhTb1UzSzQwN0pydmdvT3RGNk40YmJ0Q25mbjFvNHhxX1J0bUNKbnM?oc=5
panjang artikel: 1911

Fetch isi artikel:  12%|█▏        | 300/2473 [03:35<2:30:34,  4.16s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxOZ3B2aGViTGJXVzVIN0dJS24zaGVtZFA2M25ROEN4RVBJRkJSWm9yWU82M1RzTEI5WWMzTTNxcEZYM0VYQ0hRbHM3V2dnazRQWnZSWmR6NEtxNDVMVE54NXhWZ1JaOWkyREhNaUg3LU0zWGdxOTlOdjZfM2QzeGhMY3oybVZsS1A5UVBJR0plNm01NDY5YlFnWjJVNXQ5eFd4WGQ2UXNWT0NtSHM0TUxkU0U1YTY1Ul9xRkkwVGNuN1FlQnBSMlHSAcMBQVVfeXFMTVRJcHJmbjZBcmxUQlNzeHp0ZUhHbUMtUXhRS1JqUkN1aVY0UFprVzkzc2hlQXVWNmdod1htRUd4QmJXckFtLWVyTTZUVnA1Y0ZPWGEzSFBqQ2F6VjZqTEREdEhGQ21HOXVnRXRtblR3YmlWTkdIYW55NjViRW5rSjZheHNXTVhZZlBRNDAyYnRSUkFBYzVSWUhYZXJ5T0c5dVYxMGdGaHVmQ0RsZlJfU3NMZlQxVWJvN0lQOFlSd2pQUGIw?oc=5
panjang artikel: 7194

Fetch isi artikel:  12%|█▏        | 301/2473 [03:41<2:54:50,  4.83s/it]

Fetching link: https://news.google.com/rss/articles/CBMiywFBVV95cUxQREVXZkJFRGIzVTlkbEF0SEx4UXUtWDg3aXotdml2SVFLSzF4ZnZIUTQxM0xyQVdDLW9qV2lxYnR4cnlNc3ROYmRvMTQ0dWgxaUxkWHUwdjRDMjFYZkt3YU5Id0NGZWlHWUZWWC03dG1IcTNIcWlnSVlHMXRFUjdzOXJWMzM3TDJEX05jVVFPTGVLeEdjaWJSWVdPZ3ZDY1dHbzNuZEVjdU5fa3FkdG5MUU9ueFQwemlycWp2T2pKSU1KY2luQjYwZmpOc9IByAFBVV95cUxOYTEyczdENDNzdHFjTTdIOW1VbUVyRGZNVEdWNHRvNlZPTDlFX0hQOUxmdkNTSWdIQ0VsUGJXR21JTmJjMWY4VkVaLVNjR1A0S3ZVaVNaOEJMcWFKUWRHaHY2TXJ6bm5SUzlhMnFIUkJRNG1JRVdZYVJWRXByOTN2UFhmbnlNRVVjZG1sOTVsSDF0Y2xzcGxXcGFxR0FHNjNnQmpxQW5wRkF1V19hWUg2N3hzZ2V6b3lMOC1xT1hKZlFFR2Q4bHZiaA?oc=5
panjang artikel: 5594

Fetch isi artikel:  12%|█▏        | 302/2473 [03:46<3:00:48,  5.00s/it]

Fetching link: https://news.google.com/rss/articles/CBMiigFBVV95cUxQVkg5OHdMNW9ubFBZTUVLS0xSWUdyZU1feXE4TnU4MUJNcldTUlNMZVFMSDNTNDlxTTU4aExRRzRFcVhtSkV1bjdoazUtZWg0VWtFTFFtYWZuMjMxMTh0eUdsWEpINEZNb3pmM0g5WWcxOVBHc0FSaVFERjlkejU3eTlHbEZnMEo5dGc?oc=5
panjang artikel: 4226

Fetch isi artikel:  12%|█▏        | 303/2473 [03:50<2:48:43,  4.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMioAFBVV95cUxQNExFY3BtbkZfTDNaWU1vdU5kQjdtYVJFRHRiNkVMVUpWaXpHUTBQeW53VGFiZEd4cWMzZ091dzRkTFRkMDJnYkJUempIMHJuVlFYU3hOaWdlNkNOUHVhbzktZU8xb0tDWDlnQmdIa3hQbzVGNzZDYXVCWE1qU3dON3FaYkQ1SGxwbFpoWXZJcWxFdEJ1ck5LSWswTkxOd3RJ?oc=5
panjang artikel: 1759

Fetch isi artikel:  12%|█▏        | 304/2473 [03:54<2:38:18,  4.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxPcnJkYjRmNGltOVhLWW9mVldmRDJHZGoyZHAtTl9pTVBNZXBhNGthdGRHY0NvdDl0SnVBWlE2a3RJZnk2NFhFZEIwZHRZLTMwX3o1aUhkcUc1TTluV05VbXNiRnZuSEtTemd3TnVIdXZwQzJvMllHalVqaURGRzF1RHBrQXlqc1B3eVBIT0VDaXhzRDNvX1lZeW95eTJuQk1xcUFSR3JMVHU?oc=5
panjang artikel: 7775

Fetch isi artikel:  12%|█▏        | 305/2473 [04:02<3:15:16,  5.40s/it]

Fetching link: https://news.google.com/rss/articles/CBMiiAFBVV95cUxPUGMydVF3bndlLU1SSndTRzZBcjlLWmhpQ3F0M3ZNc0FIQXJXUmJnSHRTX3kxcjV3MnY1cUhnM0dZVDVBdXNJWXBuY3RlWmh6ZS05eEtkR05yVVJHckJHaUZWVS0wUnVQcUhzU25IcmN6U3hsd3B0enM0VERBRXAyQUprRFZKWDZf?oc=5
panjang artikel: 3808

Fetch isi artikel:  12%|█▏        | 306/2473 [04:06<2:59:08,  4.96s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxNYjNpQXA4MEVjQUVTXy1Tc0dUZXBRM0pJWUN1d3E2bS0zVFUtZ2FqT05sMEJWbWZuYzFpWVQ5c1ljYjNLYlI2X3Y4WkFac3VGNEg4NmsxWlB4bGE3OHFHZUJ1Wkx5TjVFbGtYVnhfaGtWWThqNDJnMV9yaEZqVWwxeHVnSEtaa3dDRWJZQjlYaWh5RDlnTUZ4TnYzLXZYbk9MMm42UW9kcEt3SFhDM25JQVlhZXRFbkR5R3ktMVJlT2tGQzA1bVhj0gHHAUFVX3lxTE9DM2d1SVNFTjZOOGdjekZJMTBuejBjVGhaTC0yQVhNRzBULUQ2c2FWS09YUk5CbWcxb3piQjhhSFBFUXREYUdrWnUyYjI3MU9xX25TOUpkcElkaWxkWWFEMFZpMk9MbHBTaFEzeWdxeF83MGg0Z0pFYzZPbU1YY2VFYVU5YVJMZEN1VDFXcW1fSzdHbWdaaFNWbXNWWVpmbW9CdG9EU3h0TG9KRmF2RmVIS09NXzh3M0VQVnJoUmJCOVFEM1I1c0k?oc=5
panjang artikel: 96

Fetch isi artikel:  12%|█▏        | 307/2473 [04:10<2:47:47,  4.65s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1AFBVV95cUxNTjRUcWoweUhPRnVkMkVVMmRZeHRmTV9PRkpReG8yMEtuUEN1TTBhN2lmWV9ZU0l6OXp5N0swWHF5Zld2R2sxam9Yc0NYd2tsbFphYnZKS1c3TXhqTGIwNC0ybWZfNTBLZGp2dDh3bWVHQmZBdjdCOVh0QlhHQ01wTWk0dGJXS2owbWxtVmE1dGEyQ1hsTlFyY0hKR1pWWEctcDFBOVY4OHpiMXM3V3gtX3RBTy1BcURiM1VkOTlwT0FVZ3BtSzJSbFM0bUFzeW83OGwtWQ?oc=5
panjang artikel: 432

Fetch isi artikel:  12%|█▏        | 308/2473 [04:16<3:02:37,  5.06s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxORnh0VTBwT0RaeTZ1a2UxRk80VUxXcUZuclFoZ0ktZE9QLXBkaUU1bHl4NzlNUEl5MndGSnRaWlJZU1VFTFBFcVVsY3k3aXpQVGVBcW0zSWRCWi1BQl9JT2x3Zk8tajloOWp3VVdtN2RBZTRzaEhCb2RrTHlLdHp5azlkYjZzUDVPeU5PeWJ2bGhYY1hNYW5nX3hNOG84QXk5cG5ndkdwaGkyR3B0SHJsTXNlSmhBanB5SzdKYTNLTQ?oc=5
panjang artikel: 2794

Fetch isi artikel:  12%|█▏        | 309/2473 [04:25<3:43:50,  6.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxOTDBBNUg1S3lTZzBVQkJmNU4zZGZ0cUVDbVpzYU1MaXdDWjBURU9uaGJhX053cnF4cGhndXJZcXVfNF8xSWszdk9PN1Y0d29xT2p0elllaklmTVE3bXV5dm1yVWxFbUE5Y0ZtWm9ETUdZQlMzbER0Q3RKLTZ5MEdWV05iTGoyaTV6aVVHVldNRXhSa0FXZ2lCY19MaE1JSVNXdFpZTXdkVDdOamYzWnhkeA?oc=5
panjang artikel: 961

Fetch isi artikel:  13%|█▎        | 310/2473 [04:29<3:22:59,  5.63s/it]

Fetching link: https://news.google.com/rss/articles/CBMilAFBVV95cUxPa2tQU203ZDllNmxuc2JMU3RlOFVqM3JvN2FTTzFNT1VNX2Y2TW96T1h6NXRMdGpiOGMtZ0YtWjBWWG1yeWZLRkNsV3ZNekd1dVI4X0FDU1pmRkpWNTUxb1RDeWt1ckxTNDFlb3Jqd1U5VnpHN04yVFpVYUZQdnpnZ2tWZjJTUllMbERqNnI0ak1GSHFB?oc=5
panjang artikel: 2246

Fetch isi artikel:  13%|█▎        | 311/2473 [04:33<3:01:23,  5.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxPeXRlQ0ZPX1VTTXBHME02cTk3cHJiNUNDS0k0OE9qaHpKTDVLVjR1NXNyM2dwVE5XWE1MamlVcUJpN0d1WWFPMEZxa2NxMGNDNDZXbFZQZnpRZ19LWUtsaHFvVkxVeEFLc25hYVp0b3o0R200MEEya3NITlRjMkN2QjJEN0lQQkFpWDl2TEZrc2d0M3VZU3pUVkxKYktYS1ZoUGdYQ29wMjJnS0N4V21NcVVrblh5TTZUZl96cS1QV3NGVDhuc2UzV0NhWm1YQzg?oc=5
panjang artikel: 6090

Fetch isi artikel:  13%|█▎        | 312/2473 [04:36<2:49:57,  4.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMidEFVX3lxTE9PN3llSmVydGx3MGllcEJVM2ZsWnBXVXRCbDBuMnhLc1hvUXJWU0ZXMW8xdXNMM2llVnEzY3E0a19Zdnk1WjdqNU91VE8xWjRqTWxNMGozMkRnU2I5eG93eWs0WkpCRENkM3NjSWdXMVltUEdW?oc=5
panjang artikel: 2472

Fetch isi artikel:  13%|█▎        | 313/2473 [04:41<2:42:18,  4.51s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxNeXdaaEtaT1ZFWEhnOHhGMjd3U1FuZjlsOFNfZWxOWTJEX095aVlaV2hjTktNdm5Ed0JoQUg2VklncERROVdLSVJEazFkVkpyRk52RV81ZXJ6RjlkdnBwV3NtRFdFaUlWaF9CSFp5NGtGU080QnoyWDhKd1BqVnZMbFJ4YkRRQ3UxNTNueXh6SFFsU3JRV2R1SGtZQVlTSEV2bEQzTnloclc4OG5OVlJ0SHJqeTV5dHM5cXN6MQ?oc=5
panjang artikel: 2748

Fetch isi artikel:  13%|█▎        | 314/2473 [04:44<2:36:29,  4.35s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxOdjFESnZlVzBmZzFuRnBibjdlSGh4RzQ5bDg2ak8wOUotVnhIcTF1anprdkhkX09VNzFMaWZrMlhFQW5kYnhnVjNTM2dSY1FwS1h5MHlmRFVDNzU2X3dFY1g1bHZnU0otdmRGVDQ4eEFYNVZGcldYcmhaSmFCNmx6ajJfdUhwS2x6UzV6azNOYXNiLVVkTlJ6U3FWOVVWQUdWX2N5R001bk5KTVI1RHFiLXJVcGRSVVFmQVRSejdjNA?oc=5
panjang artikel: 2511

Fetch isi artikel:  13%|█▎        | 315/2473 [04:48<2:29:17,  4.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxPbl9FV2hvcEpWWmhlQVFUX3Z1S0xHVmhBRVJkdlZjX1BCdi1wOHR0TkJGeUdyOTEyMTdCUWJ2c0NzbUJic20tYTRILXRxSm01SzNVZkV4UEtaNkhNcW5pMHBNYWkwMjlYT3VFQjV4aEpabFdfZjJ4S2ozZUg0R2RJRlFHUFhfZ2JBNFFINWxJYVpsMWd0S2xWdXY3Mi16UkJKY3hxMzV1LUNKclFlanFEakx6ZjZ0TEp2c2w2NGJ3SdIBqgFBVV95cUxOcGhnaXQzYUJjSWdyTUNtNUp5c1Z2RHRIU3ZMWnY0NXR3andGV1VwS3JMR3BySl9iVlZvNDVpU05rVkRyQV9DeFJ5MkZmTjZ1NExpbFZ2SlJxZkhJZzk0bXY0M1g4Qk1pMUk5RC0zVXpBTnhaMlY4MmlZcE1oZVZfRnp6OVptNjFleGUzUkowNXRXelJreWJ3Vzc2MUtLNnVkMDFidUZaczNKQQ?oc=5
panjang artikel: 2088

Fetch isi artikel:  13%|█▎        | 316/2473 [04:52<2:27:10,  4.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxOakdCSDZhajczY2xFUGNzN2NMeV9FR2pmTHVKbUVTWEFNODBoZ056WHhrOGlEb3Q0Z1UtU3VaME1fYzJQSWJQWEZEWTZJZUQ2ZXRKeU96bDItdUdkcU9Mb1hVOF9USkM4ZjByRHR5V0JscUZuRlMxSS1UN3NKVGdTZzBBZGo5QjVKeGgwTGVLNzRINGdjb2ZEbzE2WGtHMGtERVRfRnRwb2xEbXhLRVhycFBpdGFpaDTSAbwBQVVfeXFMTTAzd3hXRDBSTVdDdG4yVEstX0NjdG1SZ3RZVld5VmgwcnpuOFVxcEwwUm1RUzR3VlhTRXp1Z0k0SWxSWEItYklGVkp5UkpGTC1SMEJoZ2JTZUhpZm16bks2YUVqNUJacEdQX0RMTGFOUmVjZUZnbUVBT0hnTDg2SFBfdHJYaUZ1RWdnNlJpTHBycDhJUERVVDdkRk43UVNHWnowVm1nbDdsWjhjN3Bza2VKYjF3b2FRUGY1SVo?oc=5
panjang artikel: 3290

Fetch isi artikel:  13%|█▎        | 317/2473 [04:55<2:18:12,  3.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxQVzdfZmNLckRoUHlnMnprdFUybUU3b0R3VWh0Z0w3VkhqOUxucTF3ak1uMzZ5NjlOMWR6MV8zNkRKX0lDWGswb2xFRlRSaUhMUkplU2ZZOXJGT1pHMTVfcmtPS1MwNWVmVTlnQ1IwS2NuYXpnZlBhQ3VtLWt5OVZWSjB0SUI3emUxLUlINnFaOERGSGpRNDNzRk0wTTNKcVlrMm8xNmQtQmR4Y3RYbndwT1FVdGV2eVRsWk5XX3JROFAyYnB1VEp2RmNB?oc=5
panjang artikel: 5161

Fetch isi artikel:  13%|█▎        | 318/2473 [04:59<2:16:29,  3.80s/it]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxORTFfeFN1dGRwdTJqc1ppVnlobXRFNzdXOUhDUVBZRHRXREQyTjNyQmVNUUg3NkdFNFlVeGU3Z3lvUVVCRTczTzVfNlJzaWZDSzFpYThDX0Q5MHMtYVRiSWk1OEhYdldTbTE0N09Va2NIS3pBeEJCM3BpcU4xUU5WdndCSzJ4c2psckcxY1MxMU84cnhLZkkzYUV4US0?oc=5
panjang artikel: 2188

Fetch isi artikel:  13%|█▎        | 319/2473 [05:04<2:24:27,  4.02s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxOVVU0aW5BNFdrcENPcXp6R0M4SWpLUHhEQ0FjREdFNE1idHc0a2VQU1hYUXh6UXdxMERWMjNoM25JUXRGbTRjNlRhZHFOMTdYcTdjQThXbUdHc1M0QUJHc3RCVmFCaWlZaWcyVm9DRC1BaXU5cHFrM29LT1NiWm51ZjV6elEtNmZUbm5TTW5uRzFDSnRsdVJPbHFOZVdwU0owRlVaWWNCejdfaEpzaWl5TDZpN2ctZWxCVkHSAb8BQVVfeXFMT21WMmRCZmNyc2k3dFV1aVhOZDBBNHZHQk04eUd3cF9GR2lyZTN1dkpZOGdyNG80dWtDWUttcnpkNTdDeXZRYl9kMGRLSkhCQ0ZVTTRONUtYeWJpRTB6XzVuandTVTg4VVBDZ200TnpkdENCUU9EMjhEdXNHbUdFVmhqWER3UlFyd0Y0ZHVkWjFaU3plNEZyT19qQU1tNUM1SDFKeUpTQU56QmhlZjQwdUZUZm5wdkExZ1dxNmozZlE?oc=5
panjang artikel: 4494

Fetch isi artikel:  13%|█▎        | 320/2473 [05:07<2:21:14,  3.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxOXzJDdWlQcm0yU0k5QzZ4elk3Z3IwWUJNUUFadUJDUmQyN0lTV1FLdUdYd2FDWHVlLWpKTE9UQWdkQUhObXZ2NHUzVG1kVC1hTjZ3RFdLaW14cEVYQUZwR1pmNFBncXd3ZVc4ZW9haEEzYlJTU1c4eTRhdzJIX3lySW5TZDhIS2NWX3RtOHJKbkp0T05OYlRKY1UzOTVYS0Z6aUtvTnVXV2R1OWFnMHJRamt3ckIydDdRTXhyZlpPYmt6VjBkaV8tN1dn0gHPAUFVX3lxTE9CU1h0amoweS1uaVl6X2dFWlVmZmpnWUNqTFV0Z04xeGpfSDlqOU1wZW53amhXYjdremhQaHhNTkNlYVBMSWo3dnp1TG1TUDBTNTFZT3JSQVhMVmRpWXhzajBrbzdvc1JGRndjRWFaTmgzN1BXbTdOd29kalBNbURrYU5PcmRwTDNLZGlRZXVJUjhCZVNzSFdvNnBzRFZwQXNNazYtaTd2QmpsMEo0UFNwTUVuWDVEb2tWNE1BanB3cThqQnJlSjYxUi15NWtvcw?oc=5
panjang artikel: 5056

Fetch isi artikel:  13%|█▎        | 321/2473 [05:23<4:27:43,  7.46s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxNUkJ0WWNMYVBmdDNXd0pXMHpSNU5NTUVwb19VTGdqdTZGRGN6dzdoTDBtbWU2cnBXSkhORlFtZHZ0VThjdFJxcU5CSGp6c1ZXazVmaHYzZUN2aWU0bU9Kbms5ZjJtVnpLM1MzN1BMUEctWUZIWUVMVXl4SEhfY244UE85bkEwNGJpZkhfVFNxcHJYczJKRUJHX0NnV3VzR2ZVcTBCNV9CNTktNVFlZnhLQ0JEXzdNRXPSAbwBQVVfeXFMTlcwaThVSktmOVo2NEdMaEFqWkFyZnJXVHpTc1ROQ0dtOG1kSEZHT2daSFdDOWNlZ29PWG9IdVdZMnJRYS1mLVhjb3E2T0ZEYkJOU2VjSk1vZkZ6WTkwd05RQXA0Vl9mR19ZOUF2bl9xcnNCYi1xMWFUckpPT3J0Q1BMelFTNVJwSGo5WGV4NE1yR003UXBra3I1dW5OUWZFeFZ2c0JUbVVLczhMNVZTd1V0aVRCVEIwTW9oT3k?oc=5
panjang artikel: 6889

Fetch isi artikel:  13%|█▎        | 322/2473 [05:31<4:34:13,  7.65s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxOdzVSeC05d2FjOGxMakpKWENuNG1vdlAzNDVCZ0JnSjJFQ0JBc3VwZmR6NTFEWWwyS1g1ODhNOWRQanFtMF9mS0s2OENDd0dBclMyV0RSSURJR1h2aG1xVzkwSWwxZWVpU09xaW1qaFN1cWFCUUppQ2hQTFZDMkN3Qll1Ri1ZY3RfNjlMSi1sZExHam5zTG95VFZEcUJpZG1GQml0VW1pYWV1SGhBY0RrVm9jM2VWQnVpaUNNRDdyLUQ?oc=5
panjang artikel: 3193

Fetch isi artikel:  13%|█▎        | 323/2473 [05:36<4:00:43,  6.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2gFBVV95cUxQQUJDNEsyMDlNQnphU3Q4cmlXN0tMV21TZFdqcWJmSDZ0Y3ZBb21iTnFfanlwSjFUdGVFdU9EaC1MNEtHb0VlQTJNWjdDbHRsaGRtZWg0RlpfTW4xU2NmcGtqUlh5RzgtckpZeUltT3Q2MkItZjdleUZYdjl3cDF1Zl8yaF9YTDRzYThKaHRpNG92QWdubVN6RTI3bi1oeUhNM2pUNFFmYnVqQlBXVy16R1E0VEpUS25wOEJiZVhEVXEyc19UQkpHYlNwaVZBRl91TUdvdURvaUpPUdIB3wFBVV95cUxQN1NiT1ItYWhQRzVDaG1OZFBYdVlYSmwydG1uTFh1X0o3Nzh0cGJKTXdERjlvNzFrWWl3bGdwTUZsdS01elh2XzZGbGFMOE9fQVQtX1dGUUxoWC04VS1idUQzbThSRFVNQmdja0VQYzZuNEx6cy1jTHRZZ0tUbWp6TU9fUGhfQ3FyQ3BCS2EtakRRbmVsQTZJLTYyN2Z2cGEyUTRnOUNuRDdmRjJMWGlsT2N4ME1yZERFRFBCbUN3SHBhcHA2VDFsNk80dTdaZW01TmM2TWRPNjRRdkdheVY4?oc=5
panjang artikel: 98

Fetch isi artikel:  13%|█▎        | 324/2473 [05:40<3:29:26,  5.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxNOTBkTGdWUE1sWldlMURIZ3kyR29rUHE0MkhSRkJpQ3F5dDFjVW1nTkQwOGdsSTB0UHhGaGZDQ015bmI2aHE0SERlLU5sVzlSQUtZXzRpZ29KVGxDQW9PX2VfamVhZGtaeTZTbzVRWkdRODAwc0FDeGVGYnhPQWdNLVVmdXlxR2VMT3VTMktQbnZGTlM3cUl0dVVnVnBQdjBsNkNJV3JBM2hPUzNMSW9CcFdYcjVvaEtDaVhCd29n0gHDAUFVX3lxTE5kV01nOFg4SXA0Q2hEbGhHNDdJd2ZWWVAxbXJQWVY2M25TS05ucjNGSWpybURndkFOUWEwdXQ1QWVPQ0NDYlpILVVnUXJyZy1sSUtHT0ZfZnJqOUstQTgxSWpfa3BnZ0tDUnZBZlBVNGZlcEVFQ0R3VmVjRmNSVnpvTngwSkRPbDM5enc1VXdxSEhkeDduTEhyUDQ2UVdXb0xXQVAweHJFUWVzZDRqdG5hRFp1Vjkwd3lZZkpfUUxFNnBNZw?oc=5
panjang artikel: 1896

Fetch isi artikel:  13%|█▎        | 325/2473 [05:44<3:10:23,  5.32s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3AFBVV95cUxOR091U1JpcmtlVFBXbmw0NEM0LXhKQlBFWG53dk5iOEVYbHp6Umd6WEJxczhva09tOFZ5MVJRdm1HNTBpbmw5Y0phYzJXWDR3emdwNUVMQmZVMFZlM2ktLUdBWS1pOWZKeUgzdXkwNnZvMHNFQ1ltZUpPOXJYS2R1azlLY1E4eVVPczRPY3ZoaGctY29NQnU0VGR0ajRWZGFEZzlFM0xpdzU5cFd3Q2RkQVRxQ0NMWWpOWUZqa2NoTmdqMGR5eGZEMXN0dDVFNVMySjYtZkhvUzVxWE92?oc=5
panjang artikel: 0

Fetch isi artikel:  13%|█▎        | 326/2473 [05:47<2:48:47,  4.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxPNGtoVWxSRmVGc3h1S0drdnU2LUpSRlZTOHU3VU9ScVF1TjlYRWdvM3JKVkpyNzZqTWtUU1NoRzQxbVJ6UTJ6VmU5Zm53TEkwOEJNTGpLa2xRMEg5RXNRZkszOFJ4WkVmekVSZEs2amxCaXZCQW9lNUQ0VV9TWWxBVXRqZ0pORzI0MGVHcFJSNnUycjlCVnh5amdpQWRya0tlbVYyLWdLMFUzNkYwWnpPYWZ5T3dtWGZnT1lSQUcxUkVESzg?oc=5
panjang artikel: 3170

Fetch isi artikel:  13%|█▎        | 327/2473 [05:51<2:39:13,  4.45s/it]

Fetching link: https://news.google.com/rss/articles/CBMi_wFBVV95cUxQUmtwandhOUc4MTFZcWJMOEYxX0pGUldSS2Vocnhza1h4TFZzRHZhdXR1MXhBWDYwUEVDREdwanQ5LXNlX3JlRjNCNG9PY2hqWjl3OVVfa1FkeXZGY2xERG9aWDBRZllyNC1QSGZ0cXh6WTJBYWJwOHdhclVWY3NRd2RJWFUwOE4yWjhFbHNBa3VGQ1k3MDFjOXZQbUpUZ2xSWEVQdHR6Ynk1cE1Qckk5MDY1MG1pQW9YM1p0LTU4NGdVWmd2Qk5fTE9LY09oRXQxTFNHYXlEaURWZzJVcjNyRDVDbXdaejBLVXVEN3phZEwzbTlEY05rOTRxamRNTTjSAYQCQVVfeXFMT2hoOW55NkVGZXpaeWN3c2cyZlJPSDdONXVwcHlPMlh6TU55ZWJEVmF3Z3dpZ0otd0xDbnZNMllxdk44UHluWV92VlhkZnBLV1N0Y2VXZi10YUVlSnFUT05WY2lyR0FLcTlPamhHX1p6LWtIMHg4LUhuLVRIdGdYVW5YTDZnZEg3eFUxSDI3bnZBQ09MNmRZTnBKdnRPQ3hyNHRWWGxrV3dLOVNId3czRnhRSU5jSnVhRWZvQjk4ZEJkeFdSR2R6X1NTSy1meVp0WS13TV8xQXZvUmFsWjdhVDV3U01oRWxCM0VOZ1ljOWQtaE91bkJPMzBqRllMaFByOFlWSDU?oc=5
panjang artikel: 110

Fetch isi artikel:  13%|█▎        | 328/2473 [05:54<2:31:39,  4.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxNZEZSVE1VWGZIYnhMQnhBN0JxT0tyQk9kUUVTbkxNUmphV1lUM2phcEJSbzNxTU1oX0MtaUxldWptYjlPRTcxV3VqcDNDNHIwZ0ZlWG5DZ3BTRU9xaXR6V1RiNG5tNWpnamVQSHZhaW5KYnR6OWNUXzNMT0RJTndVZ1VVQzhQNVA2ckphaU5uZ1ZoUTI3OXVTSzZxZFJwbTdhWTh0UUVEOUZRMEFYZHgxQk9qbkNqQXZPc0w2UNIBwgFBVV95cUxPOEYxeDk1a1BLeG10WHpfZjdaUlNIVEJXOFgzem01cm5ac2ZrVk13YVJkWW40QXh1cmpQN25JTnZqYkk0VXRURThMeEJpbm96ZUxCVllldUtJeUt0TkZoUDFPSHRJdnd3Yk1KdF82NlhDZjJkSGdqYjlvVTFWZTVDN3RpY2hoSTg4LU04R2dVS3BmZ3R3Q1U0WFBYM0UtQ0dwSV9VN0kzR0xQSXhTTTRJaDVQX3BTamdCWVdOM2tzeUFtZw?oc=5
panjang artikel: 2634

Fetch isi artikel:  13%|█▎        | 329/2473 [05:58<2:24:32,  4.04s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxPc2FnVEV5RmMzb1dGbG9YTGZ6dTIzSUtEUUk3MWdxQjhGWWtrY3BQUjBIQWNKenlBelpHcnJ0VlV2ZzBLWTRPOWg0b190WVdMSHFDX2tuX0V1bjFtQ3BsZF83S29jM0xvVDZxdmJfV2p4TjBwZHppTVZWdl9Pa1M5N1EwQWc1eHZPYzJUTC1WemhtcG5LV05XZUNvYlNxZ3VjcjBxWDdjc3l0cTFNM280a281Rkd0cmdFdkJidGZJYTDSAcYBQVVfeXFMTkFCME1DWV84bkZHOXdlSHNjOXhyR0l1UW9zZmw0MjRCVHpySGNjV0swRXQ5REl3eHVxT2MtLXBoMmNIb2VQdEpoMDNnU2hGSm9qLV9kaGREcVpqRkRlTERkWjV3d2JjcVVlUjlxSzgzclhPZXNzMERmbkxFRHRsSi1mSjFwR3hkZ3BlWUdKWmhoWWJDbFdjQVRxaDRDcTNzM0w5aVN6OHh4UUxXZWxTaXZYU2N5X2wzeDNNbDlKN0loWXQ5Q05B?oc=5
panjang artikel: 1742

Fetch isi artikel:  13%|█▎        | 330/2473 [06:02<2:20:18,  3.93s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxNV3MyQXZkcnpuRVgtZ0Z2QVNMelJwTHRHWnZMcGZ6RmV4NkhJQmQ5cnVtWVVTYmVSSW9UZFZJQ203VHpYRVJnaUN4anFjRVozZjBtcTZEeU9PNkJ0V0pRdkNGWEwxS0Z4TUFNNklRdHlCaGF4Q2lpdVJXeGlTeHZwN0xMTGxDMmdMUTZQNEE2YloyUlpUUzJzR2x4Q0Z0T0NWX1lQbURSTmMzZ1EtcUJkZ0FUTnd2WTBlenpoNWpPT21PRnfSAcgBQVVfeXFMTVE3cGw1ZHhGaDdWQXdHXzlELXJ6VW80Y1NvZ3ZiZTlNcFJPODNMamgySmliM3RtTVZHejc4anZ4dGQ1QkVCTmt6RzF3THlEanlMU3lCa25ndXQ3TEdsbjB0MlZTd1VRR1VFZ0xTTW5xUVhSdHIyVG45TGdMZmJKdGYyM1o0bm1wMmpEcnFQYm5aZmlHVEY0OS1mUV96X09KZWd0SkYxNXFOWThNVHJ4WktJT0NvZGVJbXNxWGM0OENnR1l5RWV4azA?oc=5
panjang artikel: 2392

Fetch isi artikel:  13%|█▎        | 331/2473 [06:06<2:18:45,  3.89s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3AFBVV95cUxQd1Z4NUxrSXZ3SlVHVnU1TnZ4RmJ6UTQ4a1BveW1YWWM1SlNra2dpZTBuZGNiclFYM1BFSTFRa1B5cFhvQ2hlN09nQ1JBUXZZbmNEMXc3aVVQWjVpaml5NWZ1aFA5VFJvZjZ0ejRRSXZaM004SEpkRjkyZE1wb3N2Tm5tTERWY3dFdG9vTm1OdUlma1oxZnFYSFlpdGJYd0xjSUpoQklpc0xublNiOWc0YkZHNVdwY0ZIX2pzQkxqb2ZOS09DTWIxcDhKN1JiQktha2FwMFR3ZjFNSWpt?oc=5
panjang artikel: 0

Fetch isi artikel:  13%|█▎        | 332/2473 [06:10<2:19:45,  3.92s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxPY3dqcEV4bzMyUjNMaUREb2c3b2NON2hEZnZaMHM1SWFOVkgxTlo5WTVzZXNJNGxJZ0gwWkVQb05ITmsyVDFscHFpVEhSZXBXUVZkbHJRWC1WdC1fZTRmYTFzRnJScFZabjNmYm9fSjBMVTBlRldGWHpzc2h5SEJHMzgxaFdCRnA4YkpOOUkxdDBSdjBuUE1ra3VfQ2FXNUNZM0tKRmpIekdTdGlSZVgzOWE2eTBXd9IBuwFBVV95cUxOVUhFOFJOa0lZRjdtWDlnalpnTjVjUXd5d2FNclo1dzZjTEp6N01ReWd6NldhdjBQVFdyUDFDdWFFUy1fQWI0YnhSOHN6aWh6UkRWQ3VrOGMtdlJ5eVk0MXdOR2hIWGFQSDFReWVXZDFyenF3YjdGaDcwWlRYVW1mRVdoeUNYWDMzdi1wWUcydkJ4YnpjeW9peW8zX0ZVVzZZOTRpWVkxcDdJMEsxMExrSnREZENkbmhhMWZR?oc=5
panjang artikel: 1221

Fetch isi artikel:  13%|█▎        | 333/2473 [06:13<2:13:33,  3.74s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxPRC1GSGljbW9RZ3ZZMklqTFBOaEpxVVIxV1ZqVXY4Rmdfb0VPZGpWVFZvMm9ldzJiMHFlaXVka3NVRVNqX0R6c2xoZkMtVFhKQ1dsd19JdkluOEJ0Mk9mbEtwejIzeWJTekdUZHV3Z0x1Y095V2VPeUY3bnpERVdRUmRSTUpYbklBeGhiTXJEbzFpWVhFRTZwV3VOODNobnB2c0RMSGJDdFcxRmdaTHd0QldjUGxyZ3RGek5KOGd0LWtTTFNJQVE?oc=5
panjang artikel: 2204

Fetch isi artikel:  14%|█▎        | 334/2473 [06:17<2:16:28,  3.83s/it]

Fetching link: https://news.google.com/rss/articles/CBMif0FVX3lxTE9YUWpzajBzZHh6bTBXc21BblVCMmZCc1pVMDBTbE5pN2tYdGk4bExKVDNTV0I0MHlLZ1VudzBvWTZVc0tua0VNWVo1TzFRUlJvanpqSzk5aXVZZXNNd3BJVjVNSVg3M3FmZVpNZ1R5aGJTM2Z1MmRVMi1tOWdhMVk?oc=5
panjang artikel: 4965

Fetch isi artikel:  14%|█▎        | 335/2473 [06:22<2:31:55,  4.26s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1gFBVV95cUxNNFdUekRNS004eUFTQzFoNk9wSFRCTlFXd1BVWHpSX0dEOE1uNDRPUEhVUTBZSkk0OFJlenFpRkVsMWg4UC02dkxiTkVvZUl5cVhRVWI4d1NCZ2tOUUZvdUFiM0VmSHNQWFotaHY3NE8yS2RFaTdYN1loNHpEXzdVcW1BMWdEa2FWSHA5aFppMDFaWUlHSndTUWNKVWw2Si1ObW1kNnJrLURteWRzR0cwWDVycEkydThzMnVEQU5Ydjg4QjZoWUMxMnlEaGtucGIxV3N1VGdB0gHbAUFVX3lxTE1DbVljT3oyS0xkdW5hbURJUmxPdGlqYWdBU1RpTEVIRnNEQmE3R2h2OFRLaXZTTFJiMW9DQ0ZiRUYyYzdxYTYxMmtZVjVhRDdJczZxdEtBa0dsVGljWWNZZjhvajdPTHBZQnhGa2FIM0xKcTVnZEtHekRSMFQzQWwtb2kyVmtzY0NkZTUtRlBnVV9JcHI1YUtFVTk3ZGpJZFMwSE5lNDlYQ0tFaFhEdWk3Z044OGJLQjk0N25zcnVWZzhqRm96cERudDNqRHI4WS0wcklqSUJVVGMtcw?oc=5
panjang artikel: 170

Fetch isi artikel:  14%|█▎        | 336/2473 [06:26<2:26:36,  4.12s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxNNHhlV3VOWmQ2Tm9kSGhvTmM5UmdWZ3RpSEI0X01SY3NfSW1mMmRhSm42Sl9rWnIzTDAtbTBuSjlkZElxYVNSRHBPd1ZFeEgzZGFxWEJjcWltYjBlUGtwWG9xUmFvMFcwWFE5cFpCSnIxR3pKTmlIdG94SS1jbk1qNVVRQW9fNHU2Y0owOTRKSmF1V24tUWhqN3JuZ2kyTE9BQTZvMzNubWY4SDBPRUpIcG9IQ0hveXo3MGVUajdCYUZGTFJKMDV3OTJB0gHEAUFVX3lxTE9ETHRHbkpkTlVPemRFcWN3STFFRGVsbV9FbUM2ck5zc0pDa2JWSTdGNV9QMVNqeGxwLXNiYWVSZEZnbzQySk4xUWZPV3Q4bVRJNjN3Vms0SXNzblJfcngteElLbmdESkJSYkpFZldvUzZ3czJtS1Rnc1o2RW03VjF5bVBUZWRlX3pWNU11aHZOODZUSmxaSTQ0MG9uYmVuY2NfbDRFZzBRbGJFOWx3WldFekxTckh4M1dKamoxa2U2Mi1GRmI?oc=5
panjang artikel: 1979

Fetch isi artikel:  14%|█▎        | 337/2473 [06:29<2:20:06,  3.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3AFBVV95cUxNS0NQcURfOVRHY1hjNEJOUGZLQ3BpT2FtRXFGdlkzbFJmX3hBMmhaaXFkeEtPSmpMTkhDMC1kUjFhaEZNWVNmeTIxSFhrdG04UWFTSk9yN2NzeHh1bFhiczBmZERPNWI2dC1nYTBkZ3E4MnFibjdJTy0yLVB1VHBHLVhZektXM0hFY2xtTjBpVF9iSDVvaHJVNGxEQkJUcE8wRnlGdFZ5Wjh6ak81d2dialJHV0FxdjJUb1dtcVFRQXJoTDF5ekdKUEhlTmFzMEJmRmxGaWtyUVRIdVdE?oc=5
panjang artikel: 0

Fetch isi artikel:  14%|█▎        | 338/2473 [06:34<2:26:49,  4.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMikAFBVV95cUxQRUJ1dFpZbThKRGMwbEFROHI3M3B5TnlUMmxjc0dyUUl3d240X3NWeEJFQlhNZ25HNGxIbTN1TGZuRzhOcExtbVVHbXVwM1J4YmI0cmQwOC1jWnFMYVEyODAwNXVscmt1d0N1SVVPVmdzLXBFb0ItbFBHdmpxMllZeTFUQ1lxVnZxblNIT3BHOGzSAZYBQVVfeXFMTnJkTnNxU1pMOTdNUjJFOVc3Q3I5UmNpNU5DelJCZkxVbDJCMF80ZlRMaDZYVGJYbWlETUhzTlY0d3JQczZ6UXVhdVI2dFN0bkhBOV9EMWVzMmE2Y2hkOTVPYnE3eXlJZmpFa01EbmlxNXNVZzlUVGF1aXFvTjJJZGxHdmdvNEwwOWRtcEMwUnJkaFFDMUl3?oc=5
panjang artikel: 1321

Fetch isi artikel:  14%|█▎        | 339/2473 [06:45<3:38:18,  6.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMi4AFBVV95cUxNTjg2cVZ6NC1KTnVETUtOU3dyOS11YmVhZ01VRnNGRy1rRUtHTWpoZnNhMnRyaGNsMFhTTURXaWNGdVp6WUtMUVEtbmV3aGx0Z01zZWJUTDVVd2J2dzZkaUpTM1RCRGpYWEl2akRnMXprQkdBb3Y0bjVKcXpBR1hMNUVwV3pIR0tGUjlDTG5COTgyYXctTTZhY00xLVU1bTZaMGpkV2dCT1ptZkQzTm1MTHFfRDdNU2VJS1FJTlI4LXA5TFBaY19tWUNMMlpmM0E1T0x5VDlNaVR6SWtnR1Bxd9IB3wFBVV95cUxQZHZZQlFoUWFRZFBqRjVsWkUzMWEwZDY5dWpkMmFnLUhpa0I0d19QMXRfMWcyT0xSVXdwVzFaeTJEbUNXYjh4SVlaQ0NMUmhQbmV2ckEtOWdScjlGM3hXN0x6aXhfTVllV3hjWmxtRHI2X2syMVMtNW5XQkFXbkZSZzc5cVZ2T084b29LYzIzd1NraXdvVWtwcWZJWlJQemZvSTlYUGxFSmhDNEJBYTFnRkVWU2hibmtwa3RjQnhwdUl4a3N5bkFTWUNoM3Y2WVc0U3ZnSGR0bVZsSmRUd2xj?oc=5
panjang artikel: 1789

Fetch isi artikel:  14%|█▎        | 340/2473 [06:50<3:26:58,  5.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3AFBVV95cUxONzlMZVh5ZFE5dmtjVHowb2JjS2dSSkFQbWJ2SjBnZWFacTZ5WTQ3ZjhlZWJxeEFka0ZTTGFycVlYX05YNzRaamx3N3JmYjAtRTFGaGl4eVZRMzJJc2VvSTlCNkxRQ1dPc2ZkaUJyZ09yMDdPV1NXYlRoNUtRZWd0NmwwQUZPQzR5Y25XUTFDN1NwUzdyTUstcWtnbHJWZDBTX3JyYTg4WVh4LS12VUIxLVV2NHNFV3NVdEF4V29yWFFFTkpvRlZNZ3JCaEZXQkdmSzRDbjRsZHBYbnhp?oc=5
panjang artikel: 0

Fetch isi artikel:  14%|█▍        | 341/2473 [06:54<3:12:01,  5.40s/it]

Fetching link: https://news.google.com/rss/articles/CBMimwFBVV95cUxOUzRlUTVRWEdybjdfTVEyM0RLbndjQ3NTeFNWMUswbzRUb1d4LXBWaDRULWlkc2VmcVJNODJrZnBjR1BhWHZyZ3F6V29YeFV5dHFqS0tVR2VJaGpqR3NSMF82Wi1LYnZsQ3JBVlNZcHU3OU1WVnRCTl9jWExtS3VqaERTdjJlMHpxWUxPTzQxbVpJbHg0dmZiZDJ1a9IBoAFBVV95cUxNeHZkdE9LR29DNmlvSVQ4UE12dlFtWU5rM0lnTXlDWlNkM0tXUnUxS3diMnVGV2hkcmhWcjR3ai0wWUt2cHBlUTRPQnJsOEJHb1VMM0ZrUTBwNGw3V0FvdC1sZU5naElkREdyckwwZmg0MVZnYXF1SkZpVWUyRXVGYnRoNjhBVVZyTnJBUnZxZjNOQ3FfOUp2OUg5YzB1T2Nv?oc=5
panjang artikel: 1383

Fetch isi artikel:  14%|█▍        | 342/2473 [06:59<3:04:57,  5.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxPRkh1NmI3TTFoRDhOWnR2d0V0b1RvLV9nVjFrbENZYW5FN0ttMno3UXVaVWMzRWNqUnBNZXg1RWhkbVRiejdGM0pMTmVsekwtRjdDdFlWNkFlZmpNTWRlb0pIbm9fUjMzWm5ZSUhQU05LbWFMM1I4Mnl6NnZ6V2ZiSWFvMUM4cmREM1RhR29nSDFRMkM5VkMwcFNjRUNyakxOVHpORVVVTjJ1VFQ1dHBLcUMxMmtlYTFXTlRpTNIBwgFBVV95cUxOdDJhNllqSGVueDNFQnJ1VTNRbUxvODdlaU1pOTJIbzlQTVkwdWI1TDlrdjN6dExsZHl6d0M2aVZCdVprQWt6R0NqWkxqZ21jUlFoTm5uT2pMXzdpaWp2MmVtV19POTAzcG9nS1lKREFOcFBUVlNxb3MxZ1ZIRmdqcFp6UjdCbFhVOWtwSGVfQzFwYmZ6WjNWb0ZMeU5OZkxtTGd4eS1OX0k2RW8yLWk3YXhEYVBqazZUZkdERE9uT096QQ?oc=5
panjang artikel: 1743

Fetch isi artikel:  14%|█▍        | 343/2473 [07:03<2:55:57,  4.96s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxNYkVud3ZfQzBUZXNCZDU0MllYOEg5Q0pPNkhpMmxTcGlveW91a3Brc2hsQzdPRTdzbk5Xa3NndmlQTUFEZnlfdEx0cjM1SmxPaDJnRjdjQVhMZ25CR1JLX0hwd2RfQzF0MWp4eGlGZDE3cGZKR0tvaEF3MGVnbGRXSm1DZ25KTGxRWkIzQmJBX1hxdjg1WTd4clJ0TEYtdEJ6ZWQxWkhlVUQ1U2cwYVpoZUJhMlROX0NlQzZ1eGNfZTEzTVJPU2fSAcsBQVVfeXFMTUhGSDhuZjVwMEVrRUdGMmtINVBTVm9JWXpiZVRPNE9LNEFmRll6OUFzNFpsYTA1SEdFQW01c2RhMElpQ1FlWTd2SDd4Yll6bWttdExxTGdINlZCVFMyZlZEbjBSY2p4bVpWUV8tRjFReDdhZHVxQW9rNjYwcnRkQjFaUE9oUHk4WmV2dzhHRjZTVXl5YWhpLTNoUnhob3FJN3hzZnpSLThaMl84MFAycU5lNVNydWdUd0dkY19MOWlRbWRrY2w3QlF2SlE?oc=5
panjang artikel: 2717

Fetch isi artikel:  14%|█▍        | 344/2473 [07:08<2:48:58,  4.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1gFBVV95cUxQWnA1RlV5QmNyeHVySFBTX2hOUGJMWlFtdWJLOFlYNjdmLUppUy1KQ3FVM2xBT2Y4X1B0dlVOOXR3V2k3NUhJcFh0RzA2VW5FeGI3M29hSV8zcXhuMmRULTFPWlRlbUF0N0FibnNWWDdTdUM3VGRrNlg5Vnd1am1hNlJCbkhIaXNFeGhITnVvT3U3QXVmNzhKVVAxNVRTMkVib2NheW5UV1p2ZWtpSGhNNDF6RjFIYmFLeTFyLWd1WGFxLUZmaTNNVHVEczFWQjBVdEJDTTZB0gHUAUFVX3lxTE1OWGVjekFaTFVZMFQ4RDdTR1dCaHQ5V2hKYkNrOWtpX0s1ZGtnRmUwelpvNE1TYWppSHo4RFZTYUVjd2ttVWJpMzMxakVQRlZJc0NGZlhHQVNzd0FwemdtakRhTXBjMFYxaHJOV1RoSE5Scm9BZmF6Y1dNdFp1TUI5ZTZpNnJkZk4zdFI0QXVxSGtjNWFjU082N3RPSUFSUm16aHNZZnpoeUEySWxqejl1dEE5UHdiWXBVTnBRUVlyT2R3MFh5dWhSOEpQTkZlT1NzbVZB?oc=5
panjang artikel: 1071

Fetch isi artikel:  14%|█▍        | 345/2473 [07:12<2:39:29,  4.50s/it]

Fetching link: https://news.google.com/rss/articles/CBMingFBVV95cUxNVkRPQURRUFBhaGFQbGp4a3h0VUlSSno4dmJCTEZoWG92Mml0cEh4TnczbTd6QkxtczBsMWgwenJrQWNtQURSODExYVAzaEhxeWpuTV81bkdCZGcyUkpFX19UREJkY2E5Y3RUVk5OeWlRTzJyRVN3MkZEOFl5LUhpOFY0NFRSc3BTOHltTHpra1VCWVNOTVNXelNXT1Ztdw?oc=5
panjang artikel: 1473

Fetch isi artikel:  14%|█▍        | 346/2473 [07:19<3:07:17,  5.28s/it]

Fetching link: https://news.google.com/rss/articles/CBMiywFBVV95cUxOMlJuVmlzOHR0UV9JWjlnMFJhOFRWTzA0OE9Qbmxxc3IwalRMMTY0MWY5dTE4ZVFSLXNmRWtJakdBR19QaURmanNNVjl6SmQwLVp4TkdIT05WUkc2WktITkpsdkQyVWZaVVhRcjR0Z3pzSzhKSmg0eDJpeHd2cU42UVdoVllaMXE1bE9zYnRiaWdLd0FycXBjM09KWnUtQWNhaXJhVkhBVjBBUGh5Rlk0TW15c1lIVTNUclhpVVZNUXNLS0xkdHZKb3VaWdIB0AFBVV95cUxQTFJPaTJHWEJ6eE80SVhyR1ItenNWRlBVdzQ1RGFPR1U2YVFuSi1kNERIdHhLTXdabXo3OGVMYUV3LXpzU2RYLTBUdXdWNWVnMThZXzNmdkVWVUdLYXc0TXh3RjNXY3ZOMWw1NXdtcUlncXNKVlVMSXNnWnBCa1lpOHp6dWVyVmZtZ0JCSC1mcThlQURRWV9ERUhFc0R5WF94T1I3RFA3WTBVSmVEOVp0Y2FUd0sxS290QkJxQTlWa2paVXJ1d0x6QmNTQ0IyYzRB?oc=5
panjang artikel: 221

Fetch isi artikel:  14%|█▍        | 347/2473 [07:23<2:58:54,  5.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxPcmh0eXBLQTI1TXJPa2dhVGtOR05FenFNV0FDTGlFNzRnT1hvQlptUTh1c2dDdGdqUUJFR1NPUUp1VWFQTjBEaTlCdnBCQmlNZDVJNlBpSXJwd2VZWUhpWEFFNDZEd3dBZV9JaHJUODFwcmY1TVRackdJdGp4UXdoeWliUUNfOTAwOGFGdzU1a3Z6WWFKOFgwUFJEeXc5cTJHVXNhTVlFWUVPNEpOQmNCUUpULURRdTc2a0pXMkNR?oc=5
panjang artikel: 0

Fetch isi artikel:  14%|█▍        | 348/2473 [07:37<4:30:45,  7.64s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3gFBVV95cUxQa2x3UEZib3hpaXp2M2pkbGE3LWo5Wk43MjVGTk5Ba1J3Z2psbGh5RFBOdTRKUUlPbHlYakxicm9sOUtPVGZWWF9YWTBqblVaenY2R0xQWnVWNm5lLUVfUkFkeXl3RTNxcDRoOXRUdFVXVERLcXg5dnB3TXU2V3dKV3dFVGFmdWZRbjhwbGlpZ0N2OGcycVRBNlkyeml6N3Y1RWE5Vm1ELUZGdF9WLXVUS213bEdvemtWNUVzem9SMEcyc2ZxZ2RPakNCa2NKam1sUVJ4UVcwUUdlZkhKeWc?oc=5
panjang artikel: 154

Fetch isi artikel:  14%|█▍        | 349/2473 [07:41<3:48:37,  6.46s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxPUjVjem9vOFJMWTJmWm5QOTZ3S3FjbkhvSHdYNlVBU2ZYb1czeTBqZHpuMzh5aG8zMmtmNkZ6a3BEZVNvZ0t2NjdXZXNqRVVNckdKUVR1Ri1aaFhmaURlZ1RKOWhNejdJcnJYTjBWTjFlRDdZdjB5VkdHQ2JYQ1p1N3FWeGdnNFl5ZmlIRDRSQjZsQ2FuMmRWSkVxN0NWaDcxSjRVWFhGWWI4Rk9ROGJXbHY3OTF5b1BqMWwyLVFEQlQ3RExkWEc5dUszaWtwb0U?oc=5
panjang artikel: 4839

Fetch isi artikel:  14%|█▍        | 350/2473 [07:45<3:25:55,  5.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxPbjVvTkVwUmxIOFFwMXJyVHQ5OXlrQjh6QUNFUU5BVVpfemlvRWRZRGlCczZ6QWVMWVVfUkRvV2hQTy11Mk40ejZ6S19OXzBkRjJCVlFSdHV4VU01QnhELUxMOFdjOERWVmZabGhHdUVmZEpDaXY2UnlfdzFMb0h5VG4zbU1OVmpxYUMwV05oWFM2QW9obXZ2SERMekxRVXFpMGxaZVp6MA?oc=5
panjang artikel: 4611

Fetch isi artikel:  14%|█▍        | 351/2473 [07:49<3:07:21,  5.30s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxNRnIyaTRIaXhzMFZqWjcxaXpSWmY1QTkxNjZydGdwbjRRcnlRMVp5bW5Nb3V2aXNJemtYNWVDVEFBZFNNcXVpa3RpX05kNHBLZnZ2Z2ZobG9NelpyNjVVMmtONkNIV2w3X2dKVWU5V05xME1aSzhaTUdlamFBTXphMXJfcDNmVzZ2aDBfRENGeTk3a2pmQUExVk05RU5vbzlxdTBRcGRpNm1VWW1aeElSOTVFSkFlN0V5LWFhbUFQSVRWeW9pOUVuN0FR0gHPAUFVX3lxTE5QekkzUzN0aDFHd1g5QzZuY2J5cDZORFhtQXBrMGY5WVBWOVVhNWNiWlN0TnRHcDNGM0M0akJ5bkVUajQ2d0dXakxhSjZZLV9NWlNsTmkzUmMtWk9SdTk4RzdBODJiYWhscWhDdDg0amhwYXc4VDJRLS1WbzZuMjI4bENCcUJpSnNOVTdDRm5lekt4Tldzc2JOaDNveDBITlZFdFp4ZUl6WGtYbk9iS1JlU05uWFZ6REpXYU4zVHdiWEc1bHdxOTZMWkdrZTFyaw?oc=5
panjang artikel: 2268

Fetch isi artikel:  14%|█▍        | 352/2473 [07:56<3:20:33,  5.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxQR0tJT3F1Qjd1U3ZOaTBpbFQxQ0Q1b25raGJnRG56ZzdsNUV3elZUaTF2ekxJM2VYVnlnQ3BET2tvMnl6ZVd4Y2xzNGVILWhSVnREbkpSTUhGSEJUc3FzQ1c1c1R2bWJZZk9uei1haEkwbVVEOWVsT0ZvZ0hZbmh3NVdGdmFZcVZzdmVNZmZVUklsUzNUZU14UW5OcE9sbnZIb0E?oc=5
panjang artikel: 2225

Fetch isi artikel:  14%|█▍        | 353/2473 [07:59<2:57:59,  5.04s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxQeXJlTFNJcUExMmlMWWhGRkZuY1BLV3hXc3czOGFlMjFTU21VbThTZGlUMVRnanBSX3dFbzBEN1RMa0xVUTdHV2EzSXFocmdGQzVvdjNDektTdEctSEhQUHpHc0ozSzg2cVBndEZSZmp3VG1XTHdyRUNnZUFSUWtDQ3I1QUtwMUFNQmhBVU1hWUxuenRtUUE3U0xaeGJQSEhHVHFSX2p3MmFXSFE?oc=5
panjang artikel: 0

Fetch isi artikel:  14%|█▍        | 354/2473 [08:03<2:39:36,  4.52s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxPUEFwM3prYjBldUgwdGtIRm9UVXJERE1LdWwwNWlZNjVrSU12RUZTSUVRZWo5QklRUm44cUJ0Vmg5U0lpdDFYOHpDMHprdzNhRkpqbjY1N044amZTMUYyMV9GeTJ6aVozS214QVBkcHN2M2Rlazh6U2VtWXZ2WGx2ZThGM3h0Wk5YM2JwRTZkZkJkTlBTVlJDd2QyblljQnR0bFRzMmNMcVZ6QQ?oc=5
panjang artikel: 120

Fetch isi artikel:  14%|█▍        | 355/2473 [08:06<2:31:47,  4.30s/it]

Fetching link: https://news.google.com/rss/articles/CBMiyAFBVV95cUxPWGU3Vzl4TlJkd0NKeWRwZW9XM3pGQkptTTVyc1gycVJJbUZvWFItTk9hTTktenRhX2I3Z0RHSy1fVWxtM2ZDdjIwZnVKb1h0THRtZkhxbUIwRldjTWJIRjZfYnVVbkxTbUZ4alpUZ1hGcTM3SC0ybXRTNUNYYi1PT1NYRmp6WVhCNkY1RjlxYUlTU2JUb1BXVnFqM0hhbjlxakNnYlp4TVFmUkpEb3h3Vm11X1dnZW5MbW14QW1KbzFXYXhfUjBuRg?oc=5
panjang artikel: 6979

Fetch isi artikel:  14%|█▍        | 356/2473 [08:10<2:28:41,  4.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxOV1JEY1pxWDFIRnFBVG9laWhUQ21JV0FmZUk2YVJfdzN0RTJaTnVHQkZFZ3hBY2RNdzAwdG15RThDOFFKa3JmcTNGWTFXTTNOYjFYX1F2UENKUGFlYTUtcWVEZ2FGTGUwdjI1YWNKU0hnT3ZjeVY0Wm1Fci1FcWg3Wll5X3hQQVhfYzFpeUtpcEg2RnF2OWcxbmxNWGtIUExLdFY1b0Zla3gxZm1femd3MVh6QVFLZw?oc=5
panjang artikel: 3761

Fetch isi artikel:  14%|█▍        | 357/2473 [08:14<2:26:22,  4.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMimAFBVV95cUxPYmZvZlpPSzlYV3lzOTFUX2pCWW1OWEFLdFk5bEZyRVZPSmU3WFpTZXdLX0VKQ3NZdlFMSzNONTJST2tYOWJKSHBYRmNObk8tdl9JN19WbzR2akpKaTg1Z1NNTXZSTG5zd3A3UU8wcWhIQjZybzJpOXhySG02WEI5UTBFNnJfZmlQdm9wSFlqLXg1cGJfTHhESg?oc=5
panjang artikel: 3033

Fetch isi artikel:  14%|█▍        | 358/2473 [08:18<2:17:48,  3.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMijAFBVV95cUxNWWs0NnctYTBUcmo5MnVjc3lBeW81NS1NcDRkRl9UR3lsaWwxdFVaVnZFdnpJd1Mzdzg2dWxtbklDcTRNTzdlNUNkaU5VT3FOUmM2M1JIZk1NYVVGVEJqeE03RXlHY3k3dExPMVByWkRZOTJPRUFwMklyZ0c4b1V5aGo1ZEJ2dXVSSndWUg?oc=5
panjang artikel: 0

Fetch isi artikel:  15%|█▍        | 359/2473 [08:21<2:13:25,  3.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMimwFBVV95cUxNZzAyMUJzWHdkM0x0SkgzR1FtUUJOUEQxcFJKRlBFaFRrWUdxa002SnB2M0xEN2dKNFhEd0ZVMXFkNk9Dd3MxNEdPQ1g0ZXhwSTU1eUxKS3kwb29mQ0JWMzlFbEZveFpjNXVqRGxDN1FBa3M2S3BpZjVDTF9Od0hzS3EtbV95VUJRY296cmM2NDJ2UEVmeHFLRDJEcw?oc=5
panjang artikel: 3026

Fetch isi artikel:  15%|█▍        | 360/2473 [08:24<2:08:19,  3.64s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxNYWxNb21JaEM3MUhBVC1Oa3lwWS1EYkNfa2tzLVJjbVg5WDI4SzFmV0Faa1hVNzNaM2NuM0FMWU5KUXdCdEx1ZmFGcHVZeFhWUGVaZkN3REdRWVVuR19DTkJXdE1kRXVYQ1BJVjBvVTk5a1NXNFNNeF9scERBLU5pMGRWM2Q3a25pUlNsWTFJMTI4cTltNEFUY1lHX1V1bWJxdHFsdjFQc1ZwUGItQ3JnTUhRM1FWcHJkZTlPMjFiNTE3Rk3SAcgBQVVfeXFMTi1aNjFJYjNnZU04am5CWlRleHl3dG1jNGJUNUYzS0U0WWdkOHZJRXJUSU40SDE1Tzd0NkRMSmkxUlZiVlByWmkySWpNNzkyc0c4OWNudmFiRXR3cWp4dEZlejhDSjJSbmdKbHdZcjRjam5iaFQwMkRlRmdHYmM2NVpScmR5ZEFDX1d4WXhQU1dQaUFIamlqZkQwMkE5eFc3U20yLUo2c25JXzBWN1dDYmotUGRRakNhNG9pXzcxMWl1Mk5YM21pNEM?oc=5
panjang artikel: 2863

Fetch isi artikel:  15%|█▍        | 361/2473 [08:29<2:20:27,  3.99s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxQbS1NbkhRc2RILVJnSkhXRDNMamN6Y2hkRDhzOEJ6WkNmU2VxWHJTNU5KV3puSGJxa251LW1veXdQamlYcldyb2x2ei1zeHdMSkNjeXU1TUlVQk5qNzRwOWd6LVFlTl85cUpsVU4zbU5DVTlwbDlMM01LVHBFcl9uandXUC0wRFVfVVRHZE5jUWU3NmxaLUlkVGFWeU9za0xKTzlxS2VKbWhzRktEOF9CTWJn0gG3AUFVX3lxTFAyWmpQZmZZYVplc3lnZlk3bi12Q2RCNUZROExuWXNqbENqaWlZczlqM3RlMmMtQkNZRElsd1FUZUNOMmZDNzlmclNHVjVQd2VSRVNGZ29LVDZmTUVCanJ2eEIxVWlSMEFZU2ZjOFVZOHA1a1d4X1RGTUp4cG5qYVJjaE5kWElvVzZjbVVZbWIza24wQ09XV19OVEVyckhQZi1BMEtibmlQY0l2WnVvM2NQNDYwVWJUYw?oc=5
panjang artikel: 4032

Fetch isi artikel:  15%|█▍        | 362/2473 [08:33<2:17:25,  3.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxNNnhlVmY5LTBVSjdNeFFWUjFDVTdQMW9scE1MdWExcTFpV1lFZVBnZVZid01SZjB2Z1QxNkwycHZHQUhXT0hNanhQZXEtSlgzVlhCNGxRZURIeXRmQzMzeEMxOG9JVV9wVEEtNHl5SkRGTXhOTGFoMGs5cUp2XzdRSFJjeWxxcUFFcDktem9HMURpcjRVa3BXYWlQYlZkdzV3YldzZl83ZGZWQQ?oc=5
panjang artikel: 3084

Fetch isi artikel:  15%|█▍        | 363/2473 [08:39<2:35:36,  4.43s/it]

Fetching link: https://news.google.com/rss/articles/CBMilgFBVV95cUxOWkQ3cEFBZFA4NGNqRjk5WEVsb09rMW10d1JESm9kQWQ5LW9pb29KQkdfZ1JydWFlcHR4bkkxZHFxLV85MDZtRnh3QnpYMGhJZEFoVGJsVEJVVzItVXFsdDk1a3BaMEtFYjJFcW1lS2FlQnduWFBHNkRXZWZtbklKNjk4RjJUdmc1dGM2ekxRdU1ET0d0Q2c?oc=5
panjang artikel: 6932

Fetch isi artikel:  15%|█▍        | 364/2473 [08:42<2:27:11,  4.19s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxPQUt6QkgzQTNGd1JDQnMzeU9nU0ltVkJuSGZidGFhR1dXU3JMbkRlN2NheG0wTHl0LVFqNXNReUFuLU11NTlHbm1NSXhZbHdpMVdaeDdyc3VWR0dnaWRYVnk3M1doalo1Y0UzT3N5TXRxZnhGUXZSLVpNVU1Fa0xqNWV3RHI2bWpjdmpxQ0lFQkw1aFUtakNtdjRfbkwyaWM0UjZiY09TQmxoLS1vanR1a1FCbHRFY3lCb3VKMG9VdTJlVDFEZXc?oc=5
panjang artikel: 3546

Fetch isi artikel:  15%|█▍        | 365/2473 [08:47<2:32:00,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxPdmFHWnlRWVpqVWVmSkNMenYtOHRpUDNLZHlMTnJkbG11bHFIUC0wQUgyY2tjUlQ1bjBzbTVlZTdiZDNPNHdTVC1EVGNoWU1OT1FabG9aNnh1T1NIYkNKSjI3dWZPbmlxTEtCbjUzYmc4X3NpMUNuM1RKZWYtM1IzcFVOUVBXMTRINHNITjJxVnNldndHZnV0X2lBT01CSWhOM2ZEMVhnWEhJY0RQejdZY2pPT1DSAboBQVVfeXFMTU93VWdNc09FS0g2MmpGMEk0N0FubVhLek5PNXVpMzJBU2J0TmctcXJYNWhNVUxxTFNLNTlNMVcyTzU0bm5sSnlYem5ka1dSQWJEQjlISVdUZndXRVplOWFGa0JoMzBTdFRyUlI4Y2dGakJWWXUxeDZ0UDhqVUdOaHQ5LTQ1WEhHRnUyVGM0S2dXNzNDemhHd0VYbzVWc0lMcnpYanJIY0oxTkZhU3FxME5kU1laRF9IdUVn?oc=5
panjang artikel: 2852

Fetch isi artikel:  15%|█▍        | 366/2473 [08:51<2:31:14,  4.31s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxNeUJBeVcwUDlMWFdlXzJuc0RTOW1OanZnVjFadTJBM05uVWxEd3hINHRGMG43NzI1VWtSNi0tUzBkYzhBZlRuMl9PQ2p5WlZOYnpBeUU0OXl3OEZVMVh0eG9tcFRYNFVQYU9iUlhSNmVtVmVUdFR5TUxjdlM4TklSemk3b0ZpdTRUZ0Ixdzl5V2NwR0RrTmEtUW5QemJEZnhsZ2tiQXBkeUQyN1piQVHSAbMBQVVfeXFMTjdMeXplcU5TeHJwb1FsNkRIbU5sOEtxUVhlZW1SNlN6TEY1aVA0bG9rMEZuR1BNcDhwb0lqOThtYm85R0lZcVBnaE5xYXg4OEdTOXF6QUZPVXFlQXc1NGxKTGV5cVd6OVN0WUZJejdndzRPSkhhUlZtbWR0Y1gzSHo4OXpORGtGRnM4LWJoQzVzc0JlSE1lS2VDWTJURGQzSW5udUhjSXp2aUswcWZLaEt2WmM?oc=5
panjang artikel: 5102

Fetch isi artikel:  15%|█▍        | 367/2473 [08:57<2:46:05,  4.73s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxOUVhBNWdjTWlyejlaNTJHY3BRQjZ4WWpfQlZ0RS1JMlJNUWNpbU1CNE9KSVBoNmd5VTRsN2RwbjNEM1hHU3RId0tzQm41bnJ1LTJCUGVvVlNOVHhaMTdYRU9zamJnYkxtX25ZYWYtQ2x2Nmc2b3ZCZUd1bUFFcGdZamVIeHR3bmx6Ty1RS28zMUFtOEhxOThYdzAtOEVlQU41OXRoc0l6Ukx5WDZyWlBBM25LOEk5RHlVcDAtUnhnZ9IBxAFBVV95cUxNQ203R3MtNGwzazdLQXlMaXl5MGg3Zk5mc2swWFFhYW9Tb21oUThYcjZSc1lFc0pXbHJWRzcxUDBSN1RxbUxCU0RfMnVRWXA2NGw5S1Z0U3prdkpRRTdzSHNCMFYwZ1V1UFhnTUcwMEI2QVZqb2xvWWlKdUJnSkNtcXBLRUIzaEljcGVSMExhYjV0TnV4RGdLemJfZk1tTnVub0tqWnI5RkowMXJfamt0dzhxM2hiSkFETUx1UnJkcWRwckdW?oc=5
panjang artikel: 1903

Fetch isi artikel:  15%|█▍        | 368/2473 [09:01<2:41:38,  4.61s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxOUnZPU0dYY05YWHhyOWN3N1E5UXdGb0YtLU1yRGJOMGM5QnNxOEtXWmlfVnJnTUV1ZGpXWU9UZ0YzR2ptUWxyV1Nad19MOGo0LUVBQW5sZXl4cW9HYXZxTlNoUTNoM3hQQ0FZMTI3b0tRV05scE9zNUg1eXJtMTN1VlNpMll5cFlrQmo5Z1g2QVZBQS1DMjRmamktTi1TeXVrYjlUeU1aTWJJVzZFNUo4a3ZPdzJoWEljM2haZk5YVGhNOVhMUERpMWlTbE9NdFRQ0gHPAUFVX3lxTE5QZGtuWXlueVZvbzQ0VFpseXNaX2ZLUDZhTU1GU2R6OGhsY3BWUnZFX1FoYjl6SFdKWFVEa0RPNENmUHRRMTVVNUR3Njl1Nm80aU5Qdkx6MDBKTTNaSjdHbGhYUi1nNzRGbGx4dEVtU2xIUkl0TS1td2NheHI1WXhZMWdBSkpKQVF4Rlp5c1NQZ2V1LTlpaWZYUFlEQXBZc3I5SzJUeVFROE9WN05TMldSU2FzanROSWt6ckN5MEdfMllyNTdlaW5pZ2ZSSFVDTQ?oc=5
panjang artikel: 1345

Fetch isi artikel:  15%|█▍        | 369/2473 [09:05<2:33:56,  4.39s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxQTzdYOWx0S2V0MWVmbGNuUVFzX2pzcE1ZZFpBWDlyajM2T05ZVVlzM0hUc1NYS0Yzc1REQVd2UDBsOXUtcnRuQlp5OVVCampYOG02cEcwY3JUUjFuLTk4N18zZ2dabXpnbXVTN1JlTzFFd3lKZ1FYRTM5NE03cmZWeUZyUXpPTk04bVBqMkhvV05qZkppWkFLTUJnM3BMREhIanZYbUhsVmtfdVFmM1R3?oc=5
panjang artikel: 0

Fetch isi artikel:  15%|█▍        | 370/2473 [09:09<2:24:13,  4.11s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxQdnFaMmJCdnF5T3RvRWJ5WkJ2aTl2RWNSYldIY1dBYVhvNE5HSEg3RFRES2Z5WFNqZVZJY2oxNjVWMWltaU5ld01xMGhXUGNsWk1taXowVjNtUWpzZEJxTVduWXBKd3JoR05NUVBOckxZTlZpTVZQeHk1T3EzTE9SRURwdGhjUEkzS1N6SVJ6X0JpTDdva3IzZWRWR0pZVG00bWVHeGVrODNFWS1JRmplM0hvczhMNnZIRWpUTmRtMklZZ9IBxwFBVV95cUxPYkNyeFh4TkJhTzJCMlVZc0wzbUJubWdFd1d6MkVJOXhLVE5ad2E4bS1BMWVoU0ZCSlhfdWp1N0t1Y0d1OEl4dFVxTENGZFlOT1dMLWZDWWJuekN5c3pfdHJBLXk0SUNISVpiM2NfcTlXbXI3c1FrYlF5d0NDUV96Z21DMFhvaTk0U1g0UURnOXhZbG9LYnEwblBJdDdCWVFRaHZBajktQV8ydWRNVldFYTIyYlRUbTJScHdHVWhlU2Q4bXhmSklz?oc=5
panjang artikel: 1823

Fetch isi artikel:  15%|█▌        | 371/2473 [09:12<2:19:48,  3.99s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1AFBVV95cUxPclBPQTJ6Tk1rZFBfbjdlakRCblZtQmlYQ3pSQWNFRXJDaUVleDRnX2xTN3R0SU95ajRNMWRNeTNta3cwM2paa2trQkU2aDgySG42UXc4V0ZacFNycUV0Q1dIcDF2d0NVUjBaZzRETlpHekprdjBSMmZIWkEwY3hLalFRZXUyMS1lT0gtR194TVR4dlVjWEZZUFVRd1o3UWFRZ3JkcWxMMWFjVkR5dUUyZkxSYkRZYTB3R2QyeDNUSGZfWXlEZzVTY3ViZW1VeFBUQU5ORtIBxgFBVV95cUxOOWVGTDR2a0JUcjBnTnZ5UTYwOUVrei04YVVSbUU2MHBBNEY3dC1VNzZZYlllUVVrNEY1YzNibjJoejFxWUJjSWh5Z0x1SThTOEcxdGVQM2IyZWpBVHp1WUljbTVMWUsxUGZ4OVRieEp5aGxSd214cDNYcDJPbGZvVk1DVm9vd1EtVTliRUhuUGhVSDQ4Z2htN3JQVXlMVldUSzFmbFJkWnpqSGUwODFDUF9LRThEVnItT2p6d2FUWGhxSU5pd1E?oc=5
panjang artikel: 2055

Fetch isi artikel:  15%|█▌        | 372/2473 [09:16<2:21:02,  4.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxPMWQ3WWZEdk80Qjc0ZThfZG9GaTc3emFVRVFqeEpVanRSLVVlWlkwUTh5WllDcDI5cUxJZUhDYk9FQlVUeG9JWWNlVXRwSHF2SG1ORHA2bmRLRmZIeC1kUHFNRnJSbDBYRHlPa0pIU1JkSVRaR3BQMTRHX0tVVFIwTDdNcW8tbWZHdm5ucFQ4NXZ5U3VyazhqMkZmUlNyOUZaVHhLSUlVTk00VFRibmhFc3BHVXbSAboBQVVfeXFMT2poaU9EaFhabTMyd2gyVENjeVlHX3djQk1wU0M0aVNsdjlrOEhadkJELVhJODM1SVVWaUgwWUNEbFpRaFUwYU03V0ZLY0pULUU1NU5Vb3ZCbjVfVzdqMFNtNXp0QmF0b2tWWTIxclFRb2ZpaGNiS0xxWjNYdHRQNGZBSVdoZXBRUHhRbGVKMDN3NkNFSHkyYkRBWV9jV1k1YVNnQndTeXBteDQ2NXVPTUFhTXJVNFhLYzJn?oc=5
panjang artikel: 2855

Fetch isi artikel:  15%|█▌        | 373/2473 [09:20<2:14:17,  3.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxNczJ1ZWxoenQzQkNLdmNRWWxCTWMxeWQ0dWd3c1lRblJ4MndsMzNtNk9tMEZ5bzFQUldFZ2pVaUZjVUZZb0FRaWRnc0x4VzRXQUY0X05QeUlTM1c5SEhLZUptaVBUV3dnMHRtVkJkLTI0ZTlxZFFUZm5ZSmRsc2M2ZEFnQmY2czd2c1BCR2ZjMFA2RTc5RTRxeExjMnlsbUlJT3VodE5BQjFSZ1HSAbABQVVfeXFMTVZwYUhPekQ4SzJuYjM0VkdseXpucUpGU1NJODhfTDdaeW1SSGV4VEdZTVdlRVRoMDhXRVBfd05FX05yNnFBYzA4eHVyMi0zc2hhTVhJLXdJSWkwbDJOZlNXZXl4cHU1ejI4N2I1NXVZSW11ZlR0Sm1CUURTb0VqQTBXRm1QYmlvaHVnNnpHX1hjckc1N0t1SHk4dHFSbE5zdXhiM2lpYzNDY1hPSFNGRzY?oc=5
panjang artikel: 2506

Fetch isi artikel:  15%|█▌        | 374/2473 [09:23<2:10:34,  3.73s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxPMm0ycnJoY2lhN3ZPLW05Z2x1OWdxVmxZNmk2Ym1Cc2Z0Zll0RWFld0tmYldqdDBBY1lBbDZ1QjIzbG5SVFA5Qy1NM2NjRExUTXc3Z0pkZllhLWUxVlc1ZnQwNGhYOGxrVmw2MzBybVJueU50SzJDWjdrcUZhM0RRcEpVVUpJOExnbUN6TWlYVUxMdS13ZjBjQThSVEhaZURvVEdKZEdMNjFqUHJXRkMxLVQ5cTN3Uk3SAb8BQVVfeXFMUDlyRTl5bTM4MHR0Vzd4VzkwaGZheU9QMnplSTZ0cXJhX0FhZXdFSjlIZndaMWNDRWdfOHNDR1hlanVEdTNIYjFqQjFxN04wNUl1bjlxWFhIRmhMWHJCY1RDaEwwNzhaa3E5WUZTanMyUEszZl9uS3p1Ykl6aVNBeHJFX3VYb2x3M0F6ZTdWaTlXZ1p4N3FTM1hBSFE0d2RBSVZDVjZ6U3lZQWVOTTBRenBFbGY2M2dIcTEyeXhPOG8?oc=5
panjang artikel: 2637

Fetch isi artikel:  15%|█▌        | 375/2473 [09:27<2:08:57,  3.69s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxPWlB3TUJPU2trNTM2cHA0UGEwRjU5R0hJYzBIcmJGMXFoTXBMRUVMRE5QYmZMcXd4Q2lqUVhhUnNWT1VlTzRLZG5rZDFibm9ueU9vN3phVEhucldudkJ0YjV3WXpzRDZ0Nm9ESDBfc1hoMXpwTFpKS3pWZl9uc0lSeXFJYUhCM3gyZWY4TkV4WmwwdHNQcGNiS0F2TzdsbVBSR2R4aGJFM3B3SWk0azhLMkh1OWNPY0hLOGsxWF9UTzZuR2M?oc=5
panjang artikel: 3667

Fetch isi artikel:  15%|█▌        | 376/2473 [09:31<2:09:09,  3.70s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxQWGFwNnpzTWx5Q2FwOXZWMHdDZjBicXU0Ry03Z1FNYWt0Z0xwb2xEcVJfSkNQb2h3ZnRVTTk1V3FXTG1MVDQ0M2hQN21rQmt4aHdERkFVWWRWUkdQMHItSVpORTBBLTVhMTlEUjNQYVI4blprS0V4ZFJiODMtQ2xxdG5HT1VjeXZJRVZkZVRZTFVZOWg0MmRKT0lKZV9KWnpsQ3RXczdzYnFBOUt3d3ZhTW5n0gGyAUFVX3lxTE1oNVZGcERwRU9pOHpVbWh1dzJXcDZ5OXFHamcwVTNYcHc1d25temNHNWNCN1lUNjQ3c24zcUg3bDZuSk9EbHlibUZQNGVoOUZqTFRTWmlEaUFpbFVyR2RvMHZwT2d2N21ONG5pVVBiRlVSUTQ4M3lvNC1aeDl4STN2WFRKcXJoWm41aHdON19nQ0hqZjVLSHBOdDhoVGZfMDBQdUstSzI2MFoxQXVOQms5X1E?oc=5
panjang artikel: 170

Fetch isi artikel:  15%|█▌        | 377/2473 [09:34<2:10:17,  3.73s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxQVl9KelRvZFZEelpHQXFZRnN4S2tNSE5sQlpnQUVfZHRFY0JfZmp4dVQzMnptOTZuLW44R2xZQUlDUkJrT2hzYkcwa05DZElBSElUNDZhSmNYY05GV3E0cVFlaVNucENOQVZGQWJzTUdOaXh2STEzSEFxQ2JXenZoUjZkcXlmVldHT0NDYTZKTV82S2ZJQmkxUmh6MUZGN2Nqcm5rQXhJdWRfS1HSAbABQVVfeXFMTTZIU2Z2Tm91VFRuOWt5QmdCei1xUHJDZGtJZE1GYmZnb2VKcnk4d2hta0dJZFo4N0NFSXF2WW83TDBqOTdYOW1RWDVFeDliWWlNaEVnODNGZXExTWwybEZKZDA4NWpRMzlNbzdkOFdjVms4WGtJWkx5OXVEZ0dhWTU4d2xGYmZfaXFyVHk1bTJxbExwM1ZNYTBkeDFnQkd2S0V4OEtUUnBDRjU4SEQ0enQ?oc=5
panjang artikel: 2299

Fetch isi artikel:  15%|█▌        | 378/2473 [09:38<2:11:22,  3.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMiYEFVX3lxTFAtbEswRk5VZVdjck5jY1NqZjBnX1MtODFuUTVCeHBxbHREaW5YT2hua0Z3Z0VGYlVRd1o2MjVfd2p6SHQ4dm1kNVRJZXdjMmZjb0ZpT3hfX0hqNXpyWHktRtIBZkFVX3lxTFAzTC1qQ2hZbWhBcnJkQUtYVENGN3VRd1RiTTNjQmRsRHR1dWtOZlpsVWFVVHBLOF9Tbm03UVZDdUpWRHFfcXhxYVJPWXhfQVBLSFlvRDBLZXNQaUQtNURNOUpYampRUQ?oc=5
panjang artikel: 16765

Fetch isi artikel:  15%|█▌        | 379/2473 [09:42<2:16:31,  3.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMijgFBVV95cUxOcTBVaDhFdDlVUkFGM1JhRUpVOEo2NDNPeWljWWl2ZjFnbHE1dTRBalp4WVNUWVBnZmVDQTRTMlBlYjZiTGhVQTNNOW5vRUVPS2ZlVDVWV0F3UkFHVThtR2dPZzk0STBpUUpxMllHV09tLWstMGdTekxNZWg4US1Oc1l1eVZJbFpqTldiNktn0gGWAUFVX3lxTE45aEU2VUVJLTM0Z2J5SW11VHBodmpxeWh0VEsyQzhWRTlUR2Z6aVBCVndIc3p4R3RaczcxeFVuMEVUWFlKSkhrem1WNl9ieVdxaV9CM0lHSG8tQ21wWTJiUUVXX2RoVHpRcXNpUEFadlRZb3ExZGd1RUF0Z2R5XzVXLXZobDZORXpuU21icjRPWTQwdHBPQQ?oc=5
panjang artikel: 6400

Fetch isi artikel:  15%|█▌        | 380/2473 [09:46<2:13:15,  3.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxPMjJxUzZjZmF3ajR4Q2UtQWtlQTk2Y25meEdtbHc3SXVqNkJlZUNUOERXQkg4NUx0TVM5b3JPNGxQX3pOdDdNa2ZsUjMwcDJpMjlNQmpaNjY2dVI0QmExM2t4MWJpRm5uSkNydnVKY2V1Rk1XTGRkX3JGNl9pWmJEbm5Jd0lVY2t5UGpQSFVZb25yem54YmkzSkl2MU9Sb0VxUTU2OHpjUmFTVjhKcThaVjZoTTJ1TmRHUGFLRNIBuAFBVV95cUxQNjVXaEd5MFJxWmpEQzUzRzVDcmNDMVJWeUo2eWdqN1ZOb1hCXzBuV0d5U05ZWWEzR0NYSFp1bDdEaWY1dnBlY05WUUx1d01kMmpvYzR6T0RXd29yNnYzenhVWldCaEZlODJZSzZhMkVVRGhQdUxldFoxd1lqY1IwcmFkZEZ5QjRURXhUWWdCOHpTTHVZbmpCVTBWWDhqMEg5UTYzTFFtUGVtODVrU2dveGU3NlZWSGFJ?oc=5
panjang artikel: 2237

Fetch isi artikel:  15%|█▌        | 381/2473 [09:52<2:38:14,  4.54s/it]

Fetching link: https://news.google.com/rss/articles/CBMiVkFVX3lxTE5YWXA2dUtDS0FkN2Zmb0Qwb2s5WjVTeHRoQ2M5N1JqejNkaEdBb2VaWWJ6c2w2X0tnbVJoNi1JOWNxbGJqNHNld21mVTloS2xvWE5DMERn?oc=5
panjang artikel: 9

Fetch isi artikel:  15%|█▌        | 382/2473 [09:56<2:30:13,  4.31s/it]

Fetching link: https://news.google.com/rss/articles/CBMiYEFVX3lxTE9oM3hFcjZWejhxQlRXQkYySm50enoyUFFxeDFuSUdsNkV5Vnl4aThxU0lfeUhYWEUwQkdXc2ZGRDVmeVFQYW11cFZfWEZmUVFseUVKNVQ1VTBkSXVTS1d6LdIBZkFVX3lxTFBKOHhDam5vVWRPcXVKZnBZM29pdVBfNkJGa2R1ejVCaHNUZ3FWT2h6TXhhN0ZZTEtvb3ZUREdWVkZUUnFNSDVQOHZOUjdHbjZtMG1WX1NzbHdackJzSm1hUjVWdXhFQQ?oc=5
panjang artikel: 13897

Fetch isi artikel:  15%|█▌        | 383/2473 [10:00<2:21:12,  4.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxOc2VHOURTbW1WcGdEbmY3dks2cVFjTjJCWElNT2ZqMWNpUWM3TzduUFJFSWlJTWtsVnk5MkRwNUJvaEU1cFlST09RLUowUU5lbmRIMjhULXVNS09YSnFSTDBidDdyMDFUdlR1RDZEVGZvSXJzOUZUaVdtRTVuRmV6akEzNEtpcWhQdWJoTWtoenlubG5yLUgxNmdpeFg5bWhXamZTS3RPWW5XNTRDamxZZU1KYWx1SXhKLVdfUE5RdmJBSEE3?oc=5
panjang artikel: 6166

Fetch isi artikel:  16%|█▌        | 384/2473 [10:03<2:18:27,  3.98s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxPMXRCZzhYaHg5QWU1bzdnSnV4QUNHSDFXcE1KUFlzeGNMU25MSU93X1Y2dGc5b2NIZjNNRFRCeTY3Q2xyVmh2Z1RRV1dRRGI0NjZZZmoweGE3UERUeVRqdjR5WG8zdXJZV2VPcW02U05jM3BJNnFOdXRxQWRRVEdackFHR1JDOGU4TC0ySlFwTmFkczlBTHp4UHZQcVZaOGNoaWdOVVFSNXoyb3VP0gGyAUFVX3lxTFBWZnhaUjduOGVSMG96UEVfcFE2Njc3XzhDMnJEc3lTdHZUOFFNdkhxWUw4alFMbHR4cnJJR0FCdHBnaEhPaENwV0k5QkJBZFBMTXBKOEk3UDgzUzhjOU84UXhMZ2RsU2l0RDNzQlNxSTZKc3p1VUFPR3BNeURfMDN5TTRXUWxxalhjNWxfUkZIdjV2OUQxSDd5RXJGSnVJd0ZDVlJ6dm8tc1RFM1VnYzdwQ1E?oc=5
panjang artikel: 1899

Fetch isi artikel:  16%|█▌        | 385/2473 [10:07<2:16:29,  3.92s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxOVDlGbUpVdXhZOXlfZkhtRmFZX1B5VFlPUVd4N2NZWjhmMDJoOEttcVlyTWJSbmZrTjhIRmxKLU5heElWa1Q3NnVYSVp5SnJOQWN6Zk1GTUVVV3FxYjZQVmlfSFo1MS0xOHlwZnJOUTB6Wm13TE5GS0x6RFlwV21Bc05SR3REYTJXOUVTenRhX1ptVS1Cd0NQdEVsTzFUMXhFbWlTYlRBbU1qemZyczFlR3BjNHFPSEtv0gG-AUFVX3lxTE1CVXZXaEs5blViZDJFQ0hfV1FiSFpZeDJodXRocU1MR0Y1SmV6czczRlhOR0tHLTJYWHhLb0tZaWlyZ2czVUhaTG5ES3kwRTRZSUZPdVRDUW1pZl9Qa3MyLU9VZUsxQ2FyTEpYSURWMkxqOExmQ0NKbEU1Um9WX1ZfekV5dks4R0dsajdrMlpGV2RLLXhiNFhXUXo4M0taOF83U3B2anFxeUhBOWdNa3FzcVl4UFBSaEgwdU9Ybmc?oc=5
panjang artikel: 4106

Fetch isi artikel:  16%|█▌        | 386/2473 [10:12<2:21:39,  4.07s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxQRGdLakFwMDhHeWZWcHk4Y2c3YkdkTkdWWkVtVHZBVDhuMTZCTzVrY1lYbVd5SWpxWkdUbzFkX2VGQllYeXBIX1JMSmRZdGs2dmk0amRIM21YR2xhSFk0RjZnRDdsUVBhQnBHNkNpbERscEhac2VHRFZ6RFZRaVJvWjNGY3JpN1JvVXlWS0R1RDlGMnl2a2N0SV9GMFpObjRoVVU4dUtTMm9KRFdzUTd1aTExOExMOFRJem9KR1Z30gHDAUFVX3lxTE5BY3VORl9nNFUwbmNCY2RjVTBGVjZRdHNuQzNvZG80Z3BHY2dWWXpYaUpGQTZPamw0enZMckktWk9kajlOLWxCN0xnd0duQW9MWmE3VFI3V29SdVBPRnBaQ1dUR1pRRUtORjk5cFZxbWJvd1FxU0gxOTc1MndQc0ZTT25aZmhFRlNybDdDUk1OZ1dUOW1iSnFjeU1KNkMwR1AyQjc2TFRBMVlxLXVXNWp0UWZpc3piUEI4YWJkY3RTRmNaNA?oc=5
panjang artikel: 124

Fetch isi artikel:  16%|█▌        | 387/2473 [10:16<2:24:08,  4.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxOYUVlTUNoUWh4NWRsdGF5d0pFTFh3LUNGN0o5b05Sc3VUV2dPTm1TZHdwTEZYQlJkYzZ2bjByQU9RbHI1cC1EaVVRT0JKcHRBWUZTQWNxbG1uZjAwVUJnT3Jfb3RtbkJOUVlnMmVKVVI5cFZYVV8walJfQUxyYzA3UE9xWlNLZWhERjNfamFYWTBZZGVrb3pjaDQ4TjhXazBnRU9HdWp1b1lib1lOMXFCaElJZEVLaEV3MHI4?oc=5
panjang artikel: 6997

Fetch isi artikel:  16%|█▌        | 388/2473 [10:20<2:23:03,  4.12s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2gFBVV95cUxPODcwREN6RzdaWDg4R0ZWeGF6eEhza0ZGUW84MWZGMEdSanFTQVZqY095cUc3VWlVUHR5NlVZVzJLLWxzalVKY24wUmpWTEs2WmtFSGVwNUFveXhBUEpUZFg3X3BsazlxdXlacHJMUUpqcFFOb1NyZFBKNUZEbnI2UjlmWmdhRUgtbHRZR0JaZTBoMHl0RGlKaVZzZmdqWXBiMk1vWGZHeFV1bFJGUm05eUFHNVk2WHhvdU9LVldDWWVwYlRPWWtIQVRXcElmM3Z0NXVyYjVPbjNqdw?oc=5
panjang artikel: 8410

Fetch isi artikel:  16%|█▌        | 389/2473 [10:24<2:17:55,  3.97s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxPZFZXWXlBa0F6cDEwUGVzT3B4bU00RmJmZFRPVWJsR2pXX0g3dWpZay1lTVV4T0dPaEZqd08tTzRwVVFKQlRaTU1sUXRHM01OaHUyYnRzemV6MU1BdUotOWhZNUJ6Y2tUMjNoRDBZdHNBZU5LamJ6RGxwMm1kTXVWazVqM3ZMYktmb0hXQV9Mdng3WVR4OGhKV2gyRXVXTmdlQ3RyUlBNNGREaFBhRVhjbDByUFFidFVCb19aVzNST1lyYzdOLWhGZ0dJWEVGRjN10gG-AUFVX3lxTE9MRF8yS1c1cFhrT19CRXphX05XdnNiV1BrNW55NENuMGI5ZVh0UjlqVFkydE1Fc1R1WlZNck5nbWlIZnhSUXNjb2xpcURvVy02aXNsYnhKOTZha1RCZDdPSU5uV0djUDhzbWhDSUtwRW1rMVFGbjVqSVdQOVNDcnFnY0dfVFdGcUUxSkp3V1ZKcWtIR2lzTnZXNjRId2VaTWxsTWRYcmo5X2hTdGM3aEdjRUxkUm1oTi1jb2luZ0E?oc=5
panjang artikel: 2230

Fetch isi artikel:  16%|█▌        | 390/2473 [10:29<2:30:37,  4.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMikAFBVV95cUxPZzBDbmw0Y0lCX3A2aWlzelI1ZHgzSTJodlBhYUZMOXVlMkg0ckNDeWdod1QtVndMdnQxNkRVZ0NTM0lsT05tTWxBbzBYaDhVY3ljRU1iQ0FQMXkzYXFoRXdYWlctR2E2RU9tdC1yQ25DMEJLVDNpaGFuUVprV0UzX09BcG9Ya0ZNcjloWVNPOGo?oc=5
panjang artikel: 1974

Fetch isi artikel:  16%|█▌        | 391/2473 [10:32<2:20:50,  4.06s/it]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxPR0p1elBKRHhnYXdBNHZ6a1p0Rzg5QUtwdDVHVkU3OWxaN1NPV0hsMTV0NGl3LURKNm04c2Zrd0Z4UGFORTRyZGExbktiSjNuZHA1R0NsZENNR0QwNEltSnVfLVJlWGZSVE9MM0tBZmpNektpbVBmOTlrQ1ZUdk93ZTI2by00UENMakNhVjRMRlJ5alpFT25mOVJFR2TSAaIBQVVfeXFMT1VDNjR5UEFnUFpUQ1Z3SDZmTFM5VloyaUFxaEx2QkphQlY3aFFmMDlEd3FHRWpWTlB1c1VMSzFtSnBYNUhKdGxDeTEyM09paTB6Ty1CMDlJU1F3dTlsaUZHczNqdWxUc29rbXBad2NpVy1uaE5zTXdaTUJFQTNGUUk4MGpIVFFOMzN6R2N3QmZSVGFqZWg5eFhITUc5RFNtMkZB?oc=5
panjang artikel: 3737

Fetch isi artikel:  16%|█▌        | 392/2473 [10:36<2:19:51,  4.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxNRmxSZVRCX01ncFRZeE1ybTFnMWpENzZIZG93cmNZUzNkUllGOEZuZlRjem9oQktjUzFiMjlHcWJkSF9GSzNYLTFfN1MzN0UweTd1UkkybkdhQ0R4MXN3U0x4YWxOU3hSa2Z5M1F2RFJrcng2X0JmLVJPR19NR1JyX19zcjVMbUx2SXNZb2tOckZRLV9TaFI0LWVuVjl5OVRxMEVXRlZTcXVFSl9U?oc=5
panjang artikel: 2138

Fetch isi artikel:  16%|█▌        | 393/2473 [10:42<2:36:33,  4.52s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxNZkhMTGM1Y3FlLVdxZF93d2E0eUpFZlpuMURsNTFWMm0xSlBET3duX3g2LVFKVnJPcU52ekFIdE1wQ3BBN2lMX2Z3bU8zY1luYk5kQzRTVG1sVXdIelhrVXYzVlVFdkJQWWlRQVRPNHRCQjNaaW9URklOcEpvZVJYZTVkbk1JU1pHeUFNR2lYYk5hazZkdk51S2JEUTdTNmJFRXNRWXQwMHlIZm90OXRhUFBoOUh4bjVzQU1FNnI3UlA?oc=5
panjang artikel: 2136

Fetch isi artikel:  16%|█▌        | 394/2473 [10:48<2:57:40,  5.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMikwFBVV95cUxPNG14VmZtdi1haklyZ3VmeGNrMFFTV01ON1ViODhnQ0N4V2JZMkhKY2VMcTdjcDE1ZU9PLS03SFVhVnhLTUUzMmR0bU94VFU2Vk8xd241NDhzcHllSE5kWGpaM0pHX3ZDNGlUN0JrR01ZV0lqS2ZnQVE4UUVOanQ4Q1pmbzRtYndOc1hfaFYwQXVXMVE?oc=5
panjang artikel: 8279

Fetch isi artikel:  16%|█▌        | 395/2473 [10:53<2:48:09,  4.86s/it]

Fetching link: https://news.google.com/rss/articles/CBMic0FVX3lxTE52TjdhMi1VLWlSdXpaUEhRTFc1Q3VHREhTVzlQNGF6OVM0NS1FM091clh4YkFFMVZGbXdWSksydG1LZUtibjZJZVlNcWR2ekdkV2xuU2c4RV9tWUdNaS1HZGJlbjBCWHdVWXJ5TnFZb1lhWHc?oc=5
panjang artikel: 6379

Fetch isi artikel:  16%|█▌        | 396/2473 [10:58<2:51:34,  4.96s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxNa1UxRFNkNkVOb0dJR2tCdVZFbFRMWVRPb3FwN1RsQkJqUVZNM29OM3NYVGdDdjZveE9jTGs2VkptamxpSmdlUU4xbHI1ZHAtZjJXTXlfR1B6VWFsdkp0czd4ZmFWRC1OdFNUamt2WGd4YXNuN19GelJ3WW8xcndzaVdtNXViSXB6TThUYng0dHdZZzVDcWZEUWMxUVg4ZksyS0ZYdnYyV1E?oc=5
panjang artikel: 1895

Fetch isi artikel:  16%|█▌        | 397/2473 [11:04<3:04:27,  5.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxPZnVHZ1k5c3JBM0dlbzh2UjRoM2RqTWZhcElmTE5oYldpUVN3bUt1REdPbDlManlWaTJIQW84UTVwTmYxZHZVdVo1NnkyS2lHMEV1Z1plcUxiX1VMem1NbVhzQ2pDRm1PNmxzcEpBeG1xNWJTVUVYbTNkZkZOLUVBbm94WUZtUmRkT2loTjZWTjJUSGdKS3RkTWNqVU9RQnZFd2dLUA?oc=5
panjang artikel: 2461

Fetch isi artikel:  16%|█▌        | 398/2473 [11:09<3:00:11,  5.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2AFBVV95cUxOUzJ3dC1kZVhLeTJRYjk5eVFPUmFWWmNIMWhnQXFUeS16bm1wMVMwUERVQ1YwSzhQTzRFejJsZnlKSkdEbV9MSkl6UkNPdE10a3pJajRaQXg1SVJ5MVFpamRxcW10RU9uQk1uZExoTmRtLXJCa2o4LTNGQTNVaHVuLXo2Y3JBZzBxcTk0N3IzQkRBUkoxR1MxamZRQklOMElqUDJiWDV6bG1UeGt4TDFmbU9uRGJVTjUxMTdmaTh5UFgtMzNXSmJOWkcwa2ZfRjBMNjNxNDBJSl8?oc=5
panjang artikel: 2968

Fetch isi artikel:  16%|█▌        | 399/2473 [11:14<2:58:30,  5.16s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxQZHlqQ1dUQm5TV3NUTG4wdlpJR25tWTBqc1pmVmpUcVBUN1RXa0JMeUpUSmpsM3VtRzNBTTgteWZOTmxJakNGaXhGMXJXc3FObHVKTkRsenRYeWpHQjVmSXMteVR0OG1aSGtmRkhuLWRBQmhabGFER0JPamV3LUlvOGJYSUM4Y3N5bGxJSWF2Z1JlckgwVzlkSDlnTC1wMUdCOEZZMG9JZHdmMzJNMHhj?oc=5
panjang artikel: 4340

Fetch isi artikel:  16%|█▌        | 400/2473 [11:18<2:50:03,  4.92s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1wFBVV95cUxPdVBTTTR3T0t0Z2VwdGVhUjZOc2t3WWY3aWlqV2hsNkE3ZHVhMlBuOTZoSksyT3VVeFVDMEVBQzJ3S2g0Y2NTS2ZlUnFGdVVfNlREMWFIRklYLTFyQzBmWnl0NFlqSldLMVZXbG04LVlIU3VQRWNiXy1ZbDRBaFVMNHBOdHJ3RGFfVDFHaTI1SG5scmtyVXJvRFVCeDFNY19SNGlMQUpTN29KaWNBYW1KUWpBTEE2QmpoZGJuRUJpbUU1ZC1KUWJody1lS0JUVUxxRi1VZ1ZVONIB1wFBVV95cUxPdVBTTTR3T0t0Z2VwdGVhUjZOc2t3WWY3aWlqV2hsNkE3ZHVhMlBuOTZoSksyT3VVeFVDMEVBQzJ3S2g0Y2NTS2ZlUnFGdVVfNlREMWFIRklYLTFyQzBmWnl0NFlqSldLMVZXbG04LVlIU3VQRWNiXy1ZbDRBaFVMNHBOdHJ3RGFfVDFHaTI1SG5scmtyVXJvRFVCeDFNY19SNGlMQUpTN29KaWNBYW1KUWpBTEE2QmpoZGJuRUJpbUU1ZC1KUWJody1lS0JUVUxxRi1VZ1ZVOA?oc=5
panjang artikel: 3220

Fetch isi artikel:  16%|█▌        | 401/2473 [11:24<2:57:09,  5.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxPa0NnWDAtM1dZajA0a08xRExuZUlQNm5BMVZqUVl3bm5ScGplWTJmTWxzZlRsWnhPNGFwakdkZ1BOMmM3cUM1M3FuYUJFUjRFdWVqYU1hcF9QdW12VWVpOTdBWENhRk1fbF9aRXR3TWE4REdPX1FiU3dfSF82Z2paaHF4RW5YR09rVE80d21kYW9uOGdwSS0tMmdkVnFiWGJ1YWt3LTZvaWlXbGhQS01vSkMzOUVYeFQtVEJ6Q09kZzFJdlVW?oc=5
panjang artikel: 249

Fetch isi artikel:  16%|█▋        | 402/2473 [11:30<3:02:31,  5.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxNb21UZk1faDZpMmJGWlZFV0I1WW41bl90QmpXUHVVb3JwZUUtYjR6TEpFbkpJZXl5b3VMcEJjeDBnbTBkSTgyR29GZi0yMkR2alk3V0JURVAyMXNDLUVnNlF5LVRqcHc3NzZvUXIxbk5sR1dSY3ZFUkJTVEFkMmdOMnVXeVJXenVTM0VqWUNTM1d4b0ZWSDNpOUJ2MjBFLWNBTm1jYzhLejRTX1hYTi1j0gGvAUFVX3lxTE54RHVSU2gxaEdRcTNwb0gtNnRiTFVGOEVGajdLdWVpLVA1UU1iSDJjNEIzTUxma1FZS1pHajduemJoU2ZTYlphN3lubFc1dEMzbGd2NDI3ZUs5Zl9ZSXh2WTV6ampkMndaZERkRzJXdWVqYV83dUphWVEyd01WSml0b1dqUzNJYkhoXzVpOWhpWEtNcWg4dk1ZN3lEMzRjVlhIVm5oMlZnWUVtTVJzTm8?oc=5
panjang artikel: 138

Fetch isi artikel:  16%|█▋        | 403/2473 [11:34<2:54:42,  5.06s/it]

Fetching link: https://news.google.com/rss/articles/CBMizAFBVV95cUxOU09PQ2VkLUs0ajlZZm5HSkFOc0hLdE50OG1NNHpueWtaOFpwOEhmbG91MGIzYng1bWl3Y2RhQXNDbm56dWkwUThTZEZWdjREdlZwa2JEQ1RwN2loNzJEZnNJVHY2QVp3Q1lQbGY3RzdadnB5dnlRUWg4dHJHaXJjdE9xSUF6UnMtRDV6ZnMxVkpKSDNLSnZidGN2QzllSnRPSU8zR3lDcW5oSDVvN0RfREhoaE95a1VrejA1czd0T215VUZnek5lSmhsVHTSAdIBQVVfeXFMT0R6a2JMcHNsbEVUZVQyNlJCXzRadkhoUWNsbmdqa19SbkI0MzJjVTJuTEN2ZzVmV2xfTGk5QTBhblkzd3F1elVpRE9QSmpzZ1piY29LUkFrdlFQRV9vRkdCV3ZiOFh5SUMteExjRENPQWVEVmJid1FEeE1QalBaS1JEbkpTSFhOQmpzR2dndV9EbFhSaGIxd1dMSWdoVGlfQkJYbTZVRmszRXhLbmJBTTVCYTVkV0RVNHJlWjdQdzFOYjhGU29EZkZlTWxLX1ZIMlp3?oc=5
panjang artikel: 1783

Fetch isi artikel:  16%|█▋        | 404/2473 [11:38<2:43:55,  4.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMikgFBVV95cUxONmU1US13cVBTcHdHRkpYX25LMmJ1MEU3UEZsenl6STExWk9DMzN2dl9HSkF4ZWIxbFVuc1d3WjVwWThMZVcwVnBDMjFHUXBjUWt0MnM0OTZGTW5jMkM2R01VTFBhX0NyTlphcGF4X2ZrLUp6cnJxVzVpVHpfYWViM1BJd1FiVXVmZ3JZZk1lTXJaQdIBlAFBVV95cUxQNVRObG9sVzdDOEZBUWJxQ1dZQnJCaldnN1VVZ042MXh6TF9yUnRqVE9KclI1UWlHQXE4SWpQZm5uOWlaUXhLX0lkODhPUm93Z2p2MVFTQXY2dndtZG16bmNZczJ2SU5TVlR0OTFzaXBVczA3Y3pVZndqdUdsdWJHS2lKNGt1VkoyTFp6TEc3NGpQZHhu?oc=5
panjang artikel: 1373

Fetch isi artikel:  16%|█▋        | 405/2473 [11:42<2:40:01,  4.64s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxPYjFfTFVuRWRWcWZfcFRmWVVjSFBHVnNiZmJOSGVFbTc5VF82QUZLTy14aTlQZGIxYVA2anRVTVlSTm9BZU11aHN0YjAyU2I2Sm81c0syRWlGTXpoV21kQkxlWFNHeUpHaGFzWDN0bHJkMGFvV2dDRThTSVp0YTVBR0dyRG41dWg4RkxsTGN0NkdPVHdRVXo3dGdObWM3Y2NhN0tyT0hOME1WaXVlTjdmU9IBtgFBVV95cUxNeDFMMTJOaXAxbWc4eFlIYnlBel81U1d2UkhZWHAzUXc0WHZVdGZsYk9rbFBLUy0zNmYxLW9IRENxTGphWDdLam4telVqdzhNMjR6NXR3blpMU3hTTWZPUkNhclIzRE1qZTRMaVYyVG9jeWdIZC01S2ROVkJ4czN0MWZtTGd6MWNabkNodXU3WUdaTS1STmVYRmpmY1F6enVPWHJReklKUTBmS0piRFl4QzhkUTBidw?oc=5
panjang artikel: 1922

Fetch isi artikel:  16%|█▋        | 406/2473 [11:48<2:46:35,  4.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxQTk9ISi1CSDMzZEtpc1hLcVJMdWJ6QVdKcU44eURPTGloMjl1SjFPMFJXTndobUF1WXNEOVJKbWhQRVQ2bUlNZUIwUW56ckM3S1FZMWNvY0F6bTZpdFVlVWFXNjN1SlZLeG9fdFNsMjVjSGV4MWdxdU9LZC1LT3hWSkVuY0FGSUc1Sm1iMnpQRXRXYkVDV1FVRWN4eENBdVpTSTFFV0s3Nl9QMlRwR0HSAaoBQVVfeXFMUEs2azNpb0ZudXpzMkZOY0tfS2t6VDVteV9ZVXdFZ09WWHFUNGUxbUgtdm0yc1M4YXVzNUM5cXVFV1d0OTgwbmczTUFacWdneFVURnlIdUxwZDVyUF9UNTNaQ05KV3ZabHF0NjFRLXNMVWdabFNPVFVxMlRVaWxjQWw0VjVjSzZGS3IxSG1BQzFiMVlJT2JMNF9hLWRsanFUbGc0TXV5LVJ2RXc?oc=5
panjang artikel: 2172

Fetch isi artikel:  16%|█▋        | 407/2473 [11:52<2:42:23,  4.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQdVAzUnhzTXc2cFJrX2F5akdLcmIwbkVneTlFc1NMaUh4MTRic3I5N3Zyd0tnRElIT2EtbXE3dGh5WTI3T0NOUE9rRGh1R0w1LVVfY2gya21pRDZUSHdTQURSZC16bDhpdl8yYzNSdW1aNGk3YTY3RjFtNnlFdkxaaHR5SGh4Tk0yb2l4bE5kYlliYnpmS3d0VlduSVg4UVFEY2twemdkRmpYdmFhcmxydGJkOXUyMUt1bGc?oc=5
panjang artikel: 4842

Fetch isi artikel:  16%|█▋        | 408/2473 [11:56<2:36:35,  4.55s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3AFBVV95cUxNZkFHd25mQzh1QjUtTGRneVdvalJvT1F6d0pfSlRaZ2FaZXNuX3EzTV9SdUtZWXRxdF9EaW1KLVJSQ2lST3JoU1RPNU9lNmVMTWRSbW5qX1kyemtLYWF6eXV2SWlYQjZqZTlLRnhIS29wNWtscUpKNE1sczZQbWpiOGlWaGRFaXA2c0dJRkNCbF8tRXFkSjBxYXdiU3Zjb3ROOS0zMTRBSWU2NlFnNDR0N3prYXdoNGc4eHJ2VENqWkNfaFFKdlRYeUtEak1BMTFqd2VPdjhPQnZEdmg0?oc=5
panjang artikel: 0

Fetch isi artikel:  17%|█▋        | 409/2473 [12:01<2:40:26,  4.66s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxPM3RVNm5RR2pqNFpTRnd6NEVEVGk3ZEhRUExBNEg2Z1JPTl91dE04Wm8tbkxXUGU5aS1la0ZyYXhNa0w0akF1Z0pGWHoyZHhmVTl0RG0zMXMxMUphM0kwcUFjMV8tUEdVd3kzNDlrMDNvS0ZTdzZnT0dkQVFZbHRJTUtVR2xFRVdNQUVZTWFkVVNxN2JJei0za2ZGV19wb2Y0WFB0XzctXzRqMnJ2N0FuaW1manhPdTdzQUtQcFFuaFd4OTROblHSAcYBQVVfeXFMTzN0VTZuUUdqajRaU0Z3ejRFRFRpN2RIUVBMQTRINmdST05fdXRNOFpvLW5MV1BlOWktZWtGcmF4TWtMNGpBdWdKRlh6MmR4ZlU5dERtMzFzMTFKYTNJMHFBYzFfLVBHVXd5MzQ5azAzb0tGU3c2Z09HZEFRWWx0SU1LVUdsRUVXTUFFWU1hZFVTcTdiSXotM2tmRldfcG9mNFhQdF83LV80ajJydjdBbmltZmp4T3U3c0FLUHBRbmhXeDk0Tm5R?oc=5
panjang artikel: 2960

Fetch isi artikel:  17%|█▋        | 410/2473 [12:06<2:42:33,  4.73s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxPTmpnc29IVnNTUTFvcnBRXzJNYTRXY0hEa05pcThnRHhoM3hlT18zcGY5ai1veHZ2OFdoaHVBVFljNjM1X2UxMC10aXQzUTQ4Nzh4NFNiVnVGR1Q0SEprQUZTRnU1c2hNVGtSYUQxdGticHVPSzVCUXUyRzhDSmNwcHFueGJpZHVHa2xXdG1KLVVjN1lmdTJYWEtVZ3c5UHBvS25MWXdHMi1NYWlnMnJhNFNTVTNBR0NFZ3ZNdjVjQkdmRUE?oc=5
panjang artikel: 2925

Fetch isi artikel:  17%|█▋        | 411/2473 [12:20<4:12:43,  7.35s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxPUUVOSXdSaEJkYUxXWktubHZFRlpYRnBHcUgtZzNveGhhRTBBUDBZU3RZR20tLVU5bkZRdVYxRVRZNjVhbjR3NUd2dGxvSklhUVYxVXFud2hfcU92Ni1HRXVubEJFZTh2WHo0bkZaTkxKSE5yTzBUOENrYUg5RFBnbXJfS2UweW1ZSVVkc0Ftc0dHOWcxSXZTd0R6UmdDMHlqUTVQWVBDSklWWWdGQnFUX0g4TEI2Z2h1SFNxd3Jodkx4bFdxeEM0NDVB?oc=5
panjang artikel: 2917

Fetch isi artikel:  17%|█▋        | 412/2473 [12:25<3:48:27,  6.65s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxQT2tZWW5FaW8wZlhGVjdTZnFBR1p0N21HVkRQWHZNNlNkQ0puQjhGWEMtYUlVR3NYMVZYc0NLaWRvRlJNaFFYVjd3SEtyOE5WUUxpaEVfTGRRMEN6YWUxS2x2a0R2eHN2ZUwzcG9xSGMtX2s4WXpOTmxIUldtQnZVU0h2NWJKWGpYS2pHQnpDU2hPTFQ3WkxBS3NfdjBvSnJFZkMyanFWVjlUZEtVckHSAbMBQVVfeXFMTUFETkdmMkpxNDNkWHltTnlJUll3X01PZjdYb3ZKcFd0aGpPY1ZCOGROUEN5eVlyTXlHa0pxMUxPQ1lkdG1ZNFBEcVplVE5zZjFFZnh4cHpQVEVwUWNyYVJfbXZvLTFkckw3NUVmTHFrT2M2QTJ2MGpoOXQ3UG96N3N5Sm56b3BJSjhTTk1BMlR0ZmU0YjJqYWZZdkdXYUd3MEl2QTR6T09CWjQ3V2VVUUdRVDg?oc=5
panjang artikel: 123

Fetch isi artikel:  17%|█▋        | 413/2473 [12:29<3:27:16,  6.04s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxOU2Y1RkRHbUFrdDFFYWRfdkFkUTRZdDFYYUlwS2p5cnNIRER1MEZxQnV5Q1lWbHUtQW4ya2xveW1UMTA3OFBMMmh5a1V6QUp1QjdOaFNWRENEdzdkNmxhMjJ6d0hRQ1lGdzJhdkRxSHBoQzlwR1Ywd1JncTJfSjhTM1lkNzFyVEhrMUxucVdXX0NhTnZzdEg5YlpOZmpaUVdwZlMwSVV5eHJlb1Ezb1U0RmxuLWhKSGVYSzJMc2xkNTI1NFY1N2xv?oc=5
panjang artikel: 3198

Fetch isi artikel:  17%|█▋        | 414/2473 [12:34<3:09:22,  5.52s/it]

Fetching link: https://news.google.com/rss/articles/CBMijAFBVV95cUxPSENBSzQ4cTliUnpYY0NxWVMybU14RkpmaGVFN3VDSElJZTk5NmhrUnRpNUFOY2lzUmV0YVVxOGFpRHpPcnI0RzB4MVlqMHpJUmU5LS1oVG93NTZpMEwxZDUyWWJtYTkxc0pwVWdzbmhOdTFUZDhrb0IwaDU4THJCSllhV0diall6a3dpQdIBjAFBVV95cUxOd1FCQktZanFROWYyTUV2cWJkRzMxWnhqU0EtN3VhY19yX0RMQ29HRnJaZnJxMDZYd0VGOVF0SmJieHZEZlA4ZTI3OW9YRGh6bTU5dUpEUUdQa2NmQmJvbEItVHV3TVhfdzdxeTdPSHVUdGRveGJzV3RjOWhhS0F3Rk9vODdaSTJQNFFLbg?oc=5
panjang artikel: 139

Fetch isi artikel:  17%|█▋        | 415/2473 [12:38<3:00:41,  5.27s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxOV293RHowNkZHYXM0RUhFR0dWYzFGb0tZTTRlUFRBUU15WDN0cDcwRlpoSVQ0eEY4MlN1NVlJR1A5NHROZVVVeVJKR25sMWpIMFk4OTBRTXN0RlZpZnNDYm9JdmZmS0tFV2NaSDZfNDBYSHJpckFXdjliMGt5akp5Q2UwN3RIY0Q3Ums5dHdzRnRNWFIxRk5CRmFMeGhiQ04weHlGMDdEZHVhd9IBqgFBVV95cUxPRnNUUnJmLS1FbTM3dWlEcTQ0WmZ1aDRiWFZreVZMdXVzMDQ2VkpxRW11UURiYTBoZDNwSGoycWdkSlVfTWZwVzJxQVlxTEo5aHdycmJnQ21rdzlaV2lmdmJKcG1mMkg5WDNHOHYwSktmM2VHNGhOOWUwMzcycXNFaTVCbzdHUjBFSHVZOUthb1REcWtJQlhrckpsVEZtQ3lNOHpWOHRhNncyQQ?oc=5
panjang artikel: 137

Fetch isi artikel:  17%|█▋        | 416/2473 [12:43<2:53:17,  5.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1AFBVV95cUxPdUEyZVNvQVZHaXNVUXdRMUtnR2ZrZkxEZWFUdjdCSzROR1Z2N2hoTE0xWDJfTzdxTHNCQU1qTGowLU1rblI2cGxXRWlYcnNJY1gzTTMxY1FFZ2tBMjVsNGtQUDR4dWpNaDlxNVNPa0t4c242TUdKU2dTRXBIakpVWFNldmpOU25wbG9SNHg3SzJjaTZXcFVxdGNDZXVFT3BnVkt3cXJoTVFfTGtuX1RJYWRtaEs5RE9HdmlESkZxOTFnZ2xIak5fenQ0Qzc0a2NJQU1iSw?oc=5
panjang artikel: 4961

Fetch isi artikel:  17%|█▋        | 417/2473 [12:48<2:55:26,  5.12s/it]

Fetching link: https://news.google.com/rss/articles/CBMijAJBVV95cUxOMmEtRGJqdUU5R1hNc2ZXOUpzSkxhc1FDUzNuM19Fb3lxenpTcDZNQjdtMDBfNDdUUEJOaVg2Z0FJemJ2RnZGTGc4VTctRkZpMlBpRHhERVhKQXJvR2JXQUpXQzRuU1dWMk0tYkVXUHE5X3lKQXpnbjAxLTF2dXpoSXd3RnBjb2lLem5Md3F5dmQtYWJKeG00ejk0NWN6Zk1oXzBUakF2TVlKSjVWTF9keGFzcnEzMVVyZXZMekdHZ3VOek1ONEhlN05ZM0tyWm12bTM2WHkxMzFvM1prMVV3WEExeW5yOVI0aWI4TUtDM1lMN2RjOHZ4TjdzQUF0d0VwbXpuVzR1ZWR2cjBw?oc=5
panjang artikel: 4304

Fetch isi artikel:  17%|█▋        | 418/2473 [12:53<2:56:02,  5.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMizAFBVV95cUxNb3hiR1ZYMnJBSDl3b3FULVh4R1U5ZDFkeXgwNFRXWHROanhxUml1Mk51a3Fod1hKSVFZcXIxbTlQSXlWNkZKX3FobURHU012Y2hrYmxjRXZoT1pvU3JwRUdEV2dYVk5RZGNDS2lldVJMN2l2SHFONjVYb2ppbjAwYU52bFFBOE4yM0N0V0tjN3pLYXlndXZQZlNTejZDbVkxcS1yWDJSTElfajg3UzJZc2pXM3p5RmdRYXRHQ0EtbnFpTDJ4Sl9GdjhQbVU?oc=5
panjang artikel: 2146

Fetch isi artikel:  17%|█▋        | 419/2473 [12:59<2:59:46,  5.25s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1gFBVV95cUxOMVdHTkRlNURzU3hmc25Cbjk0SWpiWkdwdGV1QmQzdlZUMk56LW9oQklERG9oWEhjMDZXY1MtcGdZeGY1YlBxYjdXLW11X0xHYXZPd25oUUZXbkppWG44aWxtRjdUMEN6YVpGU21JNmVydGloOUU0RkpoT2tpSXNQX19NUmpwajREWmJNYkF3ZDRURDNwZEJGQ0ZRUklSemFnOGVBNUFlVFpIY3hnOWV1WDNqSlRyUFEyVVg5QlM2cGpKcnhOdWNFcmxuT1ZKa05RdzFqZjBn0gHbAUFVX3lxTFB5cTVGRy1obm51ZWxGYmlwZFkwVjFNSXN6QmpkMEtlcnoyQ0xhTE8wRmpzekJCclQ5TG5saXUxTWpwTGN0Yk9hVW4taDh0WkVLMEdzVkE0U0tjZ1pZa0o0czRjUTIxcTA1YUFLbG1ZNk80YnlMUzJwT0tXVU1qcTdXam1HMlg4ek05YXZ5Z2ZGOV91bzZLOVVpa2VQUmZtN0wyVHdNQWpJWU9GWWdudGlPX00tU0ZEZTd3UzZmdWJTSHJvUlY2Zmw3QUh2VUEyNEMyTTdSZDJ5WkZDcw?oc=5
panjang artikel: 81

Fetch isi artikel:  17%|█▋        | 420/2473 [13:03<2:47:43,  4.90s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxQdkVEdFVYdk14OE43VGMzNHJib3czcWEwcHFDU3B3TmxIVkptamx0eDJVMzREU3loTkNXSTdkU3Y1Y3RBSWUteHFXUnBEdzlYWEVvemdvR0s3WkV1Wmt6a2Ridk9Bdm00amNqcEU0N1RFTVB4Wm9lbVp1bG8wa1JDZUxCd0U0V052bXY5UEx0RkV2eW5nc2hmN2pySDBWTnVWY3FwVzEzbGtBc3hVTkYwMWVXa1g4T04xVDZhWTI0dDMxbkZENV9IQk930gHDAUFVX3lxTE5xMW5HYkwxTE5mY09QSGhHWkZ0aTNPcDFHTlJMV0dGRHREeHJFX0l4WGRwUGFKYVVKRzBSX3lTVzlJeGQ4Y09aYjRsSmNkaGg0V253SERZRTBPNjVkYkFZVUhKSVBuN1RGemx5cTlzSXh3eVAwb3hkellxeEppTFlfUzhMYlAtWTVqb1BHNVM5cW05VVBjN3d1dW5BelJWX1p5dzBSTEctRlR6WHo3cjk0QncxWHNpZk5Ec0huZG1kUXlqTQ?oc=5
panjang artikel: 87

Fetch isi artikel:  17%|█▋        | 421/2473 [13:07<2:44:04,  4.80s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxQc19fMllNYWhmaDluRUVlQlJybE5XU2NIb0t0NF9qbEJjMnI0QmxubEhvZ0ZEdE9Db3RqcTdPNTdUVjl6Wm5Jb0kyQW9VRzBoa28tN1JCMEdkNHFtSld5X3pUOVFUT3ZYSXdEOUJ1akpvSUdGNmdEaVFSREpBbTlNVFdnS1JtdU1Wb3VDdGxXOENoMktVeV9qVWk0R0dxREVWU0k2OVZIcEhxaFVTbV8zZENrcVc5NXk2?oc=5
panjang artikel: 2352

Fetch isi artikel:  17%|█▋        | 422/2473 [13:14<2:58:01,  5.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxORWZuSlRxbWgxOTFmWTNKTkNyaldBSXdXRmlibmU3VEZzcUtlb0Nnejg4RFYzSzJuSUlnWERPa2R2NUFUSWZQY3VQNTNvcHdZNnFZUDMzSmduZU9uNDR3Nm5TQlFHS09zOTB0UEI4RWxzMkRFbGxVYmFLUEJST2tIcXJPTU9zdlA2a2JVVTBydi03SEdRR0s1ckd0N0RUTENULUpGcA?oc=5
panjang artikel: 2655

Fetch isi artikel:  17%|█▋        | 423/2473 [13:21<3:17:13,  5.77s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxQcVMtNXBYUWNsVERFZDluWS1mX3BjczFhaGxfZENFZTdYMWs2VGg2Z2s5cWlZQlIweGxqV0FRRDlYVXdUc0RtS1dYS01SUmFsOW1EZll3UWIwVXp4RlNSRFduemNsM0xOZFlxaHUzcHBxXzUzRVhKMnZoY1ViY28yY3RPdHlpUFFRZC1CRS1sNkU0T3l6WkNlOUpqTlNkSmM3cnQwd3JwdXJ2M3FfM3lxYmFiMVJONEZ2?oc=5
panjang artikel: 1916

Fetch isi artikel:  17%|█▋        | 424/2473 [13:26<3:16:27,  5.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxQMVB0eXY1a0xiS3p0WkJnSGltMnF0Rm9ha2tTTzk2Q3ZmSk00ZlAtQ2YzNDdRRm5DbHRTU2d3OGRaWExFaWxSMkdHRzkzM1FMQ2JZVkJuU0daM3pIRk53NHJNRXN4ZERLOV9OSEJBU3pHUmhZbG4wd0Q1b2tJb1loNnhUT2lCM2M4dTFoQTdIbEh4cXUtOGhtVHRVSFY4LWJ4WGc?oc=5
panjang artikel: 3402

Fetch isi artikel:  17%|█▋        | 425/2473 [13:33<3:21:39,  5.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxPeGxkN0s2bHFVRmU1aVZIX3Eta2JWU2xTNFU1V05ZMHJvRW5aeEZJTkdIMV9ta1RuQkdqbmFKYnZ5YnNaUy1PaXZQWk1aQ2dDSXRQTGs5Q2xmc0NMbkE2dnl2bUJvX3E0TmxMVjdXYUNOR1J6QWdWa3BnaExTYnc1WWJ5a3AwNFBKRzBhbGkzRXkwbmRDMjl4alJhYkxQb2pXNC1yYmtzWFhfQXZ6enRtaFI2V18?oc=5
panjang artikel: 6092

Fetch isi artikel:  17%|█▋        | 426/2473 [13:38<3:14:48,  5.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxNU1l0Q3BYUHBIZ2FjSVB4OXFteWF6RUVTZC0tSlJkdTY5WG50Nkw2S0JoSG4tVFUtTVlqdE4wcmNQT3ZmWXRoeER1b1VKQjE3c1JET3pHWnVnRkpHZGE3cjhjM1ZpaVNNNF81dlA2b21qTVNlXzVCSHNxaS1WR2ZENVJIN2ZYOXFmaks2NU5QZHFSM3RoRWt3QWM0R3lUaTNLV2k1cjVKZ2tLbTFfMW9JUWw1Z1ItUWhUR2c?oc=5
panjang artikel: 5456

Fetch isi artikel:  17%|█▋        | 427/2473 [13:42<3:03:05,  5.37s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxNQWx2cC1FX3licmJjZnhoaWFrS1NzSmFSR2UtS1FWT0RERTI4cmVVMXR1QUk1TU9uenpqQWg4TkktaF9sVENhRm1PcUgtOEVkS1IyQ3hub3QxVjNfV0JpQ1lFZXVvWllPdnVHdmlaQkF1T2gyamt1U0NFS1JYVXZpMkI2V2RzaWl1U1B6NEdJNVR1aDE1ZFg4cy1lZzdBeEdVSkFJYkxZSFZaNUE?oc=5
panjang artikel: 6984

Fetch isi artikel:  17%|█▋        | 428/2473 [13:47<2:58:32,  5.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxNd3J5WWVPVG5sR3JscGMxby1hckFzbXVjUmFxVUNVWWM4dTlGVVJlcmlRRnZRUG1zdFdhUWFxalZWLWg0R3JPUzNVYnFBeDFKMnFGejBWSHRPT3VTQURlM180REgwNlJ6YkpkVmlxZkFYaG4tSGlvekdyaVZ4MHpYWTZCaWFqQzBJWE9uWUQwNEJKS29RYWgzc3dyM0lZMDY4QW1WRDc2Zjd4cHpEZjBNaTFXNWk3RW93bmgzMlpySW7SAcYBQVVfeXFMTUJ1UGpydzh2UmhiMXBfWHVQbjUyc0ZkTkdYQW12eWRGU3pKSzVReDRlTk41b0ZCYlRNaFBYQlFLWDNQVjdld09sQnFGbEZscjA5clpLdFNnc3BhZkphWTBLdnltTE5QdEF0by1ncDk4aGhCX3dILWxXSk5DQjVwWHBYUmY5dFZ3ekpsdk13TzlzOXpTSWtLdXNmY0JZMHpVY1NMMFJkZUFMWXp3YkF2dUZaNjFNMXNUQzRWc3YxVmprbDk5cEJR?oc=5
panjang artikel: 2693

Fetch isi artikel:  17%|█▋        | 429/2473 [13:52<2:56:17,  5.17s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxNT1hIV2N1bUN2VzdiTEZ5ZjR4RFJuVm1KcjJoU3lDS2paS3F1UllzNGEtcDhxdXVhV0FrcUxxR1hzcHVxWU0xUVhjUlpZTFFHcmpMdV84TVF0cFdmcGxXUnpjek5uS3hLaXprYk5wT0I0Zm9JOHBNU2dQWmI1ZS1wbEcwcklxemtoVUhiWFJxQ0Exbm9JTXFvZ2l3cXJUVXREZ3ZqaHJ4VUx1c1Joc0pHRHpoeEQ5TjgtSmNDYldURnlSU0U?oc=5
panjang artikel: 4053

Fetch isi artikel:  17%|█▋        | 430/2473 [13:57<2:50:39,  5.01s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxOa09QZEpqaHJmLTJ6aFh4ai1HMUc0UkN1U2NWT0NpZXdKekJyVGYzU0RaTUpraW96Q29GbTVGamV6NnFVbUtEOXhRREFUVWRBOGNVZUFJeVBzODlJZGZ1RHNtZ29VeHctTVNXM2YyZXBJRXRFOUxGVTk0eUVoT0ppZmxjeDRjMGJQMjJ1RFBzcE1UbjZGRU1oaDVEdkNGRXJHSTA0Yg?oc=5
panjang artikel: 5579

Fetch isi artikel:  17%|█▋        | 431/2473 [14:02<2:48:03,  4.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMingFBVV95cUxQWEtIM3RWWHo5UmE2MkdfZ0Y2c2xqTTQ2Znc3UWxFaTR1NTZCc3hLeFhTQlduRUVTTFQ4ZzZKM1F0OGQwSzFaVVFmVnhIMjgyeUZpWTktYWpHVDRPSzB4YTBDOU50ZHB3LXk3NFNxdkNKcGlnTFdBeEJiNHBiUjVpUkxUTVozUng1WUFVamRkMXZ2MEdsZGtPbHBDM2hVZw?oc=5
panjang artikel: 3966

Fetch isi artikel:  17%|█▋        | 432/2473 [14:10<3:17:02,  5.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxPSTR6dURWWkdab2VWZGxwS2x3RGtzNVFNeWk2RGctaDRXU3JjMkUyaGRvM3pDVnEyM0w0bndTak9vZVJmRVp0VDZwM1BzT092SG13ZmxRSWNJM3JLU0QwZ2l4QzY1djduUlI5T2dIWmdsMWRwNllrVGs1R2tBYU05bGxFM1lGMHJkelpzQVNoQ2hLYXVLUWdkOUNRWW81MVhOdlo4VGpoNGppQko5ZlZLb1BaVzA4MHA4UGc?oc=5
panjang artikel: 3330

Fetch isi artikel:  18%|█▊        | 433/2473 [14:17<3:32:35,  6.25s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxPZjQ3djNGcGk0Z3ExSlgzbWZkeFF2aFFIUzQzSV9Ob0FCVGhjeU54dGtobVZBTHg2azBDSTVyNExKQmVMdEIxUXBObmpqb0xrTElHVDNmNGlVVHZ2c1hLVm9VN0ZPYTFVOFQ3alJrcTZPSUUxcW5kenluQUNoVDJNdXJHVWJiNnhWNjJHTV9ieURhNE9TWFdvajRVTVExUTZVZ2xDckZKRERDT2QxdWYw?oc=5
panjang artikel: 4091

Fetch isi artikel:  18%|█▊        | 434/2473 [14:21<3:13:08,  5.68s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxPb3NhOGp0eTlnRy1TeXdHREhzNWQxeU9XallZeUR2TUhqNlZyMFA3SzY0SjZYZjZfN1dVOG40R0JTX2dVTmUzSGlZQnVDSjlLajk1UXhvUFhLcHFuS1JXS2IyNE9xUzc2OVVIQk1tUlZDNHh0WjFMTW9WVFowaU5XNEIxVHEtbUxYV0VJTW5DLW1lMGRObGFuQ0VXZTc0VEVPQ1BQSUgtOFNIbEhlN1prMXkyOGU?oc=5
panjang artikel: 3717

Fetch isi artikel:  18%|█▊        | 435/2473 [14:25<2:54:57,  5.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxQdjlPaWhhLVV6U0hxTDJmZ0o0elZuOGFtcmROdzVlMEMtTjdRMzNDMTluTXBZNF9IdmNfV21qLXNxQVFxaVV1Rjl2VTB1NGpXZzc3LW02UWpocW0xTTJlX2FOVlh0ak40My00YkVKUklTdXB1eGktTWsyM2hlWjM5elB0Qzl5ajZhbFFFdWZ5cGVJZU1kdXJubGpQMXhTZjNiQ24yZkxJN2k5SUxZVDdvS3p1eERJQQ?oc=5
panjang artikel: 3056

Fetch isi artikel:  18%|█▊        | 436/2473 [14:36<3:53:07,  6.87s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxNd0JHeHJwQzkwVVRnNHBkcVpJTDh2VklINkszbEoza1dYR0xtdUc1bVBUMU9IMFJYQUVxTWlGU1dfVXVPSlNaNVY0b3ZFV20xbUdFbHFHWjhYSUxsamxkTVBYU1dvRHFpakpHZHA2cEd4VTdFanJzN0JobmIwbm4xLTlZTk9pWTF3UEI2UlBVQnllX2FSTjhzaXctVFlZYVRVVUpEZVZwSGRyd2s?oc=5
panjang artikel: 3323

Fetch isi artikel:  18%|█▊        | 437/2473 [14:40<3:22:06,  5.96s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxNRGNBaDZHazFtZFMxQ0VDbGlBVGxCbjNpeExUcHZ4NE1JTm9qdGhoT0RGdDlGY20zbWhVcjExZkZQSzRRNDl1dUFZaHVJbkxqY2swOTVkRkJIdmFJTDg1R3FQV25kT2hvanVHb2pOUks2X0huMzdwX0FlTEVlaktCV2JLV0V1THllTG96cWp0UkxiUk10M21aQVJlNWRGOWF1dVM1QXRLbw?oc=5
panjang artikel: 2938

Fetch isi artikel:  18%|█▊        | 438/2473 [14:45<3:11:35,  5.65s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxQd29Xei03Ukp3VlpBYVBOanc3aVh3QzRBYTJXbFRMOE1ydHF2OEt2NkdOb2haZV9VTU5mTjdRZjFnLVh0dHpSVG82N1Z1VmlhQTROOEJMbmhmUTlBZmtQTGxlenl0WFZDbHpNTGVub3ZrWW51SGxMczBhRU5SZWdXTkZ6cy1salQwRnFPQXY0WWVBeGFGMXpxWlNJNzJQelBLcUV6cFljRmVUWEQxYXB1WlFTYWJhSDJobHplM1JyQ2RPOEN1LVE0?oc=5
panjang artikel: 2619

Fetch isi artikel:  18%|█▊        | 439/2473 [14:51<3:12:19,  5.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxPWkdkTUM2eVlxeXVnaWprMTRoUzBhTXNWNVFRVTB0RDJaUHFkM01qWVBKck96UzBWdnh5X0VHRmtTU09DWHoyaDBTVVBtWmxQdUx0dk9FajhlaXU4WjlJMTBWQTRLRHQ0OHFUdThWWnJna081QmtOcm9TR2huaVRfNmtxOXFvYklhY3I2R3V2SER2NzhuQnJVNW9wNGRFTDA3WXM3LTJqX3VUZ2RId0hFZE85VThzRmR4R01scU9XSkNrZDQ?oc=5
panjang artikel: 4623

Fetch isi artikel:  18%|█▊        | 440/2473 [14:55<3:04:09,  5.43s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxNSFBPYXUtSlpBcEJGd09CaE1BNFpEOVB5TFh4QWpNdk1yN0p3MVhuYWxuZ2Juc2FFMHFWVW1raS1NMXZFYUplc0w5ZWtBZlhjR0RPdVRTa2kxQVNYcDMybmpfVHR2Uzhla0pSeTl5ZXJlV1NnMUowOVVVLVNHYWpZbzcyVVZYVVZiaDRJVWZGcTlZN05xa1lHeUpLT3hlVko4ajlpLXhtYzJPUVJBVFp0TGdSWC1mZi1WZ1Rha0xKT1lHdFE?oc=5
panjang artikel: 4182

Fetch isi artikel:  18%|█▊        | 441/2473 [15:10<4:39:11,  8.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxOVFFqaGJ2N1FRNENKNnljOWVrb1AzQ3pBTy1lak5IczcwZW9pLVFVYmJ5YkdLT3dyNG5HcDRNMmt5TWtKV0dMSlI1a096NjhNbGREamdvaVhmV0JBUXlOeVp1Q3d5UGJOSC1UVGpuelRNellsNURwaUVQYlEyRHRrUDNSa3lCVGNGRjdHRG9Ja3RGbVlhbjFKYXFRem4tNXF1dE12elduWmptZms5M2VUanZvaUwtLWVr?oc=5
panjang artikel: 2463

Fetch isi artikel:  18%|█▊        | 442/2473 [15:15<3:59:56,  7.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxOZ1RWSGtwRnkxMFJETS16RXg0bTJ4X090SkpIM01YSWt4S0J3dlFJT1FBa3JYUVg4UGlKRnU4MWVSeF84MEFmLUk4OE9mV1ItdVlWOFNSOWN1NjNFQVhuU0lMekY4NE9peTRfRTVvUFJVT0lDMDV2al9ubU9ZLUd0NWctaGpzWkNET0NEaDZ5OHgyZFVubVNwaTczSGlTdEl5dlFUYTJCYktIeG5OLUhldVBB?oc=5
panjang artikel: 6200

Fetch isi artikel:  18%|█▊        | 443/2473 [15:19<3:35:41,  6.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxQUHA4cjBVUFJQbFVKbEpVTmQwLWpvVThGb3lBYnd1elpXLXFHT2hYZnpJT0RNRkdJbmNzOU1NR0tVTjlMY3JNZmtlck9rMmJGMjZzUGxjMkNnZS1jRm5pUWJ1Vm9zRENFOGIxLVJfZWJNTllqZGEzSnFGT2JSNUpLdmJoOVoxeWFWUnlsRVBXTk9NLXVQMTFUVzV3NnprckhDaXpQc0ZGM2VYRk9pcFU2a2V4ZlFCeXQtazBMWnFuMmpfek3SAcgBQVVfeXFMT1pfeG96MGFnUVU1TTNKNVhSdEItOE5jOGdOTU9UV2JBTC1UTlRjQlF1QlVMRkVIa2ZpbEtVUDY0QjhwaHFnOXBYamctYXBrZ1FZUWFzckppZEZqandfWFdsS2RHQlJoS20zXzlPVFRLNFk4MnFDLWZxaHNCTmtjT1hHTnVsRXhDNkZkWjRVSTBzYkxoVm5VZ2dFSjBNVEZnM2R0ekFrdmtVSVBPYmFsb1BpNW1oWGk4Q216clNVMHU0NnpKRENjMFI?oc=5
panjang artikel: 1723

Fetch isi artikel:  18%|█▊        | 444/2473 [15:23<3:12:28,  5.69s/it]

Fetching link: https://news.google.com/rss/articles/CBMikwFBVV95cUxQSm0xNUVSMUR5Nlo3TmlFVS1GYWdQdWpnM2loNWJnV3VLMjFyc3lTSXAxRDhmTUJqYjV2YUJKNWpBS01WQ0hBRGNrbzJKYnRFUGJ2MTFiLVhtT3dKazZoWjhyVEdIa25rZFVhX083ekRXOVNrUVFFXzljaV9hWEVNN2R0TFhDRkp6R0ZNR3paenRZcGc?oc=5
panjang artikel: 3755

Fetch isi artikel:  18%|█▊        | 445/2473 [15:28<3:02:59,  5.41s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxNRkpQMFF5WnRmbHpfN3FHUnJaNWhHVkVoTGREVW5iQ3FJSHNSN0E3aEJVSWtDd1ktVC1JT29WVkdpUkV3WE00cl9LVGozNWdieTh6OEdNZlBwN2RwM2REMnVpY1k1Zlo2YlJHUTJhcE1QcDhoazV1SllySW1WbnYyN3pjVWFFNEh5ZFhtdUtpM2J1OXhBek5XakctN2laS0xpQ2JVanM3UHIwTk5DeEJnNlE4UzA?oc=5
panjang artikel: 0

Fetch isi artikel:  18%|█▊        | 446/2473 [15:33<2:54:38,  5.17s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxNbGE5ZVY5V3Zvd09LYkJjX1FXMDlFbEdHSVFBYkNROEFyNERkQ09VMHFobEltUm42WVZXRVk5VW14MWZnVnVLLUE1R2JsaW41aUIxbU5FTzFrTGVMSHBNcFlEZTlYS0tnNEpZSXVjd2lQcWZTZl83SDNmNTJXOVlpMzhQVkFXeFdiYXU1bUVQVVlFSVVabnBva3YxdlpDeHZ6ZWh5dGFYSGhrUQ?oc=5
panjang artikel: 2254

Fetch isi artikel:  18%|█▊        | 447/2473 [15:38<2:51:49,  5.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPUmtVakQ1WkJwTzdBamRONGtPNkEwR0lPOHg0N1V0TGxQR0JNVGxvSVJUblFpZ0VGN0xsLURrX21XY0FWQVgyZUxtNmpxc18wU3BoTzY0VWJzRGIwM3AwZnNYMV9sSnUzUDd3MGtZWDF5WG1XXzhBQ0JIbmxibnB5ZnZFSURaRnhmRTZINnZpUFVPU3FGaEdwYnprYkVmNWNyVnpBZkREdkVHNE5TOTA3YkNn?oc=5
panjang artikel: 3837

Fetch isi artikel:  18%|█▊        | 448/2473 [15:42<2:44:43,  4.88s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxNb2ZmdVRqc2dpd05ZeEVYemZmQThqVG9HeU51V2RTYXQ1cDhMeDk4RXVpd3BPaEpwYnpaOGtpWFpPSFRUT3hZN3ZtVlI5M285UzU5NUtHamxHNGFGY0hGdUdUWE1nQzBKQU9TWklZUkxVX2xBWkZaSHlnTWoyVXd3TjZUVnlNcDFnMFl4VlBmUGlOUVhFVVVQbldRWW9rOVRLTzZUSW5jZWh4cHA0YnFoNFdsNEdsemdEOXM0VGp3dkU?oc=5
panjang artikel: 2149

Fetch isi artikel:  18%|█▊        | 449/2473 [15:49<3:01:17,  5.37s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxPSkdudndwVFpDSklqUXE5UVU0dXlTUnBsbmpIaHNyVzhJVzFqSk44Nk9ET0EyVEdKUkpEMTkzbWk4M3FFdl9Xa1ZCaUloMlFxY3dMMjFqOVFZaTVyZV9lM1NpVHdtTjFQeW5WSEdXV01Bemc5bUFkc3IzVFNnUEpPbTJLNExMdE16c3R3TFkzd0xaREZfMDFCYUJWalBfNk1pUmJqbE14VWVubE5DSUZ2YVZRVG5zVGItcEHSAb8BQVVfeXFMUElOTWlPa2tIdHdqTEpVR1JXNWdaU1lNYkNlLTlFdnlYOUx3Q180SFVOVlUyQXR4Y0hlRWRuVjd5djBIYmkxc0QyR2R4WXk1RFhJZjZ1TnFHWTVZNWl1eEZPS01HTzBIel95QVJzajc4TDRVVHNGdUc5Nm5sOGc1emtQZE85S1FQRkYxTzFYaTRDek1qMndfa3NXX2xHUU14UEkwRk0yZEhpRkdXZDc3YW14b3lkZU8wOFJxMnE1clU?oc=5
panjang artikel: 95

Fetch isi artikel:  18%|█▊        | 450/2473 [15:53<2:48:12,  4.99s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxQSTVQd2xLSmdHRElzcm40eXdQVnJZNGVhYUJjSGE1MnNkSnhPVjdCQTNraTFwWXFKclJEMnYtRjRySGdIeFZBUGxHandxekcxV0ZZTFRLLUpTcE1kUk1USEU3MlRoWFc1eUY2TWZoZ1g1eDJLVS1ET2tyNlZzQ0VNRmRxM2lOZEY5WGdDZFoxUTE0bEV4X056YjFVcUFBMDhPeE5pdzdvdndncHZseDdNd2VYbG1aUzg3YW9kM2wydTJiendRNDRyNEczTTZteEU?oc=5
panjang artikel: 2558

Fetch isi artikel:  18%|█▊        | 451/2473 [15:58<2:48:27,  5.00s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0gFBVV95cUxNQWFwUXpxUklzTGdHajdYQmNGZkRBMTJWbW1jcGpCRHZYVjZUbkJwVkl0RGZKR1lwYkVrVDVtVWZqWldqT2ZvT1ppSnlLTXJDN1JRRjhKUWNra01UMi1WcGF3cnphaTBBODViSzVPeWRPY2hNM254VFZnM0E4ME94YkJhbFJNcm9lQnUxYzdDQVRtWFFrcXltQXR4SmxhNmQyWEpCQVltNjBYSTdJUkdoOEtIeFpDU2JFbkRCY0g5b09DOE5GMlFvc1VzVlRVRk44SHfSAdcBQVVfeXFMUHlzN0tYUmJiVWRkcmQxSU11RXFPaUxLZEFmaDdYQjZYUmtMeEREM0dUR1U1aU04M0wtSUxCRmkwT2xHVTFuMkVNVTVXR19OQ1FCTl9FM09ISFE1SW43emJVQkwyZGtLNE1xT3c2NkNkZ1V0UnF4OFJlbnFlYVpVTFluYTJWbmxWVzZlYW55WFJzcU5ub2hGZnBmMjF1cHRFdmZ4MGVlc2V0VjFaSml6XzlSTERPalRoS29ub21OTzFaR3JnRTVSTHJ1bHBWaWlrY3luTFRXTzg?oc=5
panjang artikel: 2218

Fetch isi artikel:  18%|█▊        | 452/2473 [16:02<2:36:03,  4.63s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxOZWtlTlhjVFpPSWVCRnk5YUJGbUM3NGYxSzA4ZFViZUdzZ3dVV1BnY2N3eFVvR1hlSE9aaXlMNHBKcXhjSUZaZWZRbURsMlhjY2lmNUNqWGhCZURORU5BUXAtaVU0cWFMMTdmRzNqQVMxZ1MwWUNkWk5vOGJOUjB1RUJjc0NWOXJGRk5ESTUxWll6UEJYYXJFSHBSR2JNSUpGV0ZRZFEyQnFYaFU4WlBPTXZrZVE4ODMyMU5fNUE4aFNSMHlMckE?oc=5
panjang artikel: 4592

Fetch isi artikel:  18%|█▊        | 453/2473 [16:05<2:27:36,  4.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxPcHFRNkg1OGRwU19sWkVoc0o2cGJuZUNnYlRNMHhlX2VuQXJHeWRDRGNoOTJjWHVjX21YcVVHa0JWNHZCWWJtSEtYcUVhY1ZaemtKYXhwR1MxYmtIVUo5Vml3ckRQLVI4OVlURWlvbmt1akJOMEN4NE4wN3dLcmZGUDN5d2pTdGM0eHRXdC1mNVZtWEN1U2FaTkMwbm9ZaDZ2Y2hnRnk0WGQ?oc=5
panjang artikel: 1948

Fetch isi artikel:  18%|█▊        | 454/2473 [16:10<2:27:19,  4.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQcWtmb3lJb3ZVOTk2dzBpS0J1Q1pBaDBOLUlIUDV2X2YtV0NLeHZmVGVFTzRkcV9HWnhQUF9RWGtCM0xhdVNEMFV4SzZEUWNnNU1jX2Z3MjNXUWF2OVRZLV9TVzA2cWI0MjNLOFJGbE9PZTBtQzQ0d3hGZHNMSEpacVpjejk4d0JnQWxpNEItTHBZRXNRSUpmZ2llRno3WGo1dmZnbWVTSUo2MGdtSFlYbjY5Z3c?oc=5
panjang artikel: 3635

Fetch isi artikel:  18%|█▊        | 455/2473 [16:15<2:35:09,  4.61s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxNdmZPNnBpdFE5SDFVUmtFTXZsM3dxcUhIbUJqRnNIZGJsdl9iUzRNQUlJS2VJVldVaUZsb2Q0WmtOSERWMndIZjB1aGpFelFPZ1dJbVRjREt4VnNrV0xGOXVHSUhIMl9jRGpDSXhMTXZBaWRmaG9Ed3FUbkNITkUzc3pCTjRCWnRPQmxMZXFkZE1MdHZHdGtONWxhTjA4UjN5enh5QmVMUlhaZjdFWHYwX1pBaWtyWVFj0gG4AUFVX3lxTFBkYU1qa0xsa2xkZHBURDM0YnVaQlNqal94eU5rcGFSN1lPVjBuU0w0TnBuZUVFS09pZi1wSmZrdG9ObkFhcEVuYkh2czZRZWttR05SaVl4UWZ4S2p5Um51UVVpdVZUaGdtaUYzYVYwNU9lc21BRWN2bFN6aW94ODMzeFI3R1p6QkNqY3hWaENkbVdpclVFT3VhVDdvUG1SM1hQZV9EM2VmX2RGazQ0eWdiWlJsQVNXTmg?oc=5
panjang artikel: 138

Fetch isi artikel:  18%|█▊        | 456/2473 [16:22<3:05:15,  5.51s/it]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxNQUFKLWZpMFpsa3JkOUI5UzlmcEpJRkQ0QzQ2UVY1cnZEbGhhaVQ1dGMtRW1VRlZXQUpvM2hIZGszSHBjSXQyRVYzNDNYMTNOSFk1ZVJYSUhVYlRTN2FHaXhpemo0c21tOWQ3VzJPLUJPWnE0Y2YzdGZiZVNUV1Q2ZGM1VFVHOGpqSElySUhZeDh5a1hYWFdWLTNZNl_SAaIBQVVfeXFMTmRzUWUwWGpIeGVRVlFjaFN3QlQ2djNDcFYtUHJmSzhhbU5WczloZFFYYUZsNWloSHVuY0JBNm96NVZTN0tfT2pINjlaNkJXVHJJUENmRmJ0djB0MkZCeG9uekt1OTV0cGVsY1JISXl4VUVScUZzbldDNDNoQU5qMkF5ODBKWVV6ZXNKRThnV1psRG5JaWV5RGUxa1NsOXRHWDBn?oc=5
panjang artikel: 137

Fetch isi artikel:  18%|█▊        | 457/2473 [16:27<2:53:12,  5.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMiZEFVX3lxTE9XM2xxemxodUxaN1lPQk1aeWhNQ1VnX3RlRGRiRTBSM2F5YURyUDlpMVE5Z2FfRHhBRkhGOXlGUERyOWV4dEZKYXFOMWF3MTFvWi0xb3NyOTFqcFZnY3JGUHJfaU8?oc=5
panjang artikel: 8106

Fetch isi artikel:  19%|█▊        | 458/2473 [16:32<2:54:01,  5.18s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxNQ1hHd0tXNEZjeXB5MWFyUl9pMFp1anRoZTdZOGZtcE9RR3BjU3hlYXZ3SFAtOTNERUozeEx2SmVnLTc4THBnUC0wZW5hNDhYVk1mRWlORGtzQXU2NHVUdzBmM3JBRXRUR1NocHhEQlZXbGVod2RENXk1bGJGR2d3WW1FMjRSbGozbXhvMnJIM2lBQjh6YnlUZEZoM0FzTXdhd055bDViS1JuV09kSDhOcFYwd3dZN0RvRk9IczR4cw?oc=5
panjang artikel: 4418

Fetch isi artikel:  19%|█▊        | 459/2473 [16:36<2:42:55,  4.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxPbWxBU1I4YTE4WVp0c2UyZ0FJazRoMUZZOHU0QjJUVDhMdnBPUGI2UEU0Q0pxX082ZU1iV1hPbFBDTVAwVmNTN0g1alR0ZXpiNks1Y2JuS3Bzc0lXZ2d0eExzWS01bG5nMUpVd0FlR04tTFRrRGo3a1RVUTdfR3hzazUyZ0VCRC1DalVBUFJkeWozclY0VE9Zcy11cXZuLUpNeHNrN3oxNnBzX2FWeGVCWjhDdHRRUQ?oc=5
panjang artikel: 3879

Fetch isi artikel:  19%|█▊        | 460/2473 [16:41<2:38:22,  4.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxQMUoyeWd0ZkZSZ0ZMTEZCemxvQmQyUTNXNm1LbDYwc253clJLNG9KV0FpRERhWVdwZDZQSExaNXVYMXJqa2h6Y3VKbXFIc3RjVFJFVHBGT1BzTzY1UjlNRzFMVlVZSl8zOGV6OVZSNEdHQm1rTmR3LTVSZHFHTzkyUklZS2tGN0owVTJmd2M5WTNDdEYwZm1neXhyMnNua2FIWVRvNFdFQzN4dEc0MUZqVlpjc2ZxUU9YdklteUJhb0NYbm_SAcsBQVVfeXFMTjF6SFV5SUNzbzlXZlJWQW1zY01DM1Z4RkJ1RVpBeGdFQ2VEd3AxZFZRY25mZEhUcGxLSGlaemtJZjF3VVQxYTZZeEt5VTlnVFdab3k3WDhwSG52QkM2NzJoelY4eFhKQUw3VnF3VFA1dnlaQ3ZUU09tVDkxWEFaNElsN1RoOU5OTmRZZnZTd29CaU5PZDQ2b1AySE9lOWM1dDBsOWdkaVRmUGVuT1FfOG9yS2ZtYno0dlF6bEV3X0hjR1g4eU9Qb0xiQ2c?oc=5
panjang artikel: 1898

Fetch isi artikel:  19%|█▊        | 461/2473 [16:45<2:33:59,  4.59s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxQSkIxVjh5UGZYdHhMWFg5eklJS2xlQ2QzX3I2YnBpMGk2ZmcyaVE5OTVWaDdLU0JKWmJ5c1ZfX0NoS3YxU1lrZlEtSEJhV0dxTG13SzFKSWt5TVVCS2JueGcycmJfRjl2NGNfS3lMaHptZGJpUmFFSXkya04zUVpnS1lNRUEzRG5qVzJnWkp6LUJYN2VPSkxSbnFrNElyZG5kR05lUkcwemhsa3UxY29veTU1U2I0OXRyWWY3dVRn0gHDAUFVX3lxTFAxUlpLNk1SQS1TeHhmbERGU1E3ZmE3QWprN29HMEIxaW1mSXRwY0J5aUVTSFU0cnJsTVh1eU5GdVJOSy1DSU5aQV9LM3ZKbTJqVmUxaDl5OVdJbWo5eGc1amo1VktwbDRNY19hbjZLaDB5dXc2eWU5WnlDV0ExLUhtQ1RHVktudUlKaWItaVFLMXE4VDlPWWNKeFNtYkVQNHRPbFpPVGYxR2V6dTFkcXZQRVBGYVRtZmcyWVZCaWlISmVPWQ?oc=5
panjang artikel: 133

Fetch isi artikel:  19%|█▊        | 462/2473 [16:49<2:28:32,  4.43s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxPenpoanRlM2lKWXZFMmpQcExXNXdIQmNtYmFVS0ZlanJSVXdFVlZ2QXJWTGx3RE12UWg5djRaWTVUcWJtU0Rya3A5NVRNRnpMalpiajlTaWdRaHlGbXlYSTBfWWtjSm9sVG1sVGFYRVA3SzFZLWV1TjN0UU5jSFhJa0lNX0FYd3ZYcUpuM0N5bVhEODNqcm5UTUxXUXY4cGZXd2ZJeXV4TzRqUi1iU3Jv?oc=5
panjang artikel: 2407

Fetch isi artikel:  19%|█▊        | 463/2473 [16:55<2:42:31,  4.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2AFBVV95cUxPLU9uenBBTXE5UHpDaHo0V3JXMVdUYVp0dUtfSWZqT3R3OVVLWHU2Y0duOFVDUGhzOE1JR2JPbDJZYkFTdFYtT3VCZWhDSGZOQlFaWHp0emtNMDN2aFlteHB6a2NkYjR4NjBtMHljYmtwZGY5OGJXMzRMM2NzdXppVW02cFhVS1YweDR6QWpmcDVjblZoVmZhc1BCekx4NVBxNjdBZHlCSE5nQlQ4dFFpMFlPQy1TQUtQSVVWdGZFbUk2RXA3YnMyLUVnZXk0UXc1bG9VYnBRWFDSAd4BQVVfeXFMTjJIS2VRbF90M3E1c3NiSVdBZ3NRbGNqYno5ZUhWblRpcXhzN0tZeGdXc3pNYmxEU2k3VW0wamJWZWlQMWpPX2liMXZDWHlLZE1wMV9sa2dHVjhIalIzTUp5MVlUWm1RN3lXOUY2OG1LVEhtSjlCV2ZkVS1BVU53SWVOenhFZF9aMFJoaEVkRi1NRUpPY0lnWEZjQTRvMnVvNnZ5X0Z3aXFKc3VULTVFa3luUk1NcDBsZlFXbG5zN1R6WkJVei1TSXdCWjVtbzBhZUFGLUhVVHpJTHR4eTNB?oc=5
panjang artikel: 141

Fetch isi artikel:  19%|█▉        | 464/2473 [16:59<2:38:12,  4.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxOTkhwdkhNbUV1cWZsQzQzV1UzSG9GQzczTkNqZXoydTZRazh3Q2gxVExJQmhOTW5CbTF1V2RSM2JkMzFqdTZFeDNIc3pqTEEyZ2RYVHhhV25DSUdIbUJxeUZYZkJGZ3NiMFJqYW5uanpabmNHVkdhYkI3UkcyaDk0bkdudHA0OG84NWNWTXpNNGVHdndhMjA2XzA3dlZ5SUN4WDFIWW5NOXN5T0QyVDlzSWUybTFKNVdfcXUzWFJqQWZZNXZTcC1veFI4SjN6cFk?oc=5
panjang artikel: 3421

Fetch isi artikel:  19%|█▉        | 465/2473 [17:03<2:26:17,  4.37s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxNNVM2Zmt6ZXdjZWdyMVczaEZSTy0wM0JuNnNwSkFYZEJ1bEV5cEMxb0VjalBUNEE5ZDNlN2NXTWVac083MkxiUS1zLWVqMFVlTFZjZmZ0azlRWndFWGYyYzI0YklkdXZKS20wQjR4V2tqVVF1Mkt4Q01ETHJtbXExamc1TGtFeE13RlE3TzRTUXlYVG9ERDRpQ0pPNjk2N2dQZVk0Uno3MDlTbURaZ1FITE53?oc=5
panjang artikel: 8309

Fetch isi artikel:  19%|█▉        | 466/2473 [17:07<2:25:59,  4.36s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxNSnM4TjlORUpjTW1VWVZtMFNsTDFVUEVQR2dpVVktR1c3ZWxJMDg5MmtEZ2pQNjJVVlpwemcxNTBqbHVNOUFmTkJyeHp2Y092UV9SYjhYNWZhaUxMZ2pGSHQ0VUdNbF8zMklLa29ScElZcmVFSXc0LTFPQl9JRkwyenlydVo3V3RidlpGMHJKeUxaNFcyTm9tbXZzdGlmSkFXQTFtR19jSUl1V2lUQ0UwSTRnYmw3SzJOZ0VadWtXVFd2UjQ?oc=5
panjang artikel: 2531

Fetch isi artikel:  19%|█▉        | 467/2473 [17:10<2:16:21,  4.08s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2AFBVV95cUxQam15aWJvbE9JeEFJZjBlckQtZzhTNzVDMmloR2twb1VvaTdHVzZDRFFuMGktQms5LVM5SHpOWlNHWFUtTFJqalJZMTN3NTZXd25ySkFNYW16VzBZeGFvbnZPX3lUZno5cjRYZmhVMTVaYzRzRmkzdGJ2SU00bzNVMExRZlEya1pxSWNtMW5sLXFETFM5TzFwUndXRFhSZ0RCUlVmSkl1MDlSSmtOVElsOS1EMG5jRVYtSU9nU085Q0x1Wl94RUlpUnZmQlo1NkNWel8tQzVQRkc?oc=5
panjang artikel: 0

Fetch isi artikel:  19%|█▉        | 468/2473 [17:29<4:38:07,  8.32s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxPSVA3Zk9yX2syV0ZFV2dHMlR4dWxZQzJ4YWFBSjdFTXBuanY4cHF0XzNia3NRaG95ZXpQTEpDRl9SdU5DM3J0WTBQaUIyejI2NEZXelQ5S1A1M3V0aHI2M0diZFQwdk9UaUhjeW9xMFZkVm1hNHB4R1pjUWVjY2ZFcHQycVlXM3dPUE54Q05WaXpLb2V0V1hfUmVVTVhDZzB5dHl3Z1drOTM?oc=5
panjang artikel: 8348

Fetch isi artikel:  19%|█▉        | 469/2473 [17:33<3:56:04,  7.07s/it]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxQWTQ4aHJWX0NtVjcyS05xUVlnV2Jab29Qakp6OVY2Yks3VFVZY0JPcVZ6UUItejJQZ1Zld2ltak16OFduSGw4ckpxQjgwbjNNNzhpdWVPVHA2eEhZRC1pMEEtRzBwLWVoU2J2dm9UajJRZjZQVnB0X3ZvWUlUczJEMjE1V1dfdEZDVkg4eG8wNDZDM0pCam1UWktiUEU?oc=5
panjang artikel: 2295

Fetch isi artikel:  19%|█▉        | 470/2473 [17:36<3:20:25,  6.00s/it]

Fetching link: https://news.google.com/rss/articles/CBMizAFBVV95cUxNUHlPYm1kZ2xWNFgteWE0TE5YNWNDS1lXbWtKTW5HLXB4STNhc3JqOHpSWGU4WXRZWVdMTVJTRklETlhibmgzQ0hiWU1WeEZwSzdpMnlHclUteFlVWi1lTFNxMTNrRzJNMFZHamdON3pRRmNZMkhmTzItdUNSQU9iLWZTVnlLOVAweTFkNk9XcndWT2RJSnpSWV91RWlmNk1JSk1FanBMajRWSnN1NW9HaG9od1EzamV6RGhZT1p6X1pCSkFacU83NHRFNEM?oc=5
panjang artikel: 3150

Fetch isi artikel:  19%|█▉        | 471/2473 [17:40<2:55:27,  5.26s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1gFBVV95cUxORk9fSGFzMHhIdDR4RTc1bXExRUhlSHBheGlFdGZ1bTUyMURtQ1lCOVdaZVFNUzBySm9naVJKWTRjTVFkNGhvSlNCVDRMeTZQLU1UR1NpdmNvLTZ3d3N6ZkVQRWVkbmhYUkFKZFJCVW94Y1FvaHVPY3VZRHBuMkZwc2xCMW5lUl9DWVU3aC1lUUxjX09TRDZRQkJVQXZibmtrT01BeWFoZ0pMRG9pbDdMV2MxSUVGdzFCNHRnd2JETWo0M2hXTDlvU0dOaGNiWkhBSEZITEd30gHKAUFVX3lxTE9NVmNMM29OY1JiUTc1MkotUmpWZ0Q0b1ZvU3FJOVVHWHg0Mzh5cEZTSzRaRm1Ma25Va0hEbGplNTJIMFR4d3Q1WUhaTnRuc2ZYQjZ6bTV4SEg5VEdRdFdkM0cyT1hrLVlyR3YtMGhTWU1QRkMzcDBYVUJuc1ZodGRBNFQzZkxHUkJ4NkQ5UTNGYi11TmNTQTlMSVRWd2dEVzdQTnRfSmI4aEw5V01MWEZZNklfQ3ZrbkIyRFpFdFNYUG4zWkJoc0FrYlE?oc=5
panjang artikel: 2894

Fetch isi artikel:  19%|█▉        | 472/2473 [17:44<2:46:11,  4.98s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxQNExFbnZBREhiR0pEUFhydkZBYTZFaDVXZmdVbm9nVWdZWjlON1VzQWtxNHJUanBPa0I0eHNSVTdPeTZweThPTHV3TjRLT3Z4blEtQWpYQUl3UHl1RDZ6WEVSdEFYdmxqOUREeWxHTmV6eDNWZmU4YjFrVGw0UUhSS2VWeDB4YVZrMmRqTmdtcHUwakg4cFB1TG9XMWpPWm1Ndmp1dTRqWjRDb3g3RnZqOFpzQXpXVXVsUlB5RWFnOVViWUU?oc=5
panjang artikel: 4335

Fetch isi artikel:  19%|█▉        | 473/2473 [17:48<2:35:16,  4.66s/it]

Fetching link: https://news.google.com/rss/articles/CBMi5gFBVV95cUxQWDhpcXNlOXdzUWpHUUdVTk9uQlFLTnU5V2hkMU1xSVE0SGszWDRVcXJ4ejNiM0dEWFhMX2NNWjNPOHdLVlcyRVY3b2xtV0djSC1aZzR3STNFUnczejNVNlRESnk0U1RvVVdFZ05oYzVHcmVjdnF4TVM3cFc2TzI2azlTRTF1bzE0eHdXaFp5SGx3V2xZWXRUd2pkak5jR1ozZFYzY19vOEltcEJqaDRTRGswbjVzdE14T2hwbTB2b0NrYV9QUkNIenN4Z0NKTTZfNVh4Z3Uwajl4M2tXUjVuako3RkxyUdIB2gFBVV95cUxQd0hWMVpGYjZZRjE2RXJyMVlVOG0zaUU5R09INkVsZHJ6NHZGdXVBUFF6LWVyY3J2anYtRmUzUTBmeGYxTDlhNHA3SFlWMVpHM05vOUV6UnZVc2J1VFEzVVIyY1NmcXFTYTV1c25MSHc3VEJ3ZFM5dFg0Qmg2Z1BCWWlEcGJCX1V0VktfdVNGT3FWS1E4S05QTVpGa0llNTR2T0dHOHJpNzRlaHJnZWdCSnl0ZjF4ZUlYZmgxWnN6SzhzWTNHODZwNVA3UjZHTDJRMVNpclFMTWRydw?oc=5
panjang artikel: 2057

Fetch isi artikel:  19%|█▉        | 474/2473 [17:52<2:32:02,  4.56s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPdmwyNWxpU3JiTFNFb2EtczdIbTUzdUVwcl9JTndyM0xHSDdSTEpKVHREMlh5SkNFUWF0SGNva0dHR1FtTnNNRXR3RE5GSzRCWk1wTnJhY2JVb2tlazZhaUtuQWMwOUpxcEp4SktxRDc3VTNOLWViVXZFV3FzSkF5X1o3bm1kSERGVUVwc0s3clVrN1UxZDEzRlYtMldLQzdsM0NzOXJrb25Bbk9HTnBfN1dR?oc=5
panjang artikel: 12230

Fetch isi artikel:  19%|█▉        | 475/2473 [17:56<2:24:10,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxPV3YzdXh1M01ObUV3cTBHbndHX254VkxERG9fRTdiaW5JNS16Mllsczd4cGtSYTI1SE9Qb1UtdldJajN6TW1iNmI1c2lzWUFPcXlRM2JTYV9za0JYVFpKbHFnbEZzeFM4dXE5T04zYk9IRDhsa25LQ3l3U1NNZ1RZTXFBbTNTVE53VGk0bENIakJDMU5fZDdqTThLSGljejlsYzhBeHh0QXc4dzBwUXlJR2c1ODdwTkpSbkRkVVZBMkJ2by1zZXfSAbgBQVVfeXFMT01BNFZRM1NwMGxZYnRzTzBMdEsxRTUwQkpTRXExNDhQV3doXzVxMFFFYnlUMEZ3QUQyX21WV2RBQXYtekFKVlc3ZHpwSExWNVlxRkZHaTJZdWdXZUdnMTR5SHN3LUFHMjN5R3JVVVhjVlUtVk1KWkwwdkFLMkYtQldjUElQY3RTSWFwU0hxZDZHN0xnLXJ1NlVsSWtoSnZ5UEE0OGlCVE5Semx5MDdDNDZKWllBVm5XVg?oc=5
panjang artikel: 3561

Fetch isi artikel:  19%|█▉        | 476/2473 [18:03<2:44:19,  4.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxPa01NTWd5cjRKMG5acFNwTFVUUl9NbXhIMGFwaFJjZkNKcVZ5dXpDYUU2QkNSWldXY19tV19FYmx3ZFhEMHJPcUtLeU02YWlSUGNWNko5UkRqUFRvZWZwQkZmNExRb1ZqZjdTdUx2UWlhNjdubHE1Zm1sTHNyQ1VnQ2stZTA1dk1SdmhLcTE4RThIYVRwUU5zQ0hxZG5BMVBGdHJ2NlhZWFBJVzJjZExGQdIBowFBVV95cUxQRmFEVEMtYjk0TEo1MXRtX2xJc29oZU1Vb3VqQXdRQ2NkZktDRUVNZmZJeXduaEtuTDI3TG4zeGt4RGVPYi1PSFBTMzZKMk9vVFcyLXh6TXJ6NzJJd3VGSnV3UDRvTGt3anlaVDlKUG14a2tyNVF0V004QXFuSVNUa3hjS0JfTlJfYWRuN0sxTE8tZWVmeWNGZF83QlJCU3c0aHgw?oc=5
panjang artikel: 3514

Fetch isi artikel:  19%|█▉        | 477/2473 [18:06<2:33:54,  4.63s/it]

Fetching link: https://news.google.com/rss/articles/CBMiywFBVV95cUxORW5RRDZYdy1abjBKQ3c3Qnp0dVl4QnZTSUwtYkcwVTRCZFFyb2ItbEppTUV0STBNakdEOUVFYWRSaVlyem55Qk4xYVYwWnVuSlpmaGVFX054M0sxdTBjT1hjMjF3REpqT0xzcTJvWm1ScDl5QzVxN2FJbzFsX1k3cGYxTHRieVFvTWp1V3VSYXYtRjFVR01UQjZRUEtwQkhXSXpZOWNtVm4yRHRUN3BHZUtOZ2dqdWxYckQ2SS1QRzEwb3dNdllzQWFac9IBuwFBVV95cUxNanFyTkZueURTeUZiUkxvbVFLZ1RjSTBVQ3JIRGlxSUMxaGozOXY1MTdFVFlZLVZhazBFVjFGaXo3UjFSQW0wNi1uV3pTZzd2WTJxQXNONlVfNWNoLXQwaWxGZFNiTDAtNzNCYXgxS1htOEtFeFBrZnhGaDFsTFpjaFJHSVBMZ2tCWFJxck15R0VwbENMeF9zVmFuOFpsUTlob2dSVVlGY0Q2MUt5aEgtcnNYOExWNjFZZEUw?oc=5
panjang artikel: 3456

Fetch isi artikel:  19%|█▉        | 478/2473 [18:10<2:24:46,  4.35s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxOeHk4ci1reE9RNXl6bVJPam9Kd0I2TDBRaWJwXy1nd1lRUmlHVmxETVA4YkhPdHI5WkYyaFhaYTJTV2l6V1M1TWs3c0JVMVdaaVJRdDh0S2dxQkZ0QVVHaG92MUlNVzlxUGx4bVhQX0huWGg4bFdkSXN6cXFqbURRRFhHRXY0WGtjbF9KYWJrdEhvMnhYd25YR1c0STRFQXBCODBIU2YxUEFzMFRIWHN1TVFJZm1KcEotdW8tMDJ6WGRLUdIBsgFBVV95cUxQdFVLdmxMOUY2V0xXMHU1RTFGZ1poSGhpajBsc3VsZFpIMWdnOVdwNUFKTlVsd1VONFVNYVNoYV80SWFETDBwQzlSMld0dUQ1Smg1eWNQQnlxZGkzT3BYSUxVMlFJUThFVWVNYkhCbHVpcF9yZXA5Z0pZcF81bGh2QnZqakdYU2hRdGdsdWJqVEhFeEQ0M0xuNlhwNTRrTTNyTGdJZXY3QWJ2Nk5lY0YxYm1n?oc=5
panjang artikel: 2304

Fetch isi artikel:  19%|█▉        | 479/2473 [18:15<2:25:50,  4.39s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxPbTF3V0F0VWJEX1RWSGlFS1lJeHdNNkhUcGhKdmlHcXlyckRTVGZkZjZ3eF96V2VhclhXMkxJNTJGRmlsVmlKZjd0YXBGUXJwb0wzMnB6NE5yTWgwWWlHNk1UMzFMM1luUk95YkZsZzk5UnQ2a2JlbWJzbzJFWWtSakwxQlUxQ1NMSjFmUjBsTElUYW9UY1VDRnV6bHpVNW51dkE?oc=5
panjang artikel: 2649

Fetch isi artikel:  19%|█▉        | 480/2473 [18:19<2:23:28,  4.32s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxQNGZrcXQ4anZqZ1RhV3lmNmQ5TFBrMmd0Y1BzbGZEUDAzWVBkX2FnanFuTHNCc2E3UG5UVGZUdlRGUDlHSVlrVC1GVjRTV3hkQTdDZnFiS0hIVG9XN2RwNEkxOHMwTm5oX2RFck8zTDR0VHVSVk5pWDZ5a3lFTWJ1SzVVb0dBZm1XaXB1bXBsQ1ZtdGExaTNlNWh4RXJ2YjZhTFFmZWgzS3J4a1N1VWt1cU5VVjVJakxoOU15dGUzSWM?oc=5
panjang artikel: 2048

Fetch isi artikel:  19%|█▉        | 481/2473 [18:23<2:21:33,  4.26s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxQWGhiSXI2Q3RxVWd6dEVWRDRCamtIa2hiU0RFX3lJamlHYWE3bzh1MDQwRFNybGZ1XzlWWEVjak1DeVNNZUlDeU1kMXNXd1hkSXVWZ0pPOHdYcG9YU2ktSVZFbDdaMF83NGM4UXdkRlhPU0hicmM3aHJuRzJUSUxpLU51NU1kQlBrZUh3cU9ST0hUSzRfSGxYb2F1MDBuQ1BaNTlQUFVuOG1EMF9tWXYwMXpPWQ?oc=5
panjang artikel: 1655

Fetch isi artikel:  19%|█▉        | 482/2473 [18:27<2:21:18,  4.26s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1gFBVV95cUxOZXVYMlZYMDdpV2daNlkxT0lpLWZXb0ZKYUFkLVBZRTJ4WDRkaUtET3lYZ2Vwb0FEaUtUczB6akhPYzVJTlUzY3d6NWdIdnVvWEFON1h0TUdGMW9LVC1SY1FXWER4dEpPcEhmWXlYNU5wODQ2V29GdDIzWEJrLXB6THdudzh1akhkVFdFOVVOaHBhMmg5ci1ubGVXVFlmam4tSHlmZFNRWHFGMVViMDRCMFlDYTM0U1h5dXZUSzJqRHVNV3ZTaEdzRlpnYktLN3VKTnJiRmFn0gHIAUFVX3lxTE9LdzVfTmpKaGhCcVhqUkxZRHE4QThYRk11WXVSRE1jWFQ5MzJoVnpvdVRsTEZXSWs4d1k5THYzS2pVVlJyWDV1cGQ1UmpPdGpWQXd5RGlWdEJmbldwSTBqSnBHR0R6SlVVcFU5MWZNYmVvU2lVaWZGYXBRV0VnNm9TN2NEWlgwT3RpblBxSlJfclFLcDVZOWxqS2p3eURzcjdkZkdiRVRJVm03a3MwUl8zcWU5MFNscVowT0NNMU9oemUyVDFINkZm?oc=5
panjang artikel: 2806

Fetch isi artikel:  20%|█▉        | 483/2473 [18:33<2:37:46,  4.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxOTHhQYkMyaDk2X0w3NGZTVUg2NTlRVWdLQ1hYdGplU3lyMUpwc1lqVjFDQ2l5dFQ3a2JhMDdEM015MElKbzczVThQVGxMemJ0V0t3RnZtVnVqMUZlWDItNTQwUWEyRXV1NU9TTmZNSDJ4b0hpY1dBWVZ4QS1sSEZad1BNWHA3YzR0Q29EN3JaOUVrZ1Q3RWZENFVIeEE5WDJWRjVGNHNrSXc1TlR0THNOZmNZSUplZ3psSlE?oc=5
panjang artikel: 2749

Fetch isi artikel:  20%|█▉        | 484/2473 [18:37<2:26:50,  4.43s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3wFBVV95cUxNQUFIb2xGQXJDV0lUZWtUNDdDbFFuQzNabmdvcVAzNU0yS2ZxTUtYQThCd0xKVEcwdTc0ZVdNZEk0M1lJUTc3cm1Xbnp4dlNsdXlEdEVOMTl2RThLcE5OaWRQam9DaUVMS3JHbU9FdE05dmlDbDU3UkZic1FQWDJhaVc2R3FoWE9laTNuTGI1eTNPU1lVVjc5TWdvbkhmWFh0ZkJ4Q3hkVHJBUnBfNjdFVzI2VG5ZRzZOaFlpbDBrZVA0cXd5em9IMlg0aDdyZHUyd3BiaUMtNUkyelBWRXhz?oc=5
panjang artikel: 3983

Fetch isi artikel:  20%|█▉        | 485/2473 [18:43<2:40:33,  4.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxOOVRQMEtFZDEzOXJXSjlPb1F2eWM4dWZVWGo3Q3pqb0RDdy1SYVdzWWtQYmN4ZTg2Q1FMWmdLNnRXQzlEbWVSNUZsRHloOHNQODl0Q3pNeEZqV05PZE1VdjdMNU9xTlFoYVZYcUtLNU1Sb2FfY3MxeThIcmlZZTRlRXVPbzBHN2NCTmRRTjdDbjF0MVJLZklJWGxHVVpXYjk2TGVrZFRTSdIBrAFBVV95cUxNTURyeHB3RGJaVDVOMXhuZWRlZHM1ek9qM0d3ZUd1czVWSVhfelU3RzZNR2xGU0NDY1VuS3RXcnpIeFlncVFtMGhuY0ljLVYyMnZQd0E2ZFZQeTU3OWd0eWd2dVM0UXhfY29aSTg4UWd3MnhRcXBkSENCV3NneFZ3WmFjbklUVWt2OGZZdUc0TUJ5a1RCYlk4RmhVVlliSkJYLW05SkdpX2lSWFpR?oc=5
panjang artikel: 2240

Fetch isi artikel:  20%|█▉        | 486/2473 [18:49<2:57:21,  5.36s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxNMlFUMnp5eTA2UnFfdG9sNkF2UUZPUUJPdy1EdlF3enRLTjdjaWxNOG84VDRvQW5XbF9uQ3dYOGZCeUxmeS1WbVZ6T2dsN3VXazF1amtvR2RCUllYdFlmMFFVUWlHU2RFSW5MOTE1Zjl0QURiT0ZVX2NlMGJzNnFWaUlNc3VvdVhMYklPVVlLM3pYMEE5eEFiZ3NVa3ptU0RqM1ltMUQyNVJtZ1lkLURn?oc=5
panjang artikel: 4601

Fetch isi artikel:  20%|█▉        | 487/2473 [18:54<2:56:06,  5.32s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxQSlFxbTRFV2dBUjNOYjBYZmFCRlltVmJFc3FJb3hjODJrOWgzTldRajB4QktnUkJFN1p6RmkyRUw0MlNpT2I5SUE3bGFSQ1Npb195aDVIMVE0VnNBVWxXLW9iQWdILVUwcUxLQ1gzLU9QNG5Ga01uY2JPQWxjNV9KaVA0amducFF5N1l0SjdoX3hGYkVSTGM2WTAxRDVVX3A0V3pNZVNKc29KVExha0FuVE8ydjZURm8yU3hPclRTQmhUMmRMTUlvLU9JWERsdEHSAdQBQVVfeXFMT1JQSVN2dk1SSlMyU3FmRVc4eTdPUTNJNTZXYldMTmtyUkFXUFFzN2xHRHNuRDdGZjBOY2JoTlhfOGFTN2ZoWm4wXzRQTVk3akhreERVWnhDQzZ2NXFIOFUzRGZpNXhsSVczWW5nU1lRRkpxYURLR3A0aEZESDZxMTVuYVNHUjlXTkkxN3hOVGJhNVJ6bEF3aTFfdVdQT1YwMWprYlBTMFV5M2tWTFJJbUNpakxLaHdJanMyaGl0YU5wZjZzZmtWbDFISVctdWl6UDRoVXk?oc=5
panjang artikel: 0

Fetch isi artikel:  20%|█▉        | 488/2473 [18:58<2:37:26,  4.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxOVC1Ndm9uQktoTUVUMDN3a196cEE1d3VyY2NjcnBGVkp5cEdIWTVxWFJkdEV5Z2hMeE54elFrN21DY0xEQnp2emJLeXZKWEJvUUpDUFlrOTlsbjFLM01LR3NzZ2g0TVp4alVqRXZQblFzaWhzVjFWSFZYNlkydDVFajcwWG5FVlo2NTJaUmNkTUdndmhmdERELVRjakp5N1MxSGp6SzI1aGwxakswYm84ekp5NzJHNUNk?oc=5
panjang artikel: 2203

Fetch isi artikel:  20%|█▉        | 489/2473 [19:04<2:54:22,  5.27s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxNNjBON2Uzd1ZPcWpkUmJvOFA5LVFfeXYwazA4NTJRZzBMNW1xUGxndDUtejFMY2hTeXlpeHZTdDRMNXFCV1F4WUVsU3JieXpXdFo1ZmNwUloxZEstVHpJUUcteWN0SzJhU2JnekNTSWRBVkFucjk2d0NadDVRbWM3LWkwd1YySTl5VEhUSHN6MGNuYzJJMHBjaGxVOHg1QzR6UU5IWVdDcXFaSFg1ZzNWQlluS0pBQm5Ic2xIRmlIWFNSOWxVTEZGZmpPblppQdIBxAFBVV95cUxPRFNlX2IyOEJ2Y21DQTlrNEFOTWU0LXZ5dnl1OVIwbGJxMVpjUGlrQkRKOFhaV01Pd3MyWjR3X3FiblZkdy1Oa21XZlVfZ2dCMXNHQ1ZXV1NDWlBjd09JQlRqVEgtZ3FKUF92ZUcwd0FOMC1aalFmZkxEMmhhRDdfNnlaZ2JLVnV5alBTT05HUW02QlppTkRYMERLU1p5VmNOOUluSjVrREpqbzRqVVFxR0hrSGxheTZKdDFUN1J5ZlRZY0JB?oc=5
panjang artikel: 2521

Fetch isi artikel:  20%|█▉        | 490/2473 [19:09<2:43:44,  4.95s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxOTkF3d3VmSHZsSFhuQlRSNHRfbTBUdVlRaDZIUEJ5Mk9FcWZEeWNpMllTMW5rVkRMQUFGOXVaalpNLWtiMmFxcHpXMFJROEFFUTdLQ2pzYUpqU0tLYXZ4blJYbThOQ3doZkxGaWJIZEFhendpMkl3alJlUkQ2NGhHeE1rMk8yYWZNeGNFZUNsMmxTQ3A2dm9VV3h3dlVzOWZZZnhwSzk1RFlMWjFZVEdXaUpydVY2YzA?oc=5
panjang artikel: 8251

Fetch isi artikel:  20%|█▉        | 491/2473 [19:12<2:33:35,  4.65s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxPMkFsUDU5dGFFU05TMDlQSkV6c0RYUGFvNURBX2NzXzdpVUhITnZwVXFhLVAwUzZnSTN6SGFkWjBRbVdaTjVZRk4xSmlYd1daQy1Jd3BMQVlUVVFDY3lZSlRoX2YwZ1ZEci1TQk55SXk5Smt2Y1J4Uml5OXRib0lkYjNmNTZoaVhpb0JNcXY4cGJrZzBWVzhqTlg5TmNuMk5QaTVXSHJHdjRuTE9SSFlITlhvQ3EyQdIBpgFBVV95cUxPVUY1VWhTT0g5MG9aaVF6d2tJVG10Y1VpWF9sUUNsOWR3dVRwQ0Y0ZnI0OFRUZ0ZmckVqdC16TDQ2Zm1UQlNBdGpwNEpNSXkxcnJCSTAtNDY1TkdtQmJvb2dBckRCYmtDVWYxdHd3dFNFRkRTMzd2YVY2R1lkZ2phNnNUdXFZM3IwdkdSQ1pOQkFHbVN2bWFUYklHb0tOYl9FdTM1ZklR?oc=5
panjang artikel: 2395

Fetch isi artikel:  20%|█▉        | 492/2473 [19:17<2:31:32,  4.59s/it]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxOSmhLVkY5d1BYS0l2aS02VUtSbHFpVTJGSW5QcFRlb0tSMXdZbGd6RjZUR0t6TnRTUzNHZE01NDNicGVXRm1zZDlFbWJHX3lybGMzMzRqcjJzcm15NHRKTDNGR0NPYXRiNm5YQ2xzVjBhUjBZQ3FvaGZ6Q2VpMUFRekJUZEI4LVNGUlRvYi1UbHIwWXpLQ0hVN3FKOUI?oc=5
panjang artikel: 5747

Fetch isi artikel:  20%|█▉        | 493/2473 [19:21<2:22:59,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxPN2ZUVTQyZGFTT0FnVlM2VTJreTk3UWgwcWNJMEo1SUJwb0JabHpZeXduZXoxYlVLQ2k5bUxtQm5jTjFvU3NsckpSeWZQMlc0VVVRelhZaWVCVFh1U29kel9neldTQVN0TS1aMjN4VFJ0ZV9QTFl6eG5TOFhvWm1Zb2dWTlFhQ0pGbFFwaHdkVGVoVzJ1cnRQZ2xzRk5ld2pTTXZfX29xZFZoOEV4Z0ZybkRSc3pRcGx4MDNsazZhSmFLcTlldFJIdFVyUl9ITU91?oc=5
panjang artikel: 5309

Fetch isi artikel:  20%|█▉        | 494/2473 [19:24<2:16:19,  4.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxNMEJZUGVseVZvTFNBbm5lWHZWS1JCZ1VRbmNwOFNTV2xKQzVxQ2lSNjZ3ZGl0N2tDUXlXdkRLdzc5WXB1bGVfcHVzdDFZcHpPaVBWa0IwNWhZVndUQVNKaDdHWWcybUgxYjlFdWU3Vk83Y0k0b1plcTE4cEJPSTFYUjRLYThpZzhyWHdwUmpnV1RZd3duOTVEUXoyQ2MwN0o4TkRBa3kweGNKN3VnSDNpN2p4SUtmSEEtNEhtV2d1d9IBxAFBVV95cUxNeXo1RnFGSmhXU280djlHUkpfRklBclFIa2kzWkxid0YzemszbzF1NGN1c1J4TXlnZE90ZkVJVVNXVkx0a2dPcFAxS2kzWlliZkxreElRS1l6OWotZXZBaWotM0s2YnpyZWFXVFFhOG1iZlZ4LUZrUzF0NmhMdHVfdmJERG03cWRaVGNvX3dMaFEyT1RfM2ZmT0tHMVR3RjdEdFlzbGR5bjM4VkRYTndZQ3hKUzEzYnFxdFZlTkJlZElfZ2FO?oc=5
panjang artikel: 3566

Fetch isi artikel:  20%|██        | 495/2473 [19:28<2:14:19,  4.07s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1AFBVV95cUxQOTVSOVN3Z25UQkxLZGRlVnV6azlQenVIN3V6VE1PRzItT0g3QW0wemJIb1ZJcnhYRUw1NXEtZTRxMGppYjlWN2NKS2lwUXZCdlpOZGpZb25obHh2RkpBbjg5RjU2MFJwbWRTTGtIYkdlcWd2M0RqSVF2TTI5YUNSa3hWNDRQdWhaRXh1Y0g5bFFUQ0tBZzBuVzhQcm1jUXk4ajQzY3liWnZWZlo3MU9Ob1lDY18teWo1eEdJdnAwQ2NiUFAzWkhIV1dJMzlQSXlkZG5sTA?oc=5
panjang artikel: 4248

Fetch isi artikel:  20%|██        | 496/2473 [19:33<2:16:14,  4.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMinwFBVV95cUxQa1NtaWZyaktOMUhtUy1rMndSeEE0dWw2S050aGRwZUdPbWI0WV9jdHYtVVU1bXc2V2s0TkVWNG52RS1QaDlkVVRRTTFoSlotV19Yc1JRdC03OUdlX1F5WHByQk1GOU5aeHNpQTdrU3FNS2lCTHRqZ3liRTRqcElsamI0dDRnQ3hBYkRxeGRQTEZ0aGRGb2ZweWxNZm93ZXc?oc=5
panjang artikel: 5684

Fetch isi artikel:  20%|██        | 497/2473 [19:38<2:27:34,  4.48s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxPN3prM2pNd0tGci0tYUUySnUwaUJJaEVhUlFZVGdPZXh5SUg3WGhqRXBFYVBlclFGcGlwdURnbHp0dU82WHdSTU9pOVdnU2FPbHhhRGhxcU1CZXN1NkhLRHM3aGhWTlBrZkctOFJXRE4taURONnNSQTNpeGZhaG5kQ1RFQVZYZC1VQzZheDk2R2w0b3dPV2RPZFYxRVFSMzhvNF9PbzRLUG5iSDllVG5RZmJkbTU?oc=5
panjang artikel: 4705

Fetch isi artikel:  20%|██        | 498/2473 [19:42<2:22:46,  4.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxPX3ZxbDhlOGZQVGprSUxtNEhSeDcyZnJmak9UMzZNbFBBYUJuOUp4aW50eEVGM3Z0LXhOckZWSnZsYV9NbldKWE5xTWY0cDBFbEhwc0pTRFJMclZSRWdKcTJ1TzlTaXMyb25RZE5TeDFDaV9LMHoxZjI0YlB0M0laYXJXbEFDTzJCSVhsX0JmM3ZrVHRsdTM4NVJuVDJobVR1TzNzUFVJWTZuZw?oc=5
panjang artikel: 2508

Fetch isi artikel:  20%|██        | 499/2473 [19:47<2:26:50,  4.46s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0wFBVV95cUxPeFJaV01abmU4YmpuQkRnYTdic1V6bDg4cmNCU2V3cDBYOTJOVVZrYUFiOUNNWTVwWG05cVI1dlJTbVBjQ0NTRWhHU2huTXQ0amVab3VKMkRzUHpxQVQ3NzRFRVEzQU1pS2U3S1Y4aTlaSF9CalcwRGJCT3h3WFZiMWdfQW5xejZnbTFlU2JsNVpsTkw2Ykx4bTZuNmpTeWNPanV0bXlrN25VRUZZajZMYkZGVXN1ckt1MTh6a281SjhucGtyRnB4ZjZaU1B5VzdJbWsw0gHIAUFVX3lxTFBLUUtzQ0FfT0FQY1ZtSDl3ZklKQjdSUjZpYjFVLWMxTlJ4UGdyanMyektMc1dvWTJDZU5VcXI1d216MXZubGxjSkd3bVhTakNpOUF5cm1aN3hEb1l4TzdKN3JOTlZCQm5kbmpFZURBaWxJbFc4Mlg3YU9GZVl5UEVZcDFMVE9qZVEtTjVfZkZoUm1IVHNDalhpUGQyN1hlNndLa3NydFJNeVdzR25TZjBVVElPVy1lMUN2Vkl4M2d6bk5pQ0JyMUJl?oc=5
panjang artikel: 3270

Fetch isi artikel:  20%|██        | 500/2473 [19:52<2:31:56,  4.62s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxQNndxZm1CdEN3VkZXLUxJUmlWVm9EVVV0eHBkTlVQelBZbEp1a1RLYnNSaTR6bFR3RmM2WTA4UW5aTGFwaU5LeV9la3E4ZDl2QmtzQi1xa0lTS05Ic1EwTmlkX0F4Q2hjVVVTb0hUeXlVYndvRmJQUmJzSzEyYlVXYWstSWdDd25TVTBOdmdOdnZUMFFJUTFfSDlvdWZxOGNTa0hsRnBIbmVFV2J0S3dIMS1n0gG3AUFVX3lxTE9pOVZiSjJGZTlubTFMQXdReUVVallUcGh6cXkzX3FfT1Z1dVJHVGJiZ3dkWVFWVzExcHk0eERURENwSlFJQlBfYUdHQVVEdW5oRFp2OXNCOUVnSGhxTEVqNlZRbXVTRnozdGRIeVdSZjNfTi1OZlhOVUVKLUltMW9STlFoVl9MVXFaQ0xZdzFqVTJoM01yRTZIX3IyUklfR0hUNlU3S1F6SFFRRXhob1E5TWRhRlJlWQ?oc=5
panjang artikel: 1856

Fetch isi artikel:  20%|██        | 501/2473 [19:58<2:44:51,  5.02s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxNeEtjNm1HQ2JmY1pEeDJkUjhuUk9qMm04cGpNSWtQUXlvOUN5cll5by1RZjRYalY2Tm5FeElqTU03UXJibV81Nll2MjIyOWZBU3k2aFBRUEE1VjIyanI5a2Fxdmo2UW40bXNualVwT1RhWDhaVVZDMDFXZy1sUGVWUlN5TTRUNFVnM2hZUFJGSGFzTThHeVhTcTVfSVpmS0dNa3c?oc=5
panjang artikel: 1834

Fetch isi artikel:  20%|██        | 502/2473 [20:03<2:48:11,  5.12s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0gFBVV95cUxNNFBUZWdFNXZmNkQwdmFRVUYxRFVRU0ZpOXh4MnhJS1BCSEl0blBSSlpPa1N1Y2o2azN6Mk9abnQ3SzZwRVowTG1tXzFvYTFRUW1TdW9LVTRmWGtvY2lJQkJpSWpqUG95SWE4LVItZXZuWXJCYS10Z0M4cURhZWNiUzNTaktaLU5qWVNJWkhPZkwzdmFielBiN0FHeGdSaU9YS2tkUUEyeVRibkVPd29CeTUyYmVyNy1LVTJMbjJ3SFcyaGFPVXlkUWM4aTlYY2NDamc?oc=5
panjang artikel: 5091

Fetch isi artikel:  20%|██        | 503/2473 [20:07<2:38:21,  4.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMi5gFBVV95cUxOUkJyMVhjeUFOSFJjNFJ2Yk5zRUVkcUtzX3ZVQW1rQzRJXzFaNjV4dV9KaUh4a0ZRNFZUVjIyb1JfVm84V0cxR0lFeE5zckpvSmJuOUpOQjNVWVdnNXV5QnFfNlVXQzlBcTBnOHZOWXM1MEhhcHp6YVV5c0Q2cklTSkxfMTBFXzVGaUdDdU4zY01rRUhrVlQ4YU9wZ1hNajZDQnJxN3ZFSGlvNER4dTBzeG5lUF90MmJuS1V3SXRiTFo0MGZIb2QwN1hrUU1wTUJ5U1hyalRReENuaFNRTFA4VXB6YV9wd9IBzAFBVV95cUxPSzBqSHA1RjJ5QzVRcURFNkc3dTU1Tm5pU1hDMlQ0NFN3U0p0SkJCeTV0ak9qdzktRm56Z1BwSElmWEFfdERGcTJUMGFDT0x0M0tGSGFMWnhubmtnVGpLN3d1WmtBazV3Rjl5VHZ4aTBjOGlObUJOVEhEUDJmNWZhZ2pwT0prMjRtTVB3djhBM1JYLUs5Q3JBV1oxYzktQXNrbGFZTGhhVnhzYVVldkRNU1JiaEotb3N5dWN4a29KSHBsMDNYQ21mZDlMaFI?oc=5
panjang artikel: 2162

Fetch isi artikel:  20%|██        | 504/2473 [20:12<2:38:59,  4.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxQQXZnbE9WelVKMVNHM3VId3gyM2ZyVDlPV1paeXlHSDhQaTRjZXZmdFU1U0J1cGdOYkQtVV8tdVFUQzByWnNjRkVram1UeEsweFlEMzJQTVhXZGRmSGJtdjJLYlhydWMzZ3RITHlsM2xWTTBJNzlMSjBPdUJyYXF5cDFnX3RJaHo3NXJYcGVTeHdxRW04ZkNGRV9aQUxmZFVjZE1Ec0x2czdnZjZ4VzB6aGNsVnQ4Y0NvVzA5WkVmZXhWRUlBTkRrQ0JaeDljdw?oc=5
panjang artikel: 1523

Fetch isi artikel:  20%|██        | 505/2473 [20:17<2:39:16,  4.86s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxOanpQWVVHVGt6ZWdDNFNoWGstN3Q3VmI5WGZwaEl0WFdiem91S1NrTWw0TDl4bElkVGJZeE5makVZTG1QQUFpZ2hIYWdaTm45RVdKd0s2aWUxdnVubVlyWC1JcGNvZXE0Tm9CMGczVS0yb0w0R2FoUHFPZmE2MHVGUzBNM2FlUFFEUGxiMWxseVNzSTQ2Q1hBLVAtcm1jaE1lMVgzcVUyOGNiZ0FBSGRwRmoxS0dqbjlEVHBlSnp4bWY?oc=5
panjang artikel: 2442

Fetch isi artikel:  20%|██        | 506/2473 [20:22<2:41:00,  4.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxOeFVkSVBwU3U1czduLTBONVpjMkxscEN1RjdTcHM1QjRrQk9Vd3l0akV6VzFtN1hWelFldGQ5Nl8tUnFadFJhVldGRk4xQ3hWR20yeHlMOUVkMlRmVHFWRG5ScXNDOTUzb3BpSDMzaFVSdWNCTnBsWllBODZPeGVoLWM0U2RvN3pBNEwyRmlndFlXVHhJVHVoVWQyWnZ6ZGhDOGhack42Yl9jME1aMEkxcdIBtgFBVV95cUxNQXVaN1pXbXgwaF9VMXRqcDZKeUkyU3RNYmRKTUY3VExDaHRialcxR05idDJPWWN6MkVLWFRWYTFlbE1nNE50YTcwd2p0NUduNF9IUG1YaHMtbmNaQ2YzTUktaHZjVUwxSHRXcUV4U1FxUTAwZWNoNloxVmJYc1VNdk9hVUhETzgxQjVNaHAzX25jU2UzemJ2VXlOb3MwT0hiaTdOQjVFX3V6WU9aaDFkR0ZrWlBYZw?oc=5
panjang artikel: 2411

Fetch isi artikel:  21%|██        | 507/2473 [20:26<2:33:55,  4.70s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxPdmlXbGNfSFpEbTI5VTJuTTZldTRMa0xsWVROV01NUzN3cWxCSE9meHhrREVuZ0V5SHNZdU1tU241OVVCQ1Nvc0FyUDI1TTNjY0dhNVJFcm1Vc2wxUVFleHFBeEJpTW9rbE9ReTZ4MHYxcmU2MnJDaEZoUDN3cUFYOTFoM2kwSWFvLXVtblI2cWZZbUlSNG9QdE8wZm0yRXlCemRpOG5wWmZGbUVyc3R0b2N6enN2cGZoUFl3ZVNKSQ?oc=5
panjang artikel: 2871

Fetch isi artikel:  21%|██        | 508/2473 [20:32<2:44:17,  5.02s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxPclI0Sjg5Qmc4dE9WdERVYUl3RXVRWEpCcklRRHRabXdRWVJJdFdHVU80RnR6RzBoX1FiUHctZFRwbmpGQXNES3RpekR1eVNSVzVvTk10RjBDenh2Ym54WHR5RW5XMUVpYnNZQjR5OXduenZBMnpPQ251OVBfd21jWUhWZ1VQaVVkSTM4OThBWFhsU1J4TjVMcFZKTWlyWDBYTzNTalFIck1GMUs5TUJzSDJWVXozODNaUlJLYmFiUkJaQQ?oc=5
panjang artikel: 2809

Fetch isi artikel:  21%|██        | 509/2473 [20:37<2:45:24,  5.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxQVENVM0VUQXV6ZVBheXl0dUd3ZDFTVDFOVFVZbVA0ckVab3Y1RUlMUnlnMHlRa1lhNXE0RnhUZmo3VnhSaHY5aWNoYlZKLXNhYVQ4MllZWjRBb1ZtSmd1c0RuaXowOTVRNWZJdm53VUdvQ0NyOVRpc0JnbTZwdnA4VXJVMHlpNWlZazlPQ0dEMlVFQ1dEdHZBN1RjdUdQZTlYZ1IyU2RSdG9PbEFyRmdB0gG0AUFVX3lxTE1UV1FiQTBKV1R4Y2NtckRWV0hPVzVSZVdMcWlURlA3aEdtYUdXd3ZWS01GN0YtLXJuQU1BX2RlRzgzRS10al9LUTZQR2dJYzcxR1RLSEdROWFXUWtvSmRmZDNTdG9hVzlJRDVYTkVqdU9HeDJKZDVubmpESnNQWVB5d1h0aEdSd2ZiQnBmeE9reF9TYnFKQlAzMjJzZ3NFdWRNYS1pUEpzM3JyNDdXWEY5WlJrcA?oc=5
panjang artikel: 2131

Fetch isi artikel:  21%|██        | 510/2473 [20:41<2:39:26,  4.87s/it]

Fetching link: https://news.google.com/rss/articles/CBMizAFBVV95cUxNbWVScmt0YTNLdXNQNl9yS3NqLXVfRnNwbG81c2pWU25xeFhkMS10eUNBcjIxX2t5anZvWXdZQnJ6YzE5QnA5cDROU0NXY2FaWFJ0d3FVVHV3eUZ4SHlYUm9mSXd6cy1ubDhGeHlMM2VYQ0J6UDVHV08zM29WZ1dZREJNM3JEeWVjMjRwWkpQNnAzNUNQU3F5RWxDMTVsZUNmc3d3ODRMVHB1NXZRZkVBZXRGdG1wc1hJendKZThvT2dKaG9VOGl0eTlEUVE?oc=5
panjang artikel: 6010

Fetch isi artikel:  21%|██        | 511/2473 [20:46<2:35:44,  4.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxPX0h2bU5DYXpmdFc4NVhzajlfd0NObmJoZnhWRllObktYdGNjSzVNUF85RmZISFI4U2tJYlpkdkltSmxadl9lT3phcmIyYkdSWUMyTDNpODVJcEc0TlJlZkF1ai10Tno3aTFqdEx3UUFpN2drTU5VM2VlNGg2bnRqcHI5Mkd3ajA5cl9aWnJvd2xIcGhfUTV0ZTZGU0E?oc=5
panjang artikel: 0

Fetch isi artikel:  21%|██        | 512/2473 [21:05<4:58:40,  9.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxOMjE5ODhHVW5KM1VmbUZ6c0xyOHpUTW00Z0tEeGRkZ280cmVVa2F0OEhiS2wxdll6ajNJLVF2S2RIQ2ZKZUd5Nk1ZUjRFRklDLVp5TXI2QmxpQVNQcW1TVDVEbGxKNi10dTBYVW1rZVpacWJJc3llbThwLVd6Yy1ocnZBX0J2MVN6b3ZnS2kxb2tyRHJDMEExRC02ME5Uei1pSHlhdDlLRVhkWktVMDBTWGRrWmQ2Z9IBuwFBVV95cUxPV3E2T2hxNjYyM3JpUjdrTVo5ZXFJM1ZzRnVMZlprMFZjdGxyejg0cEtKUUFFNUtqNmhkdzZSbGQzT044ZjU3cTUxcmNvazlraVpXTkFQMXBSS2VhT0h1Z2lDaUNCV2xpS0xDNHZJajF3aklMOGRYZm9FWjFfNmNKcnFhOHluNXFkdFJEbGtsMWJKSk55bndiZUJfYUhxZXlUbWxFZm9RYmpfa3lYQ1MzcTFLRGVwR2wyNS1N?oc=5
panjang artikel: 0

Fetch isi artikel:  21%|██        | 513/2473 [21:09<4:10:33,  7.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxOLUU4M2NfNzUwZUpsT29SejJYWl9vVlZleXpSS2MzVjBOZEJYTmFUVU9zRENPTTBOZ3FXYWFXcHN3R3JWdm53MzBQYWkwUWpzeXBQOEw0bzNYdTBtakRQZjB2cVVfeWNaTHhvd3htenlncERIc1Vodjc3bWxoRElOQ1I2bXdqS19RbFpyN3R0czgyVFV2WlgySEEwMHphUjJnVUtrMjhHSFFoYWRWdGh4cw?oc=5
panjang artikel: 2295

Fetch isi artikel:  21%|██        | 514/2473 [21:14<3:41:50,  6.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMiiwFBVV95cUxON1hOR3JlUkxFRlRENE1rMEZ2VFk0dzN4QkdFQUYtMDdPTmZRZTd0TVpBdlF2MjFFdk1wSjczYk1tNzRBQUZoRlJyVmJqYTlMaWxmTldsaF9FVXlnV2puVDN4M0Q1VjZHcXlyWEk3OWVaNWl3RTNZU2I1U2ZZNjBwM0s2QnRtdWpOUkRj?oc=5
panjang artikel: 0

Fetch isi artikel:  21%|██        | 515/2473 [21:29<4:57:36,  9.12s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxQbDNKZlZ5dG55OWwtTzhBcGRhSUtkQVByNFlzXzRPUTdEdmxZSDlSTGUtVnFOSGhCTXpwWXdKbE5vQXV4QW9ickNpN3FaQmNQbk5VQWFlYzJjQzFvZW44cl9ndjhwbmdWZUhod2M5SGxSem5aZnkzREN0bmV1NjJXTHhpM0NfLWN3c29sWkU4QzIyQ0JHQUZRZU91ajFFRVBDYjllbjN3dk12UTRHOENwWHpPdUxhYlF3bmNGcGl3ZGLSAcYBQVVfeXFMUEIzZGh1SmRWQno4Z2h3STZXTUdyanVXTlh5ZFhoREpvcUk0emt0SDhsZGkxUGYyZm9Da2J5YldvYTdKZDVnb04yOEd1VE54MG82RjNEVGhxTlNXWDJ1d0tpWTJtWGpVSG9qYnRfQ2ZBMC1XRmYxdlVJbGZTWF9fTGxoMnZKZWtIaGxhdnkzbDNndVJMRDdGeDkxZ01Lbl9OamMzXzdJOVBBTjQ5ZEtCbWFsSmotVUhHWmFOS2NZQUhnZ1hneWhn?oc=5
panjang artikel: 1736

Fetch isi artikel:  21%|██        | 516/2473 [21:33<4:14:00,  7.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxQcmJ2QmhvU2J4MDlTRThZQmZtdUs2Wjh1UW5qckJnblF1dDItSlZfbDNrTm9Tc1hOS1plbVgtOW4zWF92ekVGdW1hUDVndmYxR0VGSEg4bUxyWjFHbzBnWjJEWmxpM192VjJZWjJkVDNIbHJ1S2ZDcm5mYklRZ3RrVHNROHBkaXBKUWFlS3V2TGJ3SWpqbWZlNERXMW51NHdIRXNZUnhlRW8xNV84d1dfYVE2VG4yUmlRaFNj?oc=5
panjang artikel: 3514

Fetch isi artikel:  21%|██        | 517/2473 [21:38<3:38:44,  6.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3AFBVV95cUxQQkR2Ylgzcl9STXlNek9ZUE9yU3Z1R0ZoOTVmakZWTUFmcnBybU44ZDF3SmxVbzExVGRkcEtjU0M0NDRnVWtpMkREdXFMOHFNNU9rNDVHOXp2MFotdWlSc190Q1YxMVJlMFJJek5Xc2JKd0J6cDYwVlg3cWFNNURiOWpWalJSN0Q1bXVZUUtGa3NGdTNOUnc3ZG41a09rdFJFSEg1OHJYUE5tMDQ0b1MzMVVXT0EyRHNvRlBpTzZDTWY0UmNnTHdtWi1nV0NPRmU4ck85V21oTTlTTGhv0gHSAUFVX3lxTE1mVTU0M2tNMlNNQnFYMXlYUVcwS0pNM3VTRTZVbWxkUHJzYmZqNktDUHNvVlBvUGN6M2NYODlpd2JiUUxEX2o3OEtTcjFQMVlDV0xtM2dnWTB0LUtVX2d0a1JMQUxSUElidXpTR2NLbTMza2tsdkhUQzJ0RW55R0NBSkxQaXpTYlFxQ01hQTNFbnFDOTUwTDI1WTNKcnpOYnNYS1huU0ZYUzZLU0xna05xUUZ3OGVnUGVEdllFTzFSMVBROEM2ZGt2dnZyOVI0X000Zw?oc=5
panjang artikel: 2126

Fetch isi artikel:  21%|██        | 518/2473 [21:41<3:08:26,  5.78s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3wFBVV95cUxNa29oWHBaZUZic2Q5N3kydkNiMTRZRlQ0V3ZqdXJneEZfczRKSUZrc1pWTUZfMzRjN3N3Umk4MUQyLXljRjdFZWxDaXBzcW9vaFFnY01ac1J4LVotQlpFTnFYNlBUdUxQUEVCb2Fnd0F6Q3B4QzVURktMa0d6ZjlOQlEzUm5yVlVDaUZ4SEU0UEFMd2VoN2w0cW1PbG4zZmVfbVluQUtjQjZzdXFSTHZYeWVHamhaOUlJUVVGMjRwWVJlWm5uQW1rb2pLTEp2eXdZeVZ6TWcyYWw2ZmMwQTdV?oc=5
panjang artikel: 316

Fetch isi artikel:  21%|██        | 519/2473 [21:48<3:20:24,  6.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxQNk82dnZ6SG9MS3U1WGJXbVhHdzdpS0ZjZ1BRUTB5ZzV5eWtXaExxdTViNXhfZEE2a2dCTmJEem5ZeUtvck4tSUVkVWxBaGI2aTYtekYzTEFXenN2YnMxeHNET1pJNW9lQi11NGNDdjdvVEpaUE9HbVR6LVhucjdjTFdYTUlaX3lyWmFUcHpwd21xR3g0LWpVUG1CUzNrUlF5NWUzeXFqQkJkaWNh?oc=5
panjang artikel: 1522

Fetch isi artikel:  21%|██        | 520/2473 [21:53<3:06:49,  5.74s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxOcER6NFdRWGlQX3pSbmhhM3ZSZm16dFZNQlNKdHFSMjE1X0x4ZllpdGJhRGc4ODZLUXJWQ21uTjJDUURnV3pfZWdUY3IzTF92eXNuaUhCTmdxWHY4QjF5aWUxZXR5VkhpM3hBS2JTX0ZEQ1NIaGRoV1F6WWdKaUVhVzd0SGk5ZXJ1MjhSVFg0bW1WaVBhNWNHUXJpbnktbW1ZS3lsOFlBMkhEOU52eGlFa2NWSW1WUW1raEdzWjJ3TkRrODVqdnVzR0UyU0thcmp6dmtsV1pwZ0k2eGPSAdABQVVfeXFMTW1tQUtITWhleWN4Y3lBbE5sRG1YeFdKWnBzM1VRd1AyZV9HWUdaeVNSVWt3UVVVQmdkVWVBZXZlcFU3c0ZwR1hfYy1nb0FnbnpZOGxhUmdGbHNhY3pESmxKNHlzNGVma0FaUS1rM01KdTdpUUUxWkxfM2piVEVLTGFlUl9kMGcyd3VxbHFlNFhiemtQbFdzMmc2dkJ6TWVIN0NIbGdzTmU0dzlDMWp6WGlZbFRILUJqSkRYT2FDNkRaajhaR3pxek84UXZjel9rTw?oc=5
panjang artikel: 1711

Fetch isi artikel:  21%|██        | 521/2473 [21:58<2:54:42,  5.37s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxPVmlSY2h3THBJR0l5d25RMy1Ddlc1ZXk2UVVOQi01cURsZ2p4MnhwNjkxd1VYQXVKZmhFakZmVkx4X0RvNi16NzQtTWhfZDdMNUZTVFJ0M20zLVd0R291ZlRDYWUzTEJWSUk0Y0xXYXJGTlJiWUp4dGk0R3BtcmNibXF4NnhlalBMUW1xMndxRUJCVnMtUG1Qbl8xMmdoMEJFQVg0UGljc2c?oc=5
panjang artikel: 3711

Fetch isi artikel:  21%|██        | 522/2473 [22:02<2:45:29,  5.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMiowFBVV95cUxPZnVwUE5OX2wyNHJsOUpIYUtkQ3kzd180S293cXNRd25lUU15cGJCd0JOdGxXY3RRaGZVOE1GOVVpaFNJU3FlZ2pERnhHT2NZS21XWC1DY3BWSkN3VnhaOE9nNUJBSjFwenlxQlR0VFB4TjNLSVdOUmMyZ3NucHlpUG1iMTFGbXZJVVRKU1J5X01IbEphSHJOMXNWckthR1FGaVFV?oc=5
panjang artikel: 3118

Fetch isi artikel:  21%|██        | 523/2473 [22:07<2:46:19,  5.12s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxQdVI5UGJaeVVOdUhtZnQ5cnFTbWdSc2xEY18xQ0p4VFFIWDB6OGV4VDRrVk5LZmgzTFQwRnR3VmEwS0RPU0lYQTN5SzZ6aEpqanZwSnlldjhudHhRMFpSUWRkYUZ0cDB4MHRsZi1KZlBHQWdlZXVLeXdPOWFmV2VaR1huN3dUVVZkRTE1QUpoNGYzYjI0T2ZuOEF3WHRYSFFQTEZsdU5hSktJLXFiQURpUG1KMDdfcXhDdUUxdnU5bUJOY1VD0gHKAUFVX3lxTE9vTGdSbm5aclNXWU1kc1pXbk5DX2dXb2ZseXJjbjR2NVhlWEpsb0ItS1BrLWNaWWY1STBkcFYzd203Y0VDTlNSTk9mbzFmYWsyWjBJTWlkUGxlWTZhcUZjeFhsRUt5aHNTemhhMVNIalc1dFlVMm1oYl8tYmFIdmdNTFdlSnhNRHRMeUVHaFlacU9BX0FCMGhJaDA3Q09NR1A0aVpjcHBiT0JMOG5BZ2xGS0Jlckg4c182aHRtWWxzWS1iZ3BXTFI4X3c?oc=5
panjang artikel: 5968

Fetch isi artikel:  21%|██        | 524/2473 [22:11<2:31:52,  4.68s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxOMExudFZjeWp4ZTlRbnR3NEVVMWdjZDhVZmF1cklaR2hhdHNvTVBGQXZyTkplaENBSkNOWHdJcDJic1pFOURHY1NMZkZNMzlPNGVqWnJwVHVJZi1hOUkxUHZ5TUR0bWZ0ZjE5eU5EYktXYXBITHo0Vjh3MllPUjZQSmJHNnA4dENMMTlKUE5XRHl6WnFGXzBFWGl3?oc=5
panjang artikel: 1372

Fetch isi artikel:  21%|██        | 525/2473 [22:14<2:20:53,  4.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1AFBVV95cUxOMjQ5c0w2c3p4ejJPSFY2S1JfODg5d2hYSWhKMzkwQmxxdFRjMFI2UlRwMndjV0EyUVRad1VHaWpNejNYTE1PX3A1REtqVWcxLXhXUDZWcEtUOGFjdVNjaU5JcVB5THhBNTFucjhsVmNKY0gybUtZSm9May1TQlpwaWZnRXRpZ0t2TlRmOWxxSW92UzZfT1dLU202bkNjdHNBTTNac0lZNjN2Y2U2X20xLUtuY3U0NElWWGF6dDN1a2Nwd2F6NzlGTlVXaTNyd2FtYVdfdQ?oc=5
panjang artikel: 3216

Fetch isi artikel:  21%|██▏       | 526/2473 [22:18<2:11:40,  4.06s/it]

Fetching link: https://news.google.com/rss/articles/CBMijgFBVV95cUxNNW9ESkRsVWV3Mm1TR0pWLUl3V3BsRkExbjNfV3AwTmlCN3RoWERfUTBkS1VFRzBDTVd2U2xCSnZPRHVBRXh1R1RDanVBcmJieUxRS1BFMVplQ1FCM3hzc2ttM3VyZGpXVUlaZ3RQOHE4NVhpS1gzS0RQVXFsVkZ3QmdmVW0xRTViVm5Kalpn?oc=5
panjang artikel: 2123

Fetch isi artikel:  21%|██▏       | 527/2473 [22:22<2:14:47,  4.16s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxPWWgySnUzb3pZbXhCSHFVR1lDSHJXbFRmSXJtVVE0VUE5TGxEQWplLWpKbjBRNFJ1QzhCYjhURUlPREhkVUhtTGhxaHhDRXFiZGc0OHZXRWhuVTlqSGEzQ00yNVRsMUROZndSWU9qYkNMeW5LV1V2b29VcG5wWHd5SFZ4YTYtRHZmeHFBQ2RPcS1pOEsxNGFyRXlXYjlMMVQ4V05aZ2RjQTg1cDd6bUphWnBKSU0wSmNETHFBd2o1N3PSAcYBQVVfeXFMT2Q1VU5USW9Gd1lrcmZacHg4anBySUo2eHB1bFIwVF9uekdIdkJjWnZTQlZ1Vjd6MXVvY1RHYkMzaU1UODdoVTEwU2Uya3pBQ21UblBaWEdRWnM1X2VWd1pZZjFMcXpjZ3NOUEp3azVEVnpUN1pZeVlWNEdweFZGQ1JJMDRaQlpsaDZ0RUZESjNTN2RPbUljMVdqaW9icmdROUlKelFhZUUwR0RaUjdxbW1fbW56am5TUnM1OXNlV1k5alFiSThn?oc=5
panjang artikel: 6551

Fetch isi artikel:  21%|██▏       | 528/2473 [22:26<2:09:05,  3.98s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxOazhTZnVJVEZra2VxcTYyME13Qy1SOXdNUVlBZWwyZ2lEOU13aGI3X2dvRDg3N2hvRHpZVDdlQm83Z3NqRmF2QmRYU3J5RGNCZWpjQ2MxbXRlQ3N5NWJlbkVzYWpxbnlLMjBVN0F5VlJSZ0RfazVSZjVZTXFDVHFJNmlqSTJzYlRHSkJVRW1HdTNRYWxyY2hiWGdmT2V5aFM1NC1DdFBwaGtuNDBuZXNMYm5NREtsdVk1MjViUlAtbmNfbEtr?oc=5
panjang artikel: 5787

Fetch isi artikel:  21%|██▏       | 529/2473 [22:30<2:09:28,  4.00s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQSTVqUjZjWnY4ankwTmxTcnUxRmM4djFYNXp1c1BCaURTa1BnckM5STNRQkp5MzduQnl6UGZEazRWUklPU1JHVUJMSTVaY0ZXb24wUldSaWVNS2Y4TVlRYm05NmtJNUZoTW1rVWhiN0QxYU5zb2tsVkNYbHBMR0JUdl9EX2E0MGt1dFhCellJM3RPbTBkcHN6dndwMWU4VTdpQWxhSHdTeHF1Tk9rbGh6TWhlRTk?oc=5
panjang artikel: 2555

Fetch isi artikel:  21%|██▏       | 530/2473 [22:34<2:13:42,  4.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxNdHA5akZ5ZkdhcTlzYkh5aTFBT3ZUTVFKbGFadTdqTUduMldsaFRmQjUtM3NxeEtjVXk0SldOWVpKZFJsQ2VoUjRHSWNIdXEtRkRrLUdaVkcxai1ibTBaTFF6OGNQN2ZIMEVHS1lSZm1lV3I5cDdEbUJMdFNRNkN6U09lVzQ1X0RwVFpKdUhmbERERjNHb19ENVVBUHA3bGtFQ3c4WTlucmg2RDZKRVVWNGF4SGxiVFlPaWZQTVRVTk5aaUp3LWt6dzlFZFNLQ0U?oc=5
panjang artikel: 3181

Fetch isi artikel:  21%|██▏       | 531/2473 [22:38<2:12:07,  4.08s/it]

Fetching link: https://news.google.com/rss/articles/CBMiywFBVV95cUxQTDJDZ0JsSzRYRDR0VXE1Y3dyelNzbUhHbjA0aFpyMXhOX2FCdkVMelo5X3kzZi1aZkpqTTRlZU9KZ2xEcXo4eExlMnZIWFgyU1hhZ2V0VHNuSk1kWlVna3JUdFcydHVyMlNQdUE1RXNocDJCVmpFS00wTjdaXzNUNEw1c1FSM1JKVW50OWxvLTVIT1BESThabXRDcC1OOEpTcFZTS1YtQkdVMDVjZzNQWUVsR2xQTXphOGF1U0I2N3FCU0JnWmRSRzlPQQ?oc=5
panjang artikel: 2591

Fetch isi artikel:  22%|██▏       | 532/2473 [22:43<2:14:27,  4.16s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxONFgyanZNV3M5V1h0aW1yZUU0dnBvVGs1UTJqNFJCWDl1cGU2U2VOTXhkQ0xJNXdRZ1NteGs3TnlyU3VoZ2FCLU1pMjZlSVJVU0RwNnU5UnYzSmhyZ2YzTmluclZtZHUySTJhemhtU1A1TFhGMXNHZXhvX1BjbklqVVdwa2xWN1NyaVMwbjFyd0FiX3huLTVvWVFYeGpLVnR4MnFHb1VWSjIxNE9LMkE?oc=5
panjang artikel: 2865

Fetch isi artikel:  22%|██▏       | 533/2473 [22:46<2:11:05,  4.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxOekQ4NkV3ampiU3BsNENxQWdEYVljNWlVVEl1Ykhmd2Z1NzV5SG1NSU9IRUdrOVhuMG1PUnZPUXlFeFRtRkNxTXREVXIxbnhwQmhZeFZGdHpPem5WMVN1TXZiZEhtUWFMMDFsQ0lGaDRsSzR0SkNVYktla0xvaGZCR0JzYmZhVzY0WEdVNlRYWUFNbUpQUjNkeEk1NEJWWXd1MHBOeW1XZklyZ9IBrAFBVV95cUxPcjAtaGtock9UWW1lTUVSODVpbTltUUZWSW1fSFktWm1ZZ0huWEMwQm1UYzJFOXZNbzZaMFdydlNjdGVTUV93NFlXWU1sNUp2OXluZ1BVUkJGVEdFdzd1TktWMENuODU5cTR2cmdxWlFGTDhIVWZxLW03ZjVDUjBObWxHN254XzQyUlM2STR0MG5oWjdtSWloYU1oS0dPWFFLdmJONVF6aFRCUzhp?oc=5
panjang artikel: 1506

Fetch isi artikel:  22%|██▏       | 534/2473 [22:50<2:07:48,  3.96s/it]

Fetching link: https://news.google.com/rss/articles/CBMinwFBVV95cUxNbHdyVmVieV9xdEVzRERUMTg5SkZPcS1HZGdUOUt0OFhzT3Q1cWNIZXdTNTQ5MkM4bklUVS0xWFlSRUJYVGwzT0tsd1JMT0xETGE2UkVndm80Q1VJd2dPTmc5cmNyWEI2QXZldHlxNGE5VGNCS3ZsOVRRVHBzVXRWaHU2SzFQRHZRRE1SUG0tOVRHV2RtOUtXaFJZSHBFem8?oc=5
panjang artikel: 853

Fetch isi artikel:  22%|██▏       | 535/2473 [22:54<2:07:27,  3.95s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxQNkpjSGZLTFFsSktLYTl4Z01EVUcxQW5Yb3FxSjF5aDNEM2xtblR0SF83Z0JEQnpCQXBMYWFndFV4MXJfdzJycUxDMUtTak5JaldRZjYyamdqeURmaWRqR2QzSUF2MWhmQkcyaUg1aXZqZmxtS0tLTFBWWDlLNW96cEdHX2dnLUloN1Z4Tk1odHFpRTUwT05oV3VaQ3dIWUIzSmdHVjR1SlAxM09rMFRJ0gGrAUFVX3lxTE5qelpuTnI5RVVTMFQ0ZTVuSHVjVmNuSVgtTEJuX3YzU2RWVUVqZnNPZE9GQUFSQWZPWEZDMExSX2c2d0tkUEJNM0RlMU44RzNIdmtoMlR6bE1NeEx3a3ktVkpsTHNFQkhyanlsWm1CcFNVNWMxVl93dkxhcUJfWkpFMURVN1cwbU1vZTIxdjd6Q0JoWEpaYk9uNnpMQ2ZvcWVuWE5OemJmemx2RQ?oc=5
panjang artikel: 1361

Fetch isi artikel:  22%|██▏       | 536/2473 [23:03<2:52:48,  5.35s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxQTVNZUHJmNHM5VmI5Y3RTV2tsa3RuT0dpOVhocnFEWjFRTEsyZWlrc0YwVHF4Yjd4ZG94N3VYYXdOWXBWUVZSSmZwam44OTkxRkZUbVI0SS1Ib3BIZGRSVHF2cW8tWTJnYVNlLUhOUFMyNnRUeGlvcmlpSVhkUk80TW11Mk9YeWZBZG0weUhISXNXdnljWjVjeV80M20zSzFPd1ZxLXZSUDRMbU9yRU9MYmY1Yzd1Z3M?oc=5
panjang artikel: 1413

Fetch isi artikel:  22%|██▏       | 537/2473 [23:07<2:42:18,  5.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxPV0ZFMmcxQkZyU3Jzel90cUlIb05WWUF1a1VZZjhJb2lnMmtJSEhRMDFfX2VhWWNBR2pHRnhyenJqWklQTW1zVDk4OVZCNHppVGRGQkswR3VZM1hRTnpJTDhYeFMzd2I5MnA0SzVCUHU1Q0hBRTZIVktFcTcwWFZfTElNQXpaekNTak1tT25GVEVEYnV5M1lVYndlQm7SAaIBQVVfeXFMT3hUOFdpdU01WnZxTTkzbHNESXBsamZQdUFRWkxoNExyZEo2TGJTWC13aHZaNTVQMVRwQV9WRE1mYnJxYW9zMWZjaW0xWjJ5REo3aXZlNXZiWjlLdjcyUlQ5NV9DYTRQbEJPSGFmcHVuV25KV01JNjlka2czMjJlenRFUVA3cGNWZW1LSlRLNmRMVGpqUlYtTXFEeDhfdVFpNzBB?oc=5
panjang artikel: 4187

Fetch isi artikel:  22%|██▏       | 538/2473 [23:14<2:59:58,  5.58s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxPX2FyNnFlYzY5Wks2U1FyR2d0My1hRmhvcDZFTTkwVksweVZydTFqbkRRNDF4cFV6UFdiN0F1TGNPYTF2ekVuWUxXVkowejZpMWhzbEZnYW90X014cVZ3aG5vYzBKUkFMWktxb2RRNFlTTWRDcjE4OWVMQ1dXaE5tZm04OGVtOU1teUJhMFVPbHYxcVNnV3IwNnlxbHN6dHA5NndtbGwxcFdzR2ZodlVnTlgtTVh6a3JFRmFlMUo4Zw?oc=5
panjang artikel: 3052

Fetch isi artikel:  22%|██▏       | 539/2473 [23:18<2:51:34,  5.32s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxOalRnaGlaWlBhVDA5dkVFd3RGNTB4Z0VoVlRyeExIVGNfWTBSMUJUaHNXdENNbUVEU21PZU1RUXMta1otcUk1QUNUeGpjeC1Xc3dpdzA0WFJlU1d2RkV5bUkzUUROUFV3ZlpnYmtLYy1tb0FUc3VjTVdmWHVoSmJSQzJxVnpyNFJfa0tneXZsNV9sQUcwZVY2Qk9aZTVlUENpc3RBRw?oc=5
panjang artikel: 2737

Fetch isi artikel:  22%|██▏       | 540/2473 [23:25<3:07:05,  5.81s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPSzhPaDQ4LVlMTkJZMkxoUXU1SzJITWFmcEJOTkZtUE1hQl9BYXpLOF9JUDV1NE55VF85clNhWVljU3lFVWZiZ1EzajNzYjB4Rjg2TWttVU9tdHpFb3BDYVBESWJtVk1wS1Awek1DN1FhSEUyZWRDbkx6WV9CS3Y2M3pZN0VLUVV0LXBCQ1k3ZnlOS283WFdON2VIVnZpMEtIR2hPb084bkE4V0QtejNJbUd3?oc=5
panjang artikel: 5197

Fetch isi artikel:  22%|██▏       | 541/2473 [23:38<4:17:06,  7.98s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxOeHZvbHcyNENMeWlMTFRkbi1qYU9RRmFuNmlFYTRtRVhaNy1qUm0xWUlJSWNZUjh1bjVCQkI4TGstQ204WUFuQ1JyTU5oSGFuenNiYm9FZGwyTFh6bnl5VnBObWNKaVdKSE8yNFRKdF9MbmN0bXFxakJneDlPYXJrTUYzaGo2MTBkeG93WlRPNTRFcEwtemdTalBEUlBKcjZ6SmZhMWYzcjNJX1NwT0NUQU5PTzdjZGZqVmk3UnVKNDAwdlpXZ3dFQVF3VTdaZw?oc=5
panjang artikel: 4725

Fetch isi artikel:  22%|██▏       | 542/2473 [23:42<3:35:47,  6.70s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQU0Vya3lUdXg4RFpZOFVpUnJHM2ZFd2JWQnJJem51R2tZaEJydDJzMGtFcTZZTW9vOElhRDA2eGZBSzlNSW5DVmJJVFVTZkwydnVLN29PWTIyNTFSSUp5T1pLRDZabE9YNmZ6YnJ4VG0wRmZId2ZZeXJLTHozc2l0WW1vNkRCR055YUxfMEdxd2djZGJaazF6OGx6eHJXbG9kNkw3WTQtbkprQmpZVGlQVkk0VkjSAboBQVVfeXFMT0JZS3JKdXMwTzdIOVpxS3lwbEhpeVltZjQ0cDE5OW12OVhXSm9PXzh2VktPdkVlOGhyYVdMRy0yYUJaLXBhRU5Vd2dBN1RhZHJNeTI5UGxfb0dENk5lYlNTa3BfaVloTzd2dXFOSTVRRl9rczdGU3NybGZnMWtfRmcwc1U2NUpWcjhKVVBmWXBINVdLeENSOG14Y1ExcmROdWljazJSTGYxeFpxUDAxbF8tRE5MX0dLQ1Rn?oc=5
panjang artikel: 1597

Fetch isi artikel:  22%|██▏       | 543/2473 [23:46<3:06:16,  5.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxPUzFrUWJsWmg3RWFDTXF2QWVqVExDMWRDQ1VJSnJOcjFGZFlrZGZkOHdaTjhKZEtfM3NrQWlFaVdwanVDdTlUZmZjZ1VsSHJtYzlMWElFWW1nYmJ4dzFqZ0FhYzRqMUJPakNDcTBabFBhMWRITFIzZjhMQlpDQWZnY3B3aGhXZERMR1pzaHRfYUdOclB5ZTJKX3B2allMN0h6Ry1vbEY0WlBjY05PQ2pVRGE2V0s4U3Zy?oc=5
panjang artikel: 1906

Fetch isi artikel:  22%|██▏       | 544/2473 [23:51<3:02:24,  5.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxQUVZ3WDhORXdwYXRYUE9rNlg5bV8zZkxxTTNSbG1iMU1xOUphdzRZRG1yQXpGaENSLUpDamRPMWtwakxsZDBmMEZGNkJsa05feEM5ZXJIOFR3TDhjSlRTV2xDOUMtNGh2bXdSbHBKanVyZmlmNTRlMDhCSG5SVy02SlgweU04bFRJRThjVklOV0VFR0k5NHFMSF9NNmFhWU1kN181SEROMEJHeU82d01HRnRGWm1keVBDdkxyX3FB?oc=5
panjang artikel: 1711

Fetch isi artikel:  22%|██▏       | 545/2473 [23:56<2:58:06,  5.54s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxNVDY4anRJVHdlbEhaT1RoOW5PeGRsZExvSkZFdHNKdGZJanlIVU5TeDFDRDdhVjR5ODNCdWhPNWhPN0duTm9Ud2hkXzE3VkJScWZVWVBJc3FQYlRIbXI2aDNSUVFRZ2h3OC1NQkxlQXdPTU5hTjl5ODNHRllZUXQ3TmdLRFdTa0ppWnV4V05sVUVyazBWWi1ldUhuNUtGcWUwdGxacmRNMNIBlgFBVV95cUxQeURHV0Vwemk3dzZJekg0S01sbjN1ZWVBUnNwbE5JVzUzRGIyRXJsVlJ5WDlPRV8xSmlveGxjUnd1T0haTS1mLUVWdXFIRWtWWGpiRUVVVkExbUF3N0E0eG5jZ1ZBNEJfejRoSm9WNXRQRHJ2QkdnTWFUWXl4d3lld25EbzBPeGhBSUhUc1QxbVJISVB6X0E?oc=5
panjang artikel: 3057

Fetch isi artikel:  22%|██▏       | 546/2473 [24:00<2:42:19,  5.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxQZnZnNTN5M1cxcUI0REhCcWhaWlZIbVNMMWhpcjQyRlE1UUJ4eXlfc2xXUjhfMzdfQ1JrSURyZjBkbWVyME1URVRYczdERVEwSjZsY1d2VG5GYnpfRVdIUkd6UnNyT3hEcDdVNWRHSEs4aVR5cVBkSWdrV2syM2U2RW1rZWIzTUJwdTczMzllb0djZmh0ZUl2WlZ6MlhxZThoajdGbmNWOEc0LUpHWTlsME1XTEZ4Zw?oc=5
panjang artikel: 1992

Fetch isi artikel:  22%|██▏       | 547/2473 [24:05<2:38:54,  4.95s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxQZUd3Y2w0QUgxaURnR21BdFhxbHIzejJqRnc0RUNiVUZtTkNTODdfNms3cS1STmt0UU92SkVDRTBNNldGUEtNQi01UXd0ZlE3WjFTOW1ZMzFxaWVqRXpfNmo2d0pNQkxJd0Z4VmtJS2FBVUJDU1FVcDd5MDl5Sm9SS2oyRkJCcUpOVWNXcThFSFBNMDdyS1VMNnZIbk9zaFRXZVZWbmR5MUFYd3FxclV2TTRtR1doNDhMQzMwUNIBvAFBVV95cUxPSFlHbTJNQjR6WEloUXMyR19FYk1zcGpUTlRmekdsMEFXWGlOUXNVZHdnb0ZGcEt1eVpQNmZYOGlZWEZSS3hUbDE5VnE5UTRCSV91RUpJMW9IbkhoUGlyRHJxM3lPY1VpYS03eTlKdUlaSDJpZ0RTY1dFbUpuMjlnMkplYmNFUUJwVl9JVWZZdWpjWVlMcEdDb2IwWlZmQUV4MDNNblJqN0s1ZVU1bWVfVENtMXBLQkx3ZXlWeg?oc=5
panjang artikel: 127

Fetch isi artikel:  22%|██▏       | 548/2473 [24:09<2:33:09,  4.77s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxQMkFtMzBEaXB3NjYwNzJKcVU2ZUY4b2NvRzJwLVJsdEc0UER1ZmxWd1Z0OE1tNnJtVlVHQnZXc3hVd1c5TC1SR3l2ZmJHSTR4UWd3amhjazZ0OE4wR0E3MmJsRzBuOWdDMHRfUDcxdHBKSWJwVXBvbWN0M216UUlMUW0tVDNFeFktdV9mdlI0WkRCWXRnMC1ZeEZXd192dWlCenFTTmVXMXNkdW5veHlTNDR3eENJVkpyTzJBaHBR?oc=5
panjang artikel: 2051

Fetch isi artikel:  22%|██▏       | 549/2473 [24:14<2:35:12,  4.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxNQ3NfcWQ1Q1kzemgzRkZOT1g0X21hNEdSbHY1dWVwTGl5TkowcDZuS3VKY0hWalhuMzVjNWFqQ0RqMlI3cTBGUHZvZDgtWXJ1VzRpWld5WWRNSm1uNWE4ZFpCcHpjLUlwWTg5bkxvdTl2akVZNmpnX1VOMUZDdFVHZmtYN0ZDVnB4VURyX0pTLTdSSFlscjlOV1RnRmV5RWxodjdCblIzVTZxZl9YUWx5amJhZDdxdEJ0bkxMN1ZFR2djMG5fa3UzOU9sX29VSUMy0gHKAUFVX3lxTE9vWU1oazZNMllPRnFBVk44Ym81YmZrSnUzZEpjekdJU0NxeHdkUFNqNzBIV0VZS1c4SnUwSXhlSk1zQ1JGZ3BkOE9zSkI1NjhISkZLY3lUMlgzNXl3dExDWGdFWmpvcXVmTHdJc3UtelFvT2Q5bWxrZDZkcVZRTmg5bUZTTk9PRWVKNmxxd0ttdGw0MkZ6UUdjT1FjZXMwYmdMWHp3dEhDRlhEUU1QRWlhbWdUY1VqeEgyZ09BVUJiS0Y5TDlPRVZzbHc?oc=5
panjang artikel: 2284

Fetch isi artikel:  22%|██▏       | 550/2473 [24:19<2:31:12,  4.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxOVk5nTk9XaU9lcHZDcDU1a3RJbW1FX2FjamNUZDBVUUVZTThPQ3ZTZzNUMTQ4aG5RdWRpaHRjdWFISGxsUEgybEw5aG0xcTRfUlA1T0JUaFREUW0zN09uYTQ4WHpJUW03VGV0bktTWE5SczFjVHNJOU5ubjIzblBCWVM1NWNTU1hBS01RM29oM0tEb0FYVkhPX0Z6ZnlRSVpSbnV6a0owdWFETjJMQWlvMk9zdmV6dE53MUE?oc=5
panjang artikel: 1866

Fetch isi artikel:  22%|██▏       | 551/2473 [24:24<2:33:33,  4.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxPUW9qTk5BcVpfRFVtcGtfeG9kUUNVYjhCUkJJaFl6OHNnajVTQjlnNXNYSHdxeUF4RWRCOGtxa1VjX0QwUG1QYURsX1ZEOU1BbWxJemhuR3h0SC1UYVowUG1vVmlCSW5SbnhCakpzTm9jQ25wSEpqQ1BzZ2RGR1FGbGFONUFsbHpYY0tWUks4RXBwRlA1YWVWU2FkaVNMUU9NSUJzR0U4d3YxWjQ4TnBYUENSUElEQnczcUpzUFBZNA?oc=5
panjang artikel: 1534

Fetch isi artikel:  22%|██▏       | 552/2473 [24:29<2:32:40,  4.77s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxPdThCaDk2N2l6RXQtcjh4UGpjNTNTNjFndTZoVG1CU1k4b2dQSkloeFhEZDczVl9XbnVob0V6Y1ZTMWNBMUtzVzRHalVZdE5kTWJYbUpiNHViQ053NUo5X1ZodlY3WE5HNE5QOHZkbFRCV0M0aTA3amxsdTgtcDVfMEJwZVM0VmNrekdNQy1od3BUanB6RHVZRjhaTnlIbEVIemRxM0dueExiNlZ1U3Nn0gG0AUFVX3lxTE5rRExrOVJDVXJNV2NOVC1oNU1qQjgwZEVxUTVwRjFnWGhRR0s5T2lkNnFZTHdINVI0aEs4aGFUSzhFN0RwREk4WEdtdEd1ZF9WM3F0MzdhczcxV2FRajZKaVMyNnRaMVBuNS1uVjNpNndSUkVodlN1WlQtWWVEdk1TLWhmcXZFc2ZTNmp3amZITGxEbFBxVnpSTDZMdU1LUHhHRS01MGxLRG1VTWlMMXhVZWxWRw?oc=5
panjang artikel: 1926

Fetch isi artikel:  22%|██▏       | 553/2473 [24:33<2:32:18,  4.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxNcFFFR29GdTVqb0FZZW1kdk1mWjg5QU40dVUxOUpXaGJEZFlEZHkzTmZIalR3cWdCT3IwZXA3WFFES1BJNDlwcHRXVlA4MFE2NVVoZkg1M1M2cWhzU3ExdmEtSTlIM29HQTlTYWV5Nnc0cl92N1ZHY2cwOHRDZGJ1X2ppeUZnZ3l5LWNrNGFaX081RXd5MG5KOWgtMVAtQXpiVXZRQ1ctMHdDUnZ5TFZsNkZ3QU1LRHJ2T2ZwZnZxbmhhd9IBxwFBVV95cUxQaGJ0dTBMblhmQ0d0cjc1U2NIR2tmTWs4YXVkMnJFLS1wa1hldGFJRnlUaGJGQTQ1aTZRSXA0WHhtX0ltaEpaaDJSNDE1UjBTeXBSWmh2VF8xczY2b2VQWjQtRUowSnlEdVpqTlJvSjJiNG5xLVZYanRCSEtNdDN0SkpwUVQzNjRQSDdKT1ZUdGNJRnBlU2FmTk5DOTlDN1RXXy15bVBJTWpRc2xTSUZYUUtoUWFwV1Q5TjVIODJ1MGZkR2ZVZXVF?oc=5
panjang artikel: 2222

Fetch isi artikel:  22%|██▏       | 554/2473 [24:37<2:25:43,  4.56s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxNaEt2ZTNUZXdMOV9YWnAzTzVRNFZhOHMxQXVZempEa1h3djVBN1N3M292V0VmOFU0dnBxa2plODROSTV5bXhfaHAyUTNPVW9MU1QxVHVTMDBMQUFJSmVWNXk2ZmplMTdtYXJrZ3VadWViVUJxX3ZmM2UtMktJYzNTRkQ3THk0X25CRE5LbklQWjBLQ3lqR19tWWk1YU9qNmktZm82Y2U4MFlEdm9Ma09SUjlhUlhQX3BoX3hlRHg4N3hJTGFIMm5yX1kzN1oyM1Z1S083TTVXQThhaEXSAdsBQVVfeXFMTlFwZzFlVFJNQUxsY1luN1lDang4OEFEcnR5emc5SVE4M2laMmJ5T19DUW5la1k5RlluSWQ0ZXpDUkFWVEI1aUMwMjJhQkRKNlJVMy16YzdWVjJHU0NJQURBVmp5UUFqSXFWa3BtTW11UEpZZmlHQ0xNNjFLU1VvUUV3cGtEUUdEV1lEbllpMmxvSi0xZHJfY29lSjhCeHlhdUU2cnRRckxUTVc3R1F4T1g2eG9wRnlrRHR1SHRKZ20xUmNxWWt2eWc1azBJOWxlSWR6dG1OdmxUVi1J?oc=5
panjang artikel: 165

Fetch isi artikel:  22%|██▏       | 555/2473 [24:42<2:21:45,  4.43s/it]

Fetching link: https://news.google.com/rss/articles/CBMijAFBVV95cUxNY3FVdFRKbGxxS20xMVpiTkdJdEYwRHJvVGNqSzBITUZPbGlhTkdEM05wWm83WXZhQUZ3bWRGR285TndOanZHaUxSVllQa2dobUJZcDNPZnRUMzNYMXMtZU9WcjZOTEVSUGhFT0FjLWJfTk4wMEJJZWZCU2xHWjJHM1VncjlHRXVBZDhBQg?oc=5
panjang artikel: 447

Fetch isi artikel:  22%|██▏       | 556/2473 [24:46<2:18:29,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0wFBVV95cUxNaXNFQWNOdEhEMGVkQlFMcEotNWdhbmlyQ3FNSE5KZFp3OVRXX1BaQ24xNnBITElJMVZPTjl4UVliOGRWRU5SYjd6SjFXbHVWeThPTmJHZWZid2ZnSE5pdmtjM2ZnY0QtbkRmYnRtb3V5cDdVYlhMZXpwRnBsRFZGQzRteEI3MWR0azducWpIS3lPWHZ2UnF1a3NWVU10NGJKYzMzUDR5LU9lNF9UM2liMUtyVXR6SW42TE43NFh3MDdkeERHenJIR1Z0ZFVpYnBreWZ30gHGAUFVX3lxTE1EOXRKdWpDOUJuWUtjZVN3Y0dXQUQwbi1CLVh0R0FrMUZLYjl1cEtrSWE3RlVScWVsQm9lQWZXZHNiUWgxUkdvdUwyODRtQV81MmI2czVNeTNnc2s0YWw0WWtoaUxkRVVFUTcybGJEN29hMmU4dEQtREROdkZGUDlmUjVvZVBMZTVBcWNVMjZndy1DOER6RW1GV0pNN2tNYnRTV1RFaGlvSUEwRHVYczRjV0J5U21KanN2cWkwclZCRG5QSUc0UQ?oc=5
panjang artikel: 2536

Fetch isi artikel:  23%|██▎       | 557/2473 [24:50<2:15:25,  4.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxOajV1QlBPRjVGaUtIUHBzNWlkMHhzbUt4YkwtSmFyNzMxME9HbUhmSU04VGV2aDhHWXRVWHJlNW9EdWNOaFpqTlBKeUZIMWJWbkFBZjQwSTlUYmYzUDFQNHdMcnhZSjRZbjgzVFNiSUNoNnpnY2ktbW5qSFBCVjVsZTNtamtTalVJVjN6OXVCUGdUUGVkbUVYVm1DYjNpeTcwM1RZenk5SGtPUUlRdjZmVWVDMjZXNGZYQVQ0VjdvYw?oc=5
panjang artikel: 2305

Fetch isi artikel:  23%|██▎       | 558/2473 [24:54<2:18:05,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxQTHYxWE5rX1BiR1NReUt6bnIzY2ViLWdmeDNBQ2RQOTNDUC1nTGVwSjFKOFB1TEwzTi1wSVFqWkxiMlF6SGtEdWhEcVVBS2VlRE9rSVFRbzA0Wlo4S2FBTS1FS2plMXhYWUNqYk1XbEtXZm14eWdGQzNHRzJYWkhIemNxVXNPbzVkdFJJMHgtNEZWZC1GLVBPc1NSaTE0VDBMNEo3OGdndDVGakFjNV9FVzZKUUNHb1hoSnpkaW1HakxUcHFrSlA3SkVaLWg0NTlFUy1DVTFvek5FcHfSAeABQVVfeXFMUGw3d1JlU25HcGZ4V0ZjOThSYmxpREpMSEdMY2FUNEpMcXoxQm14bmhpR0k5QjhRY0FwX2tIdjI1OVNoODhrdnUyTjY5QlhMWTNseVoyN1Vhc19PcVd4UHAtd1hQUWhCbTdmdmY1SEQ0RmVxOVpfMmxiU24zR2M5R2VlM0R1OWZlak1aazVxMFY4ZUs1S0NUZlV1LUxydW1JWHlEUVU4YTJ3eUJ0dHZidHFlcjMyNHBEQ05PTWJGOVRPdGJhTzF5dklFbnpVV1NRdWxmYkdtMXlYMzlOWDNnel8?oc=5
panjang artikel: 1980

Fetch isi artikel:  23%|██▎       | 559/2473 [24:59<2:19:24,  4.37s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxQUGNjVmtHNVFxYmJDVV9ZQUk3WDY2QTUyeHBoeWFuWXpxRGlfUlVlOTd6Xzl3ZW5zLUI0NlpjSWE5dmFxWnVHYUwwSjM0YXBibGZ3YjBORFNTSVhZYllWRjNBQ2FobDdrMllpS25uLWNaZDNnUU1BaVZQZExydWt2aVpZMVEwVkRBUy1qNEVDaGdzZHVzaHhubEkxQWR0NGxqWWgyYlg2ZlVZZTQwbmhJdkRoMW15Tkw2M1JkQkstRQ?oc=5
panjang artikel: 427

Fetch isi artikel:  23%|██▎       | 560/2473 [25:03<2:15:44,  4.26s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxPWG9hTjhTN0xuQ0ZMeEwyMWNsUk42WlJZR0w1VXZ3cHV3a09oTmdNbzg4NkFSMTNuOHF1d29NM0x6WDNHNDI5bzVadE1wVTY5SlRQdkJ6eDhXRndkYnpadlhjc1BOLWRSMHhjQzlVM2hPS1M2XzNkcmpBYndOOVdTcWpzZFN0Y0duZjduT050dnhMWjIxTkQ1RzZHc2xBRllJcWxJTFJkTnhDNTNxaDcxR212OE5MMmE3dER2a3J3?oc=5
panjang artikel: 3095

Fetch isi artikel:  23%|██▎       | 561/2473 [25:08<2:23:48,  4.51s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxPQWxiOEVGT3hHQl9hYWJYZVYxOVJHclcxTHdrOTF4bU50TXY2R2IxOFlReF9zRXBwSW8xeEkxcU1ySEJ1a3k3eUQtaVpFTGo5QnR1UWJXNVNIbzdIZ2pIaWFzY2g3N0NVWmN4M0lxYlhyT0hZOVBLRGdBYkRadEYzcUlWM2pJZzUtMW82SGJWMVB6N0hUdXFrd0JSaDhKb3RhS2tQbS1laDNNNlo5TllWa3NqQk15RFAxMkVwZGY5RHNXaUM3?oc=5
panjang artikel: 2307

Fetch isi artikel:  23%|██▎       | 562/2473 [25:12<2:24:03,  4.52s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxNeENvSnQ1V3RCSjRQNVg1Mk1yT09hck93Nm1Zck5QVWtURzdVamIybVFBdi1idGprc1daNGg1LVVDbHAxTU93LWVXR0YxUUNmaWg5TVdqTW5Wam5jeFZPdU1MdmNHVm1FWlp6V0xobTcweE0tTS0xZ2RyVzBuY1lqdFJabTd4U182UWJnQjI3X1BGX05WdHd0Q2pzVktJczVjR3lkbTVJcWdzRkp5dmhwWFAybU1qbVB5M3VOVmlHbnFIZ9IBuwFBVV95cUxNQjlvSm0wN2h1cGs0RS1WVUxhYzBqTURXMHVRbnZoU0wzb2JCeW9FR1VYYlhIQWRUU3NhMlhheEV2eHNHSlJkWEVxcGVTNDVjUW9DTjB2ZzdmUWRpd08wczFJaFhSWTJTbnJSVl9UYUJkMUNqZVFtOU5Fb3NRaHpUSzBGRnZvUnl5OE1yb3BPM3lQcTItbjgzRy0xM3EwRmdDTHliWFN1ZzAzS2xxZG5aNWkyWThQTVVOQnk0?oc=5
panjang artikel: 2767

Fetch isi artikel:  23%|██▎       | 563/2473 [25:16<2:19:45,  4.39s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxQbHdOZXRfcWZWTC0zeGpIajVjMDB6WExpd1VhNDI4b05iTFJaZ3JYVDRPTE8tMGpLbnhxNGRoWkhCUWxvcEZWWmo4Y3hPd3o0Nzg3YkNqZ28tM0xERURVeFFfcldQeUVXYlM5Zk9TWjMyVEpfQWNUOE9rb2pycHhIRFVJaXVJRlFKZC1nUGk1dkQ3SjVjQ1YzRFlNSkY1enk0eEMzcjFkNk5XT2swMEhsTk1vYmY5d0NIM3g3bG1fZTVCWkprbW8tdThWV1F0NjA?oc=5
panjang artikel: 4881

Fetch isi artikel:  23%|██▎       | 564/2473 [25:21<2:17:25,  4.32s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxQcUFBUVpPUWdmcXNQeV9hQUszSHUyMmZXZ0FxNEtaQmdvUXBPb1ROWWdxTmNvTFZHb0lRMG5HMG1mZ1ozNmhGSTl2eGF2WnotV3NDMmlESUtuczZEYmJDYnVqY3VpcjlmczV1MnlWbnF4X0plOXlWSWtjX2FDM2F1alZ6T1lxczhpTTZPd2ZxV0NuakE2X0tQdVYweVhTWG51bmNHMEtkbw?oc=5
panjang artikel: 1265

Fetch isi artikel:  23%|██▎       | 565/2473 [25:25<2:21:19,  4.44s/it]

Fetching link: https://news.google.com/rss/articles/CBMingFBVV95cUxPeVRpSVZEbTFkdzhFXzh5WlZHc0JZMXhkVFhZbXNySDdwVWJoZ3ZFVjQtQmxLeUdlWVo3WWVlWVNMLWpxZFZEdHZ3d2xaZFRKWFJ2cTQtdkw0dE84MzNRaEhKOVFnNnVZTWN0Zm9GM19HR2lubXNHXzNlM0ZjMVltdndONy1RYm5hTnR2NDNoYS01ajhiZUpMZlZ4aFh5Zw?oc=5
panjang artikel: 1749

Fetch isi artikel:  23%|██▎       | 566/2473 [25:30<2:21:27,  4.45s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxPVXhZTEY4Ri1uX0dGUTZkLXNLWEhZNzIxRFNHaEdlVVpHRlFtOXpLNWdFdnFocVRJS2N2RTRqZEdtWFhBa0dZSmNlWHNOQ0J4VjBQYVczOTR3NEpqendUR3NMVjUtM0ZTaGVLRXNnekZ3VjBYYUwtdGZWRHZYT004Y1hQcWd3S0Y1OWhVbURVaEtES2VkR2FoOXpfaDF5bHBJRF9NSm55TXR1S1c4WV9FUGJGSW9Ndw?oc=5
panjang artikel: 2720

Fetch isi artikel:  23%|██▎       | 567/2473 [25:34<2:19:53,  4.40s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxPNFpxTDBmUUhTMVVGazFNeGhmZjdpeHY5Z1JOUW9qWGtBLUs5YndXQnNlbHB3cG92YnNPNHk4QjVoM25vMVYxUmFESk9QZE04Q2p4Z1RHOFBrQlhWNXdxV2FwRi12S0FLWUtyZkl0eTVFWU9KSTFrMk42anFsdDdoZ3BpeGh2NGFGRG93X0RNRGoyM3FheGJ4QkdSTzRGYzVldDUzaE10ZUh0bTlNZXZTV0daRTZvQdIBtAFBVV95cUxOajdLZUh1MGwtUEh3V1kyMjdQeXNDX0I5a1hGb3M5UDlqcHJBSkVwZ0lPQ04wblgxeWZ2djJraklwNi1Ic1FkZjcxelkybmtyWkl1bFdTUFlUQXlqOVR3M2ZTZUF6ZnRJaUxqR3JfRFZCVm1PeElCRWg1aUI1TVo5d0JHaDE4M29EaHAyMUNnUkktcklpbEZVSHluZmNJRTBBU0FOeWc0WGh3UGZqRXZkbGhyZ1A?oc=5
panjang artikel: 1372

Fetch isi artikel:  23%|██▎       | 568/2473 [25:38<2:18:38,  4.37s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxOanJYTWczRHJ5TUpEQVM4UF9IZVRnWGMyY0J4ak5VZjRQeEFqYzRIZ2hKd2hlTF92U2JMWVc4bG41VHBqTzJYakJXRGpZeUFNRmJGYV9TdFhJM1dreDlvcFRIOGhiRC1XOTk4ZmthbzNhT0YyNVU2SlRoejMxb0xETWdFallkaHJrcXpERmN1dmFaNWd6ZHE5SjZUVks1eTBBcDlvTmlRSVBTdFB3bC1aT0tqX0o1VGUxVWtCUA?oc=5
panjang artikel: 2128

Fetch isi artikel:  23%|██▎       | 569/2473 [25:43<2:24:09,  4.54s/it]

Fetching link: https://news.google.com/rss/articles/CBMioAFBVV95cUxNWVlxMjVmNV9wQ3owWnlPbWdGREoyeXkxLUl4cHlRTUd5aHFMOTEtaktOT2NJWGtNVkF1bnprWnFhUC1ucFJnS1oyWDFvMWZwaHVER0o2Y2ZYWUxJZWU2Q2pkaXU4MjBaMmNIeUFWb0tPQm1RYlNFUUtrNDBXdU1zbl90UEluT3NVNDd4OGtfT2hGaGRtSzUzc0tYOWxYaWlH?oc=5
panjang artikel: 1696

Fetch isi artikel:  23%|██▎       | 570/2473 [25:48<2:28:11,  4.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQNE9FWk1FMW9fVUhKWWdmWWxNamNTdnRtQUpmUld6VEY5c0NBY3p2bHNEUmN4VVlpaGRDNUtqR0tsZ1NSbHN5aTlJZVZHZlBjTDdTbFMwY2xaRG40UFU3S2IzTm5YQlpZN3VKTDFqb0Q2bDlOU0pHRFJoVHk1cXNNeHh3WmxhTjczR3REaUVReXRoS3hSMnNUYlB2TXh2aE55RENvbmh2YklnVDRaRmhPN2ZyMG5sM3BUN0E?oc=5
panjang artikel: 4090

Fetch isi artikel:  23%|██▎       | 571/2473 [25:52<2:18:45,  4.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxQYjVXMUtjMmN2SGg4VlRwaXJ4WVBjQ1VfLW93Nnk1WGFVdW1WVHZRRWpKVFBNZHJBMHlrSVZodlVNWWd3OFNRb0RIOGxoc25BWThZbDBaUmlWODdNbUJSM05rTndWSXFUWVBYVU12anl4N09oWkJjSWNQV0Nwb0hDMHAzOGtLVmMxNE5QNGh6amNJdW5NZHdzVHZYeFdLVlFnWEtWUTRNbENxQWNYT0HSAa4BQVVfeXFMUGI1VzFLYzJjdkhoOFZUcGlyeFlQY0NVXy1vdzZ5NVhhVXVtVlR2UUVqSlRQTWRyQTB5a0lWaHZVTVlndzhTUW9ESDhsaHNuQVk4WWwwWlJpVjg3TW1CUjNOa053VklxVFlQWFVNdmp5eDdPaFpCY0ljUFdDcG9IQzBwMzhrS1ZjMTROUDRoempjSXVuTWR3c1R2WHhXS1ZRZ1hLVlE0TWxDcUFjWE9B?oc=5
panjang artikel: 950

Fetch isi artikel:  23%|██▎       | 572/2473 [25:55<2:09:45,  4.10s/it]

Fetching link: https://news.google.com/rss/articles/CBMiekFVX3lxTE1GSml0UE1aX01wUVg3czd3SHZtVTVBZ3lpRDVsVG5mTWs5TzJtanpMYzNlVUEzRnBHRW1pZGo4cGphV0YwcjBNbGhvZ01UMDRIU3EtOC1oUjI3T0JIVjBuMHFnQnV0VDJ4NjdENGVZQTBGS3JSMTlkVjhR?oc=5
panjang artikel: 6193

Fetch isi artikel:  23%|██▎       | 573/2473 [26:01<2:23:24,  4.53s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxNcHZld3NjZFlVc213bjVnLTNmOEhIbmNocjRIM25PYjQ2TldrTUVFOS16QzNrT05GSWNrTGI2WklmVkRzRVRTdktTR3JaR3Bhbjg4WGZGWF91RkxCSHVCY0l5cEhXZHhlSjljcV9tUTE0WXhqTElfUVpzR2ZXMXB4X1l6Y3dwWjZGbEZKUGVOd1dxUmVWX2VYNFc3d2swaTNVVXJDQXdSOTNjMm5QMUh3WlktaFcwN01XQTNMdUcxekFKV19wY3pBVlhzdmVxRUJS0gHWAUFVX3lxTFBLTG0tajRwZUU5MTdVZVkyUm5jcFczcXdBQVFMbUNkekpyN0hRcTVCRGZ1V2gxUGpJMWhGQ095Ul9kQnRERnkwLVA5eHBVMHE4d1J5NENEVExtYW5TTlRLLVdpQVhVclY3WGZFR3R6YXJzMUZ5M2dIajZvQWJXMU9UZ3dNb0dmOTI5M0ROYmJiTUxlRm53LUgzV1FhUFB3YzFaai1zYTIyMC1JYmYyVFpQSW9yeElTeDJxZWF3akxKTVA0Q2hYSVZlbWMxV3lZS1BxSmM2OVE?oc=5
panjang artikel: 3343

Fetch isi artikel:  23%|██▎       | 574/2473 [26:12<3:24:11,  6.45s/it]

Fetching link: https://news.google.com/rss/articles/CBMimAFBVV95cUxQWm5RbU5TUl9rYTdQVUJISl9NQWozX21RdElDcU1aa1YyaXFfbGFNU2VRRWVtcTBuOEkwN2xWY0hPc181Q2tJcXpBRXRUUW5lQ2JjRTlsNWdVeWxaNUU5NUtuMlhBbEFiYnlEQlBXN2oyWi05Y2xYbDVTNXRwNlJCWVlPeXQxcnl6d05jTlRXX255ckxQZ09SUtIBngFBVV95cUxOWlV0TkJYMUdPYWFUWVQ3MTVhT21fLWFOSWVDLVp2Vl9CMkRodGtzcGJTbFp0d1FSNTZnRWVnVHRzV2UtMlN6MHFmd3VzV3JsTjlvbkI2TkZBdG0xdzJ2cVVmdzR3blpoem1mdmxVZ1RBeUdtV0NxbUYyekh5TEJUM0VzTmdzQ0JGZWw0UjBKVl9MZFpEWjZobXgtTDQyUQ?oc=5
panjang artikel: 6270

Fetch isi artikel:  23%|██▎       | 575/2473 [26:16<3:03:41,  5.81s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxOUVR2YmtUWE44cEttYk9hU0pDVjZuVjA3Z2pPS1ZSZ0xCZW9IUFRDUm8zU1VJeElMZ0R4bm1aUk8yd1lzT0JZNGFnYTV4QWd0dW83dzBPeFFtTmR3alk2bmY1TnVMQTE2MEtCd1R6VmtxcFMzaFJSejVCYVlRX0UxdjFFSWl2MTMyWXlBNlpzeTI3LVVsX0dlR1RqUWp6STJxSkhYc1JDQXBacTMxaTZLckJ2LUVqVmN0YmZiUWNvQWFyYmYw0gHKAUFVX3lxTE93Qkk0Z2lKeXU2Q1BJN1lFUFZaVFVmT2Nnczk4cTRjdTh5MnZZRnhHRDFEZDkxSWg5c3ZRdDVFNXVLOF9oVlh6clh3eGdaR1F4U1hIdDZGY0J5NzVtUHlPRW9VcHNrdURpSVlkQUx3Q3ZwaDdDX0NIbEJlcldfakx1Rlp3ZklXazI5VmZyLUxtZVRpUDBrOGVTZXZSUW5OVXJWRkptY1I3SDNOV0ZtQTlMYkZ5NlJ3MWlFZUh0YlB6S3VBWjYtMHMwY2c?oc=5
panjang artikel: 2235

Fetch isi artikel:  23%|██▎       | 576/2473 [26:25<3:31:38,  6.69s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxNUHNiNG5NZDVMVWUwdGowY1FhMG53cENDZWxvZHN6YmJwcS14MXZmMDNFYVJtcDNoNkhqOEo2dVNlaGJJUzJYbVBYSzduMWZDeFFQS1M1WGZRS2YxTmFVRURwVHJ5ZHNyd3dnbFNxTHZUdGs0VGtBUFV1Q09faW5EdlZBb3M3NmFjcUhUSXpIU3p4eVhrNW5uN3YtX1ktSmhGVGRFTzFkYi1WYmFOZW50ejBlMlJWYzEtRGJWZnBWaFpHRW_SAcgBQVVfeXFMTmNzRm43d3c1c3diNHU4aXgxQ3FzZlY2a3VNRXFZS3pITUZsbXc3TDlHWTg0ZWVVX1hTUjU1NkU0azJHcnlZVUxCaUV1c0VjQzc3a1RpNDMxWkJ5cldaMENHUUU5dW1PdG12ZDMwQVdfeFM1SDdDYmJaWkZNcEd3Q0xlSEdOQWxHWDhuUDd0SzdEbHZ2ejloTkRGT0dpSmFfOERRcTdPcVg3QU9QVzBKZ0tmdV90Z0lVNU41MC1wSzQ1WFZ2NzZXRlg?oc=5
panjang artikel: 5000

Fetch isi artikel:  23%|██▎       | 577/2473 [26:31<3:26:19,  6.53s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxQb2ZCanJoNjg2aDBZYU1MZ0ZtNnUxX3d6MGFDaklCUy05X2w4WlJXZUVWV201SmRDUmNhOEFITEpRMDJjdWhYYW4xaS1NLVdIQkdsS2VXcm1MWGVNZWhhQ2xHeU44ZXU3cEtRUWdhenRZWnRubzRwSkx3UTJXanMwa1hva3NLZzQtUzJ2TU1fTno0anJsWGlXeWRrLUw1TGJRU0k5ekVEc3lTZUdfNExGN1RVLXFBZkxH0gG-AUFVX3lxTE5qdTlldDVQTjZWMW43NkVhaS1uSl95b0lQamRFSlp5ME1OeENMSFJuaEl3cGVBdDlPbkkxYVIzNWE5aDM2SFc0ZmxRRVpSc2pVdER5N2tZcjJPWnpmbzBnUDBYa2hWLU8xdUt5ODB3VlNyS2p3Y2M4TjVqY2ZXcWlVTW01V2V6emI0cWZFZ1lub2FFSDRpODVqTmVpUWxDa1RrWFpmZ3JsRmNWemVRQ3FqV1NLcjVDdUNTc1l3QkE?oc=5
panjang artikel: 5186

Fetch isi artikel:  23%|██▎       | 578/2473 [26:35<3:05:37,  5.88s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxNVGJmeXQxZlk4VFZ1OXd2UHBxeXNjdV9jRDJTd1MxSzFXOVBhRXVpa29JUkVyVWZVUThXdlNpUUVJa0tUM3p4NmJncE9LVllvZnVSaFZvQnZrOFVEbUVUMzRDZGJmeFdXR2N5Qm9xY3dWemlCYnctZWpybVFnQ1BMOWl4Rm5BcjU4TG5Mb2VuQVU4S1FKUk1pNURQcTZDQXNRdGVwWmxVWXRxWHJCU1lNSnBRa2MycEJPcDBIRHNZSmxaQXlxQTk3Ykdyb2d5Q2_SAb4BQVVfeXFMT1QxMENVX0FVS0lSYm5YeThsXzB0aXkyMUYwNkw0aVBkRUpNWWJ1YTVVRndzbWgza1NCM0tGTnhObVlEbVR3WkRPWkxjTGFJcF9sdW0yMmpxaTVnRWxlTlVYYWNsbm5BVzVJcG8yczFZRlNvNGZMYjBfNjhPSzgydVRVMEM5VkMwSmw3dHhZZTZvX3UweEFrQ0loOFdsbFJkMTNUT01QdTA3X1ZtRE9Tbm1uR1NMX0Y3cnNGRmROdw?oc=5
panjang artikel: 2388

Fetch isi artikel:  23%|██▎       | 579/2473 [26:40<2:49:14,  5.36s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPU2I0Zm9OOHVCLUs2Z2NFX3dsd3hid1J2c0tlREtxWkdvRjdBUmhEcEtVNkRNV3pfa0VQZDZmdTlrWnFFUlNVLVZBb1ZPMTdCektnX2hCX3NtclBRR2V3VGFqZ1czTnptTjY4WGxfRS1QSlVjQUw4OEJEOE9RcjhRR3lBdG9kSE1pTjVfTlhVQXFzT1JHWkxnajdEYlhhOC1UVnBEMnR5TnZVVDdIa2NWSzZ30gG3AUFVX3lxTE9xdmppYUxHcFlXRFNzRFRkTGRMSlFmYlBiUk9RSmNnOHgtZG01OVZSb3lGT1ZqQjBaNDRUcWlhaGNHbTQ1Vk1vMlhYMktxZFpoalhFM190dzdFNHZvTWF3d1o3QmJtWktaQ1pDNkpsekRvYmRGbGVkU2p1Q3NXQjRvaV84OFpCeFp5ZDFFNjZWYkdZZ1pkZ1FsSU56UzRFZllaSU85UUhyM1JNMnExQjBWRHZBaUJqOA?oc=5
panjang artikel: 6112

Fetch isi artikel:  23%|██▎       | 580/2473 [26:44<2:39:02,  5.04s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxPb000b3BxeTNSZENVS3htWGZwTjhlLW9NUVRZX0NKN05FRjJrNGJHLTlMWTRLRTREUTdldEdWWmVDS0E1dW5RZjlreHRFa0RHS3o4YkRFeGRSclE4VXIxQjQxYWJ4VnN1X0lsNlRueXZHY1NFQW1oZkJZMGNwMlc4WVVJcHFqU3Nid3lBQlRJb19nNFZlNGpaV0FIY3ZqTi1VOG5BaXhfZjZWSnfSAaABQVVfeXFMT2NtaFBnNG84OF80OTFRdXFYdzU0NHh4Sy1yaFlGZkg2RUZVR19FM19hOEJSLWpOaEpSSXB4S1IxOTBlUFZPeXNXMFJ2WXBaUUhDc01JaDY5MHlyaFczRTV3VFFlZjROVk5oVXQzOW9Kbmk2YUw4MFRTTkRCV1pjZWpHdWFfaEhlMl9uLU1hSlJnRmc1a0Z4alN4SlBoMWxKYw?oc=5
panjang artikel: 4872

Fetch isi artikel:  23%|██▎       | 581/2473 [26:49<2:39:44,  5.07s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxOZTVCenJZaE54UzM0dXNfcm9NbEJRZDRiUVNsV2Jlc05nNk1mWHJ5VlNhbnFzcjVfd3hNanZUOHI2d1I0dkF2ODVVOHR6aHdSR3NEQXRfNlJrUzgzMzByaDEzQzBLWGVMa093cEpQTkk2THVWcEVXRmlyTUNRdkpaYVpaMzAydUNkR1RZYVM1X1UzX3F6QzNZX2FCZ0lKbWg2cklGN3d4WTAxRjZmNGIzVUxB0gG3AUFVX3lxTE1EVjVveUtoTVdxbzJ3LWJ2UzUzdzNFc2t3dDNDQTY4aWFVTHJFb3BCQ0h0V0licUN0VjM4NDNVSGh5dzhUaGt0akZIaHA2eVpqNElTck1qVDVBWGxVZUdnWEhsZ0hraEVQbUE5SzJLS3Q3R2poM25kM1NXN0g4SWdqNVhOb3oya2h6Q0k4dDk0YmQ0R1c5RWlxeTUxTkVyT09xdVFVcnB6U1FaZDdScHdGMlZjcE45aw?oc=5
panjang artikel: 3371

Fetch isi artikel:  24%|██▎       | 582/2473 [26:53<2:32:31,  4.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMihAFBVV95cUxPT0ZJaXlOSEJIX3oxYVJESktpQTgzZHl4N2pzR2NlT29xQXBlSmNybGlhSGotMC02RDltUmEzSmxjeE9JSm1hVUVQZGFqUWdXakRXVXJZTW1leEluV3R4Zy1fYzdpb1ZjOThmdVhJQ0dxMnJON1BkWDJoZ1UwRDF2Q2ZaQVI?oc=5
panjang artikel: 7284

Fetch isi artikel:  24%|██▎       | 583/2473 [26:58<2:27:11,  4.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxPVUQ5dHJ3VmNWaVFjMUduRE5JaVFkTmZSUHlxbHlkaVJPbUllR3FZdnRZWjN6emJONnhzUGkxQkx1eEExYXVwRklvSEhCSFhFdS1lNER5eFlvdDBEb091T0sxRUN3UGVSX005TEU5cDhObFVhR09QSXptcTljWXpJcng5cVNySmIxU1VhQWdlX213bWcwOU1VdHd6OHc0eVhleTZZczZ5Z3ZkNmhE0gGyAUFVX3lxTE5ISU02OHZib2s3dUxhM3R6VUo0c1c3MTNxcHRmSm1VZmZ2NGJMbEptOEpKbHlLcFhaUGlsclBjd2ZvUEpCNHVtcjZNSGpnMURibE5nSGVuS09uQ0Zrb24xNE9pRXBmRDBvenVGQWVLbE5iYk03RE05cHQ3djAtWC1wenZnbnVQWjdZbC1la1FHMDJDVVkwTGRudjlRaWEtUTBZU3RROEc0UmhKZ1p3SHFYcUE?oc=5
panjang artikel: 3915

Fetch isi artikel:  24%|██▎       | 584/2473 [27:02<2:22:39,  4.53s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxNSFFvUGhkZ0hJSnNvMHlTM25CVzB5OWZfNG1idlU3YnIwbHpiUlpkMjlZalpzOWFoc3lIWFNBTV9abExyR2E5VUhoeFF3YV9PeURab2RoLW9aZVd3YWZtdGVJWGtkUTBseTdpNndKUHlKZXYzWGtjbWpGOFlkMXhHLWRZRHpYa1BCMkp0TlVmeEU5X3JmZy1fSzhCSkMwX2pLU1NocElPV0dZX2ViZDViNl9SSUTSAacBQVVfeXFMT2lRX3QzYk40WnktdHZnc0FzQTA5dFpaZzBqX2E4ekY3aEM4U0ZLSmNvbVRQNGVEb0ZnWE1NdDJlMXZLbklqM1Vwa2d3N1RXLW9INnNLcHpOekpPQ1lReWhFaHNRTWhQUkxmR25mNE1oLTdPZlFBRzMwQmtCLTE4OGtZV3RQZGVEaVhaOGY2QUl2bXNqVERvdnhXbkcwbVhFM1VzYTF6ZTA?oc=5
panjang artikel: 2743

Fetch isi artikel:  24%|██▎       | 585/2473 [27:06<2:23:33,  4.56s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxQcTM0dFZnNTR3VFZ2d2hDbi1RVGR3SFFKZXRGR3F1blN1M3dqWEU5UEduUThyRDNHSHkwaUpnbDRwbVlWd0o0cmRZWDF1QnlJUE9mNFp0ZXNhMDZ4Zk5ReEJyTFk5U1lTZm50NjNmdlVQb2JXYVp2azc2QThCT05EOUNYUE95ckhSeW1BNkpXSVdKZnhaZHFoWHpBd0swTDl2X0NyRld2TWx5OFBoWjhzdWs5MEZKckstOGc4cWNKRmVTSmfSAcgBQVVfeXFMTXZUZ2pZTjlpTEpuSUV2aGJnYXhDdkZhTjNrdzYwQXRRRU05bXJOSFVWNVBWOW1ObzhlMkdDSjBVTnJwakxMRC1tM0RZalg5cC1GemxyYkdWT3VNTjlGZi1wUjdEaWxGa080NVRrR0RFV2l5TVUwOWdlLTQ5b2VOM0tzU09hdEZqSXBkMmdFaHVPYVBRUW9BMkNLYW1uVC0tM3pBTU5DbEczWkdnRGdnbEtzRzBNQnF5QVFKT0wtN0QtTm5nMmRVSmM?oc=5
panjang artikel: 2601

Fetch isi artikel:  24%|██▎       | 586/2473 [27:11<2:25:07,  4.61s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQOXRUeGE5RFNFX0tnakp2TW42cGNCUkE2QmY0VVFoblhxbnBWT0dKSGJzS3hzTGlzbjQ4eERoOW5iak5EVUxTWldqcjltNVdqdVh2bVZwYWVBbElJWjVWNjg1eU9FRjl6Qi14c254YmFMQ2FPQzlNekhYVFNMUmhMWGJ6bHdRQy1QV3l2b01VaXFTUFBpMHl5QVF0ajVmX013V0lyN2x0Qzh5djMxaWllMlp6SUk4ZzJxMkHSAbgBQVVfeXFMUFNqMjJadWpxTHNKT2ZVQVN1MEJ4V3FHQ0p2YmotSE1OTm1lWkJhZlcxS2RvTFBnY0NFbEJLcWt4Z3FKdGRPVXJxWGpYbDNJMlI2YnN6NTdaWWVvMkgtdWExVjVwUUhkblhTdk54UlUtM1E2Nl9rc09zVmRLWmJKQUlhSFVhRTg0U1NQMW1TUWpMWnJLS2RNak9qQWhGYktLT0U5WV9hNzhER1pCNHphRTVqUS12ZzZORg?oc=5
panjang artikel: 2171

Fetch isi artikel:  24%|██▎       | 587/2473 [27:15<2:21:08,  4.49s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxNQzBsWkJEY3pNWEFLcXF1SDdFdXgyVl9OTS1qd2tvZ1VJVDcxQVlqaFZsZmlDc0trWW1SdmJMb2prNkVTU2EyY3RhNHJIcmE3SjJYdEh0M2dqOTlleERlSGlCRGhybElHVDIwOUp3d3FvY1l2cTBpNFlUd2VpQVRZUjktbWNiZ0FNNlVZVDNOX2dxVlZvTHhDcWJjSUR2R0xLanl4czh2YVdLVk5udjZyZGtB0gG3AUFVX3lxTE1Nc1I4LTFhM19aczcyUW51R1U1RTdjOFo1UGk3SlN5VjN4NnhieWNsX0JiRVdxMGJPSUh0cjJ1Rjl1X3NCYmJqXzluTmhlb3NjcHhzRmNKUVJVY3pUa2VNdHduaENnTHV4RFpYbjhCVTVfV243NWNQdnRzRWpNcGJ0NjNRWlpXdldCbGxuMW5PQ2NxZ2FZd2dmZ1N6LTF4S1BoczZaYUFHa1F4VFJsSlE2MGw0YlA1bw?oc=5
panjang artikel: 2135

Fetch isi artikel:  24%|██▍       | 588/2473 [27:20<2:20:26,  4.47s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxOTkN1Y1p1d0ZkQl9zQnpfanA5ajllLWl4MnRfUVNqT2pYcjVsMGF2VWFpREgtMzVIRkVUYTJHdVVhNHlxWXpxZlpMZ0loWldMWDhaRHF1MjFPZmFYeTRPMzRmSjdwTjROM2U1SGJHdTd5RGhIMTR2RWZGSmtEZWlkVHNvQ0hzQ0l1d25fdFEyMUhIY0NaV3BIY2l6Zk5wemNlM1lkQjBIbHZ3WHpuTHc?oc=5
panjang artikel: 1865

Fetch isi artikel:  24%|██▍       | 589/2473 [27:25<2:23:08,  4.56s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxOSnJ4Mm5rNkJ4aU9tZ3JlTVpybXVDVVlVWGFRNmp3T0R2UENxZFowQ3BwczRGZVNkdXI3NjdTMUhlOURrRENYUGxFc0o3bnV1R1ZlYmNPS1lmejBUN2Q1TVAtbjVUQXVHVkI1dGk3YWxxQUdfc2VxRDdrV3FqOWZPcXE1U1RhS0h4OFBWYjZSX1NsS1czTURUY2hqb2I0THdycFRQRVY2cnpPN015Smt2TlJn?oc=5
panjang artikel: 2830

Fetch isi artikel:  24%|██▍       | 590/2473 [27:29<2:20:57,  4.49s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxPSmNtektsQjBzaGdUcVlkQVBfNzVkOUJTeGdfMGxrbzkyYkdHSjh6c3k0eU1NVW9OYkNueC1qcnB6VjUwNkUwMVhMLUhWSEU0MWNXam1GcVpUa0JscTcyZHBneFJvd3c2bEdFZjV1ZTU4NlRpS0FkMXZoZjdxUWRVMkJFRHJaNmlNV1FFMmxWME1ZVmVickdWWml2bkhFT3hYT2FldzJYbXd4YWZpNThHSmduVnZLTmJGZURBT2VqbHY?oc=5
panjang artikel: 548

Fetch isi artikel:  24%|██▍       | 591/2473 [27:33<2:15:45,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxPdzNRbTZ2VUxDRk1IQlRIbXBfdjF5cUtTZUd4Q0tnMmp2Z1d5SHkyNWcwNUZyS2lYRkpIZGtwU0p1eTdpN0hmTUxJX05Wd1FSVDJHa0ZMVzQxanBhSUIzMjJ1TDJFck5tcmo2OThFQUM5TG92X2J0Z01JaE52eUlfdkh0dWxaY0J2eURGc2JXTzZrQ19XajV2bjJKM01HQzhhSDEyQ0ZtV0R1X1Q1NDZ3?oc=5
panjang artikel: 2194

Fetch isi artikel:  24%|██▍       | 592/2473 [27:37<2:14:24,  4.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMimAFBVV95cUxNZ3U2TXl0cDlobWh5eU1yWExHMVQ0NUVIdTB0eFFsdExnNERVdmowNHZXZnRrR1RVbjRhNFBoaFphQ2hranJ4RlBFbHRHZDdWUXhpemRTUE9zeDRlLURvSlJrX0FpZnBrdGpQV1FaTmk3YWpaN3JndExiaVhZM3dmNmN0aU9JNl80NHlJMmVtcXZBWUNST29TNg?oc=5
panjang artikel: 506

Fetch isi artikel:  24%|██▍       | 593/2473 [27:42<2:17:48,  4.40s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxOM0pmX0pPSmV1OFBEVE9RWFJNdGJlcVc1NjcwR3h6cU1GTUhaRkpCeTRRY2l2eEpDSmNmMWh0NHFhWVhzTzR3TWZVRXNpN1VjeThCR09VMEloc2Z4SkYySzhnWUZEZFIwSzYyNGVua0xVZVozN3ZENDdlNVlxcE1VMF8yblJhVXNwVFNJdzNhOUFONmw1YTJZSU44M0tsVDRWd1pWZUdrcVRxMm5tLURkemxFRnJIWWVLX2tMZDNEdnpZUWo0?oc=5
panjang artikel: 750

Fetch isi artikel:  24%|██▍       | 594/2473 [27:46<2:15:26,  4.32s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQM1hibHdjZ2VzMWdFZXU0WlNNTkw1VV9ad3FTMnRJTF9JQnRiUkVnRTF0eWhuOV9GWWlOMkRXc0xrdkE5UEhhWWgtTWNFczZZTnkxMmw4cmxnUlQxdVg1ZWlEWGxPU01xSUZPT0ZCU181SFdLWEpfSVBYWGFKVU1QejMxd2NGb2tBVlVJZzh1dGpZOEdybDE3aXRIdXZvaUt2UDF5UmcwZlU1ak1XZVQ2MDFEVG0?oc=5
panjang artikel: 2463

Fetch isi artikel:  24%|██▍       | 595/2473 [27:50<2:18:20,  4.42s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxQeWI3YTZnUC1COTFJZlBWZDQ5cEVNUDkteFRoTF80TTNxemRoTmFob050SG5wS3c3aGNQMVJFUmtzenFkNDV2N0VwYW1IcW5XSldYMmxTeFhOd0llZTk1aXFmemNrSXNyTjg3aHJqLUJrU2xkRG5HRU45cncwelZkeW4waHYxVTc1WWY2NmNxQXA2X2MtcVRyZ2p1ZzZsYkRyUFBIN1doLWhndlRQMjYzelU2MGpBaUhCNXUtZGVDeXrSAcYBQVVfeXFMTUFqZXBFdllhcC1YV2NXU0V3NXluZmVsMlZqcHFRM1JSelk5TzNNU2ppbUFDMzFKVlhrSml3WXV1bmtUbE9HdWx1M2t1U0lxV1p5c0hoN3lPTEl0ZzdNdmtQOG5CeldHbzdQT01wSm5JYVJTLVgzMGNmcU5sUERyclhVNi1KSUxURm1uUlNGVmRPV2NINWtlZGhkMkNRNEI5eF9zeWd1UWpRdXFNM1AtS0hvNHhCeWg5Y183M0ZTNTZxTDhpX2dR?oc=5
panjang artikel: 2514

Fetch isi artikel:  24%|██▍       | 596/2473 [27:55<2:21:50,  4.53s/it]

Fetching link: https://news.google.com/rss/articles/CBMiYEFVX3lxTFAyd1dNZi1JTkVNTVRTb2hmczAxU2V3MzQ3SkJCNGt0NE1xdkFuaUJycHRaalRGLXV2NEJIZUpZRnk5RTl0OWM5bzdNXzlNUklMUnZEMFU3ZGNQZVZURWdKSdIBZkFVX3lxTE53Tlk1Vnp4bV9yMXRJMGVsUW5vRDBaN0k0bFF4QXZXY2k1MmxGQkdQd0VZdm9Tai13MVFCWGNPT2xIVmZBVXZhblZUNU1Zdm1OazZxMC1HZ1lXczJ0WUdZUzZMbU1DQQ?oc=5
panjang artikel: 11643

Fetch isi artikel:  24%|██▍       | 597/2473 [27:59<2:15:13,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxPSG9CbnZ3eUI5SjhyUjNHS3NycU5RTDNFVDZBZTR6dkZETWtZWlcyRkpTcGlaVjRiZkd1MkUxbm5RVVFiMFF5akZfZFJQeUx3QTBUOWZJTE5uMVJLSjExbjFsVHE5c05uX2NESjNCSUxqRWduZTFjWmtLZWM1S0dJNEhxTkpaYXlMSG9fMXptU0FoOXY5d1hMamRWRTcwSWVRNndURVhJYmVXWk1mWTJZTktOaWpya1BkTHpB?oc=5
panjang artikel: 253

Fetch isi artikel:  24%|██▍       | 598/2473 [28:04<2:17:58,  4.41s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxNS0dMeTV2T1MzZHBBZTFEVXNldzlvTHh3MmpjcmJSbVlMeXlHZVJqcEJjN054UXpHSGRCZS00aHktaFAwVUNGVEw5LVlCTzRVS3BHOWUxdXQ0cGRqNkZkWkhZMlpIcEFyUVUzYk00TmxjQll6VHZadmxBUkhFNG9xcENHenFSQUdYZUNHeHZDWE5WWF9YbVhzY3FPQ0E3V2Z1WU9zZ3YwZ1NqajRmNTJvNFZtcGlHQlgxRm9NWnJuNXFqWU5u0gHKAUFVX3lxTE85b2l4TGxmME9JSGRQWGJiNkIyRWFvSFdBRXV5ako2cHBGcVV6TENaWkVtcmZCaHZqNVpzN1lQOUxSRUg2WDVfOV9DdmVOVEYtcWU5V3dfd0YtcWhVc3FwWlF1YkYzenI2aWY4NGF4VE5idnZVMmJjVTMtc2lWTDdEUjhmWU5UbUdVQW9rd19PR1hZUWNLSXVVaGsyZXhCY3hmaV9rM3F6TkNCS0UxaDZvdHJBUDlwZTNXSGJWd2l4MlRxZzJCR0RTT2c?oc=5
panjang artikel: 2343

Fetch isi artikel:  24%|██▍       | 599/2473 [28:08<2:15:53,  4.35s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0gFBVV95cUxPTzRFazNQZEFsUG9hMUtHX2szV3dWV0JZU1Jvd0lZdGxHSzVmZnhLNmZoa3dHNTV3bXh4RlptMHp4d0NrZnNLMnJtQmU0dkhEUEFVS2FNUmtteUd2c090TTJhVFI4RVFWUlZQOGJ1UUxsaWdfTHN2WHA2ZTZhVXJyZEpCS0RHazVpck1zcVVOaWFDZzN1eG9ockRHRGx3LWFUQWxseTJKdnlkYXRNWFRkT2M4THlGYnhtVnRINzRyVXFkR2ZLOHJXeGFQaGdoUlQwZGc?oc=5
panjang artikel: 3569

Fetch isi artikel:  24%|██▍       | 600/2473 [28:12<2:15:13,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxNVG56ZVJUUExPMnY1TjNXR0JwcEQzMGE2SG9DVEY2ZllYN1k2WnhqQlNSaUc2ZVpDY1M4WXotZlZkNkxySWs0cUU1b25kSUVGRHJYLVEzNHpnX0ZJZTkweTBWUS1ycjBSUGgxODItdEdleFNqcEtmbUREbHNoSlJDczI3VG9kbzVjSFROeFJONlppZnJUak9JbVJjQ3BOZDduNkg1MHd3czdOWUJKd1E?oc=5
panjang artikel: 0

Fetch isi artikel:  24%|██▍       | 601/2473 [28:16<2:13:15,  4.27s/it]

Fetching link: https://news.google.com/rss/articles/CBMingFBVV95cUxPZGZNemc1MTNGNzRBa1Z2Y3hQUUxZVlBfSXhpR3NIWG9yNVdnMk95cWgzNHRSWWJWLUlWenBkM1pZQm0zM2RYMko1Mm9mbGlQZHMxSVBxNkdIdkg0elJqYXF2STJKSDhXWGM3YUpoRlV0TTRpZHdjcklrb1BjSHhyRWhGQjJXZ1g1UHFuMzg1U21ET245ZV9YejlMdWk4QQ?oc=5
panjang artikel: 2623

Fetch isi artikel:  24%|██▍       | 602/2473 [28:21<2:12:37,  4.25s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxQeTNCbjJ0Nm5QZWhGcUJOUTdXYjl2Q0lNeFEzY3NTNDVFSkY1U082QUxQdHlpeHl4cDAwOERYS2xXdjlNNkkxYlZqc0Q3MllST0ZQNmhBQnFSMHBNTVUydVVFeTR3dlVjZ3hrR2VoX0dwbm5oenQtc0JHcEhKS1JVWEQ1VTh0YTZHM0ZJdndjcVJMcWZCR2JsWXJaMVN2YWVkNkpNeklCTllqRXdzZGxqUFA0N0VvZUpPaGdjTjg1c9IBxAFBVV95cUxQVFBkVzVXVU54SFV5ZEhOTHFTV001ZUJIekxFWUdISFF5R2dWWllZX0YwY2xiY2RuOEJJaFVMWG9sLUZnX1ZhcjBCNGtwQm92b0YxNmRYTFlTeThnSjI1MEYwYl9WS2tlZWM5VjlISG4wSHhVbHNsWDJYb2xxTGNMYm5QQzAxRXJTbGhhRmFldU4zVWRnSzdCUER5OVZPbDdsWFZBQjBSZEMydlVRZ1ZIMVZ5TWhsQjNOWUFSX1JJTHhzZ25Q?oc=5
panjang artikel: 2272

Fetch isi artikel:  24%|██▍       | 603/2473 [28:25<2:10:35,  4.19s/it]

Fetching link: https://news.google.com/rss/articles/CBMijgFBVV95cUxPb1hiYkMzM3dTeGZUZmIybWxyUXdudEhpMHpvdzhmcjRmMlJLOWl6UXA5NWtkMTlEbFpsVzFMeEVVaFNnRUVQcHpfSFg2M0I0YmZXbjZEamh3bGhOY1hQZDN5S1FqME9nNEtDZjJMbERrWlYyS0wwMkwzdlRSaXdsc2JOVnF6MHVDU2RqVzR3?oc=5
panjang artikel: 3660

Fetch isi artikel:  24%|██▍       | 604/2473 [28:30<2:20:24,  4.51s/it]

Fetching link: https://news.google.com/rss/articles/CBMi5AFBVV95cUxQREo2SHlrM3pQM2RoZld2TWRiZlRnVnBJOXNqNkxwSEwxMkJkQ08xYzRKN1czV2xPTW51MlluV1otN3dLTTN6Z21tYVdXX3FOY1Q1cW9zVHNtd3lPa0k2M0hYRmlqY0JwYmo1dS1xZU1ISTNONFcteER5YTBCNUI1cXdXb0tleWxMWEVpaF81VDlELXNPa3otMjJOMGVkWmM5V1N6bWRGRDJkeDRpc3VOcGIzTWw1aTBVNkhDMGY2b0VKeXlrc1dHUUFKa2VJb3JWR1hzUzRacFVNdFZ2cnJUcGEtb0vSAdcBQVVfeXFMT0FCQnFsZWlrZFRqVjRUelBadWJzVUtkcWwyYThZS2swbHRFWGhDeEFoSlRQbVJsbzdrVzA3QkkzZC1rRlljSzZPdDEwUmJjZUlIZVFjQV9hcFpLeEZwNThhSmlIdjhMbkJtMjFwTmhZelRLX3V1bnFkTUlQM2J3VGNhbW5mMjRBTk44ZC1DbV9fdVB6QXRSRkU2Q0h2aWhVTTZubncxWGxlM25NMmlhRWMydkplQnl0NFVtUEdYRW4tS2hpTFpQUWJxZUJFMGtiWF9RNE5FSkU?oc=5
panjang artikel: 1494

Fetch isi artikel:  24%|██▍       | 605/2473 [28:35<2:23:37,  4.61s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxQNnF5VnducTJON2Iyb0JrdkR6ZGg3cVF0QTNXWTIya3ZGM1VoaS11ZVhHMDhHb3NqeTJnLUE1bU9USEhVMk0tbERyUHdPb1BSXzBvY1VacHZYM3RpUzVhVDJ6TVZ2Y0ZZclJybXI0MFphamk3S1BrN1VyOG1yemFwTklqWDZ2SldBZWhWSHJXaUZFamtObXVKSkthU2o4bmRieUFOa3Z2RDR1RWZRUmM5eDNtOXlQV2ItczkzU3VQVVMzWTNo?oc=5
panjang artikel: 4529

Fetch isi artikel:  25%|██▍       | 606/2473 [28:40<2:28:26,  4.77s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxNa3VKN29IOUIxalZMaV81b2xrb1cxVXZqam1JOXM4ZkhEcFZCS0lEOEJTc08tT2pISks4ZGtHeldRU1ZQTjc4d1pZOFZwbFBDanJ5RUZpNGc0c0NJaVZUTC1GWXFsX056QUwyVWxGYW42NjRUdjVqNUhIY1pmWUZ0MjNOSVJnZVRpMVRGYWp1MFRXYWhfbkJ5YlBXaW1md3p1S1hUMGlrckQ4a2dyMlJWNTBMdnMzTWc?oc=5
panjang artikel: 2120

Fetch isi artikel:  25%|██▍       | 607/2473 [28:44<2:24:18,  4.64s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxPbTZGUVgwQm9IV1JwVWFBNzR4d1dYVnpqU1k5bXVGSFBZZEFaYlB4eWMyM3VCM3NSc3ppVWk2U3d1b2d4azkyRV9QTDEtY1U1MmlZUDFaMzU3REpFbE8tdFdJZDRYb3VsTDlCTzZ3MkkzcC1DMjhIVVIzLXhiaGs5ZVYtQmE4WnlmNndBbzAycEc4cG1KNDMwSW5JX2gwRWNncjRyNjhPQndnZ0lzMEVlLVlJSWl1UGZwN3RSMXo2UzBCYUVzbk1CQ3RZcWswRzjSAdQBQVVfeXFMTXltVU84UU1IbkJVM3lSLV9RX245aU8zYnpTMGFGWnVnYXhlMUphQU1kRExTY0hGNGlZRVoxMjFTbkZEdlRlRlZRamxDeUdhZndsRC1oc0pFUEUyNUtpWkdHSW1acXhkTW1NZGN6Rnc4bXFMT3BvVE00OGthdUtRSUNUUG5lczJhU0QwczM2WmU5Vko2V0o4V3Q1V3p2eUhGQ2pxdzJmdkRkVG9pWHFqOG5yckRWZnFWOEhseTFNNmVjRGhtMUhSYXZJVUJYQzlacDRhemw?oc=5
panjang artikel: 2336

Fetch isi artikel:  25%|██▍       | 608/2473 [28:49<2:23:03,  4.60s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxNbjlTamN1VzFhUFY1Njd4UUxyR3lnelBHRjFreGZhZXdpYlUtUWQ1Tlp0QXNrbmtsZ0czZ1RubTRpSTlHQnNMSDBVSzgyTEZULWtab3lkQVAtMXE1SVVRWmZIXzgwT2F2Q1RTWjdoZEZIbTVaaDVIMVVSSlNnV1d3bnRwQ21oMGFXRkw3T01rSEd0VkJYcFI2QU1LWEw2bDRudHp3MDg3R1NUT0xlYldMbzh3T25xY0NvaG1ueEpxMlBkT0ZuaVE?oc=5
panjang artikel: 2933

Fetch isi artikel:  25%|██▍       | 609/2473 [28:53<2:22:26,  4.58s/it]

Fetching link: https://news.google.com/rss/articles/CBMi4gFBVV95cUxQMDlfbVhUNEVyQnFPZ0ZTVUNZQ01HMkFndmVTRXpkcGtfUGhUZWdxM2xhODVSV3VTTHpFczF0SjJfYndWUVg2Rk1zUWF3UDd6dUZ6SkVUNTdrNVNZbmI2OE95ZnYyRmNfSV92dHltUVBybUJ1LXh6dkNXU2FXX2tTOGsyem9IN0hSMzh3SFZWdWJyM0hRcFdTRUIydHdCWGx1dUFFWDNCMVB5eGFlcHA1SlhYeFFNcjdhOUFqYWJjajZRa0ZFSlBIb2dndGJMX1h3bHA1MlBuSnJNUEdHb0VPa2pR0gHMAUFVX3lxTE5hNVlpTTQzS2VjNThsd1VvbnM0d2xYaFNmRGxTOFQ2TjRwbDY3cTQ3b0trUzJsc2NZQ0tIZDhZbTVUWG8wdVFtXzZDSVRyZHZXUFVsZGhWdkpUWXpiUTFhU0Zjb0xKbzB5ZlZFVjRFRDkwNERWLXlIQzgxYzcycS04Nl8xVDVMNnRiVE0yYURxUVk0Mi1qUzItLUVvYmZvSUFtVGVtSV9sbF9GRmotMnlZNkh5WFN5Qmg3S0hPeXpWdGFpeWlReFdsejRpQw?oc=5
panjang artikel: 3516

Fetch isi artikel:  25%|██▍       | 610/2473 [28:59<2:37:09,  5.06s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxPOU5zY052a3hzSDBzMGZoTU1tVnpnR2FaVXUxUVZ6aHF2RndibGdqUHo3d1NORTJUeVVVLWhrNzFaQU9ONVZIQXJSbU9sQzVvQ21yZXlHeFBCd3UxRV85aDVlcVRhS1NkalVydUhJd18tR2d3cjFVSFo0NFRfdHBiM21PMVd1d3hSSV9sNEdkMzJacEpPdzRZcHhKdjh2LWh1LTlOLVhjZmVFOXJDR1pFTGVlXzAxNjVIR1hvZ0lZcW1pdXpyaE1V?oc=5
panjang artikel: 4328

Fetch isi artikel:  25%|██▍       | 611/2473 [29:03<2:26:34,  4.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQRG52cWd1T0xyTGN1dVZvblpKUktEWmRXb1FoSXdCcktaVXVzQVJRTHlycldLQjFYc2VKTk5KZWFkZ3FlYy1ueDdnTng2cm51MVVBSldBeVp6ZkZRZXVpbEgzNW5YdVQzTFJpRjFrNzJPOGlqX3QzT3BZR3p2ZnQxV1ZXcjczQUpRT3J6M1VMRnFVUEpiendkWDc2T2k2SThIQUh0bHNVNVZjRFd5ZkdNalpvN1I?oc=5
panjang artikel: 3490

Fetch isi artikel:  25%|██▍       | 612/2473 [29:07<2:18:15,  4.46s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxOc2J2TEVFc3RSb3BPclRzTDd1czNXRndGU2NiOXlwaDItNVV0Ty1IZFVIbFZ4a3Jxc3doeUE4YXRKVEdveE5Td0JtOGpIaWFJUDQ5bVhIeHRjNVV6UUF1a0tLVDhPWXNzdHJaUGxHZkVvR1FyY0VoNnVYanZOLWI3RUJPSnZqMy1iNFVnV3Q4SEFlVWtORVdJNWpR0gGfAUFVX3lxTE1YYkpNZ3QycFhMQ3JCUU1ZNkljQzViek9nVXliQWsteDJOUXZiSUVBRTd6MFpROVU4Sm90TVhsa0JmS2FNaGFjN2p0ZEpxSnpTU05POVU4M3dXZXQyOUhXUFg2cVFDdUdOOEE0X2VqUFJHRVhMUlhtZHg5cmdaNEhPeGtySzRhN2ItZ2dkOGFMTWR5ZWQ4SnNRZl9EcDJ6dw?oc=5
panjang artikel: 3459

Fetch isi artikel:  25%|██▍       | 613/2473 [29:12<2:20:16,  4.53s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQMVRQVFg4dkpRWTQ2Z1lSVDRRaklVbUoxMmVZNXh0TTRKR00xQWZtcC1WSG03c0dxUzZUeTlnYi15YTRIeEFwRUVfUmdDcWs3UERxdWdLcndKcWgxSEdKWTFmLXh4Q2ttYldyaFlUYUg5ZkIxaTZ4ckJ6SWUxZDVPNW5DeTZWeGs3bFpQTzI2MVNaaFpuSkhGMW9KZk85TFdBQnl0T1RuQnNndlVlVlhUNmtleFQ4MXBGcmfSAb8BQVVfeXFMTzFZYkxiMXR0VnY3QmZ3aEpwWlRFLWlCQUIwTlptZ05YWDdWRE5KMGxMUHRKeFNySUZSUE1VdWNYX0NzVmJJUTc2bTVMcHB3ZXhXcXAzLXU0MHhDTG9lNE9mZEN0ZFhFc0pMYnpUUGdxMTBWV0lkRThWZzJQY0FnbHRudmotSzE3clEwNi1VTzJhUlY1eUhzVzVZcWp0TDVna2hrX3hxNUtOOFhNeFJsTm9vaXZfZzIyTnVOeVJDRVk?oc=5
panjang artikel: 3411

Fetch isi artikel:  25%|██▍       | 614/2473 [29:17<2:28:56,  4.81s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxPZU5NNWNodHFBYkN4cjVjWlZXUVNhbWRkWTlKaWxZVEo3THVycDcycGp2eHBZYUxibDFaV3ZHUU50cGY3Z240YnBrS0d4aFd0RVMyS2RDTUMyMmo3cl9INU4taHBLdU5SNHhCWVVOOTVfUkxmd0lpbGRYeFlzT3pRY1FzUjBYdEhRZHlMdkkwX0Q0VUFLQXZGSUpn?oc=5
panjang artikel: 3430

Fetch isi artikel:  25%|██▍       | 615/2473 [29:23<2:39:52,  5.16s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxObC1wUVk2Mmt0bXcwbnZHazJXczF1V294OE5DV2ZJRmpEampnOGRFS29udllMNmZ0ai1UM010N3BNOWFneHBRWEtLRnZaWlJfYWdRVWE4bzMtNDMxblRKRmJIa3hXRVh1cHdGOEFvb0p1cnlWLXVIdlk2anpyaFNRSk1PZkRLdnJuOXRiSUpVVG9DMVRpYlB1dEZHMGFETFNQUkxPS1RyYlV0Rk5OeXVlbHln?oc=5
panjang artikel: 4711

Fetch isi artikel:  25%|██▍       | 616/2473 [29:28<2:35:47,  5.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMi8AFBVV95cUxNRWg5aDB0N0I3X18zOVV5UWJsSnNseDBIMzhpeW5zT0lIVUF0cGMxUm5XOU9iYk5keXQtNUNDSDhxMjRDVzZFR1BPOWxGcWRHYzZCZTZxWWRtVFdabURwTS00VFFhbWstYkktQmhDa3dqQUZDZHRzeVo0N3lWR0FySHhLYkt1NlI3WXpMMjNJSFBpcG5ZUjR1ZUxCcVBhbTZxUTg4alp4OEUxaGdKSUhGc2ZYb1JxMmw0RGxzX0g5T3kyTEZ0Vm5YbmRJOEJUV0swNDZleGMyeURES0RzN2tYc3ZXaUQ1czJiOHkwblQwUUnSAdgBQVVfeXFMUHpEUlNuVHdkeFBlNGdNYjYzU1pSSHlKbGt1VFQyR2w5eTEtY2JOaTRVVUlNRm01NVNSaGVzb3owVGRpek9MM1FvV3lETGM3LUx3OFBDY016U0RkWDgtNWhtbHgtamlwWUozYXVZQWtwaWxaZ1VwdjhIdlZ1NUJoamg3ZHdQMlZGVTFYQlhVY1JOb3E2Wk1JNFN6WDdncUNubGUzanBEV2RiQkhEeUtvSFV0a2toQldUV1ZPeHZocmM2YWtoVGVYM1ROR004UWpRME4xbDZXRGR0?oc=5
panjang artikel: 0

Fetch isi artikel:  25%|██▍       | 617/2473 [29:47<4:47:03,  9.28s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxNWXlvRk1uYmdWdHRZRmhMVG1GbHd5clg3bENYUEZLMm9HTWtNeUFuRnJjVHMwUS1IYTFkdTNKR2thQjRNQi1BT25VdzZoaFJDdWFVU3kwaDdGb3d3eWdIR0d0NmdEZnlVbkg2bGNHekZzUTd6YzNxdHBxWXRwQTFtS2NSbzNIeTdYTE4wVzVfcjRmRDlqTjVOS1ZnNnB2TWo0N01VWmx4LXRtck0?oc=5
panjang artikel: 2253

Fetch isi artikel:  25%|██▍       | 618/2473 [29:52<4:02:27,  7.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMizAFBVV95cUxOTm9uNjhFbC1tNVE3X1ZaS3VEcUItbEpqQUpCSjhWalFPVGdFaVVTTGNKLWZMN1RkMUlSOWxaT20wZkZ6VWFFUG93RWRRVm9SUUtycHFINklwQTZ5dnY1MzgtblBMSVR0eFU1ZUVSc0xzUDRjQkpGa1VvbnM5UlMwaU5tWFRnS25DQXRWSFNvVHMtdXhhbTVsck1VSHp5MkZFWjZpNDlqNU5IYkFrVHo1d21tdEQxTlp3TUV6QWgzaDYtNE9QaGpvMzNXMUo?oc=5
panjang artikel: 4817

Fetch isi artikel:  25%|██▌       | 619/2473 [29:56<3:31:38,  6.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxQOU04Q1Y2UWtqWVpqUWNHMGhfYUJHbk5iNFZWbFZXR2RWbjlXTUZrMlpNYV9OWjlIS21PbXphbVRsMHZKQjlFWnBBekhZQUZhYndhLTdoUG41YkhqWjNtUVRWU0JpY3hZcjNsOV9rODhSekFOU0Q3MDExQ0drTGtYUnh3ZFFiUkQ5NkhqVkZNMDVoa0ZpN2NSZGl5N2wwU0ZWcktRbFB2OFZuNzRWMjVYNm05VGFfYTJ5MkJYSG1WVVF2SGRnblHSAcsBQVVfeXFMTm5xVDJtakJlaFFNNzRvd2VERUprYUJqbzhfeC14M2NfX1FnY0xKRmZJcllsWFQxWGo5SHVYRktxMndFS092WTRscENtZEhWZnJPSmxJNEZySUc1WDljV0R4YjI3Sl95Q1h5OS10WjdaVS1qY3l1NGhTZ19HS25mYkVWNGF6VkVERjA4SUhyVlZvcjZDbzZ5N3RacW1qbXhrWllGX1d5YUlYb3JTZEp5VjR3NGl1bjdpY3gyOU1Ob19kUVFRbGdEY0MtV1E?oc=5
panjang artikel: 2689

Fetch isi artikel:  25%|██▌       | 620/2473 [30:01<3:11:24,  6.20s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxNVWIzbUpXZGRlbVg2cTdLaC0wc1MwMWpqeERZamw3LTNpUTdxV3Q4T3JTOWhrbXJNYmRTZnF6bTFacko2TDNjSUVEaTYzT0FxeVpmZENGNkdraEh4eUR6cldOdVc2NEFxaGNYRnJGeEdiejhMRGFza3VCaU84Si1VMlVNeDRNc0JfZmNvdzFqMTd3aDF3RW9CWGFQNWc3bElOX2tlckdtYkdtUm9EN1RjdEpPNnpvM0NPbXVYa1dR?oc=5
panjang artikel: 5776

Fetch isi artikel:  25%|██▌       | 621/2473 [30:06<3:00:31,  5.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxPR0lISU1xeERxeGNyRFFIM1B1Y0tuTThWYm5zMFRQTHJoUlM3YzFvbEd0WldXMkl5a29LOEd1VTJlXzNQT1phZ2VBRV9BdmZVTUF5di1mdzhaNlV2UkY4eGdFUnVpZXo5WXJBOEtiSUxMM0ZiRTdWZmVmOU5uQS14X2ROUTMyYVZHZEpKR1NWWUwxcUNfVXQ4UEZ0Y2w1c2V1TkJNLUNONm50aVFGbjJRZkhkWDV2d0Q2ZmRyU1JzVkJLZw?oc=5
panjang artikel: 2963

Fetch isi artikel:  25%|██▌       | 622/2473 [30:10<2:45:30,  5.37s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxNVU1hX2hYaDBXcmNIelFCOHB2WFNmcFpxc0p2YXdjTzRUcGZ6Q09VVTk0d0VVaFVBSU1FSFg5cFNOTmNaWXlSckQwODFkVVZmQi1BaW9wTWVvcXh2c04tR1Y5NlRDVW5oMWRSa3pQYmxULW5mTVZGWEZ1bjZsX3MzbjRZdmpFY0kwWEFRcElfLU5FUWFtNGdEbnd6aFpYQ0dKT1F5bk1PYjRHTXFiQXBQYUtQWdIBuAFBVV95cUxQNkpDWXhSV2s3ZHpPSkhjMF9pSnpNTmk5azcwbEo5ZU1ieTY4MGlzYVM2aVpaMTd5bkxnRGxELTB2cjBvTTg2RjE0VkRyWkI4ajJhVW94bWplRklzMXJEcTJ0eGtjVTduNGFDTzVmUWtKZTJhN09sT3ZySTdna1RtazVPdkJpandFdGlWMTZqQ2lrSFBvVXRnUHFyVlVfRjRkeGdTWEdfcDQ1bVVXc0dhOFZYcTJ6MHg4?oc=5
panjang artikel: 2979

Fetch isi artikel:  25%|██▌       | 623/2473 [30:15<2:36:48,  5.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxOZWpyN0R4Qk9uNl9vd0NValQ0MmN2NjFfeXpfMmJaREdpVG1HOWFCSHB4UnhCSFhKeUFKZWN3VWlsTG1CVlMyYVNKVDlncWxGVmZZenljSU5IN0k2M3RRSGV0S2NEX0V4T1ZvUnRvajQ5V2l0WnZtQllmNmVKQ1R0eTA2QkdEQlQ5Rk9ISHdSYnprZm5FWDRUR0MxbUtoZHNkdmhYaE55d3VUeGM5YjhSQmtlSFRoZVHSAbwBQVVfeXFMTWxnTHNLdll6UmFwTHNBTENMbDBiSWpRMDB4OFdrN2lUMTk3RmdlRTcyTFBjNkdvNVJGLXJFVTlfZlpWa2RWcTdKY2NUTVRTajU3bEpIT2ZSZGNReUJqOXl4Yy03ZU1Fak9ZOHE5RjJmWDdRNy13TEowdFdZS3FJTVRKZVNzQWxJX3FBQ0g4QUpvTzV2Vjkwc00tbXBWRGdUdThEUXVhdTlWZEdxbDBUcFdkNlZJMEJ6VlpZSnU?oc=5
panjang artikel: 2557

Fetch isi artikel:  25%|██▌       | 624/2473 [30:19<2:30:20,  4.88s/it]

Fetching link: https://news.google.com/rss/articles/CBMiigFBVV95cUxNS3Fwd09XMzJWUlN5WlZFVV9yRWllSEZUeFZ1RjJHaEFlQ0tKcXNsRHZyalRHeEE4cGk3aWNXUnI3YlRrVy1wSHE3eGduVXBVNjB6Qzc4MlQzaElVaklwR0tjRWNyaVdCcFAwcDhuMmZTa2R5YnBzaDBzZzNDRWY1S3E5LWtwYzR1WVE?oc=5
panjang artikel: 2697

Fetch isi artikel:  25%|██▌       | 625/2473 [30:24<2:32:30,  4.95s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxPY2ZiRTBwSXJIYVN6QS1jYlUwY0FrT0N0aDRKcHdZWVQwNVhSMWhZQzFLd1B2SHhqY2RYUFFiTUJJVWZLdV9vMjAxQU85Unp6NE9rRlNIbU80N2Z6OEtTZkRuNTJUSG9pN2RBQW9TdXlBSHE5MS1VV2dYcExiVHp4S2RMbncxWjRJVTFsQTFHMm5XYUp6QXlrb19qX2VndWJaRWNtRmJIdVRxY0wyXzlsUUJRU2ZrRzVTQ1k4em9B0gG8AUFVX3lxTE5GaDBPYlgzV29NQ2wwd3N1ZWltU3hZeUFxb29iWk5aRE9WV2xlRGV4TFM1cUdtR0J6M3RjcnlSU2NIRjRzNXNaWGJXWG1nd2hvb0RFY1dOek9FNC1sWHREZVJSTHFUS1VyLXZ3bDRtZ2hpWVJZdGZjaEdnY2JJdTQ5N1VjU0wxUlpMak81dDNPVlJieUUyRFpEaGYyRjQ3elYzOEJLRWl4ZjFHOUl0SldrSElnOWlJY3lwcFJI?oc=5
panjang artikel: 1686

Fetch isi artikel:  25%|██▌       | 626/2473 [30:29<2:27:18,  4.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2AFBVV95cUxQY213SXlYbTl3ZXpGcDJCWHBxQWFKUGtYajI2WDIwajN3bUNNNy1pUGRCemtnRXNycnd1WERDM1NuZ2xiUmdvSC1YUUxNOU9fUDVrTlhsNm9ZdzBnNXQzOUlTZDQ1NlVhMFBuVFNFblU4OVVWY1c5RzctMngzMGV4RllaQnRfRTRHM1Q4cjMtb0dDb2xmZ0lSOG5FTklKSHpCb08tX1FSUklrenB0dGo4TTMxNTBtOEwxdUhTM0lDWV90TFRIREpDZktjZzhtSmtQWm1mSTIxZ1TSAd4BQVVfeXFMUEU2R0dvRzdYX1lFWTJ4UnU0RHdTemd5bUZzQlZqeFgtcFFCRmpiRHVscGVEY3RNZ2tZNWRmM2JVU2NwdzhrejdYOVVjU21NclFkYWp0U3Z6VkU2TWs2NE1teHIwcmxWNUEyT1ZrTk51RDhScExaclI5MHBQYTJkSTdzSFZfRFBsWW1jMkxhMldMUi1tYWxRWGxDWVVPd3BrS09zX0NjZTJzMWFsYWdFRTBYMnhNV05WczF2dzBraHlpZ3JQMWVDNXdLN1kwLXpLcWhuNTdudFBnSTgwLUJn?oc=5
panjang artikel: 164

Fetch isi artikel:  25%|██▌       | 627/2473 [30:33<2:19:59,  4.55s/it]

Fetching link: https://news.google.com/rss/articles/CBMilAFBVV95cUxNRmZkQlFpd2g3a200Rzd2WjJla0Nyd2xQUVNjZzMxSVZTcnRvWjd4V0ZKMXVRTDRHcU9taW1iQXhrbWV4QkZiU1FwR00tNk5aU09CQ08xQ1VoUjczLVFmSUZvSjlqa3B0eE8xV1lDUXhpRGlwckVDRWVYQzRjZU9lS0hfZXpTVTkzVVd4bzRSWjExZFF60gGXAUFVX3lxTE9iNU5EVXRnOTZlWV9HWXVPRnBkNnFPTTcyMlZDNWowVVVrQ2FoVElsV2xySkFwaFBFTnZ4dVlYd2thMXVqWGdlMmYyT3hacVN3cTFtV3ZBZXhwQV95eTFUTkVtbzVYTHZycTlTTVdJcFNkazRXdlFaSGtZSHZKaUNVbm9YRG4xMC1odTMyYm9udXVWT29UbWs?oc=5
panjang artikel: 2554

Fetch isi artikel:  25%|██▌       | 628/2473 [30:37<2:16:53,  4.45s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxPQVB5RFVNVllsdG9jXzd2MzZFVko0ektzTVBqa0NYamhkbW42N19IZjVYVjNQN3VfYm9DV05tZHBJSlRRWVRYSHdJbUpnRVpYdmpBcFRNU3lDc2tVaGNhWXVHV25uRy03YlBTU1FKRlJpNEpwaXVZOHFCOHhDakhidUNTbHYzeFJyZ1RVV3lBeURJN00zYTZqNGZ1M1NfSkc0RnBHaTRyNGdVcnJpWjd5N1Zjcw?oc=5
panjang artikel: 1655

Fetch isi artikel:  25%|██▌       | 629/2473 [30:42<2:23:41,  4.68s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxNNEFfVWN1Vk9GeVBJWTF6UkJaTGZmby1FMEF2V2hBSzNvNWltQ2VDb0hqcC1ST2hhVDczQzktbmg3Y2JYWVlBS1BrNWFsUXNrdEJhTnhnX1FhUFZDNHN3S0RWbnIyR0dzRnlEejF0YjhyOUhFWUxaS2prWmtjbDR6dFdSdmdsbWJPbUtueUI5UVdIOGR3Qzd3cDlZcVBoOTJyeUExNVgwLVVpczBfemdraXIwOVRmM2tmdEZRV0ctdw?oc=5
panjang artikel: 2337

Fetch isi artikel:  25%|██▌       | 630/2473 [30:47<2:22:45,  4.65s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2AFBVV95cUxQMTQzazd6aUV3TVl2RWlnS2ZJS3YybEdlX2ttdkxyMGFyX1J3eTZ5YXhZNFhYckRsS0JGSW9aLTFiWldqUXhkYjNTalpvS1BHM2duSXZNRnd2eEpFNEhSZDJ6MEUyU29yT0VBb3BRcWpGMTB2cU8yNVptYnVxaTMxdE9QT00yX2xVbUxCd3FIR09VbHVPR0d3ZVNIdE9ZMnJKeVdEdHYtd2tCWXJtVzQyeWEwVXpQdjZqSmFhejF3RU5BUk1WMzdUcWl4dDE5ZnJFUjBUUWZodnPSAd4BQVVfeXFMTzAzdE43RmhfN01XaFVabUZ0V20yNk9QcjZQTXVtNTJaTjJtREJaejFKdWJLTlJReHNHMWxCYWpxWVlxYWVOX3paeS1mY0Zod0RYVWhZdXU2N2M3UWNESi1tdElBbE1zbjhKODAyNTRFWDVUcUtKRkplRVhvLXp1RzlHTzVXQmF6aGZFZkN0STROSjhOUjRDVl90NDN1Sm14S3ZOdkRLMEdQQ3A2bFNGOE5hZ1lpUkFBUGtDbE0zdUxHMTQ3dGViN1VNQmNzbmlFZ3ltUjN5cnpNdVNTeEZ3?oc=5
panjang artikel: 1584

Fetch isi artikel:  26%|██▌       | 631/2473 [30:52<2:26:15,  4.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMimwFBVV95cUxOdktIaVl0S3ZyOE1kRTgtd3RpV2NKbWVzdTRuVnNLa0lKdEhITkFoRVhhMGQ1X3F6SGFNNGFvNzhoWlJMUDdKUmo2ZlRXbk50VGdWbGFRZEhBUVQ5MWlxbmdTM3g0MGNCR0c0YTlHYTR3clc0cUlXNnp6VlVGby1fd3pNVXFqdXFWYmowSjRvM1hQYWg4OVlRblZHbw?oc=5
panjang artikel: 2761

Fetch isi artikel:  26%|██▌       | 632/2473 [30:57<2:29:12,  4.86s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxQS25QMUZoWlhGTUVFUXpIU2psc3ZsR0U4WjdKZDlaYmtzLU9ZNm93LXd0NHQxRGI3V1dWQUw1VGM1c0MxMzUxV05HbEZhdEs5S2VORVZQdHg1N0phM2psQnVqbHc0YnR6Y2dmZUlxUTB0ZHJ5azctcmtNc21LNlo3bl9FZUFWbnRNX29IMDdJNktvSjJTcUdkWElzUF9OMy1pQk9aYmtmS2FsVnVzYWhBbkdDdjRyck9FUjhYSXpQbWZyMnVx?oc=5
panjang artikel: 1530

Fetch isi artikel:  26%|██▌       | 633/2473 [31:01<2:25:33,  4.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMimAFBVV95cUxPNFp0S0dvYW1COUkweGVFaGZteU9JT0VJT25pbWRwV0NrRWprWW5QdHE4THg1NzBvejZLQ0hTS1VNZi1oR3R0SmhPY0tUZXY2M3BVU1Y1Q1J1c1hIczBzU19ZT2JmNHZMTjdZS1NXVVI5TTIwRUxxWXZkUGdnV3d2Vnd5aDlCLVNVOFdzZmd5RlFsVk10X1dwYdIBlwFBVV95cUxPaDc2Vmt4UklkVkdLaWJiVXQ1ZFVfb0JjZzFHVUR6d0U0Snk1M2ViS1FOaGUweXRqTmpDS3N4UmpIckpJSDVHWnd1dFlOVWNuZlNwbTdPU2RrYUZxMU5EVUdpbUROMWh0bEgxVnpMU01sQ0gxWHdoQlU4Z3FoNEQzY3d2WWhLYUJLeDNMYm9rOFpPVUxIR3ln?oc=5
panjang artikel: 1936

Fetch isi artikel:  26%|██▌       | 634/2473 [31:06<2:28:46,  4.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxPZFVuUXJ1S1B6UXl3VlBoekJWOWFzalVQd2VWZk03ZFNwM3RLaGFpZlJ2Q1Fyb2R2LVpUUVQ4Zjd1ZFpoX2xRZlV5YmkycHBJTTl3RnZuVWVBcHppc21HMk40RXVyVzBPelZKV1l4SmZYcWtwZmZfcEpjWFlxQjN6UTdFSXJLaXp2ajZBdS16blRTWDJoZXVOeVVhQmtyU2tXanZjTkZxUldvV01KRTVxWlFlY9IBuAFBVV95cUxORTg2NG9TZDdrLUVrZUNIVHp2NHVNZE1neGJtczBSZVpGWk5UYW9rZ3hkakZqTDRGYWtJLWtzQUplanZIdHhMZTFkb0VSVGtjc3hwSUJEUEZYSllpWE94aTl4RThiOHNYeDFHeW9SRnF5X3U4a2c2YmYxbGJxN0x1LUd1QjFCTmtIZ0tMMkNuc0NSYXpIMTVtaTBMZ1djbjZkODVXYmlidGp3bUJBbkRMa3hmZ3YwVUdh?oc=5
panjang artikel: 3874

Fetch isi artikel:  26%|██▌       | 635/2473 [31:11<2:25:37,  4.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxOWDI4ZE16Y1FOWGdkR19oUklzSVVxc1QtSURqaVQxenN4a0NVQzRvWmtBcGRScUlkRmREWEI2Y3N5YWcxNkxETExCYVZIa2RoUlE0bjl4RTBBVkFrc1EzZmZ6NkpRWjVnRmg5SVJ1Wlh4ODQ5RDB1NE1PX0w5aTBTRHhaNDY3RE9BZXNTMjZZN2hxWWEwVVJhUVRYeVJFVVFCTEhCTWJhVjhWTlFtbWRBLU5PcWtZNkJMUDBITkRFa3FlWmtreldVNkhhVFc1d9IB0wFBVV95cUxQMTlGcHZJRXFaMXk5UFB0ZVBjNjZYYkNRNFRDcERuZHFabUl3X014b3Jsa2dGU3FRUjdqcldkeURnakF0ckZFVGttSVh5amhTLW96dkdDclU1UHpXbkU3UlN0Z2Y5S0NleHUzb056VkgtYXgxeS1fODdIekxBNHRWTV9iUVowNkFCRlFlcXdNeEV4cEVLVWtGenh4akRRNTV0d3ZLemZmTXo0N19BNDZFTjUtUlFfanB4TTdYN1Ita3FnY2VWaGZHSFpHSXdWb3BWNkRN?oc=5
panjang artikel: 3267

Fetch isi artikel:  26%|██▌       | 636/2473 [31:15<2:21:33,  4.62s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxPTnFmYXlsOHZWcldFWE1JMXJMdThKSUJSOF9DbjVCUWNTZXR3b09vclA4RTFqWkx4eWMtRE5wbTBhWEdHcE5ack9XLWtZdExMWTR3MGRrQ2M2YVh4UVdBRk5pWHNNOF93ejd6QTgxS3RkRzlNT3RHZXc3NlNtckI3bXh2WkFyUGxFMmRnSVdlOGdwOXRXOWZ3N01YcTRJRzNLNjBNeNIBqgFBVV95cUxQb19UN09xNUFnLUFzVHNwX05qTUFtd2NCaTZSb1B3M3h6aFJrcDM0RUlCX2pWYUd0Zy00eExmY2lKb0REV1ZWNmp2MFFWYUs2TjRWTGZNT0RUSGNfQ0l5RkE2TU1XNGtLeS0yT3ZnRW5WS0FiMmRDOWp0Z0M4VDgzSDhKZ1NhSWxoQkhJc3pwT2xZR1RJOEZRU2dOYzdfeklPTHhCRHBVdUpudw?oc=5
panjang artikel: 4456

Fetch isi artikel:  26%|██▌       | 637/2473 [31:20<2:22:27,  4.66s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxPYm5KNVZpNklvYXBWaWVWMTd0SHd4V2xoOW5HR1ZjTk1xUy1RdG1oX2NVX3FON2V6Z183NG11b2xhTGRNa05OX3lTMXZrVVFHeExsMjUzR19OTlBOMHE1a3d6N1VmSEZqZ2ZkVzBGMG1PQkl5Z0FzcmVLbU1nZ3hEOFFhcFJfSWxBc1VPeU5wdmw4aEZuRzE1Vm9rZnJtczJhNjhjajZpZzlzRmVhZ2VYeE02TVh1aElQQnfSAb8BQVVfeXFMT1NlZkI1ek4weUloM0wxUmF0YmlfWUJOTjgtWnAxdjNwUjB2UUd4UWNWM2JSb1lSaWNyX08xMWRwaWlyV0ltNzlranJyUEZlbE1kbGxPSFpHTmcwVUFQYzk2Xy1yRlFrdHNTSU9jVS1FZ1hIRDZsTlpGaFlzNDk0QnlPT2JWUmllWGdjRGduaU5EY1hnb3Q0UVZGWjdBTXQ5RElXQ04ta08zR2JUZlRvYTVHNXplVURoQVNyWlJ6aFE?oc=5
panjang artikel: 1678

Fetch isi artikel:  26%|██▌       | 638/2473 [31:24<2:19:16,  4.55s/it]

Fetching link: https://news.google.com/rss/articles/CBMioAFBVV95cUxPSWwtWUdFbTlCMk8zU0FyQnFkRmVPT3RxS0IxYmRkUzlPdFNLMDA4SFdqdk45d0NOWER3RFdZZWdpRmlSTUYtNGhhUHRQcnhqVjRZNkxtTTlUTXNQeGdXLUZVSFZpTktqMVZja0RQLTctOF91LVdVTTNSZHJhYTRLaTdscmRNMnc2dVB1OG1zQllBTTlOdGNhOUxBcTdQY1JP0gGmAUFVX3lxTFAwNnVQS3AtQzg3QnFhMUVqWUctLUlNVkNON2hpLVZTVFFQSzROc2lEN1J5bDFIT0p4N3F5aEdwVXZjNEpnZU1ocXBBc1NKYm5HVWtlWHBmR05ZbU95VkFXNXdyMEY4dXVrQVZaU243TGNSelpxUlVoZzN4T1ZuZmNUNXJ2NVFRTTVBOXh5VkR6bjktZE5aS3duazRCZUdfdXFHck5NTmc?oc=5
panjang artikel: 3679

Fetch isi artikel:  26%|██▌       | 639/2473 [31:29<2:18:29,  4.53s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxNci1ZSjFhcE96Sm1KMUZrUlhrekUyYlB1NlM2T2ZodTB2d05ncHJnaFoxZnVpQVVsS2dUT2RNTEhvazFnNW43TGxsU3VWakxhQUZCdlZiMDBLbFZ6NUxkU1dDdXFUd3k2WFdNUEVESkJobTNaYVd5YUhhTUdfRTFFYlROOG1xWjZodjdjZ2dvSHlQemxLZExOQ2lnS0xucWp5cUZVd2NPTXQzZw?oc=5
panjang artikel: 270

Fetch isi artikel:  26%|██▌       | 640/2473 [31:33<2:19:01,  4.55s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxNQUFJaERUdWJ0ZW9hMEtGQkdkS0ZRNU5fcXJGLU5ORUhVaG16SDNqN1BiSGhWQ3RnR201d3RWTEF4M1ZBZ01mZzA1d3FiZVphaUZLOW1saU1sZWNPVU81dnFhVi1nbjd4Y1BTRGlkWEZsZU5NZk9KeU9VVElfNjJ5VnEtZkZ5d3RsYmlGckxGbGZRUEsxU3V1a01qeHNyM1RIV0RlZlQ4Y2p1bjBNTWRaRkdtZFRhQWJaU1k2Zm5nN2FxQnE2ai1oclowU0tFQjTSAdQBQVVfeXFMTlRDQVZMb3k1N3RuVVNLYlJEX0t5NU1xZXcwYnlWRFZmV0QyanBtYmQzOThNRjdMTjMxSE1TemdqcHlWSmIwdHVOQjBCNG5EVXJHZERCamdTYm9nQ2NsTzQ5cUJrTXFkcjFKSmp1U2pBOE5WNkNsd3NEOWRrWDBDcFh1dFF3QjR6YlVaVUNORmlIQkhjcTNoY1NLMW04NTBwTEl1U0tsbHdIcnkwWmV2dGZvSTNqamJOcC1pWlNuYklqTlRtX2lIYnhKcm1UaTlPVHVFRFA?oc=5
panjang artikel: 5948

Fetch isi artikel:  26%|██▌       | 641/2473 [31:38<2:19:37,  4.57s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxQWW9sZ253MEVKRldfM1JNTjhzMUdXVG95Ql83VFZ1YTlSV3NJTXQyLWFCV0VWYm83Yk5WLTBkUDVSVXBFRnphaUhPX3B0aV9DSUJyVDVGcHVnNXp4RmsxOVJGY0xDeEtDeW1BaGZzQS0yVHh4RjFUM3hhV0lDUWNKY0dSSG1ia0cwZTEtZHZES2drbDVRMHNLR2JWWDNrUkR6WTNwN1BMLU9Vd0xIWlE?oc=5
panjang artikel: 258

Fetch isi artikel:  26%|██▌       | 642/2473 [31:42<2:15:29,  4.44s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3wFBVV95cUxPRG00QkZzZDViQnJ1d0lLSE9CQTU1aDVTaVJkX1RNSE55eWg2Sld2Nm5lSnFWVEFtNVh0c2twU1NIM1JOUlY1ajZ3dDZRaTg2VDJreUc5OUhQanhHVkdSYnVySU1GMktBNWQwbmFINEMtNzc1UDU5dmFpemQ0QmxPdXdrR0Q3SW9JeVliTWx0RWRQdnVwWk9HWmdfb2ZFOVQ0UFJzYWlDaGczSzc1VDRVNU1sSEdZNmFPVmpRTVZ2V1Y1VWJyYlpiNlpzdjUyR0xjWHBwMWs3bll5Z2ZUdkpj0gHkAUFVX3lxTE5Kbm0yS3VUMHRRaGotcmt4anJJSzkyUHZBMng5bWxqTm5MYV9BSUdUdzBCODJXcTRYbnE5NlhQY0JzRG8wUDNBN3ROLUdqMWZNV2dLRnVEbklFQ0ppTjdKdzZBUGFvOFpiemZEZ2FvR09wMW5IZ0dJVVozd0szUHRMd1p4T2xlUDRiSF9jN01WM1ZLcGdyNDM2YlQ2enpzOXhiRWg3U0xEcTBxekl5M0tKbktLQ2Q2RUdoTjdvUDdISHRWUEtHNFVuWTNRbmZlMFRzNVdmbVE3T0gwaVVUcDZzMGFjWQ?oc=5
panjang artikel: 186

Fetch isi artikel:  26%|██▌       | 643/2473 [31:46<2:14:37,  4.41s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxNVTFiUlpqNXc3bGNIbWlZU0tDLU42Z2pqeFFfTThlUlVHdVFGVW9hODFrTjJxNmxxY2dyVGQ3OGxPOHhxSnJoVy1qMEVqamtJRlE5ejJKR0JCYmFDSEc5eTZBak1iVGpiZ2NBVUxNSUlkb3JUT0FmdmlWRF9FTkZmSjVxbVVVU3dWMV9yUkRfd2daQ0lWWHY0Z3VHd0hfNVlLQnZIT0I1aXJ1TGd5VUlMUUhvMllfZ2tGNFVsODEyZ1HSAb8BQVVfeXFMUElaclpub0FDZDdTOVVDRXp6SmtZa3VfYnVpR0wxOW1YX3NtakluRTNyaWttajZiN09ad3FhbmlXQ1J3dUFsREVLVXhfUjN4ZlZXVF9PNmtCazhqNGR0akhxOTZZNzN6TkRyU0ItNmdrN3FDWHNJeXdUOWNsaFB3UEp0LW9rUlJyMFg0dFVZOUpuVkgyREIzZFNEX1FsZUFyOVFYc2NKUkdWdjRVYzBrcjFzNjRtWE4wbGVVSnNkTFU?oc=5
panjang artikel: 1937

Fetch isi artikel:  26%|██▌       | 644/2473 [31:51<2:16:32,  4.48s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPeWhONWsxZGN4TmZ4bWE1NXlHYk5Vei13Y2drU1RQd2ZvY2VxOUE4b19ocF9WcWNyYnYtVzhOcGtPSWxZMVdtWUFaRjJQV3VGVTJpWDFDZXZKNzJVdEFlTEU5NHJDMWQwRlFRZk9XTVRhUUQxLWRYbjRvRDJCamV5SkhRTzZNUHZUQ2d4UDg1dlhGem5vOTFKZ3JLUzJ0ZnBMNC1INWQ2TS1yOFNjRTBXTnlR?oc=5
panjang artikel: 639

Fetch isi artikel:  26%|██▌       | 645/2473 [31:55<2:10:44,  4.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxNeUVXS0xhd1JpZUxYYlB3clBobmtpM2EtYU5IdEUzMndWTzdSZlBHYkxjdmxXYjBtS2pyZU1hOVhsWV8xc3RuaGpVczBPaEhrcEdIVW5hUjVWZVdLX0xqS0MySTdGUktQSVEzZWRzcXhHM2VOZ0NTRlJXV2NLMEdHdWVoeTdiemhtWDhCWDlOVE9nOENkZkRXNlRCSjNacE5xRXJYcEluYkFwNmJadER3Zm1GbmVKN0xCckE?oc=5
panjang artikel: 3734

Fetch isi artikel:  26%|██▌       | 646/2473 [32:00<2:16:12,  4.47s/it]

Fetching link: https://news.google.com/rss/articles/CBMihwFBVV95cUxOZjhGUUh3alBzNTBQQTBwSko2Y0FhUFo0UXM5SFRfeE5Va1JPZUpJTDhKZ09GVUh1cEF6N2otVWQ2SFdvRHRqVm0yX3QtcVhOYnBWdkc4T2NQU3RNSHZLU3RBMDdrX3k5MnNGUEdIY2hldVpGRkxlX0J1bUZ2RW95SnFLWUQxdjA?oc=5
panjang artikel: 3138

Fetch isi artikel:  26%|██▌       | 647/2473 [32:04<2:16:14,  4.48s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxPckVCLTdxNkNEXzlaY3J2R0Q2b0VJZGhXNy1qTlJITXg3VnRrbjh0NlkxaExCTFB5TE9OcE5ETlZTX25oXzVPUXpEbGtELWJMYTdxZjdhb1p0akJCUkZPbWRlMzRMcXhaZHBNdkRFWXlXVDZDdzM5M0pfUS1OTURnVzVNWGxCeldyd3ZFbHNUaGZ1dU8wOEc5ak8yZ2oyYUdEMXJ3X2JsVFRrMzlFSEQ3ZtIBtgFBVV95cUxNNVQ4NlRWUjQxNGtZYlBuUWRRQ29BV2prYjFZcXJ5YVdDQk9YeG1BTkhIOWNLTXpneHltdXpRNkpvX1pXUl9zTjZ1XzJOenFYWGd2Q0MtaGl5VkJwZ0hCaTNyQ09OdlVFRFVpWjJiR2t3MExoVXpjSlBmb3JyMUNjVWFTNjdRclhEWjRJVlBOcHpPMWJIM1pMc0NwamR5MWNUSjFUQUw5MEFFaUozRnEwN2dSRG1iUQ?oc=5
panjang artikel: 3332

Fetch isi artikel:  26%|██▌       | 648/2473 [32:08<2:12:04,  4.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxPa0xHNmRoRjd1Nkdic3pXSGFLcXQ1dWR6aXJBNlRqVWJYa1hRQ2V0cmRsbmhSOUVZMXVTVzkyTEh3aFdGUVdhRjgxdnVma0FmNGVFb1JYT0FHVjFNS1JwNHItbkFSaFR5a2pRWEVUeXBydkE2dzYxTEQyUFdLbmxkOXVpdkJfQVBYNVR6RVFEREN4bkVQVi1sMW9jYWxyTTZjcUE?oc=5
panjang artikel: 2360

Fetch isi artikel:  26%|██▌       | 649/2473 [32:18<2:56:57,  5.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxQNzA3WHZmd2JaUXBHbWRieExOVDV0S20tUmVyR1A5V0VhbF9JYjJLRjZ4X0lZcjRiYl85YVlZbFRBdDNENDRncUp5WnpvMmlFc3dMb2dVak1YWFBsRHdqR2wwbTUxdEQ1bzFQbjdtZVR2RHNScDdWcTZHWnVPeXFFX01VM25QMUQ0ME95dWh4eXloTi02TVBjNlRxTGR5c0dXZ214TWIzajdsLWxpZnEwQUFmYzIzRVptY043VTV2a0JFUQ?oc=5
panjang artikel: 2725

Fetch isi artikel:  26%|██▋       | 650/2473 [32:24<3:00:26,  5.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMiaEFVX3lxTE5STkZmQndVTFBLT2s5M21JbVhxbzhmZFhLbFFZUDRTNDNHUkxsT0c1ak1ENUQ2NE51RUo2OXlJTmdkOFJEWlBhd1dLazJIMklVVUljR3BqcFZhR1g3ejdRTVMxQ3NOZGxp?oc=5
panjang artikel: 1449

Fetch isi artikel:  26%|██▋       | 651/2473 [32:28<2:40:41,  5.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMinwFBVV95cUxNOHlrdEgzeDFtd3p0NEUzN29CYW5VdmptRWhvd2RnNkotMHQ0QUl5SFVwUHRxQmpGOGJYQ3pMV0VxeFluT1d2QnlmRXBVWkhUNlNyT1ZnQVhPckhlUTBWQVRsNjBxTmxteUs5cDEyMEJzczBJZWZGQ0ZySE9PR0V1TXhkYmg2TUhVS2MtUDNrWkktM3B0eC1oNy1haUJyeWvSAaIBQVVfeXFMTmQ5cjVJb01kRnc3YXZuT1kzY0M2V1NUX1dQdDBtVWs5R2tueG5ydlZEQVlHMThycHlSZ2hxYlFERjV0NVg2RWt3T1hjSEgwR1YxZy00a1FPSXFwWWhzRmN1QmcyVlZBRnRfV2RtTTJBYndxblpYdHhTYlF1QWhkeWlXaUdveGFFUTFWNThZc2J4aW0zSGVoeEg0Y2h2dld5amNR?oc=5
panjang artikel: 3096

Fetch isi artikel:  26%|██▋       | 652/2473 [32:32<2:29:02,  4.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxPQ3RmeE5LT0syb0NMVlIxMGJoTThhbW0xUDdlemJ2ZTYxdnhCb2NQVTYxeEE0Q2Q2QmZMU2ZnQ0NVci1vLWVYZXA1TldWcFRtSHFHczNDNHRSaFVIV3prRl9SRl9OYVhEYnVCbmZWUzExZVRQbGw0VVBxVkstVm9NS3VOTTNaNlBwc2RiQU1kcS05YV9OWXNaZFd6VVhlQWVhN2liTTNYY3AxVlF5UFBWbFFjRllQZWlEQzUw?oc=5
panjang artikel: 2499

Fetch isi artikel:  26%|██▋       | 653/2473 [32:39<2:49:55,  5.60s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxPV1VVeXJjUktnbWJrQkp4VGJ1TjRnVmtiRXBHY29xQ3NCV0taejBZNWllaVk5LW85YkE0MTg2QkFpZ3k3WXZiMzA5Q2loTTA1QWNPbnNEZ2EzSDYtaTdjendPVkp5QkhfYWFqa1EyNG1Gek5CYklaMHdXdVRDNUxnUUFvbXY5X3F5RlUxcW9jYXZ4NEJ3dGRoNVNzZ1RXYWhUbGlSTWk0ZXN6bUFxemppcVFSV1MxYldRWDNEUXc4TG0wUdIBygFBVV95cUxPbW0tS3NMTTNMQklxZk94MW5nWGJqSGlGVjhhYi1VaEtwLUtEZEhWMnhMUHVERmdhNnJPUDd2YmRMUzliaDU0d2RGTE1mSjBLZm9makVmZThOSmYwYmtRSE5KWGQ1bnhyZnVYSDFZZi1VQ1NjNU15eG5BdXlZbjd1RHJ6LWFTdlkwR1VpRzJESWxBVHhXYTdyRXE2aTlpREZMQVZhOFFhcmFqNG9JZ0MtanhBVXRQUlhGMGZsVlVnWWxzOE8tbXh2Qm9R?oc=5
panjang artikel: 2652

Fetch isi artikel:  26%|██▋       | 654/2473 [32:44<2:43:04,  5.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxNWlgyRHk0ZEp2bDQyNU1NMV8tWjR1ZmgwbEpOSExqU3VpSTExUXBFWG5fRGotbi1qZDVCempoQ0xyUDVaVUFkd2dVclBFb0p0WVF2QThrVXVNaUFKTWhYOWlnSGtkNXVpNXd5dmM2MHF6UU5YNkg3bEZ0OGlNaVotY0p6a1RhbjJNb2hJMVZaZmhYRWJZYjA0cFpoNHdTdUZlTURKdGxweTQ4Zw?oc=5
panjang artikel: 3969

Fetch isi artikel:  26%|██▋       | 655/2473 [32:47<2:28:49,  4.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxQV2JUTFYwakdyc2pDbXUtcm8yeXdVQk1LUzVlU2lrbGtOYl81ek8xQ1l4aHdQVjhqTmVYR1FHOFB2cW5YT0c0RHc2enFWOUtaODAyLTBWRzQ5dnBIX1JJVG44MV83LW5aNUVJM3l2TEM2eXRmajl0MFB0WVhRTkN3UjBpRjROYXYyeVZ0MmZOV3ZIT2l5OFBFSnU0YU9PMXJlUWhGZmlaNA?oc=5
panjang artikel: 1512

Fetch isi artikel:  27%|██▋       | 656/2473 [32:52<2:21:01,  4.66s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxPM1ZKNU1YcDRDb1ZmcEpheXBKR2oya3RuNzJ0dE5faS1YYktadGNyUUN5ZVpScWRiampnaHlzWXZqRTF3dHVocmF6QjN4elJOczRzc1FXdm1keHNGSnp2clRSWE5lSXpvOEtuVU1SeW9COWNYeExkM2MyVFljSjJCWVZjMk50SGFBenV0V1gyRnpmTUtILXl0TmozZG9KUWpYVnpGRm5HRVpFa0l2VjhtZlRCUkVqalpKTHJSNXo0NXVucmZEOVlz?oc=5
panjang artikel: 2481

Fetch isi artikel:  27%|██▋       | 657/2473 [32:57<2:24:04,  4.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxQZVBsMm9vbWhQWHcwRmdyXzdVLUpTdm5vMF9jM2o5OGFuMk95Tk5qZmdsQ3NmckJiM2dJM1VRT1BsOXJMekxtU0RPNTcwVFVaRUExMjhrams3d1daeFpNZEF6Y1VDNENweDROYUZmUjlRQ3YtN0RTNlJwYTd5eDRRTUJoVFRTdVVmOTJYbnV6VURUXzZWUFMxa1Mxb0g0X1BJbUdZelVMTUlVUFlMNnhHT3pZakgzTzNSTWIweWZFVnZWMGvSAcgBQVVfeXFMT0ZaVDNaemRtdHItY0s2ZHZxaEhMVW9kYkN6SmZrR2xrRzc2LWVYMGF5N2xiN1Jqd3JLaFJyRWF6ZlRtcUVPY1Jac3JNeHR6RGUwcDN2d0E2eUVQZ2VkOTdZRDdmWnRJLXN3TGQtMXAtVkVOSThhNjJSV0M3SE0zRElYR3hWTnhZaGZuS1p4RjJEbV84Y3hKTlZSbkVfQ2dYZzgyM29vQnB5d0xWWnlrV1dzUGw5SlR2U2RROXBJSXRROW1uUUV0c2s?oc=5
panjang artikel: 2527

Fetch isi artikel:  27%|██▋       | 658/2473 [33:01<2:17:38,  4.55s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxOV2ZNcXV5V0tCTGVuX05TNms2RUJsMlRJSWVCc0FtUW5MUWp6cHl3OUktaTBNTW8xeEdRMEMyZkhXR0o2LVR3Wkd0UXZRVEllT09FeTZnUEc2VS1xVjhDSXhNeDJlZmZzdnoxb0VPeG9jY09vVmZuUlV0bUxVV0lUNFFSTVF5Y1hJS0Y5bnJVdGxUSDl0dXdYanNPUjZ0RG0zYm1Ec1FMXy1CaDBrYmE3SkswbnBXYW52aWhmTW91REs3dkpZYzlrZ21Pc2FWMHpZYk0xXzlucjBoSFXSAdsBQVVfeXFMT1N5SlVOYTVlN3FLSWljN3VGN3VvQnpieVk5cWhtTVZ5WTQ3X2JTUFFsQjVfMVg5aUZ2RzRWNTBVMzByMWdkQ2pTV1dnOF9YMF8ybURldVNuOGJlblYzWnh5bzhLRFR5dEdQUENSaEV4Q1RhMUtHS0tCTng4OFpUM292cU04TGVZZVJhZG96Z05MQ005UXZfMGhjS3Z6ZVVjcmQwUHEzZEZTYm41eTdUZkkyR2UzM0VMTDdnaWVrSU4xbk9fZUtOX0hJRU11cjdmSXYzSXFIRmE3WW1j?oc=5
panjang artikel: 103

Fetch isi artikel:  27%|██▋       | 659/2473 [33:04<2:10:10,  4.31s/it]

Fetching link: https://news.google.com/rss/articles/CBMihAFBVV95cUxOcUxtUjB3WVRHUE5WLVptQU1qS3N1cS11NEh1bUdwZEJzdlFZR2o4V1R2eUEwWUpGanB6RVpjWjRGWXdKb0FXYWFHa1lsdkMzbUpPSmZMZUhFT29acm1MZXJWd2hFUUNjUzNOVEFSYkhXaXM0SDYxWTVfdXloLVp5Q1RwVUc?oc=5
panjang artikel: 4187

Fetch isi artikel:  27%|██▋       | 660/2473 [33:08<2:08:07,  4.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxNSVRhY2w2WmJhcnBoVFY5SDhLYlJSRXQwdzZiNVhMUmJfNHR0Wkd3Q0N6elVEai1fbWdLRmdpenRHSXp4Y1ZVT0FLRjIzMElUMnlPTzduTlVrM3ZZWlZ0VTFoN3E0dnpTYkFqQXJzbG9INzd3NkhJd0lXZ2lsWTZkM3RRNnJqOE9MSURNYXhkTjZrU2ZwRVpBNzhKMHlOcWZCQ0kxRWpkdWg1U1JW0gGwAUFVX3lxTE5ONW1BM0s5bmpvV1dQU1hLQzJhYlJfRDZWLXh3NW1jLUpJSFZNeEJ6RUZyRmVRNFZNYnZzUDFCcWNRNlFFdzZBYnEyMWowTDlLV1AtUHV5V2txSDZyRmVERER4NnVvVWViYU5qVGJYUWh2bnduRU42bm92MG8yNkxVZ25jLTJoZGVjckQyb21EZUZwaHc4cnJSam50UnlzWXpRVEdnQmM4X2VuMVFpZ0Nk?oc=5
panjang artikel: 162

Fetch isi artikel:  27%|██▋       | 661/2473 [33:13<2:09:30,  4.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxNWTd6ZGpLa2JieC1kdjU5a2dOWHFIYjBKOUpsSnlMdHpfS2xsYTRmQXJfaUlXdmQ0VGJEdk1yMTktbWZhMUxMZDQ0Z1BtZkRUQ1pnUHJya1lqYmMycWxPN1ZrQTJNd0NfY1c3ekEtWk5kVWxhSVYtSFRVQjhQU1VYMFNrOF9CLXgxcDR2Q1ZyYzVLMmNhMVl5VUdCMHFlMWdDUTZySlJ6QXpIWWZrYS1XYm5QeTjSAboBQVVfeXFMT3B0SThCdWRoRkg4TWRVYkJwRHBwaHNNQVRwZmJBSVcxdXM3ODBlaHVnbnI3Y0FaMUJhMHdzSUt1TVpQRnNiRWtHTlFpZWNtUGRGWlVUZ1Y4WWVRcTdqOENQc1hmTUZ0Nll2eWZjUkQtcjR1eXJrUG5OQkk0Y1pWZVp6SFREcnNPNUlHR0dwRm5HOVpabWdYSE9XeVpGNFNta1RZS0d4OVZnSHBsLUV5Si0tbDVRdHA3Y01B?oc=5
panjang artikel: 2066

Fetch isi artikel:  27%|██▋       | 662/2473 [33:18<2:17:29,  4.56s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxNTDZEcFo3OG9aVktqdWlRRzI5SDJMV0JvR2pJY0M2OGYxbzJtS3BnWDNkVEJLd1dTc3dKbW9ETmZfM1BrRTdvZTdfbHRjT0Y4OGNRVWdEc3d6MnVkNnhOMFUzRWRFY0dHYzFSbHJNc1hLdVNvakhQZThfYkg3OHYtenpfanZNTTFSUXNnWEh3ZXRPa25SS0ZiQnU1NzhJRFF3czRGVDllbjYwaFJYbUxMbDRqOC1yODTSAbwBQVVfeXFMUHdMV1pzQV9rUW83MHNnUFRvaU12ZVJJYXRxSGgwZjdmWHV3X3dsTjlKVldfd1VxWENHcE1VY2QzZ3dwQzVCSVhfZjFNRjlDZVdRNXdLamx5c1ZHaFJPMFNkYmNFLS16Q2U0aTdtdlhPREVwSWJYTGlvOFQ1U2d5UmhYMlNINUw2elM1UldEWC1uczdWRTdkcnZERjdmWFpBaUlHbThWc21RY0tOZldaRXppazVRSk0xLUYzdHI?oc=5
panjang artikel: 3026

Fetch isi artikel:  27%|██▋       | 663/2473 [33:23<2:19:14,  4.62s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxQb0VVZjI3NVhSTHRSV3RpMkhNNFdHa0FTSWZHN211MWY5bFY1NGdELU1TYzR5SkttajNYUTlsbzI3ZDRrT0hZYjhvR0RjdGhoaDVMc044bERHWXdueHBZa1B4c3drcm5tNGlzRWJpdDBZMVY1WkRKeGdibzA0VURINFItWWpqX2trYUpRcFZHakp6V0VMWWIyLVhXT3d5RkFhM1JFeXppNmRxZw?oc=5
panjang artikel: 448

Fetch isi artikel:  27%|██▋       | 664/2473 [33:27<2:15:05,  4.48s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0wFBVV95cUxQOTNMRVlILTVydGxaeWxKVTFoT0c3bzBnTUxncWdGbzFqNXRWNW5aQlc0WHJBOTJVeHRlcnB3dWZfNzRMUXM3UXFSSmVsQ3U2VGI1Z1FrWHJ6bDZjSlBja0pxR1FlSWs1c25lb0t0bThxV1ZsSkkyRmVWdHRPM0gzdl9VV3BQSGhBWlpmR0U0UXNVWktDck12bzNwTHBJd0NrX2JhaXlDWUpWSVdrN2Y1aHh0Mkl3ZWQxZHk5TUJKZWdmLW8zYURIT2pZQ2xGQm9FNmxr0gHTAUFVX3lxTE9tc29nUUNORGVzc3FqQ2V6M3lKOXRGQk1KX0duM1h6VTRCdDVtNGQ5OUJmSHVqdVpjaXZ5cEwtZ3ZQc1hUd2xoNy1wS2JmcUVmTnlMemNRaDFzWDRvc3hQLUtHclREeDJid01udVRPX3owMlJIR3FfMUFYSXU2dnpBaWxXRDJYMjZKUE9oWTd4VWR3bm9mN0N1SlVQcVNlNGtGaEs1NlFfZTAtbU5KVjQ3emlLYlRyM3k3RTVrM2JuWXdoTWs1QTNxdm1vZkpxZ2hrb00?oc=5
panjang artikel: 175

Fetch isi artikel:  27%|██▋       | 665/2473 [33:31<2:09:00,  4.28s/it]

Fetching link: https://news.google.com/rss/articles/CBMilwFBVV95cUxOQm45dHFpWm5UOTJSbnZBUElodGFMQzRnc3lteUdNLWxzRHA3Wm1aV04wVnlQQmFLSHhUWUFVVFZtMzlWR3hKN0tPQlhPUmxBNzJsTlY5VWg2cG44SjJlbGNhYzMwNFE0enVHTXc3bktkOVoxUTBXamNWc3k4UTBnTmhnd2xFUElqM2VRX0haOGFOdjc4ODJz0gGWAUFVX3lxTE5iMjNvX0VyRUNJVXVsTXZTQ3Y4WkxZQ0NmdXVhWkpOTEg0R2NrVXJUaEdrc0xuSjdrZ1llOGNTdmZwa21OLWtJZXRJMHZNTkxORnlnR19vVUdKRGV3OW8yNXgzN29rQi1KekxiQjBCYm1Zc25Dd1lMeGpiVG00RXRhQTFSdl9MXzdFTTFEYnIzaW9aU3hsdw?oc=5
panjang artikel: 1668

Fetch isi artikel:  27%|██▋       | 666/2473 [33:35<2:09:20,  4.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxPNkozQnVVYjM1RllGaXdaRTZhQ3FFTWZXamM1TUNqT0dYWmhic3VrWV9wX3FFdWNQcWJsWjM1UmxzRUVLNVVMYUlyUG1yUnppaG1OdjVJYTZQM3dVazlSb3dzRWMxOHd0d3p2RW1HRWZNaExwZW5IUWdPZ1M1b0FJLWpmUS14Vmt2ZW9uRVBrejhQZnFfNDVkRHpsdmV2Rll6dHVsdnYwTHhqS3pRU3BUaXpfU0ZuZzVOZ3FUTmlMd1N2dDY3UDZodERB0gHPAUFVX3lxTE11MHk2NGFlSDdMOHVFWFJFRGpha3l4TEgxMUFzb290d3pxUFNOYUhhT3dxLW45T2ZzQnFTaVNvSGViVEVlYVFpS3ZQcTVfY191U290aGdWd3Z6WkhJNTlOVVAwNWhMcXduSG1NWWxDUm42WWYtdWZxOXFEaW5xeU9PWEl3YWtiVy12MktkNHhyUjhhZHVRa3EtRnVLb1lhTWxneENNUTIwNl90cGgxNEtqdUhBbWs4a3VxeEIwcF9ZSEtmYVFaMjZNNjd4MkVDZw?oc=5
panjang artikel: 1679

Fetch isi artikel:  27%|██▋       | 667/2473 [33:39<2:08:06,  4.26s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxNUFN2TmNxNEFRdkZrVjBvVDhaT1VPNWdNVVRmbXZ6elRMOVRFZ0NPRzVtWW1VQ2VmTnJHM0xBOGNIYU5kLW54d3BwbzY3WGdxc2tfclV4R3J3YnVVMzN5Q0h4NmE1RXhTcFEtM1ZuakRsenp4My1aNE5maDRqTV83Vk5mblFkcXh2TFVYOXowY2ZGdzdMT0JKTjVicHpfM08zUlhsSHd6djJsZmhQbFp0eF8tdw?oc=5
panjang artikel: 2025

Fetch isi artikel:  27%|██▋       | 668/2473 [33:43<2:05:36,  4.18s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxQMDV5X2Z5aV84Zkl3a1VKZFlqNXJCbVlsQ0gxVDNHcGZWZUJfSjdsblBPS0prSnlZSFBKQUlfMGF2N2xtcThlUmo5R0pzN2ZtWmtESXZCemNHVFF6RndGMTNsMnZDaHBtVkhJT1RWXy1sc3BzQ2dmbDVPMlpxR0dCangxTTVNZl9jQzdlcXdocUFDR1R5Z1lfLXFJblNha3l1Sjh2UWNRN3RVZm1TWU1ULXRKYWlOX29XRTNNQmRLUVd6MXfSAcgBQVVfeXFMTUtranVlVWM2MS1IM0pUWm05U25GNC0tVG54RW1jeDFkcXp4dU5MS1F1a3d2RGxDRERrZlZ3MUxrLXpfNGpxRTI2emYwbkFSeDZjRE9Pdm5NR05sREZLemdxT3dFcG50Q1NrUHdIZTdZdkdHMmY5dWY5bWZaeTc3VW5udmV2VXFaM3ZFXzl3UXNqU3pJbzFZV3pBMTlDY05WLVF3LS1nSkRnell5SjFzRTIzTE1oalJKM1ZIVElzVXBzWmdhWW9RRjE?oc=5
panjang artikel: 7550

Fetch isi artikel:  27%|██▋       | 669/2473 [33:48<2:08:21,  4.27s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxPclZ5dm9JUzZlaDZRUEM1OVhzQTBTWEJscTlIdWtzMTdnQWFxdHRsMV9jcXhGNjBibURJSFFNQ3BzOVZwbE5aSGJHREtKbFEtdFY3UkxIaTdkR2x1X0huX19wUjhiV3pfekt2RlVGTkZIZXZfeFY0RU9CRjhZV29nMWZLRkN6RlE2NFpSSXhQM3A3YVZ3TEZQSHhvUHExVHFwelRfZFVOM1FCanhDS2tyeHZGMDVtdw?oc=5
panjang artikel: 2151

Fetch isi artikel:  27%|██▋       | 670/2473 [33:52<2:07:34,  4.25s/it]

Fetching link: https://news.google.com/rss/articles/CBMiakFVX3lxTE5sYWFGXy11bkhHcnh3NWU1aTROWG5zalVxUUpKSm9YdmtGT2k4d016X2hJZ1FEZnFrOU9fZDNkdnE4dTFZM0F2eUJNQUhvVVctX3d4UXNXU0M4N1Y0OTJ5bHdBUkNIMGI3c3c?oc=5
panjang artikel: 7969

Fetch isi artikel:  27%|██▋       | 671/2473 [33:58<2:25:52,  4.86s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0wFBVV95cUxOdjJ6RHJQbmx3OWNKNTJJbHRBeFFIZDlHaTQtT19HOUFxNkJLU1lHOFRyTXpRZC1KbUVuYzk1aE5aTVA0ZlhvUVFDQ1ZHRjRiY0dEdjhLVWptdDQ1XzcwNThvYzliRFg0NEdORFJpM3A5c1k4VDhiZWtMSGJjc0ZRemUxTFlPbnNDMkN6RTRGUnFGMk5PNFllNk51YVlBeTFQVW1NTm1tN29OWW1Ic1drMzdhS25FaC1kV1J0aElDYkFSYzdLNGtkdDJBb2t3LXNCX2xR?oc=5
panjang artikel: 5068

Fetch isi artikel:  27%|██▋       | 672/2473 [34:03<2:21:19,  4.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxPdDVna1ZKRERJZjRqdDZkYWVyTHNZQ0ZfYjlNTUl1Z3c1R01YT295NDZrM19jUlRUV3ZnVXZSQ1hrQlQ2SC0ybWx5Q3ZvLTd5RXR3S3hJXy1pS1JpTkZkWWx0ekRsNDNYa1NCNEVTUlVCWW5OcnNFdklwejB2Q3RsUTVaLTNZTHo0d2Y4TmlDZVgzcTR6MlFtdE9WSmJIRVVnQ1RjbjZ2UVYyeGkxa2lGOHU3M0hzUXd4MHRF?oc=5
panjang artikel: 3800

Fetch isi artikel:  27%|██▋       | 673/2473 [34:06<2:13:58,  4.47s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxNdTJOanZYYnhSVXdlTTZTc013RTlnSXNkeHp1cFFpSFNrVEhzNUNjOWNWcUxEMVRKZkMtQWJLWlFBLWNJcXM2Z0g4SUpzZHJieDBIaEo4UExqZlo4TmFIaFc5UnpmYjF6LTllYlppb08tSW5Xa0FDTDZQbGo1X09LZW1iSnZKaEFKQXlfWVpYaWZlUmtDZVlZTUtOY0hhZXRyV2c5TFYtajJjWHdId1BwbTEzVHo0QdIBpgFBVV95cUxPNWpJMTFWX3V6WGJENGZiZHhJUmxwS1UtTWxzcmFxeEVKZlUwYUstM0U5NWVHZDlOM1p4NXlNclE0elVXWlItVllQb2hNMUFaYkdrY2FQMWdRWkUtZTh1M3VhM3pId25Db01jS1kxd2lXWjJ4amkwTXRfaHlFZzVNd0llbGJPeVEzOVhEMGxiWS1SRWNwMkd0aXh1WUJfLUlRbVdFajBB?oc=5
panjang artikel: 5470

Fetch isi artikel:  27%|██▋       | 674/2473 [34:11<2:15:29,  4.52s/it]

Fetching link: https://news.google.com/rss/articles/CBMijgFBVV95cUxOcHZLckpZdjY1ODE2dGJteVhBdVpMeFNDdGNOQmNHZDRNNUxJcWowMWlNejlmbHpWcUZ4VXNFVU5iWlB1UVFJWkxhS25HS0pTYW03aWxKWUZGOWR1b0pNRHU0V1pYc1l6VXVPa3lob2xLUmdncGxTNldHdTdiaUFvTnlSS25rWXZNRng3VHln?oc=5
panjang artikel: 5852

Fetch isi artikel:  27%|██▋       | 675/2473 [34:16<2:19:39,  4.66s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxPX3BGSm92bF96SVFJUkxUSFB3UTRySVFmZEJia1YxeE5JM2VBQ0czZzExM21MRWpTNVJGLTdIVVdXSnhWM2NrVUFzcDAzUjF4S1pib2hqaVRtNUVkZmVqWjQ1eFQ3bm1Ybmctb0t6U0ZHV25BMHFCRFhMY2dpZTIzZVRnLXBrZy1NWlFIajlVMzVLNjZUUWxtckw5WXUyX3NFMnV5WS1rRUM5dw?oc=5
panjang artikel: 3412

Fetch isi artikel:  27%|██▋       | 676/2473 [34:21<2:23:08,  4.78s/it]

Fetching link: https://news.google.com/rss/articles/CBMijwFBVV95cUxNa0Nub0huZ0k0b2dIb2wyNXJRUEltd2d5cFlrNS1EblFzcUxaQVpyd01LQUdGOE1mMzVzb0ZmOEtiQnR3NEZ6aTk3MEZJYTRPd0ZEMTk2UHREekVMMzFYazBQaWhYcWZfVExwRlBwLUowR1NvZ29VQ2x2blhjanM0enBacEVYaHVkRUIzRFhzWQ?oc=5
panjang artikel: 3884

Fetch isi artikel:  27%|██▋       | 677/2473 [34:26<2:21:22,  4.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMiowFBVV95cUxQRDFRVlVWeW1yWnJNcWI1R2YySmdZVG5oVUV2M1Rkam5meHFPSGVKTmVjcTItM3ZwY1JFQVRGbXdEcThoS3FCQzdRSENEaW9zQzN5Z2wxOWJNNWVDOS1yb3o2dmpwb0dxcXNDNldiRmpSLXFHYjktMzBmRHJqZnpjYlFvNG55ekFBSmk4N1JDbkEwTXRMZ2ZYYUhIRlQ5a2ExTXZJ?oc=5
panjang artikel: 6062

Fetch isi artikel:  27%|██▋       | 678/2473 [34:30<2:20:09,  4.68s/it]

Fetching link: https://news.google.com/rss/articles/CBMibEFVX3lxTE9neFI1TkFkZE0yT19MeElfUWJjTDNodnE2Nk9Od2R5RzZWRjVEbVdVV1ctS25mTS1YRjFnaHFMaWxYLVNMbnl5U05XZzljNGFDR2xseE9vQW9iRVk4Q2FLd0VsbC0ybjNQczNqWA?oc=5
panjang artikel: 8883

Fetch isi artikel:  27%|██▋       | 679/2473 [34:36<2:27:50,  4.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMic0FVX3lxTE0ydjdic2taZ05GalVxT3hLZ2FHaU52RVNiOFhoRDFjeFJzVExBMGIwNkEwT2pOOWJZMVVUNy1GQjRmNU01UU93amhVaVFicF9pSkFtdnRsV3Vnd2V1bmJQYV9aRWZXSkUxMFJCWFpnd3NRa28?oc=5
panjang artikel: 11224

Fetch isi artikel:  27%|██▋       | 680/2473 [34:40<2:24:55,  4.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxNYkhDbWdLRHYwVjNBZDVpR1VGRjVRUWd5bFRXNjNwdUlrMi1uSGQ3SExEY0FBTUt3XzlXQjRwMUlyeWhlcDFTc09adGxSMWEzSnQzdS1PdzgyVTlkck5EWndLeTdxdmwtS1V2ZUNzb3M5OThhT29sQTdreXk4VzQtT3BzeHh4MllobW0xd0tUY0dhS25WOXpmdXByVVgtY3JNRDE2RHVMSmhvcDNKNGFZblRvNk9qSnBxOVVvWldJd0N6UdIBxwFBVV95cUxNQmY0WWYwVHlFQXFIbUdJNXNRT2xacE9wZU9lWVVxRjlqX29yYk1ZRjRjS2k1dUNHX1FzUF9EcFJYNzVXU3psZy1SVjdtYzcwT05tSFlyU2ZfRTlxVktNZGp1aHM2NGJnU2F3R1djR2EyYkoyT1lqZ2Y3VTZmcUJnZVB4a2Q4MW1nT3ZjYzFmZWM4RC1rR1A3WWF6VmhNR3dsTV9KUVQyYmFZQUdmYzE2bG8tT1RhQlBfY0NNMTlMaE1KcVRENHJj?oc=5
panjang artikel: 3211

Fetch isi artikel:  28%|██▊       | 681/2473 [34:45<2:21:47,  4.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1wFBVV95cUxObVpfTjhWU2tHOHhXOW1rU1BnVXM3dWZVNjFWQzhCcUxXbVZHcE9TMG00VDlYcHhNeGJpUG9YUDZDdXBHN0FUNWhFYk41MVpwNUtZZGRVU01qWERDRkFSWEgwSUZWN2RYUU5iZ3RRb2cxdXI3QnpDd1pPME9OeC15M3BnVkxiQXlKZk92VWx4Mm9KTG5tV2tTeHFBOXpxajJ0U0drb0doSVNEaHdMZjVzQlUtczY1LXdWWkduZVV2aERGd0FOYjJOUWVSc0s0cjNqUjNyUmZ5RdIBxAFBVV95cUxOcFpQRDBFRmVuUlBGRlMwM0FRVUlGMFU4ZGVwUzY3bHczOWpqb1c2MzI3Q0g1TlNhdkliVVVIYkNKTGdLbVV0OTM1M3R2RGlyX1ZRXzk4cHFvVXpBNmVsODA2azJVNWdMeWtFTXoxZ3hsY0FOdUhyaUFWaV9mT3Q5Rjg3UE9wSmZkNGkwY2tKS25pcEEzZGFWd2M5SnBwNU9lQURGb3BxRUxsUmlGRTFpUUo0NzlqZTZxMm5ubDdBUGN4ejEz?oc=5
panjang artikel: 1986

Fetch isi artikel:  28%|██▊       | 682/2473 [34:51<2:28:54,  4.99s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxOUWNIOUF0Rml3Tk5mRjJSdnlQMzd6clZ4UGRyVktIRXVIaWRWMzgwUGhkbFhFa0xGWk5GeXBwVFpBWjJsZnA4WGszVnp4X3JLOUJoQWZTdHFTTVB2R3UyWTFzWFQ4U0RpbjAtMDNiQW9TYS10V3cxekhRVVdZZWdReWI1a1pBTllEUDg5SGQ2WUdUWGlDSjJBSUpCd0xyLWNqSnRVZkE1ZmZKNVFtUFE?oc=5
panjang artikel: 5590

Fetch isi artikel:  28%|██▊       | 683/2473 [34:55<2:20:16,  4.70s/it]

Fetching link: https://news.google.com/rss/articles/CBMigAFBVV95cUxPSlBiTlVQVk1KbzFlNVBkVjFIenA5N0VDY29MWFJXTks5eWY5STJhR2tpS0xRSVNWNjYxQ1Bhc2p3LWxKeW9sMExxSlVsXzhrR1ZDdEViZ3dBZTJxYkdVOU5Nd3p3TDVITkVBc3dmOERTZWxsN0NKaFBobEF4eTlIWg?oc=5
panjang artikel: 7529

Fetch isi artikel:  28%|██▊       | 684/2473 [35:00<2:22:43,  4.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxNQVZBMjRQUUtoYXpHTEtSZXk2WFhucmp4UGZTYmpIZnVhaTBPY0RQYjBzQWp2M2dTNE41TWx0YWhJZkFTUGlCZjFBdUwycjVSX0NKUzhLcS12NTVHdkxZcE5xUkNwb0JrRzhrd3pOZlZzRi1OVURQdUJPYjdET0xpVnllSjVBS3laLUtoVHhsajdtNXAyejI5cWQtTDF2U2d6LV9CWU0tcFXSAa4BQVVfeXFMT0RTRFpCS0F3YmxKUXJHSHB1M1QzXzFmblhxdm5qeDJxcWhjem9PSWtLZm1TUXhtTjBvVEs0UWd0TDhSRUxyZ29TWmxOWlRrelBNOEpucC05TGNPNFVQRjJxZktnVzhGd1hIQlhiTjhMZjVLWkxseWhhVGhKbTV0OUNkYUZJUGN3Sng1dkt1VFkzYnBBSlVFLWczaDZBdGpadndCcG1uVVBhRG5JY3JB?oc=5
panjang artikel: 4284

Fetch isi artikel:  28%|██▊       | 685/2473 [35:04<2:19:07,  4.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxNZTFFc21MbFZkUzlQUC1Ka3o3V1hqb2pOSVdLZElfTVdENEI0dVdTMmJmbmNCSVFyU0pnRjhfV052SWhEcDVKM0tNTkZiaGh5WFJjb2lldWt6VGJVY3BVTmpKUFd5M1JJU3h4U1ZkdEQyQVU4Q0lNd3FzczVrd3RjeEZLUzBxYVFid3E2dGVmYkxhVTVLXzltSnU2RlhWY093TVVVV0FnSHBmQTZlLVI2VUl1SEVVOTZ5ZXc2Q1gwOFpISFXSAbMBQVVfeXFMTVRXYXotOFhVem5DSS1sMER3N0M2cUZQdHJLQ1BncWl0QlVXUHZvQTJBcHRSUEQzcUdXdXlRal9ZemhybnBRS3E0QlNfTko1SDVWbDlyQWhpaVhXQlhPTDVXUkNrSUlxQzE4R2VteTRWNndydjlLTkFxY2dwRjJFNUJ2d1BNYnp6ZXRjMzBzUm1TZVN1Um8yLTJ2XzRBYVljNEtaQ2NYUDhFOUlTcHM2QXp0Rk0?oc=5
panjang artikel: 4637

Fetch isi artikel:  28%|██▊       | 686/2473 [35:10<2:34:33,  5.19s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxOeEItbjMzVkZaZUt3cDRGU05xMTEtbEFZYTZtelhCX0xfSDhYc2tkTDk1Q21yY3RVTmwyZTJsQ25GX3RrZURBLVZXekRveEhqblhIWHBmMi1RbE94TFNReHQ0d0pzR01EYUMyLVdObmJZXzc0VkNZUG5GN1BqMmhVcG5OUzNxdS15X2t6SXFBM0twUjFVeExNVEpxRWxnUHBzQlc3anhaN2Q3UnJCbU5KbdIBtgFBVV95cUxOSlZQZ1cwUzFHcjZhSFRva3hVQmtEOGZpME5vYkxqd1d3RzRYMGRXMDQ1Z1ZBbnZtS2U1QjRXZXpwTjVKaFEzWW9UWVMtUjlLbFFKblZPT0NBTUV0MUN4YzYxX1BhTnZ6eV9HdGVtQlJqOFNLTWdZd0NjZVR1TjdrRk5YcHpkOXBFdGFUZmEwSmplSzhfRzNGemZ2ckRwUTRpUGlVRGk4dmRseG01ckZhcW1ZaDN4dw?oc=5
panjang artikel: 5215

Fetch isi artikel:  28%|██▊       | 687/2473 [35:15<2:25:35,  4.89s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxQSjZ3OFJwNDJHX2tpSFdCSGdBWXpCQTdyUkJ1XzBHMGVPclFSckdTVGJkLVNDdVlqSk9ld2J1bXVxMWZrSUhQdmhfeVdqeU8xbzBOdVdTcFFxa2oyVE9UbEFNU2IxNmxDb1c0RU5FdTNzUXM2cDBzTm9ZN0hETi0zdXJFeEI1NmxWRHRYUG5WWXE3TU1Bd19xa25mVGxKMzFyYzl6VlNCSzNNQmtKU21jV21LeTYzS3p0M1EzVWtkWV9vaktQakI00gHMAUFVX3lxTE92MjZ0OTg2VkFmSXpURlEyOGRzdVY2NWExeEM4N0YycFg4UkRyQy1ELUVvUXhLcXRnT0JsWHRCVkJUdnlRZ0VEdWdOWGlHcTdxUHpwRXJkVDhLQmhpZHhrN04xR1l6a0g4emM3QTlNSUdpb245R0k3UXJEZWZRZXBHRnRKbFF1dnpJaFo1M1JVMGg3RzdTaXR4c1doaWw0VWtqSm9kVXhScGpIVU1aakkzbkpGLUNCZjFNRTg1NkpGNHhua080VGk5QWpCag?oc=5
panjang artikel: 3516

Fetch isi artikel:  28%|██▊       | 688/2473 [35:19<2:21:42,  4.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMibEFVX3lxTE5jVmpXMW5UcnhPaVB3c2ZtZTBqS1lXNm9QT2FPOEVFcVVrRlpCTDFFQnFEMURtbmhBd3NpRXc3cW5keVdfVnVnYkRsSi0xZzV2Q3VaSWpqS3VPU0E4ZVZYeXpiNXJCQS04MEZGSg?oc=5
panjang artikel: 2685

Fetch isi artikel:  28%|██▊       | 689/2473 [35:23<2:17:51,  4.64s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3gFBVV95cUxNbGZfdkJyVzNsek1Zel9NYkF1Wm5telNuWG5HMzJfb3g4N1NOd2RUazhna2dsWk1iVEhJTkxHa09hOWRSUFRHVnRYRzhPRmxpVlRmYUNRbkZnVzlKaDl0SkktLXlDRVhGZ3h4X0g4R2VuNGNScGtVOTUxdVlVdHJpMllmQU85cEVEX2trLXJOVEZ5cDRTMDVtdlA1WVBQaHVpQ2lRU1otYnVrRTlNTU9iUzdTNTZRRWtaLXV3a2NoeVJxZ2lZcjlMZzhqVlJFSEdmYmFySGlKVHktRzlXbmfSAdMBQVVfeXFMUDY3XzFZMmJjOFZ3N01MZzlHeFpVME5wUmlaZm1qSkJ5MHNqbmhPNXMwNG1NdUdyaEdEajlGQW9HSXlQZVJvZ3lvcXVCYXBXNjlObEZzZ2p1eEtwdjJLR3hTcHM2WTFGSjRGUTBzN1BlcXZ6ekxWVU9PNEtoWGhFY1RNU0JEUExWS0VmVnBpRnNCUWRYeFJlcWljR0tqZzNrUFh2VE1IUk5CdGlFWGdTLXJ4VVpsVFRXNkJLdFpTd2J6c0lVT2IxU3hXVDloNFdQR2txaw?oc=5
panjang artikel: 5083

Fetch isi artikel:  28%|██▊       | 690/2473 [35:28<2:15:43,  4.57s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxQaTYzOEdWMHdRSC1QQXVad0NzU0NUNC1uNHZMUjVwcFRuNGhCWWNBQ2dsaFp0RjU2aFpLTUVBQW9wZmRyQTltVkUwUWhaZjlpbThlSGx3Z3FLcnlzVUg1dWExMy1LTnFoT0hHYjhCUXJ0eGFfekZGYWVSeTl2RkxKNVdhVW9mU28tTUtrQzNlYl82eW9SZ1hnc2Qwc2lLb0otbnJrTExsQ1V4TlNKWTZYRTU3RjRBUWtuOVdpVmN0OWhPSm5nUzZ2NVliV1lGMUtF?oc=5
panjang artikel: 4489

Fetch isi artikel:  28%|██▊       | 691/2473 [35:33<2:21:27,  4.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxQX05CdTZEYnJRQVp1aXlyckdRUEQtLUtlODBZZFZ6MkVvREU3SUtib2FkbTVFRzg1OXlLMTZPUkp4S2RyR3NhaGFUNEFuV0FwRlotUXpIMWdIVkh1V2hVSXVRTTBoOG1hVW5hR2tfWk1hbG5neEs4cUJxb1Q1cm5CUzJNTzh3aWNNdHdkYTBSMkdDNnNfOUNLTERQT2RJM2VqS2ZRWjdrZ1l5cjBOR0NBVzlWajF4VkZVWW5KakdMWndrcEZ1OXRFSkpB0gGvAUFVX3lxTE1XVkFfUFpYWDJScWVZV19Hb2pGTjZEVzVDOW1LZGkyRGlFdGdMM1BiYnY2ckZrSEk1OTBJVWhFMjdNbVVBdDJiLWdoaXl6UTNPdFdkUFdwbm91cEEwenZxME5SRmxTUkd3NEZjQWJrcE5KNHk3cXFQTzUtc0lhZnphQzNLc2M2b3cxcmNULW44OXBIMGxUSmNMVFEwTTE2SS1EWnEyT0JCNUlacTlITzQ?oc=5
panjang artikel: 2006

Fetch isi artikel:  28%|██▊       | 692/2473 [35:37<2:15:25,  4.56s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxQck1uTndlemZ1Z2ZWNkhTZ0ZWNVp6a0RORXQ5ODlRUEtjSXBteXhobzFQaUU3TkNobXY1b3JpVjl1OW51bnYwSnZuMUd2TGd3UkNnRWZUMGlaZHRCQ3o1a2g3cC1pamVZZWF5R0E2RVNhN3NGNXVac0Y3UFNGbUw4U3YyNnFJNWQ5Rzc0TkJBWGJqU1lTVFhseVJxOU1DcG41VUHSAacBQVVfeXFMTnJKNjdSNk9nemhtaFRVd1pJSU04MnRoYnRQX3NrSldTNUtTQm93Y2dWcDNjQjU4ZmNja1o2UmpvQ1hVVk5qREpmanYwLTJha3FXWVJPbFkzWl9DVWZIcDVpT1ZrcXJuM0UwcUNJa0g2MHhIeFZjcUlHMnBDX1Jja2RaODFZai1vR29qZWRQMFBPYVhYdzZ3cmNwM0lpVjRDSG5nZDhJLVU?oc=5
panjang artikel: 140

Fetch isi artikel:  28%|██▊       | 693/2473 [35:41<2:10:01,  4.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxNYWhxd21pcmt4dFR3YllUSEhhWlZsU1Q2S2Z0bE0xVEYtdWxLeldUQ1NzaWgwMzVKSVlNb1FzQ1Z1YlNPUC1zMzBSRXNlVkZJYm5FamNfSTI1VDNObngzMnpDTy1SclpJRzVyQ2JmTndWRWFESnNGSk5Edm80NEwtbC1FVnVMVU51d2dhdUFhTEdPajRDbGEzWWpR0gGfAUFVX3lxTE9RREFOS1hiZWc4Yy10cTl6a1JiT0pTUlJRVThXSzVwWFZuOWo4bGZvbzJnUURKRWFxSkJKd3JONWJUTHU0YThrVy1aOXFxYkpERmoxNWdFZTB1d3RhYkZUdVJIVkJHNC1ReDhHVlB3RWdUUUJZTzF2cnh5RXpnZndQb1dIcGUyQXJrbC1nRVpySWx6eExNV3I3XzIwZmxTaw?oc=5
panjang artikel: 146

Fetch isi artikel:  28%|██▊       | 694/2473 [35:45<2:09:53,  4.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMipgFBVV95cUxQQWF0U2FfWFNNeVNFSldSWEZub3g5UWJJTFYweE93OUJoWGVUbDBPYUczUjY4ckRnV2tqQy1OQ0NCbjZWSFktTF8yaTFfQTdlNWdjRThqZmowMUpXZXFnbUlCX09vM1p4ckdhdndPOXQ5N2ZWem0wUVZWNUV4QVFXcUcwSE9oUXZ0Q01WUmg2WW8xMnVMeVN6UEFkQ3JaQ0MxcWJkUUZn0gGrAUFVX3lxTFAtRjZFeUhQWlhkX3h5OWxTam0wV3RQUFJfQjZSdU9sM0ZzX0p3V19EQ0cxdzdrUkoxejZYRFRjTDJOMi1LQWdoVFpZY280ZXZ2Qm94YVhDWlJJOFlsTE43NVZtOExmU1ZnRTNJV2ZuQUduYVlBQ1J2U0JOd3dZbWhzclQ2WnF1QWtoaC1QS0M2cGJPazBhUGdlS1NMYXU3R3Z0dGN4a2VEeVpZaw?oc=5
panjang artikel: 145

Fetch isi artikel:  28%|██▊       | 695/2473 [35:50<2:09:31,  4.37s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxQNC0zQnRrMWZpY1ZtajdVdVZoMVVzb1VtbnRPcXprUnR5QkgxWmVWTWRJcjVVbmZYY2JIZkU4U05XSUd4QmxyajE5MjBGaGlDWFpmOC0xREtSRFlvM2tOT21aRTNoMjdpamNOUmpPRkJiTjZFUE1mWE9BLV9jeVJTaUQ2cTZ6UVczQzhRS200T3BGVVpTMGZraWZLV185TEthaUlLTlVwVkNpR0Rrd0JmRkIyM0xkalBzckptRGVhRlliLWpEcUZGMVR30gHPAUFVX3lxTE1aOEVpRmcxOHJBNDJ6Rk81U0hKaGtYeUxpN09uN0RKS0NSUmtKblFtb0l4cXR2MlVVb1NMSDZ5R1pSUXdKaENacHpsci1nQXZtdVRQdnYySFJBOGNmanVEM29uNnVwRzJvM3ZJSXR6MGpDM3FqY0tTdERkamJHeFp2Nk9SQzNSYzl2YXQxZFJEcGV2ajRNVTJxdEZmOUg0QXY0am03TU84SUNzeERXZ2RrT0RURVMyeUw5LWFOQzdRUG54WmtSNHlyWkdyUDhMaw?oc=5
panjang artikel: 2716

Fetch isi artikel:  28%|██▊       | 696/2473 [35:54<2:07:03,  4.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxONURlajZtc0VXVGJmNlllWEF5QktRWjZDNWlEZXlCLWtaSXRhU2J3MHNzX1psYWJsTGZZcFpMSTZQYXVsTGZCbGM4MjJSZ0xMQjNHSTZOb0ZmakExa0hTdXBhWWdYSG5tU1ByVHJTRlc1ai1QdWRQVHAxVEdJYmNDbURVMVRSbktqR0tpQnB0bEdJX0tIZlJDam1ZcnFqSDlHZDBjYWh4WnJYcWpzWlhESVhPcHhwVGFBdEZGZTBnY9IBxAFBVV95cUxPZ3p6UGgxM09mbDJ5amNpa1g1X1M2YU5qTk5PNVV4YzFtSS1xNDBZVGprU0ZzUHpJZjhacVpUWGhIRlM3aGRBY256dlpRczJ5RGtfYVlxellFNlR0MnduMnNndGtLR3d5eXVmcDJ3eTUtVGFtSFNLOEx5OG9XLVo5X2lnSER4MGQ1UkhzVG1qeDVKSndGaGRMN1ctWnhyRk1KX0NnMFJvXzB4YWdwX3FYcVRNMjBjRFd2dVBGRGFhd2tOejFz?oc=5
panjang artikel: 145

Fetch isi artikel:  28%|██▊       | 697/2473 [35:58<2:06:01,  4.26s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxQdllndzV1WXlIaW5nX28wMmp5T0dpTUpaME9fUERWUTRSeVVPQWFjZVZtd2tibVg2ZkRIbVZfN3dOdHlscjRuZlZtdzV1cWkzQlNZeE5mSU1qNGlBQnl1OGVDUFBFMG9qSzhoU3hWWW9rT3hSWERyU3BVc2xPWkRMaVNFeDJjcjJIaTJtTDE5bm82em9GVG8zOTJDVXF4NUtMaFpvVUZFa0hZUXfSAbABQVVfeXFMUHc2aWphS1BoLWJ3cGo1RkVxWVJTVHRZZ2JFdjdKRW04NGZZWDVORFFwZ0liZ29nRkpIVnJTemZSVmVBQ0p3OGRRVnRhSmlhd1JhRTFNLXlxNGkxeTN5QXhZSG1BS3F2d2h6TVF4eEpyMmZ4ZzdlYlpnTERHekJ2TTYzTF9VQ3hRSjYxTWQ3dmtOOFFYZkZrQXhOUGZnc1g5aXBPbDFjNjNBZEp4RThQOFY?oc=5
panjang artikel: 2678

Fetch isi artikel:  28%|██▊       | 698/2473 [36:02<2:03:55,  4.19s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxPN0ktVTJaaHg1a0RhWXZhbjZoNERoaW01UmdMVnBXU0ROUEtLQU12THRWRm90aXk0XzNkYkpOUGJoU2UzREtvNzNNZGsxQnlaSktBRUlycXR1Yl9UZkRYQ25nYkRzeTJ5Q0tSWHRIY0dtZ1Y3ZllfbzdGYUVvRklnQWlqNzl6bnJBNmNyZmk4ZEZLLVZYR2pobldKOTVULU9rR3d4a0ZoOUwzX0FuYkl4RTFqUk54Vy15ZXFkc2hTOEJhd19H?oc=5
panjang artikel: 2674

Fetch isi artikel:  28%|██▊       | 699/2473 [36:06<2:03:25,  4.17s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxNcENrZzBsV05lVFBIZGtkM2IyRjJXcF9qN1hTOFhxRmc0RTJzeVhkWjBOaEU4S3R6NGt2akxicHdGNVhNX1lXSXhLV3VrMlRwMGJ4UFg3SndNb1l6RnpObGdWdWUyVV9iRFpsUDNzWG5nNVpDVHB5cmJETkpGTm94aXlsZUU1cGZWZHpWazNKU05fYTFLNEs5NjdsR0xpMjV6MkgyQkhuNzZBMW5lQjRZV2UyWUNlRDdoSTRUb1YzQ0RmZjZxUXJEVXRYVm5LZms?oc=5
panjang artikel: 3804

Fetch isi artikel:  28%|██▊       | 700/2473 [36:11<2:09:55,  4.40s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxPbXpkZjJBZnpBbWN0ODJ5MTZQd0FTa2Z4by1rb2o3R0k1dUxMUkYxRWxGcUpPcjctX1VMUTJoX1NSWHBtallfdFZObEJTSlNRc3RLVmZTdS0tZG5IUTRhVlVCNEpXNWFFbk4tNWtKR29Zb1R4STFINXhiQ3JDZ01UdVJ2MlZ4ZFJiTklSZm9HNlBFTXhxakoyQ2k2ZEttaFdZb1JDN2lPWFltYTFCMVNFallyY2U4ZTIzWDNiTHZLN2ZhdzhtRTVLdHBKWXBvQQ?oc=5
panjang artikel: 3542

Fetch isi artikel:  28%|██▊       | 701/2473 [36:16<2:14:54,  4.57s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0gFBVV95cUxPZkxVWFFwd3J0d093MEt3aXVNSjR1cjB4OWRwY2Q2N2wzRGhkb1JHbUg0ZTRnMzVEbzZFZVNtWFBwVGo4cVQ3YVZDYUdCWFRrWjlPMHVzdTJyTVc4TWc1clZDQ3NTM1pPODRwWndCbzN3YXJ2MGY3TXZCVS0zQzRaeGw3RDFGYlh1Y1pyOFNBckgzTjBDSmpqa0R6MzhLMENJTndlU3pHNVJRbk0yc2JiX3BwRUxSbjdmOU80MHNWelBGaUppUnBrOFJUZzROT01pb0E?oc=5
panjang artikel: 5196

Fetch isi artikel:  28%|██▊       | 702/2473 [36:21<2:19:19,  4.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxNcFItTWE0MVNVa25KM2NSWEZEY1YwQTdWMVViMVFzVlZaUTgzaDZZNUdaTk1VQlNjWXQ4TEc0OTdSazhiYmFwQm5IOHBjUncyVVNuVVJqRU5BUDZnMzhRMzNGQkJuSzU4SU1DdXp4ZlJHajI0Um91SGFhbFppQ3luRW1fMDRkdDh5V2tzWHV6MklxYWw0RGJQTlNJMkZyUjVxT3ZzelhKZGxIaVBYWVl3SHRjQ1R1SVN4VDZYb3NR?oc=5
panjang artikel: 4175

Fetch isi artikel:  28%|██▊       | 703/2473 [36:26<2:18:42,  4.70s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxONGV5SVRJWVNGcE5ydDlhWVhnLW1IXzJtenJJeldZR0tUQ3JEZ0JKTm9tZnlhQ09JNVF5cEdIak5BRFg2WkN4OHhpQ2hQSmNkaVhSRExhVVBPYjA1LUdZaDNMalljMzVtRVBwYUtTNHRZdlp3Q3doaDUyUG92UmlBVEtSczVOdTh4S0R2VEJIMUVERTk0eGVMRTVGZVRjZmxRZzV2NQ?oc=5
panjang artikel: 3500

Fetch isi artikel:  28%|██▊       | 704/2473 [36:32<2:32:26,  5.17s/it]

Fetching link: https://news.google.com/rss/articles/CBMi5AFBVV95cUxPUWZ6Zm45cjd6MFBBZENuMWpxMGhPSkRJR1ZQNHQxVGlUbXUxMUVLallwS0VycWlKSFJQaDlBLUlMWjJoOFg3SFFmeDF3cXRPa2ZBUmJnd2IyX21VUENWckFwSUdJU2dFUEI1d210QVppcmloYjhaY2dnMWdxejlSRjdNNE1hSnl1Qnh3X0xOdy1HVmhhYm1UZnNBcEFjMmVZNTZmekhJcUNiV3hMd1ZlX1NoNDdmcHVPbWNoVi1oMzJUUWloY2Yta2QzSkRoZV9rQVBBRDZScWNRYlR3UkdJNFhpeHo?oc=5
panjang artikel: 3062

Fetch isi artikel:  29%|██▊       | 705/2473 [36:37<2:30:47,  5.12s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxPelk3MFUwUzV3SXhIRDdNaG05bEhNV0d0eWJSc2JranJoTlg4ak5wdHlUU0hFUzkyalZuNUhha3NQc05KVTQ0RHdmZnhQcVFQZzFNa3dRazRtY09XVHpKRnBTY1NKUm9ldXhBMk5KN3F3NExBejNCVi02UkRfWVBiSEtVWF9KRXJ0alNGTkRxeTJJeGtSNDh2V1R3WXRxZldwZUFOdA?oc=5
panjang artikel: 4499

Fetch isi artikel:  29%|██▊       | 706/2473 [36:42<2:27:02,  4.99s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxOcFZMQzVYcWRVYUdubENQaDAyRDFMVUtGTUJvdHRXb1owWXplZ0JqdFZZSHh5UE4wM05zbFJjWHVSUk5qZWZqQnRzcXJPQXBrcVBpNjQwdFZJa2s1VWhtT19wVEh1SFluLURjT2xIVDBoV3RCLU5id3owS2FqN2VmcWRpSElzRWtXbk0xcGJ4RVItamxHWTJjakdBMGJzNmhTallSaU51cGR2UG5tRFlpTFUyNFJ3RGVTWnpYWGdXUWtpZkMwZlVIZkZBU010V0k?oc=5
panjang artikel: 0

Fetch isi artikel:  29%|██▊       | 707/2473 [36:46<2:17:22,  4.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMiywFBVV95cUxQV1hobDlpUGY3MFlzN0N6VHlsdXVNU25BOUlvX1hnNG1hbEh0YVhRNTBya0wzcFNYdnZKSlpUM1FUX2ZvaTJWSE1NMTdSbW9WS2RyMGxHbFFmbEhlRWdCNUpkQmR2U1RKNjNSdmFOQjFtQ3dmbFZwN0tRRGRtRkxSV1lRd0Z4UHFibUNzcVFJMll2UW5qTVpGX2JsSC1lUzk5OFpRWW9kUlBSakp6VWJNWEtGcUx3NG12Zy1wV3lqUTBWd2dyQ2Zoc1F3ONIB0AFBVV95cUxPdWFpQ21KTk9ydUl4THVheWxDSk85b3FJUDZoenh6b0htUlZneDJ5MEFUTEJyT3lkdmtGQ0lmTmROU2I5b2c2UnpqaHRwZjRuY3dOU3JxZHBESzAtcFM3cnRnQVpXLUZocms4TFlXeFZWZEYyVmdsZ0xXMU45WnVVZTBpMEZOZkQxWVRvTjVoZ0RVTEdzaGo1N0tzSXRiVnhlSDFCQkN2VzMxb0EzVW9kQzFqRHVEczB2dXppN3ZCZE9rb2JKWmlPOTZsUGduZkhI?oc=5
panjang artikel: 2067

Fetch isi artikel:  29%|██▊       | 708/2473 [36:50<2:10:07,  4.42s/it]

Fetching link: https://news.google.com/rss/articles/CBMijgFBVV95cUxNOG82UDlVZmtoVVE3TDZzT29rQjBNcV9STWhsSzZURGJTVzNvaVF0M1NIX0REdVlaZ1VyMDJWQzZscUFLY0tNZG9oc1U1cmwtUDBfUEtSY0NydFN5NmpJVWVpd0pWd05GVGpVZkhnNE1zbWNQMFU1ZXpLTC1PMmo4UkZvTV9fdXZIZXkyNEN3?oc=5
panjang artikel: 500

Fetch isi artikel:  29%|██▊       | 709/2473 [36:54<2:07:12,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMibEFVX3lxTE9XallaOV9hSU84eE9Qa0REakZ0bzVmMmJEM1o3NlVYWThwSUwwRGxoeDhzbFQtcUhjZnhGQUVRbVlTZDJSUUJxX2ZlR2Q5RXZwV2ZVUXRWc0hHY3Vod3Q2TkxYTlNiQUtjMmNnVA?oc=5
panjang artikel: 11160

Fetch isi artikel:  29%|██▊       | 710/2473 [36:58<2:10:40,  4.45s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxNaW1Hamt1SW01dllnRXhEeEhsYmw2Um1qb3B6MW04U0cwbjVHTFFXVnJlSWQ0aEd5b1kzUmtnSUVTQzdmbkRJWE5sUlg2VG9JWEswcTdCbTV5azh1b2pnWmZYeTRuTjNpRF95N19BLXI3Uko2RDAtSks2WEtXdngtWVMyd0RrQUdwZklRT3Z4NlhLVVBpZGRLSmxxei1kQ1ljTjBrdXZxc2o?oc=5
panjang artikel: 2662

Fetch isi artikel:  29%|██▉       | 711/2473 [37:05<2:32:54,  5.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxOQW9zMDZxb2ZvSkptMkhaZjFUM0ZmajVYRVdvOV9PM3ZJR0pMNVRlLWNpeVJZYm83aTVjRzk4NUQ2SHFJc0gzR2Y0Si1DVmdEMnRoX0pmejlUcExrcmlQZGlxV3FLcHRySjEwSTVrWmk4WVJJbjVWWm1zbEsxdmplNTJRdGtnNW1haktjX1hvU2gzZGozSUVBT0F6QlotQzNBTF9nbHUtbV9wVVZIdzhCNUNDaUYybHFhaGczM2RzVEx4UQ?oc=5
panjang artikel: 2632

Fetch isi artikel:  29%|██▉       | 712/2473 [37:12<2:45:22,  5.63s/it]

Fetching link: https://news.google.com/rss/articles/CBMizAFBVV95cUxOTVpaOE0xWkRXQkVnMUFZX2h4eGhnQTBoS2c0UEJKM3l1Rm05Y0RjN3VGNGNhWldWbVdWU1RUdTlpMlFneE9ONlgwYTZmRnhXbzZONU1OVlF4dHY3M29xakpmeDhxT0ttYUJnR0xQUGl5Zl8zVWVhem9LajhFNFloNlBHeUhyaFJwUnZER2tLSm9sWUxCSlA5Zmpwd1VrTjFUUHVtSm85ZWZMdFM0cWdLRUNxYjg2T2dhNjJGcWJ5dkl2aHk3M0ZfMnpuV3c?oc=5
panjang artikel: 3019

Fetch isi artikel:  29%|██▉       | 713/2473 [37:21<3:12:38,  6.57s/it]

Fetching link: https://news.google.com/rss/articles/CBMiiAFBVV95cUxQUlVCLUpzMWdFZjZpaElmazNPdGhsc292TWxoa1VqSGtHdkE3SHVPRmtZS1FBN3hnLU1iUXF2Mlh6V3BtNW9WODRaZWVDMFkxMDZUbV92U0Y1ZFFKaUtCdHhRWnRzUEFOSExtNnduQklwbWw1Wm4yM0FyTzNnTnBRbGpjM3QySTN5?oc=5
panjang artikel: 1845

Fetch isi artikel:  29%|██▉       | 714/2473 [37:26<3:01:14,  6.18s/it]

Fetching link: https://news.google.com/rss/articles/CBMilgFBVV95cUxPaGxBV0lBTEN3SmYtUWlFa1p5UVhTUUJoWEJrbTJMM3hVRHhTWVhRcHhBWHZ1eC1QODR4RVptNWozejVFbGNlWW5wYlR1UVk1YnFkQ3V6M2RGMjdwa3ZLMzhwMWNuNDVMaUhDMzRaOE1nNERuSDBQelBKSHlNLWRvc2ZwNG9KZ19scmpCSTZzVlFYb203eEE?oc=5
panjang artikel: 2365

Fetch isi artikel:  29%|██▉       | 715/2473 [37:32<3:00:44,  6.17s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQcWxPcDQyd3YzZjJ5TkItbXlpT3hSRUZ4b25CTl9qbkNscDJyZ2YxeTVJSFJwMUlyTUprU2duSkxUdE1PUnJJSEltSGczQjFqWTdqc05lUkk4dnhqVzZib3BQY0VJUXBKcnp5UGl4WWxtUVdBUU1SRkxqcm5rMlRoeE5xWFdOMWc5WlZUeE42TENpSFVpai1ZX29vOVJTalNsMG9UUTV0OGZEakVDZFh2M0UwSkPSAboBQVVfeXFMUF9tbkItVTQxWUJPT2hyQVRKeDZYYV9PLXVNQWhqR2VYUjcxYzNiT1VHenJWaUxXWnI3VkFScGxYMXhSTTdRYWR0bUNjS0RqQ3JndWdHVlV1NVUtSWpSQzM0RkFyUjg5S0U1QXRjUUJ5MnVOelotTWkxVVc2M1owdTM2RGpYb0hUVTBEZVpaVnRoU2REZVBoR2d0Q2ZxRlRFQjJBRUVhV3BXMmc2QzVMeE5xSzVZLU9GQnVn?oc=5
panjang artikel: 4469

Fetch isi artikel:  29%|██▉       | 716/2473 [37:36<2:41:40,  5.52s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxNVnkxX2NDWGJybVI4SWZwVGNCTVJweUdGb255T0tLeEpPYmNtdzNsbWV6OHk4Y0dmeVNfUll3Y1o5UkpzUGZ2VExic2RlNzBibkI3Y0VDbjc0S2FxQk5WM3l6S3hxSVNpM3NvWnBhNFNfOUxZb3ZNTk4zUk1tWTVfU24yU29aYWlPVXROcy1NaXdkc1VCeG1JUlhVR3djc0lZb2E4TmpyMmNjZw?oc=5
panjang artikel: 2365

Fetch isi artikel:  29%|██▉       | 717/2473 [37:45<3:10:57,  6.53s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxNWldHZmZpZWcyNk9HcjdxV3h6OG9zRXRscHVfMGc3Vm5pZEJ6cHIweF9qMHNEVlVPX2p5WGVKR0RYRDJJTXJXN1Mzc1BBRDdtZThJcFNIT2NoemlrNTNBaDR1RUNRVkVqVGdQVWUxZDgxQ0s2bEJVRFdPWHA3SmdGUHBFdDRRb0dQQmxRbkxpMDdEQWJrNTZLS2ZvUFFzMXJzXzFQYWJ6REpFb01abk9Z?oc=5
panjang artikel: 0

Fetch isi artikel:  29%|██▉       | 718/2473 [37:52<3:13:43,  6.62s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0wFBVV95cUxORDNUZVlwWEwxN2o5enMzN3FIRDVucFFmRU8xb2M2WWYtMmx2TzBLRDNic08zbTNmcktMR2NRZzAwU0N1WWswbDY5dkg0cHNDRFNCYl8yOHJBLXdZVVY5alZvR1hFdTloQXM1c0dXQThGazBQUXRSanFac2ltSjRiZER2dUxEYlVOZXphSEh3YXNzbWxIeUZKRnNNZFJwbGFoTE0xQVlOYzJ2UmFWYTNjdWkxTFFicHNvSFkyeHJfTjU1OTVkQ3N4V2lLNkZRcE13OTBz?oc=5
panjang artikel: 4582

Fetch isi artikel:  29%|██▉       | 719/2473 [37:56<2:53:13,  5.93s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxPdURaMXZYWjhBMExraThKRWZzVVZhN1hyUjFJVFFjZ19wMU1QVVlUdjR3MG9Wc0RIWHJaZWotUGJNcVNuVks4Z1RkZzRXN19jSFJhZ1p2dWV4U1VsNF9UYmtjN0NMb20wVlB6M3dZM1BwbzRBMWZRSEdYRlFCVE1YTE51TThRMldueUV3RDhkeW96ZkhYNFNWc2NRcl9tUnhqLTIyaUR6em9xNFcxY0Mydl93dFRZaUdKMHc?oc=5
panjang artikel: 2198

Fetch isi artikel:  29%|██▉       | 720/2473 [38:00<2:38:04,  5.41s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxQSXE2eDhDSmRWTVF2b3ZGbS11VC1IVElSaXR1QlI2WENRMHY1SzVuQUFsVHhvVXZ1X013TVo5Y1N0R1VadElNQXJJMzE1TUxTM2YweG4td2tMYkhwZkVSM3EzWGRZR0NPMDA3ZmsxUE9QRHZEdGJFd1U5dG9xS3psbVpOcF93VG5IOFFjdW5BLWRHSldfak1OVWlncXljZjczY0xnXzFUTWJjUdIBrwFBVV95cUxOaDVSU05ISlBwcWFRRC1XQ09CYy1ESGx1U3VBVzNrNzF6d3ctU0x0MXh6SXRzb1QyNWtTeWlKanhCeXRCU2FLbVZPdDQ3UERsQlFJUVlMei1LSnpDRzlRczFEaHoya0hvd0RYX0l0ejYycGpwQmpuTEFuSFl1V1d0WlpoX1FMWkZkTVZRNGF5V2l3QWNzbzZ0bGF5NG80UENNVDYyTWdVdHlnTlBUR2xr?oc=5
panjang artikel: 0

Fetch isi artikel:  29%|██▉       | 721/2473 [38:08<2:59:52,  6.16s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxPcUxTWGY2TDNVM0JDMm41SFc5OEFGTTdXUEItNTQydUZrUXB3VGNRdTkzYjBwT3M1dHBWWUlyYnZIRmRCdklvbHNvQ3BpcE9DS0dSN2NENGI3TU5sUWhBTzhCNWVYSjhmUU9Ec0pqNFNHQjBZTHNvX0tzZjkyYkhma196dVBsNm9wa0FLa2I0QTd2cnpjODRfREJ5OXVnc0s1ZnprblZ1TUVJUmRVcDRicy1XMlZtU0RSa3ZrU0pVSQ?oc=5
panjang artikel: 2574

Fetch isi artikel:  29%|██▉       | 722/2473 [38:13<2:46:43,  5.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMi6wFBVV95cUxPZ2prc1VxSi15TXVsN2VQc2VLTFhZcGhWSl8zZDhhTDUwZGhyMXN3TkE1MU5vcE84ZFBZaXNmN1JFdHJ6TURPN3NWR2wyNTFJdEMtM2Y2VUs5UlJOV3J4Y3MzXzJKY0hXbF92dFdFNl8xVUF2c2RpNW95VHlFSHNKMnZveDd2OHNPb1pIclI1UG92VDVWX3pZOVZhUFhiYUw3eF9YNkNjUGtIbVJqdlY5RGYwMnZiUDQyMXczdUFDcnJ3WW5pWUNZdlpNdFFER1BGV05SckloZXF3cVlubXlkWHVTSVc1SWEtQlJj0gHwAUFVX3lxTE9MbEhoYU0zd1hwdUphRDA2VXN5OTF4c3Z5QTJkVEhUQ21lRnZiVWh2ajBpT2lIM1lMOXEyXzc0REI1YlZyQnA2WkFndmdtYlUydk1FcWxjQVdEVjZuUDhpakUyZUpFd21CcHlvSGJjamJTcUI3dzVadHBhX2lkbkg5eTJpOTIyVlpKZUNxekJMVFFtcDhWQ0RWSUtUeTdTaFZJVXJhQXR4Wjl0cHMyUUh2Vl9QbVh3dzhRVVZrMjJGSDU2YTB1UmNLSnlLREExWkR6OUdESFFZeWRYa1ctZHNrTmxlenA5ZWZHNHJVUHF0cg?oc=5
panjang artikel: 1807

Fetch isi artikel:  29%|██▉       | 723/2473 [38:18<2:36:39,  5.37s/it]

Fetching link: https://news.google.com/rss/articles/CBMiiwFBVV95cUxOMDVvNFFnUW13MjFjbVlGVzJ3X1dwUEFwS3hWc05ReHE4bzVvTXlwa1pFWFR5c1h2bFhQc3h3X1NRZTVxQU1YZU0ybnIwdjBiQlBIdWJrbENKVnBhU0UxX21yVnhvT3FfSGtoa2VGQnJSaGtnc1gzNDdqSVM4bjZLV1RQQlZJcTMxQlB3?oc=5
panjang artikel: 3438

Fetch isi artikel:  29%|██▉       | 724/2473 [38:22<2:27:16,  5.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxPVWhJX0V1Z25mYjdZczd3Tk5PbWRwRUNxbUpQc0lqemQzLUJqYXM5eHhvQmpLMWFXQUdCMURBVlZiMkdQemxFWmJ1bTJFRV91NFlzVy11RFQ3OWdObGtDMzJNMTdGaEtYekNVZEMtYVJQU2V5anE3TWhTZkVJc0JEMEc4T0xLMGF6NFNDdkJmbmNqWExlVVdkVlJfcGVqUGZXOTZCSm9KNVg1VWVRaDVVM25ocUVKb01zcTF1Z00zbzM1VTljX1RvbUxQSXVMM0VE0gHWAUFVX3lxTE14bHZyRU5OaGJuQ0hWQ3Y3RGNaSzIwUmhTRkFpSThuRTFIaTh4TmhOdXBSZFFnU210Tkt5LUZ1R25oMXhKbmc3eVFMTWI0WG9pczMxWjB2Mk56TkxaNGNuWFdKZWxfTU5sODlOc3VmZElyV1BJRUpMU2YwZFpTNkNFZkRQeHJZQTN2NzRJeHp2SndGZTFFbGxtSVgzaEdyMEg1ZWx2R044Yzg1LVAyMmFXOVNYMVkzczJOc0FxdmtHV3psSkMwa0hKcnNMc0hUSEp1a1RMY2c?oc=5
panjang artikel: 2276

Fetch isi artikel:  29%|██▉       | 725/2473 [38:26<2:21:40,  4.86s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxQbWc4U1drS0xFNTc0dkhScFpxUElRSUpZdWd4UXJKNXQ3am1iYVBBNzlTb05uVW85WDR5eC1pb3MxNGxwdEREd3l0RGhaSDRXVVVMTHZOd1MzZjl6SkFmOFZodkx1Rzh6ZTFYdUcwRUJVaGFEcF8zdW5DeVU1SktGZ29wbjhmOHVNT3g3cEJSNmliZXZmb0U3NnVZZHRfRXJzNEdvbkdtcFlSeUx1emfSAbMBQVVfeXFMUDR6bG4zYk1rclYyMDRhZkJ5a3NSdktOVGZUMGR4ZUxUVHVLeGd6b3FfR3BndjZZZjRLZ0tqY1dTMzg0eVpqcEt2M2cxNE1vNnVfN2xaOHI5dm15NlBkcjNZS3NvQkhMdXBrNk5pdmNqSHZHUk9NUm4tanB5b2xNcUpDYTJoMDNqSXZaRHc2ZGxNcEl0b1A1SlpBT3Y2T2Ita1hkQk9Eakx1S05pVF9OZHpWdGc?oc=5
panjang artikel: 3576

Fetch isi artikel:  29%|██▉       | 726/2473 [38:30<2:08:33,  4.42s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxNY0FJMnF6OEtEZGtKZER3WW4zRU5TVktURmVxNVQyU0NJb1oyRHlpOG9PVktLTUh2Z1FjUDZPdmFTYjNWUFh5WXM1TUVOa3lDMFE5ckEtNkFvbnA3akpWU1MzU3VOTXpQMDVoMmxsWTlNMDFTVVQzbEQ2bmpCdkc3VjZvOS1NdmNVWGtKaTVFeHJ1MDNobVZzZ2p2bE9VVFhMRGZkVkU4aHNOOGRGLWJLdmRyQ2h1TlnSAbwBQVVfeXFMTy00RWJ3a3l4eGtIaWh4YnA1N0Z3TE9rRW1WcGxueHBYd1R4dWFlWEViTXNMWkc2NDJmSUwyZ0YxczJPcy1WY1pfdnpqNlVTX0N1Tk9yR0xYQzJ6Y3BIWERTcVFVTkw2ckM2MEpqVFNfV1N6cFVWV0o2SXRIc0hBOGlVbWV3TGFDTlZycnhRYS1mTUE2US1mSUtIenFJeDQ4UEFkSHFmU1lHVWxVUDZSbkh2akttUDdZbGt5RkE?oc=5
panjang artikel: 1359

Fetch isi artikel:  29%|██▉       | 727/2473 [38:34<2:04:43,  4.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxNUlk4YkhkZTJjMlZzd1ZLU3VOalQ1aG5OUVFhZnZIcXpTZHlQMkRaZU1xWE9vd1BNd3p4RVc0Y0FxeTRZRlhuaXg4SmVMOTREbjNESDgwdnZXRGJNZVc5MjV0SlJDdVptcktDcFBfZTR0a2xEUVQ3T3ZGeTNBWFlNdWcyZC16Q1VkLS1kc1JwdGV2X2szN2R4U1hrZ0hDakJyRDY1aWJjaXM5dw?oc=5
panjang artikel: 3151

Fetch isi artikel:  29%|██▉       | 728/2473 [38:40<2:22:13,  4.89s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxQRkVfakdwUjlkdzBjOUpXdXBNV2tZQTdub0ZGWnRpbXBqLXdzaG1CNF9ObXpZOGRWXzZSSUd6YUI5SVhiMEJLUHlSbnFJV2g5V3Vwck0wN2E0ZmlyXzRNZDA1b3hzTmVlU0RJTElLa1doc2tQejFVNFZoOXR6MzRCamd2YTZIRGJMSVZzWTFUYW1LV1RCUjRSQUtR?oc=5
panjang artikel: 5230

Fetch isi artikel:  29%|██▉       | 729/2473 [38:44<2:12:39,  4.56s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxQc1NTTlhZU05WVndLZTdFQTRKVFJZRjJDdWdZVnpwNGVWa2RFSEZtWlVOSFQwMlB4clJaT093VWp5UWd1Q1E5NEw1VEVDa2l3UzJoZlhDZUpFMDM5OWN0aWhFbmc1TWhEbFVPZlY2Tk85bjV2LTBQQW5CTlg2dXJCVVZsdTlVUTlhdEFqOEp3RGFRRXFlM1lEQXpwbVBxV0EzYVNfUzBxcnk5TktjNWJnMWpR0gG3AUFVX3lxTE96ajM1akd2TzBzWDZ0SURMaGFDRjBpMUlkLU9NdTAtRmppdEMwYzA3RERzM1dMNEhCN3ZyR0VYZ3N5SzFidHQ2aTRmQlZlSTZpQkZJWEZWX2dJUDRoYXJKZVVvS19OenN0dXFjV3BZNFNaUmcwckIxYkcyVldfdWZEa1VsQ1V6RTZNVXdvdXFYbXhlanc1TFJUM3hOY2FVTk9XcURfYXM1aTJhN0tuaHpFTkUyY1FvVQ?oc=5
panjang artikel: 1977

Fetch isi artikel:  30%|██▉       | 730/2473 [38:48<2:11:51,  4.54s/it]

Fetching link: https://news.google.com/rss/articles/CBMipgFBVV95cUxPZWMtT0pzQnlzNEdKVFRIbF9uN3Q1YnJZTGg4Mnh1bVdubXBGZDJBSUZ4YTZuc2RXejhheEVrNzJxM1RrcVBtQWYzdnFGNTRFaElmak1Bc3BPVkZCeUpNbHAtdGlDa3BOY3NqU1JmWEZYYmg1a3ZTVXBlbnFQU21fYnRlNVJvaC1wemZsNUg4STU0dEdGNUY3aUx0S05wWVMxdzk5Wldn0gGrAUFVX3lxTE42ZFJfMEFmbm9td1dGU01TVkpmQjdFc0p3TEI2QjVTUzltNHI0OHIxcThkNWt1MkN6ZEJBWjl2WU9US3E1eVJ2eGwtY3FMdEpmREx2ejdJYWg2MUhBSXhOSEhRaF9Rcm1hcHFfZ21wZEpnQS1YUUs2SDBXQXhfWkxnS2FHaHRiZkQ0SG5wb2x6RGdJbG1SdG1FVWZ5bkNyS3ZEY183YnVVZGFpcw?oc=5

Fetch isi artikel:  30%|██▉       | 730/2473 [38:50<1:32:45,  3.19s/it]

KeyboardInterrupt:

In [10]:
df_news.to_csv("df_news_extended_250_503.csv", index=False)

In [ ]:
def resolve_and_fetch(url: str, timeout: tuple[int, int] = (5, 15)):
    """Decode URL Google News lalu ambil HTML halaman artikel sumber."""
    source_url = url
    if "news.google.com" in url:
        try:
            decoded = gnewsdecoder(url, interval=1, timeout=10)
            if decoded.get("success") and decoded.get("decoded_url"):
                source_url = decoded["decoded_url"]
        except Exception:
            pass

    try:
        resp = requests.get(source_url, headers=HEADERS, timeout=timeout, allow_redirects=True)
        resp.raise_for_status()
        return resp.url, resp.text
    except requests.RequestException:
        return None, None


def extract_article_text(html: str) -> str:
    """Ambil isi artikel dari JSON-LD, meta description, paragraf, atau body HTML."""
    if not html:
        return ""
    soup = BeautifulSoup(html, "lxml")

    # Banyak situs berita menyimpan isi artikel di JSON-LD, bukan tag p.
    for script in soup.find_all("script", type="application/ld+json"):
        try:
            payload = json.loads(script.string or script.get_text())
        except (TypeError, json.JSONDecodeError):
            continue
        candidates = payload if isinstance(payload, list) else [payload]
        for item in candidates:
            if isinstance(item, dict) and isinstance(item.get("articleBody"), str):
                article_body = re.sub(r"\s+", " ", item["articleBody"]).strip()
                if len(article_body) >= 100:
                    return article_body

    meta = soup.find("meta", attrs={"name": "description"}) or soup.find(
        "meta", attrs={"property": "og:description"}
    )
    meta_text = meta.get("content", "").strip() if meta else ""

    for tag in soup(["script", "style", "nav", "footer", "header", "aside", "noscript"]):
        tag.decompose()
    paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]
    paragraphs = [p for p in paragraphs if len(p) >= 20]
    paragraph_text = " ".join(paragraphs)
    if len(paragraph_text) >= 100:
        return paragraph_text
    if len(meta_text) >= 40:
        return meta_text

    body_text = soup.get_text(" ", strip=True) if soup.body else ""
    return re.sub(r"\s+", " ", body_text).strip()


article_texts = []
final_urls = []
i = 1
mulai = 504
batas = 249

for link in tqdm(df_news["link"], desc="Fetch isi artikel"):
    if i < mulai:
        i += 1
        continue
    if i > mulai + batas:
        break
    print("Fetching link:", link)
    final_url, html = resolve_and_fetch(link)
    final_urls.append(final_url)
    article_texts.append(extract_article_text(html))
    print("panjang artikel:", len(article_texts[-1]))
    time.sleep(REQUEST_DELAY)

df_news["final_url"] = final_urls
df_news["article_text"] = pd.Series(article_texts, index=df_news.index, dtype="string")
df_news["article_text_length"] = df_news["article_text"].str.len().fillna(0).astype(int)
print(f"Artikel dengan isi berhasil diambil: {(df_news['article_text_length'] >= 100).sum()} dari {len(df_news)}")
print(f"Fetch gagal/kosong: {df_news['article_text'].eq('').sum()}")
df_news = df_news[df_news["article_text_length"] >= 100].reset_index(drop=True)
df_news.to_csv(f"df_news_extended_{mulai}_{mulai + batas}.csv", index=False)

Fetch isi artikel:   0%|          | 0/2473 [00:00<?, ?it/s]

Fetching link: https://news.google.com/rss/articles/CBMi5gFBVV95cUxOUkJyMVhjeUFOSFJjNFJ2Yk5zRUVkcUtzX3ZVQW1rQzRJXzFaNjV4dV9KaUh4a0ZRNFZUVjIyb1JfVm84V0cxR0lFeE5zckpvSmJuOUpOQjNVWVdnNXV5QnFfNlVXQzlBcTBnOHZOWXM1MEhhcHp6YVV5c0Q2cklTSkxfMTBFXzVGaUdDdU4zY01rRUhrVlQ4YU9wZ1hNajZDQnJxN3ZFSGlvNER4dTBzeG5lUF90MmJuS1V3SXRiTFo0MGZIb2QwN1hrUU1wTUJ5U1hyalRReENuaFNRTFA4VXB6YV9wd9IBzAFBVV95cUxPSzBqSHA1RjJ5QzVRcURFNkc3dTU1Tm5pU1hDMlQ0NFN3U0p0SkJCeTV0ak9qdzktRm56Z1BwSElmWEFfdERGcTJUMGFDT0x0M0tGSGFMWnhubmtnVGpLN3d1WmtBazV3Rjl5VHZ4aTBjOGlObUJOVEhEUDJmNWZhZ2pwT0prMjRtTVB3djhBM1JYLUs5Q3JBV1oxYzktQXNrbGFZTGhhVnhzYVVldkRNU1JiaEotb3N5dWN4a29KSHBsMDNYQ21mZDlMaFI?oc=5
panjang artikel: 2162

Fetch isi artikel:  20%|██        | 504/2473 [00:05<00:23, 85.15it/s]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxQQXZnbE9WelVKMVNHM3VId3gyM2ZyVDlPV1paeXlHSDhQaTRjZXZmdFU1U0J1cGdOYkQtVV8tdVFUQzByWnNjRkVram1UeEsweFlEMzJQTVhXZGRmSGJtdjJLYlhydWMzZ3RITHlsM2xWTTBJNzlMSjBPdUJyYXF5cDFnX3RJaHo3NXJYcGVTeHdxRW04ZkNGRV9aQUxmZFVjZE1Ec0x2czdnZjZ4VzB6aGNsVnQ4Y0NvVzA5WkVmZXhWRUlBTkRrQ0JaeDljdw?oc=5
panjang artikel: 1523
Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxOanpQWVVHVGt6ZWdDNFNoWGstN3Q3VmI5WGZwaEl0WFdiem91S1NrTWw0TDl4bElkVGJZeE5makVZTG1QQUFpZ2hIYWdaTm45RVdKd0s2aWUxdnVubVlyWC1JcGNvZXE0Tm9CMGczVS0yb0w0R2FoUHFPZmE2MHVGUzBNM2FlUFFEUGxiMWxseVNzSTQ2Q1hBLVAtcm1jaE1lMVgzcVUyOGNiZ0FBSGRwRmoxS0dqbjlEVHBlSnp4bWY?oc=5
panjang artikel: 2442
Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxOeFVkSVBwU3U1czduLTBONVpjMkxscEN1RjdTcHM1QjRrQk9Vd3l0akV6VzFtN1hWelFldGQ5Nl8tUnFadFJhVldGRk4xQ3hWR20yeHlMOUVkMlRmVHFWRG5ScXNDOTUzb3BpSDMzaFVSdWNCTnBsWllBODZPeGVoLWM0U2RvN3pBNEwyRmlndFlXVHhJVHVoVWQyWnZ6ZGhDOGhack42Yl9jME1aMEkxcdIBtgFBVV95cUxNQXVaN1pXbXgwaF9VMXRqcDZKeUkyU3RNYmRKTUY3VExDaHRialcxR05idDJPWWN6MkVLWFRWYTFlbE1nNE50YTcwd2p0NUduNF9IUG1YaHMtbmNaQ2YzTUktaHZjVUwxSHRXcUV4U1FxUTAwZWNoNloxVmJYc1VNdk9hVUhETzgxQjVNaHAzX25jU2UzemJ2VXlOb3MwT0hiaTdOQjVFX3V6WU9aaDFkR0ZrWlBYZw?oc=5

Fetch isi artikel:  20%|██        | 504/2473 [00:18<00:23, 85.15it/s]

panjang artikel: 2411

Fetch isi artikel:  21%|██        | 507/2473 [00:21<01:46, 18.46it/s]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxPdmlXbGNfSFpEbTI5VTJuTTZldTRMa0xsWVROV01NUzN3cWxCSE9meHhrREVuZ0V5SHNZdU1tU241OVVCQ1Nvc0FyUDI1TTNjY0dhNVJFcm1Vc2wxUVFleHFBeEJpTW9rbE9ReTZ4MHYxcmU2MnJDaEZoUDN3cUFYOTFoM2kwSWFvLXVtblI2cWZZbUlSNG9QdE8wZm0yRXlCemRpOG5wWmZGbUVyc3R0b2N6enN2cGZoUFl3ZVNKSQ?oc=5
panjang artikel: 2871

Fetch isi artikel:  21%|██        | 508/2473 [00:25<02:24, 13.62it/s]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxPclI0Sjg5Qmc4dE9WdERVYUl3RXVRWEpCcklRRHRabXdRWVJJdFdHVU80RnR6RzBoX1FiUHctZFRwbmpGQXNES3RpekR1eVNSVzVvTk10RjBDenh2Ym54WHR5RW5XMUVpYnNZQjR5OXduenZBMnpPQ251OVBfd21jWUhWZ1VQaVVkSTM4OThBWFhsU1J4TjVMcFZKTWlyWDBYTzNTalFIck1GMUs5TUJzSDJWVXozODNaUlJLYmFiUkJaQQ?oc=5
panjang artikel: 2809
Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxQVENVM0VUQXV6ZVBheXl0dUd3ZDFTVDFOVFVZbVA0ckVab3Y1RUlMUnlnMHlRa1lhNXE0RnhUZmo3VnhSaHY5aWNoYlZKLXNhYVQ4MllZWjRBb1ZtSmd1c0RuaXowOTVRNWZJdm53VUdvQ0NyOVRpc0JnbTZwdnA4VXJVMHlpNWlZazlPQ0dEMlVFQ1dEdHZBN1RjdUdQZTlYZ1IyU2RSdG9PbEFyRmdB0gG0AUFVX3lxTE1UV1FiQTBKV1R4Y2NtckRWV0hPVzVSZVdMcWlURlA3aEdtYUdXd3ZWS01GN0YtLXJuQU1BX2RlRzgzRS10al9LUTZQR2dJYzcxR1RLSEdROWFXUWtvSmRmZDNTdG9hVzlJRDVYTkVqdU9HeDJKZDVubmpESnNQWVB5d1h0aEdSd2ZiQnBmeE9reF9TYnFKQlAzMjJzZ3NFdWRNYS1pUEpzM3JyNDdXWEY5WlJrcA?oc=5
panjang artikel: 2131
Fetching link: https://news.google.com/rss/articles/CBMizAFBVV95cUxNbWVScmt0YTNLdXNQNl9yS3NqLXVfRnNwbG81c2pWU25xeFhkMS10eUNBcjIxX2t5anZvWXdZQnJ6YzE5QnA5cDROU0NXY2FaWFJ0d3FVVHV3eUZ4SHlYUm9mSXd6cy1ubDhGeHlMM2VYQ0J6UDVHV08zM29WZ1dZREJNM3JEeWVjMjRwWkpQNnAzNUNQU3F5RWxDMTVsZUNmc3d3ODRMVHB1NXZRZkVBZXRGdG1wc1hJendKZThvT2dKaG9VOGl0eTlEUVE?oc=5
panjang artikel: 6010

Fetch isi artikel:  21%|██        | 508/2473 [00:38<02:24, 13.62it/s]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxPX0h2bU5DYXpmdFc4NVhzajlfd0NObmJoZnhWRllObktYdGNjSzVNUF85RmZISFI4U2tJYlpkdkltSmxadl9lT3phcmIyYkdSWUMyTDNpODVJcEc0TlJlZkF1ai10Tno3aTFqdEx3UUFpN2drTU5VM2VlNGg2bnRqcHI5Mkd3ajA5cl9aWnJvd2xIcGhfUTV0ZTZGU0E?oc=5
panjang artikel: 2018

Fetch isi artikel:  21%|██        | 512/2473 [00:46<06:07,  5.34it/s]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxOMjE5ODhHVW5KM1VmbUZ6c0xyOHpUTW00Z0tEeGRkZ280cmVVa2F0OEhiS2wxdll6ajNJLVF2S2RIQ2ZKZUd5Nk1ZUjRFRklDLVp5TXI2QmxpQVNQcW1TVDVEbGxKNi10dTBYVW1rZVpacWJJc3llbThwLVd6Yy1ocnZBX0J2MVN6b3ZnS2kxb2tyRHJDMEExRC02ME5Uei1pSHlhdDlLRVhkWktVMDBTWGRrWmQ2Z9IBuwFBVV95cUxPV3E2T2hxNjYyM3JpUjdrTVo5ZXFJM1ZzRnVMZlprMFZjdGxyejg0cEtKUUFFNUtqNmhkdzZSbGQzT044ZjU3cTUxcmNvazlraVpXTkFQMXBSS2VhT0h1Z2lDaUNCV2xpS0xDNHZJajF3aklMOGRYZm9FWjFfNmNKcnFhOHluNXFkdFJEbGtsMWJKSk55bndiZUJfYUhxZXlUbWxFZm9RYmpfa3lYQ1MzcTFLRGVwR2wyNS1N?oc=5
panjang artikel: 1922

Fetch isi artikel:  21%|██        | 513/2473 [00:50<06:59,  4.67it/s]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxOLUU4M2NfNzUwZUpsT29SejJYWl9vVlZleXpSS2MzVjBOZEJYTmFUVU9zRENPTTBOZ3FXYWFXcHN3R3JWdm53MzBQYWkwUWpzeXBQOEw0bzNYdTBtakRQZjB2cVVfeWNaTHhvd3htenlncERIc1Vodjc3bWxoRElOQ1I2bXdqS19RbFpyN3R0czgyVFV2WlgySEEwMHphUjJnVUtrMjhHSFFoYWRWdGh4cw?oc=5
panjang artikel: 2295
Fetching link: https://news.google.com/rss/articles/CBMiiwFBVV95cUxON1hOR3JlUkxFRlRENE1rMEZ2VFk0dzN4QkdFQUYtMDdPTmZRZTd0TVpBdlF2MjFFdk1wSjczYk1tNzRBQUZoRlJyVmJqYTlMaWxmTldsaF9FVXlnV2puVDN4M0Q1VjZHcXlyWEk3OWVaNWl3RTNZU2I1U2ZZNjBwM0s2QnRtdWpOUkRj?oc=5
panjang artikel: 451

Fetch isi artikel:  21%|██        | 515/2473 [01:04<11:53,  2.74it/s]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxQbDNKZlZ5dG55OWwtTzhBcGRhSUtkQVByNFlzXzRPUTdEdmxZSDlSTGUtVnFOSGhCTXpwWXdKbE5vQXV4QW9ickNpN3FaQmNQbk5VQWFlYzJjQzFvZW44cl9ndjhwbmdWZUhod2M5SGxSem5aZnkzREN0bmV1NjJXTHhpM0NfLWN3c29sWkU4QzIyQ0JHQUZRZU91ajFFRVBDYjllbjN3dk12UTRHOENwWHpPdUxhYlF3bmNGcGl3ZGLSAcYBQVVfeXFMUEIzZGh1SmRWQno4Z2h3STZXTUdyanVXTlh5ZFhoREpvcUk0emt0SDhsZGkxUGYyZm9Da2J5YldvYTdKZDVnb04yOEd1VE54MG82RjNEVGhxTlNXWDJ1d0tpWTJtWGpVSG9qYnRfQ2ZBMC1XRmYxdlVJbGZTWF9fTGxoMnZKZWtIaGxhdnkzbDNndVJMRDdGeDkxZ01Lbl9OamMzXzdJOVBBTjQ5ZEtCbWFsSmotVUhHWmFOS2NZQUhnZ1hneWhn?oc=5
panjang artikel: 1736

Fetch isi artikel:  21%|██        | 516/2473 [01:08<13:49,  2.36it/s]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxQcmJ2QmhvU2J4MDlTRThZQmZtdUs2Wjh1UW5qckJnblF1dDItSlZfbDNrTm9Tc1hOS1plbVgtOW4zWF92ekVGdW1hUDVndmYxR0VGSEg4bUxyWjFHbzBnWjJEWmxpM192VjJZWjJkVDNIbHJ1S2ZDcm5mYklRZ3RrVHNROHBkaXBKUWFlS3V2TGJ3SWpqbWZlNERXMW51NHdIRXNZUnhlRW8xNV84d1dfYVE2VG4yUmlRaFNj?oc=5
panjang artikel: 3514
Fetching link: https://news.google.com/rss/articles/CBMi3AFBVV95cUxQQkR2Ylgzcl9STXlNek9ZUE9yU3Z1R0ZoOTVmakZWTUFmcnBybU44ZDF3SmxVbzExVGRkcEtjU0M0NDRnVWtpMkREdXFMOHFNNU9rNDVHOXp2MFotdWlSc190Q1YxMVJlMFJJek5Xc2JKd0J6cDYwVlg3cWFNNURiOWpWalJSN0Q1bXVZUUtGa3NGdTNOUnc3ZG41a09rdFJFSEg1OHJYUE5tMDQ0b1MzMVVXT0EyRHNvRlBpTzZDTWY0UmNnTHdtWi1nV0NPRmU4ck85V21oTTlTTGhv0gHSAUFVX3lxTE1mVTU0M2tNMlNNQnFYMXlYUVcwS0pNM3VTRTZVbWxkUHJzYmZqNktDUHNvVlBvUGN6M2NYODlpd2JiUUxEX2o3OEtTcjFQMVlDV0xtM2dnWTB0LUtVX2d0a1JMQUxSUElidXpTR2NLbTMza2tsdkhUQzJ0RW55R0NBSkxQaXpTYlFxQ01hQTNFbnFDOTUwTDI1WTNKcnpOYnNYS1huU0ZYUzZLU0xna05xUUZ3OGVnUGVEdllFTzFSMVBROEM2ZGt2dnZyOVI0X000Zw?oc=5
panjang artikel: 2126

Fetch isi artikel:  21%|██        | 518/2473 [01:16<18:35,  1.75it/s]

Fetching link: https://news.google.com/rss/articles/CBMi3wFBVV95cUxNa29oWHBaZUZic2Q5N3kydkNiMTRZRlQ0V3ZqdXJneEZfczRKSUZrc1pWTUZfMzRjN3N3Umk4MUQyLXljRjdFZWxDaXBzcW9vaFFnY01ac1J4LVotQlpFTnFYNlBUdUxQUEVCb2Fnd0F6Q3B4QzVURktMa0d6ZjlOQlEzUm5yVlVDaUZ4SEU0UEFMd2VoN2w0cW1PbG4zZmVfbVluQUtjQjZzdXFSTHZYeWVHamhaOUlJUVVGMjRwWVJlWm5uQW1rb2pLTEp2eXdZeVZ6TWcyYWw2ZmMwQTdV?oc=5
panjang artikel: 316

Fetch isi artikel:  21%|██        | 519/2473 [01:23<25:00,  1.30it/s]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxQNk82dnZ6SG9MS3U1WGJXbVhHdzdpS0ZjZ1BRUTB5ZzV5eWtXaExxdTViNXhfZEE2a2dCTmJEem5ZeUtvck4tSUVkVWxBaGI2aTYtekYzTEFXenN2YnMxeHNET1pJNW9lQi11NGNDdjdvVEpaUE9HbVR6LVhucjdjTFdYTUlaX3lyWmFUcHpwd21xR3g0LWpVUG1CUzNrUlF5NWUzeXFqQkJkaWNh?oc=5
panjang artikel: 1522

Fetch isi artikel:  21%|██        | 520/2473 [01:27<29:14,  1.11it/s]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxOcER6NFdRWGlQX3pSbmhhM3ZSZm16dFZNQlNKdHFSMjE1X0x4ZllpdGJhRGc4ODZLUXJWQ21uTjJDUURnV3pfZWdUY3IzTF92eXNuaUhCTmdxWHY4QjF5aWUxZXR5VkhpM3hBS2JTX0ZEQ1NIaGRoV1F6WWdKaUVhVzd0SGk5ZXJ1MjhSVFg0bW1WaVBhNWNHUXJpbnktbW1ZS3lsOFlBMkhEOU52eGlFa2NWSW1WUW1raEdzWjJ3TkRrODVqdnVzR0UyU0thcmp6dmtsV1pwZ0k2eGPSAdABQVVfeXFMTW1tQUtITWhleWN4Y3lBbE5sRG1YeFdKWnBzM1VRd1AyZV9HWUdaeVNSVWt3UVVVQmdkVWVBZXZlcFU3c0ZwR1hfYy1nb0FnbnpZOGxhUmdGbHNhY3pESmxKNHlzNGVma0FaUS1rM01KdTdpUUUxWkxfM2piVEVLTGFlUl9kMGcyd3VxbHFlNFhiemtQbFdzMmc2dkJ6TWVIN0NIbGdzTmU0dzlDMWp6WGlZbFRILUJqSkRYT2FDNkRaajhaR3pxek84UXZjel9rTw?oc=5
panjang artikel: 1711

Fetch isi artikel:  21%|██        | 521/2473 [01:31<34:24,  1.06s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxPVmlSY2h3THBJR0l5d25RMy1Ddlc1ZXk2UVVOQi01cURsZ2p4MnhwNjkxd1VYQXVKZmhFakZmVkx4X0RvNi16NzQtTWhfZDdMNUZTVFJ0M20zLVd0R291ZlRDYWUzTEJWSUk0Y0xXYXJGTlJiWUp4dGk0R3BtcmNibXF4NnhlalBMUW1xMndxRUJCVnMtUG1Qbl8xMmdoMEJFQVg0UGljc2c?oc=5
panjang artikel: 3711

Fetch isi artikel:  21%|██        | 522/2473 [01:35<42:54,  1.32s/it]

Fetching link: https://news.google.com/rss/articles/CBMiowFBVV95cUxPZnVwUE5OX2wyNHJsOUpIYUtkQ3kzd180S293cXNRd25lUU15cGJCd0JOdGxXY3RRaGZVOE1GOVVpaFNJU3FlZ2pERnhHT2NZS21XWC1DY3BWSkN3VnhaOE9nNUJBSjFwenlxQlR0VFB4TjNLSVdOUmMyZ3NucHlpUG1iMTFGbXZJVVRKU1J5X01IbEphSHJOMXNWckthR1FGaVFV?oc=5
panjang artikel: 3118

Fetch isi artikel:  21%|██        | 523/2473 [01:39<50:35,  1.56s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxQdVI5UGJaeVVOdUhtZnQ5cnFTbWdSc2xEY18xQ0p4VFFIWDB6OGV4VDRrVk5LZmgzTFQwRnR3VmEwS0RPU0lYQTN5SzZ6aEpqanZwSnlldjhudHhRMFpSUWRkYUZ0cDB4MHRsZi1KZlBHQWdlZXVLeXdPOWFmV2VaR1huN3dUVVZkRTE1QUpoNGYzYjI0T2ZuOEF3WHRYSFFQTEZsdU5hSktJLXFiQURpUG1KMDdfcXhDdUUxdnU5bUJOY1VD0gHKAUFVX3lxTE9vTGdSbm5aclNXWU1kc1pXbk5DX2dXb2ZseXJjbjR2NVhlWEpsb0ItS1BrLWNaWWY1STBkcFYzd203Y0VDTlNSTk9mbzFmYWsyWjBJTWlkUGxlWTZhcUZjeFhsRUt5aHNTemhhMVNIalc1dFlVMm1oYl8tYmFIdmdNTFdlSnhNRHRMeUVHaFlacU9BX0FCMGhJaDA3Q09NR1A0aVpjcHBiT0JMOG5BZ2xGS0Jlckg4c182aHRtWWxzWS1iZ3BXTFI4X3c?oc=5
panjang artikel: 5968

Fetch isi artikel:  21%|██        | 524/2473 [01:43<1:00:05,  1.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxOMExudFZjeWp4ZTlRbnR3NEVVMWdjZDhVZmF1cklaR2hhdHNvTVBGQXZyTkplaENBSkNOWHdJcDJic1pFOURHY1NMZkZNMzlPNGVqWnJwVHVJZi1hOUkxUHZ5TUR0bWZ0ZjE5eU5EYktXYXBITHo0Vjh3MllPUjZQSmJHNnA4dENMMTlKUE5XRHl6WnFGXzBFWGl3?oc=5
panjang artikel: 1372

Fetch isi artikel:  21%|██        | 525/2473 [01:47<1:09:20,  2.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1AFBVV95cUxOMjQ5c0w2c3p4ejJPSFY2S1JfODg5d2hYSWhKMzkwQmxxdFRjMFI2UlRwMndjV0EyUVRad1VHaWpNejNYTE1PX3A1REtqVWcxLXhXUDZWcEtUOGFjdVNjaU5JcVB5THhBNTFucjhsVmNKY0gybUtZSm9May1TQlpwaWZnRXRpZ0t2TlRmOWxxSW92UzZfT1dLU202bkNjdHNBTTNac0lZNjN2Y2U2X20xLUtuY3U0NElWWGF6dDN1a2Nwd2F6NzlGTlVXaTNyd2FtYVdfdQ?oc=5
panjang artikel: 3216

Fetch isi artikel:  21%|██▏       | 526/2473 [01:51<1:18:57,  2.43s/it]

Fetching link: https://news.google.com/rss/articles/CBMijgFBVV95cUxNNW9ESkRsVWV3Mm1TR0pWLUl3V3BsRkExbjNfV3AwTmlCN3RoWERfUTBkS1VFRzBDTVd2U2xCSnZPRHVBRXh1R1RDanVBcmJieUxRS1BFMVplQ1FCM3hzc2ttM3VyZGpXVUlaZ3RQOHE4NVhpS1gzS0RQVXFsVkZ3QmdmVW0xRTViVm5Kalpn?oc=5
panjang artikel: 2123

Fetch isi artikel:  21%|██▏       | 527/2473 [01:55<1:27:45,  2.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxPWWgySnUzb3pZbXhCSHFVR1lDSHJXbFRmSXJtVVE0VUE5TGxEQWplLWpKbjBRNFJ1QzhCYjhURUlPREhkVUhtTGhxaHhDRXFiZGc0OHZXRWhuVTlqSGEzQ00yNVRsMUROZndSWU9qYkNMeW5LV1V2b29VcG5wWHd5SFZ4YTYtRHZmeHFBQ2RPcS1pOEsxNGFyRXlXYjlMMVQ4V05aZ2RjQTg1cDd6bUphWnBKSU0wSmNETHFBd2o1N3PSAcYBQVVfeXFMT2Q1VU5USW9Gd1lrcmZacHg4anBySUo2eHB1bFIwVF9uekdIdkJjWnZTQlZ1Vjd6MXVvY1RHYkMzaU1UODdoVTEwU2Uya3pBQ21UblBaWEdRWnM1X2VWd1pZZjFMcXpjZ3NOUEp3azVEVnpUN1pZeVlWNEdweFZGQ1JJMDRaQlpsaDZ0RUZESjNTN2RPbUljMVdqaW9icmdROUlKelFhZUUwR0RaUjdxbW1fbW56am5TUnM1OXNlV1k5alFiSThn?oc=5
panjang artikel: 6551

Fetch isi artikel:  21%|██▏       | 528/2473 [01:58<1:34:39,  2.92s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxOazhTZnVJVEZra2VxcTYyME13Qy1SOXdNUVlBZWwyZ2lEOU13aGI3X2dvRDg3N2hvRHpZVDdlQm83Z3NqRmF2QmRYU3J5RGNCZWpjQ2MxbXRlQ3N5NWJlbkVzYWpxbnlLMjBVN0F5VlJSZ0RfazVSZjVZTXFDVHFJNmlqSTJzYlRHSkJVRW1HdTNRYWxyY2hiWGdmT2V5aFM1NC1DdFBwaGtuNDBuZXNMYm5NREtsdVk1MjViUlAtbmNfbEtr?oc=5
panjang artikel: 5787

Fetch isi artikel:  21%|██▏       | 529/2473 [02:02<1:39:52,  3.08s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQSTVqUjZjWnY4ankwTmxTcnUxRmM4djFYNXp1c1BCaURTa1BnckM5STNRQkp5MzduQnl6UGZEazRWUklPU1JHVUJMSTVaY0ZXb24wUldSaWVNS2Y4TVlRYm05NmtJNUZoTW1rVWhiN0QxYU5zb2tsVkNYbHBMR0JUdl9EX2E0MGt1dFhCellJM3RPbTBkcHN6dndwMWU4VTdpQWxhSHdTeHF1Tk9rbGh6TWhlRTk?oc=5
panjang artikel: 2555

Fetch isi artikel:  21%|██▏       | 530/2473 [02:06<1:48:48,  3.36s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxNdHA5akZ5ZkdhcTlzYkh5aTFBT3ZUTVFKbGFadTdqTUduMldsaFRmQjUtM3NxeEtjVXk0SldOWVpKZFJsQ2VoUjRHSWNIdXEtRkRrLUdaVkcxai1ibTBaTFF6OGNQN2ZIMEVHS1lSZm1lV3I5cDdEbUJMdFNRNkN6U09lVzQ1X0RwVFpKdUhmbERERjNHb19ENVVBUHA3bGtFQ3c4WTlucmg2RDZKRVVWNGF4SGxiVFlPaWZQTVRVTk5aaUp3LWt6dzlFZFNLQ0U?oc=5
panjang artikel: 3181

Fetch isi artikel:  21%|██▏       | 531/2473 [02:10<1:51:17,  3.44s/it]

Fetching link: https://news.google.com/rss/articles/CBMiywFBVV95cUxQTDJDZ0JsSzRYRDR0VXE1Y3dyelNzbUhHbjA0aFpyMXhOX2FCdkVMelo5X3kzZi1aZkpqTTRlZU9KZ2xEcXo4eExlMnZIWFgyU1hhZ2V0VHNuSk1kWlVna3JUdFcydHVyMlNQdUE1RXNocDJCVmpFS00wTjdaXzNUNEw1c1FSM1JKVW50OWxvLTVIT1BESThabXRDcC1OOEpTcFZTS1YtQkdVMDVjZzNQWUVsR2xQTXphOGF1U0I2N3FCU0JnWmRSRzlPQQ?oc=5
panjang artikel: 2591

Fetch isi artikel:  22%|██▏       | 532/2473 [02:13<1:52:07,  3.47s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxONFgyanZNV3M5V1h0aW1yZUU0dnBvVGs1UTJqNFJCWDl1cGU2U2VOTXhkQ0xJNXdRZ1NteGs3TnlyU3VoZ2FCLU1pMjZlSVJVU0RwNnU5UnYzSmhyZ2YzTmluclZtZHUySTJhemhtU1A1TFhGMXNHZXhvX1BjbklqVVdwa2xWN1NyaVMwbjFyd0FiX3huLTVvWVFYeGpLVnR4MnFHb1VWSjIxNE9LMkE?oc=5
panjang artikel: 2865

Fetch isi artikel:  22%|██▏       | 533/2473 [02:17<1:54:04,  3.53s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxOekQ4NkV3ampiU3BsNENxQWdEYVljNWlVVEl1Ykhmd2Z1NzV5SG1NSU9IRUdrOVhuMG1PUnZPUXlFeFRtRkNxTXREVXIxbnhwQmhZeFZGdHpPem5WMVN1TXZiZEhtUWFMMDFsQ0lGaDRsSzR0SkNVYktla0xvaGZCR0JzYmZhVzY0WEdVNlRYWUFNbUpQUjNkeEk1NEJWWXd1MHBOeW1XZklyZ9IBrAFBVV95cUxPcjAtaGtock9UWW1lTUVSODVpbTltUUZWSW1fSFktWm1ZZ0huWEMwQm1UYzJFOXZNbzZaMFdydlNjdGVTUV93NFlXWU1sNUp2OXluZ1BVUkJGVEdFdzd1TktWMENuODU5cTR2cmdxWlFGTDhIVWZxLW03ZjVDUjBObWxHN254XzQyUlM2STR0MG5oWjdtSWloYU1oS0dPWFFLdmJONVF6aFRCUzhp?oc=5
panjang artikel: 1506

Fetch isi artikel:  22%|██▏       | 534/2473 [02:21<1:55:27,  3.57s/it]

Fetching link: https://news.google.com/rss/articles/CBMinwFBVV95cUxNbHdyVmVieV9xdEVzRERUMTg5SkZPcS1HZGdUOUt0OFhzT3Q1cWNIZXdTNTQ5MkM4bklUVS0xWFlSRUJYVGwzT0tsd1JMT0xETGE2UkVndm80Q1VJd2dPTmc5cmNyWEI2QXZldHlxNGE5VGNCS3ZsOVRRVHBzVXRWaHU2SzFQRHZRRE1SUG0tOVRHV2RtOUtXaFJZSHBFem8?oc=5
panjang artikel: 853

Fetch isi artikel:  22%|██▏       | 535/2473 [02:24<1:54:00,  3.53s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxQNkpjSGZLTFFsSktLYTl4Z01EVUcxQW5Yb3FxSjF5aDNEM2xtblR0SF83Z0JEQnpCQXBMYWFndFV4MXJfdzJycUxDMUtTak5JaldRZjYyamdqeURmaWRqR2QzSUF2MWhmQkcyaUg1aXZqZmxtS0tLTFBWWDlLNW96cEdHX2dnLUloN1Z4Tk1odHFpRTUwT05oV3VaQ3dIWUIzSmdHVjR1SlAxM09rMFRJ0gGrAUFVX3lxTE5qelpuTnI5RVVTMFQ0ZTVuSHVjVmNuSVgtTEJuX3YzU2RWVUVqZnNPZE9GQUFSQWZPWEZDMExSX2c2d0tkUEJNM0RlMU44RzNIdmtoMlR6bE1NeEx3a3ktVkpsTHNFQkhyanlsWm1CcFNVNWMxVl93dkxhcUJfWkpFMURVN1cwbU1vZTIxdjd6Q0JoWEpaYk9uNnpMQ2ZvcWVuWE5OemJmemx2RQ?oc=5
panjang artikel: 1361

Fetch isi artikel:  22%|██▏       | 536/2473 [02:28<1:55:39,  3.58s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxQTVNZUHJmNHM5VmI5Y3RTV2tsa3RuT0dpOVhocnFEWjFRTEsyZWlrc0YwVHF4Yjd4ZG94N3VYYXdOWXBWUVZSSmZwam44OTkxRkZUbVI0SS1Ib3BIZGRSVHF2cW8tWTJnYVNlLUhOUFMyNnRUeGlvcmlpSVhkUk80TW11Mk9YeWZBZG0weUhISXNXdnljWjVjeV80M20zSzFPd1ZxLXZSUDRMbU9yRU9MYmY1Yzd1Z3M?oc=5
panjang artikel: 1413

Fetch isi artikel:  22%|██▏       | 537/2473 [02:32<1:55:41,  3.59s/it]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxPV0ZFMmcxQkZyU3Jzel90cUlIb05WWUF1a1VZZjhJb2lnMmtJSEhRMDFfX2VhWWNBR2pHRnhyenJqWklQTW1zVDk4OVZCNHppVGRGQkswR3VZM1hRTnpJTDhYeFMzd2I5MnA0SzVCUHU1Q0hBRTZIVktFcTcwWFZfTElNQXpaekNTak1tT25GVEVEYnV5M1lVYndlQm7SAaIBQVVfeXFMT3hUOFdpdU01WnZxTTkzbHNESXBsamZQdUFRWkxoNExyZEo2TGJTWC13aHZaNTVQMVRwQV9WRE1mYnJxYW9zMWZjaW0xWjJ5REo3aXZlNXZiWjlLdjcyUlQ5NV9DYTRQbEJPSGFmcHVuV25KV01JNjlka2czMjJlenRFUVA3cGNWZW1LSlRLNmRMVGpqUlYtTXFEeDhfdVFpNzBB?oc=5
panjang artikel: 4187

Fetch isi artikel:  22%|██▏       | 538/2473 [02:36<2:04:41,  3.87s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxPX2FyNnFlYzY5Wks2U1FyR2d0My1hRmhvcDZFTTkwVksweVZydTFqbkRRNDF4cFV6UFdiN0F1TGNPYTF2ekVuWUxXVkowejZpMWhzbEZnYW90X014cVZ3aG5vYzBKUkFMWktxb2RRNFlTTWRDcjE4OWVMQ1dXaE5tZm04OGVtOU1teUJhMFVPbHYxcVNnV3IwNnlxbHN6dHA5NndtbGwxcFdzR2ZodlVnTlgtTVh6a3JFRmFlMUo4Zw?oc=5
panjang artikel: 3052

Fetch isi artikel:  22%|██▏       | 539/2473 [02:39<1:58:38,  3.68s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxOalRnaGlaWlBhVDA5dkVFd3RGNTB4Z0VoVlRyeExIVGNfWTBSMUJUaHNXdENNbUVEU21PZU1RUXMta1otcUk1QUNUeGpjeC1Xc3dpdzA0WFJlU1d2RkV5bUkzUUROUFV3ZlpnYmtLYy1tb0FUc3VjTVdmWHVoSmJSQzJxVnpyNFJfa0tneXZsNV9sQUcwZVY2Qk9aZTVlUENpc3RBRw?oc=5
panjang artikel: 2737

Fetch isi artikel:  22%|██▏       | 540/2473 [02:57<4:14:33,  7.90s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPSzhPaDQ4LVlMTkJZMkxoUXU1SzJITWFmcEJOTkZtUE1hQl9BYXpLOF9JUDV1NE55VF85clNhWVljU3lFVWZiZ1EzajNzYjB4Rjg2TWttVU9tdHpFb3BDYVBESWJtVk1wS1Awek1DN1FhSEUyZWRDbkx6WV9CS3Y2M3pZN0VLUVV0LXBCQ1k3ZnlOS283WFdON2VIVnZpMEtIR2hPb084bkE4V0QtejNJbUd3?oc=5
panjang artikel: 5197

Fetch isi artikel:  22%|██▏       | 541/2473 [03:03<3:50:50,  7.17s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxOeHZvbHcyNENMeWlMTFRkbi1qYU9RRmFuNmlFYTRtRVhaNy1qUm0xWUlJSWNZUjh1bjVCQkI4TGstQ204WUFuQ1JyTU5oSGFuenNiYm9FZGwyTFh6bnl5VnBObWNKaVdKSE8yNFRKdF9MbmN0bXFxakJneDlPYXJrTUYzaGo2MTBkeG93WlRPNTRFcEwtemdTalBEUlBKcjZ6SmZhMWYzcjNJX1NwT0NUQU5PTzdjZGZqVmk3UnVKNDAwdlpXZ3dFQVF3VTdaZw?oc=5
panjang artikel: 4725

Fetch isi artikel:  22%|██▏       | 542/2473 [03:07<3:22:47,  6.30s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQU0Vya3lUdXg4RFpZOFVpUnJHM2ZFd2JWQnJJem51R2tZaEJydDJzMGtFcTZZTW9vOElhRDA2eGZBSzlNSW5DVmJJVFVTZkwydnVLN29PWTIyNTFSSUp5T1pLRDZabE9YNmZ6YnJ4VG0wRmZId2ZZeXJLTHozc2l0WW1vNkRCR055YUxfMEdxd2djZGJaazF6OGx6eHJXbG9kNkw3WTQtbkprQmpZVGlQVkk0VkjSAboBQVVfeXFMT0JZS3JKdXMwTzdIOVpxS3lwbEhpeVltZjQ0cDE5OW12OVhXSm9PXzh2VktPdkVlOGhyYVdMRy0yYUJaLXBhRU5Vd2dBN1RhZHJNeTI5UGxfb0dENk5lYlNTa3BfaVloTzd2dXFOSTVRRl9rczdGU3NybGZnMWtfRmcwc1U2NUpWcjhKVVBmWXBINVdLeENSOG14Y1ExcmROdWljazJSTGYxeFpxUDAxbF8tRE5MX0dLQ1Rn?oc=5
panjang artikel: 1597

Fetch isi artikel:  22%|██▏       | 543/2473 [03:11<3:00:19,  5.61s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxPUzFrUWJsWmg3RWFDTXF2QWVqVExDMWRDQ1VJSnJOcjFGZFlrZGZkOHdaTjhKZEtfM3NrQWlFaVdwanVDdTlUZmZjZ1VsSHJtYzlMWElFWW1nYmJ4dzFqZ0FhYzRqMUJPakNDcTBabFBhMWRITFIzZjhMQlpDQWZnY3B3aGhXZERMR1pzaHRfYUdOclB5ZTJKX3B2allMN0h6Ry1vbEY0WlBjY05PQ2pVRGE2V0s4U3Zy?oc=5
panjang artikel: 1906

Fetch isi artikel:  22%|██▏       | 544/2473 [03:16<2:54:51,  5.44s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxQUVZ3WDhORXdwYXRYUE9rNlg5bV8zZkxxTTNSbG1iMU1xOUphdzRZRG1yQXpGaENSLUpDamRPMWtwakxsZDBmMEZGNkJsa05feEM5ZXJIOFR3TDhjSlRTV2xDOUMtNGh2bXdSbHBKanVyZmlmNTRlMDhCSG5SVy02SlgweU04bFRJRThjVklOV0VFR0k5NHFMSF9NNmFhWU1kN181SEROMEJHeU82d01HRnRGWm1keVBDdkxyX3FB?oc=5
panjang artikel: 1711

Fetch isi artikel:  22%|██▏       | 545/2473 [03:21<2:47:31,  5.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxNVDY4anRJVHdlbEhaT1RoOW5PeGRsZExvSkZFdHNKdGZJanlIVU5TeDFDRDdhVjR5ODNCdWhPNWhPN0duTm9Ud2hkXzE3VkJScWZVWVBJc3FQYlRIbXI2aDNSUVFRZ2h3OC1NQkxlQXdPTU5hTjl5ODNHRllZUXQ3TmdLRFdTa0ppWnV4V05sVUVyazBWWi1ldUhuNUtGcWUwdGxacmRNMNIBlgFBVV95cUxQeURHV0Vwemk3dzZJekg0S01sbjN1ZWVBUnNwbE5JVzUzRGIyRXJsVlJ5WDlPRV8xSmlveGxjUnd1T0haTS1mLUVWdXFIRWtWWGpiRUVVVkExbUF3N0E0eG5jZ1ZBNEJfejRoSm9WNXRQRHJ2QkdnTWFUWXl4d3lld25EbzBPeGhBSUhUc1QxbVJISVB6X0E?oc=5
panjang artikel: 3057

Fetch isi artikel:  22%|██▏       | 546/2473 [03:24<2:34:52,  4.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxQZnZnNTN5M1cxcUI0REhCcWhaWlZIbVNMMWhpcjQyRlE1UUJ4eXlfc2xXUjhfMzdfQ1JrSURyZjBkbWVyME1URVRYczdERVEwSjZsY1d2VG5GYnpfRVdIUkd6UnNyT3hEcDdVNWRHSEs4aVR5cVBkSWdrV2syM2U2RW1rZWIzTUJwdTczMzllb0djZmh0ZUl2WlZ6MlhxZThoajdGbmNWOEc0LUpHWTlsME1XTEZ4Zw?oc=5
panjang artikel: 1992

Fetch isi artikel:  22%|██▏       | 547/2473 [03:28<2:26:04,  4.55s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxQZUd3Y2w0QUgxaURnR21BdFhxbHIzejJqRnc0RUNiVUZtTkNTODdfNms3cS1STmt0UU92SkVDRTBNNldGUEtNQi01UXd0ZlE3WjFTOW1ZMzFxaWVqRXpfNmo2d0pNQkxJd0Z4VmtJS2FBVUJDU1FVcDd5MDl5Sm9SS2oyRkJCcUpOVWNXcThFSFBNMDdyS1VMNnZIbk9zaFRXZVZWbmR5MUFYd3FxclV2TTRtR1doNDhMQzMwUNIBvAFBVV95cUxPSFlHbTJNQjR6WEloUXMyR19FYk1zcGpUTlRmekdsMEFXWGlOUXNVZHdnb0ZGcEt1eVpQNmZYOGlZWEZSS3hUbDE5VnE5UTRCSV91RUpJMW9IbkhoUGlyRHJxM3lPY1VpYS03eTlKdUlaSDJpZ0RTY1dFbUpuMjlnMkplYmNFUUJwVl9JVWZZdWpjWVlMcEdDb2IwWlZmQUV4MDNNblJqN0s1ZVU1bWVfVENtMXBLQkx3ZXlWeg?oc=5
panjang artikel: 127

Fetch isi artikel:  22%|██▏       | 548/2473 [03:33<2:21:56,  4.42s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxQMkFtMzBEaXB3NjYwNzJKcVU2ZUY4b2NvRzJwLVJsdEc0UER1ZmxWd1Z0OE1tNnJtVlVHQnZXc3hVd1c5TC1SR3l2ZmJHSTR4UWd3amhjazZ0OE4wR0E3MmJsRzBuOWdDMHRfUDcxdHBKSWJwVXBvbWN0M216UUlMUW0tVDNFeFktdV9mdlI0WkRCWXRnMC1ZeEZXd192dWlCenFTTmVXMXNkdW5veHlTNDR3eENJVkpyTzJBaHBR?oc=5
panjang artikel: 2051

Fetch isi artikel:  22%|██▏       | 549/2473 [03:37<2:20:56,  4.40s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxNQ3NfcWQ1Q1kzemgzRkZOT1g0X21hNEdSbHY1dWVwTGl5TkowcDZuS3VKY0hWalhuMzVjNWFqQ0RqMlI3cTBGUHZvZDgtWXJ1VzRpWld5WWRNSm1uNWE4ZFpCcHpjLUlwWTg5bkxvdTl2akVZNmpnX1VOMUZDdFVHZmtYN0ZDVnB4VURyX0pTLTdSSFlscjlOV1RnRmV5RWxodjdCblIzVTZxZl9YUWx5amJhZDdxdEJ0bkxMN1ZFR2djMG5fa3UzOU9sX29VSUMy0gHKAUFVX3lxTE9vWU1oazZNMllPRnFBVk44Ym81YmZrSnUzZEpjekdJU0NxeHdkUFNqNzBIV0VZS1c4SnUwSXhlSk1zQ1JGZ3BkOE9zSkI1NjhISkZLY3lUMlgzNXl3dExDWGdFWmpvcXVmTHdJc3UtelFvT2Q5bWxrZDZkcVZRTmg5bUZTTk9PRWVKNmxxd0ttdGw0MkZ6UUdjT1FjZXMwYmdMWHp3dEhDRlhEUU1QRWlhbWdUY1VqeEgyZ09BVUJiS0Y5TDlPRVZzbHc?oc=5
panjang artikel: 2284

Fetch isi artikel:  22%|██▏       | 550/2473 [03:40<2:12:13,  4.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxOVk5nTk9XaU9lcHZDcDU1a3RJbW1FX2FjamNUZDBVUUVZTThPQ3ZTZzNUMTQ4aG5RdWRpaHRjdWFISGxsUEgybEw5aG0xcTRfUlA1T0JUaFREUW0zN09uYTQ4WHpJUW03VGV0bktTWE5SczFjVHNJOU5ubjIzblBCWVM1NWNTU1hBS01RM29oM0tEb0FYVkhPX0Z6ZnlRSVpSbnV6a0owdWFETjJMQWlvMk9zdmV6dE53MUE?oc=5
panjang artikel: 1866

Fetch isi artikel:  22%|██▏       | 551/2473 [03:45<2:13:00,  4.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxPUW9qTk5BcVpfRFVtcGtfeG9kUUNVYjhCUkJJaFl6OHNnajVTQjlnNXNYSHdxeUF4RWRCOGtxa1VjX0QwUG1QYURsX1ZEOU1BbWxJemhuR3h0SC1UYVowUG1vVmlCSW5SbnhCakpzTm9jQ25wSEpqQ1BzZ2RGR1FGbGFONUFsbHpYY0tWUks4RXBwRlA1YWVWU2FkaVNMUU9NSUJzR0U4d3YxWjQ4TnBYUENSUElEQnczcUpzUFBZNA?oc=5
panjang artikel: 1534

Fetch isi artikel:  22%|██▏       | 552/2473 [03:49<2:14:30,  4.20s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxPdThCaDk2N2l6RXQtcjh4UGpjNTNTNjFndTZoVG1CU1k4b2dQSkloeFhEZDczVl9XbnVob0V6Y1ZTMWNBMUtzVzRHalVZdE5kTWJYbUpiNHViQ053NUo5X1ZodlY3WE5HNE5QOHZkbFRCV0M0aTA3amxsdTgtcDVfMEJwZVM0VmNrekdNQy1od3BUanB6RHVZRjhaTnlIbEVIemRxM0dueExiNlZ1U3Nn0gG0AUFVX3lxTE5rRExrOVJDVXJNV2NOVC1oNU1qQjgwZEVxUTVwRjFnWGhRR0s5T2lkNnFZTHdINVI0aEs4aGFUSzhFN0RwREk4WEdtdEd1ZF9WM3F0MzdhczcxV2FRajZKaVMyNnRaMVBuNS1uVjNpNndSUkVodlN1WlQtWWVEdk1TLWhmcXZFc2ZTNmp3amZITGxEbFBxVnpSTDZMdU1LUHhHRS01MGxLRG1VTWlMMXhVZWxWRw?oc=5
panjang artikel: 1926

Fetch isi artikel:  22%|██▏       | 553/2473 [03:53<2:13:06,  4.16s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxNcFFFR29GdTVqb0FZZW1kdk1mWjg5QU40dVUxOUpXaGJEZFlEZHkzTmZIalR3cWdCT3IwZXA3WFFES1BJNDlwcHRXVlA4MFE2NVVoZkg1M1M2cWhzU3ExdmEtSTlIM29HQTlTYWV5Nnc0cl92N1ZHY2cwOHRDZGJ1X2ppeUZnZ3l5LWNrNGFaX081RXd5MG5KOWgtMVAtQXpiVXZRQ1ctMHdDUnZ5TFZsNkZ3QU1LRHJ2T2ZwZnZxbmhhd9IBxwFBVV95cUxQaGJ0dTBMblhmQ0d0cjc1U2NIR2tmTWs4YXVkMnJFLS1wa1hldGFJRnlUaGJGQTQ1aTZRSXA0WHhtX0ltaEpaaDJSNDE1UjBTeXBSWmh2VF8xczY2b2VQWjQtRUowSnlEdVpqTlJvSjJiNG5xLVZYanRCSEtNdDN0SkpwUVQzNjRQSDdKT1ZUdGNJRnBlU2FmTk5DOTlDN1RXXy15bVBJTWpRc2xTSUZYUUtoUWFwV1Q5TjVIODJ1MGZkR2ZVZXVF?oc=5
panjang artikel: 2222

Fetch isi artikel:  22%|██▏       | 554/2473 [03:57<2:11:30,  4.11s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxNaEt2ZTNUZXdMOV9YWnAzTzVRNFZhOHMxQXVZempEa1h3djVBN1N3M292V0VmOFU0dnBxa2plODROSTV5bXhfaHAyUTNPVW9MU1QxVHVTMDBMQUFJSmVWNXk2ZmplMTdtYXJrZ3VadWViVUJxX3ZmM2UtMktJYzNTRkQ3THk0X25CRE5LbklQWjBLQ3lqR19tWWk1YU9qNmktZm82Y2U4MFlEdm9Ma09SUjlhUlhQX3BoX3hlRHg4N3hJTGFIMm5yX1kzN1oyM1Z1S083TTVXQThhaEXSAdsBQVVfeXFMTlFwZzFlVFJNQUxsY1luN1lDang4OEFEcnR5emc5SVE4M2laMmJ5T19DUW5la1k5RlluSWQ0ZXpDUkFWVEI1aUMwMjJhQkRKNlJVMy16YzdWVjJHU0NJQURBVmp5UUFqSXFWa3BtTW11UEpZZmlHQ0xNNjFLU1VvUUV3cGtEUUdEV1lEbllpMmxvSi0xZHJfY29lSjhCeHlhdUU2cnRRckxUTVc3R1F4T1g2eG9wRnlrRHR1SHRKZ20xUmNxWWt2eWc1azBJOWxlSWR6dG1OdmxUVi1J?oc=5
panjang artikel: 165

Fetch isi artikel:  22%|██▏       | 555/2473 [04:01<2:07:26,  3.99s/it]

Fetching link: https://news.google.com/rss/articles/CBMijAFBVV95cUxNY3FVdFRKbGxxS20xMVpiTkdJdEYwRHJvVGNqSzBITUZPbGlhTkdEM05wWm83WXZhQUZ3bWRGR285TndOanZHaUxSVllQa2dobUJZcDNPZnRUMzNYMXMtZU9WcjZOTEVSUGhFT0FjLWJfTk4wMEJJZWZCU2xHWjJHM1VncjlHRXVBZDhBQg?oc=5
panjang artikel: 447

Fetch isi artikel:  22%|██▏       | 556/2473 [04:05<2:07:39,  4.00s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0wFBVV95cUxNaXNFQWNOdEhEMGVkQlFMcEotNWdhbmlyQ3FNSE5KZFp3OVRXX1BaQ24xNnBITElJMVZPTjl4UVliOGRWRU5SYjd6SjFXbHVWeThPTmJHZWZid2ZnSE5pdmtjM2ZnY0QtbkRmYnRtb3V5cDdVYlhMZXpwRnBsRFZGQzRteEI3MWR0azducWpIS3lPWHZ2UnF1a3NWVU10NGJKYzMzUDR5LU9lNF9UM2liMUtyVXR6SW42TE43NFh3MDdkeERHenJIR1Z0ZFVpYnBreWZ30gHGAUFVX3lxTE1EOXRKdWpDOUJuWUtjZVN3Y0dXQUQwbi1CLVh0R0FrMUZLYjl1cEtrSWE3RlVScWVsQm9lQWZXZHNiUWgxUkdvdUwyODRtQV81MmI2czVNeTNnc2s0YWw0WWtoaUxkRVVFUTcybGJEN29hMmU4dEQtREROdkZGUDlmUjVvZVBMZTVBcWNVMjZndy1DOER6RW1GV0pNN2tNYnRTV1RFaGlvSUEwRHVYczRjV0J5U21KanN2cWkwclZCRG5QSUc0UQ?oc=5
panjang artikel: 2536

Fetch isi artikel:  23%|██▎       | 557/2473 [04:08<2:05:42,  3.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxOajV1QlBPRjVGaUtIUHBzNWlkMHhzbUt4YkwtSmFyNzMxME9HbUhmSU04VGV2aDhHWXRVWHJlNW9EdWNOaFpqTlBKeUZIMWJWbkFBZjQwSTlUYmYzUDFQNHdMcnhZSjRZbjgzVFNiSUNoNnpnY2ktbW5qSFBCVjVsZTNtamtTalVJVjN6OXVCUGdUUGVkbUVYVm1DYjNpeTcwM1RZenk5SGtPUUlRdjZmVWVDMjZXNGZYQVQ0VjdvYw?oc=5
panjang artikel: 2305

Fetch isi artikel:  23%|██▎       | 558/2473 [04:13<2:07:13,  3.99s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxQTHYxWE5rX1BiR1NReUt6bnIzY2ViLWdmeDNBQ2RQOTNDUC1nTGVwSjFKOFB1TEwzTi1wSVFqWkxiMlF6SGtEdWhEcVVBS2VlRE9rSVFRbzA0Wlo4S2FBTS1FS2plMXhYWUNqYk1XbEtXZm14eWdGQzNHRzJYWkhIemNxVXNPbzVkdFJJMHgtNEZWZC1GLVBPc1NSaTE0VDBMNEo3OGdndDVGakFjNV9FVzZKUUNHb1hoSnpkaW1HakxUcHFrSlA3SkVaLWg0NTlFUy1DVTFvek5FcHfSAeABQVVfeXFMUGw3d1JlU25HcGZ4V0ZjOThSYmxpREpMSEdMY2FUNEpMcXoxQm14bmhpR0k5QjhRY0FwX2tIdjI1OVNoODhrdnUyTjY5QlhMWTNseVoyN1Vhc19PcVd4UHAtd1hQUWhCbTdmdmY1SEQ0RmVxOVpfMmxiU24zR2M5R2VlM0R1OWZlak1aazVxMFY4ZUs1S0NUZlV1LUxydW1JWHlEUVU4YTJ3eUJ0dHZidHFlcjMyNHBEQ05PTWJGOVRPdGJhTzF5dklFbnpVV1NRdWxmYkdtMXlYMzlOWDNnel8?oc=5
panjang artikel: 1980

Fetch isi artikel:  23%|██▎       | 559/2473 [04:17<2:10:47,  4.10s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxQUGNjVmtHNVFxYmJDVV9ZQUk3WDY2QTUyeHBoeWFuWXpxRGlfUlVlOTd6Xzl3ZW5zLUI0NlpjSWE5dmFxWnVHYUwwSjM0YXBibGZ3YjBORFNTSVhZYllWRjNBQ2FobDdrMllpS25uLWNaZDNnUU1BaVZQZExydWt2aVpZMVEwVkRBUy1qNEVDaGdzZHVzaHhubEkxQWR0NGxqWWgyYlg2ZlVZZTQwbmhJdkRoMW15Tkw2M1JkQkstRQ?oc=5
panjang artikel: 427

Fetch isi artikel:  23%|██▎       | 560/2473 [04:21<2:10:11,  4.08s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxPWG9hTjhTN0xuQ0ZMeEwyMWNsUk42WlJZR0w1VXZ3cHV3a09oTmdNbzg4NkFSMTNuOHF1d29NM0x6WDNHNDI5bzVadE1wVTY5SlRQdkJ6eDhXRndkYnpadlhjc1BOLWRSMHhjQzlVM2hPS1M2XzNkcmpBYndOOVdTcWpzZFN0Y0duZjduT050dnhMWjIxTkQ1RzZHc2xBRllJcWxJTFJkTnhDNTNxaDcxR212OE5MMmE3dER2a3J3?oc=5
panjang artikel: 3095

Fetch isi artikel:  23%|██▎       | 561/2473 [04:25<2:12:09,  4.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxPQWxiOEVGT3hHQl9hYWJYZVYxOVJHclcxTHdrOTF4bU50TXY2R2IxOFlReF9zRXBwSW8xeEkxcU1ySEJ1a3k3eUQtaVpFTGo5QnR1UWJXNVNIbzdIZ2pIaWFzY2g3N0NVWmN4M0lxYlhyT0hZOVBLRGdBYkRadEYzcUlWM2pJZzUtMW82SGJWMVB6N0hUdXFrd0JSaDhKb3RhS2tQbS1laDNNNlo5TllWa3NqQk15RFAxMkVwZGY5RHNXaUM3?oc=5
panjang artikel: 2307

Fetch isi artikel:  23%|██▎       | 562/2473 [04:30<2:16:46,  4.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxNeENvSnQ1V3RCSjRQNVg1Mk1yT09hck93Nm1Zck5QVWtURzdVamIybVFBdi1idGprc1daNGg1LVVDbHAxTU93LWVXR0YxUUNmaWg5TVdqTW5Wam5jeFZPdU1MdmNHVm1FWlp6V0xobTcweE0tTS0xZ2RyVzBuY1lqdFJabTd4U182UWJnQjI3X1BGX05WdHd0Q2pzVktJczVjR3lkbTVJcWdzRkp5dmhwWFAybU1qbVB5M3VOVmlHbnFIZ9IBuwFBVV95cUxNQjlvSm0wN2h1cGs0RS1WVUxhYzBqTURXMHVRbnZoU0wzb2JCeW9FR1VYYlhIQWRUU3NhMlhheEV2eHNHSlJkWEVxcGVTNDVjUW9DTjB2ZzdmUWRpd08wczFJaFhSWTJTbnJSVl9UYUJkMUNqZVFtOU5Fb3NRaHpUSzBGRnZvUnl5OE1yb3BPM3lQcTItbjgzRy0xM3EwRmdDTHliWFN1ZzAzS2xxZG5aNWkyWThQTVVOQnk0?oc=5
panjang artikel: 2767

Fetch isi artikel:  23%|██▎       | 563/2473 [04:33<2:08:40,  4.04s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxQbHdOZXRfcWZWTC0zeGpIajVjMDB6WExpd1VhNDI4b05iTFJaZ3JYVDRPTE8tMGpLbnhxNGRoWkhCUWxvcEZWWmo4Y3hPd3o0Nzg3YkNqZ28tM0xERURVeFFfcldQeUVXYlM5Zk9TWjMyVEpfQWNUOE9rb2pycHhIRFVJaXVJRlFKZC1nUGk1dkQ3SjVjQ1YzRFlNSkY1enk0eEMzcjFkNk5XT2swMEhsTk1vYmY5d0NIM3g3bG1fZTVCWkprbW8tdThWV1F0NjA?oc=5
panjang artikel: 4881

Fetch isi artikel:  23%|██▎       | 564/2473 [04:37<2:05:27,  3.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxQcUFBUVpPUWdmcXNQeV9hQUszSHUyMmZXZ0FxNEtaQmdvUXBPb1ROWWdxTmNvTFZHb0lRMG5HMG1mZ1ozNmhGSTl2eGF2WnotV3NDMmlESUtuczZEYmJDYnVqY3VpcjlmczV1MnlWbnF4X0plOXlWSWtjX2FDM2F1alZ6T1lxczhpTTZPd2ZxV0NuakE2X0tQdVYweVhTWG51bmNHMEtkbw?oc=5
panjang artikel: 1265

Fetch isi artikel:  23%|██▎       | 565/2473 [04:41<2:09:44,  4.08s/it]

Fetching link: https://news.google.com/rss/articles/CBMingFBVV95cUxPeVRpSVZEbTFkdzhFXzh5WlZHc0JZMXhkVFhZbXNySDdwVWJoZ3ZFVjQtQmxLeUdlWVo3WWVlWVNMLWpxZFZEdHZ3d2xaZFRKWFJ2cTQtdkw0dE84MzNRaEhKOVFnNnVZTWN0Zm9GM19HR2lubXNHXzNlM0ZjMVltdndONy1RYm5hTnR2NDNoYS01ajhiZUpMZlZ4aFh5Zw?oc=5
panjang artikel: 1749

Fetch isi artikel:  23%|██▎       | 566/2473 [04:46<2:12:44,  4.18s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxPVXhZTEY4Ri1uX0dGUTZkLXNLWEhZNzIxRFNHaEdlVVpHRlFtOXpLNWdFdnFocVRJS2N2RTRqZEdtWFhBa0dZSmNlWHNOQ0J4VjBQYVczOTR3NEpqendUR3NMVjUtM0ZTaGVLRXNnekZ3VjBYYUwtdGZWRHZYT004Y1hQcWd3S0Y1OWhVbURVaEtES2VkR2FoOXpfaDF5bHBJRF9NSm55TXR1S1c4WV9FUGJGSW9Ndw?oc=5
panjang artikel: 2720

Fetch isi artikel:  23%|██▎       | 567/2473 [04:50<2:10:13,  4.10s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxPNFpxTDBmUUhTMVVGazFNeGhmZjdpeHY5Z1JOUW9qWGtBLUs5YndXQnNlbHB3cG92YnNPNHk4QjVoM25vMVYxUmFESk9QZE04Q2p4Z1RHOFBrQlhWNXdxV2FwRi12S0FLWUtyZkl0eTVFWU9KSTFrMk42anFsdDdoZ3BpeGh2NGFGRG93X0RNRGoyM3FheGJ4QkdSTzRGYzVldDUzaE10ZUh0bTlNZXZTV0daRTZvQdIBtAFBVV95cUxOajdLZUh1MGwtUEh3V1kyMjdQeXNDX0I5a1hGb3M5UDlqcHJBSkVwZ0lPQ04wblgxeWZ2djJraklwNi1Ic1FkZjcxelkybmtyWkl1bFdTUFlUQXlqOVR3M2ZTZUF6ZnRJaUxqR3JfRFZCVm1PeElCRWg1aUI1TVo5d0JHaDE4M29EaHAyMUNnUkktcklpbEZVSHluZmNJRTBBU0FOeWc0WGh3UGZqRXZkbGhyZ1A?oc=5
panjang artikel: 1372

Fetch isi artikel:  23%|██▎       | 568/2473 [04:53<2:03:46,  3.90s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxOanJYTWczRHJ5TUpEQVM4UF9IZVRnWGMyY0J4ak5VZjRQeEFqYzRIZ2hKd2hlTF92U2JMWVc4bG41VHBqTzJYakJXRGpZeUFNRmJGYV9TdFhJM1dreDlvcFRIOGhiRC1XOTk4ZmthbzNhT0YyNVU2SlRoejMxb0xETWdFallkaHJrcXpERmN1dmFaNWd6ZHE5SjZUVks1eTBBcDlvTmlRSVBTdFB3bC1aT0tqX0o1VGUxVWtCUA?oc=5
panjang artikel: 2128

Fetch isi artikel:  23%|██▎       | 569/2473 [04:57<2:05:04,  3.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMioAFBVV95cUxNWVlxMjVmNV9wQ3owWnlPbWdGREoyeXkxLUl4cHlRTUd5aHFMOTEtaktOT2NJWGtNVkF1bnprWnFhUC1ucFJnS1oyWDFvMWZwaHVER0o2Y2ZYWUxJZWU2Q2pkaXU4MjBaMmNIeUFWb0tPQm1RYlNFUUtrNDBXdU1zbl90UEluT3NVNDd4OGtfT2hGaGRtSzUzc0tYOWxYaWlH?oc=5
panjang artikel: 1696

Fetch isi artikel:  23%|██▎       | 570/2473 [05:02<2:08:12,  4.04s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQNE9FWk1FMW9fVUhKWWdmWWxNamNTdnRtQUpmUld6VEY5c0NBY3p2bHNEUmN4VVlpaGRDNUtqR0tsZ1NSbHN5aTlJZVZHZlBjTDdTbFMwY2xaRG40UFU3S2IzTm5YQlpZN3VKTDFqb0Q2bDlOU0pHRFJoVHk1cXNNeHh3WmxhTjczR3REaUVReXRoS3hSMnNUYlB2TXh2aE55RENvbmh2YklnVDRaRmhPN2ZyMG5sM3BUN0E?oc=5
panjang artikel: 4090

Fetch isi artikel:  23%|██▎       | 571/2473 [05:05<2:00:37,  3.80s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxQYjVXMUtjMmN2SGg4VlRwaXJ4WVBjQ1VfLW93Nnk1WGFVdW1WVHZRRWpKVFBNZHJBMHlrSVZodlVNWWd3OFNRb0RIOGxoc25BWThZbDBaUmlWODdNbUJSM05rTndWSXFUWVBYVU12anl4N09oWkJjSWNQV0Nwb0hDMHAzOGtLVmMxNE5QNGh6amNJdW5NZHdzVHZYeFdLVlFnWEtWUTRNbENxQWNYT0HSAa4BQVVfeXFMUGI1VzFLYzJjdkhoOFZUcGlyeFlQY0NVXy1vdzZ5NVhhVXVtVlR2UUVqSlRQTWRyQTB5a0lWaHZVTVlndzhTUW9ESDhsaHNuQVk4WWwwWlJpVjg3TW1CUjNOa053VklxVFlQWFVNdmp5eDdPaFpCY0ljUFdDcG9IQzBwMzhrS1ZjMTROUDRoempjSXVuTWR3c1R2WHhXS1ZRZ1hLVlE0TWxDcUFjWE9B?oc=5
panjang artikel: 950

Fetch isi artikel:  23%|██▎       | 572/2473 [05:08<1:57:39,  3.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMiekFVX3lxTE1GSml0UE1aX01wUVg3czd3SHZtVTVBZ3lpRDVsVG5mTWs5TzJtanpMYzNlVUEzRnBHRW1pZGo4cGphV0YwcjBNbGhvZ01UMDRIU3EtOC1oUjI3T0JIVjBuMHFnQnV0VDJ4NjdENGVZQTBGS3JSMTlkVjhR?oc=5
panjang artikel: 6193

Fetch isi artikel:  23%|██▎       | 573/2473 [05:14<2:14:22,  4.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxNcHZld3NjZFlVc213bjVnLTNmOEhIbmNocjRIM25PYjQ2TldrTUVFOS16QzNrT05GSWNrTGI2WklmVkRzRVRTdktTR3JaR3Bhbjg4WGZGWF91RkxCSHVCY0l5cEhXZHhlSjljcV9tUTE0WXhqTElfUVpzR2ZXMXB4X1l6Y3dwWjZGbEZKUGVOd1dxUmVWX2VYNFc3d2swaTNVVXJDQXdSOTNjMm5QMUh3WlktaFcwN01XQTNMdUcxekFKV19wY3pBVlhzdmVxRUJS0gHWAUFVX3lxTFBLTG0tajRwZUU5MTdVZVkyUm5jcFczcXdBQVFMbUNkekpyN0hRcTVCRGZ1V2gxUGpJMWhGQ095Ul9kQnRERnkwLVA5eHBVMHE4d1J5NENEVExtYW5TTlRLLVdpQVhVclY3WGZFR3R6YXJzMUZ5M2dIajZvQWJXMU9UZ3dNb0dmOTI5M0ROYmJiTUxlRm53LUgzV1FhUFB3YzFaai1zYTIyMC1JYmYyVFpQSW9yeElTeDJxZWF3akxKTVA0Q2hYSVZlbWMxV3lZS1BxSmM2OVE?oc=5
panjang artikel: 3343

Fetch isi artikel:  23%|██▎       | 574/2473 [05:17<2:06:32,  4.00s/it]

Fetching link: https://news.google.com/rss/articles/CBMimAFBVV95cUxQWm5RbU5TUl9rYTdQVUJISl9NQWozX21RdElDcU1aa1YyaXFfbGFNU2VRRWVtcTBuOEkwN2xWY0hPc181Q2tJcXpBRXRUUW5lQ2JjRTlsNWdVeWxaNUU5NUtuMlhBbEFiYnlEQlBXN2oyWi05Y2xYbDVTNXRwNlJCWVlPeXQxcnl6d05jTlRXX255ckxQZ09SUtIBngFBVV95cUxOWlV0TkJYMUdPYWFUWVQ3MTVhT21fLWFOSWVDLVp2Vl9CMkRodGtzcGJTbFp0d1FSNTZnRWVnVHRzV2UtMlN6MHFmd3VzV3JsTjlvbkI2TkZBdG0xdzJ2cVVmdzR3blpoem1mdmxVZ1RBeUdtV0NxbUYyekh5TEJUM0VzTmdzQ0JGZWw0UjBKVl9MZFpEWjZobXgtTDQyUQ?oc=5
panjang artikel: 6270

Fetch isi artikel:  23%|██▎       | 575/2473 [05:21<2:06:00,  3.98s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxOUVR2YmtUWE44cEttYk9hU0pDVjZuVjA3Z2pPS1ZSZ0xCZW9IUFRDUm8zU1VJeElMZ0R4bm1aUk8yd1lzT0JZNGFnYTV4QWd0dW83dzBPeFFtTmR3alk2bmY1TnVMQTE2MEtCd1R6VmtxcFMzaFJSejVCYVlRX0UxdjFFSWl2MTMyWXlBNlpzeTI3LVVsX0dlR1RqUWp6STJxSkhYc1JDQXBacTMxaTZLckJ2LUVqVmN0YmZiUWNvQWFyYmYw0gHKAUFVX3lxTE93Qkk0Z2lKeXU2Q1BJN1lFUFZaVFVmT2Nnczk4cTRjdTh5MnZZRnhHRDFEZDkxSWg5c3ZRdDVFNXVLOF9oVlh6clh3eGdaR1F4U1hIdDZGY0J5NzVtUHlPRW9VcHNrdURpSVlkQUx3Q3ZwaDdDX0NIbEJlcldfakx1Rlp3ZklXazI5VmZyLUxtZVRpUDBrOGVTZXZSUW5OVXJWRkptY1I3SDNOV0ZtQTlMYkZ5NlJ3MWlFZUh0YlB6S3VBWjYtMHMwY2c?oc=5
panjang artikel: 2235

Fetch isi artikel:  23%|██▎       | 576/2473 [05:25<2:02:49,  3.88s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxNUHNiNG5NZDVMVWUwdGowY1FhMG53cENDZWxvZHN6YmJwcS14MXZmMDNFYVJtcDNoNkhqOEo2dVNlaGJJUzJYbVBYSzduMWZDeFFQS1M1WGZRS2YxTmFVRURwVHJ5ZHNyd3dnbFNxTHZUdGs0VGtBUFV1Q09faW5EdlZBb3M3NmFjcUhUSXpIU3p4eVhrNW5uN3YtX1ktSmhGVGRFTzFkYi1WYmFOZW50ejBlMlJWYzEtRGJWZnBWaFpHRW_SAcgBQVVfeXFMTmNzRm43d3c1c3diNHU4aXgxQ3FzZlY2a3VNRXFZS3pITUZsbXc3TDlHWTg0ZWVVX1hTUjU1NkU0azJHcnlZVUxCaUV1c0VjQzc3a1RpNDMxWkJ5cldaMENHUUU5dW1PdG12ZDMwQVdfeFM1SDdDYmJaWkZNcEd3Q0xlSEdOQWxHWDhuUDd0SzdEbHZ2ejloTkRGT0dpSmFfOERRcTdPcVg3QU9QVzBKZ0tmdV90Z0lVNU41MC1wSzQ1WFZ2NzZXRlg?oc=5
panjang artikel: 5000

Fetch isi artikel:  23%|██▎       | 577/2473 [05:29<2:05:06,  3.96s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxQb2ZCanJoNjg2aDBZYU1MZ0ZtNnUxX3d6MGFDaklCUy05X2w4WlJXZUVWV201SmRDUmNhOEFITEpRMDJjdWhYYW4xaS1NLVdIQkdsS2VXcm1MWGVNZWhhQ2xHeU44ZXU3cEtRUWdhenRZWnRubzRwSkx3UTJXanMwa1hva3NLZzQtUzJ2TU1fTno0anJsWGlXeWRrLUw1TGJRU0k5ekVEc3lTZUdfNExGN1RVLXFBZkxH0gG-AUFVX3lxTE5qdTlldDVQTjZWMW43NkVhaS1uSl95b0lQamRFSlp5ME1OeENMSFJuaEl3cGVBdDlPbkkxYVIzNWE5aDM2SFc0ZmxRRVpSc2pVdER5N2tZcjJPWnpmbzBnUDBYa2hWLU8xdUt5ODB3VlNyS2p3Y2M4TjVqY2ZXcWlVTW01V2V6emI0cWZFZ1lub2FFSDRpODVqTmVpUWxDa1RrWFpmZ3JsRmNWemVRQ3FqV1NLcjVDdUNTc1l3QkE?oc=5
panjang artikel: 5186

Fetch isi artikel:  23%|██▎       | 578/2473 [05:33<2:09:30,  4.10s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxNVGJmeXQxZlk4VFZ1OXd2UHBxeXNjdV9jRDJTd1MxSzFXOVBhRXVpa29JUkVyVWZVUThXdlNpUUVJa0tUM3p4NmJncE9LVllvZnVSaFZvQnZrOFVEbUVUMzRDZGJmeFdXR2N5Qm9xY3dWemlCYnctZWpybVFnQ1BMOWl4Rm5BcjU4TG5Mb2VuQVU4S1FKUk1pNURQcTZDQXNRdGVwWmxVWXRxWHJCU1lNSnBRa2MycEJPcDBIRHNZSmxaQXlxQTk3Ykdyb2d5Q2_SAb4BQVVfeXFMT1QxMENVX0FVS0lSYm5YeThsXzB0aXkyMUYwNkw0aVBkRUpNWWJ1YTVVRndzbWgza1NCM0tGTnhObVlEbVR3WkRPWkxjTGFJcF9sdW0yMmpxaTVnRWxlTlVYYWNsbm5BVzVJcG8yczFZRlNvNGZMYjBfNjhPSzgydVRVMEM5VkMwSmw3dHhZZTZvX3UweEFrQ0loOFdsbFJkMTNUT01QdTA3X1ZtRE9Tbm1uR1NMX0Y3cnNGRmROdw?oc=5
panjang artikel: 2388

Fetch isi artikel:  23%|██▎       | 579/2473 [05:37<2:02:47,  3.89s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPU2I0Zm9OOHVCLUs2Z2NFX3dsd3hid1J2c0tlREtxWkdvRjdBUmhEcEtVNkRNV3pfa0VQZDZmdTlrWnFFUlNVLVZBb1ZPMTdCektnX2hCX3NtclBRR2V3VGFqZ1czTnptTjY4WGxfRS1QSlVjQUw4OEJEOE9RcjhRR3lBdG9kSE1pTjVfTlhVQXFzT1JHWkxnajdEYlhhOC1UVnBEMnR5TnZVVDdIa2NWSzZ30gG3AUFVX3lxTE9xdmppYUxHcFlXRFNzRFRkTGRMSlFmYlBiUk9RSmNnOHgtZG01OVZSb3lGT1ZqQjBaNDRUcWlhaGNHbTQ1Vk1vMlhYMktxZFpoalhFM190dzdFNHZvTWF3d1o3QmJtWktaQ1pDNkpsekRvYmRGbGVkU2p1Q3NXQjRvaV84OFpCeFp5ZDFFNjZWYkdZZ1pkZ1FsSU56UzRFZllaSU85UUhyM1JNMnExQjBWRHZBaUJqOA?oc=5
panjang artikel: 6112

Fetch isi artikel:  23%|██▎       | 580/2473 [05:41<2:06:22,  4.01s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxPb000b3BxeTNSZENVS3htWGZwTjhlLW9NUVRZX0NKN05FRjJrNGJHLTlMWTRLRTREUTdldEdWWmVDS0E1dW5RZjlreHRFa0RHS3o4YkRFeGRSclE4VXIxQjQxYWJ4VnN1X0lsNlRueXZHY1NFQW1oZkJZMGNwMlc4WVVJcHFqU3Nid3lBQlRJb19nNFZlNGpaV0FIY3ZqTi1VOG5BaXhfZjZWSnfSAaABQVVfeXFMT2NtaFBnNG84OF80OTFRdXFYdzU0NHh4Sy1yaFlGZkg2RUZVR19FM19hOEJSLWpOaEpSSXB4S1IxOTBlUFZPeXNXMFJ2WXBaUUhDc01JaDY5MHlyaFczRTV3VFFlZjROVk5oVXQzOW9Kbmk2YUw4MFRTTkRCV1pjZWpHdWFfaEhlMl9uLU1hSlJnRmc1a0Z4alN4SlBoMWxKYw?oc=5
panjang artikel: 4872

Fetch isi artikel:  23%|██▎       | 581/2473 [05:45<2:04:37,  3.95s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxOZTVCenJZaE54UzM0dXNfcm9NbEJRZDRiUVNsV2Jlc05nNk1mWHJ5VlNhbnFzcjVfd3hNanZUOHI2d1I0dkF2ODVVOHR6aHdSR3NEQXRfNlJrUzgzMzByaDEzQzBLWGVMa093cEpQTkk2THVWcEVXRmlyTUNRdkpaYVpaMzAydUNkR1RZYVM1X1UzX3F6QzNZX2FCZ0lKbWg2cklGN3d4WTAxRjZmNGIzVUxB0gG3AUFVX3lxTE1EVjVveUtoTVdxbzJ3LWJ2UzUzdzNFc2t3dDNDQTY4aWFVTHJFb3BCQ0h0V0licUN0VjM4NDNVSGh5dzhUaGt0akZIaHA2eVpqNElTck1qVDVBWGxVZUdnWEhsZ0hraEVQbUE5SzJLS3Q3R2poM25kM1NXN0g4SWdqNVhOb3oya2h6Q0k4dDk0YmQ0R1c5RWlxeTUxTkVyT09xdVFVcnB6U1FaZDdScHdGMlZjcE45aw?oc=5
panjang artikel: 3371

Fetch isi artikel:  24%|██▎       | 582/2473 [05:49<2:04:48,  3.96s/it]

Fetching link: https://news.google.com/rss/articles/CBMihAFBVV95cUxPT0ZJaXlOSEJIX3oxYVJESktpQTgzZHl4N2pzR2NlT29xQXBlSmNybGlhSGotMC02RDltUmEzSmxjeE9JSm1hVUVQZGFqUWdXakRXVXJZTW1leEluV3R4Zy1fYzdpb1ZjOThmdVhJQ0dxMnJON1BkWDJoZ1UwRDF2Q2ZaQVI?oc=5
panjang artikel: 7284

Fetch isi artikel:  24%|██▎       | 583/2473 [05:53<2:08:56,  4.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxPVUQ5dHJ3VmNWaVFjMUduRE5JaVFkTmZSUHlxbHlkaVJPbUllR3FZdnRZWjN6emJONnhzUGkxQkx1eEExYXVwRklvSEhCSFhFdS1lNER5eFlvdDBEb091T0sxRUN3UGVSX005TEU5cDhObFVhR09QSXptcTljWXpJcng5cVNySmIxU1VhQWdlX213bWcwOU1VdHd6OHc0eVhleTZZczZ5Z3ZkNmhE0gGyAUFVX3lxTE5ISU02OHZib2s3dUxhM3R6VUo0c1c3MTNxcHRmSm1VZmZ2NGJMbEptOEpKbHlLcFhaUGlsclBjd2ZvUEpCNHVtcjZNSGpnMURibE5nSGVuS09uQ0Zrb24xNE9pRXBmRDBvenVGQWVLbE5iYk03RE05cHQ3djAtWC1wenZnbnVQWjdZbC1la1FHMDJDVVkwTGRudjlRaWEtUTBZU3RROEc0UmhKZ1p3SHFYcUE?oc=5
panjang artikel: 3915

Fetch isi artikel:  24%|██▎       | 584/2473 [05:57<2:04:24,  3.95s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxNSFFvUGhkZ0hJSnNvMHlTM25CVzB5OWZfNG1idlU3YnIwbHpiUlpkMjlZalpzOWFoc3lIWFNBTV9abExyR2E5VUhoeFF3YV9PeURab2RoLW9aZVd3YWZtdGVJWGtkUTBseTdpNndKUHlKZXYzWGtjbWpGOFlkMXhHLWRZRHpYa1BCMkp0TlVmeEU5X3JmZy1fSzhCSkMwX2pLU1NocElPV0dZX2ViZDViNl9SSUTSAacBQVVfeXFMT2lRX3QzYk40WnktdHZnc0FzQTA5dFpaZzBqX2E4ekY3aEM4U0ZLSmNvbVRQNGVEb0ZnWE1NdDJlMXZLbklqM1Vwa2d3N1RXLW9INnNLcHpOekpPQ1lReWhFaHNRTWhQUkxmR25mNE1oLTdPZlFBRzMwQmtCLTE4OGtZV3RQZGVEaVhaOGY2QUl2bXNqVERvdnhXbkcwbVhFM1VzYTF6ZTA?oc=5
panjang artikel: 2743

Fetch isi artikel:  24%|██▎       | 585/2473 [06:00<2:00:01,  3.81s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxQcTM0dFZnNTR3VFZ2d2hDbi1RVGR3SFFKZXRGR3F1blN1M3dqWEU5UEduUThyRDNHSHkwaUpnbDRwbVlWd0o0cmRZWDF1QnlJUE9mNFp0ZXNhMDZ4Zk5ReEJyTFk5U1lTZm50NjNmdlVQb2JXYVp2azc2QThCT05EOUNYUE95ckhSeW1BNkpXSVdKZnhaZHFoWHpBd0swTDl2X0NyRld2TWx5OFBoWjhzdWs5MEZKckstOGc4cWNKRmVTSmfSAcgBQVVfeXFMTXZUZ2pZTjlpTEpuSUV2aGJnYXhDdkZhTjNrdzYwQXRRRU05bXJOSFVWNVBWOW1ObzhlMkdDSjBVTnJwakxMRC1tM0RZalg5cC1GemxyYkdWT3VNTjlGZi1wUjdEaWxGa080NVRrR0RFV2l5TVUwOWdlLTQ5b2VOM0tzU09hdEZqSXBkMmdFaHVPYVBRUW9BMkNLYW1uVC0tM3pBTU5DbEczWkdnRGdnbEtzRzBNQnF5QVFKT0wtN0QtTm5nMmRVSmM?oc=5
panjang artikel: 2601

Fetch isi artikel:  24%|██▎       | 586/2473 [06:04<1:55:28,  3.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQOXRUeGE5RFNFX0tnakp2TW42cGNCUkE2QmY0VVFoblhxbnBWT0dKSGJzS3hzTGlzbjQ4eERoOW5iak5EVUxTWldqcjltNVdqdVh2bVZwYWVBbElJWjVWNjg1eU9FRjl6Qi14c254YmFMQ2FPQzlNekhYVFNMUmhMWGJ6bHdRQy1QV3l2b01VaXFTUFBpMHl5QVF0ajVmX013V0lyN2x0Qzh5djMxaWllMlp6SUk4ZzJxMkHSAbgBQVVfeXFMUFNqMjJadWpxTHNKT2ZVQVN1MEJ4V3FHQ0p2YmotSE1OTm1lWkJhZlcxS2RvTFBnY0NFbEJLcWt4Z3FKdGRPVXJxWGpYbDNJMlI2YnN6NTdaWWVvMkgtdWExVjVwUUhkblhTdk54UlUtM1E2Nl9rc09zVmRLWmJKQUlhSFVhRTg0U1NQMW1TUWpMWnJLS2RNak9qQWhGYktLT0U5WV9hNzhER1pCNHphRTVqUS12ZzZORg?oc=5
panjang artikel: 2171

Fetch isi artikel:  24%|██▎       | 587/2473 [06:08<1:58:52,  3.78s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxNQzBsWkJEY3pNWEFLcXF1SDdFdXgyVl9OTS1qd2tvZ1VJVDcxQVlqaFZsZmlDc0trWW1SdmJMb2prNkVTU2EyY3RhNHJIcmE3SjJYdEh0M2dqOTlleERlSGlCRGhybElHVDIwOUp3d3FvY1l2cTBpNFlUd2VpQVRZUjktbWNiZ0FNNlVZVDNOX2dxVlZvTHhDcWJjSUR2R0xLanl4czh2YVdLVk5udjZyZGtB0gG3AUFVX3lxTE1Nc1I4LTFhM19aczcyUW51R1U1RTdjOFo1UGk3SlN5VjN4NnhieWNsX0JiRVdxMGJPSUh0cjJ1Rjl1X3NCYmJqXzluTmhlb3NjcHhzRmNKUVJVY3pUa2VNdHduaENnTHV4RFpYbjhCVTVfV243NWNQdnRzRWpNcGJ0NjNRWlpXdldCbGxuMW5PQ2NxZ2FZd2dmZ1N6LTF4S1BoczZaYUFHa1F4VFJsSlE2MGw0YlA1bw?oc=5
panjang artikel: 2135

Fetch isi artikel:  24%|██▍       | 588/2473 [06:11<1:57:34,  3.74s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxOTkN1Y1p1d0ZkQl9zQnpfanA5ajllLWl4MnRfUVNqT2pYcjVsMGF2VWFpREgtMzVIRkVUYTJHdVVhNHlxWXpxZlpMZ0loWldMWDhaRHF1MjFPZmFYeTRPMzRmSjdwTjROM2U1SGJHdTd5RGhIMTR2RWZGSmtEZWlkVHNvQ0hzQ0l1d25fdFEyMUhIY0NaV3BIY2l6Zk5wemNlM1lkQjBIbHZ3WHpuTHc?oc=5
panjang artikel: 1865

Fetch isi artikel:  24%|██▍       | 589/2473 [06:15<1:55:38,  3.68s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxOSnJ4Mm5rNkJ4aU9tZ3JlTVpybXVDVVlVWGFRNmp3T0R2UENxZFowQ3BwczRGZVNkdXI3NjdTMUhlOURrRENYUGxFc0o3bnV1R1ZlYmNPS1lmejBUN2Q1TVAtbjVUQXVHVkI1dGk3YWxxQUdfc2VxRDdrV3FqOWZPcXE1U1RhS0h4OFBWYjZSX1NsS1czTURUY2hqb2I0THdycFRQRVY2cnpPN015Smt2TlJn?oc=5
panjang artikel: 2830

Fetch isi artikel:  24%|██▍       | 590/2473 [06:18<1:53:16,  3.61s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxPSmNtektsQjBzaGdUcVlkQVBfNzVkOUJTeGdfMGxrbzkyYkdHSjh6c3k0eU1NVW9OYkNueC1qcnB6VjUwNkUwMVhMLUhWSEU0MWNXam1GcVpUa0JscTcyZHBneFJvd3c2bEdFZjV1ZTU4NlRpS0FkMXZoZjdxUWRVMkJFRHJaNmlNV1FFMmxWME1ZVmVickdWWml2bkhFT3hYT2FldzJYbXd4YWZpNThHSmduVnZLTmJGZURBT2VqbHY?oc=5
panjang artikel: 548

Fetch isi artikel:  24%|██▍       | 591/2473 [06:23<2:03:45,  3.95s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxPdzNRbTZ2VUxDRk1IQlRIbXBfdjF5cUtTZUd4Q0tnMmp2Z1d5SHkyNWcwNUZyS2lYRkpIZGtwU0p1eTdpN0hmTUxJX05Wd1FSVDJHa0ZMVzQxanBhSUIzMjJ1TDJFck5tcmo2OThFQUM5TG92X2J0Z01JaE52eUlfdkh0dWxaY0J2eURGc2JXTzZrQ19XajV2bjJKM01HQzhhSDEyQ0ZtV0R1X1Q1NDZ3?oc=5
panjang artikel: 2194

Fetch isi artikel:  24%|██▍       | 592/2473 [06:27<2:04:40,  3.98s/it]

Fetching link: https://news.google.com/rss/articles/CBMimAFBVV95cUxNZ3U2TXl0cDlobWh5eU1yWExHMVQ0NUVIdTB0eFFsdExnNERVdmowNHZXZnRrR1RVbjRhNFBoaFphQ2hranJ4RlBFbHRHZDdWUXhpemRTUE9zeDRlLURvSlJrX0FpZnBrdGpQV1FaTmk3YWpaN3JndExiaVhZM3dmNmN0aU9JNl80NHlJMmVtcXZBWUNST29TNg?oc=5
panjang artikel: 506

Fetch isi artikel:  24%|██▍       | 593/2473 [06:32<2:15:22,  4.32s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxOM0pmX0pPSmV1OFBEVE9RWFJNdGJlcVc1NjcwR3h6cU1GTUhaRkpCeTRRY2l2eEpDSmNmMWh0NHFhWVhzTzR3TWZVRXNpN1VjeThCR09VMEloc2Z4SkYySzhnWUZEZFIwSzYyNGVua0xVZVozN3ZENDdlNVlxcE1VMF8yblJhVXNwVFNJdzNhOUFONmw1YTJZSU44M0tsVDRWd1pWZUdrcVRxMm5tLURkemxFRnJIWWVLX2tMZDNEdnpZUWo0?oc=5
panjang artikel: 750

Fetch isi artikel:  24%|██▍       | 594/2473 [06:36<2:07:27,  4.07s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQM1hibHdjZ2VzMWdFZXU0WlNNTkw1VV9ad3FTMnRJTF9JQnRiUkVnRTF0eWhuOV9GWWlOMkRXc0xrdkE5UEhhWWgtTWNFczZZTnkxMmw4cmxnUlQxdVg1ZWlEWGxPU01xSUZPT0ZCU181SFdLWEpfSVBYWGFKVU1QejMxd2NGb2tBVlVJZzh1dGpZOEdybDE3aXRIdXZvaUt2UDF5UmcwZlU1ak1XZVQ2MDFEVG0?oc=5
panjang artikel: 2463

Fetch isi artikel:  24%|██▍       | 595/2473 [06:40<2:11:21,  4.20s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxQeWI3YTZnUC1COTFJZlBWZDQ5cEVNUDkteFRoTF80TTNxemRoTmFob050SG5wS3c3aGNQMVJFUmtzenFkNDV2N0VwYW1IcW5XSldYMmxTeFhOd0llZTk1aXFmemNrSXNyTjg3aHJqLUJrU2xkRG5HRU45cncwelZkeW4waHYxVTc1WWY2NmNxQXA2X2MtcVRyZ2p1ZzZsYkRyUFBIN1doLWhndlRQMjYzelU2MGpBaUhCNXUtZGVDeXrSAcYBQVVfeXFMTUFqZXBFdllhcC1YV2NXU0V3NXluZmVsMlZqcHFRM1JSelk5TzNNU2ppbUFDMzFKVlhrSml3WXV1bmtUbE9HdWx1M2t1U0lxV1p5c0hoN3lPTEl0ZzdNdmtQOG5CeldHbzdQT01wSm5JYVJTLVgzMGNmcU5sUERyclhVNi1KSUxURm1uUlNGVmRPV2NINWtlZGhkMkNRNEI5eF9zeWd1UWpRdXFNM1AtS0hvNHhCeWg5Y183M0ZTNTZxTDhpX2dR?oc=5
panjang artikel: 2514

Fetch isi artikel:  24%|██▍       | 596/2473 [06:44<2:05:37,  4.02s/it]

Fetching link: https://news.google.com/rss/articles/CBMiYEFVX3lxTFAyd1dNZi1JTkVNTVRTb2hmczAxU2V3MzQ3SkJCNGt0NE1xdkFuaUJycHRaalRGLXV2NEJIZUpZRnk5RTl0OWM5bzdNXzlNUklMUnZEMFU3ZGNQZVZURWdKSdIBZkFVX3lxTE53Tlk1Vnp4bV9yMXRJMGVsUW5vRDBaN0k0bFF4QXZXY2k1MmxGQkdQd0VZdm9Tai13MVFCWGNPT2xIVmZBVXZhblZUNU1Zdm1OazZxMC1HZ1lXczJ0WUdZUzZMbU1DQQ?oc=5
panjang artikel: 11643

Fetch isi artikel:  24%|██▍       | 597/2473 [06:48<2:04:17,  3.98s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxPSG9CbnZ3eUI5SjhyUjNHS3NycU5RTDNFVDZBZTR6dkZETWtZWlcyRkpTcGlaVjRiZkd1MkUxbm5RVVFiMFF5akZfZFJQeUx3QTBUOWZJTE5uMVJLSjExbjFsVHE5c05uX2NESjNCSUxqRWduZTFjWmtLZWM1S0dJNEhxTkpaYXlMSG9fMXptU0FoOXY5d1hMamRWRTcwSWVRNndURVhJYmVXWk1mWTJZTktOaWpya1BkTHpB?oc=5
panjang artikel: 253

Fetch isi artikel:  24%|██▍       | 598/2473 [06:52<2:02:50,  3.93s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxNS0dMeTV2T1MzZHBBZTFEVXNldzlvTHh3MmpjcmJSbVlMeXlHZVJqcEJjN054UXpHSGRCZS00aHktaFAwVUNGVEw5LVlCTzRVS3BHOWUxdXQ0cGRqNkZkWkhZMlpIcEFyUVUzYk00TmxjQll6VHZadmxBUkhFNG9xcENHenFSQUdYZUNHeHZDWE5WWF9YbVhzY3FPQ0E3V2Z1WU9zZ3YwZ1NqajRmNTJvNFZtcGlHQlgxRm9NWnJuNXFqWU5u0gHKAUFVX3lxTE85b2l4TGxmME9JSGRQWGJiNkIyRWFvSFdBRXV5ako2cHBGcVV6TENaWkVtcmZCaHZqNVpzN1lQOUxSRUg2WDVfOV9DdmVOVEYtcWU5V3dfd0YtcWhVc3FwWlF1YkYzenI2aWY4NGF4VE5idnZVMmJjVTMtc2lWTDdEUjhmWU5UbUdVQW9rd19PR1hZUWNLSXVVaGsyZXhCY3hmaV9rM3F6TkNCS0UxaDZvdHJBUDlwZTNXSGJWd2l4MlRxZzJCR0RTT2c?oc=5
panjang artikel: 2343

Fetch isi artikel:  24%|██▍       | 599/2473 [06:55<1:56:03,  3.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0gFBVV95cUxPTzRFazNQZEFsUG9hMUtHX2szV3dWV0JZU1Jvd0lZdGxHSzVmZnhLNmZoa3dHNTV3bXh4RlptMHp4d0NrZnNLMnJtQmU0dkhEUEFVS2FNUmtteUd2c090TTJhVFI4RVFWUlZQOGJ1UUxsaWdfTHN2WHA2ZTZhVXJyZEpCS0RHazVpck1zcVVOaWFDZzN1eG9ockRHRGx3LWFUQWxseTJKdnlkYXRNWFRkT2M4THlGYnhtVnRINzRyVXFkR2ZLOHJXeGFQaGdoUlQwZGc?oc=5
panjang artikel: 3569

Fetch isi artikel:  24%|██▍       | 600/2473 [06:58<1:53:57,  3.65s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxNVG56ZVJUUExPMnY1TjNXR0JwcEQzMGE2SG9DVEY2ZllYN1k2WnhqQlNSaUc2ZVpDY1M4WXotZlZkNkxySWs0cUU1b25kSUVGRHJYLVEzNHpnX0ZJZTkweTBWUS1ycjBSUGgxODItdEdleFNqcEtmbUREbHNoSlJDczI3VG9kbzVjSFROeFJONlppZnJUak9JbVJjQ3BOZDduNkg1MHd3czdOWUJKd1E?oc=5
panjang artikel: 0

Fetch isi artikel:  24%|██▍       | 601/2473 [07:03<2:00:01,  3.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMingFBVV95cUxPZGZNemc1MTNGNzRBa1Z2Y3hQUUxZVlBfSXhpR3NIWG9yNVdnMk95cWgzNHRSWWJWLUlWenBkM1pZQm0zM2RYMko1Mm9mbGlQZHMxSVBxNkdIdkg0elJqYXF2STJKSDhXWGM3YUpoRlV0TTRpZHdjcklrb1BjSHhyRWhGQjJXZ1g1UHFuMzg1U21ET245ZV9YejlMdWk4QQ?oc=5
panjang artikel: 2623

Fetch isi artikel:  24%|██▍       | 602/2473 [07:06<1:57:39,  3.77s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxQeTNCbjJ0Nm5QZWhGcUJOUTdXYjl2Q0lNeFEzY3NTNDVFSkY1U082QUxQdHlpeHl4cDAwOERYS2xXdjlNNkkxYlZqc0Q3MllST0ZQNmhBQnFSMHBNTVUydVVFeTR3dlVjZ3hrR2VoX0dwbm5oenQtc0JHcEhKS1JVWEQ1VTh0YTZHM0ZJdndjcVJMcWZCR2JsWXJaMVN2YWVkNkpNeklCTllqRXdzZGxqUFA0N0VvZUpPaGdjTjg1c9IBxAFBVV95cUxQVFBkVzVXVU54SFV5ZEhOTHFTV001ZUJIekxFWUdISFF5R2dWWllZX0YwY2xiY2RuOEJJaFVMWG9sLUZnX1ZhcjBCNGtwQm92b0YxNmRYTFlTeThnSjI1MEYwYl9WS2tlZWM5VjlISG4wSHhVbHNsWDJYb2xxTGNMYm5QQzAxRXJTbGhhRmFldU4zVWRnSzdCUER5OVZPbDdsWFZBQjBSZEMydlVRZ1ZIMVZ5TWhsQjNOWUFSX1JJTHhzZ25Q?oc=5
panjang artikel: 2272

Fetch isi artikel:  24%|██▍       | 603/2473 [07:10<1:55:39,  3.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMijgFBVV95cUxPb1hiYkMzM3dTeGZUZmIybWxyUXdudEhpMHpvdzhmcjRmMlJLOWl6UXA5NWtkMTlEbFpsVzFMeEVVaFNnRUVQcHpfSFg2M0I0YmZXbjZEamh3bGhOY1hQZDN5S1FqME9nNEtDZjJMbERrWlYyS0wwMkwzdlRSaXdsc2JOVnF6MHVDU2RqVzR3?oc=5
panjang artikel: 3645

Fetch isi artikel:  24%|██▍       | 604/2473 [07:15<2:11:11,  4.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMi5AFBVV95cUxQREo2SHlrM3pQM2RoZld2TWRiZlRnVnBJOXNqNkxwSEwxMkJkQ08xYzRKN1czV2xPTW51MlluV1otN3dLTTN6Z21tYVdXX3FOY1Q1cW9zVHNtd3lPa0k2M0hYRmlqY0JwYmo1dS1xZU1ISTNONFcteER5YTBCNUI1cXdXb0tleWxMWEVpaF81VDlELXNPa3otMjJOMGVkWmM5V1N6bWRGRDJkeDRpc3VOcGIzTWw1aTBVNkhDMGY2b0VKeXlrc1dHUUFKa2VJb3JWR1hzUzRacFVNdFZ2cnJUcGEtb0vSAdcBQVVfeXFMT0FCQnFsZWlrZFRqVjRUelBadWJzVUtkcWwyYThZS2swbHRFWGhDeEFoSlRQbVJsbzdrVzA3QkkzZC1rRlljSzZPdDEwUmJjZUlIZVFjQV9hcFpLeEZwNThhSmlIdjhMbkJtMjFwTmhZelRLX3V1bnFkTUlQM2J3VGNhbW5mMjRBTk44ZC1DbV9fdVB6QXRSRkU2Q0h2aWhVTTZubncxWGxlM25NMmlhRWMydkplQnl0NFVtUEdYRW4tS2hpTFpQUWJxZUJFMGtiWF9RNE5FSkU?oc=5
panjang artikel: 1494

Fetch isi artikel:  24%|██▍       | 605/2473 [07:19<2:07:13,  4.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxQNnF5VnducTJON2Iyb0JrdkR6ZGg3cVF0QTNXWTIya3ZGM1VoaS11ZVhHMDhHb3NqeTJnLUE1bU9USEhVMk0tbERyUHdPb1BSXzBvY1VacHZYM3RpUzVhVDJ6TVZ2Y0ZZclJybXI0MFphamk3S1BrN1VyOG1yemFwTklqWDZ2SldBZWhWSHJXaUZFamtObXVKSkthU2o4bmRieUFOa3Z2RDR1RWZRUmM5eDNtOXlQV2ItczkzU3VQVVMzWTNo?oc=5
panjang artikel: 4529

Fetch isi artikel:  25%|██▍       | 606/2473 [07:23<2:09:06,  4.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxNa3VKN29IOUIxalZMaV81b2xrb1cxVXZqam1JOXM4ZkhEcFZCS0lEOEJTc08tT2pISks4ZGtHeldRU1ZQTjc4d1pZOFZwbFBDanJ5RUZpNGc0c0NJaVZUTC1GWXFsX056QUwyVWxGYW42NjRUdjVqNUhIY1pmWUZ0MjNOSVJnZVRpMVRGYWp1MFRXYWhfbkJ5YlBXaW1md3p1S1hUMGlrckQ4a2dyMlJWNTBMdnMzTWc?oc=5
panjang artikel: 2120

Fetch isi artikel:  25%|██▍       | 607/2473 [07:27<2:04:59,  4.02s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxPbTZGUVgwQm9IV1JwVWFBNzR4d1dYVnpqU1k5bXVGSFBZZEFaYlB4eWMyM3VCM3NSc3ppVWk2U3d1b2d4azkyRV9QTDEtY1U1MmlZUDFaMzU3REpFbE8tdFdJZDRYb3VsTDlCTzZ3MkkzcC1DMjhIVVIzLXhiaGs5ZVYtQmE4WnlmNndBbzAycEc4cG1KNDMwSW5JX2gwRWNncjRyNjhPQndnZ0lzMEVlLVlJSWl1UGZwN3RSMXo2UzBCYUVzbk1CQ3RZcWswRzjSAdQBQVVfeXFMTXltVU84UU1IbkJVM3lSLV9RX245aU8zYnpTMGFGWnVnYXhlMUphQU1kRExTY0hGNGlZRVoxMjFTbkZEdlRlRlZRamxDeUdhZndsRC1oc0pFUEUyNUtpWkdHSW1acXhkTW1NZGN6Rnc4bXFMT3BvVE00OGthdUtRSUNUUG5lczJhU0QwczM2WmU5Vko2V0o4V3Q1V3p2eUhGQ2pxdzJmdkRkVG9pWHFqOG5yckRWZnFWOEhseTFNNmVjRGhtMUhSYXZJVUJYQzlacDRhemw?oc=5
panjang artikel: 2336

Fetch isi artikel:  25%|██▍       | 608/2473 [07:31<2:03:49,  3.98s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxNbjlTamN1VzFhUFY1Njd4UUxyR3lnelBHRjFreGZhZXdpYlUtUWQ1Tlp0QXNrbmtsZ0czZ1RubTRpSTlHQnNMSDBVSzgyTEZULWtab3lkQVAtMXE1SVVRWmZIXzgwT2F2Q1RTWjdoZEZIbTVaaDVIMVVSSlNnV1d3bnRwQ21oMGFXRkw3T01rSEd0VkJYcFI2QU1LWEw2bDRudHp3MDg3R1NUT0xlYldMbzh3T25xY0NvaG1ueEpxMlBkT0ZuaVE?oc=5
panjang artikel: 2933

Fetch isi artikel:  25%|██▍       | 609/2473 [07:35<2:04:33,  4.01s/it]

Fetching link: https://news.google.com/rss/articles/CBMi4gFBVV95cUxQMDlfbVhUNEVyQnFPZ0ZTVUNZQ01HMkFndmVTRXpkcGtfUGhUZWdxM2xhODVSV3VTTHpFczF0SjJfYndWUVg2Rk1zUWF3UDd6dUZ6SkVUNTdrNVNZbmI2OE95ZnYyRmNfSV92dHltUVBybUJ1LXh6dkNXU2FXX2tTOGsyem9IN0hSMzh3SFZWdWJyM0hRcFdTRUIydHdCWGx1dUFFWDNCMVB5eGFlcHA1SlhYeFFNcjdhOUFqYWJjajZRa0ZFSlBIb2dndGJMX1h3bHA1MlBuSnJNUEdHb0VPa2pR0gHMAUFVX3lxTE5hNVlpTTQzS2VjNThsd1VvbnM0d2xYaFNmRGxTOFQ2TjRwbDY3cTQ3b0trUzJsc2NZQ0tIZDhZbTVUWG8wdVFtXzZDSVRyZHZXUFVsZGhWdkpUWXpiUTFhU0Zjb0xKbzB5ZlZFVjRFRDkwNERWLXlIQzgxYzcycS04Nl8xVDVMNnRiVE0yYURxUVk0Mi1qUzItLUVvYmZvSUFtVGVtSV9sbF9GRmotMnlZNkh5WFN5Qmg3S0hPeXpWdGFpeWlReFdsejRpQw?oc=5
panjang artikel: 3516

Fetch isi artikel:  25%|██▍       | 610/2473 [07:39<2:03:08,  3.97s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxPOU5zY052a3hzSDBzMGZoTU1tVnpnR2FaVXUxUVZ6aHF2RndibGdqUHo3d1NORTJUeVVVLWhrNzFaQU9ONVZIQXJSbU9sQzVvQ21yZXlHeFBCd3UxRV85aDVlcVRhS1NkalVydUhJd18tR2d3cjFVSFo0NFRfdHBiM21PMVd1d3hSSV9sNEdkMzJacEpPdzRZcHhKdjh2LWh1LTlOLVhjZmVFOXJDR1pFTGVlXzAxNjVIR1hvZ0lZcW1pdXpyaE1V?oc=5
panjang artikel: 4328

Fetch isi artikel:  25%|██▍       | 611/2473 [07:43<2:01:49,  3.93s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQRG52cWd1T0xyTGN1dVZvblpKUktEWmRXb1FoSXdCcktaVXVzQVJRTHlycldLQjFYc2VKTk5KZWFkZ3FlYy1ueDdnTng2cm51MVVBSldBeVp6ZkZRZXVpbEgzNW5YdVQzTFJpRjFrNzJPOGlqX3QzT3BZR3p2ZnQxV1ZXcjczQUpRT3J6M1VMRnFVUEpiendkWDc2T2k2SThIQUh0bHNVNVZjRFd5ZkdNalpvN1I?oc=5
panjang artikel: 3490

Fetch isi artikel:  25%|██▍       | 612/2473 [07:46<1:56:50,  3.77s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxOc2J2TEVFc3RSb3BPclRzTDd1czNXRndGU2NiOXlwaDItNVV0Ty1IZFVIbFZ4a3Jxc3doeUE4YXRKVEdveE5Td0JtOGpIaWFJUDQ5bVhIeHRjNVV6UUF1a0tLVDhPWXNzdHJaUGxHZkVvR1FyY0VoNnVYanZOLWI3RUJPSnZqMy1iNFVnV3Q4SEFlVWtORVdJNWpR0gGfAUFVX3lxTE1YYkpNZ3QycFhMQ3JCUU1ZNkljQzViek9nVXliQWsteDJOUXZiSUVBRTd6MFpROVU4Sm90TVhsa0JmS2FNaGFjN2p0ZEpxSnpTU05POVU4M3dXZXQyOUhXUFg2cVFDdUdOOEE0X2VqUFJHRVhMUlhtZHg5cmdaNEhPeGtySzRhN2ItZ2dkOGFMTWR5ZWQ4SnNRZl9EcDJ6dw?oc=5
panjang artikel: 3459

Fetch isi artikel:  25%|██▍       | 613/2473 [07:50<1:58:51,  3.83s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxQMVRQVFg4dkpRWTQ2Z1lSVDRRaklVbUoxMmVZNXh0TTRKR00xQWZtcC1WSG03c0dxUzZUeTlnYi15YTRIeEFwRUVfUmdDcWs3UERxdWdLcndKcWgxSEdKWTFmLXh4Q2ttYldyaFlUYUg5ZkIxaTZ4ckJ6SWUxZDVPNW5DeTZWeGs3bFpQTzI2MVNaaFpuSkhGMW9KZk85TFdBQnl0T1RuQnNndlVlVlhUNmtleFQ4MXBGcmfSAb8BQVVfeXFMTzFZYkxiMXR0VnY3QmZ3aEpwWlRFLWlCQUIwTlptZ05YWDdWRE5KMGxMUHRKeFNySUZSUE1VdWNYX0NzVmJJUTc2bTVMcHB3ZXhXcXAzLXU0MHhDTG9lNE9mZEN0ZFhFc0pMYnpUUGdxMTBWV0lkRThWZzJQY0FnbHRudmotSzE3clEwNi1VTzJhUlY1eUhzVzVZcWp0TDVna2hrX3hxNUtOOFhNeFJsTm9vaXZfZzIyTnVOeVJDRVk?oc=5
panjang artikel: 3411

Fetch isi artikel:  25%|██▍       | 614/2473 [07:54<1:56:04,  3.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxPZU5NNWNodHFBYkN4cjVjWlZXUVNhbWRkWTlKaWxZVEo3THVycDcycGp2eHBZYUxibDFaV3ZHUU50cGY3Z240YnBrS0d4aFd0RVMyS2RDTUMyMmo3cl9INU4taHBLdU5SNHhCWVVOOTVfUkxmd0lpbGRYeFlzT3pRY1FzUjBYdEhRZHlMdkkwX0Q0VUFLQXZGSUpn?oc=5
panjang artikel: 3415

Fetch isi artikel:  25%|██▍       | 615/2473 [07:58<2:01:51,  3.94s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxObC1wUVk2Mmt0bXcwbnZHazJXczF1V294OE5DV2ZJRmpEampnOGRFS29udllMNmZ0ai1UM010N3BNOWFneHBRWEtLRnZaWlJfYWdRVWE4bzMtNDMxblRKRmJIa3hXRVh1cHdGOEFvb0p1cnlWLXVIdlk2anpyaFNRSk1PZkRLdnJuOXRiSUpVVG9DMVRpYlB1dEZHMGFETFNQUkxPS1RyYlV0Rk5OeXVlbHln?oc=5
panjang artikel: 4711

Fetch isi artikel:  25%|██▍       | 616/2473 [08:02<2:03:53,  4.00s/it]

Fetching link: https://news.google.com/rss/articles/CBMi8AFBVV95cUxNRWg5aDB0N0I3X18zOVV5UWJsSnNseDBIMzhpeW5zT0lIVUF0cGMxUm5XOU9iYk5keXQtNUNDSDhxMjRDVzZFR1BPOWxGcWRHYzZCZTZxWWRtVFdabURwTS00VFFhbWstYkktQmhDa3dqQUZDZHRzeVo0N3lWR0FySHhLYkt1NlI3WXpMMjNJSFBpcG5ZUjR1ZUxCcVBhbTZxUTg4alp4OEUxaGdKSUhGc2ZYb1JxMmw0RGxzX0g5T3kyTEZ0Vm5YbmRJOEJUV0swNDZleGMyeURES0RzN2tYc3ZXaUQ1czJiOHkwblQwUUnSAdgBQVVfeXFMUHpEUlNuVHdkeFBlNGdNYjYzU1pSSHlKbGt1VFQyR2w5eTEtY2JOaTRVVUlNRm01NVNSaGVzb3owVGRpek9MM1FvV3lETGM3LUx3OFBDY016U0RkWDgtNWhtbHgtamlwWUozYXVZQWtwaWxaZ1VwdjhIdlZ1NUJoamg3ZHdQMlZGVTFYQlhVY1JOb3E2Wk1JNFN6WDdncUNubGUzanBEV2RiQkhEeUtvSFV0a2toQldUV1ZPeHZocmM2YWtoVGVYM1ROR004UWpRME4xbDZXRGR0?oc=5
panjang artikel: 3030

Fetch isi artikel:  25%|██▍       | 617/2473 [08:05<1:57:30,  3.80s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxNWXlvRk1uYmdWdHRZRmhMVG1GbHd5clg3bENYUEZLMm9HTWtNeUFuRnJjVHMwUS1IYTFkdTNKR2thQjRNQi1BT25VdzZoaFJDdWFVU3kwaDdGb3d3eWdIR0d0NmdEZnlVbkg2bGNHekZzUTd6YzNxdHBxWXRwQTFtS2NSbzNIeTdYTE4wVzVfcjRmRDlqTjVOS1ZnNnB2TWo0N01VWmx4LXRtck0?oc=5
panjang artikel: 2253

Fetch isi artikel:  25%|██▍       | 618/2473 [08:09<1:57:12,  3.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMizAFBVV95cUxOTm9uNjhFbC1tNVE3X1ZaS3VEcUItbEpqQUpCSjhWalFPVGdFaVVTTGNKLWZMN1RkMUlSOWxaT20wZkZ6VWFFUG93RWRRVm9SUUtycHFINklwQTZ5dnY1MzgtblBMSVR0eFU1ZUVSc0xzUDRjQkpGa1VvbnM5UlMwaU5tWFRnS25DQXRWSFNvVHMtdXhhbTVsck1VSHp5MkZFWjZpNDlqNU5IYkFrVHo1d21tdEQxTlp3TUV6QWgzaDYtNE9QaGpvMzNXMUo?oc=5
panjang artikel: 4817

Fetch isi artikel:  25%|██▌       | 619/2473 [08:13<1:53:11,  3.66s/it]

Fetching link: https://news.google.com/rss/articles/CBMixgFBVV95cUxQOU04Q1Y2UWtqWVpqUWNHMGhfYUJHbk5iNFZWbFZXR2RWbjlXTUZrMlpNYV9OWjlIS21PbXphbVRsMHZKQjlFWnBBekhZQUZhYndhLTdoUG41YkhqWjNtUVRWU0JpY3hZcjNsOV9rODhSekFOU0Q3MDExQ0drTGtYUnh3ZFFiUkQ5NkhqVkZNMDVoa0ZpN2NSZGl5N2wwU0ZWcktRbFB2OFZuNzRWMjVYNm05VGFfYTJ5MkJYSG1WVVF2SGRnblHSAcsBQVVfeXFMTm5xVDJtakJlaFFNNzRvd2VERUprYUJqbzhfeC14M2NfX1FnY0xKRmZJcllsWFQxWGo5SHVYRktxMndFS092WTRscENtZEhWZnJPSmxJNEZySUc1WDljV0R4YjI3Sl95Q1h5OS10WjdaVS1qY3l1NGhTZ19HS25mYkVWNGF6VkVERjA4SUhyVlZvcjZDbzZ5N3RacW1qbXhrWllGX1d5YUlYb3JTZEp5VjR3NGl1bjdpY3gyOU1Ob19kUVFRbGdEY0MtV1E?oc=5
panjang artikel: 2689

Fetch isi artikel:  25%|██▌       | 620/2473 [08:16<1:51:35,  3.61s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxNVWIzbUpXZGRlbVg2cTdLaC0wc1MwMWpqeERZamw3LTNpUTdxV3Q4T3JTOWhrbXJNYmRTZnF6bTFacko2TDNjSUVEaTYzT0FxeVpmZENGNkdraEh4eUR6cldOdVc2NEFxaGNYRnJGeEdiejhMRGFza3VCaU84Si1VMlVNeDRNc0JfZmNvdzFqMTd3aDF3RW9CWGFQNWc3bElOX2tlckdtYkdtUm9EN1RjdEpPNnpvM0NPbXVYa1dR?oc=5
panjang artikel: 5776

Fetch isi artikel:  25%|██▌       | 621/2473 [08:21<2:01:08,  3.92s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxPR0lISU1xeERxeGNyRFFIM1B1Y0tuTThWYm5zMFRQTHJoUlM3YzFvbEd0WldXMkl5a29LOEd1VTJlXzNQT1phZ2VBRV9BdmZVTUF5di1mdzhaNlV2UkY4eGdFUnVpZXo5WXJBOEtiSUxMM0ZiRTdWZmVmOU5uQS14X2ROUTMyYVZHZEpKR1NWWUwxcUNfVXQ4UEZ0Y2w1c2V1TkJNLUNONm50aVFGbjJRZkhkWDV2d0Q2ZmRyU1JzVkJLZw?oc=5
panjang artikel: 2963

Fetch isi artikel:  25%|██▌       | 622/2473 [08:24<1:57:04,  3.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxNVU1hX2hYaDBXcmNIelFCOHB2WFNmcFpxc0p2YXdjTzRUcGZ6Q09VVTk0d0VVaFVBSU1FSFg5cFNOTmNaWXlSckQwODFkVVZmQi1BaW9wTWVvcXh2c04tR1Y5NlRDVW5oMWRSa3pQYmxULW5mTVZGWEZ1bjZsX3MzbjRZdmpFY0kwWEFRcElfLU5FUWFtNGdEbnd6aFpYQ0dKT1F5bk1PYjRHTXFiQXBQYUtQWdIBuAFBVV95cUxQNkpDWXhSV2s3ZHpPSkhjMF9pSnpNTmk5azcwbEo5ZU1ieTY4MGlzYVM2aVpaMTd5bkxnRGxELTB2cjBvTTg2RjE0VkRyWkI4ajJhVW94bWplRklzMXJEcTJ0eGtjVTduNGFDTzVmUWtKZTJhN09sT3ZySTdna1RtazVPdkJpandFdGlWMTZqQ2lrSFBvVXRnUHFyVlVfRjRkeGdTWEdfcDQ1bVVXc0dhOFZYcTJ6MHg4?oc=5
panjang artikel: 2979

Fetch isi artikel:  25%|██▌       | 623/2473 [08:28<1:56:32,  3.78s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxOZWpyN0R4Qk9uNl9vd0NValQ0MmN2NjFfeXpfMmJaREdpVG1HOWFCSHB4UnhCSFhKeUFKZWN3VWlsTG1CVlMyYVNKVDlncWxGVmZZenljSU5IN0k2M3RRSGV0S2NEX0V4T1ZvUnRvajQ5V2l0WnZtQllmNmVKQ1R0eTA2QkdEQlQ5Rk9ISHdSYnprZm5FWDRUR0MxbUtoZHNkdmhYaE55d3VUeGM5YjhSQmtlSFRoZVHSAbwBQVVfeXFMTWxnTHNLdll6UmFwTHNBTENMbDBiSWpRMDB4OFdrN2lUMTk3RmdlRTcyTFBjNkdvNVJGLXJFVTlfZlpWa2RWcTdKY2NUTVRTajU3bEpIT2ZSZGNReUJqOXl4Yy03ZU1Fak9ZOHE5RjJmWDdRNy13TEowdFdZS3FJTVRKZVNzQWxJX3FBQ0g4QUpvTzV2Vjkwc00tbXBWRGdUdThEUXVhdTlWZEdxbDBUcFdkNlZJMEJ6VlpZSnU?oc=5
panjang artikel: 2557

Fetch isi artikel:  25%|██▌       | 624/2473 [08:32<1:59:24,  3.87s/it]

Fetching link: https://news.google.com/rss/articles/CBMiigFBVV95cUxNS3Fwd09XMzJWUlN5WlZFVV9yRWllSEZUeFZ1RjJHaEFlQ0tKcXNsRHZyalRHeEE4cGk3aWNXUnI3YlRrVy1wSHE3eGduVXBVNjB6Qzc4MlQzaElVaklwR0tjRWNyaVdCcFAwcDhuMmZTa2R5YnBzaDBzZzNDRWY1S3E5LWtwYzR1WVE?oc=5
panjang artikel: 2697

Fetch isi artikel:  25%|██▌       | 625/2473 [08:38<2:16:49,  4.44s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxPY2ZiRTBwSXJIYVN6QS1jYlUwY0FrT0N0aDRKcHdZWVQwNVhSMWhZQzFLd1B2SHhqY2RYUFFiTUJJVWZLdV9vMjAxQU85Unp6NE9rRlNIbU80N2Z6OEtTZkRuNTJUSG9pN2RBQW9TdXlBSHE5MS1VV2dYcExiVHp4S2RMbncxWjRJVTFsQTFHMm5XYUp6QXlrb19qX2VndWJaRWNtRmJIdVRxY0wyXzlsUUJRU2ZrRzVTQ1k4em9B0gG8AUFVX3lxTE5GaDBPYlgzV29NQ2wwd3N1ZWltU3hZeUFxb29iWk5aRE9WV2xlRGV4TFM1cUdtR0J6M3RjcnlSU2NIRjRzNXNaWGJXWG1nd2hvb0RFY1dOek9FNC1sWHREZVJSTHFUS1VyLXZ3bDRtZ2hpWVJZdGZjaEdnY2JJdTQ5N1VjU0wxUlpMak81dDNPVlJieUUyRFpEaGYyRjQ3elYzOEJLRWl4ZjFHOUl0SldrSElnOWlJY3lwcFJI?oc=5
panjang artikel: 1686

Fetch isi artikel:  25%|██▌       | 626/2473 [08:41<2:09:48,  4.22s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2AFBVV95cUxQY213SXlYbTl3ZXpGcDJCWHBxQWFKUGtYajI2WDIwajN3bUNNNy1pUGRCemtnRXNycnd1WERDM1NuZ2xiUmdvSC1YUUxNOU9fUDVrTlhsNm9ZdzBnNXQzOUlTZDQ1NlVhMFBuVFNFblU4OVVWY1c5RzctMngzMGV4RllaQnRfRTRHM1Q4cjMtb0dDb2xmZ0lSOG5FTklKSHpCb08tX1FSUklrenB0dGo4TTMxNTBtOEwxdUhTM0lDWV90TFRIREpDZktjZzhtSmtQWm1mSTIxZ1TSAd4BQVVfeXFMUEU2R0dvRzdYX1lFWTJ4UnU0RHdTemd5bUZzQlZqeFgtcFFCRmpiRHVscGVEY3RNZ2tZNWRmM2JVU2NwdzhrejdYOVVjU21NclFkYWp0U3Z6VkU2TWs2NE1teHIwcmxWNUEyT1ZrTk51RDhScExaclI5MHBQYTJkSTdzSFZfRFBsWW1jMkxhMldMUi1tYWxRWGxDWVVPd3BrS09zX0NjZTJzMWFsYWdFRTBYMnhNV05WczF2dzBraHlpZ3JQMWVDNXdLN1kwLXpLcWhuNTdudFBnSTgwLUJn?oc=5
panjang artikel: 164

Fetch isi artikel:  25%|██▌       | 627/2473 [08:45<2:04:01,  4.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMilAFBVV95cUxNRmZkQlFpd2g3a200Rzd2WjJla0Nyd2xQUVNjZzMxSVZTcnRvWjd4V0ZKMXVRTDRHcU9taW1iQXhrbWV4QkZiU1FwR00tNk5aU09CQ08xQ1VoUjczLVFmSUZvSjlqa3B0eE8xV1lDUXhpRGlwckVDRWVYQzRjZU9lS0hfZXpTVTkzVVd4bzRSWjExZFF60gGXAUFVX3lxTE9iNU5EVXRnOTZlWV9HWXVPRnBkNnFPTTcyMlZDNWowVVVrQ2FoVElsV2xySkFwaFBFTnZ4dVlYd2thMXVqWGdlMmYyT3hacVN3cTFtV3ZBZXhwQV95eTFUTkVtbzVYTHZycTlTTVdJcFNkazRXdlFaSGtZSHZKaUNVbm9YRG4xMC1odTMyYm9udXVWT29UbWs?oc=5
panjang artikel: 2554

Fetch isi artikel:  25%|██▌       | 628/2473 [08:50<2:14:48,  4.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxPQVB5RFVNVllsdG9jXzd2MzZFVko0ektzTVBqa0NYamhkbW42N19IZjVYVjNQN3VfYm9DV05tZHBJSlRRWVRYSHdJbUpnRVpYdmpBcFRNU3lDc2tVaGNhWXVHV25uRy03YlBTU1FKRlJpNEpwaXVZOHFCOHhDakhidUNTbHYzeFJyZ1RVV3lBeURJN00zYTZqNGZ1M1NfSkc0RnBHaTRyNGdVcnJpWjd5N1Zjcw?oc=5
panjang artikel: 1655

Fetch isi artikel:  25%|██▌       | 629/2473 [08:54<2:10:19,  4.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxNNEFfVWN1Vk9GeVBJWTF6UkJaTGZmby1FMEF2V2hBSzNvNWltQ2VDb0hqcC1ST2hhVDczQzktbmg3Y2JYWVlBS1BrNWFsUXNrdEJhTnhnX1FhUFZDNHN3S0RWbnIyR0dzRnlEejF0YjhyOUhFWUxaS2prWmtjbDR6dFdSdmdsbWJPbUtueUI5UVdIOGR3Qzd3cDlZcVBoOTJyeUExNVgwLVVpczBfemdraXIwOVRmM2tmdEZRV0ctdw?oc=5
panjang artikel: 2337

Fetch isi artikel:  25%|██▌       | 630/2473 [08:58<2:08:19,  4.18s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2AFBVV95cUxQMTQzazd6aUV3TVl2RWlnS2ZJS3YybEdlX2ttdkxyMGFyX1J3eTZ5YXhZNFhYckRsS0JGSW9aLTFiWldqUXhkYjNTalpvS1BHM2duSXZNRnd2eEpFNEhSZDJ6MEUyU29yT0VBb3BRcWpGMTB2cU8yNVptYnVxaTMxdE9QT00yX2xVbUxCd3FIR09VbHVPR0d3ZVNIdE9ZMnJKeVdEdHYtd2tCWXJtVzQyeWEwVXpQdjZqSmFhejF3RU5BUk1WMzdUcWl4dDE5ZnJFUjBUUWZodnPSAd4BQVVfeXFMTzAzdE43RmhfN01XaFVabUZ0V20yNk9QcjZQTXVtNTJaTjJtREJaejFKdWJLTlJReHNHMWxCYWpxWVlxYWVOX3paeS1mY0Zod0RYVWhZdXU2N2M3UWNESi1tdElBbE1zbjhKODAyNTRFWDVUcUtKRkplRVhvLXp1RzlHTzVXQmF6aGZFZkN0STROSjhOUjRDVl90NDN1Sm14S3ZOdkRLMEdQQ3A2bFNGOE5hZ1lpUkFBUGtDbE0zdUxHMTQ3dGViN1VNQmNzbmlFZ3ltUjN5cnpNdVNTeEZ3?oc=5
panjang artikel: 1584

Fetch isi artikel:  26%|██▌       | 631/2473 [09:02<2:05:36,  4.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMimwFBVV95cUxOdktIaVl0S3ZyOE1kRTgtd3RpV2NKbWVzdTRuVnNLa0lKdEhITkFoRVhhMGQ1X3F6SGFNNGFvNzhoWlJMUDdKUmo2ZlRXbk50VGdWbGFRZEhBUVQ5MWlxbmdTM3g0MGNCR0c0YTlHYTR3clc0cUlXNnp6VlVGby1fd3pNVXFqdXFWYmowSjRvM1hQYWg4OVlRblZHbw?oc=5
panjang artikel: 2761

Fetch isi artikel:  26%|██▌       | 632/2473 [09:06<2:04:35,  4.06s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxQS25QMUZoWlhGTUVFUXpIU2psc3ZsR0U4WjdKZDlaYmtzLU9ZNm93LXd0NHQxRGI3V1dWQUw1VGM1c0MxMzUxV05HbEZhdEs5S2VORVZQdHg1N0phM2psQnVqbHc0YnR6Y2dmZUlxUTB0ZHJ5azctcmtNc21LNlo3bl9FZUFWbnRNX29IMDdJNktvSjJTcUdkWElzUF9OMy1pQk9aYmtmS2FsVnVzYWhBbkdDdjRyck9FUjhYSXpQbWZyMnVx?oc=5
panjang artikel: 1525

Fetch isi artikel:  26%|██▌       | 633/2473 [09:10<2:01:50,  3.97s/it]

Fetching link: https://news.google.com/rss/articles/CBMimAFBVV95cUxPNFp0S0dvYW1COUkweGVFaGZteU9JT0VJT25pbWRwV0NrRWprWW5QdHE4THg1NzBvejZLQ0hTS1VNZi1oR3R0SmhPY0tUZXY2M3BVU1Y1Q1J1c1hIczBzU19ZT2JmNHZMTjdZS1NXVVI5TTIwRUxxWXZkUGdnV3d2Vnd5aDlCLVNVOFdzZmd5RlFsVk10X1dwYdIBlwFBVV95cUxPaDc2Vmt4UklkVkdLaWJiVXQ1ZFVfb0JjZzFHVUR6d0U0Snk1M2ViS1FOaGUweXRqTmpDS3N4UmpIckpJSDVHWnd1dFlOVWNuZlNwbTdPU2RrYUZxMU5EVUdpbUROMWh0bEgxVnpMU01sQ0gxWHdoQlU4Z3FoNEQzY3d2WWhLYUJLeDNMYm9rOFpPVUxIR3ln?oc=5
panjang artikel: 1936

Fetch isi artikel:  26%|██▌       | 634/2473 [09:14<2:00:35,  3.93s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxPZFVuUXJ1S1B6UXl3VlBoekJWOWFzalVQd2VWZk03ZFNwM3RLaGFpZlJ2Q1Fyb2R2LVpUUVQ4Zjd1ZFpoX2xRZlV5YmkycHBJTTl3RnZuVWVBcHppc21HMk40RXVyVzBPelZKV1l4SmZYcWtwZmZfcEpjWFlxQjN6UTdFSXJLaXp2ajZBdS16blRTWDJoZXVOeVVhQmtyU2tXanZjTkZxUldvV01KRTVxWlFlY9IBuAFBVV95cUxORTg2NG9TZDdrLUVrZUNIVHp2NHVNZE1neGJtczBSZVpGWk5UYW9rZ3hkakZqTDRGYWtJLWtzQUplanZIdHhMZTFkb0VSVGtjc3hwSUJEUEZYSllpWE94aTl4RThiOHNYeDFHeW9SRnF5X3U4a2c2YmYxbGJxN0x1LUd1QjFCTmtIZ0tMMkNuc0NSYXpIMTVtaTBMZ1djbjZkODVXYmlidGp3bUJBbkRMa3hmZ3YwVUdh?oc=5
panjang artikel: 3874

Fetch isi artikel:  26%|██▌       | 635/2473 [09:17<1:58:16,  3.86s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxOWDI4ZE16Y1FOWGdkR19oUklzSVVxc1QtSURqaVQxenN4a0NVQzRvWmtBcGRScUlkRmREWEI2Y3N5YWcxNkxETExCYVZIa2RoUlE0bjl4RTBBVkFrc1EzZmZ6NkpRWjVnRmg5SVJ1Wlh4ODQ5RDB1NE1PX0w5aTBTRHhaNDY3RE9BZXNTMjZZN2hxWWEwVVJhUVRYeVJFVVFCTEhCTWJhVjhWTlFtbWRBLU5PcWtZNkJMUDBITkRFa3FlWmtreldVNkhhVFc1d9IB0wFBVV95cUxQMTlGcHZJRXFaMXk5UFB0ZVBjNjZYYkNRNFRDcERuZHFabUl3X014b3Jsa2dGU3FRUjdqcldkeURnakF0ckZFVGttSVh5amhTLW96dkdDclU1UHpXbkU3UlN0Z2Y5S0NleHUzb056VkgtYXgxeS1fODdIekxBNHRWTV9iUVowNkFCRlFlcXdNeEV4cEVLVWtGenh4akRRNTV0d3ZLemZmTXo0N19BNDZFTjUtUlFfanB4TTdYN1Ita3FnY2VWaGZHSFpHSXdWb3BWNkRN?oc=5
panjang artikel: 3267

Fetch isi artikel:  26%|██▌       | 636/2473 [09:21<1:54:02,  3.72s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxPTnFmYXlsOHZWcldFWE1JMXJMdThKSUJSOF9DbjVCUWNTZXR3b09vclA4RTFqWkx4eWMtRE5wbTBhWEdHcE5ack9XLWtZdExMWTR3MGRrQ2M2YVh4UVdBRk5pWHNNOF93ejd6QTgxS3RkRzlNT3RHZXc3NlNtckI3bXh2WkFyUGxFMmRnSVdlOGdwOXRXOWZ3N01YcTRJRzNLNjBNeNIBqgFBVV95cUxQb19UN09xNUFnLUFzVHNwX05qTUFtd2NCaTZSb1B3M3h6aFJrcDM0RUlCX2pWYUd0Zy00eExmY2lKb0REV1ZWNmp2MFFWYUs2TjRWTGZNT0RUSGNfQ0l5RkE2TU1XNGtLeS0yT3ZnRW5WS0FiMmRDOWp0Z0M4VDgzSDhKZ1NhSWxoQkhJc3pwT2xZR1RJOEZRU2dOYzdfeklPTHhCRHBVdUpudw?oc=5
panjang artikel: 4456

Fetch isi artikel:  26%|██▌       | 637/2473 [09:25<1:54:45,  3.75s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxPYm5KNVZpNklvYXBWaWVWMTd0SHd4V2xoOW5HR1ZjTk1xUy1RdG1oX2NVX3FON2V6Z183NG11b2xhTGRNa05OX3lTMXZrVVFHeExsMjUzR19OTlBOMHE1a3d6N1VmSEZqZ2ZkVzBGMG1PQkl5Z0FzcmVLbU1nZ3hEOFFhcFJfSWxBc1VPeU5wdmw4aEZuRzE1Vm9rZnJtczJhNjhjajZpZzlzRmVhZ2VYeE02TVh1aElQQnfSAb8BQVVfeXFMT1NlZkI1ek4weUloM0wxUmF0YmlfWUJOTjgtWnAxdjNwUjB2UUd4UWNWM2JSb1lSaWNyX08xMWRwaWlyV0ltNzlranJyUEZlbE1kbGxPSFpHTmcwVUFQYzk2Xy1yRlFrdHNTSU9jVS1FZ1hIRDZsTlpGaFlzNDk0QnlPT2JWUmllWGdjRGduaU5EY1hnb3Q0UVZGWjdBTXQ5RElXQ04ta08zR2JUZlRvYTVHNXplVURoQVNyWlJ6aFE?oc=5
panjang artikel: 1678

Fetch isi artikel:  26%|██▌       | 638/2473 [09:29<1:56:45,  3.82s/it]

Fetching link: https://news.google.com/rss/articles/CBMioAFBVV95cUxPSWwtWUdFbTlCMk8zU0FyQnFkRmVPT3RxS0IxYmRkUzlPdFNLMDA4SFdqdk45d0NOWER3RFdZZWdpRmlSTUYtNGhhUHRQcnhqVjRZNkxtTTlUTXNQeGdXLUZVSFZpTktqMVZja0RQLTctOF91LVdVTTNSZHJhYTRLaTdscmRNMnc2dVB1OG1zQllBTTlOdGNhOUxBcTdQY1JP0gGmAUFVX3lxTFAwNnVQS3AtQzg3QnFhMUVqWUctLUlNVkNON2hpLVZTVFFQSzROc2lEN1J5bDFIT0p4N3F5aEdwVXZjNEpnZU1ocXBBc1NKYm5HVWtlWHBmR05ZbU95VkFXNXdyMEY4dXVrQVZaU243TGNSelpxUlVoZzN4T1ZuZmNUNXJ2NVFRTTVBOXh5VkR6bjktZE5aS3duazRCZUdfdXFHck5NTmc?oc=5
panjang artikel: 3679

Fetch isi artikel:  26%|██▌       | 639/2473 [09:33<1:58:57,  3.89s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxNci1ZSjFhcE96Sm1KMUZrUlhrekUyYlB1NlM2T2ZodTB2d05ncHJnaFoxZnVpQVVsS2dUT2RNTEhvazFnNW43TGxsU3VWakxhQUZCdlZiMDBLbFZ6NUxkU1dDdXFUd3k2WFdNUEVESkJobTNaYVd5YUhhTUdfRTFFYlROOG1xWjZodjdjZ2dvSHlQemxLZExOQ2lnS0xucWp5cUZVd2NPTXQzZw?oc=5
panjang artikel: 270

Fetch isi artikel:  26%|██▌       | 640/2473 [09:36<1:55:01,  3.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxNQUFJaERUdWJ0ZW9hMEtGQkdkS0ZRNU5fcXJGLU5ORUhVaG16SDNqN1BiSGhWQ3RnR201d3RWTEF4M1ZBZ01mZzA1d3FiZVphaUZLOW1saU1sZWNPVU81dnFhVi1nbjd4Y1BTRGlkWEZsZU5NZk9KeU9VVElfNjJ5VnEtZkZ5d3RsYmlGckxGbGZRUEsxU3V1a01qeHNyM1RIV0RlZlQ4Y2p1bjBNTWRaRkdtZFRhQWJaU1k2Zm5nN2FxQnE2ai1oclowU0tFQjTSAdQBQVVfeXFMTlRDQVZMb3k1N3RuVVNLYlJEX0t5NU1xZXcwYnlWRFZmV0QyanBtYmQzOThNRjdMTjMxSE1TemdqcHlWSmIwdHVOQjBCNG5EVXJHZERCamdTYm9nQ2NsTzQ5cUJrTXFkcjFKSmp1U2pBOE5WNkNsd3NEOWRrWDBDcFh1dFF3QjR6YlVaVUNORmlIQkhjcTNoY1NLMW04NTBwTEl1U0tsbHdIcnkwWmV2dGZvSTNqamJOcC1pWlNuYklqTlRtX2lIYnhKcm1UaTlPVHVFRFA?oc=5
panjang artikel: 5948

Fetch isi artikel:  26%|██▌       | 641/2473 [09:40<1:56:24,  3.81s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxQWW9sZ253MEVKRldfM1JNTjhzMUdXVG95Ql83VFZ1YTlSV3NJTXQyLWFCV0VWYm83Yk5WLTBkUDVSVXBFRnphaUhPX3B0aV9DSUJyVDVGcHVnNXp4RmsxOVJGY0xDeEtDeW1BaGZzQS0yVHh4RjFUM3hhV0lDUWNKY0dSSG1ia0cwZTEtZHZES2drbDVRMHNLR2JWWDNrUkR6WTNwN1BMLU9Vd0xIWlE?oc=5
panjang artikel: 258

Fetch isi artikel:  26%|██▌       | 642/2473 [09:44<1:54:37,  3.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3wFBVV95cUxPRG00QkZzZDViQnJ1d0lLSE9CQTU1aDVTaVJkX1RNSE55eWg2Sld2Nm5lSnFWVEFtNVh0c2twU1NIM1JOUlY1ajZ3dDZRaTg2VDJreUc5OUhQanhHVkdSYnVySU1GMktBNWQwbmFINEMtNzc1UDU5dmFpemQ0QmxPdXdrR0Q3SW9JeVliTWx0RWRQdnVwWk9HWmdfb2ZFOVQ0UFJzYWlDaGczSzc1VDRVNU1sSEdZNmFPVmpRTVZ2V1Y1VWJyYlpiNlpzdjUyR0xjWHBwMWs3bll5Z2ZUdkpj0gHkAUFVX3lxTE5Kbm0yS3VUMHRRaGotcmt4anJJSzkyUHZBMng5bWxqTm5MYV9BSUdUdzBCODJXcTRYbnE5NlhQY0JzRG8wUDNBN3ROLUdqMWZNV2dLRnVEbklFQ0ppTjdKdzZBUGFvOFpiemZEZ2FvR09wMW5IZ0dJVVozd0szUHRMd1p4T2xlUDRiSF9jN01WM1ZLcGdyNDM2YlQ2enpzOXhiRWg3U0xEcTBxekl5M0tKbktLQ2Q2RUdoTjdvUDdISHRWUEtHNFVuWTNRbmZlMFRzNVdmbVE3T0gwaVVUcDZzMGFjWQ?oc=5
panjang artikel: 186

Fetch isi artikel:  26%|██▌       | 643/2473 [09:47<1:54:04,  3.74s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxNVTFiUlpqNXc3bGNIbWlZU0tDLU42Z2pqeFFfTThlUlVHdVFGVW9hODFrTjJxNmxxY2dyVGQ3OGxPOHhxSnJoVy1qMEVqamtJRlE5ejJKR0JCYmFDSEc5eTZBak1iVGpiZ2NBVUxNSUlkb3JUT0FmdmlWRF9FTkZmSjVxbVVVU3dWMV9yUkRfd2daQ0lWWHY0Z3VHd0hfNVlLQnZIT0I1aXJ1TGd5VUlMUUhvMllfZ2tGNFVsODEyZ1HSAb8BQVVfeXFMUElaclpub0FDZDdTOVVDRXp6SmtZa3VfYnVpR0wxOW1YX3NtakluRTNyaWttajZiN09ad3FhbmlXQ1J3dUFsREVLVXhfUjN4ZlZXVF9PNmtCazhqNGR0akhxOTZZNzN6TkRyU0ItNmdrN3FDWHNJeXdUOWNsaFB3UEp0LW9rUlJyMFg0dFVZOUpuVkgyREIzZFNEX1FsZUFyOVFYc2NKUkdWdjRVYzBrcjFzNjRtWE4wbGVVSnNkTFU?oc=5
panjang artikel: 1937

Fetch isi artikel:  26%|██▌       | 644/2473 [09:51<1:54:03,  3.74s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxPeWhONWsxZGN4TmZ4bWE1NXlHYk5Vei13Y2drU1RQd2ZvY2VxOUE4b19ocF9WcWNyYnYtVzhOcGtPSWxZMVdtWUFaRjJQV3VGVTJpWDFDZXZKNzJVdEFlTEU5NHJDMWQwRlFRZk9XTVRhUUQxLWRYbjRvRDJCamV5SkhRTzZNUHZUQ2d4UDg1dlhGem5vOTFKZ3JLUzJ0ZnBMNC1INWQ2TS1yOFNjRTBXTnlR?oc=5
panjang artikel: 639

Fetch isi artikel:  26%|██▌       | 645/2473 [09:55<1:52:41,  3.70s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxNeUVXS0xhd1JpZUxYYlB3clBobmtpM2EtYU5IdEUzMndWTzdSZlBHYkxjdmxXYjBtS2pyZU1hOVhsWV8xc3RuaGpVczBPaEhrcEdIVW5hUjVWZVdLX0xqS0MySTdGUktQSVEzZWRzcXhHM2VOZ0NTRlJXV2NLMEdHdWVoeTdiemhtWDhCWDlOVE9nOENkZkRXNlRCSjNacE5xRXJYcEluYkFwNmJadER3Zm1GbmVKN0xCckE?oc=5
panjang artikel: 3734

Fetch isi artikel:  26%|██▌       | 646/2473 [09:58<1:53:03,  3.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMihwFBVV95cUxOZjhGUUh3alBzNTBQQTBwSko2Y0FhUFo0UXM5SFRfeE5Va1JPZUpJTDhKZ09GVUh1cEF6N2otVWQ2SFdvRHRqVm0yX3QtcVhOYnBWdkc4T2NQU3RNSHZLU3RBMDdrX3k5MnNGUEdIY2hldVpGRkxlX0J1bUZ2RW95SnFLWUQxdjA?oc=5
panjang artikel: 3138

Fetch isi artikel:  26%|██▌       | 647/2473 [10:02<1:52:25,  3.69s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxPckVCLTdxNkNEXzlaY3J2R0Q2b0VJZGhXNy1qTlJITXg3VnRrbjh0NlkxaExCTFB5TE9OcE5ETlZTX25oXzVPUXpEbGtELWJMYTdxZjdhb1p0akJCUkZPbWRlMzRMcXhaZHBNdkRFWXlXVDZDdzM5M0pfUS1OTURnVzVNWGxCeldyd3ZFbHNUaGZ1dU8wOEc5ak8yZ2oyYUdEMXJ3X2JsVFRrMzlFSEQ3ZtIBtgFBVV95cUxNNVQ4NlRWUjQxNGtZYlBuUWRRQ29BV2prYjFZcXJ5YVdDQk9YeG1BTkhIOWNLTXpneHltdXpRNkpvX1pXUl9zTjZ1XzJOenFYWGd2Q0MtaGl5VkJwZ0hCaTNyQ09OdlVFRFVpWjJiR2t3MExoVXpjSlBmb3JyMUNjVWFTNjdRclhEWjRJVlBOcHpPMWJIM1pMc0NwamR5MWNUSjFUQUw5MEFFaUozRnEwN2dSRG1iUQ?oc=5
panjang artikel: 3332

Fetch isi artikel:  26%|██▌       | 648/2473 [10:06<1:50:49,  3.64s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxPa0xHNmRoRjd1Nkdic3pXSGFLcXQ1dWR6aXJBNlRqVWJYa1hRQ2V0cmRsbmhSOUVZMXVTVzkyTEh3aFdGUVdhRjgxdnVma0FmNGVFb1JYT0FHVjFNS1JwNHItbkFSaFR5a2pRWEVUeXBydkE2dzYxTEQyUFdLbmxkOXVpdkJfQVBYNVR6RVFEREN4bkVQVi1sMW9jYWxyTTZjcUE?oc=5
panjang artikel: 2360

Fetch isi artikel:  26%|██▌       | 649/2473 [10:14<2:31:51,  5.00s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxQNzA3WHZmd2JaUXBHbWRieExOVDV0S20tUmVyR1A5V0VhbF9JYjJLRjZ4X0lZcjRiYl85YVlZbFRBdDNENDRncUp5WnpvMmlFc3dMb2dVak1YWFBsRHdqR2wwbTUxdEQ1bzFQbjdtZVR2RHNScDdWcTZHWnVPeXFFX01VM25QMUQ0ME95dWh4eXloTi02TVBjNlRxTGR5c0dXZ214TWIzajdsLWxpZnEwQUFmYzIzRVptY043VTV2a0JFUQ?oc=5
panjang artikel: 2742

Fetch isi artikel:  26%|██▋       | 650/2473 [10:20<2:39:26,  5.25s/it]

Fetching link: https://news.google.com/rss/articles/CBMiaEFVX3lxTE5STkZmQndVTFBLT2s5M21JbVhxbzhmZFhLbFFZUDRTNDNHUkxsT0c1ak1ENUQ2NE51RUo2OXlJTmdkOFJEWlBhd1dLazJIMklVVUljR3BqcFZhR1g3ejdRTVMxQ3NOZGxp?oc=5
panjang artikel: 1449

Fetch isi artikel:  26%|██▋       | 651/2473 [10:24<2:27:27,  4.86s/it]

Fetching link: https://news.google.com/rss/articles/CBMinwFBVV95cUxNOHlrdEgzeDFtd3p0NEUzN29CYW5VdmptRWhvd2RnNkotMHQ0QUl5SFVwUHRxQmpGOGJYQ3pMV0VxeFluT1d2QnlmRXBVWkhUNlNyT1ZnQVhPckhlUTBWQVRsNjBxTmxteUs5cDEyMEJzczBJZWZGQ0ZySE9PR0V1TXhkYmg2TUhVS2MtUDNrWkktM3B0eC1oNy1haUJyeWvSAaIBQVVfeXFMTmQ5cjVJb01kRnc3YXZuT1kzY0M2V1NUX1dQdDBtVWs5R2tueG5ydlZEQVlHMThycHlSZ2hxYlFERjV0NVg2RWt3T1hjSEgwR1YxZy00a1FPSXFwWWhzRmN1QmcyVlZBRnRfV2RtTTJBYndxblpYdHhTYlF1QWhkeWlXaUdveGFFUTFWNThZc2J4aW0zSGVoeEg0Y2h2dld5amNR?oc=5
panjang artikel: 3096

Fetch isi artikel:  26%|██▋       | 652/2473 [10:27<2:13:14,  4.39s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxPQ3RmeE5LT0syb0NMVlIxMGJoTThhbW0xUDdlemJ2ZTYxdnhCb2NQVTYxeEE0Q2Q2QmZMU2ZnQ0NVci1vLWVYZXA1TldWcFRtSHFHczNDNHRSaFVIV3prRl9SRl9OYVhEYnVCbmZWUzExZVRQbGw0VVBxVkstVm9NS3VOTTNaNlBwc2RiQU1kcS05YV9OWXNaZFd6VVhlQWVhN2liTTNYY3AxVlF5UFBWbFFjRllQZWlEQzUw?oc=5
panjang artikel: 2499

Fetch isi artikel:  26%|██▋       | 653/2473 [10:34<2:42:21,  5.35s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxPV1VVeXJjUktnbWJrQkp4VGJ1TjRnVmtiRXBHY29xQ3NCV0taejBZNWllaVk5LW85YkE0MTg2QkFpZ3k3WXZiMzA5Q2loTTA1QWNPbnNEZ2EzSDYtaTdjendPVkp5QkhfYWFqa1EyNG1Gek5CYklaMHdXdVRDNUxnUUFvbXY5X3F5RlUxcW9jYXZ4NEJ3dGRoNVNzZ1RXYWhUbGlSTWk0ZXN6bUFxemppcVFSV1MxYldRWDNEUXc4TG0wUdIBygFBVV95cUxPbW0tS3NMTTNMQklxZk94MW5nWGJqSGlGVjhhYi1VaEtwLUtEZEhWMnhMUHVERmdhNnJPUDd2YmRMUzliaDU0d2RGTE1mSjBLZm9makVmZThOSmYwYmtRSE5KWGQ1bnhyZnVYSDFZZi1VQ1NjNU15eG5BdXlZbjd1RHJ6LWFTdlkwR1VpRzJESWxBVHhXYTdyRXE2aTlpREZMQVZhOFFhcmFqNG9JZ0MtanhBVXRQUlhGMGZsVlVnWWxzOE8tbXh2Qm9R?oc=5
panjang artikel: 2652

Fetch isi artikel:  26%|██▋       | 654/2473 [10:39<2:36:34,  5.16s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxNWlgyRHk0ZEp2bDQyNU1NMV8tWjR1ZmgwbEpOSExqU3VpSTExUXBFWG5fRGotbi1qZDVCempoQ0xyUDVaVUFkd2dVclBFb0p0WVF2QThrVXVNaUFKTWhYOWlnSGtkNXVpNXd5dmM2MHF6UU5YNkg3bEZ0OGlNaVotY0p6a1RhbjJNb2hJMVZaZmhYRWJZYjA0cFpoNHdTdUZlTURKdGxweTQ4Zw?oc=5
panjang artikel: 3969

Fetch isi artikel:  26%|██▋       | 655/2473 [10:43<2:21:34,  4.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMipwFBVV95cUxQV2JUTFYwakdyc2pDbXUtcm8yeXdVQk1LUzVlU2lrbGtOYl81ek8xQ1l4aHdQVjhqTmVYR1FHOFB2cW5YT0c0RHc2enFWOUtaODAyLTBWRzQ5dnBIX1JJVG44MV83LW5aNUVJM3l2TEM2eXRmajl0MFB0WVhRTkN3UjBpRjROYXYyeVZ0MmZOV3ZIT2l5OFBFSnU0YU9PMXJlUWhGZmlaNA?oc=5
panjang artikel: 1512

Fetch isi artikel:  27%|██▋       | 656/2473 [10:46<2:12:05,  4.36s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxPM1ZKNU1YcDRDb1ZmcEpheXBKR2oya3RuNzJ0dE5faS1YYktadGNyUUN5ZVpScWRiampnaHlzWXZqRTF3dHVocmF6QjN4elJOczRzc1FXdm1keHNGSnp2clRSWE5lSXpvOEtuVU1SeW9COWNYeExkM2MyVFljSjJCWVZjMk50SGFBenV0V1gyRnpmTUtILXl0TmozZG9KUWpYVnpGRm5HRVpFa0l2VjhtZlRCUkVqalpKTHJSNXo0NXVucmZEOVlz?oc=5
panjang artikel: 2481

Fetch isi artikel:  27%|██▋       | 657/2473 [10:50<2:02:30,  4.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxQZVBsMm9vbWhQWHcwRmdyXzdVLUpTdm5vMF9jM2o5OGFuMk95Tk5qZmdsQ3NmckJiM2dJM1VRT1BsOXJMekxtU0RPNTcwVFVaRUExMjhrams3d1daeFpNZEF6Y1VDNENweDROYUZmUjlRQ3YtN0RTNlJwYTd5eDRRTUJoVFRTdVVmOTJYbnV6VURUXzZWUFMxa1Mxb0g0X1BJbUdZelVMTUlVUFlMNnhHT3pZakgzTzNSTWIweWZFVnZWMGvSAcgBQVVfeXFMT0ZaVDNaemRtdHItY0s2ZHZxaEhMVW9kYkN6SmZrR2xrRzc2LWVYMGF5N2xiN1Jqd3JLaFJyRWF6ZlRtcUVPY1Jac3JNeHR6RGUwcDN2d0E2eUVQZ2VkOTdZRDdmWnRJLXN3TGQtMXAtVkVOSThhNjJSV0M3SE0zRElYR3hWTnhZaGZuS1p4RjJEbV84Y3hKTlZSbkVfQ2dYZzgyM29vQnB5d0xWWnlrV1dzUGw5SlR2U2RROXBJSXRROW1uUUV0c2s?oc=5
panjang artikel: 2527

Fetch isi artikel:  27%|██▋       | 658/2473 [11:01<3:05:55,  6.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxOV2ZNcXV5V0tCTGVuX05TNms2RUJsMlRJSWVCc0FtUW5MUWp6cHl3OUktaTBNTW8xeEdRMEMyZkhXR0o2LVR3Wkd0UXZRVEllT09FeTZnUEc2VS1xVjhDSXhNeDJlZmZzdnoxb0VPeG9jY09vVmZuUlV0bUxVV0lUNFFSTVF5Y1hJS0Y5bnJVdGxUSDl0dXdYanNPUjZ0RG0zYm1Ec1FMXy1CaDBrYmE3SkswbnBXYW52aWhmTW91REs3dkpZYzlrZ21Pc2FWMHpZYk0xXzlucjBoSFXSAdsBQVVfeXFMT1N5SlVOYTVlN3FLSWljN3VGN3VvQnpieVk5cWhtTVZ5WTQ3X2JTUFFsQjVfMVg5aUZ2RzRWNTBVMzByMWdkQ2pTV1dnOF9YMF8ybURldVNuOGJlblYzWnh5bzhLRFR5dEdQUENSaEV4Q1RhMUtHS0tCTng4OFpUM292cU04TGVZZVJhZG96Z05MQ005UXZfMGhjS3Z6ZVVjcmQwUHEzZEZTYm41eTdUZkkyR2UzM0VMTDdnaWVrSU4xbk9fZUtOX0hJRU11cjdmSXYzSXFIRmE3WW1j?oc=5
panjang artikel: 103

Fetch isi artikel:  27%|██▋       | 659/2473 [11:04<2:41:57,  5.36s/it]

Fetching link: https://news.google.com/rss/articles/CBMihAFBVV95cUxOcUxtUjB3WVRHUE5WLVptQU1qS3N1cS11NEh1bUdwZEJzdlFZR2o4V1R2eUEwWUpGanB6RVpjWjRGWXdKb0FXYWFHa1lsdkMzbUpPSmZMZUhFT29acm1MZXJWd2hFUUNjUzNOVEFSYkhXaXM0SDYxWTVfdXloLVp5Q1RwVUc?oc=5
panjang artikel: 4187

Fetch isi artikel:  27%|██▋       | 660/2473 [11:08<2:26:24,  4.85s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxNSVRhY2w2WmJhcnBoVFY5SDhLYlJSRXQwdzZiNVhMUmJfNHR0Wkd3Q0N6elVEai1fbWdLRmdpenRHSXp4Y1ZVT0FLRjIzMElUMnlPTzduTlVrM3ZZWlZ0VTFoN3E0dnpTYkFqQXJzbG9INzd3NkhJd0lXZ2lsWTZkM3RRNnJqOE9MSURNYXhkTjZrU2ZwRVpBNzhKMHlOcWZCQ0kxRWpkdWg1U1JW0gGwAUFVX3lxTE5ONW1BM0s5bmpvV1dQU1hLQzJhYlJfRDZWLXh3NW1jLUpJSFZNeEJ6RUZyRmVRNFZNYnZzUDFCcWNRNlFFdzZBYnEyMWowTDlLV1AtUHV5V2txSDZyRmVERER4NnVvVWViYU5qVGJYUWh2bnduRU42bm92MG8yNkxVZ25jLTJoZGVjckQyb21EZUZwaHc4cnJSam50UnlzWXpRVEdnQmM4X2VuMVFpZ0Nk?oc=5
panjang artikel: 162

Fetch isi artikel:  27%|██▋       | 661/2473 [11:11<2:14:21,  4.45s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxNWTd6ZGpLa2JieC1kdjU5a2dOWHFIYjBKOUpsSnlMdHpfS2xsYTRmQXJfaUlXdmQ0VGJEdk1yMTktbWZhMUxMZDQ0Z1BtZkRUQ1pnUHJya1lqYmMycWxPN1ZrQTJNd0NfY1c3ekEtWk5kVWxhSVYtSFRVQjhQU1VYMFNrOF9CLXgxcDR2Q1ZyYzVLMmNhMVl5VUdCMHFlMWdDUTZySlJ6QXpIWWZrYS1XYm5QeTjSAboBQVVfeXFMT3B0SThCdWRoRkg4TWRVYkJwRHBwaHNNQVRwZmJBSVcxdXM3ODBlaHVnbnI3Y0FaMUJhMHdzSUt1TVpQRnNiRWtHTlFpZWNtUGRGWlVUZ1Y4WWVRcTdqOENQc1hmTUZ0Nll2eWZjUkQtcjR1eXJrUG5OQkk0Y1pWZVp6SFREcnNPNUlHR0dwRm5HOVpabWdYSE9XeVpGNFNta1RZS0d4OVZnSHBsLUV5Si0tbDVRdHA3Y01B?oc=5
panjang artikel: 2066

Fetch isi artikel:  27%|██▋       | 662/2473 [11:15<2:10:04,  4.31s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxNTDZEcFo3OG9aVktqdWlRRzI5SDJMV0JvR2pJY0M2OGYxbzJtS3BnWDNkVEJLd1dTc3dKbW9ETmZfM1BrRTdvZTdfbHRjT0Y4OGNRVWdEc3d6MnVkNnhOMFUzRWRFY0dHYzFSbHJNc1hLdVNvakhQZThfYkg3OHYtenpfanZNTTFSUXNnWEh3ZXRPa25SS0ZiQnU1NzhJRFF3czRGVDllbjYwaFJYbUxMbDRqOC1yODTSAbwBQVVfeXFMUHdMV1pzQV9rUW83MHNnUFRvaU12ZVJJYXRxSGgwZjdmWHV3X3dsTjlKVldfd1VxWENHcE1VY2QzZ3dwQzVCSVhfZjFNRjlDZVdRNXdLamx5c1ZHaFJPMFNkYmNFLS16Q2U0aTdtdlhPREVwSWJYTGlvOFQ1U2d5UmhYMlNINUw2elM1UldEWC1uczdWRTdkcnZERjdmWFpBaUlHbThWc21RY0tOZldaRXppazVRSk0xLUYzdHI?oc=5
panjang artikel: 3026

Fetch isi artikel:  27%|██▋       | 663/2473 [11:20<2:10:35,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxQb0VVZjI3NVhSTHRSV3RpMkhNNFdHa0FTSWZHN211MWY5bFY1NGdELU1TYzR5SkttajNYUTlsbzI3ZDRrT0hZYjhvR0RjdGhoaDVMc044bERHWXdueHBZa1B4c3drcm5tNGlzRWJpdDBZMVY1WkRKeGdibzA0VURINFItWWpqX2trYUpRcFZHakp6V0VMWWIyLVhXT3d5RkFhM1JFeXppNmRxZw?oc=5
panjang artikel: 448

Fetch isi artikel:  27%|██▋       | 664/2473 [11:24<2:08:07,  4.25s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0wFBVV95cUxQOTNMRVlILTVydGxaeWxKVTFoT0c3bzBnTUxncWdGbzFqNXRWNW5aQlc0WHJBOTJVeHRlcnB3dWZfNzRMUXM3UXFSSmVsQ3U2VGI1Z1FrWHJ6bDZjSlBja0pxR1FlSWs1c25lb0t0bThxV1ZsSkkyRmVWdHRPM0gzdl9VV3BQSGhBWlpmR0U0UXNVWktDck12bzNwTHBJd0NrX2JhaXlDWUpWSVdrN2Y1aHh0Mkl3ZWQxZHk5TUJKZWdmLW8zYURIT2pZQ2xGQm9FNmxr0gHTAUFVX3lxTE9tc29nUUNORGVzc3FqQ2V6M3lKOXRGQk1KX0duM1h6VTRCdDVtNGQ5OUJmSHVqdVpjaXZ5cEwtZ3ZQc1hUd2xoNy1wS2JmcUVmTnlMemNRaDFzWDRvc3hQLUtHclREeDJid01udVRPX3owMlJIR3FfMUFYSXU2dnpBaWxXRDJYMjZKUE9oWTd4VWR3bm9mN0N1SlVQcVNlNGtGaEs1NlFfZTAtbU5KVjQ3emlLYlRyM3k3RTVrM2JuWXdoTWs1QTNxdm1vZkpxZ2hrb00?oc=5
panjang artikel: 175

Fetch isi artikel:  27%|██▋       | 665/2473 [11:28<2:07:18,  4.22s/it]

Fetching link: https://news.google.com/rss/articles/CBMilwFBVV95cUxOQm45dHFpWm5UOTJSbnZBUElodGFMQzRnc3lteUdNLWxzRHA3Wm1aV04wVnlQQmFLSHhUWUFVVFZtMzlWR3hKN0tPQlhPUmxBNzJsTlY5VWg2cG44SjJlbGNhYzMwNFE0enVHTXc3bktkOVoxUTBXamNWc3k4UTBnTmhnd2xFUElqM2VRX0haOGFOdjc4ODJz0gGWAUFVX3lxTE5iMjNvX0VyRUNJVXVsTXZTQ3Y4WkxZQ0NmdXVhWkpOTEg0R2NrVXJUaEdrc0xuSjdrZ1llOGNTdmZwa21OLWtJZXRJMHZNTkxORnlnR19vVUdKRGV3OW8yNXgzN29rQi1KekxiQjBCYm1Zc25Dd1lMeGpiVG00RXRhQTFSdl9MXzdFTTFEYnIzaW9aU3hsdw?oc=5
panjang artikel: 1668

Fetch isi artikel:  27%|██▋       | 666/2473 [11:32<2:07:52,  4.25s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxPNkozQnVVYjM1RllGaXdaRTZhQ3FFTWZXamM1TUNqT0dYWmhic3VrWV9wX3FFdWNQcWJsWjM1UmxzRUVLNVVMYUlyUG1yUnppaG1OdjVJYTZQM3dVazlSb3dzRWMxOHd0d3p2RW1HRWZNaExwZW5IUWdPZ1M1b0FJLWpmUS14Vmt2ZW9uRVBrejhQZnFfNDVkRHpsdmV2Rll6dHVsdnYwTHhqS3pRU3BUaXpfU0ZuZzVOZ3FUTmlMd1N2dDY3UDZodERB0gHPAUFVX3lxTE11MHk2NGFlSDdMOHVFWFJFRGpha3l4TEgxMUFzb290d3pxUFNOYUhhT3dxLW45T2ZzQnFTaVNvSGViVEVlYVFpS3ZQcTVfY191U290aGdWd3Z6WkhJNTlOVVAwNWhMcXduSG1NWWxDUm42WWYtdWZxOXFEaW5xeU9PWEl3YWtiVy12MktkNHhyUjhhZHVRa3EtRnVLb1lhTWxneENNUTIwNl90cGgxNEtqdUhBbWs4a3VxeEIwcF9ZSEtmYVFaMjZNNjd4MkVDZw?oc=5
panjang artikel: 1679

Fetch isi artikel:  27%|██▋       | 667/2473 [11:43<3:05:58,  6.18s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxNUFN2TmNxNEFRdkZrVjBvVDhaT1VPNWdNVVRmbXZ6elRMOVRFZ0NPRzVtWW1VQ2VmTnJHM0xBOGNIYU5kLW54d3BwbzY3WGdxc2tfclV4R3J3YnVVMzN5Q0h4NmE1RXhTcFEtM1ZuakRsenp4My1aNE5maDRqTV83Vk5mblFkcXh2TFVYOXowY2ZGdzdMT0JKTjVicHpfM08zUlhsSHd6djJsZmhQbFp0eF8tdw?oc=5
panjang artikel: 2025

Fetch isi artikel:  27%|██▋       | 668/2473 [11:47<2:46:22,  5.53s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxQMDV5X2Z5aV84Zkl3a1VKZFlqNXJCbVlsQ0gxVDNHcGZWZUJfSjdsblBPS0prSnlZSFBKQUlfMGF2N2xtcThlUmo5R0pzN2ZtWmtESXZCemNHVFF6RndGMTNsMnZDaHBtVkhJT1RWXy1sc3BzQ2dmbDVPMlpxR0dCangxTTVNZl9jQzdlcXdocUFDR1R5Z1lfLXFJblNha3l1Sjh2UWNRN3RVZm1TWU1ULXRKYWlOX29XRTNNQmRLUVd6MXfSAcgBQVVfeXFMTUtranVlVWM2MS1IM0pUWm05U25GNC0tVG54RW1jeDFkcXp4dU5MS1F1a3d2RGxDRERrZlZ3MUxrLXpfNGpxRTI2emYwbkFSeDZjRE9Pdm5NR05sREZLemdxT3dFcG50Q1NrUHdIZTdZdkdHMmY5dWY5bWZaeTc3VW5udmV2VXFaM3ZFXzl3UXNqU3pJbzFZV3pBMTlDY05WLVF3LS1nSkRnell5SjFzRTIzTE1oalJKM1ZIVElzVXBzWmdhWW9RRjE?oc=5
panjang artikel: 7550

Fetch isi artikel:  27%|██▋       | 669/2473 [11:51<2:36:15,  5.20s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxPclZ5dm9JUzZlaDZRUEM1OVhzQTBTWEJscTlIdWtzMTdnQWFxdHRsMV9jcXhGNjBibURJSFFNQ3BzOVZwbE5aSGJHREtKbFEtdFY3UkxIaTdkR2x1X0huX19wUjhiV3pfekt2RlVGTkZIZXZfeFY0RU9CRjhZV29nMWZLRkN6RlE2NFpSSXhQM3A3YVZ3TEZQSHhvUHExVHFwelRfZFVOM1FCanhDS2tyeHZGMDVtdw?oc=5
panjang artikel: 2151

Fetch isi artikel:  27%|██▋       | 670/2473 [11:56<2:30:31,  5.01s/it]

Fetching link: https://news.google.com/rss/articles/CBMiakFVX3lxTE5sYWFGXy11bkhHcnh3NWU1aTROWG5zalVxUUpKSm9YdmtGT2k4d016X2hJZ1FEZnFrOU9fZDNkdnE4dTFZM0F2eUJNQUhvVVctX3d4UXNXU0M4N1Y0OTJ5bHdBUkNIMGI3c3c?oc=5
panjang artikel: 7969

Fetch isi artikel:  27%|██▋       | 671/2473 [12:02<2:38:54,  5.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0wFBVV95cUxOdjJ6RHJQbmx3OWNKNTJJbHRBeFFIZDlHaTQtT19HOUFxNkJLU1lHOFRyTXpRZC1KbUVuYzk1aE5aTVA0ZlhvUVFDQ1ZHRjRiY0dEdjhLVWptdDQ1XzcwNThvYzliRFg0NEdORFJpM3A5c1k4VDhiZWtMSGJjc0ZRemUxTFlPbnNDMkN6RTRGUnFGMk5PNFllNk51YVlBeTFQVW1NTm1tN29OWW1Ic1drMzdhS25FaC1kV1J0aElDYkFSYzdLNGtkdDJBb2t3LXNCX2xR?oc=5
panjang artikel: 5068

Fetch isi artikel:  27%|██▋       | 672/2473 [12:07<2:34:20,  5.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxPdDVna1ZKRERJZjRqdDZkYWVyTHNZQ0ZfYjlNTUl1Z3c1R01YT295NDZrM19jUlRUV3ZnVXZSQ1hrQlQ2SC0ybWx5Q3ZvLTd5RXR3S3hJXy1pS1JpTkZkWWx0ekRsNDNYa1NCNEVTUlVCWW5OcnNFdklwejB2Q3RsUTVaLTNZTHo0d2Y4TmlDZVgzcTR6MlFtdE9WSmJIRVVnQ1RjbjZ2UVYyeGkxa2lGOHU3M0hzUXd4MHRF?oc=5
panjang artikel: 3800

Fetch isi artikel:  27%|██▋       | 673/2473 [12:10<2:20:14,  4.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxNdTJOanZYYnhSVXdlTTZTc013RTlnSXNkeHp1cFFpSFNrVEhzNUNjOWNWcUxEMVRKZkMtQWJLWlFBLWNJcXM2Z0g4SUpzZHJieDBIaEo4UExqZlo4TmFIaFc5UnpmYjF6LTllYlppb08tSW5Xa0FDTDZQbGo1X09LZW1iSnZKaEFKQXlfWVpYaWZlUmtDZVlZTUtOY0hhZXRyV2c5TFYtajJjWHdId1BwbTEzVHo0QdIBpgFBVV95cUxPNWpJMTFWX3V6WGJENGZiZHhJUmxwS1UtTWxzcmFxeEVKZlUwYUstM0U5NWVHZDlOM1p4NXlNclE0elVXWlItVllQb2hNMUFaYkdrY2FQMWdRWkUtZTh1M3VhM3pId25Db01jS1kxd2lXWjJ4amkwTXRfaHlFZzVNd0llbGJPeVEzOVhEMGxiWS1SRWNwMkd0aXh1WUJfLUlRbVdFajBB?oc=5
panjang artikel: 5470

Fetch isi artikel:  27%|██▋       | 674/2473 [12:15<2:16:24,  4.55s/it]

Fetching link: https://news.google.com/rss/articles/CBMijgFBVV95cUxOcHZLckpZdjY1ODE2dGJteVhBdVpMeFNDdGNOQmNHZDRNNUxJcWowMWlNejlmbHpWcUZ4VXNFVU5iWlB1UVFJWkxhS25HS0pTYW03aWxKWUZGOWR1b0pNRHU0V1pYc1l6VXVPa3lob2xLUmdncGxTNldHdTdiaUFvTnlSS25rWXZNRng3VHln?oc=5
panjang artikel: 5852

Fetch isi artikel:  27%|██▋       | 675/2473 [12:19<2:14:40,  4.49s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxPX3BGSm92bF96SVFJUkxUSFB3UTRySVFmZEJia1YxeE5JM2VBQ0czZzExM21MRWpTNVJGLTdIVVdXSnhWM2NrVUFzcDAzUjF4S1pib2hqaVRtNUVkZmVqWjQ1eFQ3bm1Ybmctb0t6U0ZHV25BMHFCRFhMY2dpZTIzZVRnLXBrZy1NWlFIajlVMzVLNjZUUWxtckw5WXUyX3NFMnV5WS1rRUM5dw?oc=5
panjang artikel: 3412

Fetch isi artikel:  27%|██▋       | 676/2473 [12:24<2:18:50,  4.64s/it]

Fetching link: https://news.google.com/rss/articles/CBMijwFBVV95cUxNa0Nub0huZ0k0b2dIb2wyNXJRUEltd2d5cFlrNS1EblFzcUxaQVpyd01LQUdGOE1mMzVzb0ZmOEtiQnR3NEZ6aTk3MEZJYTRPd0ZEMTk2UHREekVMMzFYazBQaWhYcWZfVExwRlBwLUowR1NvZ29VQ2x2blhjanM0enBacEVYaHVkRUIzRFhzWQ?oc=5
panjang artikel: 3884

Fetch isi artikel:  27%|██▋       | 677/2473 [12:28<2:16:34,  4.56s/it]

Fetching link: https://news.google.com/rss/articles/CBMiowFBVV95cUxQRDFRVlVWeW1yWnJNcWI1R2YySmdZVG5oVUV2M1Rkam5meHFPSGVKTmVjcTItM3ZwY1JFQVRGbXdEcThoS3FCQzdRSENEaW9zQzN5Z2wxOWJNNWVDOS1yb3o2dmpwb0dxcXNDNldiRmpSLXFHYjktMzBmRHJqZnpjYlFvNG55ekFBSmk4N1JDbkEwTXRMZ2ZYYUhIRlQ5a2ExTXZJ?oc=5
panjang artikel: 6062

Fetch isi artikel:  27%|██▋       | 678/2473 [12:32<2:11:59,  4.41s/it]

Fetching link: https://news.google.com/rss/articles/CBMibEFVX3lxTE9neFI1TkFkZE0yT19MeElfUWJjTDNodnE2Nk9Od2R5RzZWRjVEbVdVV1ctS25mTS1YRjFnaHFMaWxYLVNMbnl5U05XZzljNGFDR2xseE9vQW9iRVk4Q2FLd0VsbC0ybjNQczNqWA?oc=5
panjang artikel: 8883

Fetch isi artikel:  27%|██▋       | 679/2473 [12:37<2:16:35,  4.57s/it]

Fetching link: https://news.google.com/rss/articles/CBMic0FVX3lxTE0ydjdic2taZ05GalVxT3hLZ2FHaU52RVNiOFhoRDFjeFJzVExBMGIwNkEwT2pOOWJZMVVUNy1GQjRmNU01UU93amhVaVFicF9pSkFtdnRsV3Vnd2V1bmJQYV9aRWZXSkUxMFJCWFpnd3NRa28?oc=5
panjang artikel: 11224

Fetch isi artikel:  27%|██▋       | 680/2473 [12:41<2:12:35,  4.44s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxNYkhDbWdLRHYwVjNBZDVpR1VGRjVRUWd5bFRXNjNwdUlrMi1uSGQ3SExEY0FBTUt3XzlXQjRwMUlyeWhlcDFTc09adGxSMWEzSnQzdS1PdzgyVTlkck5EWndLeTdxdmwtS1V2ZUNzb3M5OThhT29sQTdreXk4VzQtT3BzeHh4MllobW0xd0tUY0dhS25WOXpmdXByVVgtY3JNRDE2RHVMSmhvcDNKNGFZblRvNk9qSnBxOVVvWldJd0N6UdIBxwFBVV95cUxNQmY0WWYwVHlFQXFIbUdJNXNRT2xacE9wZU9lWVVxRjlqX29yYk1ZRjRjS2k1dUNHX1FzUF9EcFJYNzVXU3psZy1SVjdtYzcwT05tSFlyU2ZfRTlxVktNZGp1aHM2NGJnU2F3R1djR2EyYkoyT1lqZ2Y3VTZmcUJnZVB4a2Q4MW1nT3ZjYzFmZWM4RC1rR1A3WWF6VmhNR3dsTV9KUVQyYmFZQUdmYzE2bG8tT1RhQlBfY0NNMTlMaE1KcVRENHJj?oc=5
panjang artikel: 3211

Fetch isi artikel:  28%|██▊       | 681/2473 [12:45<2:07:35,  4.27s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1wFBVV95cUxObVpfTjhWU2tHOHhXOW1rU1BnVXM3dWZVNjFWQzhCcUxXbVZHcE9TMG00VDlYcHhNeGJpUG9YUDZDdXBHN0FUNWhFYk41MVpwNUtZZGRVU01qWERDRkFSWEgwSUZWN2RYUU5iZ3RRb2cxdXI3QnpDd1pPME9OeC15M3BnVkxiQXlKZk92VWx4Mm9KTG5tV2tTeHFBOXpxajJ0U0drb0doSVNEaHdMZjVzQlUtczY1LXdWWkduZVV2aERGd0FOYjJOUWVSc0s0cjNqUjNyUmZ5RdIBxAFBVV95cUxOcFpQRDBFRmVuUlBGRlMwM0FRVUlGMFU4ZGVwUzY3bHczOWpqb1c2MzI3Q0g1TlNhdkliVVVIYkNKTGdLbVV0OTM1M3R2RGlyX1ZRXzk4cHFvVXpBNmVsODA2azJVNWdMeWtFTXoxZ3hsY0FOdUhyaUFWaV9mT3Q5Rjg3UE9wSmZkNGkwY2tKS25pcEEzZGFWd2M5SnBwNU9lQURGb3BxRUxsUmlGRTFpUUo0NzlqZTZxMm5ubDdBUGN4ejEz?oc=5
panjang artikel: 1986

Fetch isi artikel:  28%|██▊       | 682/2473 [12:50<2:08:25,  4.30s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxOUWNIOUF0Rml3Tk5mRjJSdnlQMzd6clZ4UGRyVktIRXVIaWRWMzgwUGhkbFhFa0xGWk5GeXBwVFpBWjJsZnA4WGszVnp4X3JLOUJoQWZTdHFTTVB2R3UyWTFzWFQ4U0RpbjAtMDNiQW9TYS10V3cxekhRVVdZZWdReWI1a1pBTllEUDg5SGQ2WUdUWGlDSjJBSUpCd0xyLWNqSnRVZkE1ZmZKNVFtUFE?oc=5
panjang artikel: 5590

Fetch isi artikel:  28%|██▊       | 683/2473 [12:53<2:02:59,  4.12s/it]

Fetching link: https://news.google.com/rss/articles/CBMigAFBVV95cUxPSlBiTlVQVk1KbzFlNVBkVjFIenA5N0VDY29MWFJXTks5eWY5STJhR2tpS0xRSVNWNjYxQ1Bhc2p3LWxKeW9sMExxSlVsXzhrR1ZDdEViZ3dBZTJxYkdVOU5Nd3p3TDVITkVBc3dmOERTZWxsN0NKaFBobEF4eTlIWg?oc=5
panjang artikel: 7529

Fetch isi artikel:  28%|██▊       | 684/2473 [12:58<2:04:58,  4.19s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxNQVZBMjRQUUtoYXpHTEtSZXk2WFhucmp4UGZTYmpIZnVhaTBPY0RQYjBzQWp2M2dTNE41TWx0YWhJZkFTUGlCZjFBdUwycjVSX0NKUzhLcS12NTVHdkxZcE5xUkNwb0JrRzhrd3pOZlZzRi1OVURQdUJPYjdET0xpVnllSjVBS3laLUtoVHhsajdtNXAyejI5cWQtTDF2U2d6LV9CWU0tcFXSAa4BQVVfeXFMT0RTRFpCS0F3YmxKUXJHSHB1M1QzXzFmblhxdm5qeDJxcWhjem9PSWtLZm1TUXhtTjBvVEs0UWd0TDhSRUxyZ29TWmxOWlRrelBNOEpucC05TGNPNFVQRjJxZktnVzhGd1hIQlhiTjhMZjVLWkxseWhhVGhKbTV0OUNkYUZJUGN3Sng1dkt1VFkzYnBBSlVFLWczaDZBdGpadndCcG1uVVBhRG5JY3JB?oc=5
panjang artikel: 4284

Fetch isi artikel:  28%|██▊       | 685/2473 [13:02<2:02:22,  4.11s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwwFBVV95cUxNZTFFc21MbFZkUzlQUC1Ka3o3V1hqb2pOSVdLZElfTVdENEI0dVdTMmJmbmNCSVFyU0pnRjhfV052SWhEcDVKM0tNTkZiaGh5WFJjb2lldWt6VGJVY3BVTmpKUFd5M1JJU3h4U1ZkdEQyQVU4Q0lNd3FzczVrd3RjeEZLUzBxYVFid3E2dGVmYkxhVTVLXzltSnU2RlhWY093TVVVV0FnSHBmQTZlLVI2VUl1SEVVOTZ5ZXc2Q1gwOFpISFXSAbMBQVVfeXFMTVRXYXotOFhVem5DSS1sMER3N0M2cUZQdHJLQ1BncWl0QlVXUHZvQTJBcHRSUEQzcUdXdXlRal9ZemhybnBRS3E0QlNfTko1SDVWbDlyQWhpaVhXQlhPTDVXUkNrSUlxQzE4R2VteTRWNndydjlLTkFxY2dwRjJFNUJ2d1BNYnp6ZXRjMzBzUm1TZVN1Um8yLTJ2XzRBYVljNEtaQ2NYUDhFOUlTcHM2QXp0Rk0?oc=5
panjang artikel: 4637

Fetch isi artikel:  28%|██▊       | 686/2473 [13:06<2:04:05,  4.17s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxOeEItbjMzVkZaZUt3cDRGU05xMTEtbEFZYTZtelhCX0xfSDhYc2tkTDk1Q21yY3RVTmwyZTJsQ25GX3RrZURBLVZXekRveEhqblhIWHBmMi1RbE94TFNReHQ0d0pzR01EYUMyLVdObmJZXzc0VkNZUG5GN1BqMmhVcG5OUzNxdS15X2t6SXFBM0twUjFVeExNVEpxRWxnUHBzQlc3anhaN2Q3UnJCbU5KbdIBtgFBVV95cUxOSlZQZ1cwUzFHcjZhSFRva3hVQmtEOGZpME5vYkxqd1d3RzRYMGRXMDQ1Z1ZBbnZtS2U1QjRXZXpwTjVKaFEzWW9UWVMtUjlLbFFKblZPT0NBTUV0MUN4YzYxX1BhTnZ6eV9HdGVtQlJqOFNLTWdZd0NjZVR1TjdrRk5YcHpkOXBFdGFUZmEwSmplSzhfRzNGemZ2ckRwUTRpUGlVRGk4dmRseG01ckZhcW1ZaDN4dw?oc=5
panjang artikel: 5215

Fetch isi artikel:  28%|██▊       | 687/2473 [13:10<2:03:19,  4.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMixwFBVV95cUxQSjZ3OFJwNDJHX2tpSFdCSGdBWXpCQTdyUkJ1XzBHMGVPclFSckdTVGJkLVNDdVlqSk9ld2J1bXVxMWZrSUhQdmhfeVdqeU8xbzBOdVdTcFFxa2oyVE9UbEFNU2IxNmxDb1c0RU5FdTNzUXM2cDBzTm9ZN0hETi0zdXJFeEI1NmxWRHRYUG5WWXE3TU1Bd19xa25mVGxKMzFyYzl6VlNCSzNNQmtKU21jV21LeTYzS3p0M1EzVWtkWV9vaktQakI00gHMAUFVX3lxTE92MjZ0OTg2VkFmSXpURlEyOGRzdVY2NWExeEM4N0YycFg4UkRyQy1ELUVvUXhLcXRnT0JsWHRCVkJUdnlRZ0VEdWdOWGlHcTdxUHpwRXJkVDhLQmhpZHhrN04xR1l6a0g4emM3QTlNSUdpb245R0k3UXJEZWZRZXBHRnRKbFF1dnpJaFo1M1JVMGg3RzdTaXR4c1doaWw0VWtqSm9kVXhScGpIVU1aakkzbkpGLUNCZjFNRTg1NkpGNHhua080VGk5QWpCag?oc=5
panjang artikel: 3516

Fetch isi artikel:  28%|██▊       | 688/2473 [13:15<2:07:36,  4.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMibEFVX3lxTE5jVmpXMW5UcnhPaVB3c2ZtZTBqS1lXNm9QT2FPOEVFcVVrRlpCTDFFQnFEMURtbmhBd3NpRXc3cW5keVdfVnVnYkRsSi0xZzV2Q3VaSWpqS3VPU0E4ZVZYeXpiNXJCQS04MEZGSg?oc=5
panjang artikel: 2685

Fetch isi artikel:  28%|██▊       | 689/2473 [13:20<2:12:52,  4.47s/it]

Fetching link: https://news.google.com/rss/articles/CBMi3gFBVV95cUxNbGZfdkJyVzNsek1Zel9NYkF1Wm5telNuWG5HMzJfb3g4N1NOd2RUazhna2dsWk1iVEhJTkxHa09hOWRSUFRHVnRYRzhPRmxpVlRmYUNRbkZnVzlKaDl0SkktLXlDRVhGZ3h4X0g4R2VuNGNScGtVOTUxdVlVdHJpMllmQU85cEVEX2trLXJOVEZ5cDRTMDVtdlA1WVBQaHVpQ2lRU1otYnVrRTlNTU9iUzdTNTZRRWtaLXV3a2NoeVJxZ2lZcjlMZzhqVlJFSEdmYmFySGlKVHktRzlXbmfSAdMBQVVfeXFMUDY3XzFZMmJjOFZ3N01MZzlHeFpVME5wUmlaZm1qSkJ5MHNqbmhPNXMwNG1NdUdyaEdEajlGQW9HSXlQZVJvZ3lvcXVCYXBXNjlObEZzZ2p1eEtwdjJLR3hTcHM2WTFGSjRGUTBzN1BlcXZ6ekxWVU9PNEtoWGhFY1RNU0JEUExWS0VmVnBpRnNCUWRYeFJlcWljR0tqZzNrUFh2VE1IUk5CdGlFWGdTLXJ4VVpsVFRXNkJLdFpTd2J6c0lVT2IxU3hXVDloNFdQR2txaw?oc=5
panjang artikel: 5083

Fetch isi artikel:  28%|██▊       | 690/2473 [13:23<2:06:08,  4.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxQaTYzOEdWMHdRSC1QQXVad0NzU0NUNC1uNHZMUjVwcFRuNGhCWWNBQ2dsaFp0RjU2aFpLTUVBQW9wZmRyQTltVkUwUWhaZjlpbThlSGx3Z3FLcnlzVUg1dWExMy1LTnFoT0hHYjhCUXJ0eGFfekZGYWVSeTl2RkxKNVdhVW9mU28tTUtrQzNlYl82eW9SZ1hnc2Qwc2lLb0otbnJrTExsQ1V4TlNKWTZYRTU3RjRBUWtuOVdpVmN0OWhPSm5nUzZ2NVliV1lGMUtF?oc=5
panjang artikel: 4489

Fetch isi artikel:  28%|██▊       | 691/2473 [13:27<2:05:45,  4.23s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxQX05CdTZEYnJRQVp1aXlyckdRUEQtLUtlODBZZFZ6MkVvREU3SUtib2FkbTVFRzg1OXlLMTZPUkp4S2RyR3NhaGFUNEFuV0FwRlotUXpIMWdIVkh1V2hVSXVRTTBoOG1hVW5hR2tfWk1hbG5neEs4cUJxb1Q1cm5CUzJNTzh3aWNNdHdkYTBSMkdDNnNfOUNLTERQT2RJM2VqS2ZRWjdrZ1l5cjBOR0NBVzlWajF4VkZVWW5KakdMWndrcEZ1OXRFSkpB0gGvAUFVX3lxTE1XVkFfUFpYWDJScWVZV19Hb2pGTjZEVzVDOW1LZGkyRGlFdGdMM1BiYnY2ckZrSEk1OTBJVWhFMjdNbVVBdDJiLWdoaXl6UTNPdFdkUFdwbm91cEEwenZxME5SRmxTUkd3NEZjQWJrcE5KNHk3cXFQTzUtc0lhZnphQzNLc2M2b3cxcmNULW44OXBIMGxUSmNMVFEwTTE2SS1EWnEyT0JCNUlacTlITzQ?oc=5
panjang artikel: 2006

Fetch isi artikel:  28%|██▊       | 692/2473 [13:34<2:28:58,  5.02s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxQck1uTndlemZ1Z2ZWNkhTZ0ZWNVp6a0RORXQ5ODlRUEtjSXBteXhobzFQaUU3TkNobXY1b3JpVjl1OW51bnYwSnZuMUd2TGd3UkNnRWZUMGlaZHRCQ3o1a2g3cC1pamVZZWF5R0E2RVNhN3NGNXVac0Y3UFNGbUw4U3YyNnFJNWQ5Rzc0TkJBWGJqU1lTVFhseVJxOU1DcG41VUHSAacBQVVfeXFMTnJKNjdSNk9nemhtaFRVd1pJSU04MnRoYnRQX3NrSldTNUtTQm93Y2dWcDNjQjU4ZmNja1o2UmpvQ1hVVk5qREpmanYwLTJha3FXWVJPbFkzWl9DVWZIcDVpT1ZrcXJuM0UwcUNJa0g2MHhIeFZjcUlHMnBDX1Jja2RaODFZai1vR29qZWRQMFBPYVhYdzZ3cmNwM0lpVjRDSG5nZDhJLVU?oc=5
panjang artikel: 140

Fetch isi artikel:  28%|██▊       | 693/2473 [13:38<2:17:36,  4.64s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxNYWhxd21pcmt4dFR3YllUSEhhWlZsU1Q2S2Z0bE0xVEYtdWxLeldUQ1NzaWgwMzVKSVlNb1FzQ1Z1YlNPUC1zMzBSRXNlVkZJYm5FamNfSTI1VDNObngzMnpDTy1SclpJRzVyQ2JmTndWRWFESnNGSk5Edm80NEwtbC1FVnVMVU51d2dhdUFhTEdPajRDbGEzWWpR0gGfAUFVX3lxTE9RREFOS1hiZWc4Yy10cTl6a1JiT0pTUlJRVThXSzVwWFZuOWo4bGZvbzJnUURKRWFxSkJKd3JONWJUTHU0YThrVy1aOXFxYkpERmoxNWdFZTB1d3RhYkZUdVJIVkJHNC1ReDhHVlB3RWdUUUJZTzF2cnh5RXpnZndQb1dIcGUyQXJrbC1nRVpySWx6eExNV3I3XzIwZmxTaw?oc=5
panjang artikel: 146

Fetch isi artikel:  28%|██▊       | 694/2473 [13:42<2:11:44,  4.44s/it]

Fetching link: https://news.google.com/rss/articles/CBMipgFBVV95cUxQQWF0U2FfWFNNeVNFSldSWEZub3g5UWJJTFYweE93OUJoWGVUbDBPYUczUjY4ckRnV2tqQy1OQ0NCbjZWSFktTF8yaTFfQTdlNWdjRThqZmowMUpXZXFnbUlCX09vM1p4ckdhdndPOXQ5N2ZWem0wUVZWNUV4QVFXcUcwSE9oUXZ0Q01WUmg2WW8xMnVMeVN6UEFkQ3JaQ0MxcWJkUUZn0gGrAUFVX3lxTFAtRjZFeUhQWlhkX3h5OWxTam0wV3RQUFJfQjZSdU9sM0ZzX0p3V19EQ0cxdzdrUkoxejZYRFRjTDJOMi1LQWdoVFpZY280ZXZ2Qm94YVhDWlJJOFlsTE43NVZtOExmU1ZnRTNJV2ZuQUduYVlBQ1J2U0JOd3dZbWhzclQ2WnF1QWtoaC1QS0M2cGJPazBhUGdlS1NMYXU3R3Z0dGN4a2VEeVpZaw?oc=5
panjang artikel: 145

Fetch isi artikel:  28%|██▊       | 695/2473 [13:46<2:08:38,  4.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxQNC0zQnRrMWZpY1ZtajdVdVZoMVVzb1VtbnRPcXprUnR5QkgxWmVWTWRJcjVVbmZYY2JIZkU4U05XSUd4QmxyajE5MjBGaGlDWFpmOC0xREtSRFlvM2tOT21aRTNoMjdpamNOUmpPRkJiTjZFUE1mWE9BLV9jeVJTaUQ2cTZ6UVczQzhRS200T3BGVVpTMGZraWZLV185TEthaUlLTlVwVkNpR0Rrd0JmRkIyM0xkalBzckptRGVhRlliLWpEcUZGMVR30gHPAUFVX3lxTE1aOEVpRmcxOHJBNDJ6Rk81U0hKaGtYeUxpN09uN0RKS0NSUmtKblFtb0l4cXR2MlVVb1NMSDZ5R1pSUXdKaENacHpsci1nQXZtdVRQdnYySFJBOGNmanVEM29uNnVwRzJvM3ZJSXR6MGpDM3FqY0tTdERkamJHeFp2Nk9SQzNSYzl2YXQxZFJEcGV2ajRNVTJxdEZmOUg0QXY0am03TU84SUNzeERXZ2RrT0RURVMyeUw5LWFOQzdRUG54WmtSNHlyWkdyUDhMaw?oc=5
panjang artikel: 2716

Fetch isi artikel:  28%|██▊       | 696/2473 [13:50<2:05:54,  4.25s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxONURlajZtc0VXVGJmNlllWEF5QktRWjZDNWlEZXlCLWtaSXRhU2J3MHNzX1psYWJsTGZZcFpMSTZQYXVsTGZCbGM4MjJSZ0xMQjNHSTZOb0ZmakExa0hTdXBhWWdYSG5tU1ByVHJTRlc1ai1QdWRQVHAxVEdJYmNDbURVMVRSbktqR0tpQnB0bEdJX0tIZlJDam1ZcnFqSDlHZDBjYWh4WnJYcWpzWlhESVhPcHhwVGFBdEZGZTBnY9IBxAFBVV95cUxPZ3p6UGgxM09mbDJ5amNpa1g1X1M2YU5qTk5PNVV4YzFtSS1xNDBZVGprU0ZzUHpJZjhacVpUWGhIRlM3aGRBY256dlpRczJ5RGtfYVlxellFNlR0MnduMnNndGtLR3d5eXVmcDJ3eTUtVGFtSFNLOEx5OG9XLVo5X2lnSER4MGQ1UkhzVG1qeDVKSndGaGRMN1ctWnhyRk1KX0NnMFJvXzB4YWdwX3FYcVRNMjBjRFd2dVBGRGFhd2tOejFz?oc=5
panjang artikel: 145

Fetch isi artikel:  28%|██▊       | 697/2473 [13:54<2:02:10,  4.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxQdllndzV1WXlIaW5nX28wMmp5T0dpTUpaME9fUERWUTRSeVVPQWFjZVZtd2tibVg2ZkRIbVZfN3dOdHlscjRuZlZtdzV1cWkzQlNZeE5mSU1qNGlBQnl1OGVDUFBFMG9qSzhoU3hWWW9rT3hSWERyU3BVc2xPWkRMaVNFeDJjcjJIaTJtTDE5bm82em9GVG8zOTJDVXF4NUtMaFpvVUZFa0hZUXfSAbABQVVfeXFMUHc2aWphS1BoLWJ3cGo1RkVxWVJTVHRZZ2JFdjdKRW04NGZZWDVORFFwZ0liZ29nRkpIVnJTemZSVmVBQ0p3OGRRVnRhSmlhd1JhRTFNLXlxNGkxeTN5QXhZSG1BS3F2d2h6TVF4eEpyMmZ4ZzdlYlpnTERHekJ2TTYzTF9VQ3hRSjYxTWQ3dmtOOFFYZkZrQXhOUGZnc1g5aXBPbDFjNjNBZEp4RThQOFY?oc=5
panjang artikel: 2678

Fetch isi artikel:  28%|██▊       | 698/2473 [13:59<2:07:49,  4.32s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxPN0ktVTJaaHg1a0RhWXZhbjZoNERoaW01UmdMVnBXU0ROUEtLQU12THRWRm90aXk0XzNkYkpOUGJoU2UzREtvNzNNZGsxQnlaSktBRUlycXR1Yl9UZkRYQ25nYkRzeTJ5Q0tSWHRIY0dtZ1Y3ZllfbzdGYUVvRklnQWlqNzl6bnJBNmNyZmk4ZEZLLVZYR2pobldKOTVULU9rR3d4a0ZoOUwzX0FuYkl4RTFqUk54Vy15ZXFkc2hTOEJhd19H?oc=5
panjang artikel: 2674

Fetch isi artikel:  28%|██▊       | 699/2473 [14:03<2:05:23,  4.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxNcENrZzBsV05lVFBIZGtkM2IyRjJXcF9qN1hTOFhxRmc0RTJzeVhkWjBOaEU4S3R6NGt2akxicHdGNVhNX1lXSXhLV3VrMlRwMGJ4UFg3SndNb1l6RnpObGdWdWUyVV9iRFpsUDNzWG5nNVpDVHB5cmJETkpGTm94aXlsZUU1cGZWZHpWazNKU05fYTFLNEs5NjdsR0xpMjV6MkgyQkhuNzZBMW5lQjRZV2UyWUNlRDdoSTRUb1YzQ0RmZjZxUXJEVXRYVm5LZms?oc=5
panjang artikel: 3804

Fetch isi artikel:  28%|██▊       | 700/2473 [14:07<2:07:51,  4.33s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxPbXpkZjJBZnpBbWN0ODJ5MTZQd0FTa2Z4by1rb2o3R0k1dUxMUkYxRWxGcUpPcjctX1VMUTJoX1NSWHBtallfdFZObEJTSlNRc3RLVmZTdS0tZG5IUTRhVlVCNEpXNWFFbk4tNWtKR29Zb1R4STFINXhiQ3JDZ01UdVJ2MlZ4ZFJiTklSZm9HNlBFTXhxakoyQ2k2ZEttaFdZb1JDN2lPWFltYTFCMVNFallyY2U4ZTIzWDNiTHZLN2ZhdzhtRTVLdHBKWXBvQQ?oc=5
panjang artikel: 3542

Fetch isi artikel:  28%|██▊       | 701/2473 [14:12<2:12:08,  4.47s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0gFBVV95cUxPZkxVWFFwd3J0d093MEt3aXVNSjR1cjB4OWRwY2Q2N2wzRGhkb1JHbUg0ZTRnMzVEbzZFZVNtWFBwVGo4cVQ3YVZDYUdCWFRrWjlPMHVzdTJyTVc4TWc1clZDQ3NTM1pPODRwWndCbzN3YXJ2MGY3TXZCVS0zQzRaeGw3RDFGYlh1Y1pyOFNBckgzTjBDSmpqa0R6MzhLMENJTndlU3pHNVJRbk0yc2JiX3BwRUxSbjdmOU80MHNWelBGaUppUnBrOFJUZzROT01pb0E?oc=5
panjang artikel: 5196

Fetch isi artikel:  28%|██▊       | 702/2473 [14:16<2:05:42,  4.26s/it]

Fetching link: https://news.google.com/rss/articles/CBMivgFBVV95cUxNcFItTWE0MVNVa25KM2NSWEZEY1YwQTdWMVViMVFzVlZaUTgzaDZZNUdaTk1VQlNjWXQ4TEc0OTdSazhiYmFwQm5IOHBjUncyVVNuVVJqRU5BUDZnMzhRMzNGQkJuSzU4SU1DdXp4ZlJHajI0Um91SGFhbFppQ3luRW1fMDRkdDh5V2tzWHV6MklxYWw0RGJQTlNJMkZyUjVxT3ZzelhKZGxIaVBYWVl3SHRjQ1R1SVN4VDZYb3NR?oc=5
panjang artikel: 4175

Fetch isi artikel:  28%|██▊       | 703/2473 [14:20<2:03:02,  4.17s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxONGV5SVRJWVNGcE5ydDlhWVhnLW1IXzJtenJJeldZR0tUQ3JEZ0JKTm9tZnlhQ09JNVF5cEdIak5BRFg2WkN4OHhpQ2hQSmNkaVhSRExhVVBPYjA1LUdZaDNMalljMzVtRVBwYUtTNHRZdlp3Q3doaDUyUG92UmlBVEtSczVOdTh4S0R2VEJIMUVERTk0eGVMRTVGZVRjZmxRZzV2NQ?oc=5
panjang artikel: 3500

Fetch isi artikel:  28%|██▊       | 704/2473 [14:25<2:14:04,  4.55s/it]

Fetching link: https://news.google.com/rss/articles/CBMi5AFBVV95cUxPUWZ6Zm45cjd6MFBBZENuMWpxMGhPSkRJR1ZQNHQxVGlUbXUxMUVLallwS0VycWlKSFJQaDlBLUlMWjJoOFg3SFFmeDF3cXRPa2ZBUmJnd2IyX21VUENWckFwSUdJU2dFUEI1d210QVppcmloYjhaY2dnMWdxejlSRjdNNE1hSnl1Qnh3X0xOdy1HVmhhYm1UZnNBcEFjMmVZNTZmekhJcUNiV3hMd1ZlX1NoNDdmcHVPbWNoVi1oMzJUUWloY2Yta2QzSkRoZV9rQVBBRDZScWNRYlR3UkdJNFhpeHo?oc=5
panjang artikel: 3062

Fetch isi artikel:  29%|██▊       | 705/2473 [14:30<2:11:03,  4.45s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxPelk3MFUwUzV3SXhIRDdNaG05bEhNV0d0eWJSc2JranJoTlg4ak5wdHlUU0hFUzkyalZuNUhha3NQc05KVTQ0RHdmZnhQcVFQZzFNa3dRazRtY09XVHpKRnBTY1NKUm9ldXhBMk5KN3F3NExBejNCVi02UkRfWVBiSEtVWF9KRXJ0alNGTkRxeTJJeGtSNDh2V1R3WXRxZldwZUFOdA?oc=5
panjang artikel: 4499

Fetch isi artikel:  29%|██▊       | 706/2473 [14:34<2:09:55,  4.41s/it]

Fetching link: https://news.google.com/rss/articles/CBMizwFBVV95cUxOcFZMQzVYcWRVYUdubENQaDAyRDFMVUtGTUJvdHRXb1owWXplZ0JqdFZZSHh5UE4wM05zbFJjWHVSUk5qZWZqQnRzcXJPQXBrcVBpNjQwdFZJa2s1VWhtT19wVEh1SFluLURjT2xIVDBoV3RCLU5id3owS2FqN2VmcWRpSElzRWtXbk0xcGJ4RVItamxHWTJjakdBMGJzNmhTallSaU51cGR2UG5tRFlpTFUyNFJ3RGVTWnpYWGdXUWtpZkMwZlVIZkZBU010V0k?oc=5
panjang artikel: 0

Fetch isi artikel:  29%|██▊       | 707/2473 [14:41<2:32:46,  5.19s/it]

Fetching link: https://news.google.com/rss/articles/CBMiywFBVV95cUxQV1hobDlpUGY3MFlzN0N6VHlsdXVNU25BOUlvX1hnNG1hbEh0YVhRNTBya0wzcFNYdnZKSlpUM1FUX2ZvaTJWSE1NMTdSbW9WS2RyMGxHbFFmbEhlRWdCNUpkQmR2U1RKNjNSdmFOQjFtQ3dmbFZwN0tRRGRtRkxSV1lRd0Z4UHFibUNzcVFJMll2UW5qTVpGX2JsSC1lUzk5OFpRWW9kUlBSakp6VWJNWEtGcUx3NG12Zy1wV3lqUTBWd2dyQ2Zoc1F3ONIB0AFBVV95cUxPdWFpQ21KTk9ydUl4THVheWxDSk85b3FJUDZoenh6b0htUlZneDJ5MEFUTEJyT3lkdmtGQ0lmTmROU2I5b2c2UnpqaHRwZjRuY3dOU3JxZHBESzAtcFM3cnRnQVpXLUZocms4TFlXeFZWZEYyVmdsZ0xXMU45WnVVZTBpMEZOZkQxWVRvTjVoZ0RVTEdzaGo1N0tzSXRiVnhlSDFCQkN2VzMxb0EzVW9kQzFqRHVEczB2dXppN3ZCZE9rb2JKWmlPOTZsUGduZkhI?oc=5
panjang artikel: 2067

Fetch isi artikel:  29%|██▊       | 708/2473 [14:45<2:24:25,  4.91s/it]

Fetching link: https://news.google.com/rss/articles/CBMijgFBVV95cUxNOG82UDlVZmtoVVE3TDZzT29rQjBNcV9STWhsSzZURGJTVzNvaVF0M1NIX0REdVlaZ1VyMDJWQzZscUFLY0tNZG9oc1U1cmwtUDBfUEtSY0NydFN5NmpJVWVpd0pWd05GVGpVZkhnNE1zbWNQMFU1ZXpLTC1PMmo4UkZvTV9fdXZIZXkyNEN3?oc=5
panjang artikel: 500

Fetch isi artikel:  29%|██▊       | 709/2473 [14:53<2:47:55,  5.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMibEFVX3lxTE9XallaOV9hSU84eE9Qa0REakZ0bzVmMmJEM1o3NlVYWThwSUwwRGxoeDhzbFQtcUhjZnhGQUVRbVlTZDJSUUJxX2ZlR2Q5RXZwV2ZVUXRWc0hHY3Vod3Q2TkxYTlNiQUtjMmNnVA?oc=5
panjang artikel: 11160

Fetch isi artikel:  29%|██▊       | 710/2473 [14:57<2:38:10,  5.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqAFBVV95cUxNaW1Hamt1SW01dllnRXhEeEhsYmw2Um1qb3B6MW04U0cwbjVHTFFXVnJlSWQ0aEd5b1kzUmtnSUVTQzdmbkRJWE5sUlg2VG9JWEswcTdCbTV5azh1b2pnWmZYeTRuTjNpRF95N19BLXI3Uko2RDAtSks2WEtXdngtWVMyd0RrQUdwZklRT3Z4NlhLVVBpZGRLSmxxei1kQ1ljTjBrdXZxc2o?oc=5
panjang artikel: 2662

Fetch isi artikel:  29%|██▉       | 711/2473 [15:09<3:36:52,  7.39s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwgFBVV95cUxOQW9zMDZxb2ZvSkptMkhaZjFUM0ZmajVYRVdvOV9PM3ZJR0pMNVRlLWNpeVJZYm83aTVjRzk4NUQ2SHFJc0gzR2Y0Si1DVmdEMnRoX0pmejlUcExrcmlQZGlxV3FLcHRySjEwSTVrWmk4WVJJbjVWWm1zbEsxdmplNTJRdGtnNW1haktjX1hvU2gzZGozSUVBT0F6QlotQzNBTF9nbHUtbV9wVVZIdzhCNUNDaUYybHFhaGczM2RzVEx4UQ?oc=5
panjang artikel: 2632

Fetch isi artikel:  29%|██▉       | 712/2473 [15:16<3:29:46,  7.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMizAFBVV95cUxOTVpaOE0xWkRXQkVnMUFZX2h4eGhnQTBoS2c0UEJKM3l1Rm05Y0RjN3VGNGNhWldWbVdWU1RUdTlpMlFneE9ONlgwYTZmRnhXbzZONU1OVlF4dHY3M29xakpmeDhxT0ttYUJnR0xQUGl5Zl8zVWVhem9LajhFNFloNlBHeUhyaFJwUnZER2tLSm9sWUxCSlA5Zmpwd1VrTjFUUHVtSm85ZWZMdFM0cWdLRUNxYjg2T2dhNjJGcWJ5dkl2aHk3M0ZfMnpuV3c?oc=5
panjang artikel: 3019

Fetch isi artikel:  29%|██▉       | 713/2473 [15:30<4:25:58,  9.07s/it]

Fetching link: https://news.google.com/rss/articles/CBMiiAFBVV95cUxQUlVCLUpzMWdFZjZpaElmazNPdGhsc292TWxoa1VqSGtHdkE3SHVPRmtZS1FBN3hnLU1iUXF2Mlh6V3BtNW9WODRaZWVDMFkxMDZUbV92U0Y1ZFFKaUtCdHhRWnRzUEFOSExtNnduQklwbWw1Wm4yM0FyTzNnTnBRbGpjM3QySTN5?oc=5
panjang artikel: 0

Fetch isi artikel:  29%|██▉       | 714/2473 [15:39<4:24:52,  9.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMilgFBVV95cUxPaGxBV0lBTEN3SmYtUWlFa1p5UVhTUUJoWEJrbTJMM3hVRHhTWVhRcHhBWHZ1eC1QODR4RVptNWozejVFbGNlWW5wYlR1UVk1YnFkQ3V6M2RGMjdwa3ZLMzhwMWNuNDVMaUhDMzRaOE1nNERuSDBQelBKSHlNLWRvc2ZwNG9KZ19scmpCSTZzVlFYb203eEE?oc=5
panjang artikel: 2365

Fetch isi artikel:  29%|██▉       | 715/2473 [15:43<3:45:49,  7.71s/it]

Fetching link: https://news.google.com/rss/articles/CBMitAFBVV95cUxQcWxPcDQyd3YzZjJ5TkItbXlpT3hSRUZ4b25CTl9qbkNscDJyZ2YxeTVJSFJwMUlyTUprU2duSkxUdE1PUnJJSEltSGczQjFqWTdqc05lUkk4dnhqVzZib3BQY0VJUXBKcnp5UGl4WWxtUVdBUU1SRkxqcm5rMlRoeE5xWFdOMWc5WlZUeE42TENpSFVpai1ZX29vOVJTalNsMG9UUTV0OGZEakVDZFh2M0UwSkPSAboBQVVfeXFMUF9tbkItVTQxWUJPT2hyQVRKeDZYYV9PLXVNQWhqR2VYUjcxYzNiT1VHenJWaUxXWnI3VkFScGxYMXhSTTdRYWR0bUNjS0RqQ3JndWdHVlV1NVUtSWpSQzM0RkFyUjg5S0U1QXRjUUJ5MnVOelotTWkxVVc2M1owdTM2RGpYb0hUVTBEZVpaVnRoU2REZVBoR2d0Q2ZxRlRFQjJBRUVhV3BXMmc2QzVMeE5xSzVZLU9GQnVn?oc=5
panjang artikel: 4469

Fetch isi artikel:  29%|██▉       | 716/2473 [15:47<3:12:41,  6.58s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxNVnkxX2NDWGJybVI4SWZwVGNCTVJweUdGb255T0tLeEpPYmNtdzNsbWV6OHk4Y0dmeVNfUll3Y1o5UkpzUGZ2VExic2RlNzBibkI3Y0VDbjc0S2FxQk5WM3l6S3hxSVNpM3NvWnBhNFNfOUxZb3ZNTk4zUk1tWTVfU24yU29aYWlPVXROcy1NaXdkc1VCeG1JUlhVR3djc0lZb2E4TmpyMmNjZw?oc=5
panjang artikel: 2365

Fetch isi artikel:  29%|██▉       | 717/2473 [15:54<3:17:57,  6.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxNWldHZmZpZWcyNk9HcjdxV3h6OG9zRXRscHVfMGc3Vm5pZEJ6cHIweF9qMHNEVlVPX2p5WGVKR0RYRDJJTXJXN1Mzc1BBRDdtZThJcFNIT2NoemlrNTNBaDR1RUNRVkVqVGdQVWUxZDgxQ0s2bEJVRFdPWHA3SmdGUHBFdDRRb0dQQmxRbkxpMDdEQWJrNTZLS2ZvUFFzMXJzXzFQYWJ6REpFb01abk9Z?oc=5
panjang artikel: 0

Fetch isi artikel:  29%|██▉       | 718/2473 [16:01<3:20:52,  6.87s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0wFBVV95cUxORDNUZVlwWEwxN2o5enMzN3FIRDVucFFmRU8xb2M2WWYtMmx2TzBLRDNic08zbTNmcktMR2NRZzAwU0N1WWswbDY5dkg0cHNDRFNCYl8yOHJBLXdZVVY5alZvR1hFdTloQXM1c0dXQThGazBQUXRSanFac2ltSjRiZER2dUxEYlVOZXphSEh3YXNzbWxIeUZKRnNNZFJwbGFoTE0xQVlOYzJ2UmFWYTNjdWkxTFFicHNvSFkyeHJfTjU1OTVkQ3N4V2lLNkZRcE13OTBz?oc=5
panjang artikel: 4582

Fetch isi artikel:  29%|██▉       | 719/2473 [16:05<2:53:53,  5.95s/it]

Fetching link: https://news.google.com/rss/articles/CBMiugFBVV95cUxPdURaMXZYWjhBMExraThKRWZzVVZhN1hyUjFJVFFjZ19wMU1QVVlUdjR3MG9Wc0RIWHJaZWotUGJNcVNuVks4Z1RkZzRXN19jSFJhZ1p2dWV4U1VsNF9UYmtjN0NMb20wVlB6M3dZM1BwbzRBMWZRSEdYRlFCVE1YTE51TThRMldueUV3RDhkeW96ZkhYNFNWc2NRcl9tUnhqLTIyaUR6em9xNFcxY0Mydl93dFRZaUdKMHc?oc=5
panjang artikel: 2198

Fetch isi artikel:  29%|██▉       | 720/2473 [16:13<3:13:19,  6.62s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxQSXE2eDhDSmRWTVF2b3ZGbS11VC1IVElSaXR1QlI2WENRMHY1SzVuQUFsVHhvVXZ1X013TVo5Y1N0R1VadElNQXJJMzE1TUxTM2YweG4td2tMYkhwZkVSM3EzWGRZR0NPMDA3ZmsxUE9QRHZEdGJFd1U5dG9xS3psbVpOcF93VG5IOFFjdW5BLWRHSldfak1OVWlncXljZjczY0xnXzFUTWJjUdIBrwFBVV95cUxOaDVSU05ISlBwcWFRRC1XQ09CYy1ESGx1U3VBVzNrNzF6d3ctU0x0MXh6SXRzb1QyNWtTeWlKanhCeXRCU2FLbVZPdDQ3UERsQlFJUVlMei1LSnpDRzlRczFEaHoya0hvd0RYX0l0ejYycGpwQmpuTEFuSFl1V1d0WlpoX1FMWkZkTVZRNGF5V2l3QWNzbzZ0bGF5NG80UENNVDYyTWdVdHlnTlBUR2xr?oc=5
panjang artikel: 0

Fetch isi artikel:  29%|██▉       | 721/2473 [16:22<3:27:44,  7.11s/it]

Fetching link: https://news.google.com/rss/articles/CBMivwFBVV95cUxPcUxTWGY2TDNVM0JDMm41SFc5OEFGTTdXUEItNTQydUZrUXB3VGNRdTkzYjBwT3M1dHBWWUlyYnZIRmRCdklvbHNvQ3BpcE9DS0dSN2NENGI3TU5sUWhBTzhCNWVYSjhmUU9Ec0pqNFNHQjBZTHNvX0tzZjkyYkhma196dVBsNm9wa0FLa2I0QTd2cnpjODRfREJ5OXVnc0s1ZnprblZ1TUVJUmRVcDRicy1XMlZtU0RSa3ZrU0pVSQ?oc=5
panjang artikel: 2574

Fetch isi artikel:  29%|██▉       | 722/2473 [16:26<3:01:07,  6.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMi6wFBVV95cUxPZ2prc1VxSi15TXVsN2VQc2VLTFhZcGhWSl8zZDhhTDUwZGhyMXN3TkE1MU5vcE84ZFBZaXNmN1JFdHJ6TURPN3NWR2wyNTFJdEMtM2Y2VUs5UlJOV3J4Y3MzXzJKY0hXbF92dFdFNl8xVUF2c2RpNW95VHlFSHNKMnZveDd2OHNPb1pIclI1UG92VDVWX3pZOVZhUFhiYUw3eF9YNkNjUGtIbVJqdlY5RGYwMnZiUDQyMXczdUFDcnJ3WW5pWUNZdlpNdFFER1BGV05SckloZXF3cVlubXlkWHVTSVc1SWEtQlJj0gHwAUFVX3lxTE9MbEhoYU0zd1hwdUphRDA2VXN5OTF4c3Z5QTJkVEhUQ21lRnZiVWh2ajBpT2lIM1lMOXEyXzc0REI1YlZyQnA2WkFndmdtYlUydk1FcWxjQVdEVjZuUDhpakUyZUpFd21CcHlvSGJjamJTcUI3dzVadHBhX2lkbkg5eTJpOTIyVlpKZUNxekJMVFFtcDhWQ0RWSUtUeTdTaFZJVXJhQXR4Wjl0cHMyUUh2Vl9QbVh3dzhRVVZrMjJGSDU2YTB1UmNLSnlLREExWkR6OUdESFFZeWRYa1ctZHNrTmxlenA5ZWZHNHJVUHF0cg?oc=5
panjang artikel: 1807

Fetch isi artikel:  29%|██▉       | 723/2473 [16:31<2:56:30,  6.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMiiwFBVV95cUxOMDVvNFFnUW13MjFjbVlGVzJ3X1dwUEFwS3hWc05ReHE4bzVvTXlwa1pFWFR5c1h2bFhQc3h3X1NRZTVxQU1YZU0ybnIwdjBiQlBIdWJrbENKVnBhU0UxX21yVnhvT3FfSGtoa2VGQnJSaGtnc1gzNDdqSVM4bjZLV1RQQlZJcTMxQlB3?oc=5
panjang artikel: 3438

Fetch isi artikel:  29%|██▉       | 724/2473 [16:36<2:45:15,  5.67s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0AFBVV95cUxPVWhJX0V1Z25mYjdZczd3Tk5PbWRwRUNxbUpQc0lqemQzLUJqYXM5eHhvQmpLMWFXQUdCMURBVlZiMkdQemxFWmJ1bTJFRV91NFlzVy11RFQ3OWdObGtDMzJNMTdGaEtYekNVZEMtYVJQU2V5anE3TWhTZkVJc0JEMEc4T0xLMGF6NFNDdkJmbmNqWExlVVdkVlJfcGVqUGZXOTZCSm9KNVg1VWVRaDVVM25ocUVKb01zcTF1Z00zbzM1VTljX1RvbUxQSXVMM0VE0gHWAUFVX3lxTE14bHZyRU5OaGJuQ0hWQ3Y3RGNaSzIwUmhTRkFpSThuRTFIaTh4TmhOdXBSZFFnU210Tkt5LUZ1R25oMXhKbmc3eVFMTWI0WG9pczMxWjB2Mk56TkxaNGNuWFdKZWxfTU5sODlOc3VmZElyV1BJRUpMU2YwZFpTNkNFZkRQeHJZQTN2NzRJeHp2SndGZTFFbGxtSVgzaEdyMEg1ZWx2R044Yzg1LVAyMmFXOVNYMVkzczJOc0FxdmtHV3psSkMwa0hKcnNMc0hUSEp1a1RMY2c?oc=5
panjang artikel: 2276

Fetch isi artikel:  29%|██▉       | 725/2473 [16:40<2:26:05,  5.01s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxQbWc4U1drS0xFNTc0dkhScFpxUElRSUpZdWd4UXJKNXQ3am1iYVBBNzlTb05uVW85WDR5eC1pb3MxNGxwdEREd3l0RGhaSDRXVVVMTHZOd1MzZjl6SkFmOFZodkx1Rzh6ZTFYdUcwRUJVaGFEcF8zdW5DeVU1SktGZ29wbjhmOHVNT3g3cEJSNmliZXZmb0U3NnVZZHRfRXJzNEdvbkdtcFlSeUx1emfSAbMBQVVfeXFMUDR6bG4zYk1rclYyMDRhZkJ5a3NSdktOVGZUMGR4ZUxUVHVLeGd6b3FfR3BndjZZZjRLZ0tqY1dTMzg0eVpqcEt2M2cxNE1vNnVfN2xaOHI5dm15NlBkcjNZS3NvQkhMdXBrNk5pdmNqSHZHUk9NUm4tanB5b2xNcUpDYTJoMDNqSXZaRHc2ZGxNcEl0b1A1SlpBT3Y2T2Ita1hkQk9Eakx1S05pVF9OZHpWdGc?oc=5
panjang artikel: 3576

Fetch isi artikel:  29%|██▉       | 726/2473 [16:44<2:23:32,  4.93s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxNY0FJMnF6OEtEZGtKZER3WW4zRU5TVktURmVxNVQyU0NJb1oyRHlpOG9PVktLTUh2Z1FjUDZPdmFTYjNWUFh5WXM1TUVOa3lDMFE5ckEtNkFvbnA3akpWU1MzU3VOTXpQMDVoMmxsWTlNMDFTVVQzbEQ2bmpCdkc3VjZvOS1NdmNVWGtKaTVFeHJ1MDNobVZzZ2p2bE9VVFhMRGZkVkU4aHNOOGRGLWJLdmRyQ2h1TlnSAbwBQVVfeXFMTy00RWJ3a3l4eGtIaWh4YnA1N0Z3TE9rRW1WcGxueHBYd1R4dWFlWEViTXNMWkc2NDJmSUwyZ0YxczJPcy1WY1pfdnpqNlVTX0N1Tk9yR0xYQzJ6Y3BIWERTcVFVTkw2ckM2MEpqVFNfV1N6cFVWV0o2SXRIc0hBOGlVbWV3TGFDTlZycnhRYS1mTUE2US1mSUtIenFJeDQ4UEFkSHFmU1lHVWxVUDZSbkh2akttUDdZbGt5RkE?oc=5
panjang artikel: 1359

Fetch isi artikel:  29%|██▉       | 727/2473 [16:49<2:18:02,  4.74s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxNUlk4YkhkZTJjMlZzd1ZLU3VOalQ1aG5OUVFhZnZIcXpTZHlQMkRaZU1xWE9vd1BNd3p4RVc0Y0FxeTRZRlhuaXg4SmVMOTREbjNESDgwdnZXRGJNZVc5MjV0SlJDdVptcktDcFBfZTR0a2xEUVQ3T3ZGeTNBWFlNdWcyZC16Q1VkLS1kc1JwdGV2X2szN2R4U1hrZ0hDakJyRDY1aWJjaXM5dw?oc=5
panjang artikel: 3151

Fetch isi artikel:  29%|██▉       | 728/2473 [16:58<2:58:19,  6.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMimgFBVV95cUxQRkVfakdwUjlkdzBjOUpXdXBNV2tZQTdub0ZGWnRpbXBqLXdzaG1CNF9ObXpZOGRWXzZSSUd6YUI5SVhiMEJLUHlSbnFJV2g5V3Vwck0wN2E0ZmlyXzRNZDA1b3hzTmVlU0RJTElLa1doc2tQejFVNFZoOXR6MzRCamd2YTZIRGJMSVZzWTFUYW1LV1RCUjRSQUtR?oc=5
panjang artikel: 5230

Fetch isi artikel:  29%|██▉       | 729/2473 [17:02<2:36:32,  5.39s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxQc1NTTlhZU05WVndLZTdFQTRKVFJZRjJDdWdZVnpwNGVWa2RFSEZtWlVOSFQwMlB4clJaT093VWp5UWd1Q1E5NEw1VEVDa2l3UzJoZlhDZUpFMDM5OWN0aWhFbmc1TWhEbFVPZlY2Tk85bjV2LTBQQW5CTlg2dXJCVVZsdTlVUTlhdEFqOEp3RGFRRXFlM1lEQXpwbVBxV0EzYVNfUzBxcnk5TktjNWJnMWpR0gG3AUFVX3lxTE96ajM1akd2TzBzWDZ0SURMaGFDRjBpMUlkLU9NdTAtRmppdEMwYzA3RERzM1dMNEhCN3ZyR0VYZ3N5SzFidHQ2aTRmQlZlSTZpQkZJWEZWX2dJUDRoYXJKZVVvS19OenN0dXFjV3BZNFNaUmcwckIxYkcyVldfdWZEa1VsQ1V6RTZNVXdvdXFYbXhlanc1TFJUM3hOY2FVTk9XcURfYXM1aTJhN0tuaHpFTkUyY1FvVQ?oc=5
panjang artikel: 1977

Fetch isi artikel:  30%|██▉       | 730/2473 [17:06<2:27:05,  5.06s/it]

Fetching link: https://news.google.com/rss/articles/CBMipgFBVV95cUxPZWMtT0pzQnlzNEdKVFRIbF9uN3Q1YnJZTGg4Mnh1bVdubXBGZDJBSUZ4YTZuc2RXejhheEVrNzJxM1RrcVBtQWYzdnFGNTRFaElmak1Bc3BPVkZCeUpNbHAtdGlDa3BOY3NqU1JmWEZYYmg1a3ZTVXBlbnFQU21fYnRlNVJvaC1wemZsNUg4STU0dEdGNUY3aUx0S05wWVMxdzk5Wldn0gGrAUFVX3lxTE42ZFJfMEFmbm9td1dGU01TVkpmQjdFc0p3TEI2QjVTUzltNHI0OHIxcThkNWt1MkN6ZEJBWjl2WU9US3E1eVJ2eGwtY3FMdEpmREx2ejdJYWg2MUhBSXhOSEhRaF9Rcm1hcHFfZ21wZEpnQS1YUUs2SDBXQXhfWkxnS2FHaHRiZkQ0SG5wb2x6RGdJbG1SdG1FVWZ5bkNyS3ZEY183YnVVZGFpcw?oc=5
panjang artikel: 0

Fetch isi artikel:  30%|██▉       | 731/2473 [17:14<2:53:22,  5.97s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxOMl9ZUkx5RTZ4M3p2eGwyUzVlVEg0MVduLV96cnpyOGZralJVNkd6c29UazlQU3Q4bXpNUXg0NEo1OFdXcS1QdGJWY19jdENhbEdxQmNhSGk3NnFzME82bHc0LTlFNllvWEVaRm90Vm1VdjN6YTY0ZnRZZndnbmljWUVvSWxPSHZFUXVCR1NXZ2FRd2NCQWhhWDVFcDdpUmttbV9MM1h2dHM4MUJKTm9kTmNvSVlJZG9UNkZKTdIBwgFBVV95cUxPWU4xb09fTEd0UWdnd1hxTzBsZ1h2ckswby1wTFVOdHphbFJ2aExnNjZBRXRGYUx5MUtCS2h2cUUyYmRCOExoNTFkUWZ0Rlc0UVQtSzdUYTJybFVfSEt6S0xxNWVvcG9hQm5yOHpudlNaeVp6Qjg4TzhlREswaVdTUEtKdDFHWTdYLWg5RkxpbU0tc2ZaYV9HQ3cyMmtFTjk0Vkl1UWktbW1TdzVGeHhZZ1lqemNIZXJzV0hqVHR3N3gzdw?oc=5
panjang artikel: 1884

Fetch isi artikel:  30%|██▉       | 732/2473 [17:20<2:47:59,  5.79s/it]

Fetching link: https://news.google.com/rss/articles/CBMiyAFBVV95cUxQN1ExN1ZYNVRCTnFqRFpsUm42Y3FKdFRRSnFJSFR1NHFZZ1RyV25mdlo1dFRNZHZBME4wdFJYUHZrRGM0Zlo4Y1dycmY1ZE9ETlgtbl9lWVZJUXFmS3ZpZG1fVkRUZzdMNzFqZklnY2FITjE4U2tBVzhWSjZpcXliQWNfbjhUUmZuQWxWMk1ORVdIVldUY1I1NFlENVFiZUU2VmNjTGlPZ0pFQVNsd0tBYmhCZmY5SHlGejdOVTc3WGxCNmhLTEdiUw?oc=5
panjang artikel: 2638

Fetch isi artikel:  30%|██▉       | 733/2473 [17:27<3:04:58,  6.38s/it]

Fetching link: https://news.google.com/rss/articles/CBMilAFBVV95cUxObTNxeHZONXhTR05vak9LSkx5aFRVcnRQMU9nZGVWMXdhZ1FDQ0luUmNSVURYMGlpZHhJc1B1Q19iSmxoR1FTVTJNVnB5MGttenVzRUhHcWh3ZGlYcG44dTVORkRwVDBBUWNaaXJJeG85UjYycDNXUzRPTjVyWHZxcUhkUDBPOFJqQVVIY3diUTN3ZHU20gGTAUFVX3lxTFBqNEdDOTMzdjdncHUzT2Q5Q19WSng3YTRBdmNlalpseFNLNlVhNHRUV1VhOUg4YURBNlNuT25XRHRtZnRscWdEcE50NXpMejVtb2VGSE1jbE8zTmpBQ0NLYXFaNG13V0ZxVXdMTHY1emVMeVVYemk3Y1hYSFpLWDd3WWF0RXJRMnFrZ0NXbG9GUmRBVQ?oc=5
panjang artikel: 955

Fetch isi artikel:  30%|██▉       | 734/2473 [17:31<2:45:00,  5.69s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxNU3pKRGJIQUt0MTl1bUZjcnJIM0djUXJFcFc2YXplelVWRWEyMWlYNHpHWkpRQ3NsSUdkdTBTM21ZaUpzYUZYZ1ZyTkJnc0h4dk5FYlBmOF80NEdCZGxNQzN2UmRwRnhCQzQ5dFI5VERjSEpfcWRySWl2WVQwMFVRaU9lYTh4clNOZXJDYk1SdnpyQm5TZUtWenRCVVRnblBrbjE4SExSUk1IOXp6M1NqNnFB?oc=5
panjang artikel: 0

Fetch isi artikel:  30%|██▉       | 735/2473 [17:50<4:40:35,  9.69s/it]

Fetching link: https://news.google.com/rss/articles/CBMiZEFVX3lxTE1IVzhwRTVVUlNtWnFjY1FRbFU3OUEzOThCOU8tZGtlZ01VVG5nNUR0aVNyUlIwMVlQaENBMlZrdTFRMTJiR0hnS0xVX3N3aG1NOFEyNDRKQWdCdXFpeWJCUExibzc?oc=5
panjang artikel: 1435

Fetch isi artikel:  30%|██▉       | 736/2473 [17:55<3:52:34,  8.03s/it]

Fetching link: https://news.google.com/rss/articles/CBMi9AFBVV95cUxPbEVQXzhLTzg5azBrYV92bURSeG55M19HeDdhTTU0RHl4REpDTFkzWnFtWFhSWHpzUHpXUDI0T3RGV3g1enl0WFh1REdoNVBFT1g3Z2dSVGc1YmFnNzlESEEyNW1DTDBpdkhSN3JrYzF2TFNxMzlIdmtCcktqUG5nTnA4QWRvNGY4Z3UxN2tYQ3AyLVQzUGpvUTdBS01KUUFoSmtsRzBRTDNDU2lLUlhEVXBydHNhRHFoZ2ZNZ09SU3YwMnFyMmxhWjl1U2JNYUhoMmVDWGRSOUlTVHR0YjdaLTJhT1lpNG52LW1OQXJ2aUQ1cXJE0gHgAUFVX3lxTE1LY3QzaXlDUTdxZFZZLXNRM2NWdEduWk91Y2VBWlRIdjlGclJEZzNpUW5wV3BPVUg1VzhfeVI3Tk5qb1JXWjNtcnlTTC1QZWYwNTVDMEpFVGlFcWhNWTlhbkY5S2VtTXZMYWQxNzlhc2JjMjFkc29WT19rRGhzN2F0SzJ1Z1BPVXcxVk1XZjFVQTBSSkRTcDFiNjZIUUdUZ1p4ZDUtTjQ5Tmh1SE1TUXJrVi1wTXJvOFBBQy1ESTJ0S29Cdm05Y0t5cFdZQVI2WlNZdjFHWWotRTJtbmJ2QjdV?oc=5
panjang artikel: 3838

Fetch isi artikel:  30%|██▉       | 737/2473 [17:58<3:15:40,  6.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMiyAFBVV95cUxOWDNrNXFmSWVWaGg4N1NVdVBULXk2UWNsOG1KeVBRalFub1VBbnV2UEJ2MHlwbEx5T0t6czF4cTJTV0pYRjZwNnFINE9fSVh5YlIzb0xpTlJoTnEzY0tSeWJydkxFd0VFOVJta2NYMGt3MUR0ZHl5QXAyTTR3WjVaMThscHhwUFNBUXhTdHNoYUNlN1VTQ2xfa2dUSmFqM2J6YWtEbEVxUWxjSWo0ZjdzYjhIcWdNbmNpRnBYTEJwNDFkcE5MTVl3TdIByAFBVV95cUxPTXROM1BfZ1BpRlhBME5CQTZuNFd1RWZ3Y29Ib0dmdXF4Vi1mZnMyc1o2R0tBdnI0OUR4bEo3TzJ4cEluN1RMVTFHRi1JN3lYeXloUGlLYklUTjl4VHBLYjg4bU9VemZKQVZGZ3l5UW1HX3pEVFUwOUNjOTJGWFFQTy1UMzJxem1GMUU2ZHN2S1RFTjFlRmdTQnpwVHZFZURZd1hOY1VHYUdncGVpY3pmWnRXNUJTQTJ2X201cjM5bVZhS05DU0xoQg?oc=5
panjang artikel: 107

Fetch isi artikel:  30%|██▉       | 738/2473 [18:02<2:48:50,  5.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMioAFBVV95cUxQeUdwd3U4SGlwQVc4aTNkUkY0dXVpUDN2R1AtZzFYNnpSR0E3N1c3ODVhdWNtMTc3TU5sc1k1NEtjRUg3elBMcU9oM1RiNWtJT3pzR1VEM1lvSFZGT0pST1dnellMb0VKX2NHOGZHZXo2dWhqT1ZmZ21OMTNHRGdkWFBQbzFKb1FpU1ZTRno5ZTA1b2hRZEZpVGVyXzdCb2hE?oc=5
panjang artikel: 1765

Fetch isi artikel:  30%|██▉       | 739/2473 [18:06<2:32:54,  5.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMidEFVX3lxTFBKR0NkQkhlUDNwajVjUDNDb3NaX0pySTlNSTh5NFpiUzRVYnJxTU0zamlZMDlMTFdMbV9iTGthMWJkYzE3OVdTUFVVOEJfRlBkQnB3SThrVkdkS3A1eVl2aE9NLVBnS1NHN3dITzFmdXgyNkVI?oc=5
panjang artikel: 4113

Fetch isi artikel:  30%|██▉       | 740/2473 [18:10<2:19:44,  4.84s/it]

Fetching link: https://news.google.com/rss/articles/CBMiowFBVV95cUxNa2dKenA5ajJiME5VUkxCbm1GbXBxM1hwRGdnbkpYTlR4X09UUzhrTFY1ZHlNelJqcUxCOWxrbjJQUWpWSVN6czVtSG5sNjVZSUlGcnhBdVI1NGlseDBVeWFPcVN2eWhRSHhPYVc2M0tFRTU2SFlUdDE1OFBoU2U1TnBDV2xFZGNlUmRVaFVWbGxpdHkwekE3elU3cHBabDNSQTlB?oc=5
panjang artikel: 4417

Fetch isi artikel:  30%|██▉       | 741/2473 [18:18<2:46:20,  5.76s/it]

Fetching link: https://news.google.com/rss/articles/CBMiogFBVV95cUxOdVJRRE9tQkJJdFZhS3BIWXJ5akZPVjhoV2RydXhhcFRfTGlBVS1WOTlab2o3REZZMnVGN1JKbVVSUlJrdnRZVzB5QjBwTDZnSDU1NWRRM1dwWnRmUjNMMHNwY1lBaTNIeWtYTW1ZV1p0UURVSDhmSVBlSTZLN3FDY0ZUYkhjdG83SzkyeXBSZFB4UkQ4NzQ4M2hDdHpzclRIclE?oc=5
panjang artikel: 2626

Fetch isi artikel:  30%|███       | 742/2473 [18:22<2:33:04,  5.31s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxPTXZlbXcwUlJDeE9za0YtaXA1ZmVVRURwMzZ1SzhRMWRhR2tvR3VIaHUxV0EzZktvQVZwVXdyZnRqYlRoS3lHQUNkNC14cHp4Z01vTGRmdXVJejhBV203R0szMGszWXZLRzBsdHRsMWtKamd1c3I0a3V2NEtiSmFaa3RfRi16ZzJiOVB3Y1lLYUJwT2NUN0lFN21aM3dxNFZTYXBjZlpxTTlQZw?oc=5
panjang artikel: 3039

Fetch isi artikel:  30%|███       | 743/2473 [18:27<2:27:59,  5.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMiY0FVX3lxTE9fcno1d2VzM0xCd2NwcWZ0ZHE4ZS1nU0tUSUswV1Z3WkRHaldLVGZIcjV2VFFuZ0tycm85dU44TS00QkJmQnYtYlNrMG41bU1HdDU2YlBjbnA4VlluZlF3MFVNVQ?oc=5
panjang artikel: 7662

Fetch isi artikel:  30%|███       | 744/2473 [18:31<2:22:01,  4.93s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxQbmtXQXVZTFNJUDFJQTYwTkhsYncxbVJXRjJUd2dZbF9uRGo3ZjgzNkw2SVE1a1JLenFpN3BLd09JX1lrSGxTM3dYNzJDSUF5ZUFTUGx4RmNJOWZQaGtPUEFtSDNUa3h5RlhCb2g1MUt3MW5MaXB6X1Q5MGVYd3g3dHNJSURvMmlYTTZvNHhQcE44RjRYcEgzVXhmRFdYQWIwTFdYVTJ1VnNHTXBaSVdSQlRLb9IBuAFBVV95cUxQc3JuNlBsMDVldWl1aVMtY2x6eTk3cUxCZm41MXhvRlY1ai1CZWJiS3A0NFlPeGgzbzFoMVIxMXFieEtuWEU4aE9DdGtRTFU1WEFXZTgwLWxNdXdpSlVSNi1LNDZMQWNzZ3FuYXNwTWNXbk9zbXplckdTUDZfeFNmaml1Q3hJbUlBRU54d2NsdGRPNzBYblJ6d3FpMjFqdHF6UzV6Q3NyeEhQT0NsX19XeUROU1pFQzJm?oc=5
panjang artikel: 5228

Fetch isi artikel:  30%|███       | 745/2473 [18:35<2:16:05,  4.73s/it]

Fetching link: https://news.google.com/rss/articles/CBMia0FVX3lxTFBFRlpEY0FyMmhUV3dNNzZhT3NkZThrblVVWjgtdmZjbXBoSllxN1FLakhrMWZab1k1ZEdub1FUc3BkaFRLR2JSWnJ0YmVfWmdxMVBwand1OTNNSHdLYV95UjBxcG5MeW5sU3dJ?oc=5
panjang artikel: 8794

Fetch isi artikel:  30%|███       | 746/2473 [18:41<2:22:42,  4.96s/it]

Fetching link: https://news.google.com/rss/articles/CBMia0FVX3lxTFBrc2d2RDRKdm5HN2Z2S1MyNVR4QjZpa0FWSlJxVUdDdG9QTXJESUh5bk5VRnN4cGhTTzc2TFpBVG1fR2U4QmZ0TWszb1RsLUlfMFllTWhBUDc3eUxRNkNNbzdkdjZUZDJaNC1j?oc=5
panjang artikel: 7996

Fetch isi artikel:  30%|███       | 747/2473 [18:45<2:16:22,  4.74s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxQc0JFUWw5Q2dsNXFoXy1XRW9XaWVUUzVsaHFheVJDRk4tVVJRcHRNTlJoN0ZTZmlQNXQ2dFJxRUljWHJMUEd0dTNram45aUh2SGkyVGtJd1pIdDZuLWhsdWdpTkZJS1kyNGFVbXJVaXY5c1I0eTVrNFdwbXdMTGFBekt2TXRGWVdJV25OLXFTZUhjWGNGVEhkTHBCYXBVVW9DVnlaLWhXdGtlOXZsNTFwUG5jaWRTRnJFbHgzVEJtb0FPeXRCS0JKOUhWNGpoMVVzT2ZoTWdUNlpZNXPSAcsBQVVfeXFMT2NRWHhMcm1lSGg0N25naldmX2owcEVvTmtDMjVuTkd5QWV6a0RlTmZsRTF1cnJUR1hyZTBNNkZiX1lmdzgwSDFLUXhxMk9IZEFhT0hYUlpEZTdheXdWdXQzaGxiV2tsRTc4T21nV1huUUw1azNHZDkxdS04UE13MzhMLWdFanBINDh6MGppUVBaQjBDZXFkVXk1RC1ybllleDZRMm5YV0dBV3c1elppcXdOaExWUElxSGV0ZlpuSk92d3B3c3FyZVlSRzA?oc=5
panjang artikel: 4059

Fetch isi artikel:  30%|███       | 748/2473 [18:49<2:08:34,  4.47s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxPY05rTXV2UkpIa1hnYllndHVOYmdEM1kxVEd2Z0R0b3NUbjJZN3ItMzdjX0tiQjlISFRDUGdCMHl5eDdRSlFQUFR4cHlmQVBiX1lMNFlRanJfY2FjM2EyV0E4S3RLNDRuZ25uclFjUFZJOUVGSV9HTmp0UWZrejZUSFBzLUdmSWpuSFFVcThIOWFEQWhmc3RvWExZNGUwQ3FLQkZQbDVmTlN4Zw?oc=5
panjang artikel: 4393

Fetch isi artikel:  30%|███       | 749/2473 [18:53<2:03:05,  4.28s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqgFBVV95cUxPck56YmlkaTdzLXZqTHJUdHNfcU1NUFhmMmtFbGhFWlU0Y0pnNHhmRjhDTGNRa2VsLUhHSFpoSEcwM21iYnpSdnhoZVQ4dG1YNGU0TmtQS0N5WDlRR0dLSkRhS0tZaHhIWWw5VkdYWnFoM0JsRm9wTVFRLUtFQ1ZVNVF0ZW8zUkp0dnhoaEpka3lCQks3WEE4ekh2VGZ4Z01NZkVadnBEaVlFQdIBrwFBVV95cUxOTEw0Z3RnQ3NUUlpvc1RIT3l4RmhXa2Y2bDBnMHIyQTY5R2ZySDd1eDBsQUJrcVNIR1Q1Mzc1LXZFZ2E0TERJaEFZV0dJT2xMZzNFRDJLU3hpTUFneFJwZzZHQlQ1THViakhaWDlYMy0tVEJERGtpTnhVbi1lb19iRXRTblZESHpHZnc2MmEzRHgxWW5hT01WZ2lHdHNnM19NLUdlM0ZIN245NWR1dkpJ?oc=5
panjang artikel: 5761

Fetch isi artikel:  30%|███       | 750/2473 [18:57<2:03:21,  4.30s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxQS05pcW1CSVg4ZkpIUVY4cXo3T0NTYXJFNzFiVkVGak1ORjJWdGEyVjE5VWdWZjRPN2ptMDZDNnF6QVZTMUJaOW9jM1cwM2E3ZExPeTI4aEl5Q2o3MjR1SWhISFR4dXo3RF9TV3laUnpBVk81ZjVlYjRROVE3RzZETEZ5X2R6MEEyUkZKU1E2WFhVVzlVNzR5a3Zkc3M5UEkxeENwLXpsWXJIbFVRNzY2eXdOZw?oc=5
panjang artikel: 3976

Fetch isi artikel:  30%|███       | 751/2473 [19:01<1:58:43,  4.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMiYEFVX3lxTFBweFFxLUZrZHRKUkZ4OWtWSEhtbkRLZmRBVzN0Uy1ITzduenNPZE1PdjI0ZEJ2b2lHR3hWalg2QzNTX1JuYjZ1MU96SHVteEJtQ3B3dzZqMUI1V2hfY1dDSA?oc=5
panjang artikel: 9686

Fetch isi artikel:  30%|███       | 752/2473 [19:05<2:01:16,  4.23s/it]

Fetching link: https://news.google.com/rss/articles/CBMiwAFBVV95cUxNVmJhZ3Q2MWR2V0IxT2d4MVBMa3Y0MnU3UzlzMm9aaFJYNVBoR2l2Z3hFRUlQYmo2NzYyYVRVb0NaNWxBM1Q3OEs5dVZzNlZEX3FkMGotSnpRcFExcW9GTnAtekVPREhBMUxZZHNmVjJiTzZ6MjdCdl9RbDlpWjRLcXUtaUw4bEVTaUlnaTNyQ20zZHdFQ3hwMlMteFNyUm10OEVMMkFMQVpCcmxKMmZGRzRuTVZsQkEzVVhjaFRxWjbSAcYBQVVfeXFMTzJERFJNT0hLZVBkT1lxeGpZUFhFdVpqMmJIUzlhR3kxN3c1TVFmT3ozU1VIZC1BU1VLaTBLcDJ2VlhUR3dhMGZLM29BcG1FdDNuUjBmWTFSbWo5ZEplSHU3eFhvcHZZTk1wWnQzMEgyY3RKclFBdnltUTdUdlRZMkxzNXVTU0NuUEtwN2pDaGM0Q1NpNGVNRzNsWlNHVHVOVFVQdnhMUnBFYzY1UXJwZjl3QUE3Y01BV2hsVTNxT1o4MG5VaTln?oc=5
panjang artikel: 10042

Fetch isi artikel:  30%|███       | 753/2473 [19:09<1:59:32,  4.17s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxPY0tEdUJoeDZ4SF9rX3AtVlA1R2FkSWg0T3U1TVYteURJNzcteXpISkpvb2tDeUR5MGE1eTN1OGpyemo1RF9IM0s4cS0zUU1RbzV4dkMyT1gzLV9uNkxPM3VybDR4YjF0ckMzTnZUc0ctM0k4OS1aU1FObEszUklHM1J3dW1WWTY4NXRvZm5Jb29mTkFOa3BTX1UwLWUtdWJyaDNyaFNpV05saDN2UXlEY1BrcHNZYng0NVU1MtIBwgFBVV95cUxPWjVmeHpTXzZJaUtVbk1FaE5sMF9LQVFLZnBqS1RoZHFxSks2Y1MyRG1KOV8tX1ZYWWdKWDIxR3B6djZjcWpERVlCczdfV0xQc3ZzSlZxVE5lR0NqalhsdUh0RHg3TjlvUzZnYmE2N1A2VHYzMFZHeGJvaGNjNnVodk5Mb0pBQjRvMy1rVzRkbkMyNkNiY1FEZm9yb1BvZzBZSjBJcXNSLWE5c0ZITGczNmNTMzZoXzZjck1JY0xndFNIdw?oc=5
panjang artikel: 4128

Fetch isi artikel:  30%|███       | 754/2473 [19:13<1:56:36,  4.07s/it]

Fetching link: https://news.google.com/rss/articles/CBMia0FVX3lxTE5iemxFOGZweDJIX2pmaWwwazE1eTE0dGkwakZZS0N3amx6ZGtzcko2NjZJaTVleVhBOGhxaS1CVXlrNzc3V0FOczBpckYyMnc0QmRROGw4TzFDb1RLV0x2UkN4RTFJLS1IZldF?oc=5
panjang artikel: 6340

Fetch isi artikel:  31%|███       | 755/2473 [19:18<1:58:47,  4.15s/it]

Fetching link: https://news.google.com/rss/articles/CBMiswFBVV95cUxOYkJQMW8xMnY1dW1ETE1Nc1NGTDVROGQzVzI0Q2x3R0dUWkFJblgtQWJnTjI3cVRfVllYang0dk9QV3VjTnJWWmpyNHJiVURzRDRTYTRhWFg4d0pCR1kyQ0FacVF2UXdReHpGdkxPRV9USERQNnZLYUh0MDFMQkN4ODFaeG4zT1ZhdDBZXzhVVEJSOFRnVzdGS1NXbUo0THo0YVk5QnY5c255a0VYV1VvazVRb9IBuAFBVV95cUxORGxzTVZMeEpqM1FvS2IxYkZNUHF2MG1EdUNBSXp6NTE5c2ZYX25FQ19lbnlzVkdpbFM1NVBRUldFX2Z1THFGak9CSkJYdUtYQ283Q0d1aUR4ZXNFZTd2Z0ZyR3dScnBMSnhGR2NSMFp4QzVkdE1JM21RekxLYWdoN3U0Q0QtNW96QUtadjNJdklEdV8yT2FVcjFSQlhIVnFaZDZCb25XeXpOaDlVMnJ1UUI2S2plcnhW?oc=5
panjang artikel: 4982

Fetch isi artikel:  31%|███       | 756/2473 [19:21<1:56:40,  4.08s/it]

Fetching link: https://news.google.com/rss/articles/CBMiW0FVX3lxTFBiczBXTm5NeUt6SF9FTWNndjdYdzFnMDF5S0UxR0hFTmpKNUFtS3I0dUtLbjY4VktIQnlNZmliZjJfVmoyVFRUcDlNRlZHTjVaVENVQ3c5cmVULU0?oc=5
panjang artikel: 7654

Fetch isi artikel:  31%|███       | 757/2473 [19:26<1:58:15,  4.13s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxNTnh4Y2ZLR0VvRHY3S19meW5VWkRsVE1nc2JsUjhZYjdRTG1JNWkyX2pqT2hPRUlmSkFDWmZ6WmFIQ250MlFkTjBURWpjeERiMVM2V1JVM1FCYU5BQVlUcXdFNml2THZGYlU3aHBMS1IzcHkxVzJkWGwzRGRRdW5uSnBUSWRwM0V5NjRGZHpCVTQ3Y1BRRUNVWHZ1aWNDWndUbWczUVkzU1l2clVpYXl2c01IZ2F0VW83OGtmWdIBwgFBVV95cUxNdEdyREltbHRiN3hYUm0wQ0NONHZXUEd5RVFNa19EU2ktdE9KOVNsVWFWSmZxM2dBRENRUGR0dmRUTnh2enlfSHVpcU1TOTJSUnlkb2lzbGZkcWRtU1FhcHcwdnk3cU9kV25LTkhXMlVzM19qV0F3ajYwZnpBTkxFYm1iR3ZNdTg5dUtGSGlBWTBfaGphdlkxbHM4bG9iMDNOeGw1bDRxNEMzQ0QxTXNoM053ZmlQaHpaNWJBRlhqN0ljZw?oc=5
panjang artikel: 9777

Fetch isi artikel:  31%|███       | 758/2473 [19:30<1:56:44,  4.08s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxORlA4SGdQZFFLbWpxOEFmdW4yNzJKV21XQUZVWFR2X2ItWVEwN01SdFRpZHRobWIyN2RTM3RkSkYtTV90Mk10WS1wdkVVOVpHYmstZXpnTm5jem5OZVhrdUZmYWtFZ2ZSMmdBZF8zUUZaR1JpUHB6NkdqT1FVTmhscGVWYUlLM3FWYjEzTDZBdS12eGdYU2t4V0dlaDZXaTBhLS14bHBKcVdPVVBT0gGyAUFVX3lxTE5yTmwyUFlZQlkyYTloX1R3LVUwUUc2VktsbmVINW03U2tDUFZveTM2dERjYk82VkR6bWR5YUdzc01lbFlDbGZ6ek9KUnN1NVppT3pPNW5LSjVEMHhyX3pSTFFSUU1BUDdKdlpmQ0NjQTFUdjN0RTdnQkVDUVpKTEkzZEY1aEZCUTR6WVBCdXMtSnpnTmwzWFB4NnJlTmNxNnFJeUlvZUREV0VBLUFDYlVvSVE?oc=5
panjang artikel: 5520

Fetch isi artikel:  31%|███       | 759/2473 [19:34<1:57:27,  4.11s/it]

Fetching link: https://news.google.com/rss/articles/CBMitwFBVV95cUxQcHZuLTFGc1dYa0d2NjZkZ283UTV2UFh6M05wXzVuRG5FTTl6dG1fbHBJYVVOUXh3VmxqUUpRT2JvWVF5cEJNR3M2MERtcThONlBTd01vS1l6dEhuU3BPVEhoSmRDT2Q4YWEwcmNHR2dtcjBjUEF6Q0w0THRLUU9zaW5pdkxPUWdKZWFlSC05UVI5UFZvd0NyOVhlZDc1cjZQbTBudm1yeHpYZG15eThCaGhpalg3M1HSAbwBQVVfeXFMTnJzYlQyMlR2QVlfbkllcklVVjBDX0FrSklxa1RrN2NVTllYV3UtQ19NZ3ZWZ2s3bmd4TkdqNE5hTW9FV2VBejR2NU0zNzd5MXR6RkdHRk5hMWRTdzBYcFp2RGprUTQwYlEwRXc0d012YkNrclpVc3B5M1htUVBtaWhMTXJCaTA4VjBMdHZkcVAxcWQ1SmlBOC1TUjVKaTlmeFdFYy14ckItRVBlOHhWNVVKWHE4OUxvMWNJeGk?oc=5
panjang artikel: 6862

Fetch isi artikel:  31%|███       | 760/2473 [19:39<2:04:50,  4.37s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxPcENsZjR5UGZLcmx1ajd1S1lqdXp0Z0liS2h1bm1DS2pUWUFwd1RfMWdvdkIwNk8wbW12QlpUXzlEdHBNbUpSbTBWVExQcWxzQi1nR2gxSmdnaGZRM09UYXFrMFNPOEtUV1JBUVhLTGRkeURfS1lpeUtDZUNEWDdObjlobzNpZ1l6OXo3UkdnaTJDNnktbDVmNEkxOEd0c1lPX1YxUi10UVJBMFZJYVRIejJ6dndqMnh4RWNz?oc=5
panjang artikel: 0

Fetch isi artikel:  31%|███       | 761/2473 [19:43<2:02:36,  4.30s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxNTERoMVNpRnpSVWVKUWxQUGhaOWx5Z0hPUWZ3ZnVyMG9OOVBQVnppdTJzQXA0ajlsUjVqem5HZmVNb0JSTEk3RTZmUFV3aERjTVBwWmlVLVR2OUJzTFdXTHdfLU0zSmx3dU5KVlJoYVNBWXl1Zk11dXRaZDdWeUFNbS05RTJ5MDdtX3BCWHpobjU4SVpZMTllRHNsbC1UWFlDMFZYX1lUTlBfYUpjdjJSUTR1dUxJblNjQS03VzFBc0hQaG1D?oc=5
panjang artikel: 2507

Fetch isi artikel:  31%|███       | 762/2473 [19:47<2:00:33,  4.23s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxNSDZfdkVnTTlTSGtJdnFjYUo5UHIzYU9ULXdQYXhEaE01dERhVUtIZ1o0d0xDYmQ0VElJMF9ha1BMZE85Z3ZsRUJmME04aDNWR2VETmhsOGFrRFFqSG1IM2JLY0ZUSDNRY0FGQ2FwbGIyVEFQUGtwY1RNd29xbDl2SklhZVU2a2lhREtqU1BYb3lVRTVHdUlQclBJVkx4UnhNckc4VkUzVjdTS3NhYUZIenR5QlM5aHlwak1CQ0VzZE0tN0NWRnVlTkczSE5Md9IBwwFBVV95cUxOQ1VxWVpZQXh2dFdTX3phNVdmYUY2aXlVSEcyZnhkcTJyNUZOUVBIOUZBWGlpc3B0U0pxa2NEZVY4allZWExqLXo4MElYYV9nQ1lyQmw4VkxRMFlzU0VYM3ZRYVRfSVJFWFU3NW5TSGc5Mlg1OUd4QndUMFE5c3pFNWpzN0pmMmJHcWx3dzlObU8ycHU5Ml9vOWNlb1dIOXZGMTNSZGJ2Qkd1TUFHOVotcWN2TG1pb2RtSXNKRHh2YUVONDA?oc=5
panjang artikel: 4165

Fetch isi artikel:  31%|███       | 763/2473 [19:52<2:06:02,  4.42s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuAFBVV95cUxPelR0c3RPQmktRXN0b04xLWViTmVMaWRWQUZ4c1hvbTVReFZjdVJSUjRBZWEzaHVjS0lsc1lPSDNWYzRJckUxbjVVQ0ZxMENBbTd4SHdoWWJUcHI3b1VNNE12NTNfUk16bXNBS3Jvc2pXWHotcWRiRVZmV25aS0NZdjNoZDAwVGFWVElvcXlWOGRpdmNVUXBwb255cjhWUkNUejMzZTBkVUtNRFJYU2lvMXV2TS1iWTla?oc=5
panjang artikel: 2938

Fetch isi artikel:  31%|███       | 764/2473 [19:56<2:02:07,  4.29s/it]

Fetching link: https://news.google.com/rss/articles/CBMitgFBVV95cUxOWF96R3ZDSVJuTTBHRVNfWmJwZlZTTGpaWGR6X0NRNVlqeHZ2RXpRVmFjMmlaZUlFQnA0R1U3MTJid3dTbWlqTGR4NjZfSTlwbkptUy1vd201SHZ4cXk3TVEtdF9QaXNXY0Z5VnA3d1lRSkVuVWxQRkRvV2hLUHVMellpZXNmc18tNmw3TkRsRHAyblptQXVuNzJ2S2ZxZElVYi01eHVjaHJDaUtwREh4blZyM2lRZw?oc=5
panjang artikel: 18287

Fetch isi artikel:  31%|███       | 765/2473 [20:01<2:06:00,  4.43s/it]

Fetching link: https://news.google.com/rss/articles/CBMikwFBVV95cUxOYjNxZk9BcnlfVzBfM0E4bUFmMGtUY3c5bERKZlNRQVhId0FzS0hYUEJVS2tMSDZWN29ldWZuYXY0MHZNWEh0WUVhNm9oRTJ3VHJxSFAycE5wZTBCZ3FhS1NrNW1aYkE4UmoyT0g4YW5jaGRmQjMxS3o5TlpZQ0tFUzliSDcweXJvRWhTR18wVktpNW8?oc=5
panjang artikel: 2323

Fetch isi artikel:  31%|███       | 766/2473 [20:05<2:07:37,  4.49s/it]

Fetching link: https://news.google.com/rss/articles/CBMizAFBVV95cUxNclJ6Sy1sUF9jZHVXdlhYaE12bDk1OHc1SVd3a01BUVhrZ2Z5dWpNdEFnWThESl9sSF9RS19aQWdQcHhzMnptRlVBelF2a0preG95UVhUV0pkcHc0RHkwTThtZmkzWEZZVmdETjlFa1Zrck54Vkh0aXJuTnk2QXVldVVrcENYWUw0YjRtcTZxM2N2amtyQmk5MHVNLXRHZEhabWZrY1dPbVcwY2d4eUc5RjlTSUdVVE5JRmlpVEtyeHZtSWM0VVZhQkltX1XSAdIBQVVfeXFMUDFqTFlMY0hnRTdSekRnZ2FraVZKbG9XWWtoekJMZFdqT2d1OENYQUtIWUVFTDZfeWFKNlZGYU0xNXBFZFRZYkNtZWswdWRqTV9lUW12WXdfMTJ6R0ZfVnFybjJ0NFdMWTVVYmhDdEhIMDlheU9tekhWYWhrRl90S3hRekp3bWRDbWR0MDFoNGwxTGZzUzBMN29lYmZaRTA1d3c4Q3BrTC1rZHZVdnlqRDRJTTZzVTFCNWNFQ3htUTNqWmR5c0lSdzBEcURXRmFFTHhR?oc=5
panjang artikel: 127

Fetch isi artikel:  31%|███       | 767/2473 [20:09<2:03:32,  4.35s/it]

Fetching link: https://news.google.com/rss/articles/CBMiuwFBVV95cUxNcTJfaGo4bVA2SFVVcmlzZzVFUkh6d0o4M3dzc1FHZTUwZm14Yy1iMlVBSERzcEN1NVRFdG1wNHo1OWozcExBX0oyWFBzWDRKSkVoX0ZaN0NlMU1hWGtabTBOLWFubVRxWTg5aUlUSUFGakJEUUxxZ0htUlJrcjlpS2J4VE41Q1A3VDZuOGRIME5PQm9ld3puMVNDTGtTNVlrUFY5UGV4eUs2eWVlSURMNDNGWlg2TjF1bG53?oc=5
panjang artikel: 3970

Fetch isi artikel:  31%|███       | 768/2473 [20:13<1:56:46,  4.11s/it]

Fetching link: https://news.google.com/rss/articles/CBMiqwFBVV95cUxPS3VBUFRvYllUVHo2bUx6Z2lVNXczNzVTRU9yTWhtTzZMdDRmT1dteTdTZDNUS2FsNlBJWjBTRXEySmtIYS1kWkNPdV9LR0c1V0J6YkprVzZYTFpsS2RqUGQ2OF8yQ01ZQUxhVUNvalNSNzRjdEhtX3lhVDhGWlZManhaODctemRobl9rVlB2VjFHRGM5dUc4X1RxSlFMeS1LSTJJRjhLd1AwcWfSAbABQVVfeXFMTkNfOHFBRVpOT25ya004anVCOGFsNGpxd2RPSHdCT3FVeDNPSm5NYzhUOGpjQjBRa3pNYlU1SG9LdTJoNXdoQmFRZkZlUXN1dExZTUZVYUpZY21mMTZhLW1hbTlKYVFxekd1NHJCcDlOWU1HQ2tjN1JJbkpHNXlGLVpOQkFJZHdyMlRBNFczeGlUb3d6cXRtNWxRcjk5VGU4c2xqdWs3cDlkOXZLaEM4Ykg?oc=5
panjang artikel: 3710

Fetch isi artikel:  31%|███       | 769/2473 [20:17<1:58:29,  4.17s/it]

Fetching link: https://news.google.com/rss/articles/CBMirAFBVV95cUxPZHVWdDRLdUM2RGx1c1NhMThSV3p5bkd2WXI1di1uOUU4MGV6M24tRmdJbS16UEl6OXV0Q202RU9HSzdUN0VYOWJ3NzdmOTBUNFlCV0F4Rm1RUVQ4dm5uWDVRVy1teDFzMG1YREs3X29IbE1fRWZtaEpvN0dMMzBPNTBuZi1BUDRFWTJPQmhLbmRLWGY0em9leTl6d2RiNEhPZGo5UWRDV0E3UHpq0gGyAUFVX3lxTE1XS3Z3UTVqcXZINEt4QS1KTElieHlJdzBmSjVQdW1RV2haREFjRGc3cFY3dXRSNVhmN1VwUmxQRmo2WHdaOUNXb0lwdUJqdlpQMjEydnR6c2pvYm10dkdtemhHOFlnT3N2ME5pei14dG44U3Z3bHZsZzB0RFlLRDNtZERyd0JGWkFMVVotamZTT1h6dlN1bGdhaDM0cHJYNmh1dFI3RXgtZHZDN2hqeDUxUVE?oc=5
panjang artikel: 2375

Fetch isi artikel:  31%|███       | 770/2473 [20:21<1:56:38,  4.11s/it]

Fetching link: https://news.google.com/rss/articles/CBMiZ0FVX3lxTE5YRHpoaFNyWWNtTHo5Vk5nbWNENlVyZDI5Tm5PdzRWQlFNS3oteWlJMHhqdE1uNzRCa00zNjZ2TXZYUXpWZ3RfeFdlOWVUYnJJMDM2WWViNFVzX29vcDV3VVJ6emplbHM?oc=5
panjang artikel: 8802

Fetch isi artikel:  31%|███       | 771/2473 [20:26<2:03:05,  4.34s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxOelAycUE1cnVacUZnRlY1Nm9WcEtzT2dPWVFxajRhczZpSVd1dmJ2b3EwWUl4ZTN4bnpVVzBHdFE3WkpUTkNZSUE2Y3FzZ0g0UnlWVHlPSThXNTlOM25hUlk3MDNUeVZXdkFhYjQ1b0c0cnBzakgwUXl2SFA1cXk0OC1GdkFzWWowSWRHUVpVYi1WOW5TeGZuVlA0bUlxUG9oODVfUGxudE1LTlJHS1E?oc=5
panjang artikel: 3771

Fetch isi artikel:  31%|███       | 772/2473 [20:30<1:59:25,  4.21s/it]

Fetching link: https://news.google.com/rss/articles/CBMirgFBVV95cUxNRGRNNzBuSGFoWmdNcFZhWU5ZVE5JTmNhc3Mzd3lTSFF4eEoxN0ExbGJUNER5OWlOVmx3eUZodENmVFhpM190ZHJ3N2pPY3M4cUxIaTRVUWRsT1J4WWsxTTdpdGk0bUNkbXd0emdpbDdESFFBc0h5TVlqVDA4dm5ueTBZbEUxem5ZSmZkdlBOSDBvSDJYb1RVUWo1YW1sUnJZMFRtSFBWbnZQcHdSMFE?oc=5
panjang artikel: 5044

Fetch isi artikel:  31%|███▏      | 773/2473 [20:34<1:54:33,  4.04s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxPOGcyVlhDYlNwQnNwTkd0ZnlfWmE4U1BKNW9SQzVnOTFZNWxPdS1jLW9Nd2VmaU9XR0NTa1AwTFM1OGtBYzhqUEY5RUlUMFJ5TXk2T0VuZFBwQWFrRUtMeWtUdWItUnA0NHl2aFVwa3N6ZUR2djNwTEhuV2g0WVFmdmtMMGN5NWNEOUswVWVVQkpHcl9MSFVZYkVWa2Z0RXcyQ0Zad1czdE9sX09hQmdwaNIBtgFBVV95cUxPMFhXYmtSOXE5MzhwZHlOYzZaREVJU0FSSWh5S1FIX2tDQUFtQ3BsdW9SYm1SbEhuNnVFQmNYX0Nya3g2UTVsX1J2WGZqMmxCUHQyOGxqekxqSTd5S2JCV09PUk95LVpJTHVBMzFwdm5OVFN1YnhmajNEOXFLdXh3WG5LaFlZb0s2RXNrRG5LUzJaNzdBUUJYQWV4S1A5UWpVejl3NDRMSE9TVVVFUVVJTmo2UnhmZw?oc=5
panjang artikel: 2134

Fetch isi artikel:  31%|███▏      | 774/2473 [20:37<1:52:36,  3.98s/it]

Fetching link: https://news.google.com/rss/articles/CBMirwFBVV95cUxNeGs5blZlMFBVVHVkZjBjTGVGeUFaWUl2eFVBUE1SOU1JQV9qeEdPQVc5SlIxSEFTUUlOVHo3NFp6QkhVZ0R1RTNoMFdmVjd6OEZleEtNMElXenJYZGRKTEhpWkg5bEhhZXNmLURmVDd0RU5iR2JVUU0zNTJ0Y1UtYkxXX0p3alc4WmUwMHlLdDN6QkZUMmkzUHlRLTBmZXJBZ0l3dE9oVkMtUGlIOC0w0gG0AUFVX3lxTE9hU180ZjM1QjJKUENvdUE5RUE0UXdibWZ0LTJCQjFYYUQyUmhCM29HRy1aaEF6QmI0MWdpMm5kanlodm1icWF5aEx4TlJ2UU8xVldwMDFvb0xOakZvSEp4TDhRellNZl81U3NKaWdIaUZrbFg2U3VBMy1SRkVfWVFELTdaY0hzbXJ4Q0NlbTVjV05DRlNfU1VUVjVIZkJ6QzNWZDBmMXhib01MdnFtbWpidDNzMQ?oc=5
panjang artikel: 4951

Fetch isi artikel:  31%|███▏      | 775/2473 [20:42<1:54:39,  4.05s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1AFBVV95cUxQVFpsaWh4MHQ0N0pPWk9xN2xmUU03dzJFaEZIc3F3QVVPQUF4TVZKbUNvLTBib3dVWkJOWDRadVh6bkxzcHpPWkppYVI2VXVHc3hTYjRsLWJmNGJOMTBzbXAwVnRwUWxKclc1Y1htVHhtZWNjWEttSVVveW1uZS14M1RyRHpfS3dLRnRwSnpSSGN3UFdoXzlpb1d4MDhTNk1SbC1BbmJzX2xkekloOEIzbGxxWXNYdGFyV1FPcC1HVElFQkNPanZ3SDJ3OVlpWWRSZ1lpTg?oc=5
panjang artikel: 2121

Fetch isi artikel:  31%|███▏      | 776/2473 [20:45<1:50:12,  3.90s/it]

Fetching link: https://news.google.com/rss/articles/CBMi5gFBVV95cUxPV1hlSGxrcW5GQjB2TWdDdXlZczNzMWlIbkVXNVRaY1J3WlNhS1NXRFJjcXlWSVUwWUVSWndXS0tXYUp3SHpNUk5hU2ZQOGR1czVNZGg5c2xfd1hDTTNWOVlpRXUzeUozTGM4REo5dGk5ZjR2N2Qybll6Um5RZ25rdVR6a1dCYTVLV0RKZEJjUS1YTklDeFoyNGkwcDRfTnM4amJtelVyQWFYYzIyd0dMd19BRHFsVm5PeHhIbURGNE12eDhUYXdiSlRzNzZWcThJb2xQUDdOTk1WNlA4NzZMSXc5Smhxd9IB6wFBVV95cUxQM3JveTdlUVRoUWtpMFFHLVh3VjZpby1xMHVWNFRNUlV2LXpHMmJJOUUwOE9wZ0FTWnZmYVRWZDRVTUlSdkU2NURuNDFNVHAwMXdjWklwMDVneExwaUxsZmtrMlZmaDhuYnpZdHM0WlQ2blBTZ3hrMFBuS3V2enc2NzR4QVVVRS1vT3lINWhfVWlpYjQ5QTdPekNXMHJiVzVHZVU3VWlNQ1llN184YXM3OGZObEZiNG5FWXpPd2dXelNNNmRnWEVfMlJRbDQxTjRQSkF1dUtCLWxWOVVoSWtYVnBIOUhjUlFIX2ZZ?oc=5
panjang artikel: 1892

Fetch isi artikel:  31%|███▏      | 777/2473 [20:49<1:51:54,  3.96s/it]

Fetching link: https://news.google.com/rss/articles/CBMi1wFBVV95cUxPV3lXVjFpRmRLUDZCQV9jblBTbzE0MzZPQjZrNnZJcHJrbVJtU2thU2ZqTjlnS1JhZmtEdDE5ckFNaDBWN3lNQ2N5T0MxaXRCSkNFZHZTeDRFd2FsVy1pbC11eUY1dmd1N0QyeTAzMmR1OUxrNHpkQ2hlRVk1ZjgydnhfWnR3YzNmbzA3bGxDY0FrTUJsUXluSlE0Ym0wVVZoQnpySDVER2llVmk5STdZSDVaLTJOTnhUYWJySXpwdTRNY1JncmZ3SWdzLWVQNmFNMmxQVlpuOA?oc=5
panjang artikel: 1733

Fetch isi artikel:  31%|███▏      | 778/2473 [20:54<1:56:00,  4.11s/it]

Fetching link: https://news.google.com/rss/articles/CBMiygFBVV95cUxOT1lqRFpmd0tTVU8xZ2VGRVZpR1p3OVFhSUpSMDRGeTg5eWNoVGZYdmg2QW1HMVFMTjdKSTdhS2phOEJqZlA2a3ZoNU1PM1Q4X2h4RUtRdWhmdE9fUUVDcTdVZjhrOVNFRVYtamZPcnVRbGw1TVlYTnVzbXRkeV9RQW93dVhvekNVRFVYUnZLRVhWSTQxNk45U1pSZEo0WmZQeE9VWHU1QWxxSkltdW5FSzk0VlZRdG41VnQxaDJUWHBKeUJvQ1FsbXNR0gG6AUFVX3lxTFBQN1Z6V3dMNHpfRVNhUlE1UGhHbG1LQmJ0Y2xyU010N3RYVmhOQXZGNy1BdmNiTXAwTUd3aFhtZ3JSZHVSLTRSb3Ewdkt5M3ZLSnpuRzZxVHhWNGNVNjJub0owdl9HUndKUjU3R2dBNERpS1FMZ2h5Q2wwODNDZzRrV2w4eWVmOG9aT21WVlNnTnM4Y095WWZhWThPTHA0bXhyWGhkV25HOGd5TDZ3b3dYekIxZzBxWlFKUQ?oc=5
panjang artikel: 5704

Fetch isi artikel:  32%|███▏      | 779/2473 [20:58<2:00:52,  4.28s/it]

Fetching link: https://news.google.com/rss/articles/CBMiX0FVX3lxTE1tdmRramctdWpEN0VhaF9MektDQ0h1SElHWVB0dFRNUVBsRWdxdDJaUlZTVUlJUlRnY3JoTVlNTHkyQU5XY1pTNGZtZlF1SUtES2FKUXg0bExmZmtsZ2pn?oc=5
panjang artikel: 8586

Fetch isi artikel:  32%|███▏      | 780/2473 [21:04<2:08:14,  4.55s/it]

Fetching link: https://news.google.com/rss/articles/CBMiWkFVX3lxTE5rN2lONVRRenY4c3Y4S1phNlVrbjlkQ3c5ckpmUW9wYW9SQ2ZZRXZnUnNRX3h0ZTRfVkZDcEpGWHpzdE5RQmo1aFpJbjF3SW9DUnJ1UWdXYlNnUQ?oc=5
panjang artikel: 9204

Fetch isi artikel:  32%|███▏      | 781/2473 [21:08<2:04:39,  4.42s/it]

Fetching link: https://news.google.com/rss/articles/CBMijAFBVV95cUxObTNOa1BpcGlRM3Vfd1JWY1psQnAzcFlpTDBpaVdaN3FJQ0ctbFBibkZ5bGw4N3B0TjEtN2M4YXRLQTQyeWUwLVZyU3pvdm9JZjJOQnEzSTZhdzNBdHhHbERxcVRLN1dEQnVrU1BxNmgzY0hUVmdlVU9mR3NndXNMUS1nMzNlUlFycnVsSdIBkgFBVV95cUxPajR1X0ZXMWFWcGJhdTBzRWZ3eENqcXI5bFJGMG1YSkdiT19IbGhsa3NRYXVtdUJ5U0ZPY2N5ckY3eGlqLUVESW8wazVFNl9LaFc0c2wyNENxSy1Ua2tJRkZxWlB3MzE3Y0o0MDZvUXR1V2hfS3NEM3RDZ3FJZ1JaQmVyZUlVWmg2bG5CZDhVT21ZUQ?oc=5
panjang artikel: 3931

Fetch isi artikel:  32%|███▏      | 782/2473 [21:13<2:09:30,  4.60s/it]

Fetching link: https://news.google.com/rss/articles/CBMinAFBVV95cUxNMWVxUzA3MmhXVmV1d0t2ZDRMSXVXUEwyOVJMTnNGVkVLNW9lZl9jeUl3dHlTdGxQRXhPM3pmOVZtUFl0emhwSXBWdkswQVJJM0YtQ1ZKME9JVjZNaTFEMU81ZGJ3aEFqQURfUE9Rdm5vRkFIcVBUMGV4NnJBcHlDN0k2dXg5MEY0b3M3SVNSSUlZVmhDc2llZDhnLTk?oc=5
panjang artikel: 3010

Fetch isi artikel:  32%|███▏      | 783/2473 [21:17<2:05:35,  4.46s/it]

Fetching link: https://news.google.com/rss/articles/CBMixAFBVV95cUxOSGZjTjMzVnEwdDExcjlONlZFcXEtSXUxT1ZmNndxT1BlbDFRUVZkRkh6aFkzOTExNl8tX1ExVktXWXJMMGJJNXZtMVQxTGRQaTJRN0I1cm5ZdVpOVmh5Q18xUVhIci05blNJSkFiZVV0dEtIc1IwZUVGb19pT1pMWHhVeWVNWEowNmdFajRjVzIzeml1Q0dmZ3ltSUMxek9VeXdtTmRUOHVDNnF5VklTbldlOEV6cUw1aXZpX1pVWmVKdk9Z0gG0AUFVX3lxTE1WOFJZeXBjZWtIWE42OUFYNE5pVER5TjltbHpZT2szcHB6RXFQTXliWm01RUNta2laa3FRTFdRMlpXc1VEMTN2SWZ6Z25vQ1dXRHZwSHliajZQVGRqYXpXOGFKODNoQi1aV2lVR1FHQXVsbl9Kd0g4OXM5VUdNTmstNzNVWU1KaUlCNEM4T3dDQ1lBX3lvUnh6WkZ3UlhCYmxhczduWjd1YlNkT2ZsRV9WVGZDdg?oc=5
panjang artikel: 4996

Fetch isi artikel:  32%|███▏      | 784/2473 [21:22<2:07:20,  4.52s/it]

Fetching link: https://news.google.com/rss/articles/CBMipAFBVV95cUxQMUxKMGZCbHNYUC10eVFlcTl3X3oxWHpMSkFaQVRQZ0ZwNmxMQW9VRkNWdGxlY1ZFa1BaOEpTZ3Jqa0ZiSjNZRlMzQTZocjk0WEVyMUtSeXNJWDZ4dW1aREVUTTB4M04xbHZtOW1LWmttUk4za3hCYVdrWm9MWmktZTlOZVh2Q05feVR2dzFGR2V0NE9sZVlyYWNZaGJ4YzlQWkR5OA?oc=5
panjang artikel: 2878

Fetch isi artikel:  32%|███▏      | 785/2473 [21:26<2:05:41,  4.47s/it]

Fetching link: https://news.google.com/rss/articles/CBMiU0FVX3lxTE1ZM3RVbUMwWlBzekxCbS1iakQ1bmFCZ0xvU0Z3dE44ZlNHRFpTdnlmRVFadW9SSHVTVG9fNXhUM0ZyWkwwQmFqOG04ZHgxZmd3YkYw?oc=5
panjang artikel: 9430

Fetch isi artikel:  32%|███▏      | 786/2473 [21:30<2:00:12,  4.28s/it]

Fetching link: https://news.google.com/rss/articles/CBMiXEFVX3lxTE1CSVlJZUhiT2dTSFpScU02VVdoZGQySUtqU2hOZWtWNnd5aC1EZUI1QktuZ3pMaU9iZHAwSldoUG5EQTdtTkJLZTNPcXVLV2VPc0hzcmN4NE1FeTV3?oc=5
panjang artikel: 8944

Fetch isi artikel:  32%|███▏      | 787/2473 [21:34<1:59:57,  4.27s/it]

Fetching link: https://news.google.com/rss/articles/CBMilAFBVV95cUxPX1R3N2E2OV9uNFRZZkx0TWRfM2ZQNzI2YlRSbkZfc2xTeHBrX0ZEVGIzM1Bzc1kyaTNEQ3d4S0drZUNTOGJudE9ZeXdrTUNKMlkxeHN3MjhDYi1iOXdHaVF4MXVTX25RM0VTSVJYZWRQSDBGU3ROeV8wUno4UWtqdGNES3VNZTRmY0JDUllFUjhqNXYx0gGaAUFVX3lxTFA1WUtfNmc4cGw1Q0oxQ2xrVXNFc3ZiS204bnM4c29YaFpXNU95RlA3VVB5UHlYYl9MM185OC1tcExLdDM1Mi1VaDFNSUloNWNxakhjSndkRkZLd19MbzhCUnk2SEgtMnA0SWJTekFIejd6TzlLNFFBYmp0Y0FEVWt1SG5sekF3cW5kaHNFMlU2UU9IM0tORDNaREE?oc=5
panjang artikel: 4972

Fetch isi artikel:  32%|███▏      | 788/2473 [21:38<2:00:57,  4.31s/it]

Fetching link: https://news.google.com/rss/articles/CBMi2wFBVV95cUxOaFRFYkRqeDVvOUpTaEVreVA3M2JQRWhMS1UyanBPWEd4clJwSUhaenk4RkdDbTZBY0FSejFlNmxqdkdmUlFqSUdGWUtCeDlOaDZLT2IxYkh5YVBYQWNBbEtzcXVCRUVCX09jZXMxVDdJaXpaMlFNU2RhZjNmeW1DMVRJWXRvUGFqMGwxbjRxTThlOE5PSHVITUlhUzdlbVJKdmEtOG1jZlpSVXo5dXl0UDhpbm5hR0xPQ1ROR3dtdnZnY0hwTjlKRTlkYXNac1JOMFhMLXFfam00N03SAccBQVVfeXFMTWdaUHVuMlh5U1dVbzBxcGxONldoTlE3ZjVfODZxaFdRc2tkR0NncEhqQ1QyWC1vN2RqUFhzanV4dVl0aWx6Vm5rOUlxMlJmSjFvQUhoTkNfZVkzNUVVUkowWjJNalRBTXB2dFY1b0JJaDJEVkY1WlJybEtXT2FjNmFsN1F4VkxyUHlTZmo0Tl9ySDM2VUl3akNzdTNtb2ZnMjZuakpiWkR2cHdEVXFPal9neC00SDc5YmFrbUNoWDZQMGE3OEhKdw?oc=5
panjang artikel: 1944

Fetch isi artikel:  32%|███▏      | 789/2473 [21:42<1:59:01,  4.24s/it]

Fetching link: https://news.google.com/rss/articles/CBMia0FVX3lxTE5xNWE1eTNUbG5ERTc0WVUzNHMtV1BzY2Rtczd0bGl4aG4wTmNHSEdNaUU5eGdnX1ZsbkZVb09PeXdCZ0k0dE1HTnhGenZZVlZ1VjB3MFZoUjVqamVkdDFfOGZ4Q294X3pmSjYw?oc=5
panjang artikel: 9142

Fetch isi artikel:  32%|███▏      | 790/2473 [21:47<2:00:55,  4.31s/it]

Fetching link: https://news.google.com/rss/articles/CBMivAFBVV95cUxPb1MweEZMVGVYQVhDZHhLak1Rb3pQd1ZkNGZWZUNlV2dYWXBfaUJYS01XT0lmTmstbUdmRWYwczUzWmF3S2tXQm9OQ2htSUVha0taVXg3eGZ6eFpVanVzS19sQkpWQ18yVVhEZGNFTjBxV01UTzZSZV9EYnFMSERwNDRMdTR3VVhHb2c0Ml96UFJXS3lEcTNMNWpKNkFKcUx4YVhpQjFTMTZPazlIQWhtZ0Q4NzRwM2VHOWpoSdIBqAFBVV95cUxNQVpDUDBuNTBoMTd3bUlsX3EzbUZPamtTVWl6MlZabVRUYjJFWHJIRS1NSmYxOTh2TWJmOWZVRXBfV1NMSFJ0V195anplbDlaR0lKMFZfbU5mSm1BVVZGSGRaZTJMb3RCQ2t5UkZkWTZFOVpNdkYzbGpQdkNObWtmYmJTVldqSW9HUkRGdE1IMkthblJ6OTBha2U5UjRUcGVWZm9tXzUxTG4?oc=5
panjang artikel: 2306

Fetch isi artikel:  32%|███▏      | 791/2473 [21:51<1:56:36,  4.16s/it]

Fetching link: https://news.google.com/rss/articles/CBMi0wFBVV95cUxPbXlBeE9hLUFIem9NdVN3bG1xUXA3bDJYWFFoX083THp3ZXg2aVJYeF9qeWZFX2hFaUd3SlFQQmlBblNWc1FiOWo1NjUtOTZZSzlBWUt6R2I1RUVyUnVhdG5WbkNfV2NwaDNkVWhOVE9HVTBGa2VmSjJjYlJ5TnJpTjFPdlBUYkJnR3dIYmxZWjNBQUI4cnpBWEZZOVc5THFueExYa1FHal9DdUU0SWc0MlBNS3pWRi13ZWFOZW1hT3NLaUlWZkhoVHBBM3hUai1mWkt3?oc=5
panjang artikel: 5852

Fetch isi artikel:  32%|███▏      | 792/2473 [21:55<1:56:00,  4.14s/it]

Fetching link: https://news.google.com/rss/articles/CBMizgFBVV95cUxOR09ScFFDMDVHRFhPYzY0ZC03Y2pvQWVvYjNDODcwTkduV3FsbkticENKZ0h3Y2hGQjlVUkIyeUtGUTFQbDQxQWM2MFJMcEFzNjR5MHQxX1RQOGJVYlBZcnBqN05Nb19ZSUtwMHpxWjhqT2FoMzhVaVRWZWlPNXNwM3FSc3RzVW51eFZVOXdzV3JRMUYtQlMwbXo1bWE3UTRBRmZLNnB0WFVnalF1UVdJTDNyWVh1YXRaRDFhS0MtQzNUWDRUSWpMaU9TVkV1QQ?oc=5
panjang artikel: 6944

Fetch isi artikel:  32%|███▏      | 793/2473 [21:59<1:54:23,  4.09s/it]

Fetching link: https://news.google.com/rss/articles/CBMisgFBVV95cUxNOTAwOXFfTGpTYlhseC1KZF9RNEpKXy12R29OZzhESlVEWlkzc3VSNTVaTlg2YVRJVjB6S0VBNjVOQ1pPdl94T3BPNm9LbTlCZE9qbmQ1VzExZXItTDJLQzQwSjhJbnlfVWRKdDlkSGhnYVNFT3FUaS04MFp5eVJzbmVBZHp3WnRJYXhaNngtZWlhRDluMEwyZDNRa2NidjR2WVlXYWRWZWNLX3FtQVctckNR?oc=5
panjang artikel: 2020

Fetch isi artikel:  32%|███▏      | 794/2473 [22:02<1:51:10,  3.97s/it]

Fetching link: https://news.google.com/rss/articles/CBMisAFBVV95cUxQa0gxU21jbWVwMHZKNWhKaEtnY2xxckNyeW13ZW9FdW1iazA1WEZmeERBblliLWx2TXlFTDBndnpOa3ZEZVZyOTVvbGZjOVFEMTZOUFhzcjlUWmhfdXVkUGtBeWpPZlVVUlBCLXpDYXY4UHhBZ2tBaHA1NENKV1BuWlI2VkZIT0h4UmwwQjhfM0paVnlsQ3l2SGxORUtKU3BfbmV2VXJ2Sm93bDl4Y1l6WdIBtgFBVV95cUxPYkQ4b3hRWF9xRmE0WnZMRDM3UkhRZkZmZUMzb2xxOWhlVTdLTjFfS2tNY3ZkVjdLMGVoN2g5MDZXSzFDbW1qVEMyQTd3MUVyMnRjYWtTSXNpSHdmTTJxTFowZHFQdW9qbFIyTzBmdlRERktobHpuVk1mYjhBR0lKQ2YwUWNWQkYxTVpIYnNiclZBVFU2Rkg0dllmZFRrb2JxSkpJTXZYTkR2bTNiSEd0MXRPZFc3QQ?oc=5

Fetch isi artikel:  32%|███▏      | 794/2473 [22:08<46:49,  1.67s/it]

KeyboardInterrupt:

In [12]:
df_news.to_csv("df_news_extended_503_757.csv", index=False)

In [ ]:
df_news["link"]

0      https://news.google.com/rss/articles/CBMifkFVX...
1      https://news.google.com/rss/articles/CBMitgFBV...
2      https://news.google.com/rss/articles/CBMiwgFBV...
3      https://news.google.com/rss/articles/CBMidEFVX...
4      https://news.google.com/rss/articles/CBMiaEFVX...
                             ...
123    https://news.google.com/rss/articles/CBMirwFBV...
124    https://news.google.com/rss/articles/CBMiqgFBV...
125    https://news.google.com/rss/articles/CBMisAFBV...
126    https://news.google.com/rss/articles/CBMiyAFBV...
127    https://news.google.com/rss/articles/CBMizwFBV...
Name: link, Length: 128, dtype: object

In [ ]:
article_texts

['Jumat, 25 September 2026 08:00 UTC Ilustrasi: Pilihan dari Layar. -Dx Gen-AI JATIMNET.COM -\xa0Media sosial mengubah cara memilih tempat makan dalam kehidupan sehari-hari. Restoran yang sebelumnya ditemukan lewat papan nama atau rekomendasi teman kini bisa dikenal melalui video berdurasi beberapa detik. Perubahan tersebut berlangsung di tengah masyarakat Indonesia yang semakin terkoneksi. Data APJII 2025 yang dikutip Kementerian Komunikasi dan Digital mencatat pengguna internet mencapai 229,4 juta orang atau 80,66 persen populasi. Lebih dari 140 juta di antaranya aktif berinteraksi melalui media sosial. Artinya, rekomendasi kuliner tidak lagi bergerak hanya dari mulut ke mulut. Foto, ulasan singkat, video menu, lokasi, hingga komentar pelanggan ikut membentuk keputusan sebelum seseorang berangkat makan. Media Sosial Menjadi Etalase Tempat Makan Dahulu, mencari restoran baru sering dimulai dengan bertanya kepada teman. Cara tersebut masih bertahan, tetapi kini rekomendasinya kerap dilengkapi tautan unggahan atau video. Seseorang dapat mengetahui tampilan makanan, kisaran suasana tempat, kepadatan pengunjung, hingga menu populer sebelum datang. Informasi itu membuat proses memilih terasa lebih praktis. Kondisi tersebut bertemu dengan industri kuliner yang sangat besar. Badan Pusat Statistik mencatat sekitar 5,28 juta usaha penyediaan makanan dan minuman beroperasi di Indonesia pada 2024. Jumlahnya naik sekitar 8,71 persen dibandingkan tahun sebelumnya. Dari jumlah tersebut, sekitar 2,51 juta merupakan restoran dan rumah makan. Kelompok ini mengambil porsi 47,59 persen dari keseluruhan usaha penyediaan makanan dan minuman pada 2024. Pilihan yang begitu banyak membuat konsumen membutuhkan cara untuk menyaringnya. Media sosial kemudian berfungsi seperti etalase awal sebelum keputusan makan benar-benar dibuat. Video Pendek Mempercepat Rasa Penasaran Konten kuliner mempunyai keuntungan visual. Lelehan keju, kuah panas, sambal yang baru diulek, atau potongan daging dapat terlihat menarik tanpa narasi panjang. Video pendek membuat pengalaman tersebut semakin cepat. Dalam beberapa detik, calon pelanggan bisa melihat makanan disiapkan, disajikan, lalu dicicipi. Rasa penasaran kemudian mendorong perilaku sederhana. Pengguna menyimpan unggahan, mengirimnya kepada teman, mencari lokasi, atau memasukkannya ke daftar tempat yang ingin dikunjungi. Skalanya besar karena internet sudah digunakan mayoritas penduduk. Penetrasi 80,66 persen pada 2025 berarti sekitar delapan dari setiap sepuluh orang Indonesia telah terhubung dengan internet. Bagi usaha kuliner, kondisi tersebut membuka peluang yang dahulu sulit diperoleh usaha kecil. Warung sederhana dapat dikenal lebih luas ketika menu atau suasananya menarik perhatian pengguna. Namun, viralitas bukan jaminan pengalaman yang selalu sama. Potongan video terbaik belum tentu menggambarkan antrean, pelayanan, ukuran porsi, kebersihan, atau konsistensi rasa sehari-hari. Ramai di Layar Belum Tentu Cocok di Lidah Salah satu tantangan memilih tempat makan dari media sosial adalah kecenderungan menilai sesuatu berdasarkan bagian yang paling menarik secara visual. Video berdurasi pendek biasanya menampilkan menu unggulan. Sementara itu, pengalaman konsumen sebenarnya terdiri dari lebih banyak unsur, termasuk rasa, harga, kenyamanan, kebersihan, dan pelayanan. Karena itu, popularitas sebaiknya diperlakukan sebagai pintu masuk informasi, bukan satu-satunya alasan berkunjung. Besarnya bisnis kuliner juga menunjukkan mengapa konsumen perlu lebih selektif. Pada 2023 saja, BPS mencatat terdapat 4,85 juta usaha penyediaan makanan dan minuman dengan nilai penjualan sekitar Rp998,37 triliun. Sektor tersebut menyerap sekitar 9,80 juta tenaga kerja pada tahun yang sama. Dibandingkan 2016 yang mencatat 8,13 juta pekerja, jumlah tenaga kerja pada 2023 meningkat 20,48 persen. Angka tersebut memperlihatkan luasnya ekosistem kuliner Indonesia. Dalam pasar sebesar itu, wajar bila pengalaman antara satu tempat dan lainnya sangat beragam. Calon pelanggan dapat menggunakan media sosial untuk menemukan pilihan, kemudian melengkapinya dengan informasi lain. Harga terbaru, alamat, jam buka, menu, dan ulasan pelanggan dapat membantu membangun gambaran yang lebih utuh. Konten Viral Bisa Mengubah Arus Pengunjung Bagi usaha makanan skala kecil, perhatian di media sosial dapat membawa perubahan cepat. Tempat yang sebelumnya dikenal warga sekitar tiba-tiba bisa didatangi pelanggan dari wilayah lain. Fenomena semacam ini semakin mungkin terjadi karena jumlah usaha kuliner juga bertambah. BPS mencatat 4,85 juta usaha pada 2023, kemudian jumlahnya meningkat menjadi sekitar 5,28 juta pada 2024. Persaingan mendapatkan perhatian konsumen pun menjadi lebih ketat. Sebuah usaha bukan hanya bersaing dengan tempat di sebelahnya, tetapi juga dengan berbagai rekomendasi yang muncul pada layar pelanggan. Namun, lonjakan pengunjung membutuhkan kesiapan. Stok bahan, waktu pelayanan, kapasitas tempat duduk, kebersihan, dan konsistensi kualitas harus mengikuti peningkatan permintaan. Konten yang berhasil menarik pelanggan pertama kali tidak otomatis membuat mereka kembali. Setelah rasa penasaran selesai, kualitas pengalaman menjadi faktor yang jauh lebih menentukan. Di sinilah media sosial dan pelayanan nyata mempunyai peran berbeda. Media sosial dapat membuka pintu, sementara makanan dan layanan menentukan apakah pelanggan ingin datang lagi. Memilih Tempat Makan dengan Lebih Cermat Media sosial tetap menjadi alat yang berguna untuk menemukan pengalaman kuliner baru. Masalah muncul ketika keputusan sepenuhnya bergantung pada satu video yang sedang ramai. Ada baiknya melihat beberapa unggahan dengan waktu berbeda. Cara ini membantu mengetahui apakah sebuah tempat konsisten menarik perhatian atau hanya muncul sesaat karena satu konten viral. Perhatikan pula kebutuhan pribadi. Restoran yang cocok untuk nongkrong ramai belum tentu nyaman untuk membawa keluarga. Tempat dengan menu unik juga belum tentu sesuai dengan anggaran makan harian. Harga pada konten lama juga dapat berubah. Informasi praktis seperti jam operasional dan ketersediaan menu sebaiknya diperiksa kembali sebelum melakukan perjalanan khusus. Cara memilih tempat makan akhirnya memang berubah. Dengan lebih dari 229 juta pengguna internet dan jutaan usaha kuliner di Indonesia, layar ponsel telah menjadi salah satu titik pertemuan penting antara konsumen dan penjual. Media sosial dapat mempertemukan kita dengan warung kecil, menu daerah, atau restoran yang sebelumnya tidak pernah diketahui. Namun, rekomendasi digital paling berguna ketika dipakai sebagai referensi, bukan sebagai jaminan. Pada akhirnya, cara memilih tempat makan yang lebih bijak tetap membutuhkan kombinasi rasa penasaran dan pertimbangan sederhana. Viral boleh menjadi alasan pertama datang, tetapi rasa, harga, kebersihan, pelayanan, dan kenyamananlah yang menentukan pengalaman sebenarnya. Sumber data: Badan Pusat Statistik, Statistik Penyediaan Makanan dan Minuman 2023 dan 2024; Kementerian Komunikasi dan Digital; Indeks Masyarakat Digital Indonesia 2025 berdasarkan data APJII 2025.',
 'Di Jakarta dan Bogor, ada kedai soto mie yang sudah buka sejak puluhan tahun lalu dan terkenal lezat. Bahkan sampai sekarang masih terus diburu oleh pelanggannya. Soto mie menjadi salah satu hidangan berkuah yang mudah ditemui di Jakarta dan Bogor. Isinya komplet sehingga makan semangkuk saja sudah cukup mengenyangkan. Beberapa penjualnya sudah bertahan selama puluhan tahun. Racikan kuah, isian, hingga pelengkapnya menjadi daya tarik yang membuat pelanggan terus datang. SCROLL TO CONTINUE WITH CONTENT Menariknya, tiap penjual memiliki ciri khas berbeda yang membuat pengalaman menyantap soto mie tidak selalu sama. Ada yang terkenal dengan risol jumbo, daging melimpah, hingga kuah gurih yang khas. Warung ini menjadi salah satu penjual soto mie yang bertahan selama puluhan tahun. Menu andalannya berupa soto mie dengan potongan daging sapi yang empuk. Harganya mulai sekitar Rp30 ribu untuk satu porsi, tersedia ukuran biasa dan besar. Alamatnya di Jalan Raya Karang Anyar E No.42, Sawah Besar, Jakarta Pusat. Soto Mie Agih dikenal sebagai salah satu kuliner legendaris Bogor sejak 1965an. Menu andalannya antara lain soto mie babat, bakut, campur, spesial, hingga jumbo. Harga yang tercatat berkisar mulai Rp40 ribuan per porsi. Alamatnya di Jalan Suryakencana No.313, Babakan Pasar, Bogor Tengah. Soto Mie Sarodja mulai berjualan pada 1970 dengan pikulan dari Grogol hingga Pejompongan. Kini usaha tersebut telah diteruskan oleh generasi kedua. Gerainya berada di Jalan Danau Tondano No.27, Pejompongan, Jakarta Pusat. Harganya sekitar Rp42 ribu, sedangkan versi bakso dibanderol Rp47 ribu. Soto Mie Theresia sudah dikenal sebagai kuliner legendaris Jakarta sejak 1972. Gerobaknya berada di kawasan Kuliner Theresia, Menteng, yang juga telah lama menjadi pusat jajanan. Harga soto mie di sini dipatok mulai Rp21 ribuan. Alamatnya di Jalan Gereja Theresia No.43, Menteng, Jakarta Pusat. Soto Mie Pak Fauzy sudah berjualan sejak 1974 dan termasuk kuliner legendaris di kawasan Suryakencana. Ciri khas dari soto mie di sini ialah kuahnya yang segar berkaldu. Soto Mie Pak Fauzy berada di Teras Suryakencana, Jalan Bata, Babakan Pasar, Bogor Tengah. Harga per porsi dibanderol mulai dari Rp20 ribuan. Soto Mie Puri H. Darjo mulai berjualan sejak 1988 dengan gerobak keliling di sekitar Puri Kembangan. Warung tetapnya kemudian berkembang dan dikenal karena risol sepanjang 50 sentimeter. Soto mie biasa dibanderol Rp25 ribu, sedangkan yang dengan tambahan bakso Rp30 ribu. Alamatnya di Jalan Kembang Abadi Utama No.7, Kembangan Selatan, Jakarta Barat. Soto Mie Mang Ohim mulai dibuat dan dijual pada 2005 di Bogor. Racikannya dikenal dengan kuah gurih serta risol renyah yang menjadi pelengkap khas. Alamatnya di Jalan Raya Taman Cimanggu No.22, Tanah Sareal, Bogor. Harga semangkuk soto mie di sini mulai dari Rp26 ribuan. Anda menyukai artikel ini',
 'RRI.CO.ID, Yogyakarta - Daerah Istimewa Yogyakarta (DIY).dikenal luas sebagai surganya kuliner murah di Indonesia, tempat menikmati hidangan otentik Jawa hingga sajian internasional tanpa menguras dompet. Sejumlah restoran hadir menawarkan sajian khasnya, termasuk diantaranya tujuh rekomendasi restoran murah di Jogja, lengkap dengan kisaran harga, lokasi, menu andalan, serta panduan langkah demi langkah untuk memesan makanan lewat Grab. Restoran ramah kantong yang dimaksud di sini adalah tempat makan dengan harga menu utama umumnya di bawah Rp75.000, cocok untuk mahasiswa, keluarga, maupun wisatawan yang ingin kuliner Jogja hemat tanpa kompromi rasa. Di aplikasi Grab, juga bisa memesan lewat GrabFood, memilih Ambil Sendiri, atau reservasi makan lewat Grab Dine Out. Disamping itu, bisa memanfaatkan fitur filter di aplikasi Grab, mulai dari harga, rating, hingga promo, serta Google Maps untuk memvalidasi ulasan dan jam buka sebelum memesan. Harga, jam buka, dan ketersediaan menu dapat berubah sewaktu-waktu. Rekomendasi Restoran Ramah Kantong Berikut tujuh rekomendasi restoran ramah kantong di Yogyakarta yang dapat dipertimbangkan berdasarkan variasi kuliner, lokasi, kisaran harga, dan rating yang tercantum di GrabFood saat materi ini disusun. Pilihannya mencakup gudeg, mi, makanan berbasis sayuran, masakan Italia, hidangan Hong Kong, dan sate kambing klathak. Harga, rating, menu, dan ketersediaan dapat berubah, jadi periksa kembali informasi terbaru sebelum memesan atau berkunjung. Gudeg Yu Djum telah menjadi salah satu ikon kuliner Jogja sejak 1950-an. Beralamat di Jl. Wijilan No. 167, Panembahan, Kraton, warung ini menyajikan gudeg tradisional dengan harga mulai sekitar Rp20.000-an per porsi menurut berbagai liputan kuliner Jogja. Ini merupakan pilihan menarik bagi pencinta gudeg yang menginginkan porsi ekonomis. Untuk melihat menu dan informasi terbaru sebelum memesan, cek listing Gudeg Yu Djum di GrabFood. Gudeg Pawon menawarkan pengalaman unik, gudeg dimasak langsung di pawon, atau dapur tradisional Jawa, dan hanya buka pada malam hari dengan kuota terbatas. Terletak di area Janturan, Umbulharjo, tempat ini memiliki kisaran harga Rp15.000 hingga Rp30.000. Karena antrean dan kapasitas dapat berubah, periksa jam buka serta ketersediaan Gudeg Pawon di GrabFood sebelum berangkat atau memesan. Yammie Pathuk adalah salah satu pilihan mi pangsit di area Pathuk, Ngampilan, dengan harga Rp10.000 hingga Rp25.000. Tempat ini cocok bagi kamu yang mencari makanan sederhana dengan harga terjangkau. Di GrabFood, konsumen dapat membandingkan menu, tambahan pesanan, promo, dan total biaya sebelum checkout. Lotek & Gado-Gado Teteg Lempuyangan Lotek dan Gado-Gado Teteg di Danurejan menyajikan sayuran dengan bumbu kacang, dengan harga mulai dari Rp10.000 hingga Rp20.000. Pilihan ini cocok untuk kamu yang mencari makanan berbasis sayuran dengan harga yang terjangkau. Cek listing Lotek dan Gado-Gado Teteg di GrabFood untuk melihat menu yang tersedia serta pilihan delivery atau Ambil Sendiri jika tersedia. Aroma Italia menyajikan aneka hidangan Italia homemade, seperti pizza dan pasta dengan opsi gluten-free, mulai dari Rp30.000. Jika tersedia di lokasi sekitar, gunakan listing Aroma Italia di GrabFood untuk melihat menu dan harga terbaru. Hong Kong Street Foods Hong Kong Street Foods berjarak sekitar lima menit dari Tugu Jogja dan buka pukul 10.30 hingga 21.00 WIB. Pilihan menu dan ketersediaannya dapat berbeda dari waktu ke waktu. Restoran ini menawarkan pilihan seperti dim sum dan nasi Hong Kong dengan kisaran harga Rp20.000 hingga Rp50.000. Cek kembali jam operasional, menu, dan ketersediaannya di GrabFood sebelum memesan. Sate Kambing Klathak Bu Jazim Sate Kambing Klathak Bu Jazim di Bantul menyajikan sate kambing klathak yang dibakar di atas arang dengan jeruji besi sebagai tusuknya, sehingga memberikan pengalaman kuliner yang khas. Sebelum datang atau memesan, cek listing Sate Kambing Klathak Bu Jazim di GrabFood untuk melihat menu, harga terbaru, jam operasional, serta ketersediaan delivery atau Ambil Sendiri dari lokasi kamu. Cara Mengecek Review dan Jam Buka Gunakan GrabFood untuk memeriksa menu, harga, promo, rating, dan pilihan pengantaran. Google Maps dapat digunakan sebagai pemeriksaan tambahan untuk melihat lokasi, jam buka, foto terbaru, dan ulasan pelanggan. Saat membandingkan restoran, jangan hanya melihat skor rating. Hal yang perlu diperhatikan juga jumlah ulasan, lalu baca sekitar 5 sampai 10 komentar terbaru tentang rasa, porsi, harga, kebersihan, dan kecepatan layanan. Informasi dapat berubah, jadi konfirmasi kembali melalui GrabFood, Google Maps, atau kanal resmi restoran sebelum memesan atau berkunjung. Panduan Memesan Makanan Lewat Grab Kebiasaan yang Membuat Pesanan Lebih Efisien Simpan restoran favorit Gunakan ikon hati atau bookmark agar dapat memesan ulang tanpa harus mencari dari awal. Pilih restoran dekat Restoran dalam radius sekitar 3–5 km biasanya membantu menghemat ongkir dan memastikan makanan tiba lebih cepat. Jam buka beberapa restoran dapat berubah, terutama restoran yang memiliki kuota terbatas atau hanya beroperasi pada malam hari.nKonfirmasi kembali jam operasional Gudeg Pawon dan restoran lainnya sebelum memesan. Memilih Restoran Murah di Jogja dengan Lebih Yakin Gunakan GrabFood dan masukkan kata kunci seperti "restoran murah Jogja", "gudeg", atau "mi ayam", lalu filter berdasarkan jarak, rating, harga, dan promo. Untuk memastikan pilihan tetap sesuai anggaran, periksa harga menu utama dan bandingkan beberapa restoran serupa sebelum checkout. Jangan hanya melihat skor rating, baca sekitar 5 sampai 10 ulasan terbaru yang membahas rasa, porsi, harga, kebersihan, dan kecepatan layanan. Untuk menghindari harga yang tidak sesuai ekspektasi, lihat daftar harga lengkap dan verifikasi informasi melalui ulasan terbaru, Google Maps, atau kanal resmi restoran. Tidak semua restoran selalu tersedia di GrabFood karena ketersediaannya dipengaruhi oleh jam operasional, lokasi mitra, dan kebijakan restoran. Jika layanan tertentu tidak tersedia, pertimbangkan Ambil Sendiri atau Grab Dine Outnjika ditawarkan oleh restoran. Saat memesan, pastikan alamat dan pin pengantaran benar, tambahkan catatan makanan bila diperlukan, periksa voucher dan biaya akhir, lalu pilih metode pembayaran yang tersedia. Memuat berita terbaru.....',

In [32]:
sample_urls = df_news["link"].head(3)
sample_results = []
for sample_url in sample_urls:
    sample_final_url, sample_html = resolve_and_fetch(sample_url)
    sample_results.append((sample_final_url, extract_article_text(sample_html)))
print("Sampel berhasil diekstrak:", sum(len(text) >= 100 for _, text in sample_results), "dari", len(sample_results))
print("URL sumber pertama:", sample_results[0][0])
print("Panjang teks:", [len(text) for _, text in sample_results])

Sampel berhasil diekstrak: 3 dari 3
URL sumber pertama: https://jatimnet.com/media-sosial-mengubah-cara-kita-memilih-tempat-makan
Panjang teks: [7110, 2855, 6105]

In [33]:
final_urls

['https://jatimnet.com/media-sosial-mengubah-cara-kita-memilih-tempat-makan',
 'https://food.detik.com/rumah-makan/d-8679688/awas-kalap-ini-7-tempat-makan-soto-mie-legendaris-di-jakarta-dan-bogor',
 'https://aktualita.co/ragam/tiktok-food-fest-2026-hari-terakhir-gbk',
 'https://rri.co.id/yogyakarta/kuliner/2752639/rekomendasi-7-tempat-makan-ramah-kantong-di-jogja-dan-tips-menggunakan-grabfood',
 'https://www.nibble.id/tempat-makan-viral-di-bandung-2026/',
 'https://www.tripzilla.id/tempat-makan-di-bekasi-hits-legendaris-dan-ramah-kantong/27718',
 'https://jogja.disway.id/gaya-hidup/read/702022/deretan-warung-ayam-goreng-legendaris-paling-hits-di-purwokerto-dengan-cita-rasa-rempah',
 'https://jatim.idntimes.com/food/dining-guide/10-rekomendasi-kuliner-malam-di-sidoarjo-cocok-bagi-pencinta-kuliner-c1c2-01-njfwj-gnsrbz',
 'https://www.rumah123.com/explore/kota-jakarta-timur/tempat-makan-di-jakarta-timur-yang-murah-dan-enak/',
 'https://erafone.com/artikel/post/wisata-kuliner-malang-04',
 'https://www.hipwee.com/travel/tempat-makan-murah-di-tangerang/',
 'https://rri.co.id/madiun/kuliner/2758486/harmadha-joglo-tempat-kuliner-hits-magetan',
 'https://food.detik.com/tempat-makan/d-8549503/7-tempat-makan-di-garut-yang-enak-dan-murah-favorit-warga-lokal',
 'https://www.tripzilla.id/tempat-makan-di-depok/27073',
 'https://www.nibble.id/restoran-baru-di-bogor-juni-2026/',
 'https://jogja.disway.id/gaya-hidup/read/701716/wisata-kuliner-tempat-makan-paling-populer-dan-menggugah-selera-di-sekitar-kelapa-gading',
 'https://www.hipwee.com/travel/tempat-makan-keluarga-di-palembang/',
 'https://www.tripzilla.id/tempat-makan-hits-bandung/27057',
 'https://www.hipwee.com/travel/rekomendasi-tempat-makan-di-kebumen/',
 'https://food.detik.com/rumah-makan/d-8550840/7-kuliner-hits-di-ciledug-yang-lagi-viral-ada-nasi-goreng-yang-antre-1-jam',
 'https://www.hipwee.com/travel/tempat-makan-murah-di-depok/',
 'https://food.detik.com/resto-dan-kafe/d-8538065/5-tempat-makan-enak-di-ampera-raya-jaksel-ada-nasi-bali-hingga-live-seafood',
 'https://www.hipwee.com/travel/tempat-makan-murah-di-surabaya/',
 'https://jatim.idntimes.com/food/dining-guide/8-rekomendasi-tempat-makan-di-kota-kediri-makan-bareng-yuk-c1c2-01-n4hg7-3kl2t9',
 'https://metropolis.batampos.co.id/jelajah-kuliner-batam-5-tempat-makan-baru-dengan-menu-unik-dan-instagramable/',
 'https://rri.co.id/tanjungpinang/kesehatan/2756719/kuliner-viral-bermunculan-apa-yang-perlu-diperhatikan-sebelum-ikut-mencoba',
 'https://www.hariansib.com/Kuliner/450454/festival-kuliner-gang-viral-jakarta-hadir-di-medan/',
 'https://www.kompas.com/food/read/cm/2026/09/24/104012175/bagaimana-cara-mencari-mie-gacoan-terdekat-dan-kuliner-viral-lain-di',
 'https://lembang-bantaengkab.digitaldesa.id/potensi/-viral-di-bantaeng-maevan-cafe-hadirkan-surga-kuliner-dengan-pesona-sunset-memikat',
 'https://food.detik.com/pengalaman-bersantap/d-8680372/di-tiktok-food-fest-2026-ada-mochi-gelato-hingga-nasi-lidah-enak',
 'https://www.tripzilla.id/kuliner-blok-m-hub-jakarta/27660',
 'https://jabar.antaranews.com/berita/708412/rekomendasi-kuliner-viral-di-sepanjang-jalan-cibeunying-utara-bandung',
 'https://tangerangkota.go.id/berita/detail/68715/hadirkan-cita-rasa-betawi-sunda-rm-sari-moerni-jadi-destinasi-kuliner-baru-di-kota-tangerang',
 None,
 'https://rm.id/baca-berita/education/326683/jebakan-fomo-kuliner-viral-saat-validasi-media-sosial-ancam-kesehatan-gen-z',
 'https://www.antarafoto.com/id/view/2850808/festival-kuliner-viral-indonesia-di-makassar',
 'https://rri.co.id/banjarmasin/regional/2759213/fenomena-fomo-kuliner-viral-picu-belanja-impulsif-generasi-muda',
 'https://www.idxchannel.com/ecotainment/kuliner-viral-jadi-daya-tarik-blok-m-masuk-daftar-destinasi-favorit-wisman-malaysia',
 'https://padek.jawapos.com/sumbar/2608250023/kuliner-halal-gang-senggol-jakarta-viral-hadir-di-padang-ini-daftar-tenantnya',
 'https://jabar.antaranews.com/berita/707015/rekomendasi-kuliner-viral-pasar-cihapit-bandung-dari-brownies-kunafa-hingga-warung-bu-eha-legendaris',
 'https://www.tripzilla.id/kuliner-jalan-sabang-murah-legendaris-viral/27681',
 'https://www.tangerangkota.go.id/berita/detail/67479/cari-sarapan-enak-di-kota-tangerang-ini-rekomendasi-tempatnya',
 'https://rri.co.id/makassar/ekonomi/umkm/2739221/kuliner-viral-di-media-sosial-peluang-baru-bagi-umkm',
 'https://rri.co.id/ambon/ekonomi/umkm/2725229/gaya-hidup-sehat-kuliner-viral-3-umkm-ambon-bagikan-rahasia-sukses',
 'https://food.detik.com/info-kuliner/d-8530757/main-ke-jagakarsa-ada-7-kuliner-viral-dari-gemblong-hingga-lopis',
 'https://www.bincangbincangmobil.com/cars-featured/833001700/berburu-kuliner-viral-di-bandung-bersama-honda-step-wgn?page=2',
 'https://informasi.com/nasional/infrms-28254/viral-parkir-motor-rp150-ribu-di-cafe-baked-gunawarman-jaksel-parkir-valet-atau-pungli',
 'https://20.detik.com/spot-wisata/20260902-260902049/mengunjungi-cafe-viral-yang-instagramable-di-seminyak-bali',
 'https://lampung.idntimes.com/news/lampung/viral-catatan-kasir-cafe-di-balam-customer-marah-soal-pesanan-seblak-00-jf67w-4sk93g',
 'https://www.bloombergtechnoz.com/detail-news/107928/10-cafe-viral-di-mekkah-madinah-sekitarnya/2',
 None,
 'https://www.cnbcindonesia.com/news/20260710114636-4-749767/viral-penggeledahan-kafe-cipete-rumah-sentul-ini-penjelasan-jampidsus',
 'https://www.waspada.id/berita/sempat-viral-cafe-janna-patumbak-akhirnya-digerebek-dan-di-police-line',
 'https://www.inilah.com/cafe-viral-di-pantai-indah-kapuk',
 'https://20.detik.com/spot-wisata/20260809-260809048/menikmati-suasana-cafe-viral-nuansa-yunani-jakarta',
 'https://www.bloombergtechnoz.com/detail-news/107928/10-cafe-viral-di-mekkah-madinah-sekitarnya',
 'https://metropolis.batampos.co.id/viral-di-batam-ini-5-cafe-baru-hits-yang-cocok-buat-nongkrong-santai/',
 'https://20.detik.com/spot-wisata/20260809-260809049/menyantap-kuliner-lezat-di-cafe-viral-jakarta',
 'https://20.detik.com/spot-wisata/20260716-260716196/bergaya-di-cafe-viral-yang-instagramable-di-bogor',
 'https://20.detik.com/spot-wisata/20260716-260716133/menyusuri-cafe-viral-yang-menghadap-laut-di-pangandaran',
 'https://20.detik.com/spot-wisata/20260719-260719106/berkuliner-di-cafe-viral-yang-hits-di-cianjur',
 'https://news.detik.com/berita/d-8444727/ditjenpas-sultra-tindak-tegas-napi-yang-viral-berkeliaran-ke-coffee-shop',
 'https://news.detik.com/berita/d-8571939/viral-kafe-declan-di-depok-tutup-bagian-depan-dipasang-rantai',
 'https://www.detik.com/jogja/plesir/d-8471001/7-cafe-kucing-di-jogja-dan-menunya-asiknya-ngopi-dan-nongkrong-bersama-anabul',
 'https://suarausu.or.id/maru-bake-house-sensasi-nongkrong-bernuansa-gua-viral-di-medan/',
 'https://news.detik.com/berita/d-8627474/viral-pria-ngamuk-dipicu-rebutan-parkir-di-kafe-bogor-polisi-cek-tkp',
 'https://bacamalang.com/viral-di-medsos-kenzs-hill-cafe-resto-batu-suguhkan-panorama-360-derajat-sunrise-hingga-citylight-point/',
 'https://food.detik.com/info-kuliner/d-8675683/viral-restoran-teriak-di-spanyol-pesan-makanannya-mirip-lelang',
 'https://investor.id/lifestyle/455584/restoran-dengan-fried-mozzarella-yang-viral-buka-gerai-kedua',
 'https://jatim.akurat.co/news/891580/viral-di-pasuruan-maling-terekam-cctv-curi-besi-tutup-saluran-air-di-restoran-cepat-saji',
 'https://jogja.disway.id/gaya-hidup/read/701701/deretan-restoran-baru-di-bali-paling-hits-tempat-makan-estetik-dan-kuliner-kekinian-viral',
 'https://mitrapost.com/2026/09/19/viral-pungli-di-alun-alun-kidul-capai-rp1-juta-per-hari-pemilik-restoran-menjerit/',
 'https://food.detik.com/info-kuliner/d-8675225/viral-ayah-12-tahun-jualan-tisu-depan-resto-demi-menanti-anaknya-pulang',
 'https://food.detik.com/info-kuliner/d-8663142/jago-gaet-pelanggan-bocah-5-tahun-ini-viral-saat-kerja-di-restoran',
 'https://surabaya.kompas.com/read/2026/08/21/230542378/viral-dugaan-pelecehan-di-restoran-korea-surabaya-kuasa-hukum-ungkap-ada?page=all',
 'https://www.detik.com/jogja/berita/d-8673195/babak-baru-kasus-pungli-parkir-food-truck-bolosego-di-alkid-jogja',
 'https://www.detik.com/jogja/berita/d-8669436/jukir-alkid-jogja-balikin-rp-3-juta-ke-food-truck-resto-viral-sambat-pungli',
 'https://www.detik.com/jogja/berita/d-8668886/viral-food-truck-resto-sambat-kena-pungli-di-alkid-jogja',
 'https://www.detik.com/jogja/berita/d-8669389/respons-wawali-jogja-soal-viral-truck-resto-sambat-kena-pungli-di-alkid',
 'https://food.detik.com/info-kuliner/d-8648567/viral-cctv-rekam-aksi-pengunjung-rusak-sofa-di-resto-bebek-jakbar',
 'https://20.detik.com/spot-wisata/20260722-260722052/mengunjungi-restoran-viral-dengan-konsep-timur-tengah-yang-menggugah-selera-di-jakarta',
 'https://food.detik.com/info-kuliner/d-8605565/restoran-steak-ini-viral-usai-tawarkan-pengalaman-makan-tanpa-busana',
 'https://food.detik.com/info-kuliner/d-8629954/viral-pelayan-restoran-padang-ahli-tebak-lauk-dari-sisa-piring-dan-kuah',
 'https://food.detik.com/info-kuliner/d-8606645/pemilik-restoran-ini-minta-orang-jangan-datang-malah-viral-dan-diserbu',
 'https://food.detik.com/foto-kuliner/d-8628943/burgernya-viral-aldi-taher-kini-punya-bisnis-kopi-dan-restoran-padang',
 'https://food.detik.com/info-kuliner/d-8571881/kritikus-makanan-bilang-ogah-masuk-restoran-dengan-5-ciri-ini',
 'https://food.detik.com/info-kuliner/d-8636676/pemilik-restoran-panik-dapat-pesan-makanan-terakhirku-dari-pelanggan',
 'https://food.detik.com/info-kuliner/d-8598461/viral-disebut-mirip-elon-musk-restoran-bbq-chef-ini-langsung-laris',
 'https://food.detik.com/info-kuliner/d-8552486/restoran-ini-viral-gegara-tambahkan-biaya-fifa-20-ternyata-ini-tujuannya',
 'https://food.detik.com/berita-boga/d-8626803/baru-tangga-viral-di-puncak-ini-mengarah-ke-restoran-indonesia-nilagiri',
 'https://rri.co.id/lhokseumawe/wisata/2765054/tingkatkan-pengamanan-objek-wisata-imbau-pengunjung-utamakan-keselamatan',
 'https://theconversation.com/akibat-kebelet-viral-tempat-wisata-potensial-kerap-layu-sebelum-berkembang-283129',
 'https://www.detik.com/bali/berita/d-8671285/wisata-berkuda-di-pererenan-berhenti-beroperasi-usai-viral-dugaan-eksploitasi',
 'https://yogyakarta.bpk.go.id/pad-wisata-kulon-progo-terkerek-3066-persen-di-2026-imbas-destinasi-viral-di-pantai-glagah-2/',
 'https://www.harapanrakyat.com/2026/09/pictniq-land-jogja-wisata-viral-keliling-dunia-dan-petualangan-offroad-di-perbukitan-gunungkidul/',
 'https://rentak.id/5-tempat-wisata-di-puncak-yang-lagi-viral-cocok-untuk-liburan-keluarga/',
 'https://jatim.antaranews.com/berita/1094615/disbudpar-spot-foto-viral-mirip-di-italia-dongkrak-wisata-sarangan',
 'https://www.suarasurabaya.net/kelanakota/2026/viral-di-media-sosial-bukan-jaminan-destinasi-wisata-bertahan-lama/',
 'https://www.dw.com/id/vietnam-disneyland-asia-siapa-yang-untung-dan-rugi-dari-pariwisata-viral/video-78261469',
 None,
 'https://www.facebook.com/medandailynews/videos/dugaan-praktik-pungutan-liar-pungli-di-kawasan-wisata-lau-debuk-debuk-kabupaten-/1003482995483706/',
 'https://rri.co.id/makassar/wisata/2739899/bendungan-kampili-kabupaten-gowa-jadi-wisata-viral',
 None,
 'https://www.suarasurabaya.net/kelanakota/2026/wawasan-polling-ss-mayoritas-masyarakat-mengaku-tidak-langsung-mengunjungi-tempat-wisata-yang-viral-di-medsos/',
 'https://www.detik.com/jateng/berita/d-8648775/sungai-juana-pati-jadi-wisata-dadakan-gegara-viral-ribuan-ikan-terdampar',
 'https://www.detik.com/jabar/wisata/d-8599649/3-jembatan-viral-di-ciamis-yang-cocok-jadi-destinasi-wisata',
 'https://20.detik.com/detikupdate/20260722-260722144/video-sungai-serayu-surut-warga-banyumas-buka-wisata-perahu-dadakan',
 None,
 'https://tv.sinpo.id/detail/wisata-bir-berkonsep-spbu-viral-di-qingdao',
 'https://travel.kompas.com/read/2026/04/19/171531127/wisata-viral-di-kebumen-pemandangan-laut-lepas-dari-ketinggian-bikin-betah',
 'https://papuatengah.tribunnews.com/jayapura/6209/usai-viral-di-tiktok-keindahan-bukit-krisna-jayapura-jadi-destinasi-wisata-ikonik-terbaru-di-papua',
 'https://www.detik.com/jabar/wisata/d-8492016/11-tempat-wisata-alam-jabar-paling-hits-di-media-sosial',
 'https://rri.co.id/bukittinggi/wisata/2503983/sedang-hits-ini-5-tempat-wisata-viral-di-indonesia-yang-wajib-dikunjungi',
 'https://www.kompasiana.com/471313/6a53b183c925c44fee3082d2/kabupaten-semarang-punya-tempat-wisata-yang-tak-kalah-hebat',
 'https://www.metrotvnews.com/read/b2lC6gd0-5-destinasi-wisata-keluarga-di-bogor-lengkap-beserta-harga-tiket-dan-aktivitasnya',
 'https://www.detik.com/sumbagsel/berita/d-8534410/viral-wisatawan-naik-gunung-anak-krakatau-bksda-bukan-destinasi-wisata',
 'https://www.detik.com/sumbagsel/wisata/d-8482740/17-tempat-wisata-favorit-di-lampung-yang-wajib-dikunjungi',
 'https://jogja.disway.id/wisata/read/699063/wisata-negeri-kahyangan-magelang-2026-destinasi-viral-di-lereng-merbabu-paling-menakjubkan',
 'https://travel.detik.com/domestic-destination/d-8508203/12-rekomendasi-tempat-wisata-keluarga-paling-hits-di-bogor-2026',
 'https://travel.tribunnews.com/destinasi/145805/5-tempat-wisata-di-wonosobo-yang-lagi-hits-indahnya-telaga-menjer',
 'https://travel.detik.com/travel-news/d-8500939/jangan-bingung-liburan-di-tangsel-ada-8-spot-wisata-menarik',
 'https://www.detik.com/jabar/wisata/d-8511873/desa-estetik-jadi-destinasi-wisata-hits-di-ciamis',
 'https://lahatpos.disway.id/topik-utama/read/662887/bukan-sekadar-keraton-5-tempat-wisata-terbaru-di-solo-yang-sedang-viral-dan-wajib-dikunjungi',
 'https://www.tripzilla.id/tempat-wisata-baru-bangkok-thailand/26990',
 'https://swa.co.id/read/471273/destinasi-wisata-baru-di-jogja-ini-6-hal-yang-ditawarkan-di-ibarbo-park',
 'https://nativeindonesia.com/mikutopia-batu/',
 'https://unikma.ac.id/2026/06/26/3-objek-wisata-terbaru-yang-paling-ramai-dikunjungi-di-cilacap/',
 'https://chanelmuslim.com/wisata/viral-canyoning-banyak-digemari-kalangan-muda-dan-jadi-destinasi-baru-di-bogor',
 'https://radarsukabumi.com/wisata/10-tempat-wisata-hits-di-sukabumi-2026-yang-wajib-masuk-bucket-list-kamu/',
 'https://www.detik.com/jatim/wisata/d-8429886/5-fakta-uji-coba-berbahaya-mikutopia-pengunjung-tewas-wahana-patah',
 'https://jogja.disway.id/wisata/read/699652/menjelajahi-kville-kaliurang-destinasi-viral-di-jogja-dengan-nuansa-eropa-yang-memukau',
 'https://radarmalang.jawapos.com/wisata-kuliner/2605150036/tempat-wisata-di-kota-malang-yang-lagi-viral-cocok-untuk-liburan-akhir-pekan']

## 5. Ekstraksi Informasi (Heuristik Regex)

- **Nama tempat**: diambil dari judul berita (bagian sebelum kata penghubung seperti "di", "-", dsb).
- **Lokasi**: dicari pola kata "Kelurahan/Kecamatan/Kabupaten/Kota/Provinsi ..." di teks artikel.
- **Sejak kapan viral**: dicari pola tanggal/bulan di teks, atau memakai tanggal publish berita sebagai perkiraan.
- **Kenapa viral**: kalimat yang memuat frasa "viral karena/usai/setelah/lantaran/gara-gara".

In [ ]:
MONTH_NAMES = (
    "januari|februari|maret|april|mei|juni|juli|agustus|september|oktober|november|desember"
)

LOC_PATTERN = re.compile(
    r"(Kelurahan|Kel\.)\s+([A-Z][\w\.\-]*(?:\s+[A-Z][\w\.\-]*){0,3})"
    r"|(Kecamatan|Kec\.)\s+([A-Z][\w\.\-]*(?:\s+[A-Z][\w\.\-]*){0,3})"
    r"|(Kabupaten|Kab\.|Kota)\s+([A-Z][\w\.\-]*(?:\s+[A-Z][\w\.\-]*){0,3})"
    r"|(Provinsi)\s+([A-Z][\w\.\-]*(?:\s+[A-Z][\w\.\-]*){0,3})"
)

VIRAL_SINCE_PATTERN = re.compile(
    rf"(\d{{1,2}}\s+(?:{MONTH_NAMES})\s+\d{{4}}|(?:{MONTH_NAMES})\s+\d{{4}})",
    re.IGNORECASE,
)

VIRAL_REASON_PATTERN = re.compile(
    r"([^.]*\bviral\b[^.]*(?:karena|usai|setelah|lantaran|gara-gara|akibat)[^.]*\.)",
    re.IGNORECASE,
)


def clean_place_candidate(candidate: str) -> str:
    """Ambil nama tempat sebelum deskripsi menu, harga, jam, atau lokasi."""
    candidate = re.sub(r"\s+", " ", candidate).strip(" -:;,\"'")
    candidate = re.split(
        r"\s+(?:yang|dengan|karena|berlokasi|beralamat|terletak|buka|mulai)\s+",
        candidate,
        maxsplit=1,
        flags=re.IGNORECASE,
    )[0]
    candidate = re.split(r"\s*[.!?]\s*|\s+[—–-]\s+|\s*:\s*", candidate, maxsplit=1)[0]
    candidate = re.split(r",\s*(?:harga|jam|mulai|tersedia|lokasi|alamat)\b", candidate, maxsplit=1, flags=re.IGNORECASE)[0]
    return candidate.strip(" -:;,\"'")


def extract_place_names(text: str) -> list[str]:
    """Ekstrak nama tempat dari marker daftar di awal paragraf atau baris."""
    if not isinstance(text, str) or not text.strip():
        return []

    matches = list(re.finditer(
        r"(?m)^\s*(?:\d{1,2}[.)]|[-•])\s+(.+?)\s*$",
        text,
        flags=re.IGNORECASE,
    ))
    if len(matches) < 2:
        return []

    rejected_terms = (
        "wib", "harga", "rp", "content writer", "copywriter", "baca juga",
        "pertahankan urutan", "daerah istimewa", "dikenal luas", "klik di sini",
        "jam buka", "minggu,", "sabtu,", "senin,", "selasa,", "rabu,",
        "kamis,", "jumat,", "diswayjogja",
    )
    candidates = []
    for match in matches:
        candidate = clean_place_candidate(match.group(1))
        lower_candidate = candidate.casefold()
        if not (3 <= len(candidate) <= 90):
            continue
        if any(term in lower_candidate for term in rejected_terms):
            continue
        if re.search(r"\b\d{1,2}:\d{2}\b|\b\d{1,2}\.\d{2}\b|\b\d{4}\b", candidate):
            continue
        if len(candidate.split()) > 12:
            continue
        candidates.append(candidate)

    unique_candidates = []
    seen = set()
    for candidate in candidates:
        key = candidate.casefold()
        if key not in seen:
            seen.add(key)
            unique_candidates.append(candidate)
    return unique_candidates


def extract_location_text(text: str) -> str:
    """Kumpulkan potongan teks lokasi yang ditemukan dari isi artikel."""
    found = []
    for match in LOC_PATTERN.finditer(text):
        groups = [group for group in match.groups() if group]
        if groups:
            found.append(" ".join(groups))
    seen = set()
    unique = []
    for location in found:
        if location not in seen:
            seen.add(location)
            unique.append(location)
    return "; ".join(unique)


def extract_viral_since(text: str, published) -> str:
    match = VIRAL_SINCE_PATTERN.search(text)
    if match:
        return match.group(1)
    if published is not None:
        return published.strftime("%B %Y") + " (perkiraan dari tanggal berita)"
    return ""


def extract_viral_reason(text: str) -> str:
    match = VIRAL_REASON_PATTERN.search(text)
    return match.group(1).strip() if match else ""


df_news["place_names"] = df_news["article_text"].apply(extract_place_names)
df_news = df_news[df_news["place_names"].map(bool)].drop(columns=["place_name"], errors="ignore").copy()
df_news = df_news.explode("place_names").rename(columns={"place_names": "place_name"}).reset_index(drop=True)
df_news["location_text"] = df_news["article_text"].apply(extract_location_text)
df_news["viral_since"] = df_news.apply(
    lambda row: extract_viral_since(row["article_text"], row["published"]), axis=1
)
df_news["viral_reason"] = df_news["article_text"].apply(extract_viral_reason)

print(f"Total tempat hasil ekstraksi dari isi artikel: {len(df_news)}")
df_news[["place_name", "location_text", "viral_since", "viral_reason"]].head(20)

Total tempat hasil ekstraksi dari isi artikel: 603

,place_name,location_text,viral_since,viral_reason
0,diswayjogja,Kota Purwokerto,September 2026 (perkiraan dari tanggal berita),
1,Dunia kuliner tradisional di Kota Purwokerto t...,Kota Purwokerto,September 2026 (perkiraan dari tanggal berita),
2,diswayjogja,Kota Purwokerto,September 2026 (perkiraan dari tanggal berita),
3,Dunia kuliner tradisional di Kota Purwokerto t...,Kota Purwokerto,September 2026 (perkiraan dari tanggal berita),
4,menghabiskan waktu,,July 2026 (perkiraan dari tanggal berita),
5,menghabiskan waktu,,July 2026 (perkiraan dari tanggal berita),
6,Jam Buka,,22 Mei 2026,
7,"Minggu, 10",,22 Mei 2026,
8,"Minggu, 09",,22 Mei 2026,
9,"Sabtu, 13",,22 Mei 2026,
10,"Minggu, 08",,22 Mei 2026,
11,Jam Buka,,22 Mei 2026,
12,"Minggu, 10",,22 Mei 2026,
13,"Minggu, 09",,22 Mei 2026,
14,"Sabtu, 13",,22 Mei 2026,
15,"Minggu, 08",,22 Mei 2026,
16,Jam Buka,,22 Mei 2026,
17,"Minggu, 10",,22 Mei 2026,
18,"Minggu, 09",,22 Mei 2026,
19,"Sabtu, 13",,22 Mei 2026,

## 6. Geocoding (Latitude, Longitude, Kelurahan, Kecamatan, Kota/Kab, Provinsi)

Memakai **Nominatim (OpenStreetMap)** dengan `RateLimiter` supaya tidak melanggar batas 1 request/detik dari kebijakan penggunaan Nominatim.

In [ ]:
geolocator = Nominatim(user_agent="riset_tempat_viral_indonesia")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1.1, max_retries=2, error_wait_seconds=2.0)
reverse = RateLimiter(geolocator.reverse, min_delay_seconds=1.1, max_retries=2, error_wait_seconds=2.0)


def geocode_place(place_name: str, location_hint: str):
    """Cari koordinat & detail alamat tempat. Coba dengan nama tempat + hint lokasi, fallback ke hint saja."""
    queries = []
    if location_hint:
        first_hint = location_hint.split(";")[0]
        queries.append(f"{place_name}, {first_hint}, Indonesia")
        queries.append(f"{first_hint}, Indonesia")
    queries.append(f"{place_name}, Indonesia")

    for q in queries:
        try:
            location = geocode(q, addressdetails=True, language="id", country_codes="id")
        except Exception:
            location = None
        if location:
            address = location.raw.get("address", {})
            return {
                "latitude": location.latitude,
                "longitude": location.longitude,
                "kelurahan": address.get("village") or address.get("suburb") or address.get("neighbourhood"),
                "kecamatan": address.get("city_district") or address.get("suburb"),
                "kota_kabupaten": address.get("city") or address.get("county") or address.get("town"),
                "provinsi": address.get("state"),
                "matched_query": q,
            }
    return {
        "latitude": None,
        "longitude": None,
        "kelurahan": None,
        "kecamatan": None,
        "kota_kabupaten": None,
        "provinsi": None,
        "matched_query": None,
    }


geo_results = []
for _, row in tqdm(df_news.iterrows(), total=len(df_news), desc="Geocoding"):
    geo_results.append(geocode_place(row["place_name"], row["location_text"]))

df_geo = pd.DataFrame(geo_results)
df_final = pd.concat([df_news.reset_index(drop=True), df_geo], axis=1)
df_final.head()

## 7. Rapikan & Simpan Hasil Akhir

In [ ]:
output_columns = [
    "place_name",
    "kelurahan",
    "kecamatan",
    "kota_kabupaten",
    "provinsi",
    "latitude",
    "longitude",
    "viral_since",
    "viral_reason",
    "location_text",
    "title",
    "source",
    "published",
    "final_url",
    "keyword",
]

df_result = df_final[output_columns].drop_duplicates(subset=["place_name", "final_url"]).reset_index(drop=True)

df_result.to_csv("tempat_viral_indonesia.csv", index=False, encoding="utf-8-sig")
df_result.to_excel("tempat_viral_indonesia.xlsx", index=False)

print(f"Total data akhir: {len(df_result)}")
df_result

## 8. Langkah Lanjutan (Opsional)

- Tambahkan sumber lain seperti RSS/API dari Detik, Kompas, Tribunnews, atau situs review kuliner (misal: pergikuliner, qraved) untuk memperkaya data.
- Ganti heuristik regex dengan model NER (misal spaCy/IndoBERT) untuk ekstraksi nama tempat & lokasi yang lebih akurat.
- Lakukan verifikasi manual pada kolom `viral_since` dan `viral_reason` karena hasil ekstraksi otomatis bisa kurang tepat pada kalimat yang kompleks.
- Jika butuh volume besar & akurasi geocoding tinggi, pertimbangkan Google Maps Geocoding API (berbayar, ada kuota gratis).